### ISSUE TITLE
config咋填？入参变量是啥呢？

### ISSUE THREAD

**Issue by litonchen** [zhayujie/chatgpt-on-wechat#1]

**Comment by zhayujie** [comment]
ChatGPT在加了cloudflare安全认证后，运行起来比较麻烦，就没有继续更新了，先看看有没有什么好的方案。

现在有图形界面的环境可以通过启动chrome来自动获取 cf_cookie，服务器部署的话暂时还没什么好办法
参考：https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by zhayujie** [comment]
已更新，暂时先使用OpenAI官方接口的方案
