### ISSUE TITLE
请问gpt4的模型测试过了吗？我的api支持gpt4，使用时model也改为了gpt-4，但总感觉他是调用的gpt3.5，和我直接curl调用api的回答完全不一样。

### ISSUE THREAD

**Issue by KicooG** [zhayujie/chatgpt-on-wechat#1003]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by KicooG** [comment]
![image](https://user-images.githubusercontent.com/20220490/235296756-e6f564bd-01ed-488d-8787-df970c6f7221.png)
![image](https://user-images.githubusercontent.com/20220490/235296777-d76c4a0b-0b57-46ef-a4b9-f9b5b75986cf.png)
model改为gpt-4-0314可以用了，填gpt-4是不行的。

**Comment by glsilover** [comment]
我的model改为“gpt-4”问答时，反馈还是gpt-3.5
![image](https://user-images.githubusercontent.com/60701203/235308745-c4963a20-4b05-4f1e-a0e7-47b4c95c1c84.png)

**Comment by KicooG** [comment]
这个回答可能不准确，你可以去官方的playground测试gpt4的回答对比看看。像我上面那个问题就可以区别4还是3.5

**Comment by glsilover** [comment]
> playground

感谢回复，我playground测试了一下，确实问“你是gpt-4还是gpt-3.5-turbo”这个问题的回复都一样。

我又测试了一些问题，发现“gpt-4”应该是已经生效了，给出的答案更接近playground的gpt-4，准确率更高

而且我从usage看了一下不同问题的回复消耗，当调整为“gpt-4”后，明显费用快速上涨（官网定价差15～30倍）

基于上述基本可以判定是支持gpt-4

**Comment by hutao562** [comment]
> > playground
> 
> 感谢回复，我playground测试了一下，确实问“你是gpt-4还是gpt-3.5-turbo”这个问题的回复都一样。
> 
> 我又测试了一些问题，发现“gpt-4”应该是已经生效了，给出的答案更接近playground的gpt-4，准确率更高
> 
> 而且我从usage看了一下不同问题的回复消耗，当调整为“gpt-4”后，明显费用快速上涨（官网定价差15～30倍）
> 
> 基于上述基本可以判定是支持gpt-4

就是看费用，错不了

**Comment by KicooG** [comment]
![image](https://user-images.githubusercontent.com/20220490/235330386-f3194980-9633-4dc2-aef4-9440abf65de8.png)
确实是支持的，上面是测试gpt-4的账单，后台显示都是走的gpt-4-0314模型，但确实回答的内容差异有点大

**Comment by Lingxiaocong** [comment]
我也改成gpt-4-0314现在可以了，这个token明显比gpt-3.5消耗的快了好多。。
![image](https://user-images.githubusercontent.com/56188690/236358233-3c8e7064-735f-4797-985c-c9b6398ae7ae.png)
