### ISSUE TITLE
Bot回复的结果和ChatGPT的Web端结果相比较过度拟合从而出现虚构，想知道哪些参数是可以控制的？

### ISSUE THREAD

**Issue by jinskanna** [zhayujie/chatgpt-on-wechat#1005]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

分别向微信机器人和ChatGPT发问“柳州好吃的螺蛳粉店有哪些”

机器人给的回复是70%虚构的店

### 问题描述 😯

![image](https://user-images.githubusercontent.com/20239634/235408721-f5c94358-26d3-4466-b071-b1edf296aca0.png)
![image](https://user-images.githubusercontent.com/20239634/235408865-4ee2ee44-7b56-4ad4-9dc8-926af1798366.png)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
复制这里https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py的配置项到config.json文件配置
![image](https://user-images.githubusercontent.com/38057450/235589821-7cee7c68-6220-4b10-bc14-9faf0130fdcf.png)

**Comment by jinskanna** [comment]
> 复制这里截图中的配置项到config.json文件配置，可以试试 https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py ![image](https://user-images.githubusercontent.com/38057450/235589821-7cee7c68-6220-4b10-bc14-9faf0130fdcf.png)

已經寫了，但是結果還是和web端的差距很大，我換了GPT-4也是一樣

**Comment by lanvent** [comment]
temperature改成0试试
