### ISSUE TITLE
用这个微信不是被封吗？

### ISSUE THREAD

**Issue by shiliu2023** [zhayujie/chatgpt-on-wechat#1006]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by 6vision** [comment]
个人微信是有这个可能的，现在项目支持企业微信了，可以玩玩，写了个详细教程包括railway部署：https://www.wangpc.cc/aigc/wechat_com-chatgpt/

**Comment by heyi-byte** [comment]
> 

但是企业微信只能对内，不能给外面的用户或者用户群访问

**Comment by KFC-vme-50** [comment]
我的个人微信小号没有被封，可能平时偶尔自己用，发发消息和表情包
