### ISSUE TITLE
RP画图插件可不可以加入一个先对中文翻译的处理逻辑呀

### ISSUE THREAD

**Issue by 6vision** [zhayujie/chatgpt-on-wechat#1007]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

有些model不支持或者对中文支持不友好，可以不可以先通过chatgpt吧prompt翻译为英文，再调用replicate

### 举例

调用rp插件，中文提示词，自动翻译为英文

### 动机

有些model不支持或者对中文支持不友好，可以不可以先通过chatgpt吧prompt翻译为英文，再调用replicate，这样就可以输入中文的提示词，更符合大多数人的使用习惯

**Comment by lanvent** [comment]
这个在`sdwebui`插件上支持了，等我有空改到`replicate`上

**Comment by lanvent** [comment]
replicate0.3 已支持

**Comment by taoguoliang** [comment]
![image](https://user-images.githubusercontent.com/28913539/236615322-e60de9bf-4170-4847-8448-3a17eb27fe8b.png)
请问下这个是啥原因，升级前后好像突然出现了，之前是好使的，已经卸载重装插件了也不行。

> replicate0.3 已支持

**Comment by lanvent** [comment]
这个是version不存在吧，去replicate检查下相关model跟version
