### ISSUE TITLE
企业微信发送消息报错

### ISSUE THREAD

**Issue by ywh888** [zhayujie/chatgpt-on-wechat#1009]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

企业微信发送消息报错

### 问题描述 😯

企业微信发送消息报错

### 终端日志 📒

```log
[INFO][2023-05-03 02:49:20][hello.py:23] - [Hello] inited
[INFO][2023-05-03 02:49:20][finish.py:23] - [Finish] inited
http://0.0.0.0:9898/
[INFO][2023-05-03 02:49:30][wechatcomapp_channel.py:145] - [wechatcom] receive params: <Storage {'nonce': '1683686759', 'msg_signature': 'ff00434b35ad97b4cbfd91b587c095b93de7ea50', 'timestamp': '1683053370'}>
183.47.98.227:24015 - - [03/May/2023 02:49:30] "HTTP/1.1 POST /wxcomapp" - 200 OK

```

**Comment by cheng-lf** [comment]
解决了吗？

**Comment by ywh888** [comment]
已解决



在 2023-05-12 18:26:17，"cheng-lf" ***@***.***> 写道：

解决了吗？

**Comment by hutao562** [comment]
>请问如何解决的?
