### ISSUE TITLE
能否@过一次，不用再@也能对话？

### ISSUE THREAD

**Issue by tenylu** [zhayujie/chatgpt-on-wechat#101]
### 问题描述

大佬能否实现@过一次，不用再@也能对话？超过15分钟没有对话，就要重新@。这样方式？

**Comment by Yan0789** [comment]
> ### 问题描述
> 大佬能否实现@过一次，不用再@也能对话？超过15分钟没有对话，就要重新@。这样方式？

对你这个提法表示认同，每次都要@才唤醒，或者去掉了代码的bot又完全是调用api数据，难受，改了的话体验可能更好

**Comment by Botreechan** [comment]
你关键字直接设置为小号的昵称就行了，就可以像群聊里艾特人一样长按发送

**Comment by tenylu** [comment]
> 

你说的，我们早就做了，重点还是每句都要艾特问题
