### ISSUE TITLE
回复无反应

### ISSUE THREAD

**Issue by Rubiadragon** [zhayujie/chatgpt-on-wechat#1010]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as K423
[INFO][2023-05-02 19:59:29][wechat_channel.py:124] - Wechat login success, user_id: @4c6f5f841ac0fdb20da4b470dd56ca93e1c49006bc2d544028fcd0f0108e7a51, nickname: K423
Start auto replying.

### 问题描述 😯

你好，我扫码成功了，同时也有Start auto replying，但是就是我用@bot或者群聊@没反应。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
请检查配置，是否在群聊白名单里

**Comment by lanvent** [comment]
消息触发词是否添加

**Comment by kscMaster** [comment]
我也遇到了这个问题，控制台可以收到微信发出的消息，但是没有回复
