### ISSUE TITLE
这个wechat的GPT能否接入互联网，让他可以实时同步呢？

### ISSUE THREAD

**Issue by Rubiadragon** [zhayujie/chatgpt-on-wechat#1011]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我已经配置成功了，但是里面的信息都是几年前的，我在想能否实现接入互联网。

**Comment by 6vision** [comment]
通过项目的tool插件可以利用bing等搜索工具搜索，模型本身训练的数据截至到2021，目前都是借助插件来实现联网
