### ISSUE TITLE
每次微信群里加入新成员时会自动发送欢迎消息，这个有没有开关可以关掉的？

### ISSUE THREAD

**Issue by SkyLifewood** [zhayujie/chatgpt-on-wechat#1013]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by congxuma** [comment]
#disablep hello

**Comment by SkyLifewood** [comment]
> #disablep hello

谢谢！

**Comment by minterjia** [comment]
#disablep hello 这个在哪
