### ISSUE TITLE
KeyError: 'wxsid'

### ISSUE THREAD

**Issue by suiyidela** [zhayujie/chatgpt-on-wechat#1016]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

新注册的账号扫码登录报KeyError: 'wxsid'
![image](https://user-images.githubusercontent.com/53991863/235970873-58c0b4a6-fb3f-45d6-8a8b-77536141539c.png)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by LittleTrue** [comment]
1、关闭代理-可能导致登录网页微信失败
2、查看微信是否进行实名认证
3、确认微信注册时间

2017年后，新注册的微信基本登录不了网页版，itchat-uos版本利用统信UOS的网页版微信，可以让你绕过网页微信的登录限制。

你只需要执行下条命令便能复活Itchat
pip3 unstall itchat
pip3 install itchat-uos==1.5.0.dev0

如果是容器部署, 则先运行以下命令进入容器后再执行以上命令:
docker exec -it sample-chatgpt-on-wechat/bin/bash 

最后, 祝你好运

**Comment by zhenda-hub** [comment]
必须要实名制才行吗？

**Comment by LittleTrue** [comment]
![image](https://user-images.githubusercontent.com/30282900/236124758-48b15e02-2c18-4e44-bffb-34da59e0dc2f.png)
因为我的场景是注册小号来弄, 而我的小号扫码登录网页版会出现以下情况, 最终换了个实名的老号通过了,  各位可以先去微信网页版, 扫码下看看自己的小号能不能正常登进去, 会不会出现以上提示, 会的话那这个号不能用

**Comment by shengzhou1216** [comment]
> 必须要实名制才行吗？

需要实名制。

**Comment by frank0828** [comment]
在railway一键部署的也出现这个问题了，请问怎么能解决呢？

**Comment by stellaye** [comment]
你的可能是被封号了
