### ISSUE TITLE
如何同时登录

### ISSUE THREAD

**Issue by tianchiguaixia** [zhayujie/chatgpt-on-wechat#1019]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

当我扫这个码登录时候，我微信电脑端就会退出。如何让电脑端微信和这个同时运行呢？

**Comment by congxuma** [comment]
这个原理就是模拟电脑端的登录，微信只能登录一个电脑端，不能让电脑端微信和这个同时运行
