### ISSUE TITLE
关于微信安全、网络通路的疑问

### ISSUE THREAD

**Issue by ziseyouyudefengzi** [zhayujie/chatgpt-on-wechat#102]
1、扫描二维码时，提示在其他地方登录网页版微信，这个“其它地方”指的是哪里登录的网页版微信呢？
2、如果走的是OPENAI的 API接口，是不是意味着这个要翻墙？那么这个网络翻墙是在哪设定的呢?   
3、另外就是这个接口是不是跟官方的Chat.OPENAI.COM用的模型不一样，不然网络的通路怎么解决的呢？

**Comment by zhayujie** [comment]
1.在你运行程序的机器上
2.不用翻墙，openai官方接口可以国内直接调用的
3.和官网提供的gpt3模型一样
