### ISSUE TITLE
问题比较长，超过了微信字数限制怎么办？

### ISSUE THREAD

**Issue by rklhxyk1128** [zhayujie/chatgpt-on-wechat#1020]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

RT，需要发送两段话才能发出完整的问题。 但是机器人每段话都会回复，导致回答的不准确，有什么好办法吗？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by KFC-vme-50** [comment]
你prompt的时候跟它说：犹豫字数限制，我将分段发送问题给你，当我说请开始回答的时候在进行回答。
