### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none) ERROR: No matching distribution found for azure-cognitiveservices-speech

### ISSUE THREAD

**Issue by LumingMelody** [zhayujie/chatgpt-on-wechat#1021]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我把 requirements-optional.txt里面的azure-cognitiveservices-speech注释了还是会安装这个库 然后报找不到这个库的错误信息 

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
可能是注释后没有保存，你可以删去这行试试

**Comment by kiddyyang** [comment]
> 可能是注释后没有保存，你可以删去这行试试

我用dock-compose构建也是同样的问题，删去那行也没用。直接pull了大神的这个镜像了ghcr.io/zhayujie/chatgpt-on-wechat:latest
