### ISSUE TITLE
可不可以通过Vercel部署

### ISSUE THREAD

**Issue by Dreamin121** [zhayujie/chatgpt-on-wechat#1023]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by lanvent** [comment]
暂无计划支持

**Comment by Kevin-free** [comment]
@Dreamin121 老哥用 vercel 部署成功了吗？我尝试了一下没成功 404

**Comment by RoyRao2333** [comment]
附议，希望大佬可以支持Vercel部署

**Comment by RoyRao2333** [comment]
附议，希望大佬可以支持Vercel部署

**Comment by xiaowuzicode** [comment]
附议，希望大佬可以支持Vercel部署
