### ISSUE TITLE
希望增加 open_ai_api_url, 用于国内的方向代理的 API接口.

### ISSUE THREAD

**Issue by online2311** [zhayujie/chatgpt-on-wechat#1024]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望增加 open_ai_api_url, 用于国内的方向代理的API接口。而不是 采用Proxy 的方式访问 OpenAI APi

**Comment by lanvent** [comment]
填写 ```open_ai_api_base```
