### ISSUE TITLE
Railway部署失败

### ISSUE THREAD

**Issue by eidev1** [zhayujie/chatgpt-on-wechat#1025]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

点击Deploy Now后，提示Looks like something went wrong and the train derailed

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
不了解，但目测不是项目的问题，请自行检查网络等环境
