### ISSUE TITLE
tool插件始终无法启用

### ISSUE THREAD

**Issue by wapscccs** [zhayujie/chatgpt-on-wechat#1026]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用最新的代码，也在插件目录中的plugins.json中配置了tool启用，也安装了所有依赖，但是依然无法启用tool插件，使用#help只能看到默认的两个插件
然后我尝试开启hello插件，是可以成功的，但是tool不管怎么折腾都不行

### 问题描述 😯

使用最新的代码，也在插件目录中的plugins.json中配置了tool启用，也安装了所有依赖，但是依然无法启用tool插件，使用#help只能看到默认的两个插件
然后我尝试开启hello插件，是可以成功的，但是tool不管怎么折腾都不行

**Comment by lanvent** [comment]
缺少启动log
