### ISSUE TITLE
gpt4.0 api  出错

### ISSUE THREAD

**Issue by s9450236139** [zhayujie/chatgpt-on-wechat#1027]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

conversation_max_tokens=1000
expires_in_seconds=3600
group_chat_in_one_session=["ALL_GROUP"]
group_chat_prefix=["@bot"]
group_name_white_list=["ALL_GROUP"]
group_speech_recognition=True
image_create_prefix=["画", "看", "找"]
model=gpt-4
open_ai_api_key=sk-lXYnfzJkfbTE8iOxxxxxxxxxxxxxxxxxxxxxxxx
single_chat_prefix=[""]
single_chat_reply_prefix=""
speech_recognition=True
voice_reply_voice=True

### 问题描述 😯

今天拿到gpt 4.0 api 用railway部署，填入api 将模式改为gpt-4，与机器人对话一直报错，说我累了。本人小白一枚，仅能反应现象，请大神查看！

conversation_max_tokens=1000
expires_in_seconds=3600
group_chat_in_one_session=["ALL_GROUP"]
group_chat_prefix=["@bot"]
group_name_white_list=["ALL_GROUP"]
group_speech_recognition=True
image_create_prefix=["画", "看", "找"]
model=gpt-4
open_ai_api_key=sk-lXYnfzJkfbTE8iOxxxxxxxxxxxxxxxxxxxxxxxx
single_chat_prefix=[""]
single_chat_reply_prefix=""
speech_recognition=True
voice_reply_voice=True

### 终端日志 📒

```log
<此处粘贴终端日志>
```conversation_max_tokens=1000
expires_in_seconds=3600
group_chat_in_one_session=["ALL_GROUP"]
group_chat_prefix=["@bot"]
group_name_white_list=["ALL_GROUP"]
group_speech_recognition=True
image_create_prefix=["画", "看", "找"]
model=gpt-4
open_ai_api_key=sk-lXYnfzJkfbTE8iOxxxxxxxxxxxxxxxxxxxxxxxx
single_chat_prefix=[""]
single_chat_reply_prefix=""
speech_recognition=True
voice_reply_voice=True

**Comment by lanvent** [comment]
一般是因为没有使用gpt-4 api的权限

**Comment by Payne-Wang** [comment]
这个问题我遇到过，你需要把原来3.5的api删掉，然后重新生成一个api，再使用就没问题了
