### ISSUE TITLE
gpt接入微信时自动回复的是[我现在有点累了，等会再来吧】

### ISSUE THREAD

**Issue by 1452534914** [zhayujie/chatgpt-on-wechat#1029]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

![mmexport1683318514548](https://user-images.githubusercontent.com/119047908/236562618-dc5ab4b4-1209-4caf-aa45-08d01592059c.jpg)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
检查代理是否设置错误
