### ISSUE TITLE
安装依赖失败：subprocess-exited-with-error setuptools已经安装，但子进程找不到

### ISSUE THREAD

**Issue by CatcherX** [zhayujie/chatgpt-on-wechat#1030]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

执行：`pip3 install -r requirements-optional.txt --proxy http://127.0.0.1:7890`

### 问题描述 😯

输出：
`Looking in indexes: https://pypi.org/simple, https://pypi.python.org/simple
Requirement already satisfied: tiktoken>=0.3.2 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from -r requirements-optional.txt (line 1)) (0.3.3)
Requirement already satisfied: pydub>=0.25.1 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from -r requirements-optional.txt (line 4)) (0.25.1)
Collecting SpeechRecognition (from -r requirements-optional.txt (line 5))
  Using cached SpeechRecognition-3.10.0-py2.py3-none-any.whl (32.8 MB)
Collecting gTTS>=2.3.1 (from -r requirements-optional.txt (line 6))
  Using cached gTTS-2.3.2-py3-none-any.whl (28 kB)
Collecting pyttsx3>=2.90 (from -r requirements-optional.txt (line 7))
  Using cached pyttsx3-2.90-py3-none-any.whl (39 kB)
Collecting baidu_aip>=4.16.10 (from -r requirements-optional.txt (line 8))
  Using cached baidu_aip-4.16.10-py3-none-any.whl (29 kB)
Collecting azure-cognitiveservices-speech (from -r requirements-optional.txt (line 9))
  Using cached azure_cognitiveservices_speech-1.28.0-py3-none-win_amd64.whl (1.5 MB)
Collecting numpy<=1.24.2 (from -r requirements-optional.txt (line 10))
  Using cached numpy-1.24.2-cp38-cp38-win_amd64.whl (14.9 MB)
Collecting langid (from -r requirements-optional.txt (line 11))
  Using cached langid-1.1.6.tar.gz (1.9 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Looking in indexes: https://pypi.org/simple, https://pypi.python.org/simple
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

尝试过单独安装：chatgpt_tool_hub
`
>pip3 install chatgpt_tool_hub==0.4.3 --no-cache-dir --proxy http://127.0.0.1:7890
Collecting chatgpt_tool_hub==0.4.3
  Downloading chatgpt_tool_hub-0.4.3-py2.py3-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 189.9 kB/s eta 0:00:00
Collecting pydantic~=1.10.7 (from chatgpt_tool_hub==0.4.3)
  Downloading pydantic-1.10.7-cp38-cp38-win_amd64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.9 MB/s eta 0:00:00
Collecting pyopenssl (from chatgpt_tool_hub==0.4.3)
  Downloading pyOpenSSL-23.1.1-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: pyyaml~=6.0 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from chatgpt_tool_hub==0.4.3) (6.0)
Collecting lxml (from chatgpt_tool_hub==0.4.3)
  Downloading lxml-4.9.2-cp38-cp38-win_amd64.whl (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 5.8 MB/s eta 0:00:00
Collecting beautifulsoup4~=4.12.0 (from chatgpt_tool_hub==0.4.3)
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 4.1 MB/s eta 0:00:00
Collecting tenacity~=8.2.2 (from chatgpt_tool_hub==0.4.3)
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
Requirement already satisfied: openai~=0.27.2 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from chatgpt_tool_hub==0.4.3) (0.27.2)
Requirement already satisfied: tiktoken~=0.3.2 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from chatgpt_tool_hub==0.4.3) (0.3.3)
Collecting arxiv (from chatgpt_tool_hub==0.4.3)
  Downloading arxiv-1.4.7-py3-none-any.whl (12 kB)
Collecting wikipedia (from chatgpt_tool_hub==0.4.3)
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

### 终端日志 📒

环境描述：
`
> python --version
Python 3.8.0

pip --version
pip 23.1.2 from c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

pip3 --version
pip 23.1.2 from c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

>pip list
Package            Version
------------------ ------------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              23.1.0
certifi            2022.12.7
cfgv               3.3.1
chardet            5.1.0
charset-normalizer 3.1.0
colorama           0.4.6
distlib            0.3.6
filelock           3.12.0
frozenlist         1.3.3
HTMLParser         0.0.2
identify           2.5.24
idna               3.4
multidict          6.0.4
nodeenv            1.7.0
openai             0.27.2
Pillow             9.5.0
pip                23.1.2
platformdirs       3.5.0
pre-commit         3.3.1
pydub              0.25.1
pypng              0.20220715.0
PyQRCode           1.2.1
PyYAML             6.0
qrcode             7.4.2
regex              2023.5.5
requests           2.30.0
setuptools         40.8.0
tiktoken           0.3.3
tqdm               4.65.0
typing_extensions  4.5.0
urllib3            2.0.2
virtualenv         20.23.0
yarl               1.9.2`

**Comment by CatcherX** [comment]
>拓展依赖 (可选，建议安装)：pip3 install -r requirements-optional.txt
这个确实是可选的？安装不完整，执行：python .\app.py 时报错了。如下：
[ERROR][2023-05-06 12:19:44][plugin_manager.py:91] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'

**Comment by lanvent** [comment]
依赖问题请使用搜索引擎工具解决，不安装可选依赖也能进行基本的文字回复
