### ISSUE TITLE
能否调优一下总结插件的prompts

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#1031]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

能否调优一下总结插件的prompts ，我看了一下代码，现在是先分段总结，再整合每个分段总结的内容再进行总结，这样效果不是太好，能否调优一下做整体的总结，设一个最大消息数就行了，4000的token大部分情况下都扛得住总结200条以内的消息的，太短的分段总结后整合再总结，效果不是很好

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
消息数太多时才会分段总结
