### ISSUE TITLE
参考楼主的banwords，做了个基于bing 搜索的插件，请问怎么提交到插件仓库，亲测可以运行

### ISSUE THREAD

**Issue by hellangleZ** [zhayujie/chatgpt-on-wechat#1035]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

![1683367408421](https://user-images.githubusercontent.com/15274284/236617604-7f63b851-19de-4c40-b231-8643cfe120b7.png)

### 举例

就是调用bing的api

### 动机

也想对这个项目做一点绵薄的贡献

**Comment by Maddaxman** [comment]
可以可以 求pr

**Comment by Maddaxman** [comment]
应该是这里
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/31379908/236618630-8022afbe-33b4-4847-81b7-b2690f10d127.png">

**Comment by lanvent** [comment]
tool插件支持bing搜索了吧，目前仓库不支持新加插件了，欢迎自建仓库，提交你的仓库地址至https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/source.json

**Comment by Li-Eternally** [comment]
兄弟你可以打包成链接分享出来😁

**Comment by Maddaxman** [comment]
> tool插件支持bing搜索了吧，现在仓库不接受新加插件了，欢迎自建仓库，然后发起PR提交你的仓库地址至https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/source.json

tool 插件的bing搜索并不好用

**Comment by LaojiJava** [comment]
这个感觉不错，我应该如何才能使用  我现在这个tool遇到的问题太多了  我应该在哪个issues得到帮助？

**Comment by hellangleZ** [comment]
我这个得输入bing的api 和密码才可以

**Comment by zhenda-hub** [comment]
厉害

**Comment by byYufeng** [comment]
已经提交整合进去了吗？找了半天没找到在哪安装
