### ISSUE TITLE
企业微信是否已经支持机器人主动给用户发送信息？（现在大部分场景是机器人被动响应用户信息），如果不支持，是否有考虑加入这个能力？

### ISSUE THREAD

**Issue by hellosmarter** [zhayujie/chatgpt-on-wechat#1036]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

企业微信是否已经支持机器人主动给用户发送信息？（现在大部分场景是机器人被动响应用户信息），如果不支持，是否有考虑加入这个能力？

### 举例

暂无

### 动机

企业微信是否已经支持机器人主动给用户发送信息？（现在大部分场景是机器人被动响应用户信息），如果不支持，是否有考虑加入这个能力？有些场景需要机器人主动给用户发送信息，比如提醒等等

**Comment by hellosmarter** [comment]
@lanvent 帮忙看看这个，谢谢

**Comment by lanvent** [comment]
不了解，暂无计划，欢迎翻阅企业微信开发者文档和PR
