### ISSUE TITLE
希望能加入触发关键词来使用语音回复的功能

### ISSUE THREAD

**Issue by TLMEMO** [zhayujie/chatgpt-on-wechat#1041]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我读了配置文件，发现似乎要使用语音回复功能要么打开voice_reply_voice，要么使用always_reply_voice，这有些不方便所以说可否加入一个设定关键词，然后使用语音回复的功能？比如说@bot -v test ,检测到"-v"这个关键字就使用语音来回复，而如果只是@bot test则使用文字来回复。

**Comment by newbee2012** [comment]
我已经实现了此功能，跟聊天时跟机器人表达出“语音”的意图，机器人就会用语音回复。表达出“文字”的意图就可以用文字回复。甚至可以很隐晦的表达意图，比如：“我现在正在开车，不方便看文字。”

**Comment by lanvent** [comment]
楼上想法很好，用插件实现挺好的，让chatgpt先确定你的意图决定是否回复声音。 关键字识别也能通过自己实现插件实现，但不建议加入到主程序，因为这类需求并不普遍

**Comment by newbee2012** [comment]
嗯，目前为了省事，我是直接修改的主程序，可以考虑用插件来实现，确实更合适。

**Comment by fatwang2** [comment]
@newbee2012 请问你是怎么改的呀

**Comment by He0607** [comment]
@newbee2012 请问是如何更改的呀可以提供一下吗
