### ISSUE TITLE
增加tool类型后，是否可以不退出微信，通过热重载生效？

### ISSUE THREAD

**Issue by CatcherX** [zhayujie/chatgpt-on-wechat#1044]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

例如：
 "tools": [
    "python",
    "url-get",
    "meteo-weather",
    "bing-search",
"新增XXXX"
  ],

**Comment by lanvent** [comment]
试一试#reloadp tool 命令
