### ISSUE TITLE
免费开源微软edge-tts 语音合成项目

### ISSUE THREAD

**Issue by joe12801** [zhayujie/chatgpt-on-wechat#1047]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

完全免费的 基于edge浏览器 逆向开发的语音合成。功能已经和音色和Azure一模一样 。
https://github.com/rany2/edge-tts
可以将此接入。接入微信公众号中。已经有其它项目公众号接入。具体参考下面的项目
公众号
<img width="281" alt="8bfd3164aff457a4b57db83d4dfdd7e" src="https://user-images.githubusercontent.com/70465495/236719047-de5bc2b5-5236-4f73-97bc-f040d194afa7.png">

https://github.com/ToryPan/ChatGPT_WeChat

### 举例

https://github.com/rany2/edge-tts

### 动机

https://github.com/rany2/edge-tts

**Comment by xtremcer** [comment]
期待 微软的自然语言音色不错

**Comment by uxfion** [comment]
可以参考一下这个PR https://github.com/zhayujie/chatgpt-on-wechat/pull/1787

**Comment by kuangdd2024** [comment]
这个项目把azure的tts改成了edge-tts，免费的语音合成。

项目：
https://github.com/kuangdd2024/wechatgpt-agent

About：
chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。
