### ISSUE TITLE
新微信号扫码提示KeyError: 'wxsid'

### ISSUE THREAD

**Issue by wangpeilin** [zhayujie/chatgpt-on-wechat#1049]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

python3 app.py
微信扫码

### 问题描述 😯

运行python3 app.py后出现二维码，用新注册的二维码扫描后提示 KeyError: 'wxsid'，查了一下大家说老微信号才能登录，新微信号不行，想问下这个问题能解决吗？老微信号是自己用的不能用来做这个机器人

### 终端日志 📒

```log
core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```

**Comment by CHENEY-LANCE** [comment]
我也是这个问题，我是通过Railway部署的，老微信可以，新微信不可以。我在网上找了下 有个解决办法，我这边没试过（正在研究Railway，看能不能进容器修改）：
版本是否为 1.5.0.dev0，不是的话是先卸载itchat，然后安装itchat-uos 1.5.0.dev0版本。

**Comment by lanvent** [comment]
itchat-uos 1.5.0.dev0 内置的就是这个版本。 绑定银行卡实名认证下吧

**Comment by frank0828** [comment]
> itchat-uos 1.5.0.dev0 内置的就是这个版本。 绑定银行卡实名认证下吧

我是新注册的账户，实名制了，前几天一直能登录，今天突然就不行，显示的也是这个错误，用railway一键部署的，请问怎么办呢？

**Comment by lanvent** [comment]
尝试下手机微信能正常上吗，银行卡能点开吗

**Comment by frank0828** [comment]
> 尝试下手机微信能正常上吗，银行卡能点开吗

登录正常，银行卡正常，但是我手动发了个信息，发送失败了，提示“发送信息过于频繁，可稍后再试”，

**Comment by lanvent** [comment]
手机微信重新登陆一下，应该是被官方限制了

**Comment by ilyzoro** [comment]
应该是微信的限制，我也碰到同样的问题，网页版微信也会无法登陆

**Comment by xxfeng2016** [comment]
相同问题. 谁有接近办法.

**Comment by shotforsky** [comment]
我遇到这个问题时使用的微信号没有实名认证，在实名认证微信号后这个问题解决了

**Comment by hooligan520** [comment]
我也碰到这个问题了，前面几天用到好好的，今天突然就掉线了，然后机器人再也登录不上了
手机上可以登录，也实名了，但是只能接收消息，不能发送消息，一发送消息就提示“发送信息过于频繁，可稍后再试"

**Comment by xxfeng2016** [comment]
由于itchat,是基于web协议,而新注册的微信号,不能web版本微信登录. 才出这个错误.
无解!!
这个项目,基本上,这样下去就是死路了.

**Comment by zhayujie** [comment]
项目用的是 itchat-uos ， 是桌面客户端协议， web登录不上去不影响项目使用， 报这个错是因为被微信限制了 发送消息， 可以在 微信安全中心点击 查询/解除账号功能限制 看看

**Comment by tomfortheking** [comment]
微信被封号了，是项目的问题吗，你们有用模拟器或者有其他违规操作吗

**Comment by xxfeng2016** [comment]
目前不清楚,微信已经解封了.


我再试试.
















在 2023-05-13 13:18:30，"tomfortheking" ***@***.***> 写道：

微信被封号了，是项目的问题吗，你们有用模拟器或者有其他违规操作吗

**Comment by xxfeng2016** [comment]
有兄弟说,用的不是网页版协议


如果你开启voice_reply_voice


语音回复后,Android收到的是一个mp3.提示的是,微信网页版,发送来的文件.


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年05月13日 23:58 |
| 收件人 | ***@***.***> |
| 主题 | Re:Re: [zhayujie/chatgpt-on-wechat] 新微信号扫码提示KeyError: 'wxsid' (Issue #1049) |
目前不清楚,微信已经解封了.


我再试试.
















在 2023-05-13 13:18:30，"tomfortheking" ***@***.***> 写道：

微信被封号了，是项目的问题吗，你们有用模拟器或者有其他违规操作吗

**Comment by wunuo1** [comment]
我实名认证后就可以了

**Comment by zwm88** [comment]
> “发送信息过于频繁，可稍后再试"

才玩了几下，就这样了。怎么解？解冻微信号说不能自助解冻。

**Comment by frank0828** [comment]
目前来看是没有办法解决了，而且和几个技术讨论了一下，目前也是无解，这是wx内部的事，咱们没什么好办法，只能是多加几个好友帮助做解封

**Comment by zwm88** [comment]
还好，过了段时间，用冻结的账号发了个消息，提示信息变成你的账号暂时无法使用聊天功能，轻触了解详情，点了解详情一步步再通过人脸识别就解冻了。

查看log发现可能导致账号冻结的原因，就是OpenAI试用的版本一分钟只能发三次gpt-turbo-3.5的请求，在使用$tool的时候插件似乎重复发送了好几个请求，导致错误：requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.  然后程序异常后可能对微信服务器发送了莫名的数据导致被微信ban了。

**Comment by kilonewzh** [comment]
应该跟老微信无关？我老微信扫码登录一样报这个错

**Comment by S-pyder** [comment]
> 项目用的是 itchat-uos ， 是桌面客户端协议， web登录不上去不影响项目使用， 报这个错是因为被微信限制了 发送消息， 可以在 微信安全中心点击 查询/解除账号功能限制 看看

同样的问题，按照这个去查了下，显示 ’账号状态正常，可完整使用微信‘

**Comment by JustinChia** [comment]
确实是，我是一个新号，在支付里实名认证一下就好了，感谢

> > 项目用的是 itchat-uos ， 是桌面客户端协议， web登录不上去不影响项目使用， 报这个错是因为被微信限制了 发送消息， 可以在 微信安全中心点击 查询/解除账号功能限制 看看
> 
> 同样的问题，按照这个去查了下，显示 ’账号状态正常，可完整使用微信‘；然后我尝试了下完成实名认证，，就可以登录了。

**Comment by xukongkkkk** [comment]
同实名晚就可以了

> 确实是，我是一个新号，在支付里实名认证一下就好了，感谢
> 
> > > 项目用的是 itchat-uos ， 是桌面客户端协议， web登录不上去不影响项目使用， 报这个错是因为被微信限制了 发送消息， 可以在 微信安全中心点击 查询/解除账号功能限制 看看
> > 
> > 
> > 同样的问题，按照这个去查了下，显示 ’账号状态正常，可完整使用微信‘；然后我尝试了下完成实名认证，，就可以登录了。

**Comment by MisakiYuuo** [comment]
我在一台服务器上部署了两个微信,第二个就是会报这个错误,不知道怎么解决.
