### ISSUE TITLE
配置完成，手机端不显示

### ISSUE THREAD

**Issue by Cristal-yin** [zhayujie/chatgpt-on-wechat#105]
已经配置完成，并到了Start auto replying. 这一步，但是微信没对话框

**Comment by ChunlinYu** [comment]
+1

**Comment by zhayujie** [comment]
微信需要发送带关键字的消息来触发

**Comment by haosechongzi** [comment]
已经发了关键字，在终端上能看到回复了，但是无法在微信里显示，怎么破？

**Comment by amaozhao** [comment]
> 

+1 同样终端显示内容，但是微信里不显示

**Comment by zhayujie** [comment]
@amaozhao @haosechongzi 

终端显示，wx不显示， 可能是被wx限制了
