### ISSUE TITLE
群名是emoji怎么添加白名单

### ISSUE THREAD

**Issue by FFF7674** [zhayujie/chatgpt-on-wechat#1051]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

emm，，我不知道python版本和chatgpt-on-wechat版本，，

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
json文件里面应该可以粘贴emoji的，复制下群名试试。另一个方法是加入下面这个配置项，群名若包含关键词就会开启回复。

 "group_name_keyword_white_list": ["测试群"],  # 开启自动回复的群名称关键词列表

**Comment by FFF7674** [comment]
好吧。我发现之前不回复不是因为emoji和白名单的关系。。好像是因为"group_chat_prefix": [""]的前缀必须要有字。我试了“”里面没字就不会回复。。话说怎么样可以让它像"single_chat_prefix": [""]不需要前缀触发？我 "group_at_off": true 和"group_chat_prefix": [""] 不行前缀没东西它就不回复。。

**Comment by lanvent** [comment]
我试是可以的， "group_chat_prefix": [""],

**Comment by FFF7674** [comment]
为啥我不行啊。。但我换了个部署方式就可以了。。
