### ISSUE TITLE
修改config.json后，可否热重载，即不用重新登录微信

### ISSUE THREAD

**Issue by CatcherX** [zhayujie/chatgpt-on-wechat#1053]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望修改配置后，通过特定指定重新获取新值。现在貌似要重新登录微信。

### 举例

"group_chat_prefix": [
    ".","aa","bb"
  ],

例如修改该配置

### 动机

调试过程经常会改参数值，频繁的登录退出微信，容易触发微信封号机制

**Comment by lanvent** [comment]
```
[INFO]
通用指令：
#help : 回复此帮助
#help 插件名: 回复指定插件的详细帮助
#set_openai_api_key api_key: 设置你的OpenAI私有api_key
#reset_openai_api_key : 重置为默认的api_key
#reset : 重置会话

目前可用插件有：
tool:这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
角色扮演:让机器人扮演不同的角色。
replicate:利用replicate api来画图。
文字冒险:可以和机器人一起玩文字冒险游戏。
summary:聊天记录总结插件。

管理员指令：
#resume : 恢复服务
#stop : 暂停服务
#reconf : 重载配置(不包含插件配置)
#resetall : 重置所有会话
#scanp : 扫描插件目录是否有新插件
#plist : 打印当前插件列表
#setpri 插件名 优先级: 设置指定插件的优先级，越大越优先
#reloadp 插件名: 重载指定插件配置
#enablep 插件名: 启用指定插件
#disablep 插件名: 禁用指定插件
#installp 仓库地址或插件名: 安装指定插件
#uninstallp 插件名: 卸载指定插件
#updatep 插件名: 更新指定插件
#debug : 开启机器调试日志
```

**Comment by CatcherX** [comment]
> ```
> [INFO]
> 通用指令：
> #help : 回复此帮助
> #help 插件名: 回复指定插件的详细帮助
> #set_openai_api_key api_key: 设置你的OpenAI私有api_key
> #reset_openai_api_key : 重置为默认的api_key
> #reset : 重置会话
> 
> 目前可用插件有：
> tool:这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
> 角色扮演:让机器人扮演不同的角色。
> replicate:利用replicate api来画图。
> 文字冒险:可以和机器人一起玩文字冒险游戏。
> summary:聊天记录总结插件。
> 
> 管理员指令：
> #resume : 恢复服务
> #stop : 暂停服务
> #reconf : 重载配置(不包含插件配置)
> #resetall : 重置所有会话
> #scanp : 扫描插件目录是否有新插件
> #plist : 打印当前插件列表
> #setpri 插件名 优先级: 设置指定插件的优先级，越大越优先
> #reloadp 插件名: 重载指定插件配置
> #enablep 插件名: 启用指定插件
> #disablep 插件名: 禁用指定插件
> #installp 仓库地址或插件名: 安装指定插件
> #uninstallp 插件名: 卸载指定插件
> #updatep 插件名: 更新指定插件
> #debug : 开启机器调试日志
> ```

请问要怎么使用的？
我的使用情况：

发送：$reconf

收到：
[ERROR]
未知插件命令
查看插件命令列表请输入#help 插件名

**Comment by zhaoxitao** [comment]
> > ```
> > [INFO]
> > 通用指令：
> > #help : 回复此帮助
> > #help 插件名: 回复指定插件的详细帮助
> > #set_openai_api_key api_key: 设置你的OpenAI私有api_key
> > #reset_openai_api_key : 重置为默认的api_key
> > #reset : 重置会话
> > 
> > 目前可用插件有：
> > tool:这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
> > 角色扮演:让机器人扮演不同的角色。
> > replicate:利用replicate api来画图。
> > 文字冒险:可以和机器人一起玩文字冒险游戏。
> > summary:聊天记录总结插件。
> > 
> > 管理员指令：
> > #resume : 恢复服务
> > #stop : 暂停服务
> > #reconf : 重载配置(不包含插件配置)
> > #resetall : 重置所有会话
> > #scanp : 扫描插件目录是否有新插件
> > #plist : 打印当前插件列表
> > #setpri 插件名 优先级: 设置指定插件的优先级，越大越优先
> > #reloadp 插件名: 重载指定插件配置
> > #enablep 插件名: 启用指定插件
> > #disablep 插件名: 禁用指定插件
> > #installp 仓库地址或插件名: 安装指定插件
> > #uninstallp 插件名: 卸载指定插件
> > #updatep 插件名: 更新指定插件
> > #debug : 开启机器调试日志
> > ```
> 
> 请问要怎么使用的？ 我的使用情况：
> 
> 发送：$reconf
> 
> 收到： [ERROR] 未知插件命令 查看插件命令列表请输入#help 插件名

管理员命令是 # 开头的，$ 开头是插件。

所以你要用命令 #reconf 而不是 $reconf

仔细看文档是个好习惯😊
