### ISSUE TITLE
企业微信人格描述不起作用，还是默认的

### ISSUE THREAD

**Issue by ywh888** [zhayujie/chatgpt-on-wechat#1054]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows Subsystem for Linux (WSL)

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

企业微信人格描述作用，还是默认的

### 问题描述 😯

企业微信人格描述作用，还是默认的

### 终端日志 📒

```log
企业微信人格描述作用，还是默认的
```

**Comment by Namarimizu** [comment]
群里的人格好像也比较默认……

**Comment by Namarimizu** [comment]
对了，群里用role插件的效果和私聊也不一样：比如猫娘人格，群聊就会把格式设定里的「语言“”」一并讲出来，私聊就不会（但是私聊又很少有方括号）

**Comment by lanvent** [comment]
是有用的，换用不同system prompt试试吧。 群聊和私聊其实是一样的。
