### ISSUE TITLE
我在群聊中生成的图片没有视频演示的清晰

### ISSUE THREAD

**Issue by FFFKLD** [zhayujie/chatgpt-on-wechat#1056]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我在群聊中生成的图片清晰度很低，请问如何解决，没有达到要求的8K，token数设置到9000也没有效果

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
请问是使用了replicate插件了么？可否截图看看后台信息？

**Comment by FFFKLD** [comment]
> 请问是使用了replicate插件了么？可否截图看后台信息？

![image](https://user-images.githubusercontent.com/73410320/236997818-5caea081-2bea-4f3f-a966-53e906a9133a.png)
是的，用的railway一键部署，显示安装插件成功，但是实际上无法使用，#plist列表中也没有找到replicate，也把Replicate的api token 加入环境变量了
![image](https://user-images.githubusercontent.com/73410320/236998130-37c689dc-6adf-435d-921f-8a75f828689d.png)

**Comment by lanvent** [comment]
安装失败是因为镜像出现了权限问题，今天晚些时候我会修复

**Comment by lanvent** [comment]
fixed in 1.3.0.2
