### ISSUE TITLE
微信不触发自动回复

### ISSUE THREAD

**Issue by longdian** [zhayujie/chatgpt-on-wechat#1057]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我这个日志有 我自己给自己发也可以 但是微信没有自动回复 还有群聊中被人@我 或者我@自己 都不触发日志 严格按照single_chat_prefix group_chat_prefix 跟

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
自行检查配置

https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py 这里包含了可选的配置项，填写到config.json中
