### ISSUE TITLE
微软已经放开网页版 Copilot，会把这个整合到项目里面吗

### ISSUE THREAD

**Issue by lidalifan** [zhayujie/chatgpt-on-wechat#1059]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

微软已经放开网页版 Copilot，会把这个整合到项目里面吗

### 动机

多元化发展

**Comment by lanvent** [comment]
暂无计划
