### ISSUE TITLE
当前账号无法使用该服务

### ISSUE THREAD

**Issue by MINGJING-WU** [zhayujie/chatgpt-on-wechat#106]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

扫描QR-Code之后显示当前账号无法使用该服务

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python3 -V` )：3.10

**Comment by MINGJING-WU** [comment]
> ### 前置确认
> 1. 运行于国内网络环境，未开代理
> 2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
> 3. 在已有 issue 中未搜索到类似问题
> 4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
> 
> ### 问题描述
> > 简要说明、截图、复现步骤等，也可以是需求或想法
> 
> 扫描QR-Code之后显示当前账号无法使用该服务
> 
> * 操作系统类型  (Mac/Windows/Linux)：Windows
> * Python版本  ( 执行 `python3 -V` )：3.10

感觉是因为原本登陆上去是用国内手机号注册的微信，现在报这个错误是因为改成国外手机号之后，就变成WeChat登陆不上去了

**Comment by zhayujie** [comment]
see #24 ，  国内手机号注册的微信应该不会报这个错， 有实名认证吗

**Comment by MINGJING-WU** [comment]
已经接收，我会尽量快点看的，谢谢
