### ISSUE TITLE
列表和字符串直接连接，导致无法获取变量

### ISSUE THREAD

**Issue by dhmgws10000** [zhayujie/chatgpt-on-wechat#1060]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Other (请在问题中说明)

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

ubuntu 20.0.4 系统
1.微信用户正常对话

### 问题描述 😯

![image](https://user-images.githubusercontent.com/53589027/237062830-1ac55188-8e7f-4456-abd1-8a4b4e3fb9d0.png)
连接列表和字符串相关的代码中存在错误。
在文件_decorate_reply的方法中chat_channel.py，reply_text变量与 连接在一起conf().get("single_chat_reply_prefix", "")，这是一个列表，而不是字符串。
我本地修复这个错误，我将 conf().get("single_chat_reply_prefix", "")先转换为字符串，然后再将其与reply_text结合. 用join()方法将列表中的所有元素连接成一个字符串。
例如
`reply_text = ''.join(conf().get("single_chat_reply_prefix", "")) + reply_text
`
修改保存后运行成功
![image](https://user-images.githubusercontent.com/53589027/237063613-a1b020f6-2396-473b-b740-cbf888b1e962.png)

### 终端日志 📒

```log
[ERROR][2023-05-09 17:51:49][chat_channel.py:267] - Worker return exception: can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/zyf/wechat/chatgpt-on-wechat/channel/chat_channel.py", line 149, in _handle
    reply = self._decorate_reply(context, reply)
  File "/data/zyf/wechat/chatgpt-on-wechat/channel/chat_channel.py", line 225, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text
TypeError: can only concatenate list (not "str") to list

```

**Comment by lanvent** [comment]
配置里需要填字符串，请勿填写list，参考config-template.json
