### ISSUE TITLE
好些管理员指令提示：未知插件命令

### ISSUE THREAD

**Issue by CatcherX** [zhayujie/chatgpt-on-wechat#1062]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在微信发送：#resetall或$resetall等

### 问题描述 😯

收到的回复：

[ERROR]
未知插件命令
查看插件命令列表请输入#help 插件名

（下方的【管理员指令】基本如此）
[INFO]
通用指令：
#help : 回复此帮助
#help 插件名: 回复指定插件的详细帮助
#set_openai_api_key api_key: 设置你的OpenAI私有api_key
#reset_openai_api_key : 重置为默认的api_key
#reset : 重置会话

目前可用插件有：
tool:这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
角色扮演:让机器人扮演不同的角色。
replicate:利用replicate api来画图。
文字冒险:可以和机器人一起玩文字冒险游戏。
summary:聊天记录总结插件。

管理员指令：
#resume : 恢复服务
#stop : 暂停服务
#reconf : 重载配置(不包含插件配置)
#resetall : 重置所有会话
#scanp : 扫描插件目录是否有新插件
#plist : 打印当前插件列表
#setpri 插件名 优先级: 设置指定插件的优先级，越大越优先
#reloadp 插件名: 重载指定插件配置
#enablep 插件名: 启用指定插件
#disablep 插件名: 禁用指定插件
#installp 仓库地址或插件名: 安装指定插件
#uninstallp 插件名: 卸载指定插件
#updatep 插件名: 更新指定插件
#debug : 开启机器调试日志

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
无log，不予帮助
