### ISSUE TITLE
重新部署后重复响应之前的消息

### ISSUE THREAD

**Issue by Namarimizu** [zhayujie/chatgpt-on-wechat#1063]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Railway中直接部署，正常扫码登录，之后重复响应几个小时前的所有消息

### 问题描述 😯

请问要怎么上线时彻底重置机器人？我晚上部署之后，一登录就把中午第一次上线时的消息又全部响应了一遍（自动发给好友那种）

### 终端日志 📒

```log
（登录成功）
Start auto replying.
[WARNING][2023-05-09 13:39:43][wechat_message.py:68] - [WX]get other_user_id failed: 'NickName'
[INFO][2023-05-09 13:39:43][bridge.py:30] - create bot chatGPT for chat
...（重复）
[WARNING][2023-05-09 13:39:43][wechat_message.py:68] - [WX]get other_user_id failed: 'NickName'
...（重复）
[INFO][2023-05-09 13:39:43][chat_gpt_bot.py:49] - [CHATGPT] query=中午好！
...(重复，蹦出来一大堆今天中午刚上线时的信息)
[WARNING][2023-05-09 13:39:44][chat_gpt_bot.py:128] - [CHATGPT] RateLimitError: Rate limit reached （下略）

```

**Comment by Namarimizu** [comment]
> 

确实……是这个原因吗 我以为跟手动点登录区别不大😯

**Comment by lanvent** [comment]
你把```"hot_reload": true``` ，加到配置项里吧，开启它之后会过滤60秒以前的消息

**Comment by Namarimizu** [comment]
> 你的手機是不是開了一些自動同意登錄的xp模塊



> 你把`"hot_reload": true` ，加到配置項裏吧，開啟它之後會過濾60秒以前的消息

好像可以了，谢谢！
