### ISSUE TITLE
跳過微信字數限制實現分段回覆

### ISSUE THREAD

**Issue by jinskanna** [zhayujie/chatgpt-on-wechat#1064]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

如何可以實現超越微信字數限制

例如我需要一篇3000字的內容

GPT給我回覆的超過微信的2013字限制可以分段回覆

### 动机

在實際應用中會被微信字數限制截掉一段讓人有點惱火

**Comment by lanvent** [comment]
经过实测，个人微信支持1万字以上的回复

**Comment by jinskanna** [comment]
哪些設置可以完成這個目標？

**Comment by lanvent** [comment]
gpt3.5: 上下文和prmopt的tokens + 回复的tokens 加起来不会超过4096 tokens 。 你可以通过减少上下文+prompt的tokens数量来使chatgpt回复的上限更高。 即使这样， 因为4096token≈2000字，你不能通过一次提问就得到你所需的内容。
