### ISSUE TITLE
建议能在私聊对话中退出角色扮演

### ISSUE THREAD

**Issue by CatcherX** [zhayujie/chatgpt-on-wechat#1065]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在某微信群中开启角色扮演，不想被所有用户知道 $停止扮演 指令（因为有时候不想被某些用户自主停止）
希望可以在私聊中发送指令停止所有的角色扮演（最好能指定会话的角色）

### 举例

在一个家庭育儿群开启了育儿专家角色，这时被某个调皮的孩子发了：$停止扮演

### 动机

希望停止扮演指令在私聊中才能生效

**Comment by lanvent** [comment]
个人微信目前没有想到很好的方法实现，你可以把育儿专家的描述填写到 `character_desc`里试试

**Comment by Namarimizu** [comment]
能不能写个权限比godcmd还高的插件，收到群消息（isgroup）时 if content == "$停止扮演" 且msg.actual_user_nickname != "你自己的昵称" 就直接breakpass掉
