### ISSUE TITLE
昨晚更新后依然无法使用railway部署replicate插件

### ISSUE THREAD

**Issue by FFFKLD** [zhayujie/chatgpt-on-wechat#1066]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

求各位大佬指点一下
![7QIH)O E3GQ7~WU5@N6~)KC](https://github.com/zhayujie/chatgpt-on-wechat/assets/73410320/c36647b1-87b2-493c-b652-7d74edbd9b53)
![7T(AKA N1ACOL ~A7$ $C](https://github.com/zhayujie/chatgpt-on-wechat/assets/73410320/9477b3cb-fbb3-4815-88ec-7d3efd7c8dfd)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
hh 很尴尬，晚上我再看一看

**Comment by Episode233** [comment]
我也遇到了同样的问题，无法在railway使用，可以登录上但是不会自动回复

**Comment by Episode233** [comment]
在railway上部署上出现错误
Build and push Docker image
Error: buildx failed with: ERROR: denied: permission_denied: write_package

**Comment by lanvent** [comment]
> Error: buildx failed with: ERROR: denied: permission_denied: write_package

这个是git action的输出吧，不影响
