### ISSUE TITLE
唤醒tool时能否去掉$tool或改成自己想要的文案，比如@tool

### ISSUE THREAD

**Issue by godblessbb** [zhayujie/chatgpt-on-wechat#1067]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

Mac电脑上$符号跟￥符号共享一个键位，每次调用的时候十分繁琐，手机上调取$符号也不是很方便，所以我在想这个符号可不可以换成自己想用的符号比如@，用@tool加一个空格来调取，考虑到群聊场景需要用@来唤醒机器人，那么改成@@可以。

同时有的场景其实完全不需要$唤醒，比如链接，直接抛一个链接给机器人，机器人就应该继续询问需要对这个链接做什么，因为这是特定对象。

感觉应该可以很方便地改掉，但是不清楚去哪里改好，请大神指路。

**Comment by goldfishh** [comment]
config.py里有一个prefix可以设置

**Comment by lanvent** [comment]
"plugin_trigger_prefix": "\" 可以更改插件交互命令的前缀
