### ISSUE TITLE
报错没有提供正确API

### ISSUE THREAD

**Issue by fdunb** [zhayujie/chatgpt-on-wechat#107]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
无类似问题

报错没有提供正确的API，但我是从官网复制粘贴而来，不应该会有错误。不论问什么，都只是回答再说一遍

### 环境
操作系统windows
 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
终端日志贴一下
