### ISSUE TITLE
版主，我想问一下，那个程序重启了，gpt的记忆就没了，怎么解决阿

### ISSUE THREAD

**Issue by X-233** [zhayujie/chatgpt-on-wechat#1070]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

那个程序重启了，gpt的记忆就没了

### 问题描述 😯

版主，我想问一下，那个程序重启了，gpt的记忆就没了，怎么解决阿

### 终端日志 📒

```log
无
```

**Comment by lanvent** [comment]
目前重启是会清除的，不能保存
