### ISSUE TITLE
能否用不同的画图指令分别调用replicate模型和OpenAI的画图模型

### ISSUE THREAD

**Issue by Li-Eternally** [zhayujie/chatgpt-on-wechat#1074]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

启用replicate插件后画图指令就被全程接管了，就是说能不能用不同的画图指令分别来调用replicate和OpenAI DALL-E2模型，求指教

### 举例

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/128838111/e5dbdfa8-1544-47ce-8e05-8845658582cd)
对于生成这种风格的图片replicate在某些情况下生成的图片并不是很准确

### 动机

这样的话又多可以出来一个DALL-E2画图模型来供用户选择

**Comment by lanvent** [comment]
目前其实也能实现，你把replicate的default参数中的model和version删除，如果没有命中replicate的关键词，它就会报错并丢给dalle2

**Comment by Li-Eternally** [comment]
> 目前其实也能实现，你把replicate的default参数中的model和version删除，如果没有命中replicate的关键词，它就会报错并丢给dalle2

感谢指导，确实可行

**Comment by adminlove520** [comment]
对于mj和rp就会这样子  不确定是调用哪个。我的想法是 类似tool，$rp/$mj这样子调用
