### ISSUE TITLE
群聊加入白名单且按关键字发言，机器人无回复，但有新成员加入时会自动欢迎，且私聊正常使用

### ISSUE THREAD

**Issue by Episode233** [zhayujie/chatgpt-on-wechat#1075]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

群聊加入白名单且按关键字发言，机器人无回复，但有新成员加入时会自动欢迎，且私聊正常使用

### 问题描述 😯

群聊加入白名单且按关键字发言，机器人无回复，但有新成员加入时会自动欢迎，且私聊正常使用

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
相关配置和日志贴一下吧

**Comment by Episode233** [comment]
![F(S@VYVJCK82BA}FBU(05 7](https://github.com/zhayujie/chatgpt-on-wechat/assets/87570815/8c75a4a9-04d1-4fe8-b654-04b3c220c91d)
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: group_chat_prefix=[""]
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: single_chat_prefix=[""]
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: single_chat_reply_prefix=[ChatGPT]
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: group_chat_in_one_session=["test"]
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: group_name_white_list=["ChatGPT的小窝"]
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: group_speech_recognition=True
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: speech_recognition=True
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: image_create_prefix=["画", "看", "找", "发"]
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: voice_reply_voice=True
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: open_ai_api_key=隐藏
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: expires_in_seconds=3600
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: conversation_max_tokens=1000
[INFO][2023-05-11 11:48:21][config.py:180] - [INIT] override config by environ args: model=gpt-3.5-turbo
[INFO][2023-05-11 11:48:21][config.py:195] - [INIT] load config: {'open_ai_api_key': '隐藏', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': [''], 'single_chat_reply_prefix': '[ChatGPT]', 'group_chat_prefix': [''], 'group_name_white_list': ['ChatGPT的小窝'], 'group_chat_in_one_session': ['test'], 'image_create_prefix': ['画', '看', '找', '发'], 'speech_recognition': True, 'group_speech_recognition': True, 'voice_reply_voice': True, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-05-11 11:48:21][config.py:145] - [Config] User datas file not found, ignore.
█
[INFO][2023-05-11 11:48:21][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-05-11 11:48:21][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-05-11 11:48:22][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-05-11 11:48:22][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-05-11 11:48:22][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
chatgpt-tool-hub version: 0.4.3
[INFO][2023-05-11 11:48:23][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-05-11 11:48:23][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-05-11 11:48:23][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-05-11 11:48:23][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-05-11 11:48:23][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-05-11 11:48:23][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin GODCMD not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin KEYWORD not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin BANWORDS not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin TOOL not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin ROLE not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin DUNGEON not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin BDUNIT not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin HELLO not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][plugin_manager.py:101] - Plugin FINISH not found in pconfig, adding to pconfig...
[INFO][2023-05-11 11:48:23][godcmd.py:181] - [Godcmd] 因未设置口令，本次的临时口令为0983。
[INFO][2023-05-11 11:48:23][godcmd.py:196] - [Godcmd] inited
[INFO][2023-05-11 11:48:23][keyword.py:40] - [keyword] {}
[INFO][2023-05-11 11:48:23][keyword.py:42] - [keyword] inited.
[WARNING][2023-05-11 11:48:23][banwords.py:53] - [Banwords] init failed, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[ERROR][2023-05-11 11:48:23][plugin_manager.py:126] - Failed to init BANWORDS, diabled. [Errno 2] No such file or directory: '/app/plugins/banwords/banwords.txt'
Traceback (most recent call last):
File "/app/plugins/plugin_manager.py", line 124, in activate_plugins
instance = plugincls()
File "/app/plugins/banwords/banwords.py", line 54, in __init__
raise e
File "/app/plugins/banwords/banwords.py", line 40, in __init__
with open(banwords_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/plugins/banwords/banwords.txt'
[INFO][2023-05-11 11:48:23][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-05-11 11:48:23][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[WARNING][2023-05-11 11:48:24][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[WARNING][2023-05-11 11:48:24][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[INFO][2023-05-11 11:48:24][victorinox.py:86] - use_tools=['terminal', 'meteo-weather', 'url-get', 'python'], params: {'debug': False, 'openai_api_key': '隐藏', 'open_ai_api_base': 'https://api.openai.com/v1';, 'proxy': '', 'request_timeout': 120, 'model_name': 'gpt-3.5-turbo', 'no_default': False, 'top_k_results': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning_news_api_key': '', 'cuda_device': 'cpu', 'think_depth': 3, 'arxiv_summary': True, 'morning_news_use_llm': False}
[INFO][2023-05-11 11:48:24][tool.py:32] - [tool] inited
[INFO][2023-05-11 11:48:24][role.py:69] - [Role] inited
[INFO][2023-05-11 11:48:24][dungeon.py:56] - [Dungeon] inited
[WARNING][2023-05-11 11:48:24][bdunit.py:47] - [BDunit] init failed, ignore
[ERROR][2023-05-11 11:48:24][plugin_manager.py:126] - Failed to init BDUNIT, diabled. config.json not found
Traceback (most recent call last):
File "/app/plugins/plugin_manager.py", line 124, in activate_plugins
instance = plugincls()
File "/app/plugins/bdunit/bdunit.py", line 48, in __init__
raise e
File "/app/plugins/bdunit/bdunit.py", line 36, in __init__
raise Exception("config.json not found")
Exception: config.json not found
[INFO][2023-05-11 11:48:24][hello.py:23] - [Hello] inited
[INFO][2023-05-11 11:48:24][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.

**Comment by lanvent** [comment]
没看出来什么毛病，debug=true 加入到配置里，群里发条消息看看log

**Comment by byYufeng** [comment]
为什么我的可以自动回复了 但是新成员加入没有自动欢迎

**Comment by leeyi2019** [comment]
有新成员加入时会自动欢迎这个怎么关闭
