### ISSUE TITLE
ReplyType.IMAGE要怎么使用？

### ISSUE THREAD

**Issue by Namarimizu** [zhayujie/chatgpt-on-wechat#1076]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

不好意思，问个特别基础的问题哈……写插件的时候想用默认的Hello插件改一改，触发关键字时自动回复图片：我把 reply.type = ReplyType.IMAGE 写好之后， reply.content = 要怎么写才能把 draw_image() 返回的图片发出去？
（可能真的太基础了，抱歉😵）

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Namarimizu** [comment]
好像解决了，但是机器人发的gif图片很小且不能保存（应该是被当成表情了），其它格式的图片不点开会压缩……

**Comment by Namarimizu** [comment]
以及把wechat_channel.py最后那段ReplyType.IMAGE改成了这样……好像方便一点？
```
        elif reply.type == ReplyType.IMAGE:  # 从文件读取图片
            # 如果 reply.content 是一个包含图像文件路径的字符串
            if os.path.isfile(reply.content):
                with open(reply.content, 'rb') as f:
                    image_storage = f.read()
                itchat.send_image(reply.content, toUserName=receiver)
            else:
                # 如果 reply.content 是一个包含图像数据的字符串
                image_data = base64.b64decode(reply.content)
                image_storage = io.BytesIO(image_data)
                image_storage.seek(0)
                itchat.send('@img@%s' % str(image_storage), toUserName=receiver)
```

**Comment by lanvent** [comment]
IMAGE是一个文件IO对象，你只需要让content=open(image path, "r")
itchat原来支持发送gif吗？我没有测试过，欢迎测试下原来的代码能不能发送gif
