### ISSUE TITLE
如果是语音提问，回复的消息增加提问语音的翻译是否合适？

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#1084]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

核心是啥呢，主要是微信的翻译和openai的翻译不一样，可能回答的问题并不能解决“语音”想表达的问题，因为转换的文字就不是原意。

**Comment by lanvent** [comment]
没有看懂，能否举个例子

**Comment by Zhaoyi-Yan** [comment]
就是我发一句语音给机器人，语音内容可能是“机器人，感觉好热啊！”。转文字可能变成“奇迹了，感觉好乐啊！”。这时候肯定没法触发，所以把转成的文字作为引用。bot回复的内容类似“针对语音`奇迹了，感觉好乐啊！`回复：`xxx` ”。可以让用户明白自己说的语音和自己表达的意思是否接近，是否重新输入语音或者文字。

核心是，
1. 用户用语音输入最多就60s，可能大部分情况下可能只是十几秒，并不会生成很长的文字。所以，即使引用了文字，应该也不会很长。
2. 微信语音转的文字，和openai转的文字，并不匹配，所以不能单纯用户从微信语音转文字看出是否语音输入准确。

**Comment by lanvent** [comment]
了解，这个会和#937 一起实现
