### ISSUE TITLE
是否能一个服务端支持多个平台或者多个帐号接入

### ISSUE THREAD

**Issue by Dfengs** [zhayujie/chatgpt-on-wechat#1085]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

搭建一个服务端，能不能公众号、企业微信和个人微信同时接入，我看channel_type只能选择一个，或者在channel_type是一个类型的情况下支持多个帐号同时使用。

**Comment by lanvent** [comment]
不支持
