### ISSUE TITLE
使用wechay后被封号，很老的实名微信号，唉！！！

### ISSUE THREAD

**Issue by 726425219** [zhayujie/chatgpt-on-wechat#1086]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

wechaty支持的版本太老，很多bug都找不到解决方案，也没法再二次开发

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
个人微信机器人都有封号的问题，欢迎交流防封姿势~

**Comment by caizhuoyue77** [comment]
请问是怎么开wechaty的呀？只用配置wechaty的token就可以了嘛？
