### ISSUE TITLE
如果想让chatgpt自动补充当前或未来最新日期这个可以如何实现或者给他prompt

### ISSUE THREAD

**Issue by hellosmarter** [zhayujie/chatgpt-on-wechat#1088]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我想让chatgpt知道我们说的某一个事情是哪一天，比如我说明天我要去聚餐，我要让chatgpt自动改成 2023年5月14日要去聚餐。
现在我用tool工具里面的python是可以查询系统最新日期，但是chatgpt没有办法自动知道当前日期，能否在那个地方直接设置让他自动先调用工具查询今天最新日期，然后推测出我说的明天或后天对应是那个日期？

### 举例

类似这样的：
user：我明天下午2点要去聚餐
bot：好的，知道了，2023年5月14下午2点要去和朋友聚餐

### 动机

暂无

**Comment by Zhaoyi-Yan** [comment]
查看本机的时间，给gpt前，增加一行，“现在是xx时间，若冒号后面提到了具体时间，则忽略冒号前面的话：“咋样？

**Comment by hellosmarter** [comment]
@Zhaoyi-Yan 可以给一个例子吗？这个是要系统自动联网去获取吧，不可能每次说之前都和他说今天是xx时间吧？

> 查看本机的时间，给gpt前，增加一行，“现在是xx时间，若冒号后面提到了具体时间，则忽略冒号前面的话：“咋样？

**Comment by Zhaoyi-Yan** [comment]
localtime直接获取不就得了。。

**Comment by lanvent** [comment]
这个我想到的实现是，提供一些占位符，比如如果包含{{localtime}}，程序将systemprompt的占位符自动替换为当前时间。 使用插件方式实现应该方便一些。

**Comment by hellosmarter** [comment]
> 这个我想到的实现是，提供一些占位符，比如如果包含{{localtime}}，程序将systemprompt的占位符自动替换为当前时间。 使用插件方式实现应该方便一些。

@lanvent 你这个方式我去尝试 一下，在系统 prompt看看能不能有用；

1、另外现在使用tool工具里面的python是可以查询最新日期，但是他没有办法自动和接下来的问题融合在一起。
2、比如我先用$tool 使用python查询今天是几月几日，然后再接着问明天我要去吃饭，他可以把我明天替换成最新的日期，但是这种就要求我每次都先让他查询一下当前日期。不是特别好
3、我其实想实现的效果是，比如在我是想config.json里面的  "character_desc" 限定她说每次都先执行一下 $tool 使用python查询今天是几月几日，但是这样弄好像不行，因为他没有办法启动tool工具，他会直接把这句话发送给了chatgpt，并没有启动tool工具查询

现在就是针对这个不知道各位大佬有没有好的其他方法。

**Comment by hellosmarter** [comment]
好的，了解了，谢谢

> 这个方法并没有在程序里实现，需要你自行实现。

**Comment by hellosmarter** [comment]
> 这个方法并没有在程序里实现，需要你自行实现。

@lanvent 再请教一下大佬，那是在那个模块下面加这个呢？是在bot文件下的chatgpt文件里面的chat_gpt_bot.py 文件里面吗？因为对整个代码结构还不是很熟，多谢
