### ISSUE TITLE
能否增加屏蔽指定好友或者群聊的配置

### ISSUE THREAD

**Issue by a472691** [zhayujie/chatgpt-on-wechat#1095]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

增加一个配置项，可以屏蔽指定群聊或者好友

### 举例

例如微信团队的消息

### 动机

上周末因为它发了一条消息给我，导致机器人自动回复，然后它又回复，两个来回不断重复回复，导致我token直接被刷完了

**Comment by lanvent** [comment]
目前个人微信的默认通道，每个用户没有唯一的ID来标识，所以没有添加这个功能
