### ISSUE TITLE
有关用户上下文的保存相关问题

### ISSUE THREAD

**Issue by hellosmarter** [zhayujie/chatgpt-on-wechat#1097]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

关于目前项目里面的一些上下文有一些疑问，想请教一下大家：
1、目前和机器人分配的用户id是不是随机分配的，同一个用户不同时间和和chagpt聊的情况下，用户id是不是变化的？
2、和机器人上午聊的事情，下午在问就不知道了，这个是不是没有超过conversation_max_tokens": 1000这个值就可以，超过了就不行了？
3、expires_in_seconds：3600,  # 无操作会话的过期时间，这个是只如果用户和gpt超过1小时都没有聊，所有的会话记录都会清空吗还是说超过这个时间，再去聊会认为是新会话重新分配id？

4、对于上下文维持更持久这个大家有啥好的 解决方案吗？谢谢

### 举例

无

### 动机

无

**Comment by lanvent** [comment]
1. 默认的个人微信通道中，每次重新登录，id重新分配
2,3 意思是超过3600秒没有跟机器人对话，这个会话就会被清除，不影响其他人的会话
4. 如果不希望机器人忘记会话，可以把秒数设大点

**Comment by hellosmarter** [comment]
> 2\. 可以把秒数设大点

@lanvent 谢谢大佬解答，另外还想问一下，如果是企业微信，这个每次重新登录id也是会重新分配是吧？

**Comment by hellosmarter** [comment]
> 现在应该只有个人微信会重新分配

好的，了解了，谢谢
