### ISSUE TITLE
Exception: you must provide a model parameter

### ISSUE THREAD

**Issue by hopegao** [zhayujie/chatgpt-on-wechat#1099]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 问题描述 😯

配置文件配置了'model': 'gpt-3.5-turbo'，ask的时候抛异常“you must provide a model parameter”

### 终端日志 📒

```log
https://github.com/zhayujie/chatgpt-on-wechat/assets/101623935/33df1d33-9d9c-4972-a3c9-8ff1c6b59e51
```

**Comment by lanvent** [comment]
你应该填写错了文件，应该修改的是config.json

**Comment by hopegao** [comment]
> 你应该填写错了文件，应该修改的是config.json

启动的时候不会是打印配置的吗，有 "model": "gpt-3.5-turbo"

**Comment by HelpSourceCodeSetup** [comment]
源码搭建|代部署|不成功不收费|+V：create8080
