### ISSUE TITLE
pip3 install openai==0.25.0

### ISSUE THREAD

**Issue by RundongWei** [zhayujie/chatgpt-on-wechat#11]
ERROR: Could not find a version that satisfies the requirement openai==0.25.0 (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
ERROR: No matching distribution found for openai==0.25.0

**Comment by RundongWei** [comment]
只有图片生成功能报错

**Comment by zhayujie** [comment]
是python版本太低吗

**Comment by L1yuu** [comment]
> 是python版本太低吗
是的 已经解决了
