### ISSUE TITLE
我部署以后，只能在个人聊天里使用，不能在群聊使用

### ISSUE THREAD

**Issue by clairelovesgravy** [zhayujie/chatgpt-on-wechat#110]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

配置完成后，个人对话支持自动回复，群聊里对话不回复。

> 简要说明、截图、复现步骤等，也可以是需求或想法
个人聊天正常回复。
群聊的问题读不出来。

### 终端日志 (如有报错)
没有日志，就是空的，读不出来。个人聊天会写入这样的信息[INFO][2023-02-08 17:01:26][open_ai_bot.py:20] - [OPEN_AI] query=股票怎么分析
但是对群聊里的问题没有反应
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Lan0618** [comment]
配置文件贴一下

**Comment by clairelovesgravy** [comment]
{
  "open_ai_api_key": "1111111111111111111111111111111",
  "single_chat_prefix": [""],
  "single_chat_reply_prefix": "[robot] ",
  "group_chat_prefix": ["@bot"],
  "group_name_white_list": "ALL_GROUP",
  "image_create_prefix": ["画", "看", "找"],
  "conversation_max_tokens": 1000,
  "character_desc": "我是gpt-3, 一个由OpenAI训练的大型语言模型, 旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。"
}

**Comment by zhayujie** [comment]
群组有设置名称吗

**Comment by clairelovesgravy** [comment]
> 群组有设置名称吗

我后面设置了群聊名称重新尝试，发现1、只有加到白名单里的群聊才能用，ALL_GROUP不能默认所有群都能使用。2、另外群聊里的，一定要"group_chat_prefix": ["@bot"], 输入@bot才能触发自动回复，不能直接@机器人  就自动回复。
以上两个问题有解决方式吗

**Comment by tiger0012** [comment]
我也是设置的ALL_GROUP， 有时候刚开始对话的群聊都可以， 但是后面的群聊就不行了， 个人猜测是ALL_GROUP 也相当于一个白名单？后面的对话的群聊就没有加入白名单了？

**Comment by StreamSun** [comment]
老哥 个人聊天怎么聊啊？跟机器人的聊天窗口在哪呢

**Comment by zhayujie** [comment]
> > 群组有设置名称吗
> 
> 我后面设置了群聊名称重新尝试，发现1、只有加到白名单里的群聊才能用，ALL_GROUP不能默认所有群都能使用。2、另外群聊里的，一定要"group_chat_prefix": ["@bot"], 输入@bot才能触发自动回复，不能直接@机器人 就自动回复。 以上两个问题有解决方式吗

正常情况：
1.ALL_GROUP 可以支持所有群聊的，用的就是白名单那个配置
2.艾特是可以自动回复的

如果有问题可能是itchat受到了一些限制，接收微信消息时字段不全

**Comment by zhayujie** [comment]
> 我也是设置的ALL_GROUP， 有时候刚开始对话的群聊都可以， 但是后面的群聊就不行了， 个人猜测是ALL_GROUP 也相当于一个白名单？后面的对话的群聊就没有加入白名单了？

不会的，逻辑是如果配置了ALL_GROUP，直接不检查群名称

**Comment by sunguanghui** [comment]
> { "open_ai_api_key": "1111111111111111111111111111111", "single_chat_prefix": [""], "single_chat_reply_prefix": "[robot] ", "group_chat_prefix": ["@bot"], "group_name_white_list": "ALL_GROUP", "image_create_prefix": ["画", "看", "找"], "conversation_max_tokens": 1000, "character_desc": "我是gpt-3, 一个由OpenAI训练的大型语言模型, 旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。" }

修改成这样，就可以了。我一开始也遇到这个问题，后来调整好就正常了。
"group_name_white_list": ["ALL_GROUP"],

**Comment by xxball1111** [comment]
我开始也是这个问题，加入群白名单就可以了
