### ISSUE TITLE
微信不能机器人直接语音回复，有点伤

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#1101]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

这个项目貌似支持直接微信的语音回复，但是这个itchat框架貌似并不能这样做。https://github.com/lss233/chatgpt-mirai-qq-bot

**Comment by lanvent** [comment]
我看了看，它也是基于uos的网页微信，网页微信是不能直接发送语音的

**Comment by psumhm** [comment]
Lss的QQ可以，微信不能

**Comment by psumhm** [comment]
> 我看了看，它也是基于uos的网页微信，网页微信是不能直接发送语音的

Wechaty 可以直接回复语音吗？
