### ISSUE TITLE
docker-compose+个人微信扫码登录常态化自动退出

### ISSUE THREAD

**Issue by Changego** [zhayujie/chatgpt-on-wechat#1103]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Linux+docker-compose 个人微信扫描登录不到一天进程 就会退出。

### 问题描述 😯

Linux+docker-compose 个人微信扫描登录不到一天进程 就会退出。

![图片](https://github.com/zhayujie/chatgpt-on-wechat/assets/4628191/bfa242c3-b302-4592-b165-a17747f89669)
![图片](https://github.com/zhayujie/chatgpt-on-wechat/assets/4628191/87e8957f-216c-4b4a-98a0-89c50905c139)

### 终端日志 📒

```log
chat-wechat    | Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
chat-wechat    | LOG OUT!

```

**Comment by Miaosful** [comment]
同款问题，我不是用的docker部署也会这样

**Comment by lanvent** [comment]
参考 https://github.com/zhayujie/chatgpt-on-wechat/issues/916#issuecomment-1535873131

**Comment by Changego** [comment]
好吧，已看，没有什么好的解决办法啊。多谢。
