### ISSUE TITLE
希望增加多key流转使用功能

### ISSUE THREAD

**Issue by xiaolietu** [zhayujie/chatgpt-on-wechat#1107]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

当使用企业微信接入自建应用后，免费key的次数限制导致无法使用，能不能增加多个key轮流，这样可以规避频率次数问题

### 举例

比如企业有300人使用，我设置50个key轮流使用，这样就可以保证每个人都可以收到内容

**Comment by lanvent** [comment]
先使用付费key吧，频率是足够的
