### ISSUE TITLE
监测机器人输出信息不完整情况，并提醒用户#重置会话

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#1109]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在聊天过程中，有时候会遇到只输出一小部分信息。如果发送“继续”，仍旧只有几十个字，再“继续”，还是只有几十个字。这种情况，通常可以通过”#重置会话”解决。但是一般用户也不懂这个。特别是，群的消息比较多，更容易出现类似的情况。

所以，能不能通过某种方法，监测类似的情况发生，并且提醒用户进行重置会话。

**Comment by lanvent** [comment]
你的conversation_max_tokens设置了多少

**Comment by Zhaoyi-Yan** [comment]
4096

**Comment by lanvent** [comment]
参考https://github.com/zhayujie/chatgpt-on-wechat/issues/908#issuecomment-1516225972

**Comment by Zhaoyi-Yan** [comment]
如果把值设置比较小的话，联系上下文的能力就会变弱吧。。比如我让机器人给出如何举办好一个茶会话，可能已经给我将近1000字的内容了。需要继续完善，这时候就需要“继续”设置太小的话，效果可能不好
