### ISSUE TITLE
部署以后，问他现在时间是多少，回答错误

### ISSUE THREAD

**Issue by xuzhouqqq** [zhayujie/chatgpt-on-wechat#111]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/14800016/217486240-41f9105e-7d15-4028-8e29-2f38721f9a47.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Ratten-fanger** [comment]
ChatGPT本身就不支持实时问题，它的训练库截止到21年，所以21年之后的信息理论上它都不知道

**Comment by xuzhouqqq** [comment]
> ChatGPT本身就不支持实时问题，它的训练库截止到21年，所以21年之后的信息理论上它都不知道

请教一下，我在https://chat.openai.com/chat 里面问他现在时间是多少，他能回答正确，是因为是两套不同的模型吗？
![image](https://user-images.githubusercontent.com/14800016/217488357-210c9135-48aa-42b7-98c1-cdfb90f3f591.png)

**Comment by Ratten-fanger** [comment]
模型不同，但是我理解他是按照聊天的创建时间确认时间的，比如你在网页版保留一个对话主题，明天再来问他还会回复你2月8号

**Comment by xuzhouqqq** [comment]
> 模型不同，但是我理解他是按照聊天的创建时间确认时间的，比如你在网页版保留一个对话主题，明天再来问他还会回复你2月8号

明白了，谢谢，我明天再去测试下。

**Comment by dzadz237** [comment]
API和官网对话机器人的底层模型应该是不一样的，我问官网对话机器人了，他说是不一样。。。
