### ISSUE TITLE
用c l a s h 飞越长城，且使用了规则模式飞流，程序依然运行不起来

### ISSUE THREAD

**Issue by HZ-YangJinLi** [zhayujie/chatgpt-on-wechat#1110]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1.启动c l a sh
2.python app.py

### 问题描述 😯

关闭飞长城工具 c l a s h 后能正常启动，工具已经配置了微信相关域名地址都是直接访问,启动工具后，启动程序就会报错。
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/129472364/789a4d8b-b3b6-4890-b987-460dff023ed9)

### 终端日志 📒

```log
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to p
roxy.', OSError(0, 'Error')))

```

**Comment by mari1995** [comment]
默认直连，加上代理，只通过domain-keyword 做特殊处理

**Comment by guagualong** [comment]
> 默认直连，加上代理，只通过domain-keyword 做特殊处理

请问这句话是对问题的描述，还是对问题的解答？

我也有这个问题，我也设置了分流规则：
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,手动选择

我用GPT-API-free项目的API Key，在关闭飞长城工具 c l a s h 后能正常启动并且使用。
我用OpenAI官方的API Key，无论打开还是关闭Clash，都不能启动。。。。
