### ISSUE TITLE
根据问题列表查询了我自己的账户API余额还有，但依旧提示You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by aaswads** [zhayujie/chatgpt-on-wechat#1111]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我根据问题列表里的链接查询了自己的API余额，还剩18刀
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67954485/1ca97c9b-ad22-476e-a8a6-f87e5cef0804)
但在railway上部署运行时依旧出现余额不足的选项
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67954485/27d48e56-2851-4197-b309-7da14cd5a503)

### 终端日志 📒

[INFO][2023-05-17 08:59:10][wechat_channel.py:124] - Wechat login success, user_id: @0c83ba040d377cceb3f258dce63a2bce4d241c8e053eebbd9dfd3fcaeffd084d, nickname: 厥根
Start auto replying.
[INFO][2023-05-17 08:59:22][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-17 08:59:22][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2023-05-17 08:59:24][chat_gpt_bot.py:128] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-05-17 08:59:44][chat_gpt_bot.py:147] - [CHATGPT] 第1次重试
[WARNING][2023-05-17 08:59:45][chat_gpt_bot.py:128] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-05-17 09:00:05][chat_gpt_bot.py:147] - [CHATGPT] 第2次重试
[WARNING][2023-05-17 09:00:05][chat_gpt_bot.py:128] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[INFO][2023-05-17 09:00:06][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
提问太快啦，请休息一下再问我吧), receiver=@012dbd283185c83ae5fddb8556a2a214a453cb98d668b4060cd74a175dca3987

**Comment by Zhaoyi-Yan** [comment]
Expired是过期的意思，3个月内没用完过期了
