### ISSUE TITLE
报错“我现在有点累了，等会再来吧”，这个应该怎么解决啊

### ISSUE THREAD

**Issue by cyangshengbin** [zhayujie/chatgpt-on-wechat#1112]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[INFO][2023-05-18 09:29:40][chat_gpt_bot.py:49] - [CHATGPT] query=你会写python嘛
[WARNING][2023-05-18 09:30:04][chat_gpt_bot.py:142] - [CHATGPT] Exception: HTTP code 404 from API (<html><title>404: Not Found</title><body>404: Not Found</body></html>)
[INFO][2023-05-18 09:30:42][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@4b8606fd820a46c5b1ed0aa7056b2831ae22ae5d3a3b4cad4464b9f7f3f6d1fd

### 问题描述 😯

[INFO][2023-05-18 09:29:40][chat_gpt_bot.py:49] - [CHATGPT] query=你会写python嘛
[WARNING][2023-05-18 09:30:04][chat_gpt_bot.py:142] - [CHATGPT] Exception: HTTP code 404 from API (<html><title>404: Not Found</title><body>404: Not Found</body></html>)
[INFO][2023-05-18 09:30:42][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@4b8606fd820a46c5b1ed0aa7056b2831ae22ae5d3a3b4cad4464b9f7f3f6d1fd

### 终端日志 📒

```log
[INFO][2023-05-18 09:29:40][chat_gpt_bot.py:49] - [CHATGPT] query=你会写python嘛
[WARNING][2023-05-18 09:30:04][chat_gpt_bot.py:142] - [CHATGPT] Exception: HTTP code 404 from API (<html><title>404: Not Found</title><body>404: Not Found</body></html>)
[INFO][2023-05-18 09:30:42][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@4b8606fd820a46c5b1ed0aa7056b2831ae22ae5d3a3b4cad4464b9f7f3f6d1fd
```

**Comment by lanvent** [comment]
贴一下配置吧

**Comment by QWei-xiaoby** [comment]
注意配置api_base时，应该加上一个/v1的后缀，而不是只有域名，要不然会报404错误。

**Comment by cyangshengbin** [comment]
> 贴一下配置吧

已解决，谢谢，就是clash代理配置没搞对

**Comment by cyangshengbin** [comment]
> 注意配置api_base时，应该加上一个/v1的后缀，而不是只有域名，要不然会报404错误。

我就是按模式配置来了，开的clash代理没有配对而已，已解决了

**Comment by cyangshengbin** [comment]
解决

**Comment by SampageGu** [comment]
> 

你好，可以具体讲讲怎么配置clash的嘛
