### ISSUE TITLE
请问一下大家config.py里面这个"trigger_by_self": False的参数具体含义是啥用来做啥的

### ISSUE THREAD

**Issue by hellosmarter** [zhayujie/chatgpt-on-wechat#1114]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

请问一下大家config.py里面这个"trigger_by_self": False的参数具体含义是啥用来做啥的

### 举例

请问一下大家config.py里面这个"trigger_by_self": False的参数具体含义是啥用来做啥的

### 动机

无

**Comment by lanvent** [comment]
是否允许机器人自己触发自己

**Comment by hellosmarter** [comment]
> 是否允许机器人自己触发自己

就是类似用微信自己给自己发信息这个意思吗？
