### ISSUE TITLE
无法连接OpenAI

### ISSUE THREAD

**Issue by wkfctoyou** [zhayujie/chatgpt-on-wechat#1118]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 追影
[INFO][2023-05-18 19:27:44][wechat_channel.py:124] - Wechat login success, user_id: @71bc8a7e6ef393c7db8309bc2ccf8f2bf0bc7b5f507b4482ebb6ca7d8f44d4ff, nickname: 追影
Start auto replying.
[WARNING][2023-05-18 19:27:58][wechat_message.py:68] - [WX]get other_user_id failed: 'NickName'
[INFO][2023-05-18 19:27:58][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-18 19:27:58][chat_gpt_bot.py:49] - [CHATGPT] query=，你好
[WARNING][2023-05-18 19:29:01][chat_gpt_bot.py:143] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BFB5A234C0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[INFO][2023-05-18 19:29:02][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=filehelper
[WARNING][2023-05-18 19:33:18][wechat_message.py:68] - [WX]get other_user_id failed: 'NickName'
[INFO][2023-05-18 19:33:18][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2023-05-18 19:34:22][chat_gpt_bot.py:143] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BFB78B7670>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[INFO][2023-05-18 19:34:22][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=filehelper

**Comment by mari1995** [comment]
网络连不上 chatgpt的域名，可以用上代理

**Comment by wkfctoyou** [comment]
我代理一直处于开启状态，可是最后始终是因为连接不到网络

**Comment by zhayujie** [comment]
> 我代理一直处于开启状态，可是最后始终是因为连接不到网络

要看看代理有没有生效，你是在命令行启动的吗， proxy配置有设置嘛

**Comment by wkfctoyou** [comment]
我这里是通过clash进行翻墙的，clash代理模式我选的是全局，因为现在才大一，所以对这些都不是很懂，只能通过模仿来进行了解，你能告诉我具体的操作方法吗？可以的话+q：3032244082

**Comment by Francis776** [comment]
> 我这里是通过clash进入翻墙的，clash代理模式我选择的是全面的，因为现在才大一，所以对这些都不是很懂，只能通过模拟进来了了解了，你可以告诉我具体的操作方法吗？可以的话+q：3032244082

查你本计算机的IP 然后把梯子的端口加在IP后面 ip:端口 类似这样 "proxy": "http://192.168.2.10:7890",
（7890是clash的端口）
同时去编辑app.py，
在from plugins import *后面加上以下代码

import os
proxy="http://192.168.2.10:7890"
os.environ["http_proxy"] =proxy
os.environ["https_proxy"] =proxy

**Comment by wkfctoyou** [comment]
谢谢，问题解决了

**Comment by SYEA01** [comment]
我是购买的国外的VPS，请问各位 这种情况怎么填代理这里的信息

**Comment by guagualong** [comment]
我的config.json是这样填的：
"open_ai_api_key": "我的OpenAI官方 API KEY",
  "model": "gpt-3.5-turbo",
  "channel_type": "wx",
  "proxy": "http://192.168.31.166:7890",
  "open_ai_api_base": "https://api.openai.com/v1",

我也编辑了app.py，
在from plugins import *后面加上以下代码
import os
proxy="http://192.168.2.10:7890/"
os.environ["http_proxy"] =proxy
os.environ["https_proxy"] =proxy

我还用了Clash翻墙。当我选择Rule模式的时候（我设置了一下规则，大致是所有的外国网站用美国的节点，所有的国内网站直连），命令提示符里显示：
[INFO][2023-09-29 08:35:13][godcmd.py:208] - [Godcmd] inited
[INFO][2023-09-29 08:35:13][keyword.py:40] - [keyword] {}
[INFO][2023-09-29 08:35:13][keyword.py:42] - [keyword] inited.
[INFO][2023-09-29 08:35:13][linkai.py:33] - [LinkAI] inited
[INFO][2023-09-29 08:35:13][role.py:69] - [Role] inited
[INFO][2023-09-29 08:35:13][dungeon.py:56] - [Dungeon] inited
[INFO][2023-09-29 08:35:13][hello.py:23] - [Hello] inited
[INFO][2023-09-29 08:35:13][finish.py:23] - [Finish] inited

我设置的翻墙规则是：
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,手动选择
 
不知道怎么办，就是用不了原生的OpenAI api。反倒是从[GPT-API-free](https://github.com/chatanywhere/GPT_API_free#gpt-api-free)项目中弄到的API可以正常使用（而且不用翻墙）。
