### ISSUE TITLE
能否支持调用dify的经过训练的ai，能做这个的话需求真的非常大

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#1119]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结
@lanvent 
dify项目是一个低代码llm应用搭建平台，支持上传资料建立向量索引，现在云服务开放后端的调用支持，这个如果能和本项目结合，真的是能有很多玩法

云服务地址：
https://cloud.dify.ai/apps

**Comment by zhayujie** [comment]
感谢分享~    这个我们正好也在做，   想更方便的集成到 微信以及其他端

**Comment by rainberg** [comment]
https://kjqvjse66l.feishu.cn/docx/DmLedTWtUoNGX8xui9ocdUEjnNh

也希望可以有接口调用FastGpt的Api

**Comment by rainberg** [comment]
https://mp.weixin.qq.com/s/RAZGDEl_KbwzXhNHiqk8Gg

也许可以借助laf来做接口

**Comment by PolarPeak** [comment]
> 感谢分享~ 这个我们正好也在做， 想更方便的集成到 微信以及其他端

也希望支持dify的本地部署的社区版
