### ISSUE TITLE
ffmpeg安装问题

### ISSUE THREAD

**Issue by NGwr** [zhayujie/chatgpt-on-wechat#1120]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

CentOS 安装不了FFmpeg

User
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libgnutls.so.26(GNUTLS_1_4)(64bit)
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libgnutls.so.26()(64bit)
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libopenjpeg.so.2()(64bit)
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest

Start auto replying.
/usr/local/lib/python3.9/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[WARNING][2023-05-19 07:14:02][chat_channel.py:175] - [WX]any to wav error, use raw path. [Errno 2] No such file or directory: 'ffprobe'
[INFO][2023-05-19 07:14:02][bridge.py:30] - create bot openai for voice_to_text
[INFO][2023-05-19 07:14:04][openai_voice.py:25] - [Openai] voiceToText text=Cough Cough Cough voice file name=tmp/230519-071402.mp3
[INFO][2023-05-19 07:14:04][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-19 07:14:04][chat_gpt_bot.py:49] - [CHATGPT] query=Cough Cough Cough
[INFO][2023-05-19 07:14:14][bridge.py:30] - create bot google for text_to_voice
[INFO][2023-05-19 07:14:15][google_voice.py:42] - [Google] textToVoice text=Hello there! Are you okay? Do you need any help or medical attention? If you have been coughing for an extended period or have other symptoms, it may be best to consult with a medical professional to determine the underlying cause and receive appropriate treatment. voice file name=tmp/reply-1684480454-262270877.mp3
[INFO][2023-05-19 07:14:22][wechat_channel.py:190] - [WX] sendFile=tmp/reply-1684480454-262270877.mp3, receiver=@c10627125a09b078f3b9a604a292b12dda8417efafd60fc23110355d4db6d1b6

尝试命令：
sudo yum install ffmpeg
安装libgnutls.so.26库：

sudo yum install gnutls

安装libopenjpeg.so.2库：

Copy code
sudo yum install openjpeg2

sudo rpm -Va --nofiles --nodigest
sudo yum install ffmpeg --skip-broken
sudo yum install https://download1.rpmfusion.org/free/el/rpmfusion-free-release-6.noarch.rpm 
https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-6.noarch.rpm
sudo yum install ffmpeg

### 问题描述 😯

CentOS 安装不了FFmpeg

User
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libgnutls.so.26(GNUTLS_1_4)(64bit)
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libgnutls.so.26()(64bit)
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libopenjpeg.so.2()(64bit)
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest

Start auto replying.
/usr/local/lib/python3.9/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[WARNING][2023-05-19 07:14:02][chat_channel.py:175] - [WX]any to wav error, use raw path. [Errno 2] No such file or directory: 'ffprobe'
[INFO][2023-05-19 07:14:02][bridge.py:30] - create bot openai for voice_to_text
[INFO][2023-05-19 07:14:04][openai_voice.py:25] - [Openai] voiceToText text=Cough Cough Cough voice file name=tmp/230519-071402.mp3
[INFO][2023-05-19 07:14:04][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-19 07:14:04][chat_gpt_bot.py:49] - [CHATGPT] query=Cough Cough Cough
[INFO][2023-05-19 07:14:14][bridge.py:30] - create bot google for text_to_voice
[INFO][2023-05-19 07:14:15][google_voice.py:42] - [Google] textToVoice text=Hello there! Are you okay? Do you need any help or medical attention? If you have been coughing for an extended period or have other symptoms, it may be best to consult with a medical professional to determine the underlying cause and receive appropriate treatment. voice file name=tmp/reply-1684480454-262270877.mp3
[INFO][2023-05-19 07:14:22][wechat_channel.py:190] - [WX] sendFile=tmp/reply-1684480454-262270877.mp3, receiver=@c10627125a09b078f3b9a604a292b12dda8417efafd60fc23110355d4db6d1b6

尝试命令：
sudo yum install ffmpeg
安装libgnutls.so.26库：

sudo yum install gnutls

安装libopenjpeg.so.2库：

Copy code
sudo yum install openjpeg2

sudo rpm -Va --nofiles --nodigest
sudo yum install ffmpeg --skip-broken
sudo yum install https://download1.rpmfusion.org/free/el/rpmfusion-free-release-6.noarch.rpm 
https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-6.noarch.rpm
sudo yum install ffmpeg

### 终端日志 📒

CentOS 安装不了FFmpeg

User
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libgnutls.so.26(GNUTLS_1_4)(64bit)
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libgnutls.so.26()(64bit)
错误：软件包：ffmpeg-libs-2.6.8-3.el6.nux.x86_64 (nux-dextop)
          需要：libopenjpeg.so.2()(64bit)
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest

Start auto replying.
/usr/local/lib/python3.9/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[WARNING][2023-05-19 07:14:02][chat_channel.py:175] - [WX]any to wav error, use raw path. [Errno 2] No such file or directory: 'ffprobe'
[INFO][2023-05-19 07:14:02][bridge.py:30] - create bot openai for voice_to_text
[INFO][2023-05-19 07:14:04][openai_voice.py:25] - [Openai] voiceToText text=Cough Cough Cough voice file name=tmp/230519-071402.mp3
[INFO][2023-05-19 07:14:04][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-19 07:14:04][chat_gpt_bot.py:49] - [CHATGPT] query=Cough Cough Cough
[INFO][2023-05-19 07:14:14][bridge.py:30] - create bot google for text_to_voice
[INFO][2023-05-19 07:14:15][google_voice.py:42] - [Google] textToVoice text=Hello there! Are you okay? Do you need any help or medical attention? If you have been coughing for an extended period or have other symptoms, it may be best to consult with a medical professional to determine the underlying cause and receive appropriate treatment. voice file name=tmp/reply-1684480454-262270877.mp3
[INFO][2023-05-19 07:14:22][wechat_channel.py:190] - [WX] sendFile=tmp/reply-1684480454-262270877.mp3, receiver=@c10627125a09b078f3b9a604a292b12dda8417efafd60fc23110355d4db6d1b6

尝试命令：
sudo yum install ffmpeg
安装libgnutls.so.26库：

sudo yum install gnutls

安装libopenjpeg.so.2库：

Copy code
sudo yum install openjpeg2

sudo rpm -Va --nofiles --nodigest
sudo yum install ffmpeg --skip-broken
sudo yum install https://download1.rpmfusion.org/free/el/rpmfusion-free-release-6.noarch.rpm 
https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-6.noarch.rpm
sudo yum install ffmpeg

**Comment by zhayujie** [comment]
mark
