### ISSUE TITLE
通过cloudflare创建api代理，国内服务器可以无阻调用openai的api了！

### ISSUE THREAD

**Issue by 6vision** [zhayujie/chatgpt-on-wechat#1128]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

申请免费的eu.org域名，通过cloudflare创建api代理，国内服务器可以无阻调用openai的api了！
:https://mp.weixin.qq.com/s/SYGPuHKO7ShzfmBGsQ363w

**Comment by bentennysonyoung** [comment]
什么science上网新思路

**Comment by KFC-vme-50** [comment]
参考这个https://github.com/zhayujie/chatgpt-on-wechat/issues/887
