### ISSUE TITLE
手机切换微信账号服务端自动退出

### ISSUE THREAD

**Issue by truynal** [zhayujie/chatgpt-on-wechat#1130]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

运行app.py之后，用个人主微信扫码登陆之后，手机端一旦切换微信或者退出登陆，服务端也会跟随退出：Unexpected sync check result: window.synccheck={retcode:"1101",selector:"0"}
LOG OUT!
不能手机端切换账号之后服务端保持登陆状态吗。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by truynal** [comment]
目前的做法是服务端登陆之后把微信卸载了，然后重新安装，登陆其他账号，服务端端账户就不会退出。

**Comment by chenyuxiangyes** [comment]
如果是原生安卓用户，可以创建多用户，即多账户使用手机互相隔离。微信多开可能也是一种选择。

**Comment by bentennysonyoung** [comment]
多开是正解。但是长时间挂网页版也会触发预警的吧。
我都是设定每天定时自启和关闭。
用requests将二维码发给自己企业微信群机器人/其他支持curl的机器人，小号去电脑端扫码登录。
app.py 的 def run() 的 try 中增加如下代码：当然你可以先修改自动生成图片的命名方式，以避免误删文件。
```
    files = os.listdir("/tmp")
        for file in files:
            if file.endswith('PNG') and 'tmp' in file:
                os.remove("/tmp/" + file)
```
利用原本文件夹 \chatgpt-on-wechat\scripts 中的 bash 脚本，再设置定时。
我也修改了对应文件：
start.sh
```
#!/bin/bash
#后台运行Chat_on_wechat执行脚本

cd `dirname $0`/..
export BASE_DIR=`pwd`
echo $BASE_DIR

# check the nohup.out log output file
if [ ! -f "${BASE_DIR}/nohup.out" ]; then
  touch "${BASE_DIR}/nohup.out"
echo "create file  ${BASE_DIR}/nohup.out"
fi

nohup python3.9 "${BASE_DIR}/app.py" &
sleep 5
nohup python3.9 "${BASE_DIR}/weworkqr.py" &

echo "Chat_on_wechat is starting，you can check the ${BASE_DIR}/nohup.out"

exit 0
```
shutdown.sh
```
#!/bin/bash

#关闭服务
pid=`ps -ef | grep python3.9 | grep "app.py" | grep -v grep | awk '{print $2}'`
if [ -z "$pid" ] ; then
        echo "No chatgpt-on-wechat running."
        exit -1;
fi

echo "The chatgpt-on-wechat(${pid}) is running..."

kill ${pid}

echo "Send shutdown request to chatgpt-on-wechat(${pid}) OK"
```
增加的 weworkqr.py 文件如下，放在主文件夹下，wework群机器人功能不赘述。
```
# -*- coding:utf-8 -*-
# 国内服务器用下面镜像
# pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn pakegename
# python -m pip install --upgrade pip
import sys
import os
# requests需要提前安装以下依赖
# pip3 install cryptography
# pip3 install pyOpenSSL
# pip3 install certifi
# pip install requests
import requests
import importlib
import base64
import hashlib

from time import sleep

importlib.reload(sys)


def post_image(wx_url, image):
    # 转换图片成base64格式
    with open(image, "rb") as pfile:
        data = pfile.read()
        encodestr = base64.b64encode(data)
        image_data = str(encodestr, "utf-8")
    # 图片的MD5值
    with open(image, "rb") as pfile:
        md = hashlib.md5()
        md.update(pfile.read())
        image_md5 = md.hexdigest()
    headers = {"Content-Type": "application/json;charset=utf-8"}
    data = {
        "msgtype": "image",
        "image": {
            "base64": image_data,
            "md5": image_md5
        }
    }
    # body = json.dumps(data)
    # result = requests.post(url = wx_url, data = body, headers = headers)
    result = requests.post(url=wx_url, headers=headers, json=data)
    return result


if __name__ == "__main__":
    wurl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=2048***********自行申请***********dc59"
    files = os.listdir("/tmp")
    for file in files:
        if file.endswith('PNG') and 'tmp' in file:
            post_image(wurl, image="/tmp/" + file)
            sleep(5)
            os.remove("/tmp/" + file)

```
如有其他好方法欢迎交流。y(^~^)y

**Comment by truynal** [comment]
好的大佬，我试试> 多开是正解。但是长时间挂网页版也会触发预警的吧。
> 
> 我都是设定每天定时自启和关闭。
> 
> 用requests将二维码发给自己企业微信群机器人/其他支持curl的机器人，小号去电脑端扫码登录。
> 
> app.py 的 def run() 的 try 中增加如下代码：当然你可以先修改自动生成图片的命名方式，以避免误删文件。
> 
> ```
> 
>     files = os.listdir("/tmp")
> 
>         for file in files:
> 
>             if file.endswith('PNG') and 'tmp' in file:
> 
>                 os.remove("/tmp/" + file)
> 
> ```
> 
> 利用原本文件夹 \chatgpt-on-wechat\scripts 中的 bash 脚本，再设置定时。
> 
> 我也修改了对应文件：
> 
> start.sh
> 
> ```
> 
> #!/bin/bash
> 
> #后台运行Chat_on_wechat执行脚本
> 
> 
> 
> cd `dirname $0`/..
> 
> export BASE_DIR=`pwd`
> 
> echo $BASE_DIR
> 
> 
> 
> # check the nohup.out log output file
> 
> if [ ! -f "${BASE_DIR}/nohup.out" ]; then
> 
>   touch "${BASE_DIR}/nohup.out"
> 
> echo "create file  ${BASE_DIR}/nohup.out"
> 
> fi
> 
> 
> 
> nohup python3.9 "${BASE_DIR}/app.py" &
> 
> sleep 5
> 
> nohup python3.9 "${BASE_DIR}/weworkqr.py" &
> 
> 
> 
> echo "Chat_on_wechat is starting，you can check the ${BASE_DIR}/nohup.out"
> 
> 
> 
> exit 0
> 
> ```
> 
> shutdown.sh
> 
> ```
> 
> #!/bin/bash
> 
> 
> 
> #关闭服务
> 
> pid=`ps -ef | grep python3.9 | grep "app.py" | grep -v grep | awk '{print $2}'`
> 
> if [ -z "$pid" ] ; then
> 
>         echo "No chatgpt-on-wechat running."
> 
>         exit -1;
> 
> fi
> 
> 
> 
> echo "The chatgpt-on-wechat(${pid}) is running..."
> 
> 
> 
> kill ${pid}
> 
> 
> 
> echo "Send shutdown request to chatgpt-on-wechat(${pid}) OK"
> 
> ```
> 
> 增加的 weworkqr.py 文件如下，放在主文件夹下，wework群机器人功能不赘述。
> 
> ```
> 
> # -*- coding:utf-8 -*-
> 
> # 国内服务器用下面镜像
> 
> # pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn pakegename
> 
> # python -m pip install --upgrade pip
> 
> import sys
> 
> import os
> 
> # requests需要提前安装以下依赖
> 
> # pip3 install cryptography
> 
> # pip3 install pyOpenSSL
> 
> # pip3 install certifi
> 
> # pip install requests
> 
> import requests
> 
> import importlib
> 
> import base64
> 
> import hashlib
> 
> 
> 
> from time import sleep
> 
> 
> 
> importlib.reload(sys)
> 
> 
> 
> 
> 
> def post_image(wx_url, image):
> 
>     # 转换图片成base64格式
> 
>     with open(image, "rb") as pfile:
> 
>         data = pfile.read()
> 
>         encodestr = base64.b64encode(data)
> 
>         image_data = str(encodestr, "utf-8")
> 
>     # 图片的MD5值
> 
>     with open(image, "rb") as pfile:
> 
>         md = hashlib.md5()
> 
>         md.update(pfile.read())
> 
>         image_md5 = md.hexdigest()
> 
>     headers = {"Content-Type": "application/json;charset=utf-8"}
> 
>     data = {
> 
>         "msgtype": "image",
> 
>         "image": {
> 
>             "base64": image_data,
> 
>             "md5": image_md5
> 
>         }
> 
>     }
> 
>     # body = json.dumps(data)
> 
>     # result = requests.post(url = wx_url, data = body, headers = headers)
> 
>     result = requests.post(url=wx_url, headers=headers, json=data)
> 
>     return result
> 
> 
> 
> 
> 
> if __name__ == "__main__":
> 
>     wurl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=2048***********自行申请***********dc59"
> 
>     files = os.listdir("/tmp")
> 
>     for file in files:
> 
>         if file.endswith('PNG') and 'tmp' in file:
> 
>             post_image(wurl, image="/tmp/" + file)
> 
>             sleep(5)
> 
>             os.remove("/tmp/" + file)
> 
> 
> 
> ```
> 
> 如有其他好方法欢迎交流。y(^~^)y

**Comment by truynal** [comment]
> 多开是正解。但是长时间挂网页版也会触发预警的吧。
> 
> 我都是设定每天定时自启和关闭。
> 
> 用requests将二维码发给自己企业微信群机器人/其他支持curl的机器人，小号去电脑端扫码登录。
> 
> app.py 的 def run() 的 try 中增加如下代码：当然你可以先修改自动生成图片的命名方式，以避免误删文件。
> 
> ```
> 
>     files = os.listdir("/tmp")
> 
>         for file in files:
> 
>             if file.endswith('PNG') and 'tmp' in file:
> 
>                 os.remove("/tmp/" + file)
> 
> ```
> 
> 利用原本文件夹 \chatgpt-on-wechat\scripts 中的 bash 脚本，再设置定时。
> 
> 我也修改了对应文件：
> 
> start.sh
> 
> ```
> 
> #!/bin/bash
> 
> #后台运行Chat_on_wechat执行脚本
> 
> 
> 
> cd `dirname $0`/..
> 
> export BASE_DIR=`pwd`
> 
> echo $BASE_DIR
> 
> 
> 
> # check the nohup.out log output file
> 
> if [ ! -f "${BASE_DIR}/nohup.out" ]; then
> 
>   touch "${BASE_DIR}/nohup.out"
> 
> echo "create file  ${BASE_DIR}/nohup.out"
> 
> fi
> 
> 
> 
> nohup python3.9 "${BASE_DIR}/app.py" &
> 
> sleep 5
> 
> nohup python3.9 "${BASE_DIR}/weworkqr.py" &
> 
> 
> 
> echo "Chat_on_wechat is starting，you can check the ${BASE_DIR}/nohup.out"
> 
> 
> 
> exit 0
> 
> ```
> 
> shutdown.sh
> 
> ```
> 
> #!/bin/bash
> 
> 
> 
> #关闭服务
> 
> pid=`ps -ef | grep python3.9 | grep "app.py" | grep -v grep | awk '{print $2}'`
> 
> if [ -z "$pid" ] ; then
> 
>         echo "No chatgpt-on-wechat running."
> 
>         exit -1;
> 
> fi
> 
> 
> 
> echo "The chatgpt-on-wechat(${pid}) is running..."
> 
> 
> 
> kill ${pid}
> 
> 
> 
> echo "Send shutdown request to chatgpt-on-wechat(${pid}) OK"
> 
> ```
> 
> 增加的 weworkqr.py 文件如下，放在主文件夹下，wework群机器人功能不赘述。
> 
> ```
> 
> # -*- coding:utf-8 -*-
> 
> # 国内服务器用下面镜像
> 
> # pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn pakegename
> 
> # python -m pip install --upgrade pip
> 
> import sys
> 
> import os
> 
> # requests需要提前安装以下依赖
> 
> # pip3 install cryptography
> 
> # pip3 install pyOpenSSL
> 
> # pip3 install certifi
> 
> # pip install requests
> 
> import requests
> 
> import importlib
> 
> import base64
> 
> import hashlib
> 
> 
> 
> from time import sleep
> 
> 
> 
> importlib.reload(sys)
> 
> 
> 
> 
> 
> def post_image(wx_url, image):
> 
>     # 转换图片成base64格式
> 
>     with open(image, "rb") as pfile:
> 
>         data = pfile.read()
> 
>         encodestr = base64.b64encode(data)
> 
>         image_data = str(encodestr, "utf-8")
> 
>     # 图片的MD5值
> 
>     with open(image, "rb") as pfile:
> 
>         md = hashlib.md5()
> 
>         md.update(pfile.read())
> 
>         image_md5 = md.hexdigest()
> 
>     headers = {"Content-Type": "application/json;charset=utf-8"}
> 
>     data = {
> 
>         "msgtype": "image",
> 
>         "image": {
> 
>             "base64": image_data,
> 
>             "md5": image_md5
> 
>         }
> 
>     }
> 
>     # body = json.dumps(data)
> 
>     # result = requests.post(url = wx_url, data = body, headers = headers)
> 
>     result = requests.post(url=wx_url, headers=headers, json=data)
> 
>     return result
> 
> 
> 
> 
> 
> if __name__ == "__main__":
> 
>     wurl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=2048***********自行申请***********dc59"
> 
>     files = os.listdir("/tmp")
> 
>     for file in files:
> 
>         if file.endswith('PNG') and 'tmp' in file:
> 
>             post_image(wurl, image="/tmp/" + file)
> 
>             sleep(5)
> 
>             os.remove("/tmp/" + file)
> 
> 
> 
> ```
> 
> 如有其他好方法欢迎交流。y(^~^)y

这种方式需要手动去扫码登录，有自动扫码登录的吗

**Comment by CHENEY-LANCE** [comment]
服务端的微信大概一天不用，就会自动log out！有什么解决办法吗  ？

**Comment by lanvent** [comment]
see #1139
