### ISSUE TITLE
如何更改API调用地址（Endpoint）？

### ISSUE THREAD

**Issue by chenyuxiangyes** [zhayujie/chatgpt-on-wechat#1131]
### ⚠️ 搜索是否存在类似issue

- [x] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

想使用 https://aiproxy.io/ 的服务，用他们独有的API Key。

### 举例

略。

### 动机

花钱买GPT-4的使用权。

**Comment by chenyuxiangyes** [comment]
其实不只是用GPT-4，提高GPT-3.5的并发能力也好的。

**Comment by bentennysonyoung** [comment]
多API共用需求。
插件功能已实现热加载，更换key是否也可以热加载？
增加类似指令？：
#key-add:""  #key-remove:""  #key-reset

**Comment by lanvent** [comment]
设置openai_api_base，查找下issue

**Comment by jayling1111** [comment]
请问是否解决？docker compose中添加哪个参数？
