### ISSUE TITLE
遇到ModuleNotFoundError: No module named 'requests'，是有什么东西没装吗？

### ISSUE THREAD

**Issue by CobraNow** [zhayujie/chatgpt-on-wechat#1133]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

$ python3.10 app.py
[INFO][2023-05-22 11:43:58][config.py:195] - [INIT] load config: {'open_ai_api_key': ', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': ['AI', '@AI'], 'single_chat_reply_prefix': '[AI] ', 'group_chat_prefix': ['@AI'], 'group_name_white_list': ['ALL_GROUP'], 'group_chat_in_one_session': ['ALL_GROUP'], 'image_create_prefix': ['▒▒', '▒▒', '▒▒', '▒뻭'], 'temperature': 0.3, 'image_create_size': '512x512', 'speech_recognition': True, 'group_speech_recognition': True, 'voice_reply_voice': False, 'conversation_max_tokens': 2000, 'expires_in_seconds': 3600, 'character_desc': '▒▒▒▒AI, ▒▒▒▒▒▒һ▒▒▒▒OpenAIѵ▒▒▒Ĵ▒▒▒▒▒▒▒ģ▒▒, ▒▒ּ▒ڻش𲢽▒▒▒▒▒ǵ▒▒κ▒▒▒▒⣬▒▒▒ҿ▒▒▒ʹ▒ö▒▒▒▒▒▒▒▒▒▒˽▒▒▒▒▒', 'subscribe_msg': '▒▒л▒▒▒Ĺ▒ע▒▒\n▒▒▒▒▒▒ChatGPT▒▒▒▒▒▒▒▒▒ɶԻ▒▒▒\n֧▒▒▒▒▒▒▒Ի▒▒▒\n֧▒▒ͼƬ▒▒▒롣\n֧▒▒ͼƬ▒▒▒▒▒▒▒▒ֿ▒ͷ▒▒▒▒Ϣ▒▒▒▒Ҫ▒▒▒▒ͼƬ▒▒\n֧▒▒tool▒▒▒▒ɫ▒▒▒ݺ▒▒▒▒▒ð▒յȷḻ▒Ĳ▒▒▒▒\n▒▒▒▒{trigger_prefix}#help ▒鿴▒▒ϸָ▒'}
[INFO][2023-05-22 11:43:58][config.py:145] - [Config] User datas file not found, ignore.
[ERROR][2023-05-22 11:43:58][app.py:52] - App startup failed!
[ERROR][2023-05-22 11:43:58][app.py:53] - No module named 'requests'
Traceback (most recent call last):
  File "C:\Users\▒▒▒▒▒▒\Desktop\Project1\chatgpt-on-wechat\app.py", line 45, in run
    channel = channel_factory.create_channel(channel_name)
  File "C:\Users\▒▒▒▒▒▒\Desktop\Project1\chatgpt-on-wechat\channel\channel_factory.py", line 13, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "C:\Users\▒▒▒▒▒▒\Desktop\Project1\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### 问题描述 😯

我一开始电脑里python版本比较杂旧，索性就更新只留下了3.10和3.11版本，之后尝试使用python3时发现有is a directory的问题，搜索后发现是系统环境变量未设置，设置好后便发现无论是输入python3还是3.10或是3.11都只会显示这一个故障，跟着再装了一次依赖后也依旧有，我还没装到插件部分想先试试原装，是插件的问题吗还是什么改错名或者未加载，求大佬们协助！

### 终端日志 📒

```log
<此处粘贴终端日志>
```[INFO][2023-05-22 11:43:58][config.py:145] - [Config] User datas file not found, ignore.
[ERROR][2023-05-22 11:43:58][app.py:52] - App startup failed!
[ERROR][2023-05-22 11:43:58][app.py:53] - No module named 'requests'
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\Project1\chatgpt-on-wechat\app.py", line 45, in run
    channel = channel_factory.create_channel(channel_name)
  File "C:\Users\XXX\Desktop\Project1\chatgpt-on-wechat\channel\channel_factory.py", line 13, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "C:\Users\XXX\Desktop\Project1\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by lanvent** [comment]
清理python环境，或者使用virtualenv吧，从头开始

**Comment by CobraNow** [comment]
> 清理python环境，或者使用virtualenv吧，从头开始

我装了virtualenv，但是应该部署在哪里呢，我部署在appdata和ChatGPT-on-wechat文件夹底下让dir可以显示app.py后启动virtualenv依然是报告上面的request故障，显示的是一摸一样的，我看上面故障list里面wechat和channel的出现比较多，但是不知道是哪里需要怎么修改

**Comment by melonlly** [comment]
python3 app.py
我也遇到了这个报错
