### ISSUE TITLE
使用GPT-4时不定时报流式异常，配置stream=True后报

### ISSUE THREAD

**Issue by RolloTomasiii** [zhayujie/chatgpt-on-wechat#1135]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

在config.json中配置GPT-4的open_ai_api_key，model设置：gpt-4
配置后发现报流式异常，因为openai在60s后就会中断链接
在chat_gpt_bot.py第44行，配置"stream": True,后重启，发现报Exception: 'generator' object is not subscriptable

### 问题描述 😯

无法稳定使用gpt-4
如果作者需要key来复现异常,我可以给您提供。

### 终端日志 📒

[INFO][2023-05-22 15:36:04][chat_gpt_bot.py:49] - [CHATGPT] query=下午好
[DEBUG][2023-05-22 15:36:04][session_manager.py:70] - prompt tokens used=14
[DEBUG][2023-05-22 15:36:04][chat_gpt_bot.py:66] - [CHATGPT] session query=[{'role': 'system', 'content': ''}, {'role': 'user', 'content': '下午好'}]
[WARNING][2023-05-22 15:36:05][chat_gpt_bot.py:142] - [CHATGPT] Exception: 'generator' object is not subscriptable
[DEBUG][2023-05-22 15:36:05][chat_gpt_bot.py:75] - [CHATGPT] new_query=[{'role': 'system', 'content': ''}, {'role': 'user', 'content': '下午好'}], session_id=wxid_bep7f407bkpg22, reply_cont=我现在有点累了，等会再来吧, completion_tokens=0
[DEBUG][2023-05-22 15:36:05][chat_channel.py:146] - [WX] ready to decorate reply: Reply(type=ERROR, content=我现在有点累了，等会再来吧)

**Comment by 726425219** [comment]
我看到您有个还未实现方法 self.reply_text_stream(query, new_query, _session_id)

**Comment by lanvent** [comment]
配置后发现报流式异常，它的exception日志有保存吗，可否发给我看看

**Comment by RolloTomasiii** [comment]
> 配置后发现报流式异常，它的exception日志有保存吗，可否发给我看看

见上文终端日志，我使用DEBUG模式打印的日志，因为深藏方法里，所以不好定位是哪个py文件哪行出的问题，初步怀疑是返回对象的格式解析异常

**Comment by RolloTomasiii** [comment]
项目部署在生产环境，不太方便直接调试打印，我可以把KEY发您，您试试看

**Comment by RolloTomasiii** [comment]
> 配置后发现报流式异常，它的exception日志有保存吗，可否发给我看看

您在关注这个问题吗？

**Comment by lanvent** [comment]
抱歉最近比较忙，没来得及回复了，我询问了一个部署在企业生产环境的朋友，他们没有遇到"配置后发现报流式异常，因为openai在60s后就会中断链接"这个问题，目前并不清楚原因。如果你有能够稳定复现的对话就最好了。

**Comment by RolloTomasiii** [comment]
好的，谢谢
