### ISSUE TITLE
微信版本长时间不聊后的第一句反应非常慢，连续聊的时候不慢，有什么办法改善吗，是我个人现象吗

### ISSUE THREAD

**Issue by zhujiajun3** [zhayujie/chatgpt-on-wechat#1141]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by yr2b** [comment]
你用的是云函数吗

**Comment by zhayujie** [comment]
暂时没遇到过， 免费账号会比较慢而且一分钟只能掉3次，绑卡会加速

**Comment by KngJmmy** [comment]
你们说的绑卡指的是啥？我在VPS中搭建，反应挺好的，没啥问题

**Comment by QAbot-zh** [comment]
这个bug修复了吗？我还有这个现象
