### ISSUE TITLE
机器人的回复永远是【ERROR】我现在有点累了

### ISSUE THREAD

**Issue by jinshi6** [zhayujie/chatgpt-on-wechat#1143]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/90970203/de88296d-6b8e-4c0e-a7c6-61b20c6bc101)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/90970203/efc48c08-3f59-4f40-bd07-3535d4d80547)
求大佬帮忙看一眼

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
应该是 query参数里没有内容导致的，只有一个 ！

**Comment by bentennysonyoung** [comment]
我打！也是有反应的。推荐安装python3.9.x
可能是维护或者IP被BAN了？

**Comment by KngJmmy** [comment]
"open_ai_api_key": "xxx",
  "model": "gpt-4",
  "proxy": "xxx",
  "open_ai_api_base":"https://api.openai.com/v1",
  我遇到过这个问题，调整下key和open_ai_api_base的值试试，我买了个国内转的api，有附带api_base，因为目前我用的是在国外的VPS，所以api_base用的官方的就行，我家里服务器本地搭建我就用的国内的转发api_base，也能行

**Comment by elephantjohn** [comment]
尝试将open-api key的值直接填在 bot/chatgpt/chat_gpt_bot.py 文件中的openai.ChatCompletion.create函数中例如 openai.ChatCompletion.create(api_key="sk-XuFE...xxxx", messages=session,,);
