### ISSUE TITLE
不想天天回复女盆友，有无懂哥指点一二

### ISSUE THREAD

**Issue by EasternCabbage** [zhayujie/chatgpt-on-wechat#1150]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

实现功能如下：
1：女友发消息即可回复，不需要加‘bot’前缀。
（次要）2：针对女友专门设置一个AI性格

 （看不懂代码，太菜了😭）

**Comment by jonntd** [comment]
把你女朋友微信推给我我替你聊啊


EasternCabbage ***@***.***> 于2023年5月26日周五 15:06写道：

**Comment by zhayujie** [comment]
第一个好解决，修改下下面两个配置

"single_chat_prefix": [""],
"single_chat_reply_prefix": ""

**Comment by EasternCabbage** [comment]
> 

感谢大佬回复，但是这个配置是对所有好友的吧。
我想不加bot这个参数只对一个人生效，其他人依旧需要输入bot才能触发会话。
我看了之前的issue，貌似不能针对单一用户修改生效，因为itchat 好友会话id是随机分配的。

**Comment by 6vision** [comment]
> > 
> 
> 感谢大佬回复，但是这个配置是对所有好友的吧。 我想不加bot这个参数只对一个人生效，其他人依旧需要输入bot才能触发会话。 我看了之前的issue，貌似不能针对单一用户修改生效，因为itchat 好友会话id是随机分配的。
itchat协议，微信昵称和备注是固定的

**Comment by bentennysonyoung** [comment]
> > 
> 
> 感谢大佬回复，但是这个配置是对所有好友的吧。 我想不加bot这个参数只对一个人生效，其他人依旧需要输入bot才能触发会话。 我看了之前的issue，貌似不能针对单一用户修改生效，因为itchat 好友会话id是随机分配的。

可以开小号，工作，私人，分开。
