### ISSUE TITLE
有没有一种可能，让机器人那端的聊天记录批量删除？

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#1186]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

咋说呢？因为很多人觉得，加机器人好友，私聊机器人，可能会没有隐私，不愿意用。如果机器人微信这端可以每隔一段时间调用聊天记录删除的话，那么至少在用户层面，会安心一些（虽然只要一个人足够无聊，看日志也是可以看到的）。比如，用户设置隐私模式，那么机器人接收该用户的一段时间session过期之前，都会自动删除机器人这边的聊天记录。

**Comment by congxuma** [comment]
没太懂，删了你的微信端的聊天记录客户端的聊天记录还是在的，别人也不知道你微信端聊天记录删没删
