### ISSUE TITLE
这啥情况，，，今天突然就登录不上去了

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#1189]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

![图片](https://github.com/zhayujie/chatgpt-on-wechat/assets/29570378/c426d75c-fdaf-474f-8475-2637eea61fe1)

**Comment by axiba053** [comment]
我今天也是，开代理就报错，不开代理可以弹出二维码
报错如下：
```
Traceback (most recent call last):
  File "D:\pipeline\venv\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "D:\pipeline\venv\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "D:\pipeline\venv\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\pipeline\venv\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\pipeline\venv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\pipeline\venv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pipeline\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\pipeline\venv\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\pipeline\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pipeline\AI\chatgpt-on-wechat-master\lib\itchat\utils.py", line 134, in test_connect
    r = requests.get(config.BASE_URL)
  File "D:\pipeline\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\pipeline\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\pipeline\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\pipeline\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\pipeline\venv\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

You can't get access to internet or wechat domain, so exit.(test)
```

**Comment by axiba053** [comment]
@Zhaoyi-Yan 那我的情况和你还不太一样，我是在windows电脑直接报错弹不出二维码，后来在mac上就没问题。现在windows上还是不行。。。

**Comment by zhayujie** [comment]
> @Zhaoyi-Yan 那我的情况和你还不太一样，我是在windows电脑直接报错弹不出二维码，后来在mac上就没问题。现在windows上还是不行。。。

你这个大概率是网络问题

**Comment by asilentwolf** [comment]
> @Zhaoyi-Yan 那我的情况和你还不太一样，我是在windows电脑直接报错弹不出二维码，后来在mac上就没问题。现在windows上还是不行。。。
你这个问题解决了吗，跟你同样的问题。 在window服务器上，不开clash代理能出二维码，开了就报这个错。

**Comment by Azad-Aihub** [comment]
> > 我今天也是，开代理就报错，不开代理可以弹出二维码 报错如下：
> > ```
> > Traceback (most recent call last):
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
> >     self._prepare_proxy(conn)
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
> >     conn.connect()
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\connection.py", line 369, in connect
> >     self.sock = conn = self._connect_tls_proxy(hostname, conn)
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
> >     socket = ssl_wrap_socket(
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
> >     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
> >     return ssl_context.wrap_socket(sock)
> >   File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
> >     return self.sslsocket_class._create(
> >   File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
> >     self.do_handshake()
> >   File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
> >     self._sslobj.do_handshake()
> > ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "D:\pipeline\venv\lib\site-packages\requests\adapters.py", line 489, in send
> >     resp = conn.urlopen(
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
> >     retries = retries.increment(
> >   File "D:\pipeline\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
> >     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "D:\pipeline\AI\chatgpt-on-wechat-master\lib\itchat\utils.py", line 134, in test_connect
> >     r = requests.get(config.BASE_URL)
> >   File "D:\pipeline\venv\lib\site-packages\requests\api.py", line 73, in get
> >     return request("get", url, params=params, **kwargs)
> >   File "D:\pipeline\venv\lib\site-packages\requests\api.py", line 59, in request
> >     return session.request(method=method, url=url, **kwargs)
> >   File "D:\pipeline\venv\lib\site-packages\requests\sessions.py", line 587, in request
> >     resp = self.send(prep, **send_kwargs)
> >   File "D:\pipeline\venv\lib\site-packages\requests\sessions.py", line 701, in send
> >     r = adapter.send(request, **kwargs)
> >   File "D:\pipeline\venv\lib\site-packages\requests\adapters.py", line 563, in send
> >     raise SSLError(e, request=request)
> > requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
> > 
> > You can't get access to internet or wechat domain, so exit.(test)
> > ```
> 
> mark 下， 通过降低urllib版本，pip install urllib3==1.25.11 解决了。 [Significant-Gravitas/AutoGPT#1278](https://github.com/Significant-Gravitas/AutoGPT/issues/1278)

看了一圈，就这个可以👍
