### ISSUE TITLE
我并没有看到让我登录我的OpenAI 的账号, 只是填写了一个 Key值, 虽然智能,但是比起 https://chat.openai.com/chat 上的还是有点差距. 我只看到了“text-davinci-003” 对话模型名称,是不是意味着这并不是真正的 chatGPT 呢 ?

### ISSUE THREAD

**Issue by CocoaJiang** [zhayujie/chatgpt-on-wechat#119]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Ratten-fanger** [comment]
API-KEY已经包含了你的账号信息，因此不需要登录。
目前OPENAI提供的最新API模型就是GPT3.0，而运行在官网的是3.5，模型不同自然有差距

**Comment by CocoaJiang** [comment]
十分感谢您
