### ISSUE TITLE
寻找增加API额度的方法

### ISSUE THREAD

**Issue by yuanhaozuogenius** [zhayujie/chatgpt-on-wechat#1196]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1. 启动app.py
2. 日志提示: RateLimitError: You exceeded your current quota, please check your plan and billing details.
3. 寻找增加API额度的方法

### 问题描述 😯

类似#1111，自己的API近日也到期了。

交流群里看到有这样的账号，请问有人知道是怎么获取的额度吗？除了氪还有别的方式可以获得额度🐴
<img width="1533" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/43596715/e665d4fc-e12c-42f6-8dd2-4b096823efce">

貌似和微软startup计划有关？ 

### 终端日志 📒

```log
[INFO][2023-06-02 10:59:15][chat_gpt_bot.py:56] - [CHATGPT] query=1231231
[WARNING][2023-06-02 10:59:15][chat_gpt_bot.py:142] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
```

**Comment by axiba053** [comment]
这个11月到期，好奇用的完么

**Comment by yuanhaozuogenius** [comment]
> 这个11月到期，好奇用的完么

这个看起来更像是某种渠道给的额度 日常提问肯定是用不完了

**Comment by congxuma** [comment]
申请网址：https://openai.com/microsoft-for-startups
https://web.okjike.com/originalPost/645d81df502f200fae5bb496

**Comment by Zhaoyi-Yan** [comment]
![图片](https://github.com/zhayujie/chatgpt-on-wechat/assets/29570378/683ea3dc-5fdf-4f3c-9daa-e0f7a36fdd39)
https://51.ruyo.net/18360.html

**Comment by yuanhaozuogenius** [comment]
> 申请网址：https://openai.com/microsoft-for-startups https://web.okjike.com/originalPost/645d81df502f200fae5bb496

加精了，害得是github啊
