### ISSUE TITLE
前面已经查看了很多issues，尝试后还是出现【我连接不到你的网络】

### ISSUE THREAD

**Issue by xiaoshaniu** [zhayujie/chatgpt-on-wechat#1199]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[INFO][2023-06-02 15:10:54][bridge.py:32] - create bot chatGPT for chat
[INFO][2023-06-02 15:10:54][chat_gpt_bot.py:49] - [CHATGPT] query=我的歌
[WARNING][2023-06-02 15:10:54][chat_gpt_bot.py:149] - [CHATGPT] **APIConnectionError: Error communicating with OpenAI:** ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[INFO][2023-06-02 15:10:54][wechat_channel.py:186] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@43d012cf8ddb20a8dd2a4dc51b68c7a1872a1b7f3a450f7ec29242f471219e37

[INFO][2023-06-02 15:11:26][chat_gpt_bot.py:49] - [CHATGPT] query=你太难整了吧
[WARNING][2023-06-02 15:11:26][chat_gpt_bot.py:149] - [CHATGPT] **APIConnectionError: Error communicating with OpenAI:** ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[INFO][2023-06-02 15:11:26][wechat_channel.py:186] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@43d012cf8ddb20a8dd2a4dc51b68c7a1872a1b7f3a450f7ec29242f471219e37

### 问题描述 😯

1，本地部署的，已开启vpn全局模式，可以正常访问https://chat.openai.com/网站；
2，当我启动后，微信触发后， 提示【我连接不到你的网络】

### 终端日志 📒

```log
[INFO][2023-06-02 15:11:26][chat_gpt_bot.py:49] - [CHATGPT] query=你太难整了吧
[WARNING][2023-06-02 15:11:26][chat_gpt_bot.py:149] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[INFO][2023-06-02 15:11:26][wechat_channel.py:186] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@43d012cf8ddb20a8dd2a4dc51b68c7a1872a1b7f3a450f7ec29242f471219e37
```

**Comment by 13592491893** [comment]
@xiaoshaniu 怎么弄啊

**Comment by monk-after-90s** [comment]
看看后台是不是启动了多个程序实例
