### ISSUE TITLE
运行后，回复一直都是‘提问太快了啦，请休息一下再问我吧’,

### ISSUE THREAD

**Issue by 1604653069** [zhayujie/chatgpt-on-wechat#120]
### 前置确认

一直报这个错
Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.

![image](https://user-images.githubusercontent.com/29847018/217704824-c2f41228-337f-4765-92c1-88cd054120d7.png)

**Comment by 1604653069** [comment]
这个是我的key不行吗？还是怎么回事？  求助

**Comment by Rwindest168888** [comment]
key没流量了吧，官司网查下就知了

**Comment by 1604653069** [comment]
![image](https://user-images.githubusercontent.com/29847018/217708503-1dc52d0a-59b4-403a-b1d5-f5ddb086b07b.png)
有的呀，新注册的
