### ISSUE TITLE
执行pip3 install -r requirements.txt时报错，提供的可选版本里都低于requirements.txt文件中的版本，需要升级什么吗？

### ISSUE THREAD

**Issue by zhiwen-Jiang** [zhayujie/chatgpt-on-wechat#1200]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

git clone https://github.com/zhayujie/chatgpt-on-wechat
cd chatgpt-on-wechat/
pip3 install -r requirements.txt

### 问题描述 😯

文件里的版本是：
openai==0.27.2
HTMLParser>=0.0.2
PyQRCode>=1.2.1
qrcode>=7.4.2
requests>=2.28.2
chardet>=5.1.0
Pillow
pre-commit
但是运行 pip3 install -r requirements.txt时，报下面的错，使用0.10.5就正常，是需要升级什么吗？
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting openai==0.27.2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement openai==0.27.2 (from -r requirements.txt (line 1)) (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
No matching distribution found for openai==0.27.2 (from -r requirements.txt (line 1))

### 终端日志 📒

WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting openai==0.27.2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement openai==0.27.2 (from -r requirements.txt (line 1)) (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
No matching distribution found for openai==0.27.2 (from -r requirements.txt (line 1))

**Comment by zhiwen-Jiang** [comment]
哦，没注意，我要手动升级这些包。打扰了

**Comment by wangjueszu** [comment]
这个问题，我也遇到了。没理解如何手动升级这些包

**Comment by MrSleeplessC** [comment]
同样遇到这样的问题，现在是0.27.8，也报这种问题。该如何查看这些包的最新版本号？
