### ISSUE TITLE
微信和企业微信的回复差别跟大，请大佬指教怎么回事

### ISSUE THREAD

**Issue by easydune** [zhayujie/chatgpt-on-wechat#1201]
![Screenshot_20230602_205256_com.tencent.mm_edit_81937049494266.jpg](https://github.com/zhayujie/chatgpt-on-wechat/assets/40026257/5064bdd8-fd61-4b94-9a3c-70920eb3233c)

![Screenshot_20230602_205250_com.tencent.wework_edit_81983602573426.jpg](https://github.com/zhayujie/chatgpt-on-wechat/assets/40026257/cbbb9b50-9f54-4265-ab2a-eeb3fd2077ad)

**Comment by easydune** [comment]
在补胎的时候打开微信和企业微信问的，之前没问过相关问题

**Comment by lanvent** [comment]
多重启程序多试几遍呢

**Comment by lanvent** [comment]
因为chatgpt的回答不是固定的，如果这个问题能够稳定复现的话，那它就是一个问题了

**Comment by alexhmyang** [comment]
> 在补胎的时候打开微信和企业微信问的，之前没问过相关问题，微信和企业微信所有配置全部一样API KEY也一模一样，同一个时间问的，前后不差1分钟

请问你这个 企业微信 是 企业微信自建应用 还是 可以加客户的企业微信号 ， 怎么对接这个chatgpt呢，官方教程是 企业自建应用 ，无法加客户

**Comment by lanvent** [comment]
后者目前还不支持

**Comment by easydune** [comment]
> > 在补胎的时候打开微信和企业微信问的，之前没问过相关问题，微信和企业微信所有配置全部一样API KEY也一模一样，同一个时间问的，前后不差1分钟
> 
> 请问你这个 企业微信 是 企业微信自建应用 还是 可以加客户的企业微信号 ， 怎么对接这个chatgpt呢，官方教程是 企业自建应用 ，无法加客户

企业微信的自建应用
