### ISSUE TITLE
这个部署的服务器时间正常，为什么它回复的一直是2020年3月31日

### ISSUE THREAD

**Issue by kusila** [zhayujie/chatgpt-on-wechat#121]
![image](https://user-images.githubusercontent.com/28586954/217705504-969b4c03-6c8e-458c-b6fe-e246b1c1375a.png)
<img width="435" alt="image" src="https://user-images.githubusercontent.com/28586954/217705618-994fc9af-b79b-4b56-8eff-1efd9e071f08.png">

**Comment by kusila** [comment]
> 

官网问今天日期，回答的是对的呢？

**Comment by Rwindest168888** [comment]
![2023-02-09_111456](https://user-images.githubusercontent.com/124567966/217709062-29b40760-2274-4b1f-bf46-7db6a5c881b0.jpg)
我问的是这样的

**Comment by kusila** [comment]
> ![2023-02-09_111456](https://user-images.githubusercontent.com/124567966/217709062-29b40760-2274-4b1f-bf46-7db6a5c881b0.jpg) 我问的是这样的

![image](https://user-images.githubusercontent.com/28586954/217709482-b53cc4d0-26d9-422b-8718-1e7acc05bcc0.png)
是不是没用chatGPT最新的版本呀~

**Comment by colorfbalck** [comment]
![image](https://user-images.githubusercontent.com/124777439/217709634-281eb740-a1ea-4c21-95c0-051705367e0e.png)

**Comment by colorfbalck** [comment]
我这个为什么是这个时间

**Comment by kusila** [comment]
> 

时间是随机的好像，但是感觉回答的问题和官网的还是有点区别。

**Comment by colorfbalck** [comment]
怎么感觉他模型是3年前，好多数据都是截止到2020年

**Comment by kusila** [comment]
> 怎么感觉他模型是3年前，好多数据都是截止到2020年

官方好像就是到2021年前的数据，就是相同的问题感觉回答的没有官网回答的好，准确率也一般。作者大哥知道为啥不

**Comment by zhayujie** [comment]
> > 怎么感觉他模型是3年前，好多数据都是截止到2020年
> 
> 官方好像就是到2021年前的数据，就是相同的问题感觉回答的没有官网回答的好，准确率也一般。作者大哥知道为啥不

不是一个模型，官网是 gpt-3.5，接口是gpt-3

**Comment by zhayujie** [comment]
> > 怎么感觉他模型是3年前，好多数据都是截止到2020年
> 
> 官方好像就是到2021年前的数据，就是相同的问题感觉回答的没有官网回答的好，准确率也一般。作者大哥知道为啥不

不是一个模型，官网是 chatgpt，接口是gpt-3
