### ISSUE TITLE
开了代理就报错SSLError，关闭代理能扫码登录，但无法连接chatgpt

### ISSUE THREAD

**Issue by axiba053** [zhayujie/chatgpt-on-wechat#1211]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Traceback (most recent call last):
  File "D:\biosoftware\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\biosoftware\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "D:\biosoftware\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\biosoftware\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\biosoftware\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\biosoftware\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\biosoftware\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\biosoftware\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\biosoftware\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\biosoftware\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\biosoftware\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\chatgpt-on-wechat-master\lib\itchat\utils.py", line 134, in test_connect
    r = requests.get(config.BASE_URL)
  File "D:\AI\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\AI\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\AI\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\AI\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\AI\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

You can't get access to internet or wechat domain, so exit.

Process finished with exit code 0

### 问题描述 😯

类似FAQs里：2.项目启动报错SSL连接失败
按提示做了，如果关了代理确实能扫码登录，但是不能连接chatgpt还是无法解决问题；我原来python版本是3.10，改为3.9也是同样报错。
这个问题不只我遇到了，别人也遇到了，还没解决。
另外，我在mac电脑上使用没有问题。

### 终端日志 📒

```log
[DEBUG][2023-06-05 10:25:10][config.py:196] - [INIT] set log level to DEBUG
[INFO][2023-06-05 10:25:10][config.py:198] - [INIT] load config: {'open_ai_api_key': 'sk-rVGOkHNEdpdoF4mAGT3BlbkFJ0mns0OfL2ag7Pdpdh00', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': [''], 'single_chat_reply_prefix': '', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ALL_GROUP'], 'group_chat_in_one_session': ['ChatGPT测试群'], 'image_create_prefix': ['画', '看', '找'], 'debug': True, 'speech_recognition': True, 'group_speech_recognition': True, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-06-05 10:25:10][config.py:146] - [Config] User datas loaded.
[INFO][2023-06-05 10:25:10][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-06-05 10:25:10][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins\banwords
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins\bdunit
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins\dungeon
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins\finish
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins\godcmd
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins\hello
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins\keyword
[INFO][2023-06-05 10:25:10][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins\role
[INFO][2023-06-05 10:25:11][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins\tool
[DEBUG][2023-06-05 10:25:11][plugin_manager.py:153] - plugins.json config={'plugins': SortedDict({'Godcmd': {'enabled': True, 'priority': 999}, 'Keyword': {'enabled': True, 'priority': 900}, 'Banwords': {'enabled': False, 'priority': 100}, 'tool': {'enabled': True, 'priority': 0}, 'Role': {'enabled': True, 'priority': 0}, 'Dungeon': {'enabled': True, 'priority': 0}, 'BDunit': {'enabled': False, 'priority': 0}, 'Hello': {'enabled': True, 'priority': -1}, 'Finish': {'enabled': True, 'priority': -999}}, sort_func=<lambda>, reverse=True)}
[INFO][2023-06-05 10:25:11][godcmd.py:193] - [Godcmd] 因未设置口令，本次的临时口令为3758。
[INFO][2023-06-05 10:25:11][godcmd.py:208] - [Godcmd] inited
[DEBUG][2023-06-05 10:25:11][keyword.py:34] - [keyword]加载配置文件D:\AI\chatgpt-on-wechat-master\plugins\keyword\config.json
[INFO][2023-06-05 10:25:11][keyword.py:40] - [keyword] {}
[INFO][2023-06-05 10:25:11][keyword.py:42] - [keyword] inited.
[INFO][2023-06-05 10:25:22][tool.py:32] - [tool] inited
[DEBUG][2023-06-05 10:25:22][role.py:62] - [Role] no role found for tag comments 
[INFO][2023-06-05 10:25:22][role.py:69] - [Role] inited
[INFO][2023-06-05 10:25:22][dungeon.py:56] - [Dungeon] inited
[INFO][2023-06-05 10:25:22][hello.py:23] - [Hello] inited
[INFO][2023-06-05 10:25:22][finish.py:23] - [Finish] inited
```

**Comment by 6vision** [comment]
python3.9版本在开了代理的情况下会运行报错，请降低urllib3模块的版本即可，pip install urllib3==1.25.11

**Comment by axiba053** [comment]
感谢！
