### ISSUE TITLE
pip3 install -r requirements.txt 失败

### ISSUE THREAD

**Issue by wangjueszu** [zhayujie/chatgpt-on-wechat#1219]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
### 服务器位置?
美国服务器

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

```
git clone https://github.com/zhayujie/chatgpt-on-wechat
cd chatgpt-on-wechat/
```
```
[root@racknbd0 chatgpt-on-wechat]# python3 --version
Python 3.8.16
```
```
[root@racd0 chatgpt-on-wechat]# git pull
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), 1.37 KiB | 469.00 KiB/s, done.
From https://github.com/zhayujie/chatgpt-on-wechat
   dfe1c23..f66df85  master     -> origin/master
Updating dfe1c23..f66df85
Fast-forward
 README.md | 6 ------
 1 file changed, 6 deletions(-)
```
```
[root@rackd0 chatgpt-on-wechat]# pip3 install --no-cache-dir -r requirements.txt
ERROR: Could not find a version that satisfies the requirement openai==0.27.2 (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
ERROR: No matching distribution found for openai==0.27.2
```
无法解决，也尝试了yum update，无效。

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/5095602/2781edd4-959b-424d-868f-d1d3fa9a4c1a)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
更新下 pip 试试， pip3 install --upgrade pip

**Comment by zwlsix** [comment]
这种情况也可以使用pip3的-i参数改变python库的镜像源来解决

**Comment by Kevin-free** [comment]
> python3.8 -m pip install --no-cache-dir -r requirements.txt

你好，我遇到和你同样的问题。按你的解决方案，执行：
python3 -m ensurepip --upgrade
Requirement already up-to-date: setuptools in /usr/lib/python3.6/site-packages
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages
应该怎么办呢？

**Comment by Kevin-free** [comment]
> > python3.8 -m pip install --no-cache-dir -r requirements.txt
> 
> 你好，我遇到和你同样的问题。按你的解决方案，执行： python3 -m ensurepip --upgrade Requirement already up-to-date: setuptools in /usr/lib/python3.6/site-packages Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages 应该怎么办呢？

@wangjueszu

**Comment by Meng-de-Cao** [comment]
安装的时候换个pip源就行了 ：
pip3 install -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
