### ISSUE TITLE
 itchat 现在很容易被封号，能否改成企业微信方式？

### ISSUE THREAD

**Issue by tenylu** [zhayujie/chatgpt-on-wechat#123]
最近好多chatgpt bot都用itchat，导致微信大量封号，能否升级成企业微信的api，这样一劳永逸~~

**Comment by colorfbalck** [comment]
有没有企业微信机器人

**Comment by wwb306** [comment]
已经被警告了

**Comment by kusila** [comment]
![image](https://user-images.githubusercontent.com/28586954/217737308-7feacecf-ba47-4664-8d71-8090cde39852.png)
已被封禁~

**Comment by shangdibaozi** [comment]
2个号都被封了。fk

**Comment by colorfbalck** [comment]
我换成小号了，暂时没有提醒。你们是多久提醒的 发了多少消息啊

**Comment by zhayujie** [comment]
企业微信机器人的话只能在 企业微信群使用了，是不是不太方便

**Comment by ayaweiy** [comment]
> 企业微信机器人的话只能在 企业微信群使用了，是不是不太方便

这个能不能将chatGPT变成一个回复机器人？如果不加唤醒词，只需要是指定群聊就可以自动回复？

**Comment by xiemobiao** [comment]
> 我换成小号了，暂时没有提醒。你们是多久提醒的 发了多少消息啊

昨天下午搭建的，发了几条消息，今天下午突然退出去，再登录就提示被封了

**Comment by zhayujie** [comment]
> > 企业微信机器人的话只能在 企业微信群使用了，是不是不太方便
> 
> 这个能不能将chatGPT变成一个回复机器人？如果不加唤醒词，只需要是指定群聊就可以自动回复？

你是说在企业微信群，还是微信群？

**Comment by ayaweiy** [comment]
> 

微信群。比方说，我建立一个在config.json里写好群名的群（如chatGPT测试群），在这个群里只要别人说话，就都是API的回复。或者在这个群里只要是我问话，不需要任何唤醒词都可以回复。

**Comment by fj9876** [comment]
> 企业微信机器人的话只能在 企业微信群使用了，是不是不太方便

个人认为这个应该可以实现，就是微信账号创建的群聊可以转换为企业微信群，然后再把群主转让回微信号，这个时候微信里面显示是企业微信群，但是企业微信显示是由微信用户创建。这样再通过企业号登录使用既方便，又不会封微信号了，建议大佬考虑下

**Comment by zhayujie** [comment]
> > 企业微信机器人的话只能在 企业微信群使用了，是不是不太方便
> 
> 个人认为这个应该可以实现，就是微信账号创建的群聊可以转换为企业微信群，然后再把群主转让回微信号，这个时候微信里面显示是企业微信群，但是企业微信显示是由微信用户创建。这样再通过企业号登录使用既方便，又不会封微信号了，建议大佬考虑下

这种属于外部群，企业微信不一定有支持的接口

**Comment by colorfbalck** [comment]
只有使用过基本都遭封号提醒了

**Comment by colorfbalck** [comment]
企业微信通过第三方应用进行管理

**Comment by zhayujie** [comment]
> 企业微信通过第三方应用进行管理

这个有方案吗

**Comment by designbyly** [comment]
？？？

**Comment by SunknightCzy** [comment]
纵有许多不便，不会封号，还能从微信查看，就是最大的优点了
