### ISSUE TITLE
railway部署如何对接公众号

### ISSUE THREAD

**Issue by Nothingness-Void** [zhayujie/chatgpt-on-wechat#1259]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

无

### 问题描述 😯

想知道在railway上面部署如何填写环境变量中的"wechatmp_port": 8080,
和如何在公众号端口上填写url 
测试下来 端口填写443 公众号填写https://xxx.railway.com/wx 貌似不太行 会出现Token验证失败
本人实在是搞不明白了，故来求助各位大佬

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by chenwenfeng** [comment]
对接不了 貌似微信访问不了railway 要在国内部署
