### ISSUE TITLE
按照文档在企业微信做了部署，经测试可以正常收发消息。请问大家接下来如何把部署好的机器人应用作为企业微信客服分享出去

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#1266]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

按照这个项目的企业微信部署方法成功创建了机器人应用，并且基于chatgpt-on-wechat可以和chatgpt通讯。能够正常收发消息。
目前的问题是，机器人应用只能在企业微信里自己用，但是没法推送或者分享给别人。
我接下来该如何操作才可以让部署的机器人应用作为企业微信客户为用户服务?

谢谢解答，提前谢过！

### 问题描述 😯

按照这个项目的企业微信部署方法成功创建了机器人应用，并且基于chatgpt-on-wechat可以和chatgpt通讯。能够正常收发消息。
目前的问题是，机器人应用只能在企业微信里自己用，但是没法推送或者分享给别人。
我接下来该如何操作才可以让部署的机器人应用作为企业微信客户为用户服务?

谢谢解答，提前谢过！

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhangzhanhui** [comment]
哪位大神知道企业微信部署后怎么对接企业微信客服吗？

**Comment by zhangzhanhui** [comment]
在配置企业微信客服API的url时，填了9898结尾的"wechatcomapp服务地址，显示回调成功。但是往对应的企业微信客服发消息时后台都显示类似下面的日志，且收不到客户端发的消息。请问怎么改才可以和企业微信客服对接？

[INFO][2023-06-22 03:40:59][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {'nonce': '1687927148', 'echostr': 'NH11N5PmoYss9ybo1JO/k3a07XtmRROcc5uYNmTEXgJL9oh/IorIxBYgF4WPPxGFRzRyGw7/C2QVQI41Xz2QBQ==', 'msg_signature': 'c66161972506fe228d1af793600151e8bc771543', 'timestamp': '1687419669'}>
113.xxx.x9x.100:53466 - - [22/Jun/2023 03:40:59] "HTTP/1.1 GET /wxcomapp" - 200 OK
[INFO][2023-06-22 03:41:00][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {'nonce': '1687727633', 'echostr': 'mmnsco2vK5NLgTKdJ45E9fBvcPwtbTsT4bZhFfNa2aA9F9bYH/f+BdsZkoYjDnHiqZGAHL+sI4ag29lsFDBWsg==', 'msg_signature': '78a36e6403ffe2935a004fa21c517747f581ba8c', 'timestamp': '1687419669'}>
113.xxx.xx2.100:54056 - - [22/Jun/2023 03:41:00] "HTTP/1.1 GET /wxcomapp" - 200 OK

**Comment by 6vision** [comment]
目前只支持企业自建应用

**Comment by whyiskey** [comment]
> 在配置企业微信客服API的url时，填了9898结尾的"wechatcomapp服务地址，显示回调成功。但是往对应的企业微信客服发消息时后台都显示类似下面的日志，且收不到客户端发的消息。请问怎么改才可以和企业微信客服对接？
> 
> [INFO][2023-06-22 03:40:59][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {'nonce': '1687927148', 'echostr': 'NH11N5PmoYss9ybo1JO/k3a07XtmRROcc5uYNmTEXgJL9oh/IorIxBYgF4WPPxGFRzRyGw7/C2QVQI41Xz2QBQ==', 'msg_signature': 'c66161972506fe228d1af793600151e8bc771543', 'timestamp': '1687419669'}> 113.xxx.x9x.100:53466 - - [22/Jun/2023 03:40:59] "HTTP/1.1 GET /wxcomapp" - 200 OK [INFO][2023-06-22 03:41:00][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {'nonce': '1687727633', 'echostr': 'mmnsco2vK5NLgTKdJ45E9fBvcPwtbTsT4bZhFfNa2aA9F9bYH/f+BdsZkoYjDnHiqZGAHL+sI4ag29lsFDBWsg==', 'msg_signature': '78a36e6403ffe2935a004fa21c517747f581ba8c', 'timestamp': '1687419669'}> 113.xxx.xx2.100:54056 - - [22/Jun/2023 03:41:00] "HTTP/1.1 GET /wxcomapp" - 200 OK

一样的问题

**Comment by zhangzhanhui** [comment]
> 

谢谢答复~

**Comment by zhangzhanhui** [comment]
> > 在配置企业微信客服API的url时，填了9898结尾的"wechatcomapp服务地址，显示回调成功。但是往对应的企业微信客服发消息时后台都显示类似下面的日志，且收不到客户端发的消息。请问怎么改才可以和企业微信客服对接？
> > [INFO][2023-06-22 03:40:59][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {'nonce': '1687927148', 'echostr': 'NH11N5PmoYss9ybo1JO/k3a07XtmRROcc5uYNmTEXgJL9oh/IorIxBYgF4WPPxGFRzRyGw7/C2QVQI41Xz2QBQ==', 'msg_signature': 'c66161972506fe228d1af793600151e8bc771543', 'timestamp': '1687419669'}> 113.xxx.x9x.100:53466 - - [22/Jun/2023 03:40:59] "HTTP/1.1 GET /wxcomapp" - 200 OK [INFO][2023-06-22 03:41:00][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {'nonce': '1687727633', 'echostr': 'mmnsco2vK5NLgTKdJ45E9fBvcPwtbTsT4bZhFfNa2aA9F9bYH/f+BdsZkoYjDnHiqZGAHL+sI4ag29lsFDBWsg==', 'msg_signature': '78a36e6403ffe2935a004fa21c517747f581ba8c', 'timestamp': '1687419669'}> 113.xxx.xx2.100:54056 - - [22/Jun/2023 03:41:00] "HTTP/1.1 GET /wxcomapp" - 200 OK
> 
> 一样的问题

感觉像是chatgpt-on-wechat在接口上没有做兼容，可能还需要大佬支持

**Comment by n0whereRuoxi** [comment]
@6vision 请问产生这个问题的原因是什么呢？

**Comment by n0whereRuoxi** [comment]
@zhangzhanhui 你好，可以打听一下你现在的替代解决方案吗？

**Comment by cocomany** [comment]
我也很感兴趣

**Comment by zhayujie** [comment]
企微应用分享需要将用户拉入企业。
目前已支持企微个人号，支持群聊
