### ISSUE TITLE
二维码扫描后出现报错'wxsid'

### ISSUE THREAD

**Issue by HotDog1010** [zhayujie/chatgpt-on-wechat#127]
![image](https://user-images.githubusercontent.com/124560017/217737390-177ab7e6-7839-4e66-9456-284340791ab0.png)

**Comment by HotDog1010** [comment]
![image](https://user-images.githubusercontent.com/124560017/217744912-ecad7798-9382-41da-8da4-4cd3ebacd482.png)

**Comment by zhayujie** [comment]
先卸载itchat，然后安装itchat-uos 1.5.0.dev0版本
