### ISSUE TITLE
Link.ai接入别的应用

### ISSUE THREAD

**Issue by MGeorge01** [zhayujie/chatgpt-on-wechat#1270]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

Link.ai能否接入自己开发的基于chatgpt的api的应用，而不是局限于本项目

### 动机

想做一个简易版本的微信chatbot，并接入自己的知识库

**Comment by zhayujie** [comment]
很快会提供api 供其他项目接入

**Comment by MGeorge01** [comment]
十分感谢作者！
