### ISSUE TITLE
tool里的news功能无法正常使用

### ISSUE THREAD

**Issue by joyce677** [zhayujie/chatgpt-on-wechat#1272]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用news-api 工具只会出现以下两种情况，两种情况都导致最后无法成功使用上news工具。

1.已经正确的配置了News的api，但是经常在tool里没有使用上，根据API的响应结果，我们可以看到API key无效或不正确的错误信息。

2.在没有任何改动的情况下，偶尔news-api的API KEY又能正常使用上，而且能正确的返回结果，但是LLM-OS会重复去提问，导致超过了openai的提问速率，最后返回结果失败。

### 问题描述 😯

[INFO][2023-06-25 18:12:02][victorinox.py:111] - 提问: iphone15有关的新闻
﻿[INFO][2023-06-25 18:12:07][base.py:222] - LLM-OS想和你说：你可以使用 news 工具中的 news-api 子工具来获取关于 iPhone 15 的新闻。
﻿[INFO][2023-06-25 18:12:07][base.py:227] - LLM-OS的内心独白:
﻿推理：用户想要获取关于 iPhone 15 的新闻，可以使用 news 工具中的 news-api 子工具来获取实时新闻资讯。
﻿[INFO][2023-06-25 18:12:07][base.py:177] - 执行Tool: news中...
﻿[INFO][2023-06-25 18:12:07][base.py:115] - 输入: iphone15的新闻
﻿[INFO][2023-06-25 18:12:07][tool_engine.py:134] - 我将给工具发送如下信息:
﻿iphone15的新闻
﻿[INFO][2023-06-25 18:12:08][base.py:128] - 执行Tool: news-api中...
﻿[INFO][2023-06-25 18:12:08][bot.py:108] - 输入: "What are the top headlines for iPhone 15 news?"
﻿[INFO][2023-06-25 18:12:08][tool_engine.py:134] - 我将给工具发送如下信息:
﻿"What are the top headlines for iPhone 15 news?"
﻿[INFO][2023-06-25 18:12:10][base.py:77] - URL 构造: https://newsapi.org/v2/top-headlines?q=iPhone%2015&pageSize=5&apiKey=YOUR_API_KEY
﻿[INFO][2023-06-25 18:12:10][base.py:87] - API 响应: '{"status":"error","code":"apiKeyInvalid","message":"Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org/ to create a free API key."}'
﻿[WARNING][2023-06-25 18:12:10][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-vDISzRcmq5OhpP1c3Nx54xCM on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
﻿[INFO][2023-06-25 18:12:34][tool_engine.py:163] - 工具 news-api 返回内容: 根据API的响应结果，我们可以看到API key无效或不正确的错误信息。这意味着我们无法使用该API URL来获取iPhone 15新闻的头条。因此，我们需要先确保我们的API key是有效的，并且在API URL中正确地使用它。如果我们的API key有效并且我们正确地使用了它，那么我们可以使用以下API URL来获取iPhone 15新闻的头条：
﻿https://newsapi.org/v2/top-headlines?q=iPhone%2015&pageSize=5&apiKey=YOUR_API_KEY
﻿请注意，我们在API URL中使用了正确的endpoint和参数，以确保我们只获取与iPhone 15相关的头条新闻，并且我们只获取5条结果。因此，我们可以使用上述API URL来回答用户的问题：“What are the top headlines for iPhone 15 news?”，并提供相关的新闻头条。
﻿[INFO][2023-06-25 18:12:34][tool_engine.py:193] - 我从[news-api]中获得了一些信息：
﻿'根据API的响应结果，我们可以看到API key无效或不正确的错误信息。这意味着我们无法使用该API URL来获取iPhone 15新闻的头条。因此，我们需要先确保我们的API key是有效的，并且在API URL中正确地使用它。如果我们的API key有效并且我们正确地使用了它，那么我们可以使用以下API URL来获取iPhone 15新闻的头条：\n\nhttps://newsapi.org/v2/top-headlines?q=iPhone%2015&pageSize=5&apiKey=YOUR_API_KEY\n\n请注意，我们在API URL中使用了正确的endpoint和参数，以确保我们只获取与iPhone 15相关的头条新闻，并且我们只获取5条结果。因此，我们可以使用上述API URL来回答用户的问题：“What are the top headlines for iPhone 15 news?”，并提供相关的新闻头条。'
﻿[WARNING][2023-06-25 18:12:35][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-vDISzRcmq5OhpP1c3Nx54xCM on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
﻿[INFO][2023-06-25 18:12:52][base.py:128] - 执行Tool: news-api中...
﻿[INFO][2023-06-25 18:12:52][bot.py:108] - 输入: "What are the top headlines for iPhone 15 news?"
﻿[INFO][2023-06-25 18:12:52][tool_engine.py:134] - 我将给工具发送如下信息:
﻿"What are the top headlines for iPhone 15 news?"
﻿[WARNING][2023-06-25 18:12:52][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-vDISzRcmq5OhpP1c3Nx54xCM on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
﻿[INFO][2023-06-25 18:13:08][base.py:77] - URL 构造: https://newsapi.org/v2/top-headlines?q=iPhone%2015&pageSize=5&apiKey=YOUR_API_KEY
﻿[INFO][2023-06-25 18:13:08][base.py:87] - API 响应: '{"status":"error","code":"apiKeyInvalid","message":"Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org/ to create a free API key."}'
﻿[WARNING][2023-06-25 18:13:08][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-vDISzRcmq5OhpP1c3Nx54xCM on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
﻿[INFO][2023-06-25 18:13:33][tool_engine.py:163] - 工具 news-api 返回内容: 根据API的响应结果，我们可以看到API key无效或不正确的错误信息。这意味着我们无法使用该API URL来获取iPhone 15新闻的头条。因此，我们需要先确保我们的API key是有效的，并且在API URL中正确地使用它。如果我们的API key有效并且我们正确地使用了它，那么我们可以使用以下API URL来获取iPhone 15新闻的头条：
﻿https://newsapi.org/v2/top-headlines?q=iPhone%2015&pageSize=5&apiKey=YOUR_API_KEY
﻿请注意，我们在API URL中使用了正确的endpoint和参数，以确保我们只获取与iPhone 15相关的头条新闻，并且我们只获取5条结果。因此，我们可以使用上述API URL来回答用户的问题：“What are the top headlines for iPhone 15 news?”，并提供他们所需的必要信息。
﻿[INFO][2023-06-25 18:13:33][tool_engine.py:193] - 我从[news-api]中获得了一些信息：
﻿'根据API的响应结果，我们可以看到API key无效或不正确的错误信息。这意味着我们无法使用该API URL来获取iPhone 15新闻的头条。因此，我们需要先确保我们的API key是有效的，并且在API URL中正确地使用它。如果我们的API key有效并且我们正确地使用了它，那么我们可以使用以下API URL来获取iPhone 15新闻的头条：\n\nhttps://newsapi.org/v2/top-headlines?q=iPhone%2015&pageSize=5&apiKey=YOUR_API_KEY\n\n请注意，我们在API URL中使用了正确的endpoint和参数，以确保我们只获取与iPhone 15相关的头条新闻，并且我们只获取5条结果。因此，我们可以使用上述API URL来回答用户的问题：“What are the top headlines for iPhone 15 news?”，并提供他们所需的必要信息。'
﻿[INFO][2023-06-25 18:13:33][tool_engine.py:163] - 工具 news 返回内容: Bot stopped due to max iterations.
﻿[INFO][2023-06-25 18:13:33][tool_engine.py:193] - 我从[news]中获得了一些信息：
﻿'Bot stopped due to max iterations.'
﻿[INFO][2023-06-25 18:13:33][wechat_channel.py:183] - [WX] sendMsg=Reply(type=TEXT, content=[AI]Bot stopped due to max iterations.), receiver=@bc3a2929b9fa1105143613023c54168bd36c357bbdcfa9703dfca890954b0834

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Francis776** [comment]
{
  "tools": [
    "python",
    "url-get",
    "terminal",
    "meteo-weather",
    "bing-search",
    "news",
    "wolfram-alpha",
    "arxiv"
  ],
  "kwargs": {
    "top_k_results": 2,
    "think_depth": 3,
    "no_default": false,
    "model_name": "gpt-3.5-turbo",
    "bing_subscription_key": "2eb0bf60ee774223b927846778a****",
    "news_api_key": "090de6a2318d43c195eccf4ba4e****",
    "morning_news_api_key": "kxNtVzK1orx8****",
    "wolfram_alpha_appid": "5HH6WY-TWRQW7****",
    "arxiv_summary:":false
  }
}

**Comment by befantasy** [comment]
重复提问，超出API频次限制，可能是"think_depth": 3导致的，把这个改成2或者1试试。
