### ISSUE TITLE
使用docker正常启动，微信扫描登陆之后，出发不了自动回复

### ISSUE THREAD

**Issue by liuzjccc** [zhayujie/chatgpt-on-wechat#1277]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/24708993/dba7649b-0a07-47d0-a254-fd6a4e623799)

**Comment by liuzjccc** [comment]
一般怎么排查问题呢

**Comment by zhayujie** [comment]
> 一般怎么排查问题呢

私聊的话看下有没有带触发前缀， 群聊的话看下是否在白名单内。

可以添加 "debug": "true" 参数， 从日志排查在哪个环境出现了问题

**Comment by liuzjccc** [comment]
好的，谢谢，我开一下debug日志看看

**Comment by liuzjccc** [comment]
请问这个参数在哪里可以设置？是在docker-compose.yml配置嘛

**Comment by liuzjccc** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/24708993/e5e909c6-1b85-4905-a988-8bcd773580d4)
你好，这个错能帮忙看下是是什么原因吗

**Comment by liuzjccc** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/24708993/062590c7-e0e3-4a6d-955a-903989940630)
你好，发送信息显示是成功了，但是微信里头没有回复

**Comment by zhayujie** [comment]
> ![image](https://user-images.githubusercontent.com/24708993/249215994-062590c7-e0e3-4a6d-955a-903989940630.png) 你好，发送信息显示是成功了，但是微信里头没有回复

你是在群聊还是私聊 ，有触发嘛， 收到消息不一定会触发自动回复

**Comment by liuzjccc** [comment]
我是私聊

**Comment by liuzjccc** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/24708993/66a8c3ed-7f72-4379-95e2-692e9be81e9d)

**Comment by zhayujie** [comment]
> ![image](https://user-images.githubusercontent.com/24708993/249220438-66a8c3ed-7f72-4379-95e2-692e9be81e9d.png)

加一下README里面的小助手微信吧，帮你看下

**Comment by TopZxx** [comment]
这个问题解决了吗

**Comment by guaguaSama** [comment]
emmm一样

**Comment by liuzjccc** [comment]
> > ![image](https://user-images.githubusercontent.com/24708993/249220438-66a8c3ed-7f72-4379-95e2-692e9be81e9d.png)
> 
> 加一下README里面的小助手微信吧，帮你看下

你好，小助手加啦

**Comment by liuzjccc** [comment]
> > > ![image](https://user-images.githubusercontent.com/24708993/249220438-66a8c3ed-7f72-4379-95e2-692e9be81e9d.png)
> > 
> > 
> > 加一下README里面的小助手微信吧，帮你看下
> 
> 你好，小助手加啦

我的微信名字是liuzjccc

**Comment by zhayujie** [comment]
重启后已解决
