### ISSUE TITLE
App startup failed!

### ISSUE THREAD

**Issue by wasdwsws** [zhayujie/chatgpt-on-wechat#1281]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

root@VM47189:/chatgpt-on-wechat# python3 app.py
[ERROR][2023-06-28 04:45:10][app.py:52] - App startup failed!
[ERROR][2023-06-28 04:45:10][app.py:53] - Expecting ',' delimiter: line 20 column 5 (char 378)
Traceback (most recent call last):
  File "app.py", line 29, in run
    load_config()
  File "/chatgpt-on-wechat/config.py", line 179, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 5 (char 378)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by wasdwsws** [comment]
重启完又好了

**Comment by zhayujie** [comment]
> 重启完又好了

config.json 格式问题
