### ISSUE TITLE
Free GTP-4 API NO KEY NO LIMIT 🔥🔥🔥

### ISSUE THREAD

**Issue by bestK** [zhayujie/chatgpt-on-wechat#1283]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

``` shell
curl -X 'POST' \
  'https://gpt4.anysign.xyz/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model": "got-4",
  "max_tokens": 0,
  "temperature": 0,
  "messages": [
    {
      "content": "你是谁",
      "role": "user"
    }
  ],
  "stream": false
}'
```

### 举例
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/14979305/ec80bb47-cadd-40a0-adbb-a28a9a33ed8c)

### 动机

The source code of this website is for sale.
Free until sold.

**Comment by wuguanglei** [comment]
@bestK 如何联系你呢

**Comment by bestK** [comment]
> @bestK 如何联系你呢

@wuguanglei ech2okk@gmail.com
