### ISSUE TITLE
各位大神帮帮我

### ISSUE THREAD

**Issue by langjix** [zhayujie/chatgpt-on-wechat#1286]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

<img width="1219" alt="屏幕截图 2023-07-03 181020" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/134485397/54f3e53b-8992-4e46-9ee5-2d3aa7136f33">

### 问题描述 😯

一直没有回复后就报错：一段时间后没有正确答复。然后就自动回复：[ERROR]
我连接不到你的网络),

### 终端日志 📒

```log
<此处粘贴终端日志>
```[chat_gpt_bot.py:143] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022DED57CA60>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

[wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络),

**Comment by monk-after-90s** [comment]
看看是不是启动了多个程序实例在后台
