### ISSUE TITLE
支持讯飞星火认知的接入嘛

### ISSUE THREAD

**Issue by chihun** [zhayujie/chatgpt-on-wechat#1298]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by scut-chenzk** [comment]
自己写一个，我也是自己写了个直接调用讯飞星火的bot 。。。

**Comment by youqugit** [comment]
> 自己写一个，我也是自己写了个直接调用讯飞星火的bot 。。。

麻烦吗，只改配置文件可以吗

**Comment by zhayujie** [comment]
已支持
