### ISSUE TITLE
早报没有消息没有输出到微信客户端

### ISSUE THREAD

**Issue by xingyingshuailiangzheng** [zhayujie/chatgpt-on-wechat#1301]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/119168509/f4faf24f-d3ce-41ac-8607-10e9d4581e70)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/119168509/9ccae1e9-1197-430f-a55a-e26f414a29c4)

### 问题描述 😯

服务端有早报数据，但是没传到客户端。没有报错

### 终端日志 📒

```log
<此处粘贴终端日志>
```
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/119168509/638251e4-0c72-472e-919b-7d3fbf2b2be1)

**Comment by 6vision** [comment]
看截图最后一行，banwords，说明触发了敏感词插件，可以更改一下banwords配置项中的 "reply_action": "replace"

**Comment by Kevin-free** [comment]
@xingyingshuailiangzheng @6vision 大佬，为什么我执行 `$tool 早报` 报错了。是少装了插件？还是什么原因？
<img width="957" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/26422757/f7a02c49-696c-418b-b802-4d96f5a39969">
