### ISSUE TITLE
开启linkai，之后用不了summary插件

### ISSUE THREAD

**Issue by xingyingshuailiangzheng** [zhayujie/chatgpt-on-wechat#1306]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

打开linkai，输入$总结 10，没反应

### 问题描述 😯

我在summary的bot适配加上linkai了但是日志报bot没有args属性。能否通过改动代码解决这个问题？该如何修改代码？

### 终端日志 📒

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/119168509/56f6b9b6-e3c6-4749-957a-e08d0bab0206)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/119168509/7dc94323-956c-4653-91b0-a37e3cf3431f)

**Comment by zhayujie** [comment]
已兼容，需要更新代码及插件代码
