### ISSUE TITLE
建议加一个配置 prefix_ask

### ISSUE THREAD

**Issue by pinshig** [zhayujie/chatgpt-on-wechat#1309]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

建议加一个配置用来给输入信息 前面加一个默认的前缀(在不包含#号的情况下)
每次想查找联网信息输入$tool 有一点繁琐

### 举例

建议加一个配置用来给输入信息 前面加一个默认的前缀(在不包含#号的情况下)

配置内容: 
"prefix_ask": "$tool"

eg: 
查找最新新闻  => $tool 查找最新新闻
#auth 123123 => #auth 123123

### 动机

每次想查找联网信息输入$tool 有一点繁琐

**Comment by JC0v0** [comment]
可以参考我最新上传的搜索插件

**Comment by fatwang2** [comment]
> 可以参考我最新上传的搜索插件

@JC0v0  请问是指哪个插件？
