### ISSUE TITLE
微信扫码登录后，微信发了一条消息，linux日志中可以看到内容并且已回复，但是在微信聊天框中就没有得到回复

### ISSUE THREAD

**Issue by zzh103011** [zhayujie/chatgpt-on-wechat#131]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

如图

![QQIHOVXTRPD27%MEI$ AIPE](https://user-images.githubusercontent.com/63699994/217764483-6f4555c2-fdc2-47fd-9b06-a2281aa5df20.png)

![6770652F740C814B34A94F632EEFF767](https://user-images.githubusercontent.com/63699994/217764551-d44048d3-bb3b-456c-9a71-524fef91d0af.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
账号被openai限流了，具体原因未知
