### ISSUE TITLE
公众号接入gpt4后【正在思考中，回复任意文字尝试获取回复】

### ISSUE THREAD

**Issue by Pa5sw0rd** [zhayujie/chatgpt-on-wechat#1310]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

增加延迟

### 问题描述 😯

3.5速度很快，4api返回相对慢一些，然后公众号提示【正在思考中，回复任意文字尝试获取回复】

### 终端日志 📒

```log
[INFO][2023-07-10 16:34:05][passive_reply.py:151] - [wechatmp] Request 1 do send to o6uB91dX1ClksEY1NcXZTQspW0lM 24180351648420684: #gpt_model
[INFO]
你的GPT模型为gpt-4-0613

```

**Comment by zhayujie** [comment]
订阅号是这样的，超时后需要用户主动获取

**Comment by dhr2333** [comment]
有没有什么办法能将订阅号的超时时间增加。我尝试在代码中增加超时时间和超时次数，但是在公众号中并没有发生任何改变。

**Comment by jun7891** [comment]
一样的问题，解决了吗

**Comment by BJ-MQC** [comment]
同问，一样的问题，求大佬更新代码
