### ISSUE TITLE
语音识别与合成不能同时使用一个服务商？

### ISSUE THREAD

**Issue by teshushu** [zhayujie/chatgpt-on-wechat#1311]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

terminal

### 复现步骤 🕹

将配置文件中
  "voice_to_text": "baidu",
  "text_to_voice": "baidu",
全部设置为百度时出现无法识别，无法合成

### 问题描述 😯

将配置文件中
  "voice_to_text": "baidu",
  "text_to_voice": "baidu",
全部设置为百度时出现无法识别，无法合成
单独设置百度合成，openai识别时，百度语音可以合成
单独设置百度识别，azure合成时，百度识别总是为空
bridge.py文件也尝试修改过，不行~

### 终端日志 📒

175.27.**.**:14718 - - [11/Jul/2023 16:59:12] "HTTP/1.1 POST /wxcomapp" - 200 OK
[DEBUG][2023-07-11 16:59:12][chat_channel.py:312] - [WX] consume context: Context(type=VOICE, content=tmp/1GhEDH-n-fSLdfo30RtQWa4fY1WPsoGSTFYOwCfeOcEWyJe-9qj7FPSui1c2mLZsb.amr, kwargs={'isgroup': False, 'msg': <channel.wechatcom.wechatcomapp_message.WechatComAppMessage object at 0x7f3e13425330>, 'origin_ctype': <ContextType.VOICE: 2>, 'openai_api_key': None, 'gpt_model': None, 'session_id': 'fakeuncle', 'receiver': 'fakeuncle'})
[DEBUG][2023-07-11 16:59:12][chat_channel.py:144] - [WX] ready to handle context: Context(type=VOICE, content=tmp/1GhEDH-n-fSLdfo30RtQWa4fY1WPsoGSTFYOwCfeOcEWyJe-9qj7FPSui1c2mLZsb.amr, kwargs={'isgroup': False, 'msg': <channel.wechatcom.wechatcomapp_message.WechatComAppMessage object at 0x7f3e13425330>, 'origin_ctype': <ContextType.VOICE: 2>, 'openai_api_key': None, 'gpt_model': None, 'session_id': 'fakeuncle', 'receiver': 'fakeuncle'})
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][plugin_manager.py:163] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:12][chat_channel.py:164] - [WX] ready to handle context: type=VOICE, content=tmp/1GhEDH-n-fSLdfo30RtQWa4fY1WPsoGSTFYOwCfeOcEWyJe-9qj7FPSui1c2mLZsb.amr
[INFO][2023-07-11 16:59:13][bridge.py:32] - create bot baidu for voice_to_text
[DEBUG][2023-07-11 16:59:13][baidu_voice.py:63] - [Baidu] voice file name=tmp/1GhEDH-n-fSLdfo30RtQWa4fY1WPsoGSTFYOwCfeOcEWyJe-9qj7FPSui1c2mLZsb.wav
[INFO][2023-07-11 16:59:13][baidu_voice.py:67] - 百度语音识别到了：['']
[DEBUG][2023-07-11 16:59:13][plugin_manager.py:163] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:13][godcmd.py:218] - [Godcmd] on_handle_context. content: 
[DEBUG][2023-07-11 16:59:13][plugin_manager.py:163] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:13][keyword.py:52] - [keyword] on_handle_context. content: 
[DEBUG][2023-07-11 16:59:13][plugin_manager.py:163] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-07-11 16:59:13][plugin_manager.py:163] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[INFO][2023-07-11 16:59:13][bridge.py:32] - create bot chatGPT for chat
[ERROR][2023-07-11 16:59:13][chat_channel.py:270] - Worker return exception: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 193, in _generate_reply
    reply = self._generate_reply(new_context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/root/chatgpt-on-wechat/plugins/role/role.py", line 111, in on_handle_context
    if clist[0] == f"{trigger_prefix}停止扮演":

**Comment by xiaoxiaoliuzzZ** [comment]
你这个是没识别出内容，然后报错吧
