### ISSUE TITLE
增加 企业微信客户群聊机器人（类似个人微信那种）

### ISSUE THREAD

**Issue by mari1995** [zhayujie/chatgpt-on-wechat#1314]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

增加 企业微信客户群聊机器人（类似个人微信那种）

### 举例

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/16129683/5b617e65-a1aa-4b74-8f85-3ec5387c2929)

### 动机

减少对个人微信的依赖，提高更多的企业微信和高拓展

**Comment by gh-adsia** [comment]
你好，请问你是怎么实现的，我只能做成应用，但是应用是不支持分享到企业微信群的

**Comment by sunlin-xiaonai** [comment]
这种是怎么实现的，我也很疑惑，我看了企业微信的文档，也没找到这种，难道是企业微信第三方么

**Comment by cocomany** [comment]
worktool的实现方式是纯模拟真实使用，缺点是慢，也不太稳定。 
有另一个项目 luolin-ai/Enterprise-WeChat-GPTbot 也实现了企业微信群聊机器人，相当于二次开发了企微应用。
但我还是非常期待本项目能支持企业微信群聊。

**Comment by zhayujie** [comment]
已支持

**Comment by yujiahaopro** [comment]
请问怎么实现的呀
