### ISSUE TITLE
新增插件“搜索”，“星座运势”

### ISSUE THREAD

**Issue by JC0v0** [zhayujie/chatgpt-on-wechat#1315]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

解决了使用搜索插件前需要添加缀特殊符号的烦恼

### 举例

![1689252881282](https://github.com/zhayujie/chatgpt-on-wechat/assets/108552928/c8d65430-f444-4c9f-b375-ae85860d82e7)
![1689252923405](https://github.com/zhayujie/chatgpt-on-wechat/assets/108552928/006ef512-0b82-4ce4-add6-825d54e0d15c)

**Comment by JC0v0** [comment]
你可以自己实现，讲插件返回的信息发送给主线gpt

**Comment by MILKMILKKING** [comment]
> 你可以自己实现，讲插件返回的信息发送给主线gpt

请问能否看看你的搜索插件链接？我刚刚开始研究，很多还不太明白，想先看看具体的例子是怎么实现的。

**Comment by JC0v0** [comment]
在我的分叉里就可以看到源码
