### ISSUE TITLE
新增插件：midjourney绘图插件，基于midjourney-proxy服务的api

### ISSUE THREAD

**Issue by mouxangithub** [zhayujie/chatgpt-on-wechat#1317]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

详细请看文档：[`mouxangithub/midjourney-proxy-on-wechat`](https://github.com/mouxangithub/midjourney-proxy-on-wechat)

## 支持的平台
- [x] 可接入个人微信聊天使用[`chatgpt-on-wechat`](https://github.com/zhayujie/chatgpt-on-wechat)
- [x] 可接入企业微信应用使用[`企业微信应用号`](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechatcom/README.md)
- [x] 可接入微信公众号[`微信公众号`](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechatmp/README.md)，但由于个人主体的微信订阅号由于无法通过微信认证，无法主动发出消息，只能被动回复，存在回复时间限制(最多只有15秒的自动回复时间窗口)，所以可能无法及时发送图片，只能通过查询接口去拿，建议不使用个人公众号，可以使用[`公众号测试号`](https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login)或认证后的公众号

目前只测试了：个人微信，企业应用号，测试公众号；其他平台自行测试

## 现有功能
- [x] midjourney `imgine` 想象
- [x] midjourney `upscale` 放大
- [x] midjourney `variation` 变幻
- [x] midjourney `describe` 识图，使用方式：（1）私聊窗口（非群聊模式）发图直接生成；（2）发送describe_prefix配置的指令，然后发送一张图片进行识别（此方法不限群聊还是私聊方式）
- [x] midjourney `blend` 混图，使用方式：发送blend_prefix配置的指令，然后发送多张图片进行混合（此方法不限群聊还是私聊方式）
- [x] midjourney 垫图，使用方式：发送pad_prefix配置的指令+prompt描述，然后发送一张图片进行生成（此方法不限群聊还是私聊方式）
- [x] 绘图进度百分比查询
- [x] 发送/queue 任务队列查询
- [x] 解决webp图片无法发送问题
- [x] mj_tip可关闭多条消息发送（最终只发图片或者描述）
- [x] 可自定义添加修改各种功能prefix前缀
- [x] 聊天窗口管理员指令可修改管理员密码，配置mj_url,mj_api_secret，暂停启用mj服务
- [x] 聊天窗口管理员指令可增删改查白名单群组和白名单用户，从而限制用户使用，减少损耗
- [x] 增加图片代理地址discordapp_proxy配置，解决图片本地国内无法发送的问题，可配置discordapp_proxy或配置chatgpt-on-wechat配置的proxy

详细请看文档：[`mouxangithub/midjourney-proxy-on-wechat`](https://github.com/mouxangithub/midjourney-proxy-on-wechat)

### 举例

![2c2904707a659b350129b649cd928f1](https://github.com/zhayujie/chatgpt-on-wechat/assets/48978046/7d298fae-734b-4af4-b52d-1a0bd26e4f60)
![82790cc4c32531869ff80bca39625bc](https://github.com/zhayujie/chatgpt-on-wechat/assets/48978046/efbd9cd4-df57-4d7e-b134-5a15d6861f31)
![4a51e180d538cce99eb39c6b24d9faf](https://github.com/zhayujie/chatgpt-on-wechat/assets/48978046/0691c736-dfb7-4dc6-bd24-b7cae9da2efc)
![fa1ebf6b44c37fa4e18286aa5085458](https://github.com/zhayujie/chatgpt-on-wechat/assets/48978046/236adc2f-af8e-437d-b163-6b918f8e9704)

**Comment by bluecc0** [comment]
请问"mj_api_secret": "", // midjourney-proxy的api请求头是在哪里看，已在railway上部署Midjourney-proxy

**Comment by mouxangithub** [comment]
> 请问"mj_api_secret": "", // midjourney-proxy的api请求头是在哪里看，已在railway上部署Midjourney-proxy

参考文档：https://github.com/novicezk/midjourney-proxy/blob/main/docs/config.md

没有的话不进行配置也是可以的，只是加了这个请求头可以避免别人可以轻松调用

**Comment by airuibadi12** [comment]
你好请问一下我出现：[ERROR]
❌ 请求失败：未知服务器
这是为什么？谢谢！

**Comment by mouxangithub** [comment]
> 

检查下[`midjourney-proxy`](https://github.com/novicezk/midjourney-proxy)起了么

**Comment by mouxangithub** [comment]
> 你好请问一下我出现：[ERROR] ❌ 请求失败：未知服务器 这是为什么？谢谢！

检查下[`midjourney-proxy`](https://github.com/novicezk/midjourney-proxy)起了么
