### ISSUE TITLE
机器人启动后不定时会出现死机无响应情况

### ISSUE THREAD

**Issue by RolloTomasiii** [zhayujie/chatgpt-on-wechat#1318]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

可能复现的方案是，当长时间部署gpt后，再重新启动，大概有50%的概率会出现这种情况。

### 问题描述 😯

问题的情况很复杂，经常在项目启动后，接到微信消息时无反应，典型的特征有，微信发送消息后，wechaty接收到消息后，chatgpt-on-wechat**没有**以下日志：
[INFO][2023-07-14 16:57:20][bridge.py:30] - create bot chatGPT for chat
如果正常响应时会创建bot，但是异常时就没有任何反应
目前没有DEBUG日志，正在想办法收集,注意：wechaty没有退出登录

### 终端日志 📒

异常时不会打印任何日志

**Comment by RolloTomasiii** [comment]
开启DEBUG模式后也捕捉不到任何异常信息

**Comment by RolloTomasiii** [comment]
死机前的日志：
[DEBUG][2023-07-16 16:28:39][wechaty_channel.py:122] - [WX] message:ChatMessage: id=6379386314863424604, create_time=1689496119, ctype=TEXT, content=好的, from_user_id=wxid_qhfif1k1mi0g22, from_user_nickname=朝, to_user_id=wxid_wihg7hmtosen22, to_user_nickname=ChatGPT, other_user_id=wxid_qhfif1k1mi0g22, other_user_nickname=朝, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None
[INFO][2023-07-16 16:28:39][wechaty_channel.py:128] - [WX] receiveMsg=ChatMessage: id=6379386314863424604, create_time=1689496119, ctype=TEXT, content=好的, from_user_id=wxid_qhfif1k1mi0g22, from_user_nickname=朝, to_user_id=wxid_wihg7hmtosen22, to_user_nickname=ChatGPT, other_user_id=wxid_qhfif1k1mi0g22, other_user_nickname=朝, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, context=Context(type=TEXT, content=好的, kwargs={'isgroup': False, 'msg': <channel.wechat.wechaty_message.WechatyMessage object at 0x7f6f05894610>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': 'wxid_qhfif1k1mi0g22', 'receiver': 'wxid_qhfif1k1mi0g22'})

正常的回应日志：
[DEBUG][2023-07-16 22:43:40][wechaty_channel.py:122] - [WX] message:ChatMessage: id=584556846616084181, create_time=1689518619, ctype=TEXT, content=晚上好, from_user_id=wxid_bep7f407bkpg22, from_user_nickname=明天, to_user_id=wxid_wihg7hmtosen22, to_user_nickname=ChatGPT, other_user_id=wxid_bep7f407bkpg22, other_user_nickname=明天, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None
[INFO][2023-07-16 22:43:40][wechaty_channel.py:128] - [WX] receiveMsg=ChatMessage: id=584556846616084181, create_time=1689518619, ctype=TEXT, content=晚上好, from_user_id=wxid_bep7f407bkpg22, from_user_nickname=明天, to_user_id=wxid_wihg7hmtosen22, to_user_nickname=ChatGPT, other_user_id=wxid_bep7f407bkpg22, other_user_nickname=明天, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, context=Context(type=TEXT, content=晚上好, kwargs={'isgroup': False, 'msg': <channel.wechat.wechaty_message.WechatyMessage object at 0x7faed53031f0>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': 'wxid_bep7f407bkpg22', 'receiver': 'wxid_bep7f407bkpg22'})
[DEBUG][2023-07-16 22:43:40][chat_channel.py:309] - [WX] consume context: Context(type=TEXT, content=晚上好, kwargs={'isgroup': False, 'msg': <channel.wechat.wechaty_message.WechatyMessage object at 0x7faed53031f0>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': 'wxid_bep7f407bkpg22', 'receiver': 'wxid_bep7f407bkpg22'})
[DEBUG][2023-07-16 22:43:40][chat_channel.py:143] - [WX] ready to handle context: Context(type=TEXT, content=晚上好, kwargs={'isgroup': False, 'msg': <channel.wechat.wechaty_message.WechatyMessage object at 0x7faed53031f0>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': 'wxid_bep7f407bkpg22', 'receiver': 'wxid_bep7f407bkpg22'})

**Comment by RolloTomasiii** [comment]
死机的现象是，chat_channel.py:309 日志文件不打印，死机后任何日志都不输出

**Comment by RolloTomasiii** [comment]
目测与session有关，可能是线程问题

**Comment by befantasy** [comment]
那怎么恢复正常的？

**Comment by RolloTomasiii** [comment]
> 那怎么恢复正常的？

监测不到bug，没法改，只能多重启几次，碰运气

**Comment by befantasy** [comment]
就是说重启可以恢复正常？

**Comment by RolloTomasiii** [comment]
> 就是说重启可以恢复正常？

有一定概率可以恢复正常，但因为他死机时间不确定，有可能几个小时候就突然死机了，所以要一直监控，只要超过一天，就稳了

**Comment by RolloTomasiii** [comment]
解决了。。。

**Comment by theLastWinner** [comment]
> 解决了。。。

@RolloTomasiii 请问是怎么解决的？目前也遇到相同问题

**Comment by joyce677** [comment]
> 解决了。。。

求解决方案🙏

**Comment by willzzq** [comment]
> > 解决了。。。
> 
> @RolloTomasiii 请问是怎么解决的？目前也遇到相同问题

最近刚刚安装，也出现了死机现象，你是咋解决的？

**Comment by joyce677** [comment]
> > > 解决了。。。
> > 
> > @RolloTomasiii 请问是怎么解决的？目前也遇到相同问题
> 
> 最近刚刚安装，也出现了死机现象，你是咋解决的？

运行后，私聊和群聊收到的第一条消息必须是触发机器人的消息，如果收到的是其他信息内容，特别是收到引用的消息，就容易触发这个bug。

**Comment by RolloTomasiii** [comment]
> > > > 解决了。。。
> > > 
> > > 
> > > @RolloTomasiii 请问是怎么解决的？目前也遇到相同问题
> > 
> > 
> > 最近刚刚安装，也出现了死机现象，你是咋解决的？
> 
> 运行后，私聊和群聊收到的第一条消息必须是触发机器人的消息，如果收到的是其他信息内容，特别是收到引用的消息，就容易触发这个bug。

加我微信交流 AIYLWL

**Comment by RolloTomasiii** [comment]
> > 解决了。。。
> 
> @RolloTomasiii 请问是怎么解决的？目前也遇到相同问题

加我微信交流 AIYLWL
