### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by chn-youbai** [zhayujie/chatgpt-on-wechat#1322]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

启动

### 问题描述 😯

启动之后就会报错
起先是没有找到根目录下的config.json文件，我把config.py里的相对路径替换成绝对路径就能找到了
接下来是没有找到plugins文件夹里的plugins.json文件，但是这次改路径没有用了，因为我本来就没有这个文件
我把整个文件夹删掉之后从新clone一遍也还是一样
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/112460920/aede218a-e563-473a-a596-2d32dee63f27)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
当前路径是哪里呢
是在本地还是服务器
