### ISSUE TITLE
是否能支持fly.io部署呢

### ISSUE THREAD

**Issue by GesiIvy128** [zhayujie/chatgpt-on-wechat#1327]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

因为railway取消starter plan了，以后连500小时都没法白嫖了，是否考虑fly.io部署呢？

**Comment by timmycheng** [comment]
你railway能成功部署么？ 我试了几次好像都不行，以公众号的模式
