### ISSUE TITLE
添加本地模型部署功能

### ISSUE THREAD

**Issue by lx0126z** [zhayujie/chatgpt-on-wechat#1331]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

使用gpt是付费的，网上很多开源的模型可以加载在本地运行，例如chatglm6B。

我试图拆解代码，把自己的模型放进去，但是在debug到chatgpt-on-wechat\lib\itchat\components\register.py的49行代码（msg = self.msgList.get(timeout=1)）后就进不去了，不清楚这步后面的实现细节。

如果能有个位置说明哪里接的模型输入，哪里接的模型输出，那么替换本地模型将非常容易。

**Comment by mouxangithub** [comment]
参考chatgpt-on-wechat下的bot文件夹，基本上模型机器人接口那些都在里边
