### ISSUE TITLE
付费求一个插件功能

### ISSUE THREAD

**Issue by nbdxrycyl** [zhayujie/chatgpt-on-wechat#1339]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

想要找人开发一个插件，功能是能够在这个插件普通的基础上，实现多个微信群中某些特定用户（多个用户）的信息实时转发到一个特定的群中，并且能够发送给GPT，通过GPT判断信息是否为垃圾信息、筛选信息。
有想法开发的朋友请留下报价，太贵就算了- -

### 举例

A B C D E 微信聊天群内的 a b c d e f g 用户 
产生了聊天记录 xxxxxxxx
通过GPT进行判断和内容筛选，无用则不转发，有用则转发至 X 微信群内。

### 动机

不想看聊天记录

**Comment by lx348321409** [comment]
你这个需要加钱啊

**Comment by undefinedcodezhong** [comment]
聊天记录转发不难，但是筛选信息就有点难了，得定义一些大致的标准

**Comment by nbdxrycyl** [comment]
已经找人写出来 不过是不通过这个插件的 费用1k

>
