### ISSUE TITLE
二维码太大了, 扫不了, 怎么办?

### ISSUE THREAD

**Issue by zhouyu168** [zhayujie/chatgpt-on-wechat#134]
二维码太大了, 扫不了, 怎么办? 谢谢!
![二维码太大了](https://user-images.githubusercontent.com/124881099/217791511-82b19eab-54f3-416d-8422-2e284d48498e.png)

**Comment by synjkc** [comment]
复制进notpad+

**Comment by Linkegee** [comment]
你不要用VScode或者Pycharm跑，就在源码文件目录的终端输入python3 app.py跑，完美解决。

**Comment by zhouyu168** [comment]
把值设为0, 就出现了清晰的二维码图片,
谢谢! : )

**Comment by zhouyu168** [comment]
> 如果是本地环境的对话，可以修改行代码测试： https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechat_channel.py
> 
> 把37行举号码里的enableCmdQR=2 去掉试 ![图片](https://user-images.githubusercontent.com/26161723/217872714-dcf53cf6-f9a2-47a9-a2b4-633c7181daea.png)

把2改为0 , 就出现了清晰的二维码图片,  谢谢! : )

**Comment by zhouyu168** [comment]
> 你不要用VScode或者Pycharm跑，就在源代码文件目录的最终输入python3 app.py跑，完美解决。

你是说在cmd中运行?

**Comment by Linkegee** [comment]
> > 你不要用VScode或者Pycharm跑，就在源代码文件目录的最终输入python3 app.py跑，完美解决。
> 
> 你是说在cmd中运行?

是的

**Comment by learner-NKH** [comment]
> 如果是本地环境的话，可以改一行代码试试： https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechat_channel.py
> 
> 把37行括号里的 enableCmdQR=2 去掉试试 ![image](https://user-images.githubusercontent.com/26161723/217872714-dcf53cf6-f9a2-47a9-a2b4-633c7181daea.png)

如果是服务器环境应该怎么办呢，去掉enableCmdQR=2或者enableCmdQR=0之后报错，FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'

**Comment by zhayujie** [comment]
@learner-NKH  服务器的话没办法去， 只能看看换一个终端程序能否解决，可以调小字体分辨率的
