### ISSUE TITLE
python3 app.py 无反应

### ISSUE THREAD

**Issue by shitvbr** [zhayujie/chatgpt-on-wechat#1342]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

python3 app.py

### 问题描述 😯

执行python3 app.py 没有任何反应，也找不到日志文件
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/7031353/cffb5ae3-2dd4-4547-938a-494634768df6)

已安装必要的依赖

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
windows下试试 python app.py
