### ISSUE TITLE
分支1.3.4的LinkAI，对接企业微信导入失败

### ISSUE THREAD

**Issue by Martin-dq** [zhayujie/chatgpt-on-wechat#1344]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

切换到分支1.3.4后，配置企业微信，启用报错
[WARNING][2023-07-29 13:50:33][plugin_manager.py:113] - Failed to import plugin linkai: 'type' object is not subscriptable
chatgpt-tool-hub version: 0.4.6

### 问题描述 😯

依赖全部安装OK，python版本3.8，在master中运行良好，切换到分支1.3.4启用LinkAI插件报错，无法导入linkai插件，其余正常

### 终端日志 📒

[INFO][2023-07-29 13:50:33][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-07-29 13:50:33][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-07-29 13:50:33][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-07-29 13:50:33][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-07-29 13:50:33][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[WARNING][2023-07-29 13:50:33][plugin_manager.py:113] - Failed to import plugin linkai: 'type' object is not subscriptable
chatgpt-tool-hub version: 0.4.6
[INFO][2023-07-29 13:50:34][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-07-29 13:50:34][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-07-29 13:50:34][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-07-29 13:50:34][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-07-29 13:50:34][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-07-29 13:50:34][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-07-29 13:50:34][godcmd.py:205] - [Godcmd] inited
[INFO][2023-07-29 13:50:34][keyword.py:40] - [keyword] {}
[INFO][2023-07-29 13:50:34][keyword.py:42] - [keyword] inited.
[INFO][2023-07-29 13:50:34][role.py:69] - [Role] inited
[INFO][2023-07-29 13:50:34][dungeon.py:56] - [Dungeon] inited
[INFO][2023-07-29 13:50:34][hello.py:23] - [Hello] inited
[INFO][2023-07-29 13:50:34][finish.py:23] - [Finish] inited

**Comment by zhayujie** [comment]
我试了下没有复现，可以帮忙在 plugin_manager.py 的第133行加一行代码 logger.exception(e) ，然后启动看下详细报错嘛

**Comment by Martin-dq** [comment]
还是一样，没有变化
[INFO][2023-07-30 11:12:18][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-07-30 11:12:18][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-07-30 11:12:18][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-07-30 11:12:18][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-07-30 11:12:18][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[WARNING][2023-07-30 11:12:18][plugin_manager.py:113] - Failed to import plugin linkai: 'type' object is not subscriptable
chatgpt-tool-hub version: 0.4.6
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin MidJourney_v1.0.41 registered, path=./plugins/midjourney
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-07-30 11:12:19][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-07-30 11:12:19][godcmd.py:205] - [Godcmd] inited
[INFO][2023-07-30 11:12:19][keyword.py:40] - [keyword] {}
[INFO][2023-07-30 11:12:19][keyword.py:42] - [keyword] inited.
[INFO][2023-07-30 11:12:19][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-07-30 11:12:19][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-07-30 11:12:19][chatgpt.py:186] - proxy no find, directly request to chatgpt instead
[INFO][2023-07-30 11:12:19][chatgpt.py:186] - proxy no find, directly request to chatgpt instead

**Comment by Martin-dq** [comment]
切换到主分支，将linkAI这个文件夹整个复制到plugin里面后，通过初始化加载，还是提示加载失败
[INFO][2023-07-30 11:24:04][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-07-30 11:24:04][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-07-30 11:24:04][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-07-30 11:24:04][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-07-30 11:24:04][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[WARNING][2023-07-30 11:24:04][plugin_manager.py:113] - Failed to import plugin linkai: cannot import name 'global_config' from 'config' (/home/chatgpt-on-wechat/config.py)
chatgpt-tool-hub version: 0.4.6
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin MidJourney_v1.0.41 registered, path=./plugins/midjourney
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-07-30 11:24:06][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-07-30 11:24:06][godcmd.py:205] - [Godcmd] inited
[INFO][2023-07-30 11:24:06][keyword.py:40] - [keyword] {}
[INFO][2023-07-30 11:24:06][keyword.py:42] - [keyword] inited.
[INFO][2023-07-30 11:24:06][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-07-30 11:24:06][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-07-30 11:24:06][chatgpt.py:186] - proxy no find, directly request to chatgpt instead
[INFO][2023-07-30 11:24:06][chatgpt.py:186] - proxy no find, directly request to chatgpt instead

**Comment by Martin-dq** [comment]
还不支持本地化部署的插件加载，对吧？
1.3.3
支持在 plugins/config.json 中添加全量插件配置，docker部署时可通过挂载该文件修改插件配置

**Comment by Martin-dq** [comment]
BUG已修复
