### ISSUE TITLE
定制化开发chargpt-on-wechat，有偿代部署商业化运行

### ISSUE THREAD

**Issue by RolloTomasiii** [zhayujie/chatgpt-on-wechat#1353]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by RolloTomasiii** [comment]
### 目前已实现功能：
**定时自动通过好友申请
定时自动通过群聊邀请
定时向指定群聊推送消息
MidJourney绘图功能
记录用户使用次数
付费功能开发
自动开通会员服务
次数会员与包月包年会员
分享后自动激励功能
超低维护成本
全网最全微信敏感词集
GPT4流式请求支持
等等等等等等等等等等等等等等等等等等等等等**

**Comment by kokojacket** [comment]
有微信吗

**Comment by spoony-Z** [comment]
怎么联系
