### ISSUE TITLE
扫描登录成功后提示Unexpected sync check result: window.synccheck={retcode:"-1",selector:"0"} LOG OUT!

### ISSUE THREAD

**Issue by lihongcheng** [zhayujie/chatgpt-on-wechat#1355]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1、nohup python3 app.py & tail -f nohup.out
2、扫描登录成功。
3、提示错误，程序退出。
Start auto replying.
Unexpected sync check result: window.synccheck={retcode:"-1",selector:"0"}
LOG OUT!

### 问题描述 😯

<img width="859" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/20829680/9835ee7d-5075-4831-92af-a2e544e22838">

### 终端日志 📒

```log
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as AIChat
[INFO][2023-08-05 07:36:11][wechat_channel.py:126] - Wechat login success, user_id: @afdfd9cc3b925ca820cb4bd9eca789ad0323750e28836dbbb7e87ce3635e0e39, nickname: AIChat
Start auto replying.
Unexpected sync check result: window.synccheck={retcode:"-1",selector:"0"}
LOG OUT!
^C
[3]+  Done                    nohup python3 app.py
```

**Comment by losteye** [comment]
我也遇到了同样的问题，而且二维码没法扫描

**Comment by lp380490944** [comment]
是的，就几分钟就挂了

**Comment by ZachFengY** [comment]
+1

**Comment by ZachFengY** [comment]
应该是微信扫码登录之后，手机微信退掉了，pc端就会同步退出，亲测是这么回事

**Comment by lp380490944** [comment]
我发现问题了，这个是跟微信账号有关，我换了一个微信账号就好了，确保你用的是安卓手机，最好不要太差，我已经用了一周了而且是在个人的PC上，现在稳如老狗
