### ISSUE TITLE
TypeError: unsupported type for timedelta seconds component: str

### ISSUE THREAD

**Issue by swumagic** [zhayujie/chatgpt-on-wechat#1361]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10.11

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

正常可以登录微信网页端 后输入消息，不会回复且出现如上错误。
且开了日本或者台湾或者美国节点的梯子，设置为规则，且安装了环境urllib3==1.25.11。

### 问题描述 😯
正常可以登录微信网页端 后输入消息，不会回复且出现如上错误。
且开了日本或者台湾或者美国节点的梯子，设置为规则，且安装了环境urllib3==1.25.11。
6, nickname: AI
Start auto replying.
[INFO][2023-08-11 09:53:03][bridge.py:34] - create bot chatGPT for chat
[INFO][2023-08-11 09:53:03][chat_gpt_bot.py:49] - [CHATGPT] query=在吗
[ERROR][2023-08-11 09:53:03][chat_channel.py:274] - Worker return exception: unsupported type for timedelta seconds component: str
Traceback (most recent call last):**如下
    expiry_time = datetime.now() + timedelta(seconds=self.expires_in_seconds)
TypeError: unsupported type for timedelta seconds component: str

### 终端日志 📒

[INFO][2023-08-11 09:51:10][config.py:209] - [INIT] load config: {'open_ai_api_key': 'sk-Rwq**u', 'model': 'gpt-3.5-turbo', 'proxy': 'http://127.0.0.1:7890', 'conversation_max_tokens': '4000', 'expires_in_seconds': '360000', 'image_create_prefix': ['绘画'], 'image_create_size': '1024x1024', 'always_reply_voice': 'False', 'speech_recognition': 'True', 'group_speech_recognition': 'True', 'voice_reply_voice': 'True', 'voice_to_text': 'openai', 'text_to_voice': 'azure', 'azure_voice_api_key': '5aa**32cdb', 'azure_voice_region': 'eastus', 'clear_memory_commands': '#清除', 'plugin_trigger_prefix': '$', 'single_chat_prefix': ['yh', '@yh'], 'single_chat_reply_prefix':6 ', 'single_chat_reply_suffix': '6', 'group_at_off': 'False', 'group_chat_in_one_session': ['ALL_GROUP'], 'group_chat_prefix': ['@yh'], 'group_chat_reply_prefix': '6, 'group_chat_reply_suffix': '6', 'group_name_white_list': ['ALL_GROUP'], 'use_global_plugin_config': 'True', 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持角色扮演和文字冒险等丰富插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-08-11 09:51:10][config.py:159] - [Config] User datas file not found, ignore.
[INFO][2023-08-11 09:51:10][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-08-11 09:51:10][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins\banwords
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins\bdunit
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins\dungeon
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins\finish
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins\godcmd
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins\hello
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins\keyword
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins\linkai
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin sdwebui_v2.1 registered, path=./plugins\plugin_sdwebui-master
[INFO][2023-08-11 09:51:10][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins\role
chatgpt-tool-hub version: 0.4.6
[INFO][2023-08-11 09:51:11][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins\tool
[ERROR][2023-08-11 09:51:11][plugin_manager.py:180] - Plugin replicate not found, but found in plugins.json
[INFO][2023-08-11 09:51:11][godcmd.py:190] - [Godcmd] 因未设置口令，本次的临时口令为**98。
[INFO][2023-08-11 09:51:11][godcmd.py:205] - [Godcmd] inited
[INFO][2023-08-11 09:51:11][keyword.py:40] - [keyword] {}
[INFO][2023-08-11 09:51:11][keyword.py:42] - [keyword] inited.
[INFO][2023-08-11 09:51:13][chatgpt.py:184] - success use proxy: http://127.0.0.1:7890
[INFO][2023-08-11 09:51:13][victorinox.py:86] - use_tools=['terminal', 'python', 'meteo-weather', 'url-get'], params: {'debug': False, 'openai_api_key': 'sk-Rq**u', 'open_ai_api_base': 'https://api.openai.com/v1', 'deployment_id': '', 'proxy': 'http://127.0.0.1:7890', 'request_timeout': 120, 'model_name': 'gpt-3.5-turbo', 'no_default': False, 'top_k_results': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning_news_api_key': '', 'cuda_device': 'cpu', 'think_depth': 3, 'arxiv_summary': True, 'morning_news_use_llm': False, 'llm_api_key': 'sk-Re5X**qu', 'llm_api_base_url': 'https://api.openai.com/v1'}
[INFO][2023-08-11 09:51:13][tool.py:31] - [tool] inited
[INFO][2023-08-11 09:51:13][role.py:69] - [Role] inited
[INFO][2023-08-11 09:51:13][dungeon.py:56] - [Dungeon] inited
[INFO][2023-08-11 09:51:13][hello.py:23] - [Hello] inited
[INFO][2023-08-11 09:51:13][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.
Downloading QR code.
XXX

Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as AI
[INFO][2023-08-11 09:52:35][wechat_channel.py:126] - Wechat login success, user_id: @5680b**96, nickname: AI
Start auto replying.
[INFO][2023-08-11 09:53:03][bridge.py:34] - create bot chatGPT for chat
[INFO][2023-08-11 09:53:03][chat_gpt_bot.py:49] - [CHATGPT] query=在吗

[ERROR][2023-08-11 09:53:03][chat_channel.py:274] - Worker return exception: unsupported type for timedelta seconds component: str
Traceback (most recent call last):
  File "M:\SD\Python31011\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "M:\SD\git\chatgpt-on-wechat\channel\chat_channel.py", line 150, in _handle
    reply = self._generate_reply(context)
  File "M:\SD\git\chatgpt-on-wechat\channel\chat_channel.py", line 172, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "M:\SD\git\chatgpt-on-wechat\channel\channel.py", line 37, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "M:\SD\git\chatgpt-on-wechat\bridge\bridge.py", line 49, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "M:\SD\git\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 65, in reply
    session = self.sessions.session_query(query, session_id)
  File "M:\SD\git\chatgpt-on-wechat\bot\session_manager.py", line 65, in session_query
    session = self.build_session(session_id)
  File "M:\SD\git\chatgpt-on-wechat\bot\session_manager.py", line 58, in build_session
    self.sessions[session_id] = self.sessioncls(session_id, system_prompt, **self.session_args)
  File "M:\SD\git\chatgpt-on-wechat\common\expired_dict.py", line 18, in __setitem__
    expiry_time = datetime.now() + timedelta(seconds=self.expires_in_seconds)
TypeError: unsupported type for timedelta seconds component: str

**Comment by GeekerMa** [comment]
我也发生了这个问题

**Comment by zhayujie** [comment]
config.json里 expires_in_seconds 这个配置是不是遗漏了
