### ISSUE TITLE
利用fakeopen转为的API，无法接入到项目汇总

### ISSUE THREAD

**Issue by wangjueszu** [zhayujie/chatgpt-on-wechat#1362]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

https://github.com/pengzhile/pandora/issues/837
fakeopen 已支持 ChatGPT 转 Turbo API
---------
将web的chatgpt转为Api后，弄了一上午无法接入到本项目中

### 问题描述 😯

在修改了config.py的文件后，chat_gpt_bot.py文件中
response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)报错。

理解这条代码应该是统计token用的，所以解决方法就把它注释掉了。对应的将返回值默认设为1、1、“”。

然后就成了，我无论输入什么都返回“[bot]你好！请问有什么我可以为你做的吗？”
--------
在服务器上通过以下代码是可以正常执行的
curl https://ai.fakeopen.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer fk-UFP***************lVXUc" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "system", "content": ""}, {"role": "user", "content": "hello,world"}]
  }'

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by byxinyu** [comment]
我接入fastgpt也出现类似的问题

**Comment by wangjueszu** [comment]
我的在使用了最新的版本代码后，奇迹的正常了。

**Comment by liuyaboixixi** [comment]
@wangjueszu

**Comment by wisdom520** [comment]
同问 我用pandoranext的接口返回的是我现在有点累了，等会再来吧也是用了pooltokens了，也不会自动是哪里的问题
