### ISSUE TITLE
本机使用梯子，运行返回：You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by LYY1030** [zhayujie/chatgpt-on-wechat#1366]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[INFO][2023-08-13 17:38:28][wechat_channel.py:126] - Wechat login success, user_id: @f114079d3b391ad454c887109c1932c1b4a6123e394f58b5c4f0a87746f450d2, nickname: 点点
[INFO][2023-08-13 17:39:00][bridge.py:34] - create bot chatGPT for chat
[INFO][2023-08-13 17:39:00][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2023-08-13 17:39:00][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-08-13 17:39:20][chat_gpt_bot.py:159] - [CHATGPT] 第1次重试
[WARNING][2023-08-13 17:39:20][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-08-13 17:39:40][chat_gpt_bot.py:159] - [CHATGPT] 第2次重试
[WARNING][2023-08-13 17:39:41][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[INFO][2023-08-13 17:39:41][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
提问太快啦，请休息一下再问我吧), receiver=@80643925f80e41f2fffd087a704cc2d24413975d1e82122f8668a7691deffc67

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/81019749/c19c458c-8b62-4655-94e8-2020ea33358b)

### 终端日志 📒

```log
INFO][2023-08-13 17:38:28][wechat_channel.py:126] - Wechat login success, user_id: @f114079d3b391ad454c887109c1932c1b4a6123e394f58b5c4f0a87746f450d2, nickname: 点点
[INFO][2023-08-13 17:39:00][bridge.py:34] - create bot chatGPT for chat
[INFO][2023-08-13 17:39:00][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2023-08-13 17:39:00][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-08-13 17:39:20][chat_gpt_bot.py:159] - [CHATGPT] 第1次重试
[WARNING][2023-08-13 17:39:20][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-08-13 17:39:40][chat_gpt_bot.py:159] - [CHATGPT] 第2次重试
[WARNING][2023-08-13 17:39:41][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[INFO][2023-08-13 17:39:41][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
提问太快啦，请休息一下再问我吧), receiver=@80643925f80e41f2fffd087a704cc2d24413975d1e82122f8668a7691deffc67

```

**Comment by evachxji** [comment]
你的openai key过期了，去官网检查下你的key有效期。
https://platform.openai.com/account/usage

**Comment by qxsomeone** [comment]
去https://platform.openai.com/account/ 这里，看看usage和rate limit，和你的配额以及访问速率有关，你问得太多太快了。如果是免费版的，也可能是试用账户送的代金券用完了。
