### ISSUE TITLE
azure语音配置报错

### ISSUE THREAD

**Issue by LPtrichor** [zhayujie/chatgpt-on-wechat#1367]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1.项目下载之后，配置了config.json的语音部分
2.检查了azure语音接口的秘钥和区域，没有问题
3.运行报错

### 问题描述 😯

请问一下这个报错是什么问题呀？
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/78304742/00ad7233-c0f0-41d9-837a-39f2b9d113fe)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by LPtrichor** [comment]
本地调试发现，读取不到api_key和region信息，直接放到代码里可以用了

**Comment by fatwang2** [comment]
> 

请问放代码里具体指的是什么？

**Comment by fatwang2** [comment]
@LPtrichor 请问最终是怎么解决的呀

**Comment by LPtrichor** [comment]
本地调试是发现环境变量没有加载出来，把那个key直接放代码里面了，不过部署在云服务器上还是有问题，返回语音的长度是0



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月22日(周二) 中午12:34
收件人: ***@***.***&gt;;
抄送: "Luo ***@***.******@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] azure语音配置报错 (Issue #1367)




 
@LPtrichor 请问最终是怎么解决的呀

**Comment by fatwang2** [comment]
我直接放代码里没有解决啥问题，报错都是一样的

**Comment by LPtrichor** [comment]
你报的是啥错误，可以本地调试看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月22日(周二) 晚上8:01
收件人: ***@***.***&gt;;
抄送: "Luo ***@***.******@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] azure语音配置报错 (Issue #1367)




 
我直接放代码里没有解决啥问题，报错都是一样的

**Comment by fatwang2** [comment]
我安装FFmpeg后问题就解决了
