### ISSUE TITLE
关于使用其他大模型api（非chatgpt）

### ISSUE THREAD

**Issue by Vicerebel** [zhayujie/chatgpt-on-wechat#1372]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

请问我如何使用其他大模型的api接口，我应该修改哪些文件呀

### 动机

尝试更换大模型

**Comment by zhayujie** [comment]
see https://github.com/zhayujie/chatgpt-on-wechat/issues/1378，开源模型也会持续接入

**Comment by zwdzwdzwd** [comment]
> see #1378 开源模型也会持续接入

请问，Claude 可以接入了吗，有找到一个项目，但是看作者说已经停用了。谢谢！

**Comment by zhayujie** [comment]
> > see #1378 开源模型也会持续接入
> 
> 请问，Claude 可以接入了吗，有找到一个项目，但是看作者说已经停用了。谢谢！

这个没有api 不太稳定 暂时不考虑接入哈
