### ISSUE TITLE
关于国内模型文心一言和讯飞星火的使用

### ISSUE THREAD

**Issue by zhayujie** [zhayujie/chatgpt-on-wechat#1378]
### 一、文心一言使用

1. 参考 [文心千帆文档](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/flfmc9do2) 文档创建应用，获取 API Key 和 Secret Key
2. 将项目config.json 中的 model 字段设置为 `wenxin`，同时将上一步获取的配置在config.json中 填入 `baidu_wenxin_api_key` 和 `baidu_wenxin_secret_key`
 
### 二、讯飞星火使用

1. 前往 [讯飞星火控制台](https://console.xfyun.cn/services/bm2) 申请API权限，获取 APPID，APISecret 和 APIKey。项目默认使用的是 V2.0 接口

2. 安装依赖 
```bash
pip3 install websocket-client==1.2.0
```
3. 将项目config.json 中的 model 字段设置为 `xunfei`，同时将上一步获取的配置在 config.json 中 填入 `xunfei_app_id`, `xunfei_api_key`, `xunfei_api_secret`

### 三、模型切换

由于模型model字段可选值较多，增加了 `#model` 管理员指令来进行查看和切换全局模型。

目前支持的`model`字段为 `gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-4, wenxin, xunfei`，使用方式如下:

```bash
# auth <临时口令>          # 首先在私聊认证管理员
#model                   # 查看当前模型. 
#model <模型名称>          # 切换模型， 例如 #model xunfei
```

**P.S.**  LinkAI 用户使用文心或讯飞模型时无需申请和填写 api secret,  api key 等配置，只需使用 `link_ai_api_key` 并直接切换model 参数即可。

**Comment by zhayujie** [comment]
占坑

**Comment by Bromaomao** [comment]
我的默认模型为gpt-3.5-turbo，使用#model切换其他模型能正常使用，想再切回gpt-3.5-turbo时提示模型名称不存在

**Comment by zhayujie** [comment]
> 我的默认模型为gpt-3.5-turbo，使用#model切换其他模型能正常使用，想再切回gpt-3.5-turbo时提示模型名称不存在

发我下日志哈，还有你切换模型时的指令

**Comment by biaozhang64** [comment]
请问我用管理员身份输入#model为什么提示
[ERROR]
未知指令：model
查看指令列表请输入#help 
已拉取最新的代码

**Comment by zhayujie** [comment]
> 请问我用管理员身份输入#model为什么提示 [ERROR] 未知指令：model 查看指令列表请输入#help 已拉取最新的代码

git log 看一下是否为最新代码

**Comment by fatwang2** [comment]
请问xunfei的安装依赖问题有解决方案吗？目前一直提示AttributeError: module 'websocket' has no attribute 'enableTrace'

**Comment by yunyu930** [comment]
接入讯飞和文言一心后模型换回GPT3.5后，tool插件不见了，哪怕把讯飞和文言一心的代码删了tool插件还是无法使用，但是文件夹里tool还是在的

**Comment by fatwang2** [comment]
我把websocket.enableTrace(False)删掉就可以了，好像也没影响啥

**Comment by Windrunner20** [comment]
如何指定使用文心4.0呢

**Comment by mobguang** [comment]
@zhayujie 
请问支持ChatGLM3-6B模型吗，谢谢。

**Comment by mashagua** [comment]
> websocket

我也是这个,你要不先卸载websocket-client,然后安装1.2版本，我是用了这个才好的

**Comment by hypernovalee** [comment]
App startup failed!
key baidu_wenxin_api_key not in available_setting.
我使用百度文心一言模型时提示这个？

**Comment by O1ive2** [comment]
如何使用自己训练的fine-tuned chatgpt model呢
