### ISSUE TITLE
大佬，我想学习一下，但是却启动不了

### ISSUE THREAD

**Issue by lslove10010** [zhayujie/chatgpt-on-wechat#1379]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

other

### 问题描述 😯

root@ali:~/chatgpt-on-wechat# python3 app.py
[ERROR][2023-08-27 10:53:23][app.py:52] - App startup failed!
[ERROR][2023-08-27 10:53:23][app.py:53] - Expecting ',' delimiter: line 39 column 3 (char 1020)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 195, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 39 column 3 (char 1020)
root@ali:~/chatgpt-on-wechat#

### 终端日志 📒

```log
<[ERROR][2023-08-27 10:53:23][app.py:52] - App startup failed!
[ERROR][2023-08-27 10:53:23][app.py:53] - Expecting ',' delimiter: line 39 column 3 (char 1020)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 195, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 39 column 3 (char 1020)
>
```

**Comment by zhayujie** [comment]
config.json 格式的问题，39行是不是少了逗号，可以去 https://json.cn  检查

**Comment by lslove10010** [comment]
谢谢大佬，是config最后一个参数的逗号不需要，
[INFO][2023-08-27 12:14:49][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-08-27 12:14:49][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-08-27 12:14:49][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-08-27 12:14:49][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-08-27 12:14:49][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-08-27 12:14:49][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-08-27 12:14:49][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
chatgpt-tool-hub version: 0.4.6
[INFO][2023-08-27 12:14:50][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-08-27 12:14:50][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-08-27 12:14:50][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-08-27 12:14:50][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2023-08-27 12:14:50][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-08-27 12:14:50][godcmd.py:192] - [Godcmd] 因未设置口令，本次的临时口令为3567。
[INFO][2023-08-27 12:14:50][godcmd.py:207] - [Godcmd] inited
[INFO][2023-08-27 12:14:50][keyword.py:40] - [keyword] {}
[INFO][2023-08-27 12:14:50][keyword.py:42] - [keyword] inited.
[INFO][2023-08-27 12:14:50][role.py:69] - [Role] inited
[INFO][2023-08-27 12:14:50][linkai.py:23] - [LinkAI] inited
[INFO][2023-08-27 12:14:50][dungeon.py:56] - [Dungeon] inited
[INFO][2023-08-27 12:14:50][hello.py:23] - [Hello] inited
[INFO][2023-08-27 12:14:50][finish.py:23] - [Finish] inited
http://0.0.0.0:9898/
这样是启动成功了么，但是没见微信的二维码

**Comment by zhayujie** [comment]
> 

你这个用的是企业微信吧 
"channel_type": "wx"  才是个人微信，才会有二维码

**Comment by lslove10010** [comment]
是的 ，企业微信的应用能接收到我发的信息，但是不会自己回复，不懂哪个地方我没处理好，换个人微信再试试，折腾不了就只能放弃啦，纯小白，还是感谢大佬的解答~

**Comment by zhayujie** [comment]
> 是的 ，企业微信的应用能接收到我发的信息，但是不会自己回复，不懂哪个地方我没处理好，换个人微信再试试，折腾不了就只能放弃啦，纯小白，还是感谢大佬的解答~

是不是没配置ip白名单，可以参考这个文档
https://link-ai.tech/platform/link-app/wechat-com

**Comment by lslove10010** [comment]
配置啦，用讯飞或者linkai可以在企业微信创建的应用有返回，如果"channel_type": "wx"选微信的话我就不懂咋配置了~，问题我先关闭啦，发现国内的模型还是好惨，问天气都不会播，时间也不会，叫下载美女图片，居然告诉我它不处理淫秽内容，我的天阿- -~！

**Comment by zhayujie** [comment]
选wx的话，配置不用动，等着扫码就可以了
