### ISSUE TITLE
怎么样默认使用openai或者chatgpt来进行回答呢。现在看到回答的都是LINKAI

### ISSUE THREAD

**Issue by 1378056564** [zhayujie/chatgpt-on-wechat#1381]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

根目录下的config.json把use_linkai填完整之后true。之后去plugins/linkai也相应的进行配置。就可以使用了，知识库等都使用正常。并且回答问题的是【LinkAI】query=xxx reply=xxx
接下来，用管理员认证的方式进行认证。私聊给自己的微信：#auth xxx  进行认证成功,并且重载。然后ssh进行配置把根目录下面的config.json里面的use_linkai改成false，在私聊进行重载配置 #reconf 然后发现回答问题还是LINKai

### 问题描述 😯

看复现，不知道怎么回事一直是linkai进行回复

### 终端日志 📒

```log
emmm，不知道这个算啥
```

**Comment by zhayujie** [comment]
直接改config.json中的 user_linkai参数，需要重启程序才能生效

如果你想临时关闭和开启，可以用 $linkai close  和  $linkai open 指令

**Comment by 1378056564** [comment]
> 直接修改config.json中的user_linkai参数，需要重启程序才能生效
> 
> 如果你想临时关闭和开启，可以使用 $linkai close 和 $linkai open 指令

害，然后一顿修改，现在插件tool开启失败了0.0这个要怎么修复呢。重新安装一下requirements-optional.txt吗

**Comment by zhayujie** [comment]
> > 直接修改config.json中的user_linkai参数，需要重启程序才能生效
> > 如果你想临时关闭和开启，可以使用 $linkai close 和 $linkai open 指令
> 
> 害，然后一顿修改，现在插件tool开启失败了0.0这个要怎么修复呢。重新安装一下requirements-optional.txt吗

看看启动日志里tool插件注册的地方，是不是哪里报错了

**Comment by 1378056564** [comment]
> > > 直接修改config.json中的user_linkai参数，需要重启程序才能生效
> > > 如果你想临时关闭和开启，可以使用 $linkai close 和 $linkai open 指令
> > 
> > 
> > 害，然后修改一下，现在插件工具开启失败了0.0这个要怎么修复呢。重新安装一下requirements-optional.txt吗
> 
> 看看启动日志里工具插件注册的位置，是不是哪里报错了

[INFO][2023-08-28 05:20:28][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件不存在), receiver=@5e37500f89a1247ad58940e702bc731f
[WARNING][2023-08-28 05:20:31][tool.py:165] - [tool] filter invalid tool: 'news'
[WARNING][2023-08-28 05:20:31][tool.py:165] - [tool] filter invalid tool: 'google-search'
[WARNING][2023-08-28 05:20:31][tool.py:165] - [tool] filter invalid tool: 'morning-news'
[WARNING][2023-08-28 05:20:31][plugin_manager.py:148] - Failed to init TOOL, diabled. loading tool failed
[INFO][2023-08-28 05:20:31][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件开启失败), receiver=@5e37500f89a1247ad58940e702bc731f

**Comment by 1378056564** [comment]
> > > 直接修改config.json中的user_linkai参数，需要重启程序才能生效
> > > 如果你想临时关闭和开启，可以使用 $linkai close 和 $linkai open 指令
> > 
> > 
> > 害，然后修改一下，现在插件工具开启失败了0.0这个要怎么修复呢。重新安装一下requirements-optional.txt吗？
> 
> 看看启动日志里工具插件注册的位置，是不是哪里报错了

就报错这个，tool倒是在的，就是不知道为什么启动不来

**Comment by 1378056564** [comment]
> 



> > [WARNING][2023-08-28 05:20:31][tool.py:165] - [tool] filter invalid tool: 'google-search
> 
> requirements-optional.txt 之前安装过吗， 看下 plugins/tool/config.json 的配置里json格式有没有问题
> 
> 如果 还不行 在 plugins/plugin_manager.py 的 148行加一句日志 logger.exception(e) 看下具体情况

之前安装过，现在另外一个手机没拿。不方便调试。只能通过管理员命令进行重载啥的。就只能看到这些[INFO][2023-08-28 07:38:55][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[WARNING][2023-08-28 07:38:55][victorinox.py:41] - refresh the config of tools
[ERROR][2023-08-28 07:38:56][load_tools.py:62] - Now registered tools are: ['python', 'summary', 'terminal', 'browser', 'url-get', 'finance-news', 'news-api', 'arxiv', 'debug', 'answer-user', 'hello-tool', 'wolfram-alpha', 'wikipedia', 'searxng-search', 'bing-search']
[ERROR][2023-08-28 07:38:56][victorinox.py:81] - ValueError('Got unknown tool: meteo-weather')
[WARNING][2023-08-28 07:38:56][plugin_manager.py:148] - Failed to init TOOL, diabled. loading tool failed
[INFO][2023-08-28 07:38:56][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
