### ISSUE TITLE
请问微调后的GPT-3.5-trubo模型可以在机器人中使用吗？

### ISSUE THREAD

**Issue by frank0828** [zhayujie/chatgpt-on-wechat#1384]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

openai出了微调GPT-3.5-turbo的功能，那微调之后的模型能直接放到model里面使用吗？通过railways一键部署的机器人，直接在参数里填写微调的模型可以吗？

**Comment by zhayujie** [comment]
可以的

**Comment by frank0828** [comment]
> 可以的

那请问可以在railway里面设置system的内容么？

**Comment by zhayujie** [comment]
> > 可以的
> 
> 那请问可以在railway里面设置system的内容么？

可以的， character_desc 参数
