### ISSUE TITLE
新增热榜、天气插件，无需消耗openai token

### ISSUE THREAD

**Issue by fatwang2** [zhayujie/chatgpt-on-wechat#1393]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

1. Tophub热榜插件，支持通过参数切换不同类型的新闻：https://github.com/fatwang2/tophub

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/134143178/b470d538-92fe-495c-a4e9-6cd5175e993d)

2. 天气插件，实时获取国内城市天气 https://github.com/fatwang2/weather

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/134143178/9694fd00-79eb-4ed7-9323-4611c8bb3636)

**Comment by fatwang2** [comment]
更新：alapi的热榜接口目前已升级为付费接口，免费用户暂时无法使用；天气接口目前正常

**Comment by fatwang2** [comment]
更新：热榜接口更新为网易新闻，免费接口

**Comment by wangdezhong** [comment]
666

**Comment by pandaligx** [comment]
根本用不了

**Comment by fatwang2** [comment]
这个插件我现在已经不维护了，你可以使用其他插件，我来关闭这个issue
