### ISSUE TITLE
TOOL启动失败

### ISSUE THREAD

**Issue by 0TT0123** [zhayujie/chatgpt-on-wechat#1398]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

**微信启动TOOL**：@bot #enablep tool
**AI反馈**：[ERROR]插件开启失败
**CMD报错**：[WARNING][2023-09-03 20:39:51][plugin_manager.py:148] - Failed to init TOOL, diabled. 1 validation error for ChatOpenAI 
proxy
  str type expected (type=type_error.str)

排查tool的config.json文件，我的config配置为
{
  "tools": ["news"],
  "kwargs": {
    "debug": true,
    "proxy": {
      "http": "http://localhost:10809", //我的代理http端口为10809
      "https": "http://localhost:10809"
    },
    "request_timeout": 120,
    "no_default": false,
    "morning_news_api_key": "XXXXXXXXXX"
  }
}
AI基础功能可实现，但TOOL无法启动，请版主和大神们帮忙看下，谢谢了!
另：chatgpt-tool-hub version: 0.4.2
       python version：3.9.13
       pip version 23.2.1
      chatgpt-on-wechat version 1.3.5

### 问题描述 😯

<img width="657" alt="1693745134467" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/143918304/8b6b7224-0432-4c2b-b1cf-49c07ce8c351">

### 终端日志 📒

```log
<[WARNING][2023-09-03 20:39:51][plugin_manager.py:148] - Failed to init TOOL, diabled. 1 validation error for ChatOpenAI
proxy
  str type expected (type=type_error.str)
[INFO][2023-09-03 20:39:52][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件开启失败), receiver=@caa1e4f12318b8d87a09087149dd7cec92fda89c5a0167195768af6d31a7d339
>
```

**Comment by befantasy** [comment]
代理错误，是docker运行的吗？

**Comment by 0TT0123** [comment]
> 

本地部署的。。

**Comment by 0TT0123** [comment]
> 代理错误，是docker运行的吗？

本地部署的、、

**Comment by 0TT0123** [comment]
已自己排查修复，chatgpt-on-wechat目录下config的proxy未配置正确，导致报错。修复为  "proxy": "http://localhost:10809",可运行。
