### ISSUE TITLE
群聊自动欢迎功能？

### ISSUE THREAD

**Issue by GideonZY** [zhayujie/chatgpt-on-wechat#1400]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我发现白名单群聊如果有新成员加入的时候会有自动欢迎的功能，但是这部分内容我没找到在哪配置的，可以提前设置好欢迎消息吗？

**Comment by befantasy** [comment]
hello插件。

**Comment by xionghaizhi** [comment]
> hello插件。

咋关了他 没看见开启的地方呀

**Comment by 6vision** [comment]
代码在hello.py内，目前是gpt随机风格欢迎新群友，不需要使用可以关闭#disablep hello，认证管理员参考这里：https://www.wangpc.cc/aigc/chatgpt-on-wechat_plugin/
