### ISSUE TITLE
在yml文件中的model字段，只能填写一个模型，如果多个模型，该怎么写？

### ISSUE THREAD

**Issue by dfggggx198601** [zhayujie/chatgpt-on-wechat#1402]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

A:
@bot #model 

B:
[INFO]
当前模型为: claude

A:
@bot #model gpt-3.5-turbo

B:
[INFO]
模型设置为: gpt-3.5-turbo

A:
@bot #model claude

B
[ERROR]
模型名称不存在

### 问题描述 😯

我想使用claude,但发现model中，无法填入多个值，如果写2个model，切换一次后就无法切换回去，请问该如何解决呢？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by fatwang2** [comment]
model你填写一个默认值，但是各个模型需要的参数都关上，运行后通过管理员命令切换不同模型
