### ISSUE TITLE
控制台可以回应，但是微信客户端不会回复

### ISSUE THREAD

**Issue by kejiegithub** [zhayujie/chatgpt-on-wechat#1407]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

控制台日志有回复，微信没有回复

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/111474021/349cbd66-c175-44b5-af8d-2be3d1d74cb5)

### 终端日志 📒

```
[INFO][2023-09-07 21:37:37][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[INFO][2023-09-07 21:37:39][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 你好！有什么我可以帮助你的吗？), receiver=@df20ca8f708cac1ff81854b36bdf3a31f8a2ad794d0f26e15d7b00f6b9985db5
[WARNING][2023-09-07 21:43:15][wechat_message.py:74] - [WX]get other_user_id failed: 'NickName'
[INFO][2023-09-07 21:43:32][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[INFO][2023-09-07 21:43:33][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 你好！有什么我可以帮助你的吗？), receiver=@df20ca8f708cac1ff81854b36bdf3a31f8a2ad794d0f26e15d7b00f6b9985db5
```

**Comment by zhayujie** [comment]
考虑是账号相关，换一个wechat账号来给这个机器人发送消息试试
