### ISSUE TITLE
配置里边添加一个api基础链接的参数，使用代理链接

### ISSUE THREAD

**Issue by lence773** [zhayujie/chatgpt-on-wechat#1408]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 举例

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/46234853/7eac2964-e57d-4693-8286-c6ac4cd1c828)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/46234853/16456837-fa24-4863-9555-e19c2d7687e7)

**Comment by zhayujie** [comment]
这个配置已经有了
