### ISSUE TITLE
运行新模块报错

### ISSUE THREAD

**Issue by yanyuxiyangzk** [zhayujie/chatgpt-on-wechat#1416]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[INFO][2023-09-08 03:10:46][kef_ai_bot.py:84] - [kf] request post result is, res={'code': 200, 'message': 'success', 'data': {'contextId': '8660f673-86eb-446d-b34d-35b4acd21d61', 'contents': ['你好，请告诉我你需要我回答什么问题。'], 'jsonData': [], 'tags': []}}
[INFO][2023-09-08 03:10:46][kef_ai_bot.py:102] - [kf] reply=['你好，请告诉我你需要我回答什么问题。']
[ERROR][2023-09-08 03:10:46][chat_channel.py:280] - Worker return exception: can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 159, in _handle
    reply = self._decorate_reply(context, reply)
  File "/app/channel/chat_channel.py", line 238, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
TypeError: can only concatenate str (not "list") to str

### 问题描述 😯

新增加了一个模块，模仿linkai，这个是自己的私有知识库llama，能够正常回复内容，但回调提示错误[ERROR][2023-09-08 03:10:46][chat_channel.py:280] - Worker return exception: can only concatenate str (not "list") to str

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
看下返回的 reply_text 是不是一个数组，  需要是字符串结构才能拼接

**Comment by yanyuxiyangzk** [comment]
已经解决了，我的reply_text 和要求的不一样，我单独处理了，已经成功了
