### ISSUE TITLE
新增视频、文章、播客总结插件

### ISSUE THREAD

**Issue by fatwang2** [zhayujie/chatgpt-on-wechat#1417]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

实现的主要功能是对文章、视频、播客内容做总结，覆盖b站、抖音、快手、小红书、微信等各个平台！
插件地址：https://github.com/fatwang2/bibigpt

### 举例

微信文章
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/134143178/af991386-8833-4fe3-8995-16c90413ae88)

抖音视频
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/134143178/78d4a815-6343-4e89-8b99-9c21211e9fef)

小红书图文
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/134143178/b5f1e512-d4c4-4418-8d04-3a0135208b9a)

**Comment by MILKMILKKING** [comment]
抱歉，我不知道具体的KEY应该填哪个？是红色框的所有内容，还是只是箭头处的部分？
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/69726213/bedc51e6-e4ad-4593-9742-5c1308f1b2f3)

**Comment by fatwang2** [comment]
箭头那个就可以

MILKMILKKING ***@***.***>于2023年9月13日 周三00:25写道：

**Comment by MILKMILKKING** [comment]
成功了，谢谢你!!!感谢!
另外，我发一篇文章，会消耗多少时长呢？好像在bibigpt时长那里没有显示文章抵扣的时长。

**Comment by fatwang2** [comment]
我没有精确统计过，用完再买呗，反正还有60min 打底

MILKMILKKING ***@***.***>于2023年9月13日 周三00:32写道：

**Comment by MILKMILKKING** [comment]
你这个插件实在太棒了!!! 不过似乎只能发送网址。如果我将微信文章直接转发给机器人，它不会向发网址那样主动总结

**Comment by fatwang2** [comment]
是的，得等我再研究研究哈哈

MILKMILKKING ***@***.***>于2023年9月13日 周三00:42写道：

**Comment by MILKMILKKING** [comment]
哈哈，如果能直接转发个微信文章就自动总结就神了!!以后微信看到啥文章直接甩过去~

**Comment by fatwang2** [comment]
> 哈哈，如果能直接转发个微信文章就自动总结就神了!!以后微信看到啥文章直接甩过去~

理论上是可以的 只是要研究下链接卡片这种消息类型 如何被识别

**Comment by MILKMILKKING** [comment]
> > 哈哈，如果能直接转发个微信文章就自动总结就神了!!以后微信看到啥文章直接甩过去~
> 
> 理论上是可以的 只是要研究下链接卡片这种消息类型 如何被识别

https://github.com/fatwang2/read 这个是不是就是现成可以直接借鉴的例子？

**Comment by MILKMILKKING** [comment]
哈，这么巧，我加了你后面附的链接公众号，他们似乎做到了只要给他们转发一篇文章就能自动总结了。

**Comment by fatwang2** [comment]
是的

MILKMILKKING ***@***.***>于2023年9月13日 周三01:22写道：

**Comment by zhayujie** [comment]
不错的

**Comment by fatwang2** [comment]
> 不错的

嘿嘿，感谢你这个项目，开放的插件生态发挥空间太大了，下一步计划支持链接卡片（还没研究明白怎么搞）、配置文件改为插件内json文件、配置支持prompt！

**Comment by MILKMILKKING** [comment]
期待!!

> > 不错的
> 
> 嘿嘿，感谢你这个项目，开放的插件生态发挥空间太大了，下一步计划支持链接卡片（还没研究明白怎么搞）、配置文件改为插件内json文件、配置支持prompt！

**Comment by crossai-2033** [comment]
@fatwang2 这个插件什么时候能变成内置的插件

**Comment by fatwang2** [comment]
那就要看原作者了，你为啥需要是内置的呀

CrossAI ***@***.***>于2023年9月22日 周五20:37写道：

**Comment by fatwang2** [comment]
@crossai-2033 已更新插件，支持插件内的配置文件，由于更名，需卸载原有插件，重新安装，具体见说明文档

**Comment by fatwang2** [comment]
@MILKMILKKING 插件更新了，支持微信链接卡片的总结啦，不过我改了名，需要把旧插件卸载重装下，配置文件也换了地方，需要重新整下，你可以考虑下要不要更新

**Comment by MILKMILKKING** [comment]
> @MILKMILKKING 插件更新了，支持微信链接卡片的总结啦，不过我改了名，需要把旧插件卸载重装下，配置文件也换了地方，需要重新整下，你可以考虑下要不要更新

Wow 我回去更新下！！！
