### ISSUE TITLE
插件readim：读取图像主要信息+OCR，demo代码

### ISSUE THREAD

**Issue by Loping151** [zhayujie/chatgpt-on-wechat#1419]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

他连伊布都认得出来，我哭死

请先参考issue #1414 

仓库地址：https://github.com/Loping151/plugin_readim/

demo暂不pr。欢迎协作完善

### 举例

![2](https://github.com/zhayujie/chatgpt-on-wechat/assets/97866915/ca61ef4b-66be-4f65-87f1-4a19a653ffbd)

**Comment by zhayujie** [comment]
see #1414
