### ISSUE TITLE
是否可以在使用过程中切换GPT模型？

### ISSUE THREAD

**Issue by Payne-Wang** [zhayujie/chatgpt-on-wechat#1420]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

目前我的机器人正在运行，后台使用GPT3.5模型，我现在有个4.0的API，我想让机器人既支持3.5又支持4.0，可以在聊天界面来回切换，目前这个项目可以做到嘛？谢谢大佬！

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
使用管理员指令 #model gpt-4 就可以切换

**Comment by Payne-Wang** [comment]
那比如config文件如何设置？是把3.5和4都写上吗？还有api和base url 。如果有说明文档，请大佬指个路，感激不尽！

**Comment by zhayujie** [comment]
> a

config.json中是启动后默认使用的， #model 指令用来临时切换
