### ISSUE TITLE
通过Railway快速部署，怎么使用midjourney能力

### ISSUE THREAD

**Issue by crossai-2033** [zhayujie/chatgpt-on-wechat#1430]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

1. 通过本地部署，开始LinkAI去支持midjourney画图比较容易，并且已经实现。
2. 通过Railway快速部署，配置参数后，发现midjourney无法开启，一直默认使用chatgpt去画图。

### 举例

本地配置好LinkAI后，可以通过midjourney代理画图

### 动机

是否可以通过修改配置搞定，或者可以直接修改源码部署的方式实现通过Railway快速部署并且支持midjourney画图的能力。

**Comment by zhayujie** [comment]
最新版本的镜像直接通过管理员指令  #mj open 就可以开启

可以重新部署一下railway

**Comment by crossai-2033** [comment]
@zhayujie 抱歉，我是直接通过railway的web端操作部署的，不知道这个管理员指令#mj open，写到哪里

**Comment by zhayujie** [comment]
> @zhayujie 抱歉，我是直接通过railway的web端操作部署的，不知道这个管理员指令#mj open，写到哪里

通过私聊机器人完成

先进行管理员认证
https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/godcmd/README.md

再开启mj插件: $mj open
https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/linkai/README.md

**Comment by crossai-2033** [comment]
@zhayujie 抱歉，可能我没Get到您的点，我之前在本地是运行成功过的，LinkAI我也都付费跑通了，后面我是通过railway的web一键部署。没看清楚从哪里能够配置 $mj open的命令

<img width="953" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/310315/bba996e0-ff15-48d1-aca2-91db323c1c5d">
是在这个服务启动时候启动么？貌似不可以。
