### ISSUE TITLE
如何支持微信链接卡片

### ISSUE THREAD

**Issue by fatwang2** [zhayujie/chatgpt-on-wechat#1439]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

正在开发一个插件，想知道如何识别微信文章的链接卡片，研究了 itchat 但是没搞明白

### 动机

插件开发

**Comment by fatwang2** [comment]
> 需要改wechat_channel.py，注册一下缺失的几类消息，链接是SHARING。得做挺多修改。 可以添加一下发个链接看看返回的json
> 
> @itchat.msg_register([MAP, CARD, SHARING]) def text_reply(msg): #将 msg 字典转换为 JSON 格式的字符串 msg_json = json.dumps(msg, indent=4, ensure_ascii=False) # 发送消息给发送者 itchat.send('Received message:\n{}'.format(msg_json), msg['FromUserName'])
@befantasy 研究白天还没整明白，请问您有写过类似的插件或者实例吗？

**Comment by befantasy** [comment]
> > 需要改wechat_channel.py，注册一下缺失的几类消息，链接是SHARING。得做挺多修改。 可以添加一下发个链接看看返回的json
> > @itchat.msg_register([MAP, CARD, SHARING]) def text_reply(msg): #将 msg 字典转换为 JSON 格式的字符串 msg_json = json.dumps(msg, indent=4, ensure_ascii=False) # 发送消息给发送者 itchat.send('Received message:\n{}'.format(msg_json), msg['FromUserName'])
> > @befantasy 研究白天还没整明白，请问您有写过类似的插件或者实例吗？

https://github.com/zhayujie/chatgpt-on-wechat/pull/1427

**Comment by fatwang2** [comment]
@befantasy 我看您这个项目里增加的类型没有包含sharing，是不是我参考你这几种类型的实例，单独增加一个sharing类型？

**Comment by befantasy** [comment]
> @befantasy 我看您这个项目里增加的类型没有包含sharing，是不是我参考你这几种类型的实例，单独增加一个sharing类型？

理论上是的，但我改的那些都是发送的通道。sharing需要注册监听接收，在开头那里。
你可以参考一楼先注册一下sharing，使程序收到sharing时，解出msg回复给你，研究一下sharing的msg结构。

**Comment by fatwang2** [comment]
修改后没有任何返回，开了debug也没有，不知道是哪里没搞对

**Comment by zhayujie** [comment]
已支持
