### ISSUE TITLE
模型版本是GPT-2？这个可以升级吗？关于时间的问答都停留在2020年？

### ISSUE THREAD

**Issue by realzsy** [zhayujie/chatgpt-on-wechat#144]
机器人答复使用的模型是GPT-2，且问其时间答复是2020年，这个多少有点智障了啊？

**Comment by renny-ren** [comment]
确实有这个问题，但我看了代码里用的确实是 GPT-3 model，我把同样的代码拿出来单独运行是对的，估计是哪里有 bug。

**Comment by realzsy** [comment]
> 确实有这个问题，但我看了代码里用的确实是 GPT-3 model，我把同样的代码拿出来单独运行是对的，估计是哪里有 bug。

哦，我还以为机器人很清楚自己的版本，他回答自己是基于gpt-2的。

**Comment by renny-ren** [comment]
微信里：
<img width="545" alt="image" src="https://user-images.githubusercontent.com/19547819/218008837-ef558244-fd64-490d-9836-66e0d5a7bd1d.png">

单独运行：
![image](https://user-images.githubusercontent.com/19547819/218008869-e42965c7-c2ef-4003-8c72-95d213adc172.png)

**Comment by realzsy** [comment]
> 微信里：
> <img width="545" alt="image" src="https://user-images.githubusercontent.com/19547819/218008837-ef558244-fd64-490d-9836-66e0d5a7bd1d.png">
> 
> 单独运行：
> ![image](https://user-images.githubusercontent.com/19547819/218008869-e42965c7-c2ef-4003-8c72-95d213adc172.png)
> 

就是代码确实是gpt-3，只是机器人自己不知道？

**Comment by defamilo** [comment]
[我的没问题
<img width="594" alt="WX20230210-144733@2x" src="https://user-images.githubusercontent.com/7792149/218022156-fc2acc19-6e2e-4d09-8353-698fc92c891a.png">

**Comment by realzsy** [comment]
> [我的没问题，昨天下午部署的
> <img width="594" alt="WX20230210-144733@2x" src="https://user-images.githubusercontent.com/7792149/218022156-fc2acc19-6e2e-4d09-8353-698fc92c891a.png">
> 

我昨天晚上部署的，有一次他说自己是gpt-3，我又问你到底是2还是3，又回我是2

**Comment by renny-ren** [comment]
> [我的没问题，昨天下午部署的 <img alt="WX20230210-144733@2x" width="594" src="https://user-images.githubusercontent.com/7792149/218022156-fc2acc19-6e2e-4d09-8353-698fc92c891a.png">

我的不管怎么问他都说他是 GPT-2，而且还否认 GPT-3 是最新版本。
看了代码没发现问题。难道是它在骗我？。

<img width="582" alt="image" src="https://user-images.githubusercontent.com/19547819/218023110-1acf4f63-6609-4ab0-a7a5-200b036553b7.png">

**Comment by defamilo** [comment]
> 

我的确实没问题。。。
<img width="592" alt="WX20230210-151413@2x" src="https://user-images.githubusercontent.com/7792149/218026591-a6135a5b-ee8d-49d0-882f-5dff8f3543e8.png">

**Comment by wpneu6699** [comment]
感觉和chatgpt对比，差得有点远啊，是gpt-3.5吗

**Comment by Hanhaijl** [comment]
> 

我的也是，关于最简单的判断方式就是问他时间。
@zhayujie 大佬 ，这是BUG吗？

**Comment by zhayujie** [comment]
> 我的也是，关于最简单的判断方式就是问他时间。 @zhayujie 大佬 ，这是BUG吗？

时间没办法，模型设置的就是这个时候
