### ISSUE TITLE
是否可以内置一个文章内容摘要插件

### ISSUE THREAD

**Issue by crossai-2033** [zhayujie/chatgpt-on-wechat#1443]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

是否可以镜像内置一个微信文章内容摘要的插件。

### 举例

类似于绘画一下，可以配置一个关键字，比如「内容摘要」+ 微信文章链接，就把微信内容提取出来。

### 动机

这个能力还挺实用了，看有人通过知了阅读的API简单支持了一下，建议官方可以内置。

**Comment by fatwang2** [comment]
哥们，我的内容总结插件更新了，支持插件内配置文件了，你可以试试

**Comment by zhayujie** [comment]
> ### ⚠️ 搜索是否存在类似issue
> * [x]  我已经搜索过issues和disscussions，没有发现相似issue
> 
> ### 总结
> 是否可以镜像内置一个微信文章内容摘要的插件。
> 
> ### 举例
> 类似于绘画一下，可以配置一个关键字，比如「内容摘要」+ 微信文章链接，就把微信内容提取出来。
> 
> ### 动机
> 这个能力还挺实用了，看有人通过知了阅读的API简单支持了一下，建议官方可以内置。

在linkai插件加上了 文档摘要 +  内容对话的功能， 可以体验下， [插件说明](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/linkai#3%E6%96%87%E6%A1%A3%E6%80%BB%E7%BB%93%E5%AF%B9%E8%AF%9D%E5%8A%9F%E8%83%BD)

目前支持发送 文件、 公众号链接卡片

**Comment by crossai-2033** [comment]
@zhayujie 感谢支持，但我目前试了一下，没有生效，不知道哪个环节的问题。我大概是做了以下几步：

1. git更新仓库，拉取最新代码
2. 我是通过docker部署，配置更改是通过
```
volumes:
      - ./config.json:/app/plugins/config.json
```
3. 在config.json中配置了 

```
 "linkai": {
        "group_app_map": {
            "测试群1": "default",
            "测试群2": "Kv2fXJcH"
        },
        "midjourney": {
            "enabled": true,
            "auto_translate": true,
            "img_proxy": true,
            "max_tasks": 3,
            "max_tasks_per_user": 1,
            "use_image_create_prefix": true
        },
        "summary": {
            "enabled": true,
            "group_enabled": true,
            "max_file_size": 10000
        }
    }
```

4. 重启docker 
```
sudo docker compose up -d
sudo docker compose down
sudo docker compose start
```

5. 测试机器人  @机器人  http:xxx公众号链接，无法解析

PS：我的文本对话和MJ画图都是运行正常的，也在LINKAI后台能够看到正常计费积分。

**Comment by befantasy** [comment]
docker compose down up会重新拉取镜像，在你docker没有做volume的持久化配置的情况下，之前github拉取的新代码被docker image里的覆盖回去了。

重启docker用：docker compose restart

**Comment by zhayujie** [comment]
> @zhayujie 感谢支持，但我目前试了一下，没有生效，不知道哪个环节的问题。我大概是做了以下几步：
> 
> 1. git更新仓库，拉取最新代码
> 2. 我是通过docker部署，配置更改是通过
> 
> ```
> volumes:
>       - ./config.json:/app/plugins/config.json
> ```
> 
> 3. 在config.json中配置了
> 
> ```
>  "linkai": {
>         "group_app_map": {
>             "测试群1": "default",
>             "测试群2": "Kv2fXJcH"
>         },
>         "midjourney": {
>             "enabled": true,
>             "auto_translate": true,
>             "img_proxy": true,
>             "max_tasks": 3,
>             "max_tasks_per_user": 1,
>             "use_image_create_prefix": true
>         },
>         "summary": {
>             "enabled": true,
>             "group_enabled": true,
>             "max_file_size": 10000
>         }
>     }
> ```
> 
> 4. 重启docker
> 
> ```
> sudo docker compose up -d
> sudo docker compose down
> sudo docker compose start
> ```
> 
> 5. 测试机器人  @机器人  http:xxx公众号链接，无法解析
> 
> PS：我的文本对话和MJ画图都是运行正常的，也在LINKAI后台能够看到正常计费积分。

docker 部署更新的话不用重新拉取代码，拉取镜像就可以了。

由于我还没有发布latest 版本镜像。可以先执行这一行获取master镜像：

```
docker pull zhayujie/chatgpt-on-wechat:master
```

然后修改 docker-compose.yml

```
image: zhayujie/chatgpt-on-wechat:master
```

接着关闭容器

```
docker compose down
```

然后启动容器

```
docker compose up
```

**Comment by crossai-2033** [comment]
@zhayujie 感谢已经可以了。

没想好这种交互方式，目前是直接@机器人 给一个链接，这样更合理，还是有个出发动作，比如分析网页：xxx链接，更合理一下，目前应该这个插件不支持动作触发，

**Comment by crossai-2033** [comment]
@zhayujie 感谢已经可以了。

没想好这种交互方式，目前是直接@机器人 给一个链接，这样更合理，还是有个出发动作，比如分析网页：xxx链接，更合理一下，目前应该这个插件不支持动作触发，

**Comment by zhayujie** [comment]
> @zhayujie 感谢已经可以了。
> 
> 没想好这种交互方式，目前是直接@机器人 给一个链接，这样更合理，还是有个出发动作，比如分析网页：xxx链接，更合理一下，目前应该这个插件不支持动作触发，

这里可以加个触发指令的配置

不过如果是直接分享公众号链接卡片， 或者发送文件的话 ，就没办法带着指令了

**Comment by you-know-m** [comment]
这是为啥


<img width="1182" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/167161999/0437d6d5-5598-4898-8abb-752d56304797">
