### ISSUE TITLE
讯飞模型 回复时请求错误

### ISSUE THREAD

**Issue by Jesoone** [zhayujie/chatgpt-on-wechat#1444]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

正常测试询问

### 问题描述 😯

version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: ''
      MODEL: 'xunfei'
      xunfei_app_id: '*****'
      xunfei_api_secret: '*******************************************'
      xunfei_api_key: '********************'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["?","bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["?","@bot"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''

### 终端日志 📒

chatgpt-on-wechat  | [INFO][2023-09-23 02:08:58][xunfei_spark_bot.py:54] - [XunFei] query=测试
chatgpt-on-wechat  | [INFO][2023-09-23 02:08:58][xunfei_spark_bot.py:96] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '撒旦暗色调'}, {'role': 'user', 'content': 'asd asd'}, {'role': 'assistant', 'content': ''}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '测试'}]
chatgpt-on-wechat  | [INFO][2023-09-23 02:09:00][xunfei_spark_bot.py:192] - [XunFei] Start websocket, session_id=@6d675cfb923b249f6be2b3986db85b83bb65ef7614094c1ca02858f01fc_169543493866
chatgpt-on-wechat  | [ERROR][2023-09-23 02:09:00][xunfei_spark_bot.py:207] - 请求错误: 10004, {'header': {'code': 10004, 'message': "SchemaCheckError:(10:09:00.305) '$.header.app_id' Invalid type, expected: string , given: float64; ", 'sid': 'cid000b8f3a@dx18abfcc1f9a4b540', 'status': 2}}
chatgpt-on-wechat  | [INFO][2023-09-23 02:09:29][xunfei_spark_bot.py:86] - [XunFei-API] response=, time=30.14193941626587s, usage={}
chatgpt-on-wechat  | [INFO][2023-09-23 02:09:29][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=@偏挚丶
chatgpt-on-wechat  | ), receiver=@@267ead4661a19a2680f8ce1b76afb4e2de6be4a83523af7af62afd6be20bf

**Comment by zhayujie** [comment]
确认下 xunfei_app_id 这个参数是不是正确

**Comment by Jesoone** [comment]
是正确的

**Comment by Jesoone** [comment]
使用讯飞 OPEN_AI_API_KEY: ''是必填项吗。

**Comment by zhayujie** [comment]
> 使用讯飞 OPEN_AI_API_KEY: ''是必填项吗。

不是必填
