### ISSUE TITLE
微信会封号，可不可以改成公众号或者小程序

### ISSUE THREAD

**Issue by lifeofbow** [zhayujie/chatgpt-on-wechat#145]

**Comment by DwyaneLee** [comment]
在研究公众号和小程序的接入方式，小程序的麻烦点，而且最近好像小程序的chatgpt都被下架了，公众号的网上很多教程

**Comment by synjkc** [comment]
我的WX今天 已经被封了

**Comment by jjcizi** [comment]
微信很容易被封；企业微信和公众号都只能单向传信息，不能双向。

**Comment by zhayujie** [comment]
公众号的参考这个项目：https://github.com/zhayujie/bot-on-anything/

**Comment by FaderYin** [comment]
> 微信很容易被封；企业微信和公众号都只能单向传信息，不能双向。

这个是什么意思，就是不会被封号吗
