### ISSUE TITLE
讯飞接入失败

### ISSUE THREAD

**Issue by sangguosha** [zhayujie/chatgpt-on-wechat#1458]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

运行扫码成功后，提问后直接报错

### 问题描述 😯

Exception in thread Thread-5:
Traceback (most recent call last):
  File "E:\新建文件夹 (2)\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\新建文件夹 (2)\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\chatwechat\chatgpt-on-wechat-1.3.9\bot\xunfei\xunfei_spark_bot.py", line 99, in create_web_socket
    ws = websocket.WebSocketApp(wsUrl, on_message=on_message, on_error=on_error, on_close=on_close,
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
[INFO][2023-09-28 18:17:03][xunfei_spark_bot.py:86] - [XunFei-API] response=, time=32.75139355659485s, usage={}
[INFO][2023-09-28 18:17:03][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[hfk] ), receiver=@17ce9ee8403de16b8fa0290cb2edd018b3c124132a5be0e63c12ed684959f647

### 终端日志 📒

```log
[INFO][2023-09-28 18:15:33][wechat_channel.py:126] - Wechat login success, user_id: @****************, nickname: hfk
[INFO][2023-09-28 18:15:36][bridge.py:39] - create bot xunfei for chat
[INFO][2023-09-28 18:15:36][xunfei_spark_bot.py:54] - [XunFei] query=你是谁
[INFO][2023-09-28 18:15:36][xunfei_spark_bot.py:96] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你是谁'}]
[INFO][2023-09-28 18:16:09][xunfei_spark_bot.py:86] - [XunFei-API] response=, time=32.73078227043152s, usage={}
[INFO][2023-09-28 18:16:09][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[hfk] ), receiver=@17ce9ee8403de16b8fa0290cb2edd018b3c124132a5be0e63c12ed684959f647
[INFO][2023-09-28 18:16:30][xunfei_spark_bot.py:54] - [XunFei] query=现在是什么时候
[INFO][2023-09-28 18:16:30][xunfei_spark_bot.py:96] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你是谁'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '现在是什么时候'}]
[INFO][2023-09-28 18:17:03][xunfei_spark_bot.py:86] - [XunFei-API] response=, time=32.75139355659485s, usage={}
[INFO][2023-09-28 18:17:03][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[hfk] ), receiver=@17ce9ee8403de16b8fa0290cb2edd018b3c124132a5be0e63c12ed684959f647

```

**Comment by zhayujie** [comment]
缺少websocket依赖
