### ISSUE TITLE
既然微信会提示违规，那么布置到Telegram是不是会好一点？

### ISSUE THREAD

**Issue by Linkegee** [zhayujie/chatgpt-on-wechat#146]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

既然微信会提示违规，那么布置到Telegram是不是会好一点？
但是我查阅了一些资料并没有人做过相关的project..本人能力也有限，希望能一起探讨下

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by DwyaneLee** [comment]
我记得在github还是csdn上见到过有类似开源的，接入了tg的

**Comment by Linkegee** [comment]
> 我记得在github还是csdn上见到过有类似开源的，接入了tg的

可能是我搜索方式不对所以没找到，请赐教🙏

**Comment by zhayujie** [comment]
telegram已支持
https://github.com/zhayujie/bot-on-anything
