### ISSUE TITLE
项目不支持ARM平台吗

### ISSUE THREAD

**Issue by zabc4066** [zhayujie/chatgpt-on-wechat#1460]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 举例

[+] Running 3/3
 ✔ Network root_default                                                                                                                                             Created                   0.1s 
 ✔ Container chatgpt-on-wechat                                                                                                                                      Started                  29.0s 
 ! chatgpt-on-wechat The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                           0.0s

**Comment by zhaoxitao** [comment]
支持的，已经在树莓派平台成功部署

**Comment by harlanhu** [comment]
请看 #1335
