### ISSUE TITLE
大佬救救，在本地能跑，但是放到服务器上就启动不起来了....

### ISSUE THREAD

**Issue by zy00000** [zhayujie/chatgpt-on-wechat#1461]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

纯新手，第一次玩github，项目在本地可以正常使用，但是丢上服务器一直起不来
腾讯云的服务器+宝塔面板，
在面板上添加了python项目，python3.8.5，模块也全加载了，运行方式选python和gunicorn都起不来，选uwsgi可以运行，但是日志里提示的是找不到app入口，二维码也加载不出来，有没大佬救救孩子~ ~ 

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/25195482/1c617963-de8a-4017-baa5-da766b0e6a76)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/25195482/21246c0f-509a-489f-b45b-20c15cf89587)

### 终端日志 📒

```log
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct 2 21:10:32 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 29 September 2023 21:11:49
os: Linux-3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023
nodename: VM-4-12-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /www/server/panel
writing pidfile to /www/wwwroot/chatgpt-on-wechat-master/uwsgi.pid
detected binary path: /www/server/pyporject_evn/chatgpt-on-wechat-master_venv/bin/uwsgi
setgid() to 1000
setuid() to 1000
chdir() to /www/wwwroot/chatgpt-on-wechat-master
your processes number limit is 7908
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5005 fd 3
Python version: 3.8.5 (default, Sep 30 2023, 05:02:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0xfcd680
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
unable to find "application" callable in file /www/wwwroot/chatgpt-on-wechat-master/app.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1686)
spawned uWSGI worker 1 (pid: 1687, cores: 2)
spawned uWSGI worker 2 (pid: 1688, cores: 2)
spawned uWSGI worker 3 (pid: 1689, cores: 2)
spawned uWSGI worker 4 (pid: 1690, cores: 2)
```

**Comment by zy00000** [comment]
试了下运行方式为python的时候，启动不起来，提示是日志文件不存在，但是我很确定日志文件就在文件夹下，我是本地能正常跑的整个文件夹上传上来的。
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/25195482/2cf9c63b-caf9-4553-9f5a-cd17ccde81d2)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/25195482/ba6f9514-6ce3-4815-9335-b9a70f085432)

**Comment by zhayujie** [comment]
运行方式选python就可以，但是宝塔的配置文件相对路径貌似一直有点问题

建议你再在腾讯云CVM控制台直接登录服务器，进入项目目录下 执行 python3 app.py 来运行程序

**Comment by zy00000** [comment]
> 运行方式选python就可以，但是宝塔的配置文件相对路径貌似一直有点问题
> 
> 建议你再在腾讯云CVM控制台直接登录服务器，进入项目目录下 执行 python3 app.py 来运行程序

感谢~ ~ 直接终端运行可以启动起来
