### ISSUE TITLE
使用千帆模型+百度语音识别合成出错，用其他语言模型+百度语音就正常

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#1462]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows 10

### 运行的python版本是?

Python 3.11.5

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我使用千帆模型+百度语音识别+百度语音合成，就会出错“[INFO][2023-10-03 08:53:40][baidu_wenxin.py:79] - [BAIDU] response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'}”

如果 用OPANAI，讯飞++百度语音识别+百度语音合成，就没任何问题, 发语音，回复MP3

不同情况都是用的相同百度语音key，百度语音后台也没有报告超量使用问题。只要切换config为非千帆模型就能成功，用千帆则超量ERR。WHY?

用千帆模型的config
`{
  "baidu_wenxin_api_key": "fG##############Mc",
  "baidu_wenxin_secret_key": "RU##############Wz",
  "model": "wenxin",
  "channel_type": "wx",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": [
    ""
  ],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": [
    "@bot"
  ],
  "group_name_white_list": [
    "宁波小徐学英语",
    "ChatGPT测试群2"
  ],
  "group_chat_in_one_session": [
    "ChatGPT测试群"
  ],
  "image_create_prefix": [
    "画",
    "看",
    "找"
  ],
  "voice_to_text": "baidu", 
  "baidu_app_id": "4##############9",
  "baidu_api_key": "qzS##############O",
  "baidu_secret_key": "Lz##############iQ",
  "speech_recognition": true,
  "group_speech_recognition": true,
  "text_to_voice": "baidu", 
  "voice_reply_voice": false,
  "always_reply_voice": false,
  "conversation_max_tokens": 1000,
  "expires_in_seconds": 3600,
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
  "temperature": 0.7,
  "top_p": 1,
  "subscribe_msg": "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,
  "linkai_api_key": "",
  "linkai_app_code": ""
}
`

用其他模型的config，比如讯飞
`{
  "xunfei_app_id": "7##############ff",
  "xunfei_api_key": "7f##############9",
  "xunfei_api_secret": "Nz##############U5",
  "model": "xunfei",
  "channel_type": "wx",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": [
    ""
  ],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": [
    "@bot"
  ],
  "group_name_white_list": [
    "宁波小徐学英语",
    "ChatGPT测试群2"
  ],
  "group_chat_in_one_session": [
    "ChatGPT测试群"
  ],
  "image_create_prefix": [
    "画",
    "看",
    "找"
  ],
  "voice_to_text": "baidu", 
  "baidu_app_id": "4##############9",
  "baidu_api_key": "q##############O",
  "baidu_secret_key": "L##############iQ",
  "speech_recognition": true,
  "group_speech_recognition": true,
  "text_to_voice": "baidu", 
  "voice_reply_voice": true,
  "always_reply_voice": false,
  "conversation_max_tokens": 1000,
  "expires_in_seconds": 3600,
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
  "temperature": 0.7,
  "top_p": 1,
  "subscribe_msg": "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,
  "linkai_api_key": "",
  "linkai_app_code": ""
}
`

### 终端日志 📒

```log
[INFO][2023-10-03 08:53:38][bridge.py:39] - create bot baidu for voice_to_text
[INFO][2023-10-03 08:53:38][baidu_voice.py:67] - 百度语音识别到了：['您好。']
[INFO][2023-10-03 08:53:38][bridge.py:39] - create bot baidu for chat
[INFO][2023-10-03 08:53:39][baidu_wenxin.py:25] - [BAIDU] query=您好。
[INFO][2023-10-03 08:53:39][baidu_wenxin.py:63] - [BAIDU] model=eb-instant
[INFO][2023-10-03 08:53:40][baidu_wenxin.py:79] - [BAIDU] response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'}
[WARNING][2023-10-03 08:53:40][baidu_wenxin.py:91] - [BAIDU] Exception: 'result'
[ERROR][2023-10-03 08:53:40][chat_channel.py:282] - Worker return exception: 'total_tokens'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\qianfan-on-wechat\channel\chat_channel.py", line 155, in _handle
    reply = self._generate_reply(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\qianfan-on-wechat\channel\chat_channel.py", line 202, in _generate_reply
    reply = self._generate_reply(new_context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\qianfan-on-wechat\channel\chat_channel.py", line 177, in _generate_reply
    reply = super().build_reply_content(context.content, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\qianfan-on-wechat\channel\channel.py", line 37, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\qianfan-on-wechat\bridge\bridge.py", line 54, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\qianfan-on-wechat\bot\baidu\baidu_wenxin.py", line 38, in reply
    result["total_tokens"],
    ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'total_tokens'
```

**Comment by taozhiyuai** [comment]
解决办法就是给百度充值! 是千帆的Key需要充值， 语音的Key免费额度超级多。

**Comment by effectZz** [comment]
我用千帆模型+百度语音是没问题的，你需要去百度语音的控制台添加一个应用，然后把相应的接口开通，最后给你的账号充点钱就行了。

**Comment by nonamegivetome** [comment]
我充值了，还是显示response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'}

**Comment by flyice8** [comment]
百度英文语音你们能调试的通吗？
