### ISSUE TITLE
希望在1个知识库应用中能够至少关联2个知识库

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#1464]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望在1个知识库应用中能够至少关联2个知识库。因为多为客户可能有共同的行业知识库，有个性化的知识库，因此希望至少能关联两个知识库。这样减少积分消耗。

### 动机

这样减少积分消耗和资源

**Comment by taozhiyuai** [comment]
应该用linkai的映射功能解决

**Comment by zhayujie** [comment]
> ### ⚠️ 搜索是否存在类似issue
> * [x]  我已经搜索过issues和disscussions，没有发现相似issue
> 
> ### 总结
> 希望在1个知识库应用中能够至少关联2个知识库。因为多为客户可能有共同的行业知识库，有个性化的知识库，因此希望至少能关联两个知识库。这样减少积分消耗。
> 
> ### 举例
> _No response_
> 
> ### 动机
> 这样减少积分消耗和资源

现在在应用配置里是可以一个应用 关联多个 知识库的
<img width="764" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/26161723/ca56cb8d-fa4d-4da8-82b0-b6ca2f933681">
