### ISSUE TITLE
希望能把bing search直接作为机器人调用的接口，而不要通过插件tool

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#1474]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望能把bing search直接作为机器人调用的接口，而不要通过插件tool. 插件的效率太低了，而且返回的信息也太少，体验太差。

**Comment by 6vision** [comment]
linkai 平台已支持配置bing key直接联网：https://chat.link-ai.tech/home   创建应用，应用里面开启联网插件即可
