### ISSUE TITLE
dockercompose部署使用第三方api及第三方api域名，Bad Gateway: Invalid response object from API: '{"data":null,"success":false,"errorCode":404,"message":"Page not found"}' (HTTP response code was 404)

### ISSUE THREAD

**Issue by azxcvjj** [zhayujie/chatgpt-on-wechat#1477]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[docker-compose.yml.txt](https://github.com/zhayujie/chatgpt-on-wechat/files/12903070/docker-compose.yml.txt)

### 问题描述 😯

是我环境变量写的不对吗？使用官方api不写OPEN_AI_API_BASE: ''这个环境变量的时候就没问题。
![图片_20231014142815](https://github.com/zhayujie/chatgpt-on-wechat/assets/38803089/29d6bb20-6a1f-49ff-93b0-a9db0a0271d5)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by azxcvjj** [comment]
解决了，第三方api域名后面也要加/v1

**Comment by jayling1111** [comment]
你好，我也是用的这个第三方接口，配置文件如何改成这个网关，可以给我看看吗

**Comment by azxcvjj** [comment]
> 你好，我也是用的这个第三方接口，配置文件如何改成这个网关，可以给我看看吗

这么写就行
"open_ai_api_base": "https://https://api.aiproxy.io/v1",

**Comment by jayling1111** [comment]
> > 你好，我也是用的这个第三方接口，配置文件如何改成这个网关，可以给我看看吗
> 
> 这么写就行
> "open_ai_api_base": "https://https://api.aiproxy.io/v1",
是在compose yaml文件添加然后部署吗 我这样操作没有生效

**Comment by azxcvjj** [comment]
> > > 你好，我也是用的这个第三方接口，配置文件如何改成这个网关，可以给我看看吗
> > 
> > 这么写就行
> > "open_ai_api_base": "https://https://api.aiproxy.io/v1",
> 是在compose yaml文件添加然后部署吗 我这样操作没有生效

不是，这个是config.json里的写法。
dockercompose的话是这样：
OPEN_AI_API_BASE: 'https://api.aiproxy.io/v1'

**Comment by jayling1111** [comment]
感谢，已成功对接aipory那边，还有个问题，aiproxy那边扣的4.0额度，怎么微信机器人仍然还是3.0版本，你会这样吗？


机器人： 我是基于GPT-3模型的版本。GPT-3是OpenAI最新发布的大型语言模型，它比之前的版本更大、更强大，具有更好的理解和生成语言的能力。

**Comment by azxcvjj** [comment]
> 感谢，已成功对接aipory那边，还有个问题，aiproxy那边扣的4.0额度，怎么微信机器人仍然还是3.0版本，你会这样吗？
> 
> 
> 
> 
> 
> 机器人： 我是基于GPT-3模型的版本。GPT-3是OpenAI最新发布的大型语言模型，它比之前的版本更大、更强大，具有更好的理解和生成语言的能力。

应该是bug，我测试了也是这样，问他也是这么说，应该不影响使用，你可以重提issue

**Comment by jayling1111** [comment]
画图功能你正常吗 我换第三方后不支持了 说是文字模型 不支持照片

**Comment by azxcvjj** [comment]
> 画图功能你正常吗 我换第三方后不支持了 说是文字模型 不支持照片

我好像也不行，看日志是调用失败，还没空研究啥问题

**Comment by azxcvjj** [comment]
> 画图功能你正常吗 我换第三方后不支持了 说是文字模型 不支持照片

画图已解决，修改chatgpt-on-wechat/bot/openai中open_ai_image.py文件里第28行，改为
size=conf().get("image_create_size") or "1024x1024",  # 图片大小,dall-e-2可选有 256x256 512x512 1024x1024 ,dall-e-3可选有 1024x1024 1792x1024 1024x1792

带宽大的机器可以用dall-e-3，小水管2就行，不然下图片下的慢，回复你也慢。

**Comment by jayling1111** [comment]
> > 画图功能你正常吗 我换第三方后不支持了 说是文字模型 不支持照片
> 
> 画图已解决，修改chatgpt-on-wechat/bot/openai中open_ai_image.py文件里第28行，改为 size=conf().get("image_create_size") or "1024x1024", # 图片大小,dall-e-2可选有 256x256 512x512 1024x1024 ,dall-e-3可选有 1024x1024 1792x1024 1024x1792
> 
> 带宽大的机器可以用dall-e-3，小水管2就行，不然下图片下的慢，回复你也慢。

原来如此，我尝试在config文件添加了size参数1024，原来是没有生效，还得进入py文件改
__

**Comment by azxcvjj** [comment]
> > > 画图功能你正常吗 我换第三方后不支持了 说是文字模型 不支持照片
> > 
> > 
> > 画图已解决，修改chatgpt-on-wechat/bot/openai中open_ai_image.py文件里第28行，改为 size=conf().get("image_create_size") or "1024x1024", # 图片大小,dall-e-2可选有 256x256 512x512 1024x1024 ,dall-e-3可选有 1024x1024 1792x1024 1024x1792
> > 带宽大的机器可以用dall-e-3，小水管2就行，不然下图片下的慢，回复你也慢。
> 
> 原来如此，我尝试在config文件添加了size参数1024，原来是没有生效，还得进入py文件改 __

更正一下，aiproxy这个接口好像只有dall-e-3.。。。。。。。。。。。

**Comment by jayling1111** [comment]
> > > > 画图功能你正常吗 我换第三方后不支持了 说是文字模型 不支持照片
> > > 
> > > 
> > > 画图已解决，修改chatgpt-on-wechat/bot/openai中open_ai_image.py文件里第28行，改为 size=conf().get("image_create_size") or "1024x1024", # 图片大小,dall-e-2可选有 256x256 512x512 1024x1024 ,dall-e-3可选有 1024x1024 1792x1024 1024x1792
> > > 带宽大的机器可以用dall-e-3，小水管2就行，不然下图片下的慢，回复你也慢。
> > 
> > 
> > 原来如此，我尝试在config文件添加了size参数1024，原来是没有生效，还得进入py文件改 __
> 
> 更正一下，aiproxy这个接口好像只有dall-e-3.。。。。。。。。。。。

感谢答疑，目前已完美对接这个功能！
