### ISSUE TITLE
apikey 送的额度撑不了多久，建议使用账号密码

### ISSUE THREAD

**Issue by yangchuansheng** [zhayujie/chatgpt-on-wechat#148]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

建议使用这个项目：https://github.com/bytemate/chatapi

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
账号密码是说通过chatgpt网页版接口的方案吗， 那种响应速度慢，不太稳定，而且依赖浏览器

**Comment by yangchuansheng** [comment]
> 

你看下项目就知道了，支持账号池，账号池可以解决响应慢的问题，而且免费

**Comment by bboychencan** [comment]
404了
