### ISSUE TITLE
docker版中怎样清除log日志内容，时间长了日志太大。

### ISSUE THREAD

**Issue by binfred** [zhayujie/chatgpt-on-wechat#1483]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

通过正常手段没有找到/var/lib/docker下的日志文件，请问日志文件存放在什么地方，或着用什么方式清除日志内容。感谢

**Comment by zhayujie** [comment]
你看下日志是不是在
/var/lib/docker/containers

**Comment by huangzhitian** [comment]
docker-compose logs -f --tail=100 
加载最近100行日志
