### ISSUE TITLE
添加脱离微信的渠道

### ISSUE THREAD

**Issue by zouzhenglu** [zhayujie/chatgpt-on-wechat#149]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
现在运行的时候都需要使用到微信，可不可以加一个渠道，开发调试测试chatGPT的时候就可以不用微信了。

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
其他应用的接入在这个项目中进行：
https://github.com/zhayujie/bot-on-anything
