### ISSUE TITLE
无法多用户的根据你是聊天记录聊天，没记忆

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#1490]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

设置好json
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/146583103/04b7472b-6883-4469-bbf0-8bbe068a8232)

只能记住第一聊天用户的名字，第二个用户的就没记忆了。
`Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as TAOZHIYUAI
[INFO][2023-10-30 04:18:50][wechat_channel.py:126] - Wechat login success, user_id: @e017f6aea3e51fa31f426af3d9ab905cca62689db783b873a629e4c330937cdb, nickname: TAOZHIYUAI
Start auto replying.
[INFO][2023-10-30 04:19:02][bridge.py:39] - create bot chatGPT for chat
[INFO][2023-10-30 04:19:02][chat_gpt_bot.py:49] - [CHATGPT] query=my name is mary
[INFO][2023-10-30 04:19:05][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]Hello Mary! How can I assist you today?), receiver=@5f118a47fac484c7997a65ff08f2147b
[INFO][2023-10-30 04:19:50][chat_gpt_bot.py:49] - [CHATGPT] query=i like tomato
[INFO][2023-10-30 04:20:01][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]That's great to hear, Mary! Tomatoes are delicious and versatile. They can be used in various dishes like salads, sandwiches, sauces, and more. Is there anything specific you would like to know or discuss about tomatoes?), receiver=@5f118a47fac484c7997a65ff08f2147b
[INFO][2023-10-30 04:20:03][chat_gpt_bot.py:49] - [CHATGPT] query=what is my name?
[INFO][2023-10-30 04:20:06][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]Your name is Mary, as you mentioned earlier. Is there anything else I can help you with, Mary?), receiver=@5f118a47fac484c7997a65ff08f2147b
[INFO][2023-10-30 04:20:38][chat_gpt_bot.py:49] - [CHATGPT] query=我是唐知足
[INFO][2023-10-30 04:20:41][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]你好，唐知足！有什么我可以帮助你的吗？), receiver=@17492a73956ab83b02fd747175c0d247c14ed20bf66be9c900e0865d65393163
[INFO][2023-10-30 04:20:45][chat_gpt_bot.py:49] - [CHATGPT] query=我不喜欢西红柿
[INFO][2023-10-30 04:20:56][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]那没关系，每个人都有自己的口味和喜好。如果你不喜欢西红柿，你可以尝试其他种类的食物，找到适合你的味道和偏好。还有很多其他的蔬菜和水果可以选择，你可以探索不同的食材来满足你的口味。如果你有任何其他的问题或需要其他建议，请随时告诉我！), receiver=@17492a73956ab83b02fd747175c0d247c14ed20bf66be9c900e0865d65393163
[INFO][2023-10-30 04:20:58][chat_gpt_bot.py:49] - [CHATGPT] query=我是谁？
[INFO][2023-10-30 04:21:11][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]很抱歉，作为一个语言模型，我无法知道你是谁。我只能回答问题和提供信息。如果你有其他需要帮助的问题，请随时告诉我！), receiver=@17492a73956ab83b02fd747175c0d247c14ed20bf66be9c900e0865d65393163
[INFO][2023-10-30 04:21:26][chat_gpt_bot.py:49] - [CHATGPT] query=我是谁？
[INFO][2023-10-30 04:21:30][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]您是以用户名"mary"进行与我对话的用户。请问有什么我可以帮助您的吗？), receiver=@5f118a47fac484c7997a65ff08f2147b
[INFO][2023-10-30 04:21:42][chat_gpt_bot.py:49] - [CHATGPT] query=我是谁
[INFO][2023-10-30 04:21:49][wechat_channel.py:188] - [WX] sendMsg=Reply(type=TEXT, content=[bot]作为一个语言模型，我无法知道你是谁。我无法获得你的个人身份信息或历史记录。请记住，与我进行的对话是匿名的。如果你有其他需要帮助的问题，请随时告诉我！), receiver=@17492a73956ab83b02fd747175c0d247c14ed20bf66be9c900e0865d65393163
`

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
多用户默认是记忆隔离的， 你是想再一个群里多人共享一个记忆？

在config.json 添加

"group_chat_in_one_session": ["群名称"]

**Comment by taozhiyuai** [comment]
> 多用户默认是记忆隔离的， 你是想再一个群里多人共享一个记忆？
> 
> 在config.json 添加
> 
> "group_chat_in_one_session": ["群名称"]

我是2个私聊。第一个私聊首先告诉AI名字，再问我名字是什么，回答正确。第二个私聊告诉AI自己名字，再问名字是什么，就回答错误了。

**Comment by taozhiyuai** [comment]
@zhayujie 你看这张图片，我标注清楚了。还是改写成langchain的吧。也方便多种memory.截取token的方式不好。

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/146583103/ca0e5a92-c9ed-4122-b59c-5d38be544a9e)

**Comment by taozhiyuai** [comment]
> 多用户默认是记忆隔离的， 你是想再一个群里多人共享一个记忆？
> 
> 在config.json 添加
> 
> "group_chat_in_one_session": ["群名称"]

aotogent都有替代langchain的功能，干脆用微软的aotogen重写长记忆这个功能，顺便增加agent
