### ISSUE TITLE
改写程序，支持langchain进行历史对话吧。

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#1492]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

改写程序，支持langchain进行历史对话吧。把数据存入矢量数据库

**Comment by qjsir** [comment]
那么请问程序改了吗

**Comment by taozhiyuai** [comment]
> 那么请问程序改了吗

NO
