### ISSUE TITLE
尽快支持oneapi哦。目前只能用openai和azure，讯飞是个半吊子。

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#1493]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

尽快支持oneapi哦。目前只能用openai和azure，讯飞是个半吊子。

**Comment by yinjianjie** [comment]
请问试成功了吗，结合oneapi

**Comment by skstudying** [comment]
请问现在能用oneapi了吗？

**Comment by marshzhao** [comment]
请问azure如何部署

**Comment by Game-zy** [comment]
请问azure如何部署  docker-compose.yml 配置文件能共享下么
