### ISSUE TITLE
讯飞大模型官方更新到3.0了

### ISSUE THREAD

**Issue by john-jh24** [zhayujie/chatgpt-on-wechat#1495]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

星火认知大模型V3.0能力全面升级，最新的docker代码会更新么

**Comment by leopardsamurai** [comment]
直接修改代码，替换bot/xunfei/的py程序，换成v3版本

**Comment by john-jh24** [comment]
> 直接修改代码，替换bot/xunfei/的py程序，换成v3版本

用docker部署的启动docker-compose up -d会重新拉hub代码的吧，本地代码就覆盖了
