### ISSUE TITLE
如何设置总是自动回复，不要前缀

### ISSUE THREAD

**Issue by SatoshiRui** [zhayujie/chatgpt-on-wechat#15]
如何设置成私聊时不要前缀，只要艾特自己就都能自动回复。所有群聊都自动回复

**Comment by SatoshiRui** [comment]
请问如何设置成私聊时不要前缀, 我想设置为总是自动回复. 群聊时, 只要艾特我就都能自动回复, 希望所有群聊都自动回复. 这一点其实wechat-chatgpt已经做到了. 但是wechat-chatgpt登录方式仍然是邮箱+密码, 现在有了人机验证, 登录比较麻烦, 而且没有API key稳定.

**Comment by zhayujie** [comment]
> 请问如何设置成私聊时不要前缀, 我想设置为总是自动回复. 群聊时, 只要艾特我就都能自动回复, 希望所有群聊都自动回复. 这一点其实wechat-chatgpt已经做到了. 但是wechat-chatgpt登录方式仍然是邮箱+密码, 现在有了人机验证, 登录比较麻烦, 而且没有API key稳定.

1.私聊不用前缀触发，只要在config.json中的single_chat_prefix配置项里加一个空字符串就行了:

```
"single_chat_prefix": [""]
```

2.群聊现要被艾特就会自动回复，但是需要在白名单配置 group_name_white_list 中，这个是保证自动回复的可控。 稍后可以加一个全局的开关，打开后任意群的会生效.

**Comment by zhayujie** [comment]
1.配置 "single_chat_prefix": [""] 可实现私聊无需前缀触发
2.配置  "group_name_white_list": "ALL_GROUP" 可对所有群聊开启自动回复
