### ISSUE TITLE
怎么支持每天自动发布消息

### ISSUE THREAD

**Issue by sujianwei1** [zhayujie/chatgpt-on-wechat#1508]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我想每天在群里发布每日AI消息，有接口模板可以使用吗

**Comment by single228758** [comment]
https://github.com/haikerapples/timetask

**Comment by sujianwei1** [comment]
good
