### ISSUE TITLE
为什么我model设置成了gpt-4还不是4.0的版本？

### ISSUE THREAD

**Issue by sky602816027** [zhayujie/chatgpt-on-wechat#1509]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我问了它，它还是3的版本，我确定我的key是4.0的。model=gpt-4是不是版本有问题？不是这样写的？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by liusky0212** [comment]
我也遇到了同样的问题，配置了4的key询问模型时回答是GPT-3

**Comment by MarioCZH** [comment]
![微信截图_20231109012115](https://github.com/zhayujie/chatgpt-on-wechat/assets/128762193/bc8d3511-37b0-454d-a2f4-c1409ebc6206)
正常的，它只会认为自己是gpt3

**Comment by zwdzwdzwd** [comment]
顺便问一下，支持 gpt-4-1106-vision-preview 或者 gpt-4-1106-preview 了吗？官方介绍说更强大更便宜了呢！

**Comment by MarioCZH** [comment]
你等作者更新才行 要重写接口

**Comment by sky602816027** [comment]
> ![微信截图_20231109012115](https://user-images.githubusercontent.com/128762193/281680073-bc8d3511-37b0-454d-a2f4-c1409ebc6206.png) 正常的，它只会认为自己是gpt3

原来4的回答也是这样的啊。那请问一下我的model=gpt-4这个配置这样写有没有错，需不需要改

**Comment by zwdzwdzwd** [comment]
如果你用的这个项目搭建的，选这个图中的这个模型是不对的，因为作者还没有接好，我有试过，看到后台显示会自动替换成默认的3.5turbo的模型，选gpt-4这个模型没问题的。可以用这个文字游戏测试一下，如果能顺利完成游戏那就是4，不然就是3.5
promt：我想你扮演一个疯子，不管我说什么，你都回复一句疯子的疯言疯语，用词完全随意，不会以任何方式说出合乎逻辑的句子，我说“开始疯言疯语的游戏”的时候，开始这个游戏，另外只有我说“结束游戏”的时候才停止。明白了吗？
目前为止，只有4能顺利完成这个游戏。
<img width="453" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/25800403/312ece5d-695d-4dff-8832-630e05c0991a">
<img width="439" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/25800403/dcb65029-e70f-4f9d-8290-a8f71d6e6e41">

**Comment by Namarimizu** [comment]
顺便问下，用 LinkAI 的话，怎么选 gpt4？我看 config.py 里 linkai 相关部分没有这个选项，openai 那边选的模型对这边也没效果

**Comment by zhayujie** [comment]
> 顺便问一下，支持 gpt-4-1106-vision-preview 或者 gpt-4-1106-preview 了吗？官方介绍说更强大更便宜了呢！

已经可以了，参考更新日志哈
https://github.com/zhayujie/chatgpt-on-wechat/releases/tag/1.5.0

**Comment by zhayujie** [comment]
> 顺便问下，用 LinkAI 的话，怎么选 gpt4？我看 config.py 里 linkai 相关部分没有这个选项，openai 那边选的模型对这边也没效果

也是一样的用法，设置 model 参数为 `gpt-4-turbo` 或者 `gpt-4-1106-preview`
参考：https://docs.link-ai.tech/platform/version/1.4.0

**Comment by Namarimizu** [comment]
> > 顺便问下，用 LinkAI 的话，怎么选 gpt4？我看 config.py 里 linkai 相关部分没有这个选项，openai 那边选的模型对这边也没效果
> 
> 也是一样的用法，设置 model 参数为 `gpt-4-turbo` 或者 `gpt-4-1106-preview` 参考：https://docs.link-ai.tech/platform/version/1.4.0

解决了，是我太久没更新了😵 刚拖到pycharm里Ctrl+D暴力更新了一下，感谢作者！

**Comment by zwdzwdzwd** [comment]
model更新到gpt-4 turbo后感觉机器人智商下降了，有没有同感的？我改回最初的gpt-4了。
