### ISSUE TITLE
讯飞星火3.0接入失败

### ISSUE THREAD

**Issue by mxf-bug** [zhayujie/chatgpt-on-wechat#1510]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

正常测试询问

### 问题描述 😯

给订阅号发送消息，只能回复[bot]和【正在思考中，回复任意文字尝试获取回复】，
无法连上讯飞星火3.0。
**如果我没理解错误的话**，报错显示11200 官方解释11200授权错误：该appId没有相关功能的授权 或者 业务量超过限制
但是我的api没有问题，刚刚开通的。但今日使用token数就是为0

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/78996304/ceed04e2-33c8-4227-bfc6-845dedb65e8b)

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/78996304/66d03b92-7fe9-449f-98fa-0be1bf55477d)

### 终端日志 📒

[INFO][2023-11-08 17:53:43][passive_reply.py:97] - [wechatmp] Request 1 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330091627574234 127.0.0.1:56106
1
[INFO][2023-11-08 17:53:43][passive_reply.py:153] - [wechatmp] Request 1 do send to oiA9_5ypeUOGUcvXnwXAueysHM9U 24330091627574234: 1
[bot]
[INFO][2023-11-08 17:53:45][passive_reply.py:97] - [wechatmp] Request 1 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330091413888720 127.0.0.1:56108
你好
[INFO][2023-11-08 17:53:45][xunfei_spark_bot.py:54] - [XunFei] query=你好
[INFO][2023-11-08 17:53:45][xunfei_spark_bot.py:96] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}]
[INFO][2023-11-08 17:53:45][xunfei_spark_bot.py:192] - [XunFei] Start websocket, session_id=oiA9_5ypeUOGUcvXnwXAueysHM9U_169943722568
**[ERROR][2023-11-08 17:53:45][xunfei_spark_bot.py:207] - 请求错误: 11200, {'header': {'code': 11200, 'message': 'AppIdNoAuthError:(17:53:45.769) tokens.total', 'sid': 'cht000b96dd@dx18bae5a2729b81c540', 'status': 2}}**
[INFO][2023-11-08 17:53:50][passive_reply.py:97] - [wechatmp] Request 2 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330091413888720 127.0.0.1:56112
你好
[INFO][2023-11-08 17:53:55][passive_reply.py:97] - [wechatmp] Request 3 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330091413888720 127.0.0.1:56114
你好
[INFO][2023-11-08 17:54:09][passive_reply.py:97] - [wechatmp] Request 1 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330088215497245 127.0.0.1:56118
国寿福心动的人
[INFO][2023-11-08 17:54:14][passive_reply.py:97] - [wechatmp] Request 2 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330088215497245 127.0.0.1:56120
国寿福心动的人
**[INFO][2023-11-08 17:54:15][xunfei_spark_bot.py:86] - [XunFei-API] response=, time=30.14573836326599s, usage={}**
[INFO][2023-11-08 17:54:15][wechatmp_channel.py:85] - [wechatmp] text cached, receiver oiA9_5ypeUOGUcvXnwXAueysHM9U
[bot]
[INFO][2023-11-08 17:54:15][passive_reply.py:153] - [wechatmp] Request 2 do send to oiA9_5ypeUOGUcvXnwXAueysHM9U 24330088215497245: 国寿福心动的人
[bot]
[INFO][2023-11-09 08:51:40][passive_reply.py:97] - [wechatmp] Request 1 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330862208791904 127.0.0.1:59030
随便
[INFO][2023-11-09 08:51:40][xunfei_spark_bot.py:54] - [XunFei] query=随便
[INFO][2023-11-09 08:51:40][xunfei_spark_bot.py:96] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '随便'}]
[INFO][2023-11-09 08:51:40][xunfei_spark_bot.py:192] - [XunFei] Start websocket, session_id=oiA9_5ypeUOGUcvXnwXAueysHM9U_169949110087
**[ERROR][2023-11-09 08:51:40][xunfei_spark_bot.py:207] - 请求错误: 11200, {'header': {'code': 11200, 'message': 'AppIdNoAuthError:(08:51:40.720) tokens.total', 'sid': 'cht000bfdc5@dx18bb190382fb81c540', 'status': 2}}**
[INFO][2023-11-09 08:51:45][passive_reply.py:97] - [wechatmp] Request 2 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330862208791904 127.0.0.1:59034
随便
[INFO][2023-11-09 08:51:50][passive_reply.py:97] - [wechatmp] Request 3 from oiA9_5ypeUOGUcvXnwXAueysHM9U 24330862208791904 127.0.0.1:59036
随便

**Comment by mxf-bug** [comment]
已经知道是什么问题了，讯飞文件忘记改成v3版本了

**Comment by wt616** [comment]
> 已经知道是什么问题了，讯飞文件忘记改成v3版本了
遇到和您一样的问题了，
请问在哪改成v3，什么字段要改成什么值？

**Comment by chenfrigate** [comment]
> > 已经知道是什么问题了，讯飞文件忘记改成v3版本了
> > 遇到和您一样的问题了，
> > 请问在哪改成v3，什么字段要改成什么值？

1、config文件，看1.3.6的更新日志
2、bot/xunfei/xunfei_spark_bot.py 第40多行，修改self.domain和self.spark_url，和讯飞的官方文档对上即可。@wt616
