### ISSUE TITLE
回复的数据被截取，少了一段

### ISSUE THREAD

**Issue by wh-stone** [zhayujie/chatgpt-on-wechat#152]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

chatgpt 回复的数据信息被截取，例如提问 用Python帮我写一个俄罗斯方块的代码
返回的信息是
import pygame
import rando
然后就没了

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

![image](https://user-images.githubusercontent.com/29125044/218004972-2e8f8be2-caa6-48e6-b6b7-2bb167a6c5e4.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - ubuntu 20.04
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
Python 3.8.10

**Comment by wh-stone** [comment]
看了 bot/openai/open_ai_bot.py 是字段截取的问题引起，
res_content = response.choices[0]["text"].strip().rstrip("<|im_end|>")
去掉即可

**Comment by hy233** [comment]
res_content = response.choices[0]["text"].strip().rstrip("<|im_end|>")
整个这个去掉？我不懂……

**Comment by zhayujie** [comment]
由于openai接口中的stop参数为 '#'，导致回复内容出现'#'即被阶段，修改为 '\n\n\n'后解决

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/26161723/218265644-3adfec82-a78b-4270-8a47-522fbe1d1560.png">

**Comment by hy233** [comment]
> 由于openai接口中的stop参数为'#'，导致返回内容出现'#'即被阶段，修改为'\n\n\n'后解决
> 
> <img alt="图像" width="1027" src="https://user-images.githubusercontent.com/26161723/218265644-3adfec82-a78b-4270-8a47-522fbe1d1560.png">

多谢
