### ISSUE TITLE
新增用One-API做中转站，fakeApiTool做OpenAI账号密码管理网站，自动填充API，免费白嫖ChatGPT3.5所有模型，速度飞快，支持高并发，多账号轮询

### ISSUE THREAD

**Issue by Yanyutin753** [zhayujie/chatgpt-on-wechat#1522]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

自己写了一个基于One-API的工具网站，可以通过opneAI账号密码自动在One-API添加渠道，同时能够自动修改更新删除，再通过微信机器人调取One-API的令牌，实现多账号轮询，支持高并发，速度极快，有兴趣的小伙伴可以看我项目，一起来完善项目！
本项目使用的OpenAI服务，均是免费服务，无需5刀，或者其他，废号都可以，所以对于余额不足的小伙伴想给同学体验飞速的chatGPT还是很不错的选择，请给我点个star⭐

本项目地址：https://github.com/Yanyutin753/fakeApiTool-One-API

### 举例

本项目地址：https://github.com/Yanyutin753/fakeApiTool-One-API

### 动机

对于余额不足的小伙伴想给同学体验飞速的chatGPT还是很不错的选择

**Comment by seven2202** [comment]
其实目前可以用one-api的，把base_url_api改成你的中转地址即可。

**Comment by ladypiapia** [comment]
> 其实目前可以用one-api的，把base_url_api改成你的中转地址即可。

咨询下大佬，我现在就是想用one-api来添加多个openai key实现轮询和负载均衡，但遇到了一点问题，请问是哪里不对头吗？
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/36269124/2091b497-1fb2-46f6-a0cf-40e888669a2f)
这是我在one-api提的issue：**https://github.com/songquanpeng/one-api/issues/734**
