### ISSUE TITLE
回复版本、日期不正确？

### ISSUE THREAD

**Issue by wangjunrong09** [zhayujie/chatgpt-on-wechat#153]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

询问版本回复的是chatgpt V1.0
询问日期回复的是21年，
请问这个可以修改吗？现在应该是3.0版本的呀？

> 简要说明、截图、复现步骤等，也可以是需求或想法

![2cd8535b5a9552c31d873dc8e4dd140](https://user-images.githubusercontent.com/55369939/218009273-8570a566-103b-4cbd-800f-3801ceaca167.jpg)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by realzsy** [comment]
都是这样的，版本和日期回答各种各样

**Comment by zhayujie** [comment]
在 character参数里面指定下
