### ISSUE TITLE
我也是遇到这个问题，上述解决方案都试过还是不行，有没有大佬救救

### ISSUE THREAD

**Issue by shaxao** [zhayujie/chatgpt-on-wechat#1530]
我也是遇到这个问题，上述解决方案都试过还是不行

_Originally posted by @shaxao in https://github.com/zhayujie/chatgpt-on-wechat/issues/93#issuecomment-1815932139_
            系统centos7.9
           国内阿里云服务器
            ImportError: Can't connect to HTTPS URL because the SSL module is not available.

You can't get access to internet or wechat domain, so exit.
python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
python: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

**Comment by zhayujie** [comment]
发一下部署的系统版本、网络环境、报错日志上下文哈
