### ISSUE TITLE
如何使用aiproxy的这个第三方api接口

### ISSUE THREAD

**Issue by jayling1111** [zhayujie/chatgpt-on-wechat#1533]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

openai部署完正常使用，现打算使用aiproxy的第三方key尝试gpt4.0的模型，使用docker-compose的方式部署，启动后返回日志api无效，还是走了openai官方接口，我想改成第三方的访问域名，请问改如何在docker compose yaml添加第三方的域名？

### 问题描述 😯

wechat-plus-111      | Start auto replying.
wechat-plus-111      | [INFO][2023-11-18 08:31:04][chat_gpt_bot.py:33] - [OPEN_AI] query=???
wechat-plus-111      | [ERROR][2023-11-18 08:31:04][chat_gpt_bot.py:106] - Incorrect API key provided: sk-Ok3vu***************************************vjHj. You can find your API key at https://platform.openai.com/account/api-keys.
wechat-plus-111      | Traceback (most recent call last):
wechat-plus-111      |   File "/app/bot/chatgpt/chat_gpt_bot.py", line 80, in reply_text
wechat-plus-111      |     presence_penalty=conf().get('presence_penalty', 0.0),  # [-2,2]???????????????????
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_resources/chat_completion.py", line 25, in create
wechat-plus-111      |     return super().create(*args, **kwargs)
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create
wechat-plus-111      |     request_timeout=request_timeout,
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 226, in request
wechat-plus-111      |     resp, got_stream = self._interpret_response(result, stream)
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 623, in _interpret_response
wechat-plus-111      |     stream=False,
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
wechat-plus-111      |     rbody, rcode, resp.data, rheaders, stream_error=stream_error
wechat-plus-111      | openai.error.AuthenticationError: Incorrect API key provided: sk-Ok3vu***************************************vjHj. You can find your API key at https://platform.openai.com/account/api-keys.
wechat-plus-111      | [INFO][2023-11-18 08:31:04][wechat_channel.py:146] - [WX] sendMsg=???????, receiver=@3edfcc2a946ed87ff54aa9db62544713
^CGracefully stopping... (press Ctrl+C again to force)

### 终端日志 📒

wechat-plus-111      | Start auto replying.
wechat-plus-111      | [INFO][2023-11-18 08:31:04][chat_gpt_bot.py:33] - [OPEN_AI] query=???
wechat-plus-111      | [ERROR][2023-11-18 08:31:04][chat_gpt_bot.py:106] - Incorrect API key provided: sk-Ok3vu***************************************vjHj. You can find your API key at https://platform.openai.com/account/api-keys.
wechat-plus-111      | Traceback (most recent call last):
wechat-plus-111      |   File "/app/bot/chatgpt/chat_gpt_bot.py", line 80, in reply_text
wechat-plus-111      |     presence_penalty=conf().get('presence_penalty', 0.0),  # [-2,2]???????????????????
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_resources/chat_completion.py", line 25, in create
wechat-plus-111      |     return super().create(*args, **kwargs)
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create
wechat-plus-111      |     request_timeout=request_timeout,
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 226, in request
wechat-plus-111      |     resp, got_stream = self._interpret_response(result, stream)
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 623, in _interpret_response
wechat-plus-111      |     stream=False,
wechat-plus-111      |   File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
wechat-plus-111      |     rbody, rcode, resp.data, rheaders, stream_error=stream_error
wechat-plus-111      | openai.error.AuthenticationError: Incorrect API key provided: sk-Ok3vu***************************************vjHj. You can find your API key at https://platform.openai.com/account/api-keys.
wechat-plus-111      | [INFO][2023-11-18 08:31:04][wechat_channel.py:146] - [WX] sendMsg=???????, receiver=@3edfcc2a946ed87ff54aa9db62544713
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by jayling1111** [comment]
已解决

**Comment by twfxr** [comment]
请问一下是怎么解决的？

**Comment by jayling1111** [comment]
> 请问一下是怎么解决的？

https://github.com/zhayujie/chatgpt-on-wechat/issues/1477

看这里
