### ISSUE TITLE
调用第三方api后无法画图，报分辨率错误

### ISSUE THREAD

**Issue by jayling1111** [zhayujie/chatgpt-on-wechat#1536]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    volumes:
      - /root/gpt/config.json:/app/plugins/config.json    
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: '123123123'
      OPEN_AI_API_BASE: 'https://apivip.aiproxy.io/v1'      
      MODEL: 'gpt-3.5-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["", ""]'
      SINGLE_CHAT_REPLY_PREFIX: '" "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      IMAGE_CREATE_SIZE: '1024x1024'-------------------------（按logs提示，在docker compose中添加了该参数）
      CONVERSATION_MAX_TOKENS: 5000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型,同时你是一个非常可爱的小女孩，非常热心，你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''

### 问题描述 😯

使用官方api的话出图正常，更换第三方接口api后，画图功能报错，提示我要修改分辨率，在环境变量添加"image_create_size": "1024x1024",参数为1024x1024后依然报相同错误。

### 终端日志 📒

```log
<此处粘贴终端日志>
```
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/84979549/021f80a7-4fdf-4807-a28a-857f032728d1)

**Comment by mela93** [comment]
确认一下第三方API接口是否支持画图

**Comment by jayling1111** [comment]
用的aiproxy 付费支持全模型

**Comment by mela93** [comment]
试试加个配置
```
TEXT_TO_IMAGE: 'dall-e-2'
```

**Comment by rkongzy** [comment]
麻烦问下怎么解决的，遇到相同问题了

**Comment by jayling1111** [comment]
> 麻烦问下怎么解决的，遇到相同问题了

我是docker部署的，映射改文件，在该文件改好分辨率参数bot/openai/open_ai_image.py

**Comment by rkongzy** [comment]
感谢，问题已解决

**Comment by wgsxsm** [comment]
> > 麻烦问下怎么解决的，遇到相同问题了
> 
> 我是docker部署的，映射改文件，在该文件改好分辨率参数bot/openai/open_ai_image.py

你好，大佬！请教下，docker部署之后，文件存在什么路径下面？
