### ISSUE TITLE
请教大佬！对项目修改调试和开发插件调试功能的时候，每次都需要重新扫码登录测试吗？有没有其他方法呢？

### ISSUE THREAD

**Issue by ladypiapia** [zhayujie/chatgpt-on-wechat#1549]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

单纯请教各位大佬，自己在尝试写一个插件，在调试过程中，每改一次代码都要重新扫码登录微信测试，得登录好几十次，有什么其他办法吗？还是说只能这么改一次代码就得重新登录一次

**Comment by zhayujie** [comment]
config.json 中设置 hot_reload: true

**Comment by ladypiapia** [comment]
> config.json 中设置 hot_reload: true

开启hot_reload之后，是指restart容器时不需要再扫码直接就登陆了还是说 修改的代码实时生效了哇？

**Comment by single228758** [comment]
> > config.json 中设置 hot_reload: true
> 
> 开启hot_reload之后，是指restart容器时不需要再扫码直接就登陆了还是说 修改的代码实时生效了哇？

是退出登录不用再扫码，插件我之前试用#reloadp 插件名: 重载指定插件配置
但好像没有用，可以试下备份插件，然后通过指令卸载插件，再把备份的插件放到文件中，扫描插件加载看行不行

**Comment by single228758** [comment]
> > config.json 中设置 hot_reload: true
> 
> 开启hot_reload之后，是指restart容器时不需要再扫码直接就登陆了还是说 修改的代码实时生效了哇？

是退出登录不用再扫码，插件我之前试用#reloadp 插件名: 重载指定插件配置
但好像没有用，可以试下备份插件，然后通过指令卸载插件，再把备份的插件放到文件中，扫描插件加载看行不行

**Comment by ladypiapia** [comment]
感谢，这就去试试

**Comment by BUJIDAOVS** [comment]
> > config.json 中设置 hot_reload: true
> 
> docker 容器的话不行哈，每次都要 compose down 才能生效

docker应该怎么保留登陆状态呢，每次down或restart都要重新登录也太麻烦了

**Comment by xionghaizhi** [comment]
> > > config.json 中设置 hot_reload: true
> > 
> > 
> > docker 容器的话不行哈，每次都要 compose down 才能生效
> 
> docker应该怎么保留登陆状态呢，每次down或restart都要重新登录也太麻烦了

大佬 解决了吗？
