### ISSUE TITLE
  openai_voice.py 中有一行变量没有自动更改

### ISSUE THREAD

**Issue by kflyfly** [zhayujie/chatgpt-on-wechat#1552]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

如果使用第三方中转平台，由于会默认调用
url = 'https://api.openai.com/v1/audio/speech'
但第三方平台可能无法连接openai,会导致无法联网的问题

希望更新此变量，可以自动替换主目录下面的链接变量

### 终端日志 📒

```log
[openai_voice.py:54] - HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/audio/speech (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb3b44b8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

**Comment by zhayujie** [comment]
已解决
