### ISSUE TITLE
chatgpt4 turbo无法使用问题

### ISSUE THREAD

**Issue by KevinMahone** [zhayujie/chatgpt-on-wechat#1554]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

配置如下：
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/42559137/5c417c6b-9bd7-48ed-88ef-ef01f408ad1c)
微信访问：
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/42559137/4629cba2-0f76-4840-a423-92690039bfad)

### 问题描述 😯

请问一下我使用的是GPT4的key为什么接入到微信后回复仍然是gpt3.5呢

### 终端日志 📒

终端日志正常

**Comment by LeoAKALiu** [comment]
```
[INFO][2024-04-28 20:23:49][chat_gpt_bot.py:49] - [CHATGPT] query=你是哪个模型
[WARNING][2024-04-28 20:23:50][chat_gpt_session.py:85] - num_tokens_from_messages() is not implemented for model gpt-4-turbo. Returning num tokens assuming gpt-3.5-turbo.
[WARNING][2024-04-28 20:23:52][chat_gpt_session.py:85] - num_tokens_from_messages() is not implemented for model gpt-4-turbo. Returning num tokens assuming gpt-3.5-turbo.
[INFO][2024-04-28 20:23:54][wechatcomapp_channel.py:63] - [wechatcom] Do send text to LiuBo: 我是ChatGPT，由OpenAI开发的一个基于GPT-3技术的语言模型。我被设计用来理解和生成自然语言，可以帮助回答问题、提供信息、进行对话、创作文本等。如果你有任何问题或需要帮助，随时可以问我！
```

后台log现实gpt-4-turbo没有调用成功，还是gpt-3.5回复的，请问num_tokens_from_messages()在哪设置

**Comment by barney2022** [comment]
我也是这样

[WARNING][2024-05-01 16:19:39][chat_gpt_session.py:85] - num_tokens_from_messages() is not implemented for model gpt-4-turbo. Returning num tokens assuming gpt-3.5-turbo.
