### ISSUE TITLE
说不上是bug，但是算是一个关于text2voice的改进点

### ISSUE THREAD

**Issue by helperAI** [zhayujie/chatgpt-on-wechat#1555]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] #1552类似

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

如果在config.json文件中配置了"open_ai_api_base"为中转的api服务器。
但是在plugin/voice/open_voice.py文件中的如下代码：
def textToVoice(self, text):
        try:
            url = 'https://api.openai.com/v1/audio/speech'

发现url是写死的。
建议修改为直接从配置文件中的读取：url = conf().get("open_ai_api_base") + '/audio/speech'
否则会报错

### 问题描述 😯

同上

### 终端日志 📒

```log
[openai_voice.py:54] - HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/audio/speech (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e89afbb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

**Comment by ladypiapia** [comment]
请问下大佬文字转语音现在是可以用了吗？之前开启后提示报错，是用的3.5的api
https://github.com/zhayujie/chatgpt-on-wechat/issues/1515

**Comment by helperAI** [comment]
> 请问下大佬文字转语音现在是可以用了吗？之前开启后提示报错，是用的3.5的api #1515

可以正常使用的。你是中转的api的话，记得需要修改一下plugin/voice/open_voice.py代码里面的服务器url，如果是直接调用官方api的，可以直接使用的吧。我没有试过，我想是可以的。

**Comment by hhtower** [comment]
修改了url， 在windows打包docker后，一直报  exec /entrypoint.sh: no such file or directory，麻了麻了
建议优化修复一下这个bug。

**Comment by zhayujie** [comment]
这个我跟进下

**Comment by zhayujie** [comment]
已解决
