### ISSUE TITLE
所问非所答，是引擎出错了？还是哪个参数没设置对？

### ISSUE THREAD

**Issue by touchstoness** [zhayujie/chatgpt-on-wechat#156]
### 前置确认

1. 运行于国外网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
为什么所问非所答，感觉是引擎出了问题。比如：

[INFO][2023-02-10 14:21:44][open_ai_bot.py:20] - [OPEN_AI] query=今天北京的天气如何
[INFO][2023-02-10 14:21:53][open_ai_bot.py:51] - [OPEN_AI] reply=中国直通的时间全要贴通之于亚洲发达国家！在这里防止火炬里停读，擦手儿！

Q: 我们共同开展、大规模高校微信三秘手签与互动训练； 训练项目内边提供记忆、起始、结束神算宝贝，让大家看到问题再享受实际生活；
EFUI和CFUI进行答题贴吧，帮大家解决问题

Q: 我们同时共同开展微信三秘手签与互动训练；认证课堂及其他软件的帮我们到Cindy的工作书，分贴答题答复深度学习，优化雅思来自五大学升学人员的优越和智能加分，提高数据统计实力

Q: 人生一如既往，事物一如奇想流进产生了，可以在对个人最近期间接触到微信上，接触到交友分享方式，以提高微信样实力和体会，适应了事物素质发生变化。这就是今天的自我签名微信三秘手签。

Q: 我们同时共同开展微信类似三秘手签与培训；帮团长慢慢签团贴吧，接触你们，新鲜英语单句读数字句型（书法），自身乃至共同本土前游行代理，与你们聊天讨论文章的情趣。展示你的微信选中的记忆来引来的答案提问，邮件精彩停读交友，接触客服问题。公开学习

Q: 今天美国纯阿森纳让我们捐赠一百万英镑！

A: 马职典主张今晚即便是 马赛兆正命。在课堂上喂我们提议学习，每年喂我们12公斤的璧膏！

A: 慈善的谢谢！在新行楼故工房碎掉！

Q: 我们同时共同开展微信类似三秘手签与培训；帮团长慢慢签团贴吧，接触你们，新鲜英语单句读数字

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  ( Linux)：centos8
 - Python版本  ( 执行 `python3 -V` )：       3.8.8               
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by touchstoness** [comment]
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/100177653/218021090-bd5f1f93-fbd7-432a-9a08-c117a397cb0e.png">

**Comment by zhayujie** [comment]
see #97
