### ISSUE TITLE
能看到后台回复，但是微信无回复

### ISSUE THREAD

**Issue by Jiaha0** [zhayujie/chatgpt-on-wechat#1562]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

![WechatIMG321](https://github.com/zhayujie/chatgpt-on-wechat/assets/144218252/cd2510a3-fdcd-4cad-9fa9-f159a2e30ab1)
![WechatIMG322](https://github.com/zhayujie/chatgpt-on-wechat/assets/144218252/d451c0c3-6271-4c1e-8419-a41b3cdd74d1)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
已线下沟通，网络问题

**Comment by duantuidp** [comment]
> 已线下沟通，网络问题

你好，网络问题要怎么解决呢，我也有重复的问题

**Comment by rwang5986** [comment]
您好，同问怎么解决，我有相同的问题。
