### ISSUE TITLE
企业微信个人号部署COW流程

### ISSUE THREAD

**Issue by sillyluna** [zhayujie/chatgpt-on-wechat#1566]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [x] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

other

### 复现步骤 🕹

按照以下流程操作，第一步安装ntwork出现库不存在安装失败的情况

1. 安装ntwork依赖：在Windows环境下打开命令行，执行以下命令安装ntwork依赖：
```
pip install ntwork
```

2. 安装指定PC企微专用版本：下载并安装[WeCom_4.0.8.6027版本](https://dldir1.qq.com/wework/work_weixin/WeCom_4.0.8.6027.exe)，扫码登录企业微信，并关闭自动更新企业微信。

3. 在config.json文件中添加配置：打开config.json文件，将以下配置添加到文件中：
```json
"channel_type": "wework",
"wework_smart": true
```

4. 运行app.py：在命令行中执行以下命令运行app.py：
```
python app.py

### 问题描述 😯

请问下使用企业个人微信部署COW对接外部人和外部群，这4个步骤是否是正确，我在Issue上其实有看到不少人在别的issue下提出ntwork安装依赖失败，但没有得到答案，希望能够解惑。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
这个依赖的源库好像已经被删除了

试试看加一个  -i https://pypi.tuna.tsinghua.edu.cn/simple 能成功下载嘛

**Comment by sillyluna** [comment]
> 这个依赖的源库好像已经被删除了
> 
> 试试看加一个 -i https://pypi.tuna.tsinghua.edu.cn/simple 能成功下载嘛

可以了，感谢

**Comment by kill136** [comment]
群主，加上-i https://pypi.tuna.tsinghua.edu.cn/simple   现在也安装失败了 怎么办

**Comment by kill136** [comment]
> 这个依赖的源库好像已经被删除了
> 
> 试试看加一个 -i https://pypi.tuna.tsinghua.edu.cn/simple 能成功下载嘛

老板，按照您的方法，用清华的源提示找不到怎么办

**Comment by sillyluna** [comment]
失败是什么提示呢？你复制一下错误

&nbsp;


和叶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月22日(星期五) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhayujie/chatgpt-on-wechat] 企业微信个人号部署COW流程 (Issue #1566)





 
群主，加上-i https://pypi.tuna.tsinghua.edu.cn/simple   现在也安装失败了 怎么办

**Comment by kill136** [comment]
我知道问题了，python 下面3.11安装失败，3.10 就能安装成功了

**Comment by zhangshenzhan7** [comment]
有离线包吗？3.10也找不到了，可以和itchat一样用离线方式加进去

**Comment by I-E-E-E** [comment]
> 有离线包吗？3.10也找不到了，可以和itchat一样用离线方式加进去

https://github.com/dev-kang/ntwork
