### ISSUE TITLE
README.md中开启群组聊天  配置描述有误

### ISSUE THREAD

**Issue by sunguanghui** [zhayujie/chatgpt-on-wechat#157]
### 问题描述

> 群组聊天中，群名称需配置在 group_name_white_list  中才能开启群聊自动回复。如果想对所有群聊生效，可以直接填写 "group_name_white_list": "ALL_GROUP"

以上配置，需要修改成"group_name_white_list": ["ALL_GROUP"]，才能生效，否则无法在所有群聊里自动回复。

**Comment by defamilo** [comment]
我昨天部署的配置的就是"group_name_white_list": "ALL_GROUP"
可以正常生效

**Comment by zhayujie** [comment]
> ### 问题描述
> > 群组聊天中，群名称需配置在 group_name_white_list  中才能开启群聊自动回复。如果想对所有群聊生效，可以直接填写 "group_name_white_list": "ALL_GROUP"
> 
> 以上配置，需要修改成"group_name_white_list": ["ALL_GROUP"]，才能生效，否则无法在所有群聊里自动回复。

你的python版本是多少

**Comment by defamilo** [comment]
我用的3.8.1版本的python

**Comment by sunguanghui** [comment]
> > ### 问题描述
> > > 群组聊天中，群名称需配置在 group_name_white_list  中才能开启群聊自动回复。如果想对所有群聊生效，可以直接填写 "group_name_white_list": "ALL_GROUP"
> > 
> > 
> > 以上配置，需要修改成"group_name_white_list": ["ALL_GROUP"]，才能生效，否则无法在所有群聊里自动回复。
> 
> 你的python版本是多少

3.10.6
