### ISSUE TITLE
新加坡主机，服务器接收消息响应[WX]get other_user_id failed: 'NickName'

### ISSUE THREAD

**Issue by mysmallwhale** [zhayujie/chatgpt-on-wechat#1571]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1.新加坡windows主机运行python项目
2.个人微信扫码生成的二维码，正常登录，并提示Start auto replying
3.微信每发一条信息（无论是否带bot），都会响应一条字符串[WARNING][2023-12-05 19:43:48][wechat_message.py:84] - [WX]get other_user_id failed: 'NickName'
4.我的config.json配置如下
{
  "channel_type": "wx",
  "model": "gpt-3.5-turbo",
  "open_ai_api_key":我在Open AI官网上注册的api key,
  "open_ai_api_base": "https://api.openai.com/v1",
  "text_to_image": "dall-e-2",
  "voice_to_text": "openai",
  "text_to_voice": "openai",
  "proxy": "http://127.0.0.1:7890",
  "hot_reload": false,
  "single_chat_prefix": [
    "bot",
    "@bot"
  ],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": [
    "@bot"
  ],
  "group_name_white_list": [
    "ChatGPT测试群",
    "ChatGPT测试群2"
  ],
  "group_chat_in_one_session": [
    "ChatGPT测试群"
  ],
  "image_create_prefix": [
    "画"
  ],
  "use_azure_chatgpt": false,
  "speech_recognition": true,
  "group_speech_recognition": false,
  "voice_reply_voice": false,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "character_desc": "chatGPT机器人",
  "temperature": 0.7,
  "top_p": 1,
  "subscribe_msg": "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,
  "linkai_api_key": "",
  "linkai_app_code": "",
  "linkai_api_base": "https://api.link-ai.chat"

### 问题描述 😯

微信每发一条信息（无论是否带bot），电脑的python运行窗口都会响应一条字符串[WARNING][2023-12-05 19:43:48][wechat_message.py:84] - [WX]get other_user_id failed: 'NickName'。运行窗口不显示接收的字符串，微信也没没有收到chatGPT的响应。

### 终端日志 📒

```log
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as whale
[INFO][2023-12-05 19:23:00][wechat_channel.py:126] - Wechat login success, user_
id: @4492b68221c3e297abb92ea5af43e514a1508012f46d2b4f54d31e811887ada5, nickname:
 whale
Start auto replying.
[WARNING][2023-12-05 19:23:14][wechat_message.py:84] - [WX]get other_user_id fai
led: 'NickName'
[WARNING][2023-12-05 19:43:42][wechat_message.py:84] - [WX]get other_user_id fai
led: 'NickName'
[WARNING][2023-12-05 19:43:48][wechat_message.py:84] - [WX]get other_user_id fai
led: 'NickName'
```

**Comment by zhayujie** [comment]
你换一个账号来和bot对话看看，同时要携带 bot 前缀

**Comment by mysmallwhale** [comment]
我换了2个微信账号，换了一个open ai的appkey（同一个账号下），发的微信内容也是带bot前缀的，仍然同样的错误。
我主机是新加坡的，不过我是在国内登录微信，不知道有没有影响，proxy配置成 "http://127.0.0.1:7890/"对不对？
C:\chatGPT\chatgpt-on-wechat>py app.py
[INFO][2023-12-06 15:37:07][config.py:236] - [INIT] load config: {'channel_type'
: 'wx', 'model': 'gpt-3.5-turbo', 'open_ai_api_key': 'sk-Q3V4Z7SMB7J4Xl8OdAjlT3B
lbkFJDrFjwNxaf1yAz2FCQNQM', 'open_ai_api_base': 'https://api.openai.com/v1', 'te
xt_to_image': 'dall-e-2', 'voice_to_text': 'openai', 'text_to_voice': 'openai',
'proxy': 'http://127.0.0.1:7890', 'hot_reload': False, 'single_chat_prefix': ['b
ot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'
], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'group_chat_in_
one_session': ['ChatGPT测试群'], 'image_create_prefix': ['画'], 'use_azure_chatg
pt': False, 'speech_recognition': True, 'group_speech_recognition': False, 'voic
e_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 36
00, 'character_desc': 'chatGPT机器人', 'temperature': 0.7, 'top_p': 1, 'subscrib
e_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片
输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字
冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': Fal
se, 'linkai_api_key': '', 'linkai_app_code': '', 'linkai_api_base': 'https://api
.link-ai.chat'}
[INFO][2023-12-06 15:37:07][config.py:184] - [Config] User datas loaded.
[WARNING][2023-12-06 15:37:08][audio_convert.py:9] - import pysilk failed, wecha
ty voice message will not be supported.
C:\Program Files\Python38\lib\site-packages\pydub\utils.py:170: RuntimeWarning:
Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work"
, RuntimeWarning)
[INFO][2023-12-06 15:37:08][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-12-06 15:37:08][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Banwords_v1.0 registe
red, path=./plugins\banwords
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin BDunit_v0.1 registere
d, path=./plugins\bdunit
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Dungeon_v1.0 register
ed, path=./plugins\dungeon
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Finish_v1.0 registere
d, path=./plugins\finish
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Godcmd_v1.0 registere
d, path=./plugins\godcmd
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Hello_v0.1 registered
, path=./plugins\hello
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Keyword_v0.1 register
ed, path=./plugins\keyword
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin linkai_v0.1.0 registe
red, path=./plugins\linkai
[INFO][2023-12-06 15:37:08][plugin_manager.py:41] - Plugin Role_v1.0 registered,
 path=./plugins\role
chatgpt-tool-hub version: 0.4.6
[INFO][2023-12-06 15:37:09][plugin_manager.py:41] - Plugin tool_v0.4 registered,
 path=./plugins\tool
[INFO][2023-12-06 15:37:09][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口
令为5287。
[INFO][2023-12-06 15:37:09][godcmd.py:210] - [Godcmd] inited
[INFO][2023-12-06 15:37:09][keyword.py:40] - [keyword] {}
[INFO][2023-12-06 15:37:09][keyword.py:42] - [keyword] inited.
[INFO][2023-12-06 15:37:09][linkai.py:33] - [LinkAI] inited, config={'group_app_
map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled
': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_
per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'g
roup_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2023-12-06 15:37:10][__init__.py:29] - [visual_dl] init failed, error_inf
o: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-12-06 15:37:10][__init__.py:29] - [visual_dl] init failed, error_inf
o: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-12-06 15:37:10][chatgpt.py:184] - success use proxy: http://127.0.0.
1:7890
[INFO][2023-12-06 15:37:10][victorinox.py:86] - use_tools=['url-get', 'terminal'
, 'meteo-weather', 'python'], params: {'debug': False, 'openai_api_key': 'sk-Q3V
4Z7SMB7J4Xl8OdAjlT3BlbkFJDrFjwNxaf1yAz2FCQNQM', 'open_ai_api_base': 'https://api
.openai.com/v1', 'deployment_id': '', 'proxy': 'http://127.0.0.1:7890', 'request
_timeout': 120, 'model_name': 'gpt-3.5-turbo', 'no_default': False, 'top_k_resul
ts': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', '
google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning
_news_api_key': '', 'cuda_device': 'cpu', 'think_depth': 3, 'arxiv_summary': Tru
e, 'morning_news_use_llm': False, 'llm_api_key': 'sk-Q3V4Z7SMB7J4Xl8OdAjlT3BlbkF
JDrFjwNxaf1yAz2FCQNQM', 'llm_api_base_url': 'https://api.openai.com/v1'}
[INFO][2023-12-06 15:37:10][tool.py:31] - [tool] inited
[INFO][2023-12-06 15:37:10][role.py:69] - [Role] inited
[INFO][2023-12-06 15:37:10][dungeon.py:56] - [Dungeon] inited
[INFO][2023-12-06 15:37:10][hello.py:24] - [Hello] inited
[INFO][2023-12-06 15:37:10][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.
Downloading QR code.
You can also scan QRCode in any website below:
https://api.pwmqr.com/qrcode/create/?url=https://login.weixin.qq.com/l/IalT7JQsT
w==
https://my.tv.sohu.com/user/a/wvideo/getQRCode.do?text=https://login.weixin.qq.c
om/l/IalT7JQsTw==
https://api.qrserver.com/v1/create-qr-code/?size=400×400&data=https://login.wei
xin.qq.com/l/IalT7JQsTw==
https://api.isoyu.com/qr/?m=1&e=L&p=20&url=https://login.weixin.qq.com/l/IalT7JQ
sTw==
█▀▀▀▀▀▀▀█▀█▀██▀██▀█████▀▀▀▀▀▀▀█
█ █▀▀▀█ ██ ▄▄ ▄ █▀▀ ▄██ █▀▀▀█ █
█ █   █ █   █  ▄█ ▀▀█▄█ █   █ █
█ ▀▀▀▀▀ █ ▄ █▀█ █ ▄▀▄ █ ▀▀▀▀▀ █
█▀███▀█▀▀ ▄█ ▀▀▄█▀ █▄ ▀▀▀▀▀██▀█
██▄▄ ▄▀▀█▄▀▄▀█▄▀ ▀█▄█▄█▄▄▄▄▄▄ █
██▀▄▄▀▄▀ ▀ ▄ ▀██▄▀ ▄▄ ▄█▄▄▄█ ▄█
█ █ ▄  ▀█▀     ▀▀ ▄ █▀█▄▄   ▄ █
██▄▀██ ▀▄▀█▀▀ █  █ ▄█▀ █████ ▄█
█▄█▄   ▀█▄▄█▀▄█▀ ▄  ██▄ ▄ ▄▀▄ █
█▀▀▀▀▀█▀ ▀▀█ ▄█ ▄▄  █▀▀▀▀ ▀█▄ █
█▀▀▀▀▀▀▀█ █▀ ▄█▀ ▄▄ ▀ █▀█ ▀▀█ █
█ █▀▀▀█ █▀▄ ▀█▀  ▄ ▄  ▀▀▀ ▀█▄▀█
█ █   █ ██▀█ ▄ ▄▀▄  █  ███▀▀▀ █
█ ▀▀▀▀▀ █▀▀▄▀▄█▄▀█ ▀█ ▀▄ █ █ ▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 鲸鱼
[INFO][2023-12-06 15:37:46][wechat_channel.py:126] - Wechat login success, user_
id: @5d381b77244a767238d43cd25aa05779, nickname: 鲸鱼
Start auto replying.
[WARNING][2023-12-06 15:38:58][wechat_message.py:84] - [WX]get other_user_id fai
led: 'NickName'
[WARNING][2023-12-06 15:39:42][wechat_message.py:84] - [WX]get other_user_id fai
led: 'NickName'
[WARNING][2023-12-06 15:39:44][wechat_message.py:84] - [WX]get other_user_id fai
led: 'NickName'

**Comment by mysmallwhale** [comment]
问题解决了。提示[WARNING][2023-12-05 19:43:48][wechat_message.py:84] - [WX]get other_user_id failed: 'NickName'，是因为我给“文件传播助手”发消息。给其他人发消息，没有这个问题。
