### ISSUE TITLE
用了一天, 突然不行了

### ISSUE THREAD

**Issue by zhouyu168** [zhayujie/chatgpt-on-wechat#158]
好好的突然不行了, 啥原因? 
![不行了](https://user-images.githubusercontent.com/124881099/218058541-0f19cd2f-f265-4061-80d5-2230b80ade9d.png)

**Comment by hexuaaa** [comment]
一样，微信制裁了吧....

**Comment by kof8855** [comment]
我也一样，也是不行了。问题是我itchat别的版本一样等登陆没问题。

**Comment by kof8855** [comment]
换了另一个微信小号就可以。。。看来真是被封号

**Comment by zhouyu168** [comment]
谢谢各位的回复 : )
 换个号成功运行,  前面的号被限制了

**Comment by kof8855** [comment]
> 

先别用了，这个版本的itchat有风险，容易被检测第三方客户端登陆，所以微信才会临时被封，用大号微信解封一下就行。

**Comment by zhayujie** [comment]
先不要用了，see #115
