### ISSUE TITLE
运行程序后ai回答与问题没有关联且程序报错

### ISSUE THREAD

**Issue by Gitspike** [zhayujie/chatgpt-on-wechat#159]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
运行以后胡乱回答问题，并且程序有报错
> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/57885140/218062990-221d660a-844d-4ec6-a8f6-2f3942d55a9a.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：ubuntu20.0
 - Python版本  ( 执行 `python3 -V` )：    3.8                  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip3

**Comment by Gitspike** [comment]
换过key了还是这样，@zhajujie 大佬有空康康是什么问题

**Comment by zhayujie** [comment]
see #97
