### ISSUE TITLE
企微自定义应用，用企业微信客户端正常，个人微信加入聊天无回复，必须要企微的客户端么？(企微未认证)

### ISSUE THREAD

**Issue by rtnt2008** [zhayujie/chatgpt-on-wechat#1593]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 问题描述 😯

企微自定义应用，用企业微信客户端正常，个人微信加入聊天无回复，必须要企微的客户端么？(企微未认证)

**Comment by zhayujie** [comment]
企微自建应用只能和 企微的用户对话哈，个人微信需要加入企业后才能对话

**Comment by huawuhen** [comment]
我也是这样
