### ISSUE TITLE
企微能正常使用，但是回复带有error前缀

### ISSUE THREAD

**Issue by wisdom520** [zhayujie/chatgpt-on-wechat#1594]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

能正常使用，但是回复带有error全追

### 问题描述 😯

![10100](https://github.com/zhayujie/chatgpt-on-wechat/assets/45055150/b083a963-11c3-4397-a70a-2abb53181219)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by ZhangJony** [comment]
我使用微信也有同样问题

[WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我是ChatGPT，一种由OpenAI开发的高级人工智能模型。我可以回答问题、提供信息、撰写文本、翻译语言、帮助解决问题，甚至进行创造性思考。我的知识截止于2023年4月，所以对那之后的事件可能不太了解。我还可以理解和生成图像。我在这里帮助你，无论是解答疑问还是进行有趣的对话。)

**Comment by nothing0here** [comment]
同样的问题
[wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我可以回答各种问题，提供信息，帮助解决问题，进行一般性的对话，提供建议等等。无论是学术性的问题、日常生活中的疑问，还是需要创意性思考的挑战，我都会尽力提供有用的回答。请告诉我你有什么需要或者想要了解的，我会尽力帮助你。)

**Comment by huangzhitian** [comment]
带前缀error的大概率不是使用官方key，使用官方key(sk-xxxxx)没问题的

**Comment by zhayujie** [comment]
和openai接口返回不兼容导致的错误
