### ISSUE TITLE
请问有支持的谷歌gemini的计划吗

### ISSUE THREAD

**Issue by Reachan0** [zhayujie/chatgpt-on-wechat#1596]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by superyoung0927** [comment]
同问，万人血书添加上

**Comment by zhayujie** [comment]
已接入
https://github.com/zhayujie/chatgpt-on-wechat/pull/1598
