### ISSUE TITLE
使用docker模式部署，使用飞书CHANNEL，容器启动后发现配置的端口没有监听服务

### ISSUE THREAD

**Issue by wurenxiaozu** [zhayujie/chatgpt-on-wechat#1597]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

多次启动容器，每次启动后都没有对应的监听服务

### 问题描述 😯

使用docker模式部署，使用飞书CHANNEL，使用微软云的Chatgpt，启动容器后，容器没有启动任何监听端口。
[root@VM-16-4-centos cow]# cat /data/cow/docker-compose.yml
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'XXXXXXXXXXXXXXXXXXXXXXX'
      MODEL: 'gpt-4-32k'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'True'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      USE_AZURE_CHATGPT: 'True'
      OPEN_AI_API_BASE: 'https://xxxx.openai.azure.com/'
      CHANNEL_TYPE: 'feishu'
      FEISHU_PORT: 8081
      FEISHU_APP_ID: 'XXXXXXXXXXXXXXXXXXXXXXX'
      FEISHU_APP_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXX'
      FEISHU_TOKEN: 'XXXXXXXXXXXXXXXXXXXXXXX'
      FEISHU_BOT_NAME: '智能AI'
      CHANNEL_TYPE: 'feishu'
[root@VM-16-4-centos cow]#

### 终端日志 📒

[INFO][2023-12-15 01:46:01][config.py:193] - [Config] User datas file not found, ignore.
[WARNING][2023-12-15 01:46:01][audio_convert.py:9] - import pysilk failed, wechaty voice message will not be supported.
[INFO][2023-12-15 01:46:01][feishu_channel.py:39] - [FeiShu] app_id=XXXXXXXXXXXXXXXXXXXXXXX, app_secret=XXXXXXXXXXXXXXXXXXXXXXX verification_token=XXXXXXXXXXXXXXXXXXXXXXX
[INFO][2023-12-15 01:46:01][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-12-15 01:46:01][plugin_manager.py:88] - Scaning plugins ...
[INFO][2023-12-15 01:46:01][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-12-15 01:46:01][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-12-15 01:46:01][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-12-15 01:46:01][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-12-15 01:46:01][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-12-15 01:46:01][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
chatgpt-tool-hub version: 0.4.6
[INFO][2023-12-15 01:46:02][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-12-15 01:46:02][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-12-15 01:46:02][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-12-15 01:46:02][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin GODCMD not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin KEYWORD not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin BANWORDS not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin LINKAI not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin TOOL not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin ROLE not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin DUNGEON not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin BDUNIT not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin HELLO not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][plugin_manager.py:123] - Plugin FINISH not found in pconfig, adding to pconfig...
[INFO][2023-12-15 01:46:02][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为9483。
[INFO][2023-12-15 01:46:02][godcmd.py:210] - [Godcmd] inited
[INFO][2023-12-15 01:46:02][keyword.py:40] - [keyword] {}
[INFO][2023-12-15 01:46:02][keyword.py:42] - [keyword] inited.
[WARNING][2023-12-15 01:46:02][banwords.py:54] - [Banwords] init failed, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[WARNING][2023-12-15 01:46:02][plugin_manager.py:148] - Failed to init BANWORDS, diabled. [Errno 2] No such file or directory: '/app/plugins/banwords/banwords.txt'
[INFO][2023-12-15 01:46:02][linkai.py:33] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2023-12-15 01:46:02][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-12-15 01:46:02][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-12-15 01:46:02][chatgpt.py:186] - proxy no find, directly request to chatgpt instead
[INFO][2023-12-15 01:46:02][chatgpt.py:191] - success use customized api base url: https://xxxx.openai.azure.com/
[INFO][2023-12-15 01:46:02][chatgpt.py:186] - proxy no find, directly request to chatgpt instead
[INFO][2023-12-15 01:46:02][victorinox.py:86] - use_tools=['meteo-weather', 'python', 'url-get', 'terminal'], params: {'debug': False, 'openai_api_key': 'XXXXXXXXXXXXXXXXXXXXXXX', 'open_ai_api_base': 'https://xxxx.openai.azure.com/', 'deployment_id': '', 'proxy': '', 'request_timeout': 120, 'model_name': 'gpt-4-32k', 'no_default': False, 'top_k_results': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning_news_api_key': '', 'cuda_device': 'cpu', 'think_depth': 3, 'arxiv_summary': True, 'morning_news_use_llm': False, 'llm_api_key': 'XXXXXXXXXXXXXXXXXXXXXXX', 'llm_api_base_url': 'https://xxxx.openai.azure.com/'}
[INFO][2023-12-15 01:46:02][tool.py:31] - [tool] inited
[INFO][2023-12-15 01:46:02][role.py:69] - [Role] inited
[INFO][2023-12-15 01:46:02][dungeon.py:56] - [Dungeon] inited
[WARNING][2023-12-15 01:46:02][bdunit.py:42] - [BDunit] init failed, ignore
[WARNING][2023-12-15 01:46:02][plugin_manager.py:148] - Failed to init BDUNIT, diabled. config.json not found
[INFO][2023-12-15 01:46:02][hello.py:24] - [Hello] inited
[INFO][2023-12-15 01:46:02][finish.py:23] - [Finish] inited

[root@VM-16-4-centos cow]# docker -v
Docker version 1.13.1, build 7d71120/1.13.1
[root@VM-16-4-centos cow]# netstat -anpl
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      1216/pure-ftpd (SER
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1159/sshd
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      2220/python3
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1204/master
tcp        0      0 10.0.16.4:22            106.120.105.229:49689   ESTABLISHED 28711/sshd: appuser
tcp        0      0 10.0.16.4:39788         169.254.0.55:5574       ESTABLISHED 3203/YDService
tcp        0      0 10.0.16.4:22            106.120.105.229:64672   ESTABLISHED 19801/sshd: appuser
tcp        0      0 10.0.16.4:22            106.120.105.229:55752   ESTABLISHED 24505/sshd: appuser
tcp        0      0 10.0.16.4:41298         169.254.0.138:8186      ESTABLISHED 2379/tat_agent
tcp        0      0 10.0.16.4:8888          106.120.105.229:49545   ESTABLISHED 2220/python3
tcp        0      0 10.0.16.4:39786         169.254.0.55:5574       ESTABLISHED 3203/YDService
tcp        0      0 10.0.16.4:22            106.120.105.229:64675   ESTABLISHED 19805/sshd: appuser
tcp        0     48 10.0.16.4:22            106.120.105.229:49688   ESTABLISHED 28708/sshd: appuser
tcp6       0      0 :::3306                 :::*                    LISTEN      2152/mysqld
tcp6       0      0 :::21                   :::*                    LISTEN      1216/pure-ftpd (SER
tcp6       0      0 ::1:25                  :::*                    LISTEN      1204/master
udp        0      0 0.0.0.0:68              0.0.0.0:*                           961/dhclient
udp        0      0 172.18.0.1:123          0.0.0.0:*                           697/ntpd
udp        0      0 172.17.0.1:123          0.0.0.0:*                           697/ntpd
udp        0      0 10.0.16.4:123           0.0.0.0:*                           697/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           697/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           697/ntpd
udp6       0      0 fe80::42:4aff:fe6c::123 :::*                                697/ntpd
udp6       0      0 fe80::4c49:4cff:fe1:123 :::*                                697/ntpd
udp6       0      0 fe80::5054:ff:fe5a::123 :::*                                697/ntpd
udp6       0      0 ::1:123                 :::*                                697/ntpd
udp6       0      0 :::123                  :::*                                697/ntpd

**Comment by zhayujie** [comment]
可以在docker-compose.yml 中增加一个端口映射，假设你在宿主机也监听8081端口，则在services下的对应服务中添加以下配置：

ports:
  - "8081:8081"

**Comment by wurenxiaozu** [comment]
没有配置端口映射，增加后解决，多谢。
