### ISSUE TITLE
google 的老是提示这个｛google.api_core.exceptions.FailedPrecondition: 400 User location is not supported for the API use.｝大家有办法解决吗

### ISSUE THREAD

**Issue by Rwindest168888** [zhayujie/chatgpt-on-wechat#1602]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

换了不同的节点，用几分钟就提示，有时过段时间又能用了，你们的会吗？
raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.FailedPrecondition: 400 User location is not supported for the API use.

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by LichKing-W** [comment]
看着像是用户所在地区不支持，代理换成别的地方试试？

**Comment by Rwindest168888** [comment]
> 看着像是用户所在地区不支持，代理换成别的地方试试？

我换了一堆代理，问几条问题后又报这错，这些代理都能网页的Bard,API就不行了

**Comment by Rwindest168888** [comment]
挂国外云服务器上就没问题，本地开代理，看来是对节点要求太高了.

**Comment by Niuwh** [comment]
同样是这个问题，这是自己的服务器问题吗

**Comment by Rwindest168888** [comment]
> 同样是这个问题，这是自己的服务器问题吗

我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。

**Comment by Niuwh** [comment]
> > 同样是这个问题，这是自己的服务器问题吗
> 
> 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。

香港的不行吗，我的是香港没有成功一次

**Comment by Rwindest168888** [comment]
> > > 同样是这个问题，这是自己的服务器问题吗
> > 
> > 
> > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> 
> 香港的不行吗，我的是香港没有成功一次

HK不在可用国家里面呀，当然不行

**Comment by Niuwh** [comment]
> > > > 同样是这个问题，这是自己的服务器问题吗
> > > 
> > > 
> > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> > 
> > 
> > 香港的不行吗，我的是香港没有成功一次
> 
> HK不在可用国家里面呀，当然不行

这样啊，没仔细看。多谢了。我还一直找问题呢，话说哪里能白嫖服务器呀

**Comment by zousoooo** [comment]
> > > > > 同样是这个问题，这是自己的服务器问题吗
> 
> > > > 
> 
> > > > 
> 
> > > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> 
> > > 
> 
> > > 
> 
> > > 香港的不行吗，我的是香港没有成功一次
> 
> > 
> 
> > HK不在可用国家里面呀，当然不行
> 
> 
> 
> 这样啊，没仔细看。多谢了。我还一直找问题呢，话说哪里能白嫖服务器呀

aws或者谷歌云

**Comment by Niuwh** [comment]
> > > > > > 同样是这个问题，这是自己的服务器问题吗
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 香港的不行吗，我的是香港没有成功一次
> > 
> > 
> > > 
> > 
> > 
> > > HK不在可用国家里面呀，当然不行
> > 
> > 
> > 这样啊，没仔细看。多谢了。我还一直找问题呢，话说哪里能白嫖服务器呀
> 
> aws或者谷歌云

都需要信用卡，白嫖了阿里云的新加坡服务器，可行

**Comment by zousoooo** [comment]
> > > > > > > 同样是这个问题，这是自己的服务器问题吗
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 香港的不行吗，我的是香港没有成功一次
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > HK不在可用国家里面呀，当然不行
> 
> > > 
> 
> > > 
> 
> > > 这样啊，没仔细看。多谢了。我还一直找问题呢，话说哪里能白嫖服务器呀
> 
> > 
> 
> > aws或者谷歌云
> 
> 
> 
> 都需要信用卡，白嫖了阿里云的新加坡服务器，可行

可以用多久啊，另外aws或者谷歌云可以在淘宝买虚拟卡注册

**Comment by Niuwh** [comment]
> > > > > > > > 同样是这个问题，这是自己的服务器问题吗
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 香港的不行吗，我的是香港没有成功一次
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > HK不在可用国家里面呀，当然不行
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 这样啊，没仔细看。多谢了。我还一直找问题呢，话说哪里能白嫖服务器呀
> > 
> > 
> > > 
> > 
> > 
> > > aws或者谷歌云
> > 
> > 
> > 都需要信用卡，白嫖了阿里云的新加坡服务器，可行
> 
> 可以用多久啊，另外aws或者谷歌云可以在淘宝买虚拟卡注册

一年，是嘛，学到了

**Comment by KimhonWong** [comment]
> > > 同样是这个问题，这是自己的服务器问题吗
> > 
> > 
> > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> 
> 香港的不行吗，我的是香港没有成功一次

香港不行，用日本试试

**Comment by Ostrich3388** [comment]
> > > > 同样是这个问题，这是自己的服务器问题吗
> > > 
> > > 
> > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> > 
> > 
> > 香港的不行吗，我的是香港没有成功一次
> 
> 香港不行，用日本试试

我已經用了日本ORACLE FREE去開了, 都是出User location is not supported for the API use.

**Comment by qiuyueovo** [comment]
SG是可以的

**Comment by heiheiheibj** [comment]
我也是用HK，出现这情况，切新加坡、小日本等都行。

**Comment by ReiiNoki** [comment]
> > > > > 同样是这个问题，这是自己的服务器问题吗
> > > > 
> > > > 
> > > > 我上午用本地电脑开节点就一直这样，偶尔能用几次，下午换成在US的服务器部署，就没发生这问题了。
> > > 
> > > 
> > > 香港的不行吗，我的是香港没有成功一次
> > 
> > 
> > 香港不行，用日本试试
> 
> 我已經用了日本ORACLE FREE去開了, 都是出User location is not supported for the API use.

大佬能解决吗，我也是一样的情况，解决不了还是报错

**Comment by Aure7138** [comment]
同样，在服务器上跑了几天突然就不行了
![image](https://i.imgur.com/gYQMd6s.png)
