### ISSUE TITLE
微信掉线通知，支持配置 WebHook

### ISSUE THREAD

**Issue by alfchao** [zhayujie/chatgpt-on-wechat#1603]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

登录之后，隔几天就会掉线。
希望可以加一个微信掉线通知，支持自定义webhook配置。
我在这个issue中发现有人提出过类似想法。
#916
https://github.com/zhayujie/chatgpt-on-wechat/issues/916#issuecomment-1535873131

### 举例

我大概找了下，可以在此处添加 WebHook 调用。
lib.itchat.components.login.login
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/49786895/da8d1e3c-3988-41c5-89f7-a432153be9f8)

### 动机

微信会不定期掉线，无法直接知晓当前机器人是否存活，所以希望加一个存活检测。

**Comment by xushuojie** [comment]
钉钉机器人加签版本的login函数
`import requests
import json
import time
import hmac
import hashlib
import base64
def login(self, enableCmdQR=False, picDir=None, qrCallback=None,
          loginCallback=None, exitCallback=None):
    # 钉钉webhook
    url = '钉钉webhook_url'
    secret = '钉钉webhook_加签'
    timestamp = str(round(time.time() * 1000))
    sign = generate_sign(secret, timestamp)
    webhook_url = f"{url}&timestamp={timestamp}&sign={sign}"
    headers = {
        'Content-Type': 'application/json',
        }
    if self.alive or self.isLogging:
        logger.warning('itchat has already logged in.')
        return
    self.isLogging = True
    logger.info('Ready to login.')
    while self.isLogging:
        uuid = push_login(self)
        if uuid:
            qrStorage = io.BytesIO()
        else:
            data = {
                'msgtype': 'text',
                'text': {'content': '腾讯云-微信掉线了！'}
                }
            response = requests.post(webhook_url, headers=headers, data=json.dumps(data))
            logger.info(response.text)
            logger.info('Getting uuid of QR code.')
            while not self.get_QRuuid():
                time.sleep(1)
            logger.info('Downloading QR code.')
            qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
                                    picDir=picDir, qrCallback=qrCallback)
            # logger.info('Please scan the QR code to log in.')
        isLoggedIn = False
        while not isLoggedIn:
            status = self.check_login()
            if hasattr(qrCallback, '__call__'):
                qrCallback(uuid=self.uuid, status=status,
                           qrcode=qrStorage.getvalue())
            if status == '200':
                isLoggedIn = True
            elif status == '201':
                if isLoggedIn is not None:
                    logger.info('Please press confirm on your phone.')
                    isLoggedIn = None
                    time.sleep(7)
                time.sleep(0.5)
            elif status != '408':
                break
        if isLoggedIn:
            break
        elif self.isLogging:
            logger.info('Log in time out, reloading QR code.')
    else:
        return  # log in process is stopped by user
    logger.info('Loading the contact, this may take a little while.')
    self.web_init()
    self.show_mobile_login()
    self.get_contact(True)
    if hasattr(loginCallback, '__call__'):
        r = loginCallback()
    else:
        # utils.clear_screen()
        if os.path.exists(picDir or config.DEFAULT_QR):
            os.remove(picDir or config.DEFAULT_QR)
        data = {
                'msgtype': 'text',
                'text': {'content': '腾讯云-微信已登录！'}
                }
        response = requests.post(webhook_url, headers=headers, data=json.dumps(data))
        logger.info(response.text)
        logger.info('Login successfully as %s' % self.storageClass.nickName)
    self.start_receiving(exitCallback)
    self.isLogging = False`

**Comment by xushuojie** [comment]
钉钉机器人加签版本的login函数
```python
import requests
import json
import time
import hmac
import hashlib
import base64

   def login(self, enableCmdQR=False, picDir=None, qrCallback=None,
          loginCallback=None, exitCallback=None):
    # 钉钉webhook
    url = '钉钉webhook_url'
    secret = '钉钉webhook_加签'
    timestamp = str(round(time.time() * 1000))
    sign = generate_sign(secret, timestamp)
    webhook_url = f"{url}&timestamp={timestamp}&sign={sign}"
    headers = {
        'Content-Type': 'application/json',
        }
    if self.alive or self.isLogging:
        logger.warning('itchat has already logged in.')
        return
    self.isLogging = True
    logger.info('Ready to login.')
    while self.isLogging:
        uuid = push_login(self)
        if uuid:
            qrStorage = io.BytesIO()
        else:
            data = {
                'msgtype': 'text',
                'text': {'content': '腾讯云-微信掉线了！'}
                }
            response = requests.post(webhook_url, headers=headers, data=json.dumps(data))
            logger.info(response.text)
            logger.info('Getting uuid of QR code.')
            while not self.get_QRuuid():
                time.sleep(1)
            logger.info('Downloading QR code.')
            qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
                                    picDir=picDir, qrCallback=qrCallback)
            # logger.info('Please scan the QR code to log in.')
        isLoggedIn = False
        while not isLoggedIn:
            status = self.check_login()
            if hasattr(qrCallback, '__call__'):
                qrCallback(uuid=self.uuid, status=status,
                           qrcode=qrStorage.getvalue())
            if status == '200':
                isLoggedIn = True
            elif status == '201':
                if isLoggedIn is not None:
                    logger.info('Please press confirm on your phone.')
                    isLoggedIn = None
                    time.sleep(7)
                time.sleep(0.5)
            elif status != '408':
                break
        if isLoggedIn:
            break
        elif self.isLogging:
            logger.info('Log in time out, reloading QR code.')
    else:
        return  # log in process is stopped by user
    logger.info('Loading the contact, this may take a little while.')
    self.web_init()
    self.show_mobile_login()
    self.get_contact(True)
    if hasattr(loginCallback, '__call__'):
        r = loginCallback()
    else:
        # utils.clear_screen()
        if os.path.exists(picDir or config.DEFAULT_QR):
            os.remove(picDir or config.DEFAULT_QR)
        data = {
                'msgtype': 'text',
                'text': {'content': '腾讯云-微信已登录！'}
                }
        response = requests.post(webhook_url, headers=headers, data=json.dumps(data))
        logger.info(response.text)
        logger.info('Login successfully as %s' % self.storageClass.nickName)
    self.start_receiving(exitCallback)
    self.isLogging = False
```
