### ISSUE TITLE
群晖docker中映射配置文件config.json的路径应该是？

### ISSUE THREAD

**Issue by lepingzhang** [zhayujie/chatgpt-on-wechat#1604]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

尝试了/config.json、/app/config.json、/data/config.json，可以扫码登录，但状态却是一直等待自动回复

### 问题描述 😯

尝试了/config.json、/app/config.json、/data/config.json，可以扫码登录，但状态却是一直等待自动回复，传统的环境变量添加参数就可以，因为配置文件修改比较方便，所以想知道是否支持挂载以及对应的映射路径是什么。提前感谢。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by huangzhitian** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/129321746/fdde21d0-6b64-495b-847c-80fca5c3ed11)
我的docker-compose.yml是这样的
删除原本的一些配置
新建config.json在docker-compose.yml同级文件夹里
只是主配置的映射，插件的config没有映射
另外dokcer使用Gemini的话
需要安装一下依赖
cd docker-compose.yml所在的文件夹
docker exec -it 容器ID /bin/bash 
pip3 install google-generativeai
exit
sudo docker compose restart
sudo docker logs -f chatgpt-on-wechat
扫码登录即可

**Comment by lepingzhang** [comment]
> ![image](https://private-user-images.githubusercontent.com/129321746/291021390-fdde21d0-6b64-495b-847c-80fca5c3ed11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDMwMTQsIm5iZiI6MTcwMjgwMjcxNCwicGF0aCI6Ii8xMjkzMjE3NDYvMjkxMDIxMzkwLWZkZGUyMWQwLTZiNjQtNDk1Yi04NDdjLTgwZmNhNWMzZWQxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwODQ1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWYyYWJkMGE5ZjIyZjkyZWIxMWRhMTg0NzU5OWNmYTVjMzQxOGJiOGVlMGIzNWY1YTUxMDIwY2M4NjhjNmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yHJ74V5XZM5KXjFxnWxlC4KlvjnkVaZC6CZiKTeBbxU) 我的docker-compose.yml是这样的 删除原本的一些配置 新建config.json在docker-compose.yml同级文件夹里 只是主配置的映射，插件的config没有映射 另外dokcer使用Gemini的话 需要安装一下依赖 cd docker-compose.yml所在的文件夹 docker exec -it 容器ID /bin/bash pip3 install google-generativeaipip3安装google-generativeai exit 退出 sudo docker compose restart sudo docker logs -f chatgpt-on-wechat 扫码登录即可

非常感谢提供帮助
