### ISSUE TITLE
更改openai的API端口url为本地的url

### ISSUE THREAD

**Issue by ZDP-Q** [zhayujie/chatgpt-on-wechat#1608]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我在本地部署了一个模型，这个模型支持chatgpt的端口，能够调用chatgpt端口的工具都可以调用这个本地的url，我想知道在哪里可以修改调用的url地址

**Comment by huangzhitian** [comment]
看看config.py文件

**Comment by ZDP-Q** [comment]
看到了，谢谢你！已经OK了

**Comment by ZDP-Q** [comment]
> 看看config.py文件

看到了，谢谢你！已经OK了
