### ISSUE TITLE
可以考虑对接公众号，我测试了一下，这个仓库的机器人好像更智能一些

### ISSUE THREAD

**Issue by GeorgeGalway** [zhayujie/chatgpt-on-wechat#161]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by andyli386** [comment]
这个响应时间怎么样？

**Comment by GeorgeGalway** [comment]
> 这个响应时间怎么样？

回复速度都差不多，公众号的 5s 和 15s 限制可以优化

**Comment by twthblzhm** [comment]
我有公众号，怎么对接啊

**Comment by wpneu6699** [comment]
公众号怎么对接啊

**Comment by zhayujie** [comment]
> > 这个响应时间怎么样？
> 
> 回复速度都差不多，公众号的 5s 和 15s 限制可以优化

5s限制 对于个人公众号有什么好的优化方式吗

**Comment by zhayujie** [comment]
个人和企业公众号的已经接入了：
https://github.com/zhayujie/bot-on-anything/

**Comment by zhayujie** [comment]
个人和企业公众号的已经接入了：  @twthblzhm @wpneu6699 
https://github.com/zhayujie/bot-on-anything/

**Comment by GeorgeGalway** [comment]
> 个人和企业公众号的已经接入了： @twthblzhm @wpneu6699 https://github.com/zhayujie/bot-on-anything/

感谢作者，已F
