### ISSUE TITLE
[WARNING][2023-12-19 02:57:38][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request')))

### ISSUE THREAD

**Issue by loks666** [zhayujie/chatgpt-on-wechat#1610]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[WARNING][2023-12-19 02:57:38][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request')))

### 问题描述 😯

由于我使用的是one api搭建的代理key，所以他一直报这样的一个错误，能肯定的是肯定我的地址填的有问题，我想知道到底应该填什么地址，才可以成功调用我的中转服务器

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by huangAoJiong** [comment]
同样问题，请问楼主解决了吗

**Comment by loks666** [comment]
填base不要填proxy

**Comment by loks666** [comment]
fixed

**Comment by huangAoJiong** [comment]
> 填base不要填proxy

感谢感谢，可以了

**Comment by cq134cq** [comment]
> > 填base不要填proxy
> 
> 感谢感谢，可以了

‘请你能不能看一下你的配置，我填base，可是还是报和你一产的错
这是我的配置
# encoding:utf-8

import json
import logging
import os
import pickle

from common.log import logger

# 将所有可用的配置项写在字典里, 请使用小写字母
# 此处的配置值无实际意义，程序不会读取此处的配置，仅用于提示格式，请将配置加入到config.json中
available_setting = {
    # openai api配置
    "open_ai_api_key": "sk-Ig5Y2Lq1nluNvYZE81B4B1F11cA84d1eAb112eE4C826De94",  # openai api key
    # openai apibase，当use_azure_chatgpt为true时，需要设置对应的api base
    "open_ai_api_base": "http://10.0.100.176:3002/v1",
    "proxy": "",  # openai使用的代理
    # chatgpt模型， 当use_azure_chatgpt为true时，其名称为Azure上model deployment名称
    "model": "gpt-3.5-turbo",  # 还支持 gpt-4, gpt-4-turbo, wenxin, xunfei, qwen
    "use_azure_chatgpt": False,  # 是否使用azure的chatgpt
    "azure_deployment_id": "",  # azure 模型部署名称
    "azure_api_version": "",  # azure api版本
    # Bot触发配置

**Comment by you-know-m** [comment]
这就太坑了

**Comment by huimutan** [comment]
"model": "gpt-3.5-turbo",
我用的情况是，如果模型选openai里面的，那就走这个配置
  # openai api配置
  "open_ai_api_key": "*******",
  "open_ai_api_base": "http://*******:3000/v1",
如果模型是智谱的比如glm-4，就走智谱这个配置
    # 智谱AI 平台配置
    "zhipu_ai_api_key": "******",
    "zhipu_ai_api_base": "https://open.bigmodel.cn/api/paas/v4",
