### ISSUE TITLE
请问，用docker在linux部署的，是否一次只能是有一个模型在用

### ISSUE THREAD

**Issue by jonny-gg** [zhayujie/chatgpt-on-wechat#1616]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

比如设置了GPT4.5,又设置了azure-api，那是不是只能用azure-api模型。如果不是，那么是怎么切换模型的呀，请大佬指教

### 举例

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/10399955/c450b139-42b9-4710-bfb2-521d1dc91e54)
看着代码好像是逐步替换的

**Comment by XueJourney** [comment]
详细查看godcmd插件的使用教程，godcmd配置完后，可使用#model看当前模型，使用#model 模型名字 切换模型
