### ISSUE TITLE
复制了项目的副本，使用的配置信息，是同一个config.json，这个怎么解决呢？ 服务器部署

### ISSUE THREAD

**Issue by moylor123** [zhayujie/chatgpt-on-wechat#1619]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

如何更换不同的config.json角色和key池？

### 举例

登录不同的微信，出现不同的角色名，是服务器部署。

### 动机

解决bot复制和多账号登录的问题！

**Comment by yangzhao917** [comment]
我的也是服务端部署的方式，我对你的问题的理解是一个项目使用多个不同的config.json文件配置，不知道我的理解是否正确。如果是这样，有两种办法：
1.尝试将副本复制多份，使用不同的命名来命名，然后修改config.json的配置信息，使用脚本启动项目。然后使用不同的微信扫码登陆。（推荐使用这种方式，应该是可行的）
2.尝试修改config.json的配置，添加多个数组参数，然后修改对应的Python解析代码，使其支持数组参数的解析配置。但对于多账户的登陆，这种可能不太可行，因为涉及微信的接口回调。这种适用于扩展现有的配置和功能。
希望对你有所帮助~

**Comment by 6vision** [comment]
> 我的也是服务端部署的方式，我对你的问题的理解是一个项目使用多个不同的config.json文件配置，不知道我的理解是否正确。如果是这样，有两种办法： 1.尝试将副本复制多份，使用不同的命名来命名，然后修改config.json的配置信息，使用脚本启动项目。然后使用不同的微信扫码登陆。（推荐使用这种方式，应该是可行的） 2.尝试修改config.json的配置，添加多个数组参数，然后修改对应的Python解析代码，使其支持数组参数的解析配置。但对于多账户的登陆，这种可能不太可行，因为涉及微信的接口回调。这种适用于扩展现有的配置和功能。 希望对你有所帮助~

第一种是可行的
