### ISSUE TITLE
微信账号违规被限制中

### ISSUE THREAD

**Issue by jezhang** [zhayujie/chatgpt-on-wechat#162]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

账号违规，以下功能被限制中：所有社交场景功能

限制原因：使用了外挂，非官方客户端或模拟器

* 2月9日收到微信安全提醒，你承诺合规使用微信
* 2月10日 限制所有社交场景：你已多次违规，本次升级处罚

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by budongsir** [comment]
封了几天？ 会影响主号吗？

**Comment by zhayujie** [comment]
目前用不了了 #115
