### ISSUE TITLE
每次重启itchat, 用户的ID都会变, 谁有办法固定这个用户ID

### ISSUE THREAD

**Issue by ZhanglinX233** [zhayujie/chatgpt-on-wechat#1620]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

ID是这样的:
@31fd7be93cba9b43788e2cf8cff6a3c63b41f8856b0ca87f95c6f608cf26e277

### 举例

<img width="928" alt="截屏2023-12-22 16 54 16" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/135933325/ac86368f-8da1-4d82-b974-ee2363c14402">

### 动机

更好记录用户相关信息

**Comment by ZhanglinX233** [comment]
有大佬咩

**Comment by yangzhao917** [comment]
第一：根据你反馈的内容，应该是把用户信息持久化到数据库了，那么关键问题是这些数据是怎么来的呢？并没有看到相关持久化到数据库的代码片段，还希望能反馈一下相关的内容。
第二：每次重启itchat, 用户的ID都会变，这个userId，是哪里得到的，我并没有注意到itchat重启，userId是否会发生变化的问题。

**Comment by fattank** [comment]
> ### ⚠️ 搜索是否存在类似issue
> * [x]  我已经搜索过issues和disscussions，没有发现相似issue
> 
> ### 总结
> ID是这样的: @31fd7be93cba9b43788e2cf8cff6a3c63b41f8856b0ca87f95c6f608cf26e277
> 
> ### 举例
> <img alt="截屏2023-12-22 16 54 16" width="928" src="https://private-user-images.githubusercontent.com/135933325/292445976-ac86368f-8da1-4d82-b974-ee2363c14402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MTk2NzIsIm5iZiI6MTcwMzUxOTM3MiwicGF0aCI6Ii8xMzU5MzMzMjUvMjkyNDQ1OTc2LWFjODYzNjhmLThkYTEtNGQ4Mi1iOTc0LWVlMjM2M2MxNDQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxNTQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWIyOTlhNGY3ZWQ4ZTkxNDcyZTVjMjcwYTVhZmE2NzI2OGMwOTM4M2UwZWJhMWZhMWRhMjg3Njk2MGQzZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GDWb5BdS2i2BAY_Prb2D_NqwkLOuzVof4y-9bH_TJPI">
> ### 动机
> 更好记录用户相关信息

感觉你要做记录或者计费。目前我用的是昵称，ID是相对动态的，不好建立对应关系，抓昵称基本不会变。

**Comment by ZhanglinX233** [comment]
只能用昵称了，看来

**Comment by ningxiaoxiao** [comment]
https://github.com/wechaty/wechaty/issues/1644   使用的应该是网页版本的微信协议?  ipad版本的协议好像可以固定下来

**Comment by Namarimizu** [comment]
我用remarkname追踪，不过备注是我自己手动的

**Comment by bingjiw** [comment]
可以修改itchat的源码，直接把微信通信协议中的 wxid 拿过来当 ID 用，永不变。

**Comment by 1441853031** [comment]
> 可以修改itchat的源码，直接把微信通信协议中的 wxid 拿过来当 ID 用，永不变。

大佬应该怎么改

**Comment by bingjiw** [comment]
不好意思，我不是大佬，才发现：是腾讯把WEB微信协议中的WXID隐藏了，故意让它每次都变。而ITCHAT是基于WEB微信协议的。

除非用wechaty的 IPAD PRO微信协议，但不知此协议是否容易被封。

**Comment by 6vision** [comment]
ichat协议暂未好的解决办法
