### ISSUE TITLE
讯飞星火v3.0 401错误

### ISSUE THREAD

**Issue by fengyuanluo** [zhayujie/chatgpt-on-wechat#1623]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

企业微信发送信息

### 问题描述 😯

error: Handshake status 401 Unauthorized
没有修改xunfei_spark_bot.py，确认信息填写正确

### 终端日志 📒

```log
[INFO][2023-12-23 02:12:46][bridge.py:49] - create bot xunfei for chat
[INFO][2023-12-23 02:12:46][xunfei_spark_bot.py:58] - [XunFei] query=你是谁
[INFO][2023-12-23 02:12:46][xunfei_spark_bot.py:105] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你是谁'}]
[ERROR][2023-12-23 02:12:47][xunfei_spark_bot.py:192] - [XunFei] error: Handshake status 401 Unauthorized
[INFO][2023-12-23 02:13:16][xunfei_spark_bot.py:91] - [XunFei-API] response=, time=30.15532612800598s, usage={}
```

**Comment by fengyuanluo** [comment]
讯飞部分json如下
 "model": "xunfei",
  "xunfei_app_id": "",
  "xunfei_api_key": "",
  "xunfei_api_secret": "",

**Comment by fengyuanluo** [comment]
> 讯飞部分json如下 "model": "xunfei", "xunfei_app_id": "", "xunfei_api_key": "", "xunfei_api_secret": "",

id什么的都正确填写了的

**Comment by CHANGUO** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/35283633/1b390758-7fac-4fd6-b1c8-1f77d33b065b)
。。。

**Comment by SunBriad** [comment]
这个后面解决了吗？我也遇到这个问题了

**Comment by fengyuanluo** [comment]
> 这个后面解决了吗？我也遇到这个问题了

没解决，暂时拿linkai用着

**Comment by 316yangguang** [comment]
大佬解决了吗，我现在也遇到了这个问题

**Comment by Irurii** [comment]
我也是这个问题，发现确实"xunfei_api_key": "","xunfei_api_secret": ""填反了

**Comment by fengyuanluo** [comment]
> 我也是这个问题，发现确实"xunfei_api_key": "","xunfei_api_secret": ""填反了

是这样的......
这俩和后台显示的是反过来的

**Comment by mr1qinganliu** [comment]
老哥你这个问题解决以后讯飞回答的快吗

**Comment by Irurii** [comment]
好像不快，4s-8s的延迟



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月3日(周六) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 讯飞星火v3.0 401错误 (Issue #1623)




 
老哥你这个问题解决以后讯飞回答的快吗
