### ISSUE TITLE
模型claude无法使用

### ISSUE THREAD

**Issue by aidyfeng** [zhayujie/chatgpt-on-wechat#1627]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

model使用claude, 并且设置了claude_api_cookie

### 问题描述 😯

无法完成对话,提示{"error":{"type":"permission_error","message":"Invalid model","code":"model_not_allowed"}}

### 终端日志 📒

```log
[INFO][2023-12-26 02:45:55][claude_ai_bot.py:147] - [CLAUDEAI] query=瑶柱是什么
[ERROR][2023-12-26 02:45:56][claude_ai_bot.py:207] - [CLAUDE] chat failed, status_code=403, msg=Invalid model, type=permission_error, detail: {"error":{"type":"permission_error","message":"Invalid model","code":"model_not_allowed"}}, uuid: 192c8935-0a83-4f7c-8487-301595f1d802
[INFO][2023-12-26 02:45:56][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
提问太快啦，请休息一下再问我吧), receiver=@@ca2d9d6b2a96b5e80527c385a468f6b54f7b9246853b3ae5f4ff3a220a6bde57
```

**Comment by 6vision** [comment]
最新版本已支持api调用，
