### ISSUE TITLE
过一两个小时自动log out 是什么原因

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#163]
# 自动logout 无法提供服务
# 没有做什么事，服务自己就停止了，是哪里配置的问题吗？ 系统已经设置了不会sleep不会自动logout

**Comment by zhayujie** [comment]
网络稳定吗，中途没有开代理什么的吧?   有在其他端登录微信吗，手机微信有下线吗

**Comment by hellger** [comment]
我也遇到自动退出登录了。目前大概4-5天左右电脑端退出登录了。尚不清楚是微信踢下线还是软件本身的问题。

**Comment by bboychencan** [comment]
> 网络稳定吗，中途没有开代理什么的吧? 有在其他端登录微信吗，手机微信有下线吗

手机扫码登录后，手机微信一直开着。 需要把手机微信下线吗？ 手机微信下线服务还可以继续使用是吗？

**Comment by zhayujie** [comment]
> > 网络稳定吗，中途没有开代理什么的吧? 有在其他端登录微信吗，手机微信有下线吗
> 
> 手机扫码登录后，手机微信一直开着。 需要把手机微信下线吗？ 手机微信下线服务还可以继续使用是吗？

手机微信下线，其他端就会一起下线，所以要保持登录

**Comment by 1574162728** [comment]
我也遇到这个问题

**Comment by 1574162728** [comment]
我也遇到这个问题，手机没下线其他端也没登录

**Comment by zxf969175364** [comment]
我也有这个问题, 美国的机器, 大概运行1-2天就要重新扫码登录一次, 手机登录并没有下过线, 国内机器没有这个问题吗?
