### ISSUE TITLE
在Ubuntu服务器使用Docker和Azure ChatGPT API部署报错：TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'

### ISSUE THREAD

**Issue by marshzhao** [zhayujie/chatgpt-on-wechat#1636]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

# Docker部署

已经安装好需要安装好 docker 及 docker-compose

## 1.下载 docker-compose.yml 文件

wget https://open-1317903499.cos.ap-guangzhou.myqcloud.com/docker-compose.yml

## 2.打开docker-compose.yml 修改所需配置，配置如下
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      openai.api_key: '7a4a377032594***50231e2d5fedb'
      openai.api_type: 'azure'
      MODEL: 'gpt-35-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      use_azure_chatgpt: true                                 # 是否使用Azure ChatGPT service代替openai ChatGPT service. 当设置为true时需要设置 open_ai_api_base，如 https://xxx.openai.azure.com/
      openai.api_base: 'https://**.openai.azure.com/'
      azure_deployment_id: '**Model'                         # 采用Azure ChatGPT时，模型部署名称
      azure_api_version: ''                                    # 采用Azure ChatGPT时，API版本

## 3.启动容器
docker compose up -d

## 4.扫码登陆
sudo docker logs -f chatgpt-on-wechat

显示Login successfully as XXX

### 问题描述 😯

在微信中向目标微信发送“@bot 你好”，目标微信回复“[ERROR]我现在有点累了，等会再来吧”

[INFO][2023-12-28 14:04:40][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[ERROR][2023-12-28 14:04:40][chat_gpt_bot.py:155] - [CHATGPT] Exception: InvalidRequestError.__init__() missing 1 required positional argument: 'param'
Traceback (most recent call last):
  File "/app/bot/chatgpt/chat_gpt_bot.py", line 123, in reply_text
    response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 113, in __prepare_create_request
    url = cls.class_url(engine, api_type, api_version)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 37, in class_url
    raise error.InvalidRequestError(
TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'
[INFO][2023-12-28 14:04:40][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@e83531bb7f902de21f9c631a19a22f2ad115fb5318518ac52d7100f4bf310b30

### 终端日志 📒

```log
<此处粘贴终端日志>无
```

**Comment by marshzhao** [comment]
大佬们能否给一个在Ubuntu服务器使用Docker和Azure ChatGPT API部署Cow的docker-compose.yml。

**Comment by Game-zy** [comment]
大佬们能否给一个在Ubuntu服务器使用Docker和Azure ChatGPT API部署Cow的docker-compose.yml。

同求

**Comment by 13419879072** [comment]
遇到相同的问题   有解决么？

**Comment by hcxiaoliu** [comment]
我配的 OPEN_AI_API_BASE  OPEN_AI_API_KEY 我的key和url 配置过其他gpt应用都是OK的  
我的代理都是通的  他也是报同样的错误  

chatgpt-on-wechat  | [ERROR][2024-03-07 09:50:52][chat_gpt_bot.py:155] - [CHATGPT] Exception: Unknown request URL: POST /vi/chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/app/bot/chatgpt/chat_gpt_bot.py", line 123, in reply_text
chatgpt-on-wechat  |     response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
![Uploading 企业微信截图_20240307175953.png…]()

**Comment by hcxiaoliu** [comment]
OPEN_AI_API_BASE 我弄得 是http://ip+端口

**Comment by raozhiyong11** [comment]
通样的问题，请问解决了吗？

**Comment by 6vision** [comment]
azure对话相关配置：
{
"model": "",
"open_ai_api_key": "8d31dbcddddfa5c325cb362c24e2",
"open_ai_api_base": "https://xxxxx-ai.openai.azure.com/",

"use_azure_chatgpt": true,
"azure_deployment_id": "orange-gpt-4",
}

测试可以正常对话
