### ISSUE TITLE
语音识别直接使用openai，无法识别

### ISSUE THREAD

**Issue by xinggonglie** [zhayujie/chatgpt-on-wechat#1638]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

印度服务器，ubuntu系统，git clone之后，安装完依赖，使用中转api，https://api.gptapi.us。
1.语音识别填“openai”，发送语音，无法识别，日志如下。
2.安装ffmpeg espeak，语音识别填“google”，gpt-3.5-turbo模型，语音信息，只有文字回复，且回复信息“[ERROR]"开头，换成gpt-4模型，可以正常使用语音信息

### 问题描述 😯

印度服务器，ubuntu系统，git clone之后，安装完依赖，使用中转api，https://api.gptapi.us。
1.语音识别填“openai”，发送语音，无法识别，日志如下。
2.安装ffmpeg espeak，语音识别填“google”，gpt-3.5-turbo模型，语音信息，只有文字回复，且回复信息“[ERROR]"开头，换成gpt-4模型，可以正常使用语音信息

### 终端日志 📒

```log
<Start auto replying.
[INFO][2023-12-29 14:33:57][bridge.py:49] - create bot openai for voice_to_text
[INFO][2023-12-29 14:33:58][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我暂时还无法听清您的语音，请稍后再试吧~), receiver=@ddd99185cc22fbb68d887462b0960eceaa7c0a6b8579c3d9b8e0a49fd8ae9643
[INFO][2023-12-29 14:34:15][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我暂时还无法听清您的语音，请稍后再试吧~), receiver=@ddd99185cc22fbb68d887462b0960eceaa7c0a6b8579c3d9b8e0a49fd8ae9643
^C[INFO][2023-12-29 14:35:23][app.py:17] - signal 2 received, exiting...>
```

**Comment by xinggonglie** [comment]
只有gpt-3.5-turbo模型有问题，其他gpt-3.5-turbo-1106，gpt-3.5-turbo-16k都以正常发语音

**Comment by Miykah** [comment]
> 只有gpt-3.5-turbo模型有问题，其他gpt-3.5-turbo-1106，gpt-3.5-turbo-16k都以正常发语音

请问你解决了吗？我试了下gpt-3.5-turbo和gpt-3.5-turbo-16k都无法识别语音。

**Comment by 5high** [comment]
我用的Gemini 也无法正常识别语音

**Comment by xinggonglie** [comment]
openai的whisper模型识别成功率太低了，改成使用Google语音识别

**Comment by xinggonglie** [comment]
> 试了下gpt-3.5-turbo和gpt-3.5-turbo-16k都无法

使用Google（不需要key）或者其他的语音识别api（需要key），openai的语音识别不行

**Comment by sparkssssssss** [comment]
> > 试了下gpt-3.5-turbo和gpt-3.5-turbo-16k都无法
> 
> 使用Google（不需要key）或者其他的语音识别api（需要key），openai的语音识别不行

请教下,怎么修改为google语音识别?

**Comment by taozhiyuai** [comment]
> > 试了下gpt-3.5-turbo和gpt-3.5-turbo-16k都无法
> 
> 使用Google（不需要key）或者其他的语音识别api（需要key），openai的语音识别不行

google的语音识别和合成是免费的吗?

**Comment by wangluyichen** [comment]
同样的问题啊。。困扰很久了

**Comment by wangluyichen** [comment]
> > 试了下gpt-3.5-turbo和gpt-3.5-turbo-16k都无法
> 
> 使用Google（不需要key）或者其他的语音识别api（需要key），openai的语音识别不行

如何使用谷歌的语音呢？需要在配置文件中添加 什么？

**Comment by 6vision** [comment]
语音相关参数配置都在[config.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)，
