### ISSUE TITLE
扫码反复提示Log in time out

### ISSUE THREAD

**Issue by phynero** [zhayujie/chatgpt-on-wechat#164]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
Please scan the QR code to log in.
Please press confirm on your phone.
Log in time out, reloading QR code.
Getting uuid of QR code.
Downloading QR code.

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by phynero** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/issues/8

**Comment by phynero** [comment]
汗

**Comment by bboychencan** [comment]
前置确认
用的是自己的macbook，国内网络环境，使用了vpn翻墙
python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装

在已有 issue 中未搜索到类似问题
[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题 
问题描述
简要说明、截图、复现步骤等，也可以是需求或想法

前面步骤完成后，正常工作，但电脑如果隔一段时间不管的话就会锁屏然后log显示LOGOUT
有点怀疑是锁屏的原因，但是在系统设置里已经勾掉了自动锁屏的选项

终端日志 (如有报错)
edc09e531250cae36ffbfb7368b63ecd0736c794902296c7487
[INFO][2023-02-10 22:03:39][open_ai_bot.py:20] - [OPEN_AI] query=哪去啦
[INFO][2023-02-10 22:03:45][open_ai_bot.py:51] - [OPEN_AI] reply=不用担心，我很快就会完成。
[INFO][2023-02-10 22:03:45][wechat_channel.py:103] - [WX] sendMsg=不用担心，我很快就会完成。, receiver=@ffeb5d94fb71fedc09e531250cae36ffbfb7368b63ecd0736c794902296c7487
[INFO][2023-02-10 22:03:54][open_ai_bot.py:20] - [OPEN_AI] query=给我画的微信头像呢
[INFO][2023-02-10 22:04:00][open_ai_bot.py:51] - [OPEN_AI] reply=不用急，我正在设计你的微信头像，如果你想要的话，我会尽快给你一个满意的头像。
[INFO][2023-02-10 22:04:00][wechat_channel.py:103] - [WX] sendMsg=不用急，我正在设计你的微信头像，如果你想要的话，我会尽快给你一个满意的头像。, receiver=@ffeb5d94fb71fedc09e531250cae36ffbfb7368b63ecd0736c794902296c7487
LOG OUT!

环境
操作系统类型 (Mac/Windows/Linux)：Mac
Python版本 ( 执行 python3 -V )：Python 3.10.9 
pip版本 ( 依赖问题此项必填，执行 pip3 -V)：pip 22.3.1

**Comment by bboychencan** [comment]
搭建这个服务不需要vpn吗，完全用国内网络就可以吗？

**Comment by zhayujie** [comment]
> 搭建这个服务不需要vpn吗，完全用国内网络就可以吗？

是的
