### ISSUE TITLE
无法启用tool工具

### ISSUE THREAD

**Issue by WDAhyhy** [zhayujie/chatgpt-on-wechat#1640]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用#auth指令进入管理者模式之后，#plist后显示的有tool工具且未启用，#enablep tool后启动失败

### 问题描述 😯

无法初始化tool，tool整个文件夹是clone过来的，从未修改

### 终端日志 📒

```log
<此处粘贴终端日志>
```
[INFO][2023-12-31 13:05:52][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[INFO][2023-12-31 13:05:52][__init__.py:29] - [visual_dl] init failed, error_info: ModuleNotFoundError("No module named 'torch'")
[WARNING][2023-12-31 13:05:52][plugin_manager.py:148] - Failed to init TOOL, diabled. Did not find llm_api_key, please add an environment variable `LLM_API_KEY` which contains it, or pass  `llm_api_key` as a named parameter.
[INFO][2023-12-31 13:05:52][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件开启失败), receiver=@9fe959cdc24f25fa65be839d90a05cc1c91d05a06a1612b2ee8de6f3b052775d

**Comment by fatbun** [comment]
同样遇到这个问题

**Comment by enjoyour** [comment]
同样遇到这个问题,请问解决了吗?

**Comment by jiandamplus** [comment]
怎么解决的，大佬

**Comment by linccee** [comment]
同样的问题，关键是LLM_API_KEY都配置了，咋还是找不到

**Comment by ouyanghuangzheng** [comment]
使用app.py启动试试，是不是用其它方式启动导致获取不到配置了

**Comment by xingxinag** [comment]
我也一样

**Comment by xingxinag** [comment]
![Screenshot_2025-01-02-11-04-12-850_com tencent mm](https://github.com/user-attachments/assets/244798c6-433d-48e9-841c-af6f6b206d0e)
[tool.py.txt](https://github.com/user-attachments/files/18287470/tool.py.txt)
是他代码有问题，我解决了后缀改一下直接替换即可
