### ISSUE TITLE
RAG support

### ISSUE THREAD

**Issue by WQL782795** [zhayujie/chatgpt-on-wechat#1645]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

I don’t seem to have found any relevant support for RAG. Will you consider adding support for some vector databases and the functions of RAG in the future?

**Comment by 6vision** [comment]
可以使用linkai的服务，参考[快速开始](https://docs.link-ai.tech/platform/quick-start)，[微信接入](https://docs.link-ai.tech/platform/link-app/wechat)

**Comment by kuangdd2024** [comment]
这个项目可以作为参考，已经实现了RAG功能，用作对话记录的搜索，从而实现记忆提取。

项目：
https://github.com/kuangdd2024/wechatgpt-agent

About：
chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。
