### ISSUE TITLE
中转API，回复内容提示【ERROR】docker部署的如何解决？

### ISSUE THREAD

**Issue by lizhe0326** [zhayujie/chatgpt-on-wechat#1647]
你这个api返回的tokens消耗为0，所以chatgpt-on-wechat认为接口返回有错误，所以有[ERROR]的提示。

解决办法：
修改`bot/chatgpt/chat_gpt_bot.py`的87、88、89行，让它tokens为0时不报错就好了。
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/11461928/0974cc0a-d7d4-47d0-8ed6-2bfe6351d65a)

_Originally posted by @yushuaige in https://github.com/zhayujie/chatgpt-on-wechat/issues/1323#issuecomment-1665339739_

**Comment by lepingzhang** [comment]
按照步骤修改后报错（群晖docker运行，尝试了映射文件也是这个问题）：
<html>
<body>

2024/01/06 15:22:17 | stdout | TypeError: can only concatenate list (not "str") to list
-- | -- | --
2024/01/06 15:22:17 | stdout | reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
2024/01/06 15:22:17 | stdout | File "/app/channel/chat_channel.py", line 257, in _decorate_reply
2024/01/06 15:22:17 | stdout | reply = self._decorate_reply(context, reply)
2024/01/06 15:22:17 | stdout | File "/app/channel/chat_channel.py", line 172, in _handle
2024/01/06 15:22:17 | stdout | result = self.fn(*self.args, **self.kwargs)
2024/01/06 15:22:17 | stdout | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024/01/06 15:22:17 | stdout | Traceback (most recent call last):
2024/01/06 15:22:17 | stdout | [ERROR][2024-01-06 07:22:17][chat_channel.py:299] - Worker return exception: can only concatenate list (not "str") to list


</body>
</html>

**Comment by ImBatman52** [comment]
请问如果是在Railway部署的，这个中转API的[ERROR]提示的问题如何解决？谢谢！

**Comment by infrost** [comment]
同docker同报错，看这个报错
 stdout | reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "") 
 我怀疑是single_chat_reply_prefix问题导致的，直接删掉环境变量中的single_chat_reply_prefix整个变量，问题解决。

**Comment by 6vision** [comment]
> 按照步骤修改后报错（群晖docker运行，尝试了映射文件也是这个问题）：
> 
> 2024/01/06 15:22:17 | stdout | TypeError: can only concatenate list (not "str") to list -- | -- | -- 2024/01/06 15:22:17 | stdout | reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "") 2024/01/06 15:22:17 | stdout | File "/app/channel/chat_channel.py", line 257, in _decorate_reply 2024/01/06 15:22:17 | stdout | reply = self._decorate_reply(context, reply) 2024/01/06 15:22:17 | stdout | File "/app/channel/chat_channel.py", line 172, in _handle 2024/01/06 15:22:17 | stdout | result = self.fn(*self.args, **self.kwargs) 2024/01/06 15:22:17 | stdout | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run 2024/01/06 15:22:17 | stdout | Traceback (most recent call last): 2024/01/06 15:22:17 | stdout | [ERROR][2024-01-06 07:22:17][chat_channel.py:299] - Worker return exception: can only concatenate list (not "str") to list

这是参数设置的有问题
