### ISSUE TITLE
新拉的微信群，无法触发api

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#165]
### 前置确认

1. 运行于国内网络环境，使用了vpn
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
加了这个助手好友以后可以单独聊天，但是如果拉一个新的小群的话，@助手没有响应
有一点值得注意的是，我的助手设置的是可以免验证同意好友申请。所以我申请加它好友就自动通过了。

### 终端日志 (如有报错)
无报错，正常的对话都可以有回复，但是新拉群的话，没有触发api
log里[OPEN_AI] query= 没有出现对应的message

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：mac
 - Python版本  ( 执行 `python3 -V` )：               3.10.9       
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.3.1

**Comment by bboychencan** [comment]
设置了白名单    "group_name_white_list": ["ALL_GROUP"],
多试了几次，基本找到了原因，新拉的群，如果不设置群名，@bot 一律没有触发。
但是一旦设置了一个任意的群名，就可以触发了，哪怕之后再改为空群名，也一样可以触发。 
应该是个bug，如果设置了白名单ALL_GROUP，则要涵盖新拉的群的默认群名的情形

**Comment by zhayujie** [comment]
>

**Comment by zhayujie** [comment]
> 设置了白名单 "group_name_white_list": ["ALL_GROUP"], 多试了几次，基本找到了原因，新拉的群，如果不设置群名，@bot 一律没有触发。 但是一旦设置了一个任意的群名，就可以触发了，哪怕之后再改为空群名，也一样可以触发。 应该是个bug，如果设置了白名单ALL_GROUP，则要涵盖新拉的群的默认群名的情形

**Comment by zhayujie** [comment]
已解决

**Comment by bboychencan** [comment]
依然没有解决
设置了白名单 "group_name_white_list": ["ALL_GROUP"],
新拉的群，如果不修改群名称依然无回复
