### ISSUE TITLE
百度文心chatlaw模型返回336000

### ISSUE THREAD

**Issue by xrggen** [zhayujie/chatgpt-on-wechat#1651]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/chatlaw模型，稳定复现返回{'error_code': 336000, 'error_msg': 'Internal error', 'id': 'as-x7f25ipx49'}

个人手动构建请求是可以正常返回的
![17ef276db520ab971e505c8096c6eea](https://github.com/zhayujie/chatgpt-on-wechat/assets/48742166/dfdf6968-7c55-41b5-a22d-438016e5b9c5)

### 问题描述 😯

百度文心场景使用chatlaw模型错误返回

### 终端日志 📒

[DEBUG][2024-01-05 10:49:46][chat_channel.py:186] - [WX] ready to handle context: type=TEXT, content=Test
[INFO][2024-01-05 10:49:46][baidu_wenxin.py:28] - [BAIDU] query=Test
[DEBUG][2024-01-05 10:49:46][session_manager.py:70] - prompt tokens used=4
[INFO][2024-01-05 10:49:46][baidu_wenxin.py:66] - [BAIDU] model=chatlaw
[INFO][2024-01-05 10:49:47][baidu_wenxin.py:82] - [BAIDU] response text={'error_code': 336000, 'error_msg': 'Internal error', 'id': 'as-pvj2b5gaq8'}
[WARNING][2024-01-05 10:49:47][baidu_wenxin.py:94] - [BAIDU] Exception: 'result'
[ERROR][2024-01-05 10:49:47][chat_channel.py:299] - Worker return exception: 'total_tokens'
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat-law/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat-law/channel/chat_channel.py", line 189, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/root/chatgpt-on-wechat-law/channel/channel.py", line 37, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt-on-wechat-law/bridge/bridge.py", line 64, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/root/chatgpt-on-wechat-law/bot/baidu/baidu_wenxin.py", line 41, in reply
    result["total_tokens"],
KeyError: 'total_tokens'

**Comment by 1461381460** [comment]
这个属于百度的问题，参考https://cloud.baidu.com/doc/WENXINWORKSHOP/s/tlmyncueh

**Comment by 6vision** [comment]
最新代码不存在这个KeyError: 'total_tokens' 报错了，不过chatlaw不是项目默认支持的模型，需要自己适配
