### ISSUE TITLE
railway部署时 报错

### ISSUE THREAD

**Issue by this-me0** [zhayujie/chatgpt-on-wechat#1653]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

按着文档走的

### 问题描述 😯

按照readme里面的描述，选择用railway一件部署企业微信应用版本，跳转到railway填写完成企业配置信息，点击部署后，等待一段时间，然后会提示如下错误
Oh No!

Looks like something went wrong and the train derailed

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
railway现在已经不支持企业微信应用的部署了，很早之前从文档移除了

**Comment by toolazytoname** [comment]
我搜到之前的issue 是能成功部署的，是什么原因导致不支持呢
