### ISSUE TITLE
Apilot插件中的摸鱼功能好像不能用了

### ISSUE THREAD

**Issue by 404AHAO** [zhayujie/chatgpt-on-wechat#1654]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在微信中发送'摸鱼'回复的是 moyu_calendar请求失败

### 问题描述 😯

公众号中测试也出现了同样的问题

### 终端日志 📒

```log
[ERROR][2024-01-06 05:58:46][Apilot.py:414] - 请求失败，错误信息：Expecting value: line 1 column 1 (char 0)
[ERROR][2024-01-06 05:58:46][Apilot.py:414] - moyu_calendar请求失败，错误信息：请求失败
[INFO][2024-01-06 05:58:46][wechat_channel.py:191] - [WX] sendMsg=Reply(type=TEXT, content=[Chat_Ai] moyu_calendar请求失败), receiver=@fd8618ee320f8a5b0f6fd6ecd484fa7261d0a4351112d3326b063a4b0e668903
```

**Comment by 6vision** [comment]
更新插件到最新即可
