### ISSUE TITLE
[ERROR][2024-01-08 11:22:35][app.py:52] - App startup failed! [ERROR][2024-01-08 11:22:35][app.py:53] - 'wxsid'

### ISSUE THREAD

**Issue by keithchen2017** [zhayujie/chatgpt-on-wechat#1655]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码登录号后报错

### 问题描述 😯

扫码登录号后报错

### 终端日志 📒

```log
扫码登录号后报错
<此处粘贴终端日志>
```

**Comment by yansuang** [comment]
我也是一样的问题，有没有大佬教一下

**Comment by GreysonHYH** [comment]
我也遇到了这个问题，情况一模一样。

**Comment by woodyxiong** [comment]
实名认证之后可以+1
