### ISSUE TITLE
使用第三方域名后，但是默认使用的GPT3的模型

### ISSUE THREAD

**Issue by lzx4627** [zhayujie/chatgpt-on-wechat#1656]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

MODEL: 'gpt-4'
OPEN_AI_API_KEY: 'xxxx'
OPEN_AI_API_BASE: 'http://xxxxx:8080/v1'

### 问题描述 😯

使用第三方域名后，提问返回的结果默认使用的GPT3的模型

### 终端日志 📒

```log
[bot] 我是基于OpenAI的GPT-3模型。GPT是"Generative Pretrained Transformer"的缩写，这是一种自然语言处理（NLP）的深度学习模型，用于理解和生成人类语言。GPT-3是该系列模型的最新版本。
```

**Comment by lzx4627** [comment]
问：bot 你的最新知识库是什么时间
答：[bot] 作为一个开源的人工智能模型，我并不能实时更新或获取新的数据和知识。我所知的所有信息都是基于我最后一次训练时的数据，这通常是在训练我时使用的大型文本数据集中。在我被创建的时候，最新的信息大约是到2021年为止的。因此，对于2021年之后的信息，我可能无法提供最准确的答案。

**Comment by QAbot-zh** [comment]
早期版本的gpt4模型是不知道自己是gpt4的

**Comment by Fnlyu** [comment]
解决了吗，我遇到同样的问题了

**Comment by 6vision** [comment]
模型受限于训练的数据不具有实时性，不能依据模型的回答来看是使用的什么模型
