### ISSUE TITLE
画画的接口是否可以优化

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#166]
有些人爱用“给。。。画。。。”的方式画画， 或者“把上面的。。。画出来”。 这种交互方式比较自然，但是bot识别不出来。
如果能够用自然的方法下指令会比较好

**Comment by defamilo** [comment]
你把config.json里画画的触发关键字改下，当成默认前缀就行，这个项目里对于画画api触发的场景，会去掉匹配的开头的字再调用chatai的绘画接口。

比如你按默认配置说：
画一只彩色的猪

后台看到调用api的关键词是:
一只彩色的猪

因此你告诉其他人想让他画画可以这样描述：
画给狗子画上螃蟹的钳子

后台调用api会下发：
给狗子画上螃蟹的钳子
