### ISSUE TITLE
对接公众号不能连续回话

### ISSUE THREAD

**Issue by amielan027** [zhayujie/chatgpt-on-wechat#1661]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

发送消息给公众号，第一次能回复，连续对话就不会有回文了

### 问题描述 😯

发送消息给公众号，第一次能回复，连续对话就不会有回文了

### 终端日志 📒

```log
[INFO][2024-01-10 15:24:33][link_ai_bot.py:111] - [LINKAI] reply=你好！有什么我可以帮助你的吗？如果你有任何问题或者需要了解的内容，都可以告诉我。我会尽力回答你的。, total_tokens=482
[INFO][2024-01-10 15:24:33][link_ai_bot.py:318] - [LINKAI] knowledge base, search_hit=True, first_similarity=0.8133
[INFO][2024-01-10 15:24:33][wechatmp_channel.py:85] - [wechatmp] text cached, receiver oWbJIxM3XQjZ-92HkcDrgGRBa6Ic
你好！有什么我可以帮助你的吗？如果你有任何问题或者需要了解的内容，都可以告诉我。我会尽力回答你的。
[INFO][2024-01-10 15:24:33][passive_reply.py:153] - [wechatmp] Request 3 do send to oWbJIxM3XQjZ-92HkcDrgGRBa6Ic 24407887530646869: 你好
你好！有什么我可以帮助你的吗？如果你有任何问题或者需要了解的内容，都可以告诉我。我会尽力回答你的。
175.24.212.195:54156 - - [10/Jan/2024 15:24:33] "HTTP/1.1 POST /wx" - 200 OK
[ERROR][2024-01-10 15:24:33][passive_reply.py:210] - 24407887530646869
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechatmp/passive_reply.py", line 126, in POST
    channel.request_cnt.pop(message_id)
KeyError: 24407887530646869
81.69.103.236:9496 - - [10/Jan/2024 15:24:33] "HTTP/1.1 POST /wx" - 200 OK
[ERROR][2024-01-10 15:24:33][passive_reply.py:210] - 24407887530646869
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechatmp/passive_reply.py", line 126, in POST
    channel.request_cnt.pop(message_id)
KeyError: 24407887530646869

```

**Comment by gaohuaigh** [comment]
同问，我的和你基本上一样，也是这个报错。然后我在公众号后台基本设置的时候，域名也设置不了。我这边看到的是，消息能收，但是生成回答后，返不回来。比如我问天气报错如下：

* 2024-01-20：小雨转多云，4~10℃，无持续风向<3级，空气质量良。
* 2024-01-21：晴转小雨，1~8℃，无持续风向<3级，空气质量优。
81.69.103.236:8046 - - [15/Jan/2024 22:28:24] "HTTP/1.1 POST /wx" - 200 OK
[ERROR][2024-01-15 22:28:24][passive_reply.py:210] - 24414438626426755
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechatmp/passive_reply.py", line 126, in POST
    channel.request_cnt.pop(message_id)
KeyError: 24414438626426755
175.24.212.195:53426 - - [15/Jan/2024 22:28:24] "HTTP/1.1 POST /wx" - 200 OK

**Comment by amielan027** [comment]
有没有大佬能帮忙看看，都是返回服务器有消息，但是不能往微信公众号推了

**Comment by LeiXH** [comment]
大佬解决问题了吗，同样的问题

**Comment by LeiXH** [comment]
可以看一下请求日志，有时间一个消息打印了两个request

**Comment by 6vision** [comment]
项目最新代码应该没这个问题，可以试试
