### ISSUE TITLE
容器root密码

### ISSUE THREAD

**Issue by shantzhou** [zhayujie/chatgpt-on-wechat#1662]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

以非root运行 想更改一些东西没有权限

**Comment by dmmmmdJack** [comment]
好像连sudo命令都没有   切换不了

**Comment by lyy0755** [comment]
docker exec -it --user root ID bash
