### ISSUE TITLE
openai语音识别和语音生成都用不了了

### ISSUE THREAD

**Issue by lewisliuyi** [zhayujie/chatgpt-on-wechat#1666]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

正常运行，以前都可以，现在都不行了。

### 问题描述 😯

openai的语音识别会一直运行直到超时，但是不出结果。
openai的语音生成会产生一个mp3文件，但是打不开。

### 终端日志 📒

```log
create bot openai for voice_to_text
[INFO][2024-01-12 22:50:05][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我暂时还无法听清您的语音，请稍后再试吧~), receiver=@04e56c846d9bf4f61d1c115854ffcf3f5d9d0a0c22f2ca98141f754b5025959d
```log
create bot openai for text_to_voice
[INFO][2024-01-12 22:46:30][openai_voice.py:53] - [OPENAI] text_to_Voice success
[INFO][2024-01-12 22:46:31][wechat_channel.py:197] - [WX] sendFile=tmp/20240112224630220.mp3,
```

**Comment by zhayujie** [comment]
已合并，看下是否解决

**Comment by zhayujie** [comment]
已合并，看下是否解决
