### ISSUE TITLE
openai的接口返回出错的时候没有消息

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#167]
有时候用户给一些指令，后台log会报”max tokens 4023"之类的，或者说"Your request was rejected as a result of our safety system. Your prompt may contain text that is not allowed by our safety system." 这个时候bot就没有响应，能否让bot处理一下这种情况，至少让人知道无法获得返回请求，而不是完全没消息。

**Comment by zhayujie** [comment]
是最新版本吗， 有报错会回复 “请再问我一次吧”

**Comment by bboychencan** [comment]
拉了最新版本，如果发的请求带有色情色彩的话，后台会报错，但是依然不返回消息

**Comment by zhayujie** [comment]
> 拉了最新版本，如果发的请求带有色情色彩的话，后台会报错，但是依然不返回消息

不能发敏感内容，openai会限制

**Comment by bboychencan** [comment]
'不能发敏感内容，openai会限制' 我们很难控制用户是否发这样的东西，如果用户发了，openai限制，能不能在我们这边做一些处理，给用户一个返回信息，比如”不要发这类的消息“之类的。 不然用户可能会以为死机了，就不玩了
