### ISSUE TITLE
Gemini是否可以加入代理呢

### ISSUE THREAD

**Issue by single228758** [zhayujie/chatgpt-on-wechat#1670]
可以解决IP问题不能使用![Screenshot_20240115-013016.png](https://github.com/zhayujie/chatgpt-on-wechat/assets/122099583/03f6e7bc-faf0-44a6-9550-588e42664edd)

**Comment by zhayujie** [comment]
gemini的sdk里面没有proxy和 api_base类似的参数提供

**Comment by single228758** [comment]
> gemini的sdk里面没有proxy和 api_base类似的参数提供

> [这个是链接地址](https://simonmy.com/posts/%E4%BD%BF%E7%94%A8vercel%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86google-palm-api.html)，是把原来的API地址修改成代理地址
Google原生API：
```

curl https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?key={YOUR_KEY} \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{ "contents":[
   { "parts":[{"text": "Hi"}]}
   ]
}'

curl https://https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?key={YOUR_KEY}&alt=sse \
   -H 'Content-Type: application/json' \
   --no-buffer \
   -d '{ "contents":[
         {"role": "user",
            "parts":[{"text": "Hi"}]
         }
         ]
      }' > response.json

```
替换Vercel域名或自定义域名:
```
curl https://{YOUR_DOMAIN}/v1/models/gemini-pro:generateContent?key={YOUR_KEY} \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{ "contents":[
   { "parts":[{"text": "Hi"}]}
   ]
}'

curl https://{YOUR_DOMAIN}/v1/models/gemini-pro:streamGenerateContent?key={YOUR_KEY}&alt=sse \
   -H 'Content-Type: application/json' \
   --no-buffer \
   -d '{ "contents":[
         {"role": "user",
            "parts":[{"text": "Hi"}]
         }
         ]
      }' > response.json

```

**Comment by lengsukq** [comment]
查了下代码，本来想通过改代码试试的，结果是通过调用模块实现的，查阅模块，只看到暴露了个api可以自定义设置，所以如果作者不改用模块，或者模块后续不开放自定义url，估计没可能实现
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/105091166/45d8652c-b814-40a9-9a7f-26b8b9ead751)

**Comment by weituotian** [comment]
试了一下，这个可能有用
https://zhuanlan.zhihu.com/p/673100444

**Comment by engigu** [comment]
试下这个
https://zhuanlan.zhihu.com/p/679115466

**Comment by shoot82003** [comment]
"open_ai_api_base": "https://api.openai.com/v1",
    "proxy": "",  # openai使用的代理
-------------------
没有找到gemini_api_base,或相关proxy的设置

-----------------
 修改后,genai.configure(api_key=self.api_key,transport='rest')
[ERROR][2024-02-26 10:20:42][google_gemini_bot.py:45] - [Gemini] fetch reply error, may contain unsafe content
[ERROR][2024-02-26 10:20:42][google_gemini_bot.py:46] - HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Max retries exceeded with url: / 
 ---------------------
 楼上的方法不会操作
 ---------------------
 希望出一期gemini设置proxy相关的
 因为gemini的key免费相比较chatgpt

**Comment by ksda9001** [comment]
修改chatgpt-on-wechat/bot/gemini/目录下google_gemini_bot.py
<img width="464" alt="2" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/56786072/f1b1c561-f048-4954-9f92-308f2307562e">
将genai.configure改为如图形式

**Comment by ksda9001** [comment]
> ```
> "open_ai_api_base": "https://api.openai.com/v1",
> "proxy": "",  # openai使用的代理
> ```
> 
> 没有找到gemini_api_base,或相关proxy的设置
> ## 修改后,genai.configure(api_key=self.api_key,transport='rest')
> [ERROR][2024-02-26 10:20:42][google_gemini_bot.py:45] - [Gemini] fetch reply error, may contain unsafe content
> [ERROR][2024-02-26 10:20:42][google_gemini_bot.py:46] - HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Max retries exceeded with url: /
> ## 楼上的方法不会操作
> 
> 希望出一期gemini设置proxy相关的 因为gemini的key免费相比较chatgpt

<img width="464" alt="2" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/56786072/0f63277b-2cca-4950-a58e-562ed2eb7425">
如图所示

**Comment by evachxji** [comment]
> google_gemini_bot

感谢分享，亲测有效，gemini访问可以走代理了

**Comment by weituotian** [comment]
好~(￣▽￣)~*
