### ISSUE TITLE
能否提供 arm 版本的 docker img？

### ISSUE THREAD

**Issue by Kaol-Fu** [zhayujie/chatgpt-on-wechat#1671]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

如题，发现 docker hub 中没有 arm 的 img，无法在 arm 的服务器中使用，是否可以提供？谢谢！

### 举例

建一个 arm 的docker hub tag？

### 动机

能过让 arm 的服务器也能够使用。

**Comment by zptqghsw** [comment]
zptqghsw/chatgpt-on-wechat:latest
dockerhub直接拉
