### ISSUE TITLE
linkai应用中的插件，与项目中的linkai插件结算问题

### ISSUE THREAD

**Issue by Namarimizu** [zhayujie/chatgpt-on-wechat#1672]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

两个问题：
1.  项目中的`linkai`插件功能正常（下称`summary`），而应用中的`谷歌搜索`和`时间`插件也正常工作，而`图像识别`不在微信端生效（在网页端正常）。也就是，对于微信端，仅开启应用中的`图像识别`时发送图片没有回应，仅开启项目中的`summary`时有效。

2.  设置的角色个性并不会作用于`summary`中图像识别的结果，而诡异的是**有时**会作用于`图像识别`，这取决于发送图片时附带的文本（微信端也并不能这么做）：
- 仅发送图片，个性未体现：

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38524387/ae651b90-5833-4b67-8843-a06240aa577c)
- 发送图片，配文「你看看这个」（总之要明确提到该 bot 本人或人设），个性体现：

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38524387/9119c853-7483-4fb8-8efb-cc444d331c82)

- 作为对比，发送图片，配文「看看这个」，个性未体现：
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38524387/6a12ec96-03d8-4e16-9f5a-c9f9964c0e11)

如果（应该是我这边的 bug 吧）`图像识别`以这种方法对微信端生效了，微信端发送的图片和文本仍然会被分开处理，同样无济于事。要是`summary`能有加入 context 的选项就好了（无用需求+1

### 问题描述 😯

-

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
微信端发送图片后跟随一句问题就能触发图像识别插件， 需要更新至1.5.2版本之后
