### ISSUE TITLE
企微个人号 运行app.py后，企微桌面版会闪退报错

### ISSUE THREAD

**Issue by Wesley806** [zhayujie/chatgpt-on-wechat#1674]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

<img width="976" alt="截屏2024-01-15 15 24 25" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/67988642/31a914e3-e627-45d6-8b2c-5fb1daed7116">

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Fnckerpoi** [comment]
请问ntwork包哪里还能下载？

**Comment by lei195827** [comment]
> 请问ntwork包哪里还能下载？

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple ntwork

**Comment by Fnckerpoi** [comment]
> > 请问ntwork包哪里还能下载？
> 
> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple ntwork

ERROR: Could not find a version that satisfies the requirement ntwork (from versions: none)
ERROR: No matching distribution found for ntwork

应该是全面封杀了吧

**Comment by 7tinghua** [comment]
同求一个ntwork的包，不然企微运行不起来，谢谢了！！
