### ISSUE TITLE
是否可以增加聊天记录导出或备份功能？

### ISSUE THREAD

**Issue by do-one-thing-to-well** [zhayujie/chatgpt-on-wechat#1677]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

使用了Summary插件，发现是总结的功能，与我所期望的不一致。

### 动机

如果有聊天记录导出的功能，可以做模型训练或者是备份。

**Comment by dreammax2010** [comment]
+1 ， 再等等。。不行的话打算自己去日志里面解析了

**Comment by 6vision** [comment]
隐私考虑，应该不会支持的
