### ISSUE TITLE
可以增加使用cookie来调用，这样就可以免费了，而且还能使用bing

### ISSUE THREAD

**Issue by hsx-123** [zhayujie/chatgpt-on-wechat#1681]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

可以增加使用cookie来调用，这样就可以免费了，而且还能使用bing

### 举例

可以增加使用cookie来调用，这样就可以免费了，而且还能使用bing

### 动机

可以增加使用cookie来调用，这样就可以免费了，而且还能使用bing

**Comment by single228758** [comment]
自己搭建个PandoraNext

**Comment by 6vision** [comment]
不稳定，维护也麻烦，建议使用官方api
