### ISSUE TITLE
建议支持GLM4

### ISSUE THREAD

**Issue by 2259512750** [zhayujie/chatgpt-on-wechat#1684]

**Comment by YYForReal** [comment]
现在已经支持了，在config.json配置项那里修改model，有下面的内容就可以了。
```
  "model": "glm-4",
  "zhipu_ai_api_key": "glm4的API key",
  "zhipu_ai_api_base": "https://open.bigmodel.cn/api/paas/v4",
```

**Comment by qazxswaaa** [comment]
@YYForReal 但是这种方法能连接上自己在智谱平台上创建的应用吗，感觉在平台上搭的agent和连到微信里的问答机器人回复差异很大，

**Comment by YYForReal** [comment]
> @YYForReal 但是这种方法能连接上自己在智谱平台上创建的应用吗，感觉在平台上搭的agent和连到微信里的问答机器人回复差异很大，

最近没看智谱平台搭建的agent应用能否导出成api，如果可以的话理论上是可以连接上的。

**Comment by qazxswaaa** [comment]
@YYForReal 我参考的这个#1158，有什么方法能连接上应用的api吗

**Comment by qazxswaaa** [comment]
@YYForReal 我参考的这个#1758，有什么方法能连接上应用的api吗
