### ISSUE TITLE
疑似机器人在群里@人时没有了提醒，

### ISSUE THREAD

**Issue by cm04918** [zhayujie/chatgpt-on-wechat#1691]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在群里@机器人，机器人回复时会@我。而@我时是没有有人@我的提醒！
![微信图片_20240119080046](https://github.com/zhayujie/chatgpt-on-wechat/assets/131333293/188a0b7c-2881-44ab-acec-ea8346fb0b11)
![微信图片_20240119080100](https://github.com/zhayujie/chatgpt-on-wechat/assets/131333293/d1330814-c4ca-4a0a-99cc-edc88569c9be)
正常情况是应该有被@的提醒的

### 问题描述 😯

在群里@机器人，机器人回复时会@我。而@我时是没有有人@我的提醒！

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Candy555** [comment]
同问，我看好像需要通过 search_chatrooms()函数，获取群聊成员list后，找到对应的成员@，才能提醒，但是试了一下，调用search_chatrooms()返回的list总是空的，没法实现，想知道这个问题应该怎么解决~

**Comment by 6vision** [comment]
是的，假艾特，itchat协议应该是没办法实现真实的艾特效果
