### ISSUE TITLE
群聊bot没反应，程序死机了，内存中没有退出

### ISSUE THREAD

**Issue by willzzq** [zhayujie/chatgpt-on-wechat#1692]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1. 今晚在群里@了一下机器人，没反应。
2. 用tail检查日志，停留在今天中午12:21
3. 杀死进程，诚信启动，恢复

### 问题描述 😯

日志里没有奔溃的debug信息，无从查到死机原因

### 终端日志 📒

```log
[INFO][2024-01-19 12:21:16][youhui_bot.py:107] - [YOUHUI] reply=我是科大讯飞自主研发的认知智能大模型。
[INFO][2024-01-19 12:21:16][wechat_channel.py:191] - [WX] sendMsg=Reply(type=TEXT, content=@高山流水
我是科大讯飞自主研发的认知智能大模型。), receiver=@@20b398a78097886a60a0fe99fdacf9728d3d959da28c6b526b0568619bcee4f5
[INFO][2024-01-19 19:18:15][config.py:254] - [INIT] load config: {'channel_type': 'wx', 'model': 'youhui', 'use_azure_chatgpt': False, 'open_ai_api_key': '6092d693b681405e8ee782d804870f3c', 'open_ai_api_base': 'https://xiaohuiproplus.openai.azure.com', 'text_to_image': 'dall-e-2', 'voice_to_text': 'openai', 'text_to_voice': 'openai', 'proxy': '', 'hot_reload': False, 
```

**Comment by BoscoCJ** [comment]
找到问题了吗？我也是一直没有回复，后台log没输出

**Comment by etfromchina** [comment]
有一种可能，就是服务器内存或者存储溢出，没有报错。

**Comment by JimWuuu** [comment]
我也是，请问找到解决方案了吗

**Comment by 6vision** [comment]
可能是 协议不稳定的原因，暂时无法解决，如果发现其他问题导致的，可以一起讨论
