### ISSUE TITLE
语音回复为什么我在微信中使用，然后回复的是mp3文件呀，可以让他回复的是微信语音吗，求大佬帮忙解决一下

### ISSUE THREAD

**Issue by He0607** [zhayujie/chatgpt-on-wechat#1699]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

![1](https://github.com/zhayujie/chatgpt-on-wechat/assets/144927814/18d43d82-2889-49f3-8dbf-010f9dba7b43)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Matsuzaka2** [comment]
得用wechaty

**Comment by He0607** [comment]
@Matsuzaka2 要如何使用wechaty呀

**Comment by caizhuoyue77** [comment]
> 得用wechaty

同问大佬，怎么开wechaty模式呢？有wechaty的key了～

**Comment by liyf1** [comment]
> > 得用wechaty
> 
> 同问大佬，怎么开wechaty模式呢？有wechaty的key了～

channel_type = wxy
<img width="554" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/49024327/5a2d5090-5505-4093-ba22-2c664d1d564a">

**Comment by bkzy333** [comment]
同问，如何让chatgpt-on-wechat回复的是微信语音，而不是mp3文件，wechaty该如何设置和使用呢？
