### ISSUE TITLE
不懂就问,现在CoW支持dify平台了吗

### ISSUE THREAD

**Issue by Matsuzaka2** [zhayujie/chatgpt-on-wechat#1700]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 动机

dify真的很好用,还能对接notion,但好像接不上CoW？

**Comment by sisuad** [comment]
这里大佬提了一个pr，你可以拉过去试试，而且支持最新的agent了
https://github.com/zhayujie/chatgpt-on-wechat/pull/1731 @hanfangyuan4396

**Comment by Fone520** [comment]
> 这里大佬提了一个pr，你可以拉过去试试，而且支持最新的agent了 #1731 @hanfangyuan4396

太棒了！！
