### ISSUE TITLE
这个我在微信中使用#installp命令安装后，不知道为啥使用扫描命令扫描不到这个插件求大佬帮忙解决一下

### ISSUE THREAD

**Issue by He0607** [zhayujie/chatgpt-on-wechat#1703]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

然后这个是安装插件显示错误的日志： 'type' object is not subscriptable

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by W1nd** [comment]
我之前遇到过类似问题，升级Python版本问题解决了。我之前是Python3.8，升级到3.9无此问题

**Comment by He0607** [comment]
> 我之前遇到过类似的问题，升级Python版本问题解决了。我之前是Python3.8，升级到3.9无此问题

好的感谢这个问题我已经解决啦

**Comment by spacex-3** [comment]
> > 我之前遇到过类似的问题，升级Python版本问题解决了。我之前是Python3.8，升级到3.9无此问题
> 
> 好的感谢这个问题我已经解决啦

你好，请问怎么解决的呀

**Comment by Azad-Aihub** [comment]
> > 我之前遇到过类似的问题，升级Python版本问题解决了。我之前是Python3.8，升级到3.9无此问题
> 
> 好的感谢这个问题我已经解决啦

您好，请问怎么解决呢？今天也碰到这个问题了

**Comment by IdealYth** [comment]
> > 我之前遇到过类似的问题，升级Python版本问题解决了。我之前是Python3.8，升级到3.9无此问题
> 
> 好的感谢这个问题我已经解决啦
您好，请问怎么解决呢？今天也碰到这个问题了

**Comment by AnCool-OvO** [comment]
看报错吧，针对报错去解决就可以了
