### ISSUE TITLE
好像不能在arm平台里的docker跑啊？？

### ISSUE THREAD

**Issue by answerzx** [zhayujie/chatgpt-on-wechat#1706]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

我使用软路由的系统armv8平台的openwrt上的docker 启动镜像的时候报错：
 ⠧ chatgpt-on-wechat The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   

### 终端日志 📒

```log
<此处粘贴终端日志>
``` ⠧ chatgpt-on-wechat The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by null0034** [comment]
默认编译的是x86架构的镜像，你要是在arm上跑需要自己打包arm架构镜像

**Comment by katfionn** [comment]
> 默认编译的是x86架构的镜像，你要是在arm上跑需要自己打包arm架构镜像

不懂代码和服务器的小奶白，请教下这个有没有打包教程呀

**Comment by katfionn** [comment]
> 默认编译的是x86架构的镜像，你要是在arm上跑需要自己打包arm架构镜像

文心一言让我改dockerfile，但是看不懂那里面写的是啥

**Comment by 6vision** [comment]
最新的已支持

**Comment by keyikai** [comment]
> 最新的已支持
我跑的时候也遇到了同样的问题，似乎没有解决啊

**Comment by keyikai** [comment]
> 最新的已支持

会不会是源码更新了，yml没有更新，我使用的是wget到docker的，docker后台日志是stderr: exec /entrypoint.sh: exec format error
