### ISSUE TITLE
Gemini配置文件config.json是否有问题，我使用了api正确可访问的，但微信机器人对接

### ISSUE THREAD

**Issue by HHasi** [zhayujie/chatgpt-on-wechat#1707]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/96771553/fe9f3606-2021-4ea6-9f66-c8ffe1d2487b)
![微信图片_20240127024618](https://github.com/zhayujie/chatgpt-on-wechat/assets/96771553/9e8b2add-2330-4a0e-819b-19ae73e96503)
如图

### 问题描述 😯

{
  "gemini_api_key": "AIzaSyCTp2-IKeT7xxxxxx",
  "hot_reload": false,
  "single_chat_prefix": ["bot", "@bot"],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": ["@bot"],
  "group_name_white_list": ["ALL_GROUP"],
  "group_chat_in_one_session": ["ALL_GROUP"],
  "image_create_prefix": ["画","看","找"],
  "speech_recognition": true,
  "group_speech_recognition": false,
  "voice_reply_voice": true,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "character_desc": "你是Gemini, 一个由Google AI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
  "temperature": 0.7,
  "top_p": 1,
  "subscribe_msg": "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false
}

这个是我的config.json

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by single228758** [comment]
#model gemini

**Comment by Jas0nxlee** [comment]
同问 加了model一样报错

**Comment by 6vision** [comment]
model参数没配置，走的还是chatGPT bot。此外，如果提示网络问题，是gemini服务需要海外环境，且对代理的ip要求较高
