### ISSUE TITLE
阿里Qwen配置缺失：建议在requirements-optional里面加上broadscope_bailian的依赖包

### ISSUE THREAD

**Issue by AurganicSubstance** [zhayujie/chatgpt-on-wechat#1709]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by 6vision** [comment]
项目现在已支持新版阿里模型接入，配置  "dashscope_api_key": "",参数即可，见https://github.com/zhayujie/chatgpt-on-wechat/pull/1851
