### ISSUE TITLE
请问在获取到微信图片类型消息后如何保存图片？

### ISSUE THREAD

**Issue by piniing** [zhayujie/chatgpt-on-wechat#1712]
请问在获取到微信图片类型消息后如何保存图片？

**Comment by piniing** [comment]
“ [WX] consume context: Context(type=IMAGE, content=tmp/240129-182416.png, kwargs={”

根目录下确实是有tmp目录，但图片并没有保存。

**Comment by Oject** [comment]
也遇到了这个需求，请问怎么样可以获取到图片

**Comment by reinforceli** [comment]
同样问题，tmp目录下没文件

**Comment by xjspace** [comment]
保存图片的时候，接收到图片，分析图片，给出图片描述

**Comment by 6vision** [comment]
在需要保存图片的地方调用chat_message的prepare方法，可以參考：https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/linkai/linkai.py#L53

**Comment by ctruk** [comment]
> 在需要保存图片的地方调用chat_message的prepare方法，可以參考：https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/linkai/linkai.py#L53

亲测可用！

**Comment by Kennytian** [comment]
```python
def on_handle_context(self, e_context: EventContext):
    context = e_context['context']
    context.get("msg").prepare()
    file_path = context.content
```
