### ISSUE TITLE
tool插件是否可以使用chatgpt-on-wechat本身配置的model？

### ISSUE THREAD

**Issue by wayshall** [zhayujie/chatgpt-on-wechat#1714]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

chatgpt-on-wechat本身需要配置model，而tool插件目前只支持chatgpt。
如果tool插件能直接使用chatgpt-on-wechat项目本身配置的model，就省去重复配置，而tool集成到项目后，也变相能支持更多的model。

### 动机

tool插件能直接使用chatgpt-on-wechat项目本身配置的model，就省去重复配置，而tool集成到项目后，也变相能支持更多的model。

**Comment by xiaoze-hub** [comment]
怎么说
