### ISSUE TITLE
如何在插件中获取群名称

### ISSUE THREAD

**Issue by starsliao** [zhayujie/chatgpt-on-wechat#1715]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

你好，我想编写个插件，需要在消息触发插件时候获取到群名称，请问下有哪个字段会记录群名称，可以在插件中获取到。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by azz212** [comment]
换wx协议，换ipdad
