### ISSUE TITLE
用微信公众号搭建，语音回复失败

### ISSUE THREAD

**Issue by glhhello** [zhayujie/chatgpt-on-wechat#1717]
文字回复没有问题，图片回复也没有问题，图片的缓存也做得很好。就是语音出现了问题。

显示报错是Request 1 from ocEI4t0Mz8HIZ3BsZo2JUvYCEXvw 7329778444185632768 162.62.80.8:12737
tmp/75GFMyk3aNUKFYKeuFgnxmlR9fMT_fPs2-WQattnZDR1qGacisIUtJgbH4WBhkJM.amr
/www/server/python_manager/versions/3.9.7/lib/python3.9/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[WARNING][2024-01-30 14:43:54][chat_channel.py:198] - [WX]any to wav error, use raw path. [Errno 2] No such file or directory: 'ffprobe'
[INFO][2024-01-30 14:43:55][wechatmp_channel.py:85] - [wechatmp] text cached, receiver ocEI4t0Mz8HIZ3BsZo2JUvYCEXvw
[ERROR]
我暂时还无法听清您的语音，请稍后再试吧~

**Comment by zhayujie** [comment]
已合并，看下是否解决了
