### ISSUE TITLE
配置千问无返回结果

### ISSUE THREAD

**Issue by 7li7li** [zhayujie/chatgpt-on-wechat#1718]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

这是我的环境变量
OPEN_AI_API_KEY='sk-xxx'
MODEL='qwen'
PROXY=''
SINGLE_CHAT_PREFIX='["bot", "@bot"]'
SINGLE_CHAT_REPLY_PREFIX='"[bot] "'
GROUP_CHAT_PREFIX='["@bot"]'
GROUP_NAME_WHITE_LIST='["测试群", "测试群2"]'
IMAGE_CREATE_PREFIX='["画", "看", "找"]'
CONVERSATION_MAX_TOKENS=1000
SPEECH_RECOGNITION='False'
CHARACTER_DESC='你是鲁树人, 一个由7li7li训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
EXPIRES_IN_SECONDS=3600
USE_GLOBAL_PLUGIN_CONFIG='True'
USE_LINKAI='False'
LINKAI_API_KEY=''
LINKAI_APP_CODE=''
CHANNEL_TYPE="wechatmp"
WECHATMP_PORT=8888
WECHATMP_APP_ID="xxx"
WECHATMP_APP_SECRET="xx"
WECHATMP_AES_KEY="xx"
WECHATMP_TOKEN="xx"
SINGLE_CHAT_PREFIX=[""]
SINGLE_CHAT_REPLY_PREFIX=""
PLUGIN_TRIGGER_PREFIX="&"
qwen_access_key_id="xx",
qwen_access_key_secret="xx",
qwen_agent_key="xx",
qwen_app_id="xx",
qwen_node_id=""

### 问题描述 😯

公众号消息没有回应

### 终端日志 📒

[WARNING][2024-01-30 12:14:13][client.py:223] - Client login failed, res={'code': 401, 'data': 'Authentication failed, please check your API_KEY in https://link-ai.tech/console/interface', 'type': 'LOGIN'}
[DEBUG][2024-01-30 12:14:22][passive_reply.py:32] - [wechatmp] Receive encrypted post data:
<xml>
    <ToUserName><![CDATA[gh_514131533672]]></ToUserName>
    <Encrypt><![CDATA[FmsKUoD36WcwOuBJutI/tdcErExD5GLDLxw4de5afjDENoqS3fVC3425sxDi78NrOi7s+lW381+v8x8GUTSIyUywl/nmpMlWozoKXCH2zMwLrjmcti75rF6/snYpqgeSs/obQykRMuQ6FGFmTBk61BG7iO6fgVJfp2ACgOTJA1idXHPwTG7jC7tPivpDvP4QP+pVifqqpxvCThlRGDyAPFNWDBgOLwXBOVhEthE4NSs+CBsTJyG2FrBb7xfSx0p/EU9Fk0mv2vCSvQeekegnNEQLio5vcr3iqtCsMtxmg+P3ZDEFcprpa/DhiGghnlayO3yJYEtoi+sfBQbwOtHAArEfbuH21Z3qS6UgiQb/E/x3gtifdZESEkZcllDKHU2wxU5cVV8ZnheSnn/vqjeSI12xlaFTA6wOp4jH09o5T+w=]]></Encrypt>
</xml>

[DEBUG][2024-01-30 12:14:22][passive_reply.py:62] - [wechatmp] context: Context(type=TEXT, content=你好, kwargs={'isgroup': False, 'msg': <channel.wechatmp.wechatmp_message.WeChatMPMessage object at 0x7f7e9953c250>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': 'olTVy1rAV2xdWQMoFTaaPPP80wHM', 'receiver': 'olTVy1rAV2xdWQMoFTaaPPP80wHM'}) ChatMessage: id=24432875879848982, create_time=1706616880, ctype=TEXT, content=你好, from_user_id=olTVy1rAV2xdWQMoFTaaPPP80wHM, from_user_nickname=None, to_user_id=gh_514131533672, to_user_nickname=None, other_user_id=olTVy1rAV2xdWQMoFTaaPPP80wHM, other_user_nickname=None, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, at_list=None True
[INFO][2024-01-30 12:14:22][passive_reply.py:97] - [wechatmp] Request 1 from olTVy1rAV2xdWQMoFTaaPPP80wHM 24432875879848982 172.18.0.1:52116
你好
[DEBUG][2024-01-30 12:14:22][chat_channel.py:341] - [WX] consume context: Context(type=TEXT, content=你好, kwargs={'isgroup': False, 'msg': <channel.wechatmp.wechatmp_message.WeChatMPMessage object at 0x7f7e9953c250>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': 'olTVy1rAV2xdWQMoFTaaPPP80wHM', 'receiver': 'olTVy1rAV2xdWQMoFTaaPPP80wHM'})
[DEBUG][2024-01-30 12:14:22][chat_channel.py:166] - [WX] ready to handle context: Context(type=TEXT, content=你好, kwargs={'isgroup': False, 'msg': <channel.wechatmp.wechatmp_message.WeChatMPMessage object at 0x7f7e9953c250>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': 'olTVy1rAV2xdWQMoFTaaPPP80wHM', 'receiver': 'olTVy1rAV2xdWQMoFTaaPPP80wHM'})
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][godcmd.py:220] - [Godcmd] on_handle_context. content: 你好
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][keyword.py:52] - [keyword] on_handle_context. content: 你好
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin LINKAI triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][hello.py:71] - [Hello] on_handle_context. content: 你好
[DEBUG][2024-01-30 12:14:22][plugin_manager.py:187] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-01-30 12:14:22][finish.py:30] - [Finish] on_handle_context. content: 你好
[DEBUG][2024-01-30 12:14:22][chat_channel.py:186] - [WX] ready to handle context: type=TEXT, content=你好
[INFO][2024-01-30 12:14:22][bridge.py:49] - create bot qwen for chat
[ERROR][2024-01-30 12:14:22][wechatmp_channel.py:233] - [wechatmp] Fail to generate reply to user, msgId=24432875879848982, exception='tuple' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/app/channel/chat_channel.py", line 189, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/app/channel/channel.py", line 38, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/app/bridge/bridge.py", line 64, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/app/bridge/bridge.py", line 55, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "/app/bot/bot_factory.py", line 49, in create_bot
    return AliQwenBot()
  File "/app/bot/ali/ali_qwen_bot.py", line 24, in __init__
    self.api_key_expired_time = self.set_api_key()
  File "/app/bot/ali/ali_qwen_bot.py", line 149, in set_api_key
    api_key, expired_time = self.api_key_client().create_token(agent_key=self.agent_key())
  File "/usr/local/lib/python3.10/site-packages/broadscope_bailian/api/access_token_client.py", line 41, in create_token
    token_response = client.create_token(CreateTokenRequest(agent_key=agent_key))
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_bailian20230601/client.py", line 535, in create_token
    return self.create_token_with_options(request, runtime)
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_bailian20230601/client.py", line 499, in create_token_with_options
    self.call_api(params, req, runtime)
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_tea_openapi/client.py", line 1799, in call_api
    return self.do_request(params, request, runtime)
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_tea_openapi/client.py", line 1320, in do_request
    raise e
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_tea_openapi/client.py", line 1253, in do_request
    _request.headers['Authorization'] = OpenApiUtilClient.get_authorization(_request, signature_algorithm, hashed_request_payload, access_key_id, access_key_secret)
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_openapi_util/client.py", line 421, in get_authorization
    signature = Client.hex_encode(signature_method(secret, str_to_sign, sign_type))
  File "/usr/local/lib/python3.10/site-packages/alibabacloud_openapi_util/client.py", line 43, in signature_method
    secret = secret.encode('utf-8')
AttributeError: 'tuple' object has no attribute 'encode'
172.18.0.1:52116 - - [30/Jan/2024 12:14:22] "HTTP/1.1 POST /wx" - 200 OK

**Comment by 6vision** [comment]
看起来是参数有问题，项目现在已支持新版阿里模型接入，配置`  "dashscope_api_key": "",`参数即可，见#1851
