### ISSUE TITLE
如何接入one api

### ISSUE THREAD

**Issue by 7li7li** [zhayujie/chatgpt-on-wechat#1719]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

我尝试设置port为one api的地址 和对应的key 提示连接失败
我尝试设置baseurl改为oneapi地址也是一样的提示
不知道如何设置自己的代理服务器来使用
在nextchat中使用oneapi正常

### 问题描述 😯

以下是我的配置
OPEN_AI_API_KEY='one-api的配置'
MODEL='gpt-3.5-turbo'
PROXY='https://xxx.7li7li.cn'
open_ai_api_base='https://xxx.7li7li.cn/v1'
SINGLE_CHAT_PREFIX='["bot", "@bot"]'
SINGLE_CHAT_REPLY_PREFIX='"[bot] "'
GROUP_CHAT_PREFIX='["@bot"]'
GROUP_NAME_WHITE_LIST='["测试群", "测试群2"]'
IMAGE_CREATE_PREFIX='["画", "看", "找"]'
CONVERSATION_MAX_TOKENS=1000
SPEECH_RECOGNITION='False'
CHARACTER_DESC='你是鲁树人, 一个由7li7li训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
EXPIRES_IN_SECONDS=3600
USE_GLOBAL_PLUGIN_CONFIG='True'
USE_LINKAI='False'
LINKAI_API_KEY=''
LINKAI_APP_CODE=''
CHANNEL_TYPE="wechatmp"
WECHATMP_PORT=8888
WECHATMP_APP_ID="xx"
WECHATMP_APP_SECRET="xx"
WECHATMP_AES_KEY="xx"
SINGLE_CHAT_PREFIX=[""]
SINGLE_CHAT_REPLY_PREFIX=""
PLUGIN_TRIGGER_PREFIX="&"

**Comment by 7li7li** [comment]
我好像知道问题出在了哪里  因为是https代理，日志显示返回400错误 我在网上发现python的requests的模块存在这个问题。 希望作者尽快修复 支持https
使用http协议即可正确

**Comment by xiaoyucom1** [comment]
把PROXY的内容去掉，只保留open_ai_api_base就好

**Comment by 7li7li** [comment]
> 把PROXY的内容去掉，只保留open_ai_api_base就好

我尝试过不太行  解决方法是使用http替代https

**Comment by QAbot-zh** [comment]
proxy是给梯子准备的，正常是base配合key就行

**Comment by cq134cq** [comment]
同问

**Comment by death4444** [comment]
> 你好，请问解决了吗？我也希望能够接入本地的oneAPI,这样可以整合更多的功能

解决了呀，one api那个项目介绍里都说了，它的调用与openai一致的，所以前面几位大佬的意思就是说，直接在本项目的配置里面，在open_ai_api_base这一项填上one api的地址，然后key也填one api的key就行了。
题主快来close啦

**Comment by fanxing-6** [comment]
不行吧 open_ai_api_base貌似是只有"use_azure_chatgpt":true,才会启用 但是azure的与其他第三方还不一样

**Comment by 6vision** [comment]
见#2046

很多提供三方api服务的都兼容openai格式(模型除了chatgpt外，还有claude，Gemini等)，现有代码会根据model参数来选择对应的bot，特增加bot_type参数，指定使用的bot类型，可以解决使用第三方api key时候不能使用除chatgpt以外模型的问题 https://github.com/zhayujie/chatgpt-on-wechat/issues/2067 https://github.com/zhayujie/chatgpt-on-wechat/issues/2063 https://github.com/zhayujie/chatgpt-on-wechat/issues/2055
部分配置如下：
{
"open_ai_api_key": "sk-2c23a6cf8d2a2b677275d38c", # 三方服务的key
"bot_type": "chatGPT", # 兼容openai请求格式时候，保持不变，
"model": "claude-opus", # 依三方服务商提供的模型名字为准
"open_ai_api_base": "https://api.dxxxxxxh.com/v1", # 三方服务api 地址
}
