### ISSUE TITLE
Vercel部署

### ISSUE THREAD

**Issue by Mrgiraffe0102** [zhayujie/chatgpt-on-wechat#1720]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

增加vercel部署

### 动机

Railway要收费QAQ

**Comment by infrost** [comment]
我昨天试过了去适配vercel，结论是vercel不可以运行这样的项目。
1. vercel里的python应用要求声明一个handler，以在有http请求时触发运行，然而，用http请求去触发程序运行不可行。首先因为在handler下执行run（）实际上是创建了一个子进程，由于vercel本身限制，app.py中的signal模块不能在非主进程中被调用，会报错。
2. vercel里面的文件一旦部署后就是只读状态，程序没有写权限无法输出日志到文件，需要把log.py的部分注释掉，以及插件功能不可用（貌似）。
3. 就算是各种魔改了代码，vercel的severless服务似乎用的是Lambda ，函数有执行时间的限制（通常是 15 分钟），并且它们不是为长时间运行的进程设计的。此外，Lambda 函数是事件驱动的，不是传统的多线程或进程模型。
