### ISSUE TITLE
我配置都调试好    出现报错  debian12

### ISSUE THREAD

**Issue by deng-da-da** [zhayujie/chatgpt-on-wechat#1726]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 80 (char 81)
nohup: ignoring input and appending output to 'nohup.out'
[ERROR][2024-02-01 11:22:01][app.py:61] - App startup failed!
[ERROR][2024-02-01 11:22:01][app.py:62] - Expecting property name enclosed in double quotes: line 2 column 80 (char 81)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 30, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 229, in load_config
    config = Config(json.loads(config_str))
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 80 (char 81)
出现这个报错  检查了 config.json  但是还是报错 
这是我的配置（api配置做了删减）有哪位大佬帮忙解决下

**Comment by deng-da-da** [comment]
{
    "open_ai_api_key": "oxdSUsPN2",  // openai api key
    // openai apibase，当use_azure_chatgpt为true时，需要设置对应的api base
    "open_ai_api_base": "https://api.chatanywhere.tech/v1",
    "proxy": "",  // openai使用的代理
    // chatgpt模型， 当use_azure_chatgpt为true时，其名称为Azure上model deployment名称
    "model": "gpt-3.5-turbo",  // 还支持 gpt-4, gpt-4-turbo, wenxin, xunfei, qwen
    "use_azure_chatgpt": false,  // 是否使用azure的chatgpt
    "azure_deployment_id": "",  // azure 模型部署名称
    "azure_api_version": "",  // azure api版本
    // Bot触发配置
    "single_chat_prefix": ["", "@bot"],  // 私聊时文本需要包含该前缀才能触发机器人回复
    "single_chat_reply_prefix": " ",  // 私聊时自动回复的前缀，用于区分真人
    "single_chat_reply_suffix": "",  // 私聊时自动回复的后缀，\n 可以换行
    "group_chat_prefix": ["@bot"],  // 群聊时包含该前缀则会触发机器人回复
    "group_chat_reply_prefix": "",  // 群聊时自动回复的前缀
    "group_chat_reply_suffix": "",  // 群聊时自动回复的后缀，\n 可以换行
    "group_chat_keyword": [],  // 群聊时包含该关键词则会触发机器人回复
    "group_at_off": false,  // 是否关闭群聊时@bot的触发
    "group_name_white_list": ["ALL_GROUP", "ALL_GROUP"],  // 开启自动回复的群名称列表
    "group_name_keyword_white_list": [],  // 开启自动回复的群名称关键词列表
    "group_chat_in_one_session": ["ALL_GROUP"],  // 支持会话上下文共享的群名称
    "nick_name_black_list": [],  // 用户昵称黑名单
    "group_welcome_msg": "",  // 配置新人进群固定欢迎语，不配置则使用随机风格欢迎 
    "trigger_by_self": true,  // 是否允许机器人触发
    "text_to_image": "dall-e-2",  // 图片生成模型，可选 dall-e-2, dall-e-3
    "image_proxy": true,  // 是否需要图片代理，国内访问LinkAI时需要
    "image_create_prefix": ["画", "看", "找"],  // 开启图片回复的前缀
    "concurrency_in_session": 1,  // 同一会话最多有多少条消息在处理中，大于1可能乱序
    "image_create_size": "256x256",  // 图片大小,可选有 256x256, 512x512, 1024x1024 (dall-e-3默认为1024x1024)
    "group_chat_exit_group": false, 
    // chatgpt会话参数
    "expires_in_seconds": 3600,  // 无操作会话的过期时间
    // 人格描述
    "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
    "conversation_max_tokens": 5000,  // 支持上下文记忆的最多字符数
    // chatgpt限流配置
    "rate_limit_chatgpt": 20,  // chatgpt的调用频率限制
    "rate_limit_dalle": 50,  // openai dalle的调用频率限制
    // chatgpt api参数 参考https://platform.openai.com/docs/api-reference/chat/create
    "temperature": 0.9,
    "top_p": 1,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "request_timeout": 180,  // chatgpt请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
    "timeout": 120,  // chatgpt重试超时时间，在这个时间内，将会自动重试
    // Baidu 文心一言参数
    "baidu_wenxin_model": "eb-instant",  // 默认使用ERNIE-Bot-turbo模型
    "baidu_wenxin_api_key": "n5zGHIdeCNKg",  // Baidu api key
    "baidu_wenxin_secret_key": "xjE",  // Baidu secret key
    // 讯飞星火API
    "xunfei_app_id": "7d",  // 讯飞应用ID
    "xunfei_api_key": "ZjI4ZjAzzNTE2",  // 讯飞 API key
    "xunfei_api_secret": "07344a0e98",  // 讯飞 API secret
    // claude 配置
    "claude_api_cookie": "",
    "claude_uuid": "",
    // 通义千问API, 获取方式查看文档 https://help.aliyun.com/document_detail/2587494.html
    "qwen_access_key_id": "LTAI5CD",
    "qwen_access_key_secret": "PBeTzz17lT0",
    "qwen_agent_key": "28_p_efm",
    "qwen_app_id": "5e9e07",
    "qwen_node_id": "",  // 流程编排模型用到的id，如果没有用到qwen_node_id，请务必保持为空字符串
    // Google Gemini Api Key
    "gemini_api_key": "",
    // wework的通用配置
    "wework_smart": true,  // 配置wework是否使用已登录的企业微信，false为多开
    // 语音设置
    "speech_recognition": true,  // 是否开启语音识别
    "group_speech_recognition": false,  // 是否开启群组语音识别
    "voice_reply_voice": false,  // 是否使用语音回复语音，需要设置对应语音合成引擎的api key
    "always_reply_voice": false,  // 是否一直使用语音回复
    "voice_to_text": "baidu",  // 语音识别引擎，支持openai,baidu,google,azure
    "text_to_voice": "baidu",  // 语音合成引擎，支持openai,baidu,google,pytts(offline),azure,elevenlabs
    "text_to_voice_model": "tts-1",
    "tts_voice_id": "alloy",
    // baidu 语音api配置， 使用百度语音识别和语音合成时需要
    "baidu_app_id": "49091841",
    "baidu_api_key": "UypKCo6",
    "baidu_secret_key": "aOwjqp5",
    // 1536普通话(支持简单的英文识别) 1737英语 1637粤语 1837四川话 1936普通话远场
    "baidu_dev_pid": "1536",
    // azure 语音api配置， 使用azure语音识别和语音合成时需要
    "azure_voice_api_key": "",
    "azure_voice_region": "japaneast",
    // elevenlabs 语音api配置
    "xi_api_key": "",    //获取ap的方法可以参考https://docs.elevenlabs.io/api-reference/quick-start/authentication
    "xi_voice_id": "",   //ElevenLabs提供了9种英式、美式等英语发音id，分别是“Adam/Antoni/Arnold/Bella/Domi/Elli/Josh/Rachel/Sam”
    // 服务时间限制，目前支持itchat
    "chat_time_module": false,  // 是否开启服务时间限制
    "chat_start_time": "00:00",  // 服务开始时间
    "chat_stop_time": "24:00",  // 服务结束时间
    // 翻译api
    "translate": "baidu",  // 翻译api，支持baidu
    // baidu翻译api的配置
    "baidu_translate_app_id": "2001",  // 百度翻译api的appid
    "baidu_translate_app_key": "tHi41Q5X",  // 百度翻译api的秘钥
    // itchat的配置
    "hot_reload": false,  // 是否开启热重载
    // wechaty的配置
    "wechaty_puppet_service_token": "",  // wechaty的token
    // wechatmp的配置
    "wechatmp_token": "",  // 微信公众平台的Token
    "wechatmp_port": 8080,  // 微信公众平台的端口,需要端口转发到80或443
    "wechatmp_app_id": "",  // 微信公众平台的appID
    "wechatmp_app_secret": "",  // 微信公众平台的appsecret
    "wechatmp_aes_key": "",  // 微信公众平台的EncodingAESKey，加密模式需要
    // wechatcom的通用配置
    "wechatcom_corp_id": "",  // 企业微信公司的corpID
    // wechatcomapp的配置
    "wechatcomapp_token": "1000003",  // 企业微信app的token
    "wechatcomapp_port": 9999,  // 企业微信app的服务端口,不需要端口转发
    "wechatcomapp_secret": "fI2Cg",  // 企业微信app的secret
    "wechatcomapp_agent_id": "YC",  // 企业微信app的agent_id
    "wechatcomapp_aes_key": "vbPBY",  // 企业微信app的aes_key

    // 飞书配置
    "feishu_port": 80,  // 飞书bot监听端口
    "feishu_app_id": "",  // 飞书机器人应用APP Id
    "feishu_app_secret": "",  // 飞书机器人APP secret
    "feishu_token": "",  // 飞书 verification token
    "feishu_bot_name": "",  // 飞书机器人的名字
    
    // 钉钉配置
    "dingtalk_client_id": "",  // 钉钉机器人Client ID 
    "dingtalk_client_secret": "",  // 钉钉机器人Client Secret 
    
    // chatgpt指令自定义触发词
    "clear_memory_commands": ["//清除记忆"],  // 重置会话指令，必须以//开头
    // channel配置
    "channel_type": "wx",  // 通道类型，支持：{wx,wxy,terminal,wechatmp,wechatmp_service,wechatcom_app}
    "subscribe_msg": "",  // 订阅消息, 支持: wechatmp, wechatmp_service, wechatcom_app
    "debug": false,  // 是否开启debug模式，开启后会打印更多日志
    "appdata_dir": "",  // 数据目录
    // 插件配置
    "plugin_trigger_prefix": "$",  // 规范插件提供聊天相关指令的前缀，建议不要和管理员指令前缀"//"冲突
    // 是否使用全局插件配置
    "use_global_plugin_config": false,
    "max_media_send_count": 3,     // 单次最大发送媒体资源的个数
    "media_send_interval": 1,  // 发送图片的事件间隔，单位秒
    // LinkAI平台配置
    "use_linkai": false,
    "linkai_api_key": "",
    "linkai_app_code": "",
    "linkai_api_base": "https://api.link-ai.chat",  // linkAI服务地址，若国内无法访问或延迟较高可改为 https://api.link-ai.tech
}

**Comment by deng-da-da** [comment]
我用的是企业微信

**Comment by azz212** [comment]
json 文件不要有任何注释
