### ISSUE TITLE
support gpt-3.5-turbo-0125 model

### ISSUE THREAD

**Issue by echo-lgtm** [zhayujie/chatgpt-on-wechat#1727]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

https://platform.openai.com/docs/models/overview

**Comment by zhayujie** [comment]
已经支持 
https://github.com/zhayujie/chatgpt-on-wechat/releases/tag/1.5.6
