### ISSUE TITLE
单独聊天画画，不能给出图片而是文字描述，只有群聊可以画画

### ISSUE THREAD

**Issue by wpneu6699** [zhayujie/chatgpt-on-wechat#173]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by wpneu6699** [comment]
能否单独聊天也能给出图片结果呢？

**Comment by kof8855** [comment]
很多人都微信都被封了一次了， 你还没？我小号被封了一次，大号帮助解封了就不用了。可能他用的itchat版本有什么改动，都是因为非法客户端登陆被封。我小号微信用的另一个版本itchat很久了都没问题，已用这个项目的就封了一次

**Comment by zhayujie** [comment]
> 很多人都微信都被封了一次了， 你还没？我小号被封了一次，大号帮助解封了就不用了。可能他用的itchat版本有什么改动，都是因为非法客户端登陆被封。我小号微信用的另一个版本itchat很久了都没问题，已用这个项目的就封了一次

我用的 itchat-uos 框架，  框架本身没变， 是前几天用的人太多，wx集中封了

**Comment by zhayujie** [comment]
> 能否单独聊天也能给出图片结果呢？

现在是支持的， 单聊消息需要同时满足 single_chat_prefix 和 image_create_prefix
