### ISSUE TITLE
关于公众号Channel的8080端口转发有更好的办法

### ISSUE THREAD

**Issue by shyouhui** [zhayujie/chatgpt-on-wechat#1730]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

这里面：
https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechatmp/README.md
说，端口转发用下面方法：
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables-save > /etc/iptables/rules.v4

对于已经部署了N个网站的服务器，这种方法不可行。

可以在宝塔建一个网站（使用子域名），然后设置一个反向代理指向本机的8080端口即可：
![微信图片编辑_20240203124221](https://github.com/zhayujie/chatgpt-on-wechat/assets/157334984/316ba717-21bd-4abc-ba57-6c7ab758a26e)

**Comment by zhayujie** [comment]
对的， 如果是直接在服务器上运行的也可以用nginx类似的反向代理工具

**Comment by wenbochang888** [comment]
> 对的， 如果是直接在服务器上运行的也可以用nginx类似的反向代理工具

@zhayujie 我用nginx转发，比如http://url/wx, 一直校验不通过？是还需要配置一些其他内容么？
