### ISSUE TITLE
扫码登录成功后start auto replying   后发送信息bot触发无回复

### ISSUE THREAD

**Issue by descending-order** [zhayujie/chatgpt-on-wechat#1733]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

git clone拉取
pip insatll -re,optional re
python 运行成功扫二维码可以登录并start auto replying
配置用的是文心模型

### 问题描述 😯

应用没有被调用,经调试from bot猜想机器人没有创建成功，运行bot相关文件发现虚拟环境与自定义模块冲突，py文件找不到import

### 终端日志 📒

(weixin) C:\Users\zoey\Desktop\random\weixinGPT>C:/Users/zoey/anaconda3/envs/weixin/python.exe c:/Users/zoey/Desktop/random/weixinGPT/chatgpt-on-wechat/bot/bot_factory.py
Traceback (most recent call last):
  File "c:/Users/zoey/Desktop/random/weixinGPT/chatgpt-on-wechat/bot/bot_factory.py", line 4, in <module>
    from common import const
ImportError: cannot import name 'const' from 'common' (C:\Users\zoey\anaconda3\envs\weixin\lib\site-packages\common\__init__.py)

(weixin) C:\Users\zoey\Desktop\random\weixinGPT>C:/Users/zoey/anaconda3/envs/weixin/python.exe c:/Users/zoey/Desktop/random/weixinGPT/chatgpt-on-wechat/bot/bot.py
Traceback (most recent call last):
  File "c:/Users/zoey/Desktop/random/weixinGPT/chatgpt-on-wechat/bot/bot.py", line 6, in <module>
    from bridge.context import Context
ModuleNotFoundError: No module named 'bridge'

(weixin) C:\Users\zoey\Desktop\random\weixinGPT>C:/Users/zoey/anaconda3/envs/weixin/python.exe c:/Users/zoey/Desktop/random/weixinGPT/chatgpt-on-wechat/bot/session_manager.py
Traceback (most recent call last):
  File "c:/Users/zoey/Desktop/random/weixinGPT/chatgpt-on-wechat/bot/session_manager.py", line 1, in <module>
    from common.expired_dict import ExpiredDict
ModuleNotFoundError: No module named 'common.expired_dict'

**Comment by zhayujie** [comment]
建议直接安装python运行

**Comment by descending-order** [comment]
我全局的是3.11要卸掉重下嘛

**Comment by zhayujie** [comment]
> 我全局的是3.11要卸掉重下嘛

可以试下，不行就换低版本的，3.9

**Comment by descending-order** [comment]
好的好的，谢谢你

**Comment by LuckMonkey2000** [comment]
我刚刚使用3.9也试了，没回复。所有流程都是按照教程来的，没有多余意外情况，就是没回复。连别人发消息给自己，都捕捉不到。

**Comment by descending-order** [comment]
C:\Users\zoey\Desktop\random\weixin>C:/Python311/python.exe c:/Users/zoey/Desktop/random/weixin/chatgpt-on-wechat/bot/bot_factory.py
Traceback (most recent call last):
  File "c:\Users\zoey\Desktop\random\weixin\chatgpt-on-wechat\bot\bot_factory.py", line 4, in <module>
    from common import const
ModuleNotFoundError: No module named 'common'

**Comment by sxbg321** [comment]
你等一下网页版的微信看看是不是登不上
