### ISSUE TITLE
加入自定义WEB调用API接口

### ISSUE THREAD

**Issue by Simon-leomon** [zhayujie/chatgpt-on-wechat#1737]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

增加一个通过WEB页面访问API接口，简化的自定义协议格式。
便于用户自定义功能的连接应用

### 举例

只需要三个参数
账号、口令、数据
回复数据

### 动机

开放连接，连接成互联“智能体”

**Comment by 6vision** [comment]
[bot on anything](https://github.com/zhayujie/bot-on-anything)支持web访问，可以部署该项目
