### ISSUE TITLE
项目能否提供API接入支持

### ISSUE THREAD

**Issue by freestylefly** [zhayujie/chatgpt-on-wechat#1738]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

目前消息没法接收，也没有相应的API接口能收到消息，如果想基于此开发一些功能目前看来做不到

### 举例

比如，我想获取消息后，走我自己的一个验证通道

### 动机

想基于此自定义开发

**Comment by 6vision** [comment]
目前没有的，可以写个插件看看能不能满足需求
