### ISSUE TITLE
是否可以将uos替换为其他协议？

### ISSUE THREAD

**Issue by hbsun2113** [zhayujie/chatgpt-on-wechat#174]

**Comment by fj9876** [comment]
用什么协议都一样，微信照样封，腾讯不干人事

**Comment by zhayujie** [comment]
目前除了uos没有更好的方案了， 原生的itchat需要有网页版的登录权限，能用的人本来就不多；其他的协议可能要收费，比如通过ipad登录。

**Comment by kinfaicheung** [comment]
> 目前除了uos没有更好的方案了， 原生的itchat需要有网页版的登录权限，能用的人本来就不多；其他的协议可能要收费，比如通过ipad登录。

可以写个收费协议的教程吗

**Comment by yinuxy** [comment]
> 目前除了uos没有更好的方案了， 原生的itchat需要有网页版的登录权限，能用的人本来就不多；其他的协议可能要收费，比如通过ipad登录。
大佬可以看看ntchat，不用扫码登录，直接抓客户端hook
