### ISSUE TITLE
讯飞星火已经更新3.5版本

### ISSUE THREAD

**Issue by silence9527** [zhayujie/chatgpt-on-wechat#1740]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

修改代码为wss://spark-api.xf-yun.com/v3.5/chat，即可运行，已测试通过

### 问题描述 😯

使用3.5token会造成返回错误

[ERROR][2024-02-06 17:17:15][xunfei_spark_bot.py:223] - 请求错误: 11200, {'header': {'code': 11200, 'message': 'AppIdNoAuthError:(17:17:15.673) domain.generalv3', 'sid': 'cht000cdfcc@dx18d7db51418b8f3550', 'status': 2}}

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by JobsLee0** [comment]
我这边也遇到了这个问题，目前已经提交PR
https://github.com/zhayujie/chatgpt-on-wechat/pull/1763

**Comment by liukangjia666** [comment]
[ERROR][2024-02-28 10:28:02][xunfei_spark_bot.py:194] - [XunFei] error: Handshake status 401 Unauthorized，这个协议进去为什么

**Comment by LiuXin-up** [comment]
我也遇到了相同问题，3.0版本的讯飞星火可以使用，3.5版本会报11200错误

**Comment by Sven-Rose** [comment]
遇到同样问题，没有找到怎么解决，改申请了3.0的token，就能正常使用了

**Comment by Sven-Rose** [comment]
> 我也遇到了相同问题，3.0版本的讯飞星火可以使用，3.5版本会报11200错误

说明到这一步基本上通的了

**Comment by JobsLee0** [comment]
请参照我的PR，3.5版本不明原因需要走wss协议，否则会报以上错误码

**Comment by kingdocker** [comment]
讯飞支持图片生成了，研究了下本地可以跑通，项目代码没搞定。。。
项目有望合入吗~

**Comment by JobsLee0** [comment]
> 讯飞支持图片生成了，研究了下本地可以跑通，项目代码没搞定。。。 项目有望合入吗~

有PR吗，想参考学习一下

**Comment by silence9527** [comment]
> 遇到同样问题，没有找到怎么解决，改申请了3.0的token，就能正常使用了

/app/bot/xunfei/xunfei_spark_bot.py，这里改wss://spark-api.xf-yun.com/v3.5/chat就可以了

**Comment by silence9527** [comment]
> 请参照我的PR，3.5版本不明原因需要走wss协议，否则会报以上错误码

/app/bot/xunfei/xunfei_spark_bot.py，这里改wss://spark-api.xf-yun.com/v3.5/chat就可以了，3.5 3 2都是wss
