### ISSUE TITLE
可否增加一项参数？让机器人在群组中回答问题的时候不要@用户，只回答问题就行。

### ISSUE THREAD

**Issue by zhaolu1206** [zhayujie/chatgpt-on-wechat#1741]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by 6vision** [comment]
正常来看，艾特一下是正常逻辑，方便区分回复的是哪个人，如有特殊需求，可以参考这部分[代码](https://github.com/zhayujie/chatgpt-on-wechat/blob/2074f27aff7c18e3adb286ed2578af5639ce6efc/channel/chat_channel.py#L256)
