### ISSUE TITLE
[Ok][shut][app.py:67] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0) Traceback (most recent call last):   File "C:\Users\Administrator\Desktop\gpt\chatgpt-on-wechat\app.py", line 46, in run     load_config()   File "C:\Users\Administrator\Desktop\gpt\chatgpt-on-wechat\config.py", line 232, in load_config     config = Config(json.loads(config_str))   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads     raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)", json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by k08255-lxm** [zhayujie/chatgpt-on-wechat#1743]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

我使用的是windows server2016，python版本3.8.5，安装好了所有依赖，一运行app.py便会出现报错

### 问题描述 😯

[ERROR][2024-02-07 21:13:59][app.py:66] - App startup failed!
[ERROR][2024-02-07 21:13:59][app.py:67] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\gpt\chatgpt-on-wechat\app.py", line 46, in run
    load_config()
  File "C:\Users\Administrator\Desktop\gpt\chatgpt-on-wechat\config.py", line 232, in load_config
    config = Config(json.loads(config_str))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### 终端日志 📒

```log
<[ERROR][2024-02-07 21:13:59][app.py:66] - App startup failed!
[ERROR][2024-02-07 21:13:59][app.py:67] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\gpt\chatgpt-on-wechat\app.py", line 46, in run
    load_config()
  File "C:\Users\Administrator\Desktop\gpt\chatgpt-on-wechat\config.py", line 232, in load_config
    config = Config(json.loads(config_str))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
>
```

**Comment by doublet444** [comment]
配置config.json文件使用utf8编码
