### ISSUE TITLE
登录二维码能通过web服务访问，方便重启服务重新扫码

### ISSUE THREAD

**Issue by fyl080801** [zhayujie/chatgpt-on-wechat#1744]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

每次重启服务都需要扫码登陆，是否可通过web服务在网页上直接访问获取二维码，而不用去控制台输出里看？使用vps部署不能每次都登录vps看log

**Comment by thchen0** [comment]
在github上看到过一个用node.js的微信机器人能用web登录，但是功能和支持的模型没这个多
https://github.com/Pchen0/Web-Wechat-Bot

**Comment by 6vision** [comment]
根目录config.json文件里的hot reload设为true，短暂暂停重新运行，不需要扫码
