### ISSUE TITLE
扫码后报错了，无法启动。

### ISSUE THREAD

**Issue by xin800** [zhayujie/chatgpt-on-wechat#175]
### 前置确认

1. 运行于国内网络环境，开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

扫码后报错了，无法启动。
![image](https://user-images.githubusercontent.com/9602020/218259945-6fb36548-18b2-4311-8222-52d045e78e1f.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
python版本太高了，换3.7-3.10的试试
