### ISSUE TITLE
修改昵称后，群聊@失效

### ISSUE THREAD

**Issue by housirzero** [zhayujie/chatgpt-on-wechat#1750]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1. 用户昵称当前为A，此时启动进程，使用其他的微信在群聊中@A用户，可以正常应答
2. 修改用户昵称为B，等待其他的微信中显示A用户名称已变更后，@B用户，无法响应

### 问题描述 😯

A,B实际是同一个用户，只是修改了名字，就无法被正常识别

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
需要重启项目，如果hot reload为true，需要删除根目录的itchat.pkl文件
