### ISSUE TITLE
使用DALLE3时有概率无法收到图片

### ISSUE THREAD

**Issue by Zoumachuan** [zhayujie/chatgpt-on-wechat#1755]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

正常启动并创建了接入COW的应用，在尝试启动mj和dalle-3时均遇到了在微信群里或和个人私信无法发送图片的情况，无论这个图片是什么内容。

### 问题描述 😯

![微信截图_20240219192517](https://github.com/zhayujie/chatgpt-on-wechat/assets/123653723/c89025f8-4e9d-4620-9dbe-73446077e158)
![微信截图_20240219192533](https://github.com/zhayujie/chatgpt-on-wechat/assets/123653723/53c6298c-57eb-4ba6-8da4-f5f8c1d0e199)

### 终端日志 📒

```log
[INFO][2024-02-19 19:02:42][wechat_channel.py:207] - [WX] download image success, size=3162696, img_url=https://image-1317903499.cos.accelerate.myqcloud.com/delle/c1dab59c-516e-4dd8-922e-8e48da706ee2.png
[INFO][2024-02-19 19:02:48][wechat_channel.py:210] - [WX] sendImage url=https://image-1317903499.cos.accelerate.myqcloud.com/delle/c1dab59c-516e-4dd8-922e-8e48da706ee2.png, receiver=@@a736587b0dae073f4e5a8630f7e7c1bfbc46a7f3936dd2d07a345357b047ee71
```

**Comment by dudujiq** [comment]
加一

**Comment by 6vision** [comment]
这个大概率是微信账户的问题，引起风控，等等应该就恢复了

**Comment by princeGoo** [comment]
楼主，请问上述问题可以确认是微信风控引起的吗

**Comment by MuskZhouMQ** [comment]
我完全无法收到图片回复，终端显示已发送但并未收到，个人号和公众号都不行
