### ISSUE TITLE
正常运行一段时间后，程序死机无法回复

### ISSUE THREAD

**Issue by joyce677** [zhayujie/chatgpt-on-wechat#1759]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

启动程序时，只要有人在群里连续两三条消息都是发表情包或者都是发引用的时候就会有大概率触发，导致任务队列卡住，后续任何指令都无法执行，只能重启项目。

### 问题描述 😯

不回复消息，进程还在，消息队列里卡住，只能重启项目。

### 终端日志 📒

{'gh_d39ce2573b46': [<common.dequeue.Dequeue object at 0x0000023EDB45E910>, <threading.BoundedSemaphore object at 0x0000023EDB45E970>], '49481945001@chatroom': [<common.dequeue.Dequeue object at 0x0000023EDB843A00>, <threading.BoundedSemaphore object at 0x0000023EDB843940>]}

**Comment by songwenyuan** [comment]
有解决吗 我也碰到此类问题，进程还在，但是假死。没有任何日志输出了

**Comment by joyce677** [comment]
> 有解决吗 我也碰到此类问题，进程还在，但是假死。没有任何日志输出了

 没有，猜测应该是session_id的问题，但是调了半天还是依旧会偶发出现。

**Comment by shyouhui** [comment]
遇到同样问题。官方解释Web协议不稳定，没有给到解决办法

**Comment by lwg712176** [comment]
gemini里面同样遇到了，难受啊
