### ISSUE TITLE
Ask some questions

### ISSUE THREAD

**Issue by QQbbla** [zhayujie/chatgpt-on-wechat#1767]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

如何将自己的大模型接入到wechat？

**Comment by QAbot-zh** [comment]
你这问的也太宽泛了，至少得给你的大模型的调用文档说明吧

**Comment by QQbbla** [comment]
我已经有训练好的模型权重文件，我要怎么把它接到WeChat呢？就类似baichuan、qwen，chatglm这样的llm的权重文件。

**Comment by 6vision** [comment]
这个不支持直接接入使用，应该要新增bot，或者修改一下源代码

**Comment by QQbbla** [comment]
确实是的！发自我的 iPhone在 2024年3月19日，23:51，vision ***@***.***> 写道：﻿
这个不支持直接接入使用，应该要新增bot，或者修改一下源代码
