### ISSUE TITLE
一定需要服务器可以访问openai的吗？ 我配置了代理直接使用我的代理来转发不行吗？ 

### ISSUE THREAD

**Issue by yangbuyiya** [zhayujie/chatgpt-on-wechat#1768]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

一定需要服务器可以访问openai的吗？ 我配置了代理直接使用我的代理来转发不行吗？ 

我已经配置了proxy按道理直接给我用proxy来发请求吧

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/52228969/f2b4786c-e9e4-4b28-9c46-edb0fe28358f)

### 举例

一定需要服务器可以访问openai的吗？ 我配置了代理直接使用我的代理来转发不行吗？ 

### 动机

一定需要服务器可以访问openai的吗？ 我配置了代理直接使用我的代理来转发不行吗？ 

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/52228969/433b51b5-c811-470e-9f21-c95a03674f4e)

**Comment by yangbuyiya** [comment]
解决了 文档里面没有看到 open_ai_api_base 这个字段 ，建议补充一下吧

我把 'proxy ' 字段去掉使用 
"open_ai_api_base": "http://xxx.xxx.xxx.xxx:port/v1", 

# 如果是ip+port :  ip+port/v1
# 如果是域名: 直接域名/v1

**Comment by Jerrywang2013** [comment]
open_ai_api_base是用于转发，就是你说的这个需求； proxy是代理服务器设置

**Comment by wonder-perfect** [comment]
> # 解决了 文档里面没有看到 open_ai_api_base 这个字段 ，建议补充一下吧

config.py中有所有可配置参数的说明
