### ISSUE TITLE
nas上部署的gpt如何设置godcmd插件的口令，新人求教！

### ISSUE THREAD

**Issue by fyshion1** [zhayujie/chatgpt-on-wechat#1770]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用的是绿联DX4600，配置好了环境变量，一切正常，就是不知道在nas的docker上如何设置godcmd的口令，因此无法获取管理员权限

### 问题描述 😯

如题

### 终端日志 📒

```log
<此处粘贴终端日志>
```无需日志

**Comment by lepingzhang** [comment]
用的群晖，应该大同小异：

映射目录新建`plugins`文件夹，然后里面配置插件的`config.json`文件，就可以修改管理员口令了

**Comment by fyshion1** [comment]
请问如何新建映射目录，搜不到具体教程，能否稍微指点一下，十分感谢！

**Comment by zdbpython** [comment]
这个是最基础的了

**Comment by fyshion1** [comment]
实在不好意思,请问有无地方有视频教程呢,目前大一在读,基础不是特别太牢固.

**Comment by 6vision** [comment]
> ### 前置确认
> * [x]  我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。
> 
> ### ⚠️ 搜索issues中是否已存在类似问题
> * [x]  我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
> 
> ### 操作系统类型?
> Docker
> 
> ### 运行的python版本是?
> other
> 
> ### 使用的chatgpt-on-wechat版本是?
> Latest Release
> 
> ### 运行的`channel`类型是?
> wx(个人微信, itchat)
> 
> ### 复现步骤 🕹
> 使用的是绿联DX4600，配置好了环境变量，一切正常，就是不知道在nas的docker上如何设置godcmd的口令，因此无法获取管理员权限
> 
> ### 问题描述 😯
> 如题
> 
> ### 终端日志 📒
> ```
> <此处粘贴终端日志>
> ```无需日志
> ```

docker配置插件，参考：https://github.com/zhayujie/chatgpt-on-wechat#3-%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8
