### ISSUE TITLE
什么时候可以支持扣子coze呀

### ISSUE THREAD

**Issue by k1ngr4m** [zhayujie/chatgpt-on-wechat#1775]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

https://www.coze.com/ 需要梯子，coze支持chatgpt4.0，还免费。想看看大佬能不能接入一下

**Comment by kingdocker** [comment]
配合https://github.com/deanxv/coze-discord-proxy已经用起来了~

**Comment by CHP20230826** [comment]
> 配合 https://github.com/deanxv/coze-discord-proxy 已经用起来了~

大佬教教

**Comment by kingdocker** [comment]
> > 配合 https://github.com/deanxv/coze-discord-proxy 已经用起来了~
> 
> 大佬教教

按照部署指导操作就好了~
1. 正常部署完上面的CDP后，就会有对应的api；
2. 本项目中的两个配置改一下：
* "open_ai_api_key": 用CDP里面设置的PROXY_SECRET环境变量值；
*  "open_ai_api_base":用CDP部署环境http://IP:port（项目默认7077）/v1
* model用gpt-4，画图可以用dall-e-3

**Comment by CHP20230826** [comment]
> > > 配合 https://github.com/deanxv/coze-discord-proxy 已经用起来了~
> > 
> > 
> > 大佬教教
> 
> 按照部署指导操作就好了~
> 
> 1. 正常部署完上面的CDP后，就会有对应的api；
> 2. 本项目中的两个配置改一下：
> 
> * "open_ai_api_key": 用CDP里面设置的PROXY_SECRET环境变量值；
> * "open_ai_api_base":用CDP部署环境[http://IP:port（项目默认7077）/v1](http://IP:port%EF%BC%88%E9%A1%B9%E7%9B%AE%E9%BB%98%E8%AE%A47077%EF%BC%89/v1)
> * model用gpt-4，画图可以用dall-e-3

感谢大佬！是我base填多了，老是404

**Comment by zhaolu1206** [comment]
> > > 配合 https://github.com/deanxv/coze-discord-proxy 已经用起来了~
> > 
> > 
> > 大佬教教
> 
> 按照部署指导操作就好了~
> 
> 1. 正常部署完上面的CDP后，就会有对应的api；
> 2. 本项目中的两个配置改一下：
> 
> * "open_ai_api_key": 用CDP里面设置的PROXY_SECRET环境变量值；
> * "open_ai_api_base":用CDP部署环境[http://IP:port（项目默认7077）/v1](http://IP:port%EF%BC%88%E9%A1%B9%E7%9B%AE%E9%BB%98%E8%AE%A47077%EF%BC%89/v1)
> * model用gpt-4，画图可以用dall-e-3

请问一下大佬，我的也是按照这个部署成功了，我是通过微秘书接入的，在微信里提问bot，但是bot只在discord里面回复，微信里面没有反应

**Comment by yalidabuda** [comment]
cow目前还是没适配扣子吗😂
