### ISSUE TITLE
图片消息怎么获取图片

### ISSUE THREAD

**Issue by Oject** [zhayujie/chatgpt-on-wechat#1776]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

发送图片消息，在项目根目录 tmp 下没有消息图片，debug 拿到原消息
<img width="1422" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/13999771/ae8453c3-f775-403a-b83e-747c9830d241">
但是不知道怎么获取图片

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
可以看下这部分的[代码](https://github.com/zhayujie/chatgpt-on-wechat/blob/2074f27aff7c18e3adb286ed2578af5639ce6efc/channel/wechat/wechat_message.py#L27)

**Comment by reinforceli** [comment]
我的也 是，图片没保存到tmp目录下。
