### ISSUE TITLE
Azure Openai API 接口无法使用

### ISSUE THREAD

**Issue by nidasfly** [zhayujie/chatgpt-on-wechat#1779]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

      OPEN_AI_API_KEY: 'my azure key'
      OEPN_AI_API_BASE: 'https://myresourcename.openai.azure.com/'
      MODEL: 'gpt-4-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '[""]'
      SINGLE_CHAT_REPLY_PREFIX: '""'
      GROUP_CHAT_PREFIX: '["/gpt"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      IMAGE_CREATE_PREFIX: ''
      TEXT-TO-IMAGE: "dall-e-3"
      CONVERSATION_MAX_TOKENS: 4000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: 'You are a helpful assistant.'
      EXPIRES_IN_SECONDS: 3600
      USE_AZURE_CHATGPT: 'True'
      AZURE_DEPLOYMENT_ID: 'gpt-4-turbo'
      AZURE_API_VERSION: '2024-02-15-preview'

### 问题描述 😯

使用时报错，提示获取url /v1/openai/deployments/gpt-4-turbo/chat/completions?api-version=2024-02-15-preview 错误。
然而正确的url应该是/openai/deployments/gpt-4-turbo/chat/completions?api-version=2024-02-15-preview，并没有v1

**Comment by zhang-tianyi** [comment]
+1

**Comment by 6vision** [comment]
可以贴一下具体log哈

**Comment by l00kg** [comment]
我也不行有成功的例子吗？我这提示获取的url 是/openai 开头的但是还是访问不到azure。
![微信截图_20240320201337](https://github.com/zhayujie/chatgpt-on-wechat/assets/103115271/7539934d-208c-4904-9e9e-acb9bc636d80)
