### ISSUE TITLE
可否用ananconda环境下运行该项目？

### ISSUE THREAD

**Issue by Champaignwei** [zhayujie/chatgpt-on-wechat#1782]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

尝试过spyder和jupyter lab都无法运行

**Comment by QAbot-zh** [comment]
怎么会无法运行，报什么错？只要环境配置正确，库都安装好，肯定是没问题的，用anaconda虚拟环境当然也是可以的。

**Comment by Champaignwei** [comment]
感谢您的回复！不适用pycharm而是用jupyter notebook能运行吗，可以的话麻烦介绍说明下注意事项！

**Comment by QAbot-zh** [comment]
> 感谢您的回复！不适用pycharm而是用jupyter notebook能运行吗，可以的话麻烦介绍说明下注意事项！

存在可行性但不建议，jupyter notebook一般是用来跑具体代码的，而且它依托浏览器或者专门的软件运行，后台很容易死掉。如果不想开着pycharm跑，可以通过cmd终端来运行程序。这样对系统也不会占用太多内存资源。

**Comment by 6vision** [comment]
建议服务器部署，1c1g的配置就可以跑
