### ISSUE TITLE
可否定时发送一些提醒，比如早安问候，打卡提醒之类的

### ISSUE THREAD

**Issue by huyuetongSX** [zhayujie/chatgpt-on-wechat#1783]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

【早安问候】
又是元气满满的一天...

### 动机

主动发送提醒消息

**Comment by mashagua** [comment]
可以使用timetask 的plugin

**Comment by 6vision** [comment]
这里有一个定时插件[timetask](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/source.json)
