### ISSUE TITLE
为什么我没办法用bing-search tool？

### ISSUE THREAD

**Issue by zhoushuai1998** [zhayujie/chatgpt-on-wechat#1786]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

在railway运行是一只报错，[INFO][2024-03-02 15:57:06][__init__.py:39] - [bing-search] initialization failed, error_info: 1 validation error for BingSearchAPIWrapper

Value error, Did not find bing_subscription_key, please add an environment variable `BING_SUBSCRIPTION_KEY` which contains it, or pass  `bing_subscription_key` as a named parameter. [type=value_error, input_value={'log': True, 'debug': Fa...olfram_alpha_appid': ''}, input_type=dict]

### 终端日志 📒

```log
<此处粘贴终端日志>
```[INFO][2024-03-02 15:57:06][__init__.py:39] - [bing-search] initialization failed, error_info: 1 validation error for BingSearchAPIWrapper

Value error, Did not find bing_subscription_key, please add an environment variable `BING_SUBSCRIPTION_KEY` which contains it, or pass  `bing_subscription_key` as a named parameter. [type=value_error, input_value={'log': True, 'debug': Fa...olfram_alpha_appid': ''}, input_type=dict]

**Comment by QAbot-zh** [comment]
信息不是写了吗，没有配`BING_SUBSCRIPTION_KEY`
