### ISSUE TITLE
1天后个人微信自动断开，需要重新扫码登陆

### ISSUE THREAD

**Issue by multsean** [zhayujie/chatgpt-on-wechat#1788]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

一到两天左右个人微信就会自动断开，需要重新扫码登陆，railway和docker都用过了都这样，有什么办法避免么

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by amyflash** [comment]
我也遇到同样的问题，是不是微信自己的原因？

**Comment by shyouhui** [comment]
同样的问题。最长的能撑4天，短的半天到1天就掉线

**Comment by sisuad** [comment]
协议的问题，目前使用的是web协议，免费的，但是不稳定，要掉线，正常的。

**Comment by multsean** [comment]
> 协议的问题，目前使用的是web协议，免费的，但是不稳定，要掉线，正常的。

有用付费不掉线协议的项目推荐么

**Comment by kingdocker** [comment]
说说我的解法：
* 之前用的iPhone，扫码登录跑1天左右就自动断线了；
* 后来换了安卓手机，扫码登录后跑了半个多月了都还正常；

**Comment by Liyu910228** [comment]
通过扫码登录之后能干嘛

**Comment by hecarli555** [comment]
> 说说我的解法：
> 
> * 之前用的iPhone，扫码登录跑1天左右就自动断线了；
> * 后来换了安卓手机，扫码登录后跑了半个多月了都还正常；

安卓扫码登录后关wifi不？

**Comment by shyouhui** [comment]
> 说说我的解法：
> 
> * 之前用的iPhone，扫码登录跑1天左右就自动断线了；
> * 后来换了安卓手机，扫码登录后跑了半个多月了都还正常；

跟是否安卓/苹果没有关系，我都用的安卓手机扫码登录，一样掉线

**Comment by ViperGash** [comment]
有可能是杀后台。微信其实后台如果不能持续在线。web这边就可能会挂掉。我的安卓系统双开就是这样的。主系统没有问题。一直在线。但是影子系统里面的微信就会持续挂掉。。

**Comment by 6vision** [comment]
微信移动端保持联网在线，设置微信app在后台锁定，不要被自动关了，开源项目目前好像没其他办法

**Comment by RockWillams** [comment]
解决步骤：
1：配置文件中    "hot_reload": true,
2:创建重启脚本autorestart.bat：
@echo off
taskkill /F /IM python.exe
timeout /t 5
cd C:\software\code\dify-on-wechat
timeout /t 2
start  python  C:\software\code\dify-on-wechat\app.py
3：windows下，使用脚本设置定时任务，设置每天1:35重启，linux下类似，使用crontab
 schtasks /create /tn "RestartApp" /tr "C:\software\code\dify-on-wechat\autorestart.bat" /sc daily /st 01:35
4：windows下，测试脚本,linux下类似，使用crontab
schtasks /run /tn "RestartApp"

收工

**Comment by JAHSEH618** [comment]
> 解决步骤： 1：配置文件中配置热启动功能，在重启后无需扫码即可自动登录： "hot_reload": true,
> 
> 2:创建重启脚本autorestart.bat： @echo off taskkill /F /IM python.exe timeout /t 5 cd C:\path-to-project\chatgpt-on-wechat timeout /t 2 start python C:\path-to-project\dify-on-wechat\app.py
> 
> 3：windows下，使用脚本设置定时任务，设置每天1:35重启（linux下类似，使用crontab）： schtasks /create /tn "RestartApp" /tr "C:\path-to-project\chatgpt-on-wechat\autorestart.bat" /sc daily /st 01:35
> 
> 4：windows下，测试脚本（linux下类似，使用crontab）: schtasks /run /tn "RestartApp"
> 
> 收工

有linux的解决方案吗
