### ISSUE TITLE
微信聊天中 只要发微信表情、或者关键词中的其中一个字符 就会直接触发gpt回复 

### ISSUE THREAD

**Issue by jachin113** [zhayujie/chatgpt-on-wechat#1791]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

我用cssaos系统去直接部署了此项目，成功了，不过现在发现的问题在于 ，只要是别人的聊天信息中有表情或者触发词中的字符（我的关键词是chatgpt，然后别人聊天打了个c 一样被触发了），不清楚问题在哪

### 问题描述 😯

version:'2.0'
services:
 chatgpt-on-wechat:
  image:zhayujie/chatgpt-on-wechat
  container_name:chatgpt-on-wechat
  security_opt:
   -seccomp:unconfined
  environment:
  "open_ai_api_key": "sk-o1es3Lbil6i0sacbhkecvwg56b461bB5386c484a2c010f",                          # 填入上面创建的 OpenAI API KEY
  "open_ai_api_base":"https://api.openai.com/v1"          #请求地址
  "model": "gpt-4",                                   # 模型名称, 支持 gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-4, wenxin, xunfei
  "proxy": "",                                                # 代理客户端的ip和端口，国内环境开启代理的需要填写该项，如 "127.0.0.1:7890"
  "single_chat_prefix": '[""]',                      # 私聊时文本需要包含该前缀才能触发机器人回复
  "single_chat_reply_prefix": '["ChatGPT"]',                       # 私聊时自动回复的前缀，用于区分真人
  "group_chat_prefix": '["ChatGPT"]',                              # 群聊时包含该前缀则会触发机器人回复
  "group_name_white_list": '["王者荣耀-花涧一壶酒i战队群", "TEST", "gpt"]', # 开启自动回复的群名称列表
  "group_chat_in_one_session": '["王者荣耀-花涧一壶酒i战队群", "TEST", "gpt"]',              # 支持会话上下文共享的群名称  
  "image_create_prefix": '["画", "看", "找"]',                   # 开启图片回复的前缀
  "conversation_max_tokens": 1000,                            # 支持上下文记忆的最多字符数
  "speech_recognition": false,                                # 是否开启语音识别
  "group_speech_recognition": false,                          # 是否开启群组语音识别
  "use_azure_chatgpt": false,                                 # 是否使用Azure ChatGPT service代替openai ChatGPT service. 当设置为true时需要设置 open_ai_api_base，如 https://xxx.openai.azure.com/
  "azure_deployment_id": "",                                  # 采用Azure ChatGPT时，模型部署名称
  "azure_api_version": "",                                    # 采用Azure ChatGPT时，API版本
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",  # 人格描述
  "subscribe_msg": "\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持角色扮演和文字冒险等丰富插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,                                        # 是否使用LinkAI接口，默认关闭，开启后可国内访问，使用知识库和MJ
  "linkai_api_key": "",                                       # LinkAI Api Key
  "linkai_app_code": ""                                       # LinkAI 应用code

这是放ccasaos中的代码

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by N4tsu-Y** [comment]
哥们，你的key暴露了

**Comment by jachin113** [comment]
谢谢谢，没事，那个是假的 我乱打的，非常感谢

N4tsu-Y ***@***.***> 于2024年3月5日周二 21:10写道：

**Comment by QAbot-zh** [comment]
你这不是没设置触发词吗？
`"single_chat_prefix": '[""]', # 私聊时文本需要包含该前缀才能触发机器人回复`

**Comment by 6vision** [comment]
> "single_chat_prefix": '[""]',

"single_chat_prefix": '[""]',这样写是不对的，这个参数是一个列表，要改为"single_chat_prefix": [""],
