### ISSUE TITLE
什么时候能支持claude的api？我看之前的还是利用的cookie的方式。现在claude的api放开了已经。

### ISSUE THREAD

**Issue by ViperGash** [zhayujie/chatgpt-on-wechat#1792]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

什么时候能支持claude的api？我看之前的还是利用的cookie的方式。现在claude的api放开了。

**Comment by pgciq** [comment]
up

**Comment by ChaiZhi** [comment]
希望支持

**Comment by resphinas** [comment]
我会将这个安排在近期的日程表上。

**Comment by resphinas** [comment]
更新后 不懂弄海外手机号注册，希望有人可以帮忙

**Comment by ViperGash** [comment]
> 更新后 不懂弄海外手机号注册，希望有人可以帮忙

现在确实是个问题。我有海外的手机号。所以没困难。但是如果需要不被封号的话，可能需要一个稳定的手机号。买一个esim或者实体卡寄到国内然后激活。。如果需要api测试的话。我可以把系统送的5刀给你。反正暂时没怎么用。

**Comment by resphinas** [comment]
> > 更新后 不懂弄海外手机号注册，希望有人可以帮忙
> 
> 现在确实是个问题。我有海外的手机号。所以没困难。但是如果需要不被封号的话，可能需要一个稳定的手机号。买一个esim或者实体卡寄到国内然后激活。。如果需要api测试的话。我可以把系统送的5刀给你。反正暂时没怎么用。

用api不会存在封号问题 如果可以的话烦请将相关信息发送至我主页的邮箱

**Comment by 6vision** [comment]
> 更新后 不懂弄海外手机号注册，希望有人可以帮忙

这里有一个解码平台，可以注册claude

**Comment by 6vision** [comment]
#1810 已经支持
