### ISSUE TITLE
如何设置回复延迟 模拟人类回复消息的习惯

### ISSUE THREAD

**Issue by lgl1996521** [zhayujie/chatgpt-on-wechat#1793]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

比如在和朋友交流，不想一直秒回复，很容易露馅

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by QAbot-zh** [comment]
手动加个time.sleep(random.randint(5, 10))，随机等5~10秒 😂

**Comment by QAbot-zh** [comment]
> 大佬，加在哪个文件里啊

可以加在这个位置
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/40236765/5fcdf5ea-7168-47e1-b078-755ef1cac849)

**Comment by huihuihenqiang** [comment]
改进了回复问题以及增加了其他特性 https://github.com/huihuihenqiang/wechat-simulate-human
