### ISSUE TITLE
程序跑时间长了就出错了- Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}

### ISSUE THREAD

**Issue by wyl765** [zhayujie/chatgpt-on-wechat#1795]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在windows command line跑 python app.py 

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/834505/fe631a96-85a4-40d5-bd74-41198f70a0bc)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by DayDreammy** [comment]
> wx检测到长时间登陆主动踢掉了

有没有什么解决方案

**Comment by tipani86** [comment]
这个问题我也出现过，目前用的是个人微信账号。有人用企业微信或者类似公众号客服的，有遇到这种问题吗？就是在想是不是换一种账号会好一些。

**Comment by 6vision** [comment]
腾讯官方的检测机制，移动端微信尽量保持联网在线，其他目前好像没什么太好的办法

**Comment by monk-after-90s** [comment]
😫
