### ISSUE TITLE
一个奇怪的BUG，某些关键词触发- 嗨，此内容的版权正在努力获取中，请在喜马拉雅APP继续收听吧- 的回复

### ISSUE THREAD

**Issue by swumagic** [zhayujie/chatgpt-on-wechat#1799]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

群或者私聊，只要关键词带了方案，祝福，话术，设计，清晨鸡汤等 ，就会回复嗨，此内容的版权正在努力获取中，请在喜马拉雅APP继续收听吧。不知道怎么修复。怀疑是配置的news插件还是timetask插件或者那个插件问题导致。哪位大哥知道怎么修复么

### 问题描述 😯

如上

### 终端日志 📒

[INFO][2024-03-07 19:36:45][chat_channel.py:117] - [WX]receive group at

[INFO][2024-03-07 19:36:48][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[黑]

@余

嗨，此内容的版权正在努力获取中，请在喜马拉雅APP继续收听吧

[更多关注DY-黑科技智造基地]), receiver=@@a98cb****

[INFO][2024-03-07 19:38:35][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[黑]

嗨，此内容的版权正在努力获取中，请在喜马拉雅APP继续收听吧

[更多关注DY-黑科技智造基地]), receiver=@70239a*****

**Comment by rexinshimin0001** [comment]
你好，timetask插件还能用么，为什么我的日志显示已执行，但实际并没有执行

**Comment by swumagic** [comment]
插件冲突导致
