### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by tlome** [zhayujie/chatgpt-on-wechat#18]
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
试了好几个版本的python都报这个

**Comment by zhayujie** [comment]
你是什么操作系统，试了哪些python版本呢？看起来像系统没有安装openssl模块，可以加下我帮你看看具体原因

**Comment by fountainhead-gq** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) 试了好几个版本的python都报这个

@tlome 这个报错后来是怎么解决的

**Comment by jackzhujie** [comment]
> 

windows
