### ISSUE TITLE
关于timetask

### ISSUE THREAD

**Issue by rexinshimin0001** [zhayujie/chatgpt-on-wechat#1802]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

请问time task插件是不能用了么，安装后发现日志显示已执行，但实际上并没有任何操作，比如执行几点告诉我该吃饭了，日志显示检测到几点有计划，已完成执行，但实际并没有提示，还有就是，有没有歌曲插件，我是找到一个网易云的插件，但是在网易云api的地方发现api弄不了，项目不能用了，有没有其他的或者是我搞错了，谢谢

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by rexinshimin0001** [comment]
还有个小问题，我怀疑是不是我插件装多的原因，我的godcmd 口令明明设置了，但是，登录的时候，提示我没有设置口令，临时口令为XXXX ,不知道有没有同样问题的是怎么解决的，

**Comment by swumagic** [comment]
作者的插件有BUG

**Comment by 6vision** [comment]
> 还有个小问题，我怀疑是不是我插件装多的原因，我的godcmd 口令明明设置了，但是，登录的时候，提示我没有设置口令，临时口令为XXXX ,不知道有没有同样问题的是怎么解决的，

  应该是godcmd配置文件没生效，或者有参数问题，可以重新从模板文件复制

**Comment by 6vision** [comment]
> ### 前置确认
> * [x]  我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。
> 
> ### ⚠️ 搜索issues中是否已存在类似问题
> * [x]  我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
> 
> ### 操作系统类型?
> Linux
> 
> ### 运行的python版本是?
> python 3.8
> 
> ### 使用的chatgpt-on-wechat版本是?
> Latest Release
> 
> ### 运行的`channel`类型是?
> wx(个人微信, itchat)
> 
> ### 复现步骤 🕹
> 请问time task插件是不能用了么，安装后发现日志显示已执行，但实际上并没有任何操作，比如执行几点告诉我该吃饭了，日志显示检测到几点有计划，已完成执行，但实际并没有提示，还有就是，有没有歌曲插件，我是找到一个网易云的插件，但是在网易云api的地方发现api弄不了，项目不能用了，有没有其他的或者是我搞错了，谢谢
> 
> ### 问题描述 😯
> _No response_
> 
> ### 终端日志 📒
> ```
> <此处粘贴终端日志>
> ```
启动后可以发送 #reloadp timetask  试一下，还不行的话，可能是插件有问题，可以到插件仓库提一下issue
