### ISSUE TITLE
启动后到Email初始化时就停住了，要等好几分钟才继续

### ISSUE THREAD

**Issue by xinggonglie** [zhayujie/chatgpt-on-wechat#1804]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

启动后，初始化到email这里就停住了，要等好几分钟才会继续下去，如果只安装核心依赖，没有这个问题

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/109005556/621a0e6d-66bb-4df6-9608-d61b888f7cc8)

### 终端日志 📒

```log
<![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/109005556/6083e9bf-dae9-4689-a2b6-0582e8487480)>
```

**Comment by mashagua** [comment]
这个email 提示没有email_sender,我在tool里的这个config.json里面也写了email_sender:****.qq.com,为什么还是提示email_sender错误

**Comment by mashagua** [comment]
@xinggonglie 这个发送邮件是怎么弄的？
