### ISSUE TITLE
企业微信回调接口的地址问题

### ISSUE THREAD

**Issue by doscriptsite** [zhayujie/chatgpt-on-wechat#1813]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

other

### 复现步骤 🕹

企业微信的回调url格式为：http://ip:port/wxcomapp ，在某些版本的nginx下使用反向代理，会自动在末尾加上反斜杠/，导致404

### 问题描述 😯

如果把监听的path末尾加上反斜杠，统一规范path格式，可以兼容全部nginx反向代理配置。[详见url配置](https://github.com/zhayujie/chatgpt-on-wechat/blob/2074f27aff7c18e3adb286ed2578af5639ce6efc/channel/wechatcom/wechatcomapp_channel.py#L47)

**Comment by 6vision** [comment]
该问题会在 #2163 中优化
