### ISSUE TITLE
mj画图指令报错

### ISSUE THREAD

**Issue by rexinshimin0001** [zhayujie/chatgpt-on-wechat#1814]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[WARNING][2024-03-14 15:55:34][midjourney.py:293] - send() takes 3 positional arguments but 4 were given

### 问题描述 😯

[WARNING][2024-03-14 15:55:34][midjourney.py:293] - send() takes 3 positional arguments but 4 were given

### 终端日志 📒

![Uploading c8c82534ee5e5be7e8e8c079d220dec.png…]()

**Comment by 7tinghua** [comment]
你是用自己的mj api 还是接linkai的？

**Comment by rexinshimin0001** [comment]
linkai的，自己的封了

> 你是用自己的mj api 还是接linkai的？

**Comment by 6vision** [comment]
现在没遇到这个问题，应该正常了吧，如果还有问题，可以留言

**Comment by rexinshimin0001** [comment]
> 现在没遇到这个问题，应该正常了吧，如果还有问题，可以留言

正常了
