### ISSUE TITLE
登录后输出了很多日志不知道是什么原因求解决

### ISSUE THREAD

**Issue by He0607** [zhayujie/chatgpt-on-wechat#1820]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

登录后就输出了非常多的跟以下日志的代码

### 终端日志 📒

[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 3270323365326021296 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 50546770603946063 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 7467707595724703003 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 5428519573585622919 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 1428863536260184919 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 8870226517755524663 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 3439969981622185778 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 1970367947927931380 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 6331026815078733142 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 7108069454428723231 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 7957345535600069397 already received, ignore
[INFO][2024-03-18 14:58:25][wechat_channel.py:55] - Wechat message 4300301017866913873 already received, ignore

**Comment by He0607** [comment]
这个修改了的确是不出错了但这些消息都直接全部发出来了，这个有什么办法解决掉吗，我感觉好像是登陆后如何我之前发的消息的缓存文件就又都全部执行了一遍

**Comment by He0607** [comment]
@6vision

**Comment by 6vision** [comment]
> 这个修改了的确是不出错了但这些消息都直接全部发出来了，这个有什么办法解决掉吗，我感觉好像是登陆后如何我之前发的消息的缓存文件就又都全部执行了一遍

添加上边的配置后，根目录的itchat.pkl文件删除了，再启动试试

**Comment by He0607** [comment]
感谢感谢解决掉了不是那个配置文件的问题，好像就是好兄弟你提出的这个itchat.pkl文件的问题，这个删除了就没有了非常感谢
