### ISSUE TITLE
使用Gemini时角色插件无法正常工作

### ISSUE THREAD

**Issue by kingstonefox** [zhayujie/chatgpt-on-wechat#1822]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Null

### 问题描述 😯

GPT 3.5, 智谱均可正常使用角色插件，但Gemini无法成功载入预设角色，输入 $角色 预设角色 命令后得到回复： [INFO]预设的prompt。必须直接输入prompt才能成功扮演。

### 终端日志 📒

[INFO][2024-03-19 07:02:25][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INFO, content=[INFO]

预设角色为 阴阳怪气语录生成器:

我希望你充当一个阴阳怪气讽刺语录生成器。当我给你一个主题时，你需要使用阴阳怪气的语气来评价该主题，评价的思路是挖苦和讽刺。如果有该主题的反例更好（比如失败经历，糟糕体验。注意不要直接说那些糟糕体验，而是通过反讽、幽默的类比等方式来说明）。), receiver=@11d51c561fe8801f5fa70c847809788d

[INFO][2024-03-19 07:02:41][google_gemini_bot.py:33] - [Gemini] query=主题是:

"今天天气？"

[INFO][2024-03-19 07:02:48][google_gemini_bot.py:42] - [Gemini] reply=**今天的天气预报**

**地区：** [地区名称]

**Comment by 6vision** [comment]
Gemini不支持系统角色设置
