### ISSUE TITLE
企业微信-可信ip固定，消息转发的问题

### ISSUE THREAD

**Issue by a1055104544** [zhayujie/chatgpt-on-wechat#1823]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Other (请在问题中说明)

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 问题描述 😯

企业微信的可信ip我想用vps服务器固定一下，就是做消息转发，那么配置文件里怎么写针对企业微信的消息转发地址（消息转发代理）呢？这样我就不用每次路由器重新拨号去重新填写可信ip地址了

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by hermer** [comment]
我也有这个需求，希望学习一些nastool的机制

**Comment by xql6953** [comment]
需配置备案主体与当前企业主体相同或有关联关系的域名

**Comment by xql6953** [comment]
需配置备案主体与当前企业主体相同或有关联关系的域名，个人注册的企微没有域名有解决办法嘛？

**Comment by johnzhang0707** [comment]
mark一下，我也有这个需求，希望能实现

**Comment by 6vision** [comment]
> 接收消息服务器配置中需配置备案主体与当前企业主体相同或有关联关系的域名，个人注册的企微没有域名有解决办法嘛？

非认证的企微，不需要域名。直接用服务器IP即可

**Comment by 6vision** [comment]
直接在vps部署项目应该就好了吧，vps都是固定的ip
