### ISSUE TITLE
如何引入知识库或者QA集进行RAG?

### ISSUE THREAD

**Issue by RainFung** [zhayujie/chatgpt-on-wechat#1824]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

实现自定义的客服机器人

### 举例

如何引入知识库或者QA集进行RAG?
是否有demo或者插件可以直接使用, 之前的方案都是基于langchain本地实现的

### 动机

如何引入知识库或者QA集进行RAG?
是否有demo或者插件可以直接使用, 之前的方案都是基于langchain本地实现的

**Comment by QAbot-zh** [comment]
linkAI ?

**Comment by nianyi-778** [comment]
> linkAI ?

除此之外还有吗？

**Comment by kuangdd2024** [comment]
这个项目可以作为参考，已经实现了RAG功能，用作对话记录的搜索，从而实现记忆提取。

项目：
https://github.com/kuangdd2024/wechatgpt-agent

About：
chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。
