### ISSUE TITLE
什么时候能支持kimi的api？

### ISSUE THREAD

**Issue by pgciq** [zhayujie/chatgpt-on-wechat#1828]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

https://api.moonshot.cn

**Comment by suyu0925** [comment]
kimi(moonshot) +1

顺便，上面的地址失效了，api文档的新地址：
[api文档](https://platform.moonshot.cn/docs/api-reference)

**Comment by withlin** [comment]
+1

**Comment by a512154224** [comment]
> kimi(moonshot) +1，moonshot的api兼容openai的api，支持起来应该很容易
> 
> 顺便，上面的地址失效了，api文档的新地址： [api文档](https://platform.moonshot.cn/docs/api-reference)

kimi兼容chatgpt的API 的输入和输出，直接修改config.json即可使用：
OPEN_AI_API_KEY: 'kimi的Key'
MODEL: 'kimi的模板'
"open_ai_api_base": "https://api.moonshot.cn/v1"

**Comment by 6vision** [comment]
#1849 已支持
