### ISSUE TITLE
有个明显的bug：引用bot库时会引用到bot文件夹下的bot.py文件，导致引用失败

### ISSUE THREAD

**Issue by lwg712176** [zhayujie/chatgpt-on-wechat#1830]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

直接看chat_gpt_bot.py，google_gemini_bot.py等文件的前几行代码就可以了

### 问题描述 😯

项目中文件夹也叫bot，然后文件下方有个py文件也叫bot，我们调用时有些时候是需要我想调用文件夹名bot，有时候是bot.py，所以建议把bot.py重命名成bot1.py，然后全局替换一下，修改引用到的几个地方，我改完后引用问题都解决了
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/93820791/d990de74-ce75-4ca2-9621-1f0dac22effd)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/93820791/a26b2ef7-d85f-4f2f-929f-8b070fc2cf2b)

### 终端日志 📒

```log
<此处粘贴终端日志>
```无需日志

**Comment by 6vision** [comment]
不是bug，可以正常使用，为明显区分确实可以考虑区别命名
