### ISSUE TITLE
如何解决微信AI机器人频繁断开和记忆丢失问题

### ISSUE THREAD

**Issue by MILKMILKKING** [zhayujie/chatgpt-on-wechat#1838]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

1. 频繁的自动断开问题：每次成功通过扫码登录后，AI机器人能够正常接管微信回复。但问题是这种连接状态并不稳定，大约每一到两天连接就会自动断开（我的备用机，也开了手机的4G和wifi，应该不是网络问题。不过微信号是新号，但是我也实名制和绑了银行卡），桌面版微信会自动退出登录。所以我不得不再扫码登录，请问这种频繁断开的情况是否属于正常现象？如果不是，应该如何操作或设置，以确保连接状态更加稳定，从而延长在线时间？

2. 记忆丢失问题：因为经常会自动断开，它会清空失去之前交谈内容的记忆。请问，有没有办法在重新扫码登录后，让AI机器人依然能保持对之前聊天内容的记忆？

**Comment by QAbot-zh** [comment]
那就得把对话内容缓存到本地，响应时再加载记忆了

**Comment by lei195827** [comment]
写一个定时回复的插件能保持活跃度，就是没隔一小时到两小时之间回复一次，这样可以运行隔十几二十天不掉线，但掉线的问题依然无法解决

**Comment by MILKMILKKING** [comment]
> 写一个定时回复的插件能保持活跃度，就是没隔一小时到两小时之间回复一次，这样可以运行隔十几二十天不掉线，但掉线的问题依然无法解决

谢谢你，如果能保持4~5天就行了，现在1~2天掉线一次，有点折腾。
请问你有这个定时回复的插件吗？如果有的话，方便分享给我吗？非常感谢!

**Comment by azz212** [comment]
建议换个wx机器人，ipad协议稳定

**Comment by MILKMILKKING** [comment]
> 建议换个wx机器人，ipad协议稳定

请问你的意思是，用ipad登陆，作为机器人吗？

**Comment by azz212** [comment]
> > 建议换个wx机器人，ipad协议稳定
> 
> 请问你的意思是，用ipad登陆，作为机器人吗？

是的，已经增加ipad协议 channel，非常稳定 wx rongdhui

**Comment by liuzp19850130** [comment]
@MILKMILKKING 问题解决了吗

**Comment by MILKMILKKING** [comment]
> @MILKMILKKING 问题解决了吗

算是解决了。感谢关注，我用了上面的建议定时回复的插件能保持活跃度，这样大概能保持个十天左右了。

**Comment by liuzp19850130** [comment]
> > @MILKMILKKING 问题解决了吗
> 
> 算是解决了。感谢关注，我用了上面的建议定时回复的插件能保持活跃度，这样大概能保持个十天左右了。

啥插件，能分享一下吗，老哥

**Comment by liuzp19850130** [comment]
@MILKMILKKING 能分享一下插件吗，老哥

**Comment by MILKMILKKING** [comment]
> @MILKMILKKING 能分享一下插件吗，老哥

      "url": "https://github.com/haikerapples/timetask.git",
      "desc": "一款定时任务系统的插件"

**Comment by azz212** [comment]
https://github.com/azz212/chatgpt-on-wechat-ipad 底层Ipad协议

**Comment by Namarimizu** [comment]
> > @MILKMILKKING 能分享一下插件嗎，老哥
> 
> ```
>   "url": "https://github.com/haikerapples/timetask.git",
>   "desc": "一款定時任務系統的插件"
> ```

我定時回覆用了一陣子被封了…… 間隔是2小時

**Comment by 6vision** [comment]
开源项目使用的协议比较老旧，掉线不稳定问题没法彻底解决，可以尝试其他协议，企业使用的话可以使用商用稳定版，查看[企业服务](https://github.com/zhayujie/chatgpt-on-wechat?tab=readme-ov-file#%E4%BC%81%E4%B8%9A%E6%9C%8D%E5%8A%A1)

**Comment by JAHSEH618** [comment]
> > > @MILKMILKKING 能分享一下插件嗎，老哥
> > 
> > 
> > ```
> >   "url": "https://github.com/haikerapples/timetask.git",
> >   "desc": "一款定時任務系統的插件"
> > ```
> 
> 我定時回覆用了一陣子被封了…… 間隔是2小時

可以用iPhone的快捷指令，定时回复

**Comment by ccsdfsdzxces** [comment]
@JAHSEH618 

> > > @MILKMILKKING 能分享一下插件嗎，老哥
> > 
> > 
> > ```
> >   "url": "https://github.com/haikerapples/timetask.git",
> >   "desc": "一款定時任務系統的插件"
> > ```
> 
> 我定時回覆用了一陣子被封了…… 間隔是2小時

微信号被封了？？
