### ISSUE TITLE
终端生成的二维码不全

### ISSUE THREAD

**Issue by ly-ally** [zhayujie/chatgpt-on-wechat#184]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
![7aeb83b064056c883b2f1d5f356807c](https://user-images.githubusercontent.com/59250986/218292172-99039bfc-000e-41ba-a618-d9b0fb406da9.png)

[在此处粘贴终端日志]
```
![7aeb83b064056c883b2f1d5f356807c](https://user-images.githubusercontent.com/59250986/218292172-99039bfc-000e-41ba-a618-d9b0fb406da9.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
see #134

**Comment by ly-ally** [comment]
跟我一样
