### ISSUE TITLE
以正常运行，能收到对方的信息，可是没有任何回复

### ISSUE THREAD

**Issue by cq134cq** [zhayujie/chatgpt-on-wechat#1840]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

重新安装

### 问题描述 😯

以正常运行，能收到对方的信息，可是没有任何回复
Start auto replying.
[INFO][2024-03-26 08:41:42][bridge.py:51] - create bot chatGPT for chat
[INFO][2024-03-26 08:41:42][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[INFO][2024-03-26 08:42:53][chat_gpt_bot.py:49] - [CHATGPT] query=你是谁
[INFO][2024-03-26 08:43:20][chat_gpt_bot.py:49] - [CHATGPT] query=HI

### 终端日志 📒

```log
<此处粘贴终端日志>
Start auto replying.
[INFO][2024-03-26 08:41:42][bridge.py:51] - create bot chatGPT for chat
[INFO][2024-03-26 08:41:42][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[INFO][2024-03-26 08:42:53][chat_gpt_bot.py:49] - [CHATGPT] query=你是谁
[INFO][2024-03-26 08:43:20][chat_gpt_bot.py:49] - [CHATGPT] query=HI

**Comment by Fanyue1227** [comment]
APIkey有问题

**Comment by 6vision** [comment]
网络不通，可以试试 #2147
