### ISSUE TITLE
azure的dall-e-3生成图片失败

### ISSUE THREAD

**Issue by 991547436** [zhayujie/chatgpt-on-wechat#1848]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

![QQ截图20240327150220](https://github.com/zhayujie/chatgpt-on-wechat/assets/15355274/fe7673d2-3767-4ece-ae71-1c2617caf751)

### 问题描述 😯

提示{'error': {'code': '404', 'message': 'Resource not found'}}，通过sdk调用正确取图片的地址和参数如下，供参考

 api_version = "2024-02-01"
    url = "{}openai/deployments/dall-e-3/images/generations?api-version={}".format("https://xxx.openai.azure.com/", api_version)
    api_key = api_key or openai.api_key
    headers = {"api-key": api_key, "Content-Type": "application/json"}
    logger = logging.getLogger(__name__)
    try:
        print(url)
        body = {"prompt": query, "model": "dall-e-3"}
        submission = requests.post(url, headers=headers, json=body)
        print()
        if "error" in submission.json():
            return False, "图片生成失败" + submission.json()["error"]["message"]
        else:
            image_url = submission.json()["data"][0]["url"]
        print(image_url)
        return True, image_url
    except Exception as e:
        logger.error("create image error: {}".format(e))
        return False, "图片生成失败"

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by mikaelfun** [comment]
+1，官方的代码更新了，需要适配下

https://learn.microsoft.com/en-us/azure/ai-services/openai/dall-e-quickstart?tabs=dalle3%2Ccommand-line&pivots=programming-language-python#generate-images-with-dall-e
