### ISSUE TITLE
新建的微信群依然无法触发api

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#185]
前置确认
运行于国内网络环境，使用了vpn
python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
在已有 issue 中未搜索到类似问题
[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
问题描述

简要说明、截图、复现步骤等，也可以是需求或想法
加了这个助手好友以后可以单独聊天，但是如果拉一个新的小群的话，@助手 没有响应
"group_name_white_list": ["ALL_GROUP"]
如果任意修改群名后，会有响应，怀疑是新拉的小群群名可能是null？
有一点值得注意的是，我的助手设置的是可以免验证同意好友申请。所以我申请加它好友就自动通过了。

终端日志 (如有报错)
无报错，正常的对话都可以有回复，但是新拉群的话，没有触发api
"group_name_white_list": ["ALL_GROUP"]
log里没有出现对应的query message

环境
操作系统类型 (Mac/Windows/Linux)：mac
Python版本 ( 执行 python3 -V )： 3.10.9
pip版本 ( 依赖问题此项必填，执行 pip3 -V)：pip 22.3.1

**Comment by zhayujie** [comment]
有获取最新代码吗

**Comment by bboychencan** [comment]
没有 抱歉

**Comment by bboychencan** [comment]
依然没有解决
设置了白名单 "group_name_white_list": ["ALL_GROUP"],
新拉的群，如果不修改群名称依然无回复

**Comment by bboychencan** [comment]
拉了最新的代码，新建的群不改群名称，还是无法触发

**Comment by Kalpeny** [comment]
是的，微信群名不能是未命名

**Comment by vpegasus** [comment]
新建的群，改名后，也不行，是什么情况？

**Comment by vpegasus** [comment]
@zhayujie  麻烦看下呗，谢谢

**Comment by zhayujie** [comment]
> @zhayujie 麻烦看下呗，谢谢

群名就叫 ChatGPT 吗，  不行就把群名改成别的，再改回来试试
