### ISSUE TITLE
回复的时候为什么要搞一堆的  ** （星号）？

### ISSUE THREAD

**Issue by ieiian** [zhayujie/chatgpt-on-wechat#1850]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

语音回复的时候一堆(**)星号星号星号...听得我头上一堆星星🌟，我用的是Gemini，我以为Gemini就是这样，上原版看发现并没有，这个希望可以修正一下...

### 举例

\*\*健康方面：\*\*

\* 注意肠胃健康，避免暴饮暴食。
\* 适度运动，增强体质。
\* 戒烟限酒，保持健康的生活方式。

\*\*事业方面：\*\*

\* 保持积极进取的心态，把握机遇。
\* 避免冲动行事，三思而后行。
\* 注意人际关系，与同事和领导保持良好互动。

\*\*财运方面：\*\*

\* 谨慎投资，避免盲目跟风。
\* 开源节流，合理规划财务。
\* 防范破财，注意保管贵重物品。

**Comment by QAbot-zh** [comment]
你以为原版没有，但实际上有，只是网页给你做了渲染，而微信老老实实把文本给你呈现出来而已，两个**包裹表示加粗:

|原版文本|渲染效果|
|---|----|
|\*\*健康\*\*| **健康**|
|\*健康\*| *健康*|
|\~\~健康\~\~| ~~健康~~|

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/40236765/82b8b3cf-2fa6-42ee-bf32-a9c08809fca8)

**Comment by spacex-3** [comment]
加粗

**Comment by Amazingzl** [comment]
不就是正常的markdown语法么

**Comment by ieiian** [comment]
> 你以为原版没有，但实际上有，只是网页给你做了渲染，而微信老老实实把文本给你呈现出来而已，两个**包裹表示加粗:
> 
> 原版文本	渲染效果	格式
> **健康**	**健康**	粗体
> *健康*	_健康_	斜体
> ~~健康~~	~健康~	划去文本
> ![image](https://private-user-images.githubusercontent.com/40236765/317202424-82b8b3cf-2fa6-42ee-bf32-a9c08809fca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDk5MjcsIm5iZiI6MTcxMjA0OTYyNywicGF0aCI6Ii80MDIzNjc2NS8zMTcyMDI0MjQtODJiOGIzY2YtMmZhNi00MmVlLWJmMzItYTljMDg4MDlmY2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA5MjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNWJhMTUzYmZkNWMzZGVkZDZhYmM3YThmNDVjMjQwYmJmYjg0ZDJmZDgwMzgzODc3NTY3NmMxMTcyNTUzNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mRzjhu1Ki4Xqo2cLsFz75hjyUE2unnJCZFsZGI1zZrg)

是的，你说的对，只是希望可以修正一下😃

**Comment by finexss** [comment]
我觉得在微信里完全可以把回复的*~符号都给过滤掉，微信端不支持这样的格式显示。

**Comment by ShinJiEDU** [comment]
你在prompt里直接说不要用markdown形式回答问题不就行了

**Comment by 6vision** [comment]
在应用设定，或者系统提示词加一句，输出不要使用markdown格式，可以极大概率降低markdown格式输出(即输出星号)
