### ISSUE TITLE
阿里千问修改了鉴权方式

### ISSUE THREAD

**Issue by XiaoChouYou** [zhayujie/chatgpt-on-wechat#1852]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

通义千问无法获取新的 agent_key

### 举例

2024-03-18 10:36:43
为了提升API/SDK调用的便捷性和安全性，新版本系统进行了升级，采用更为简洁高效的API-KEY认证机制。取代了原有的Access Key和Access Key Secret认证方式。

API-KEY的获取方式请参考文档[获取API-KEY](https://help.aliyun.com/document_detail/2712195.html)。

**Comment by wangxyd** [comment]
获取方式调整了：
主账号访问阿里云百炼 - 右上角头像 - 业务空间管理中，即可看到AgentKey

**Comment by anthonywjq2018** [comment]
有解决方案吗？目前也卡在这里，
      qwen_access_key_id: "主账号AK"
      qwen_access_key_secret: "主账号SK"
      qwen_agent_key: "API-KEY"
      qwen_app_id: "应用ID"

**Comment by zzl-myh** [comment]
> 修改 qwen_agent_key: "API-KEY" 为 qwen_api_key: "API-KEY"

这个成功了吗，项目配置里也得修改吧？成功了吗？

**Comment by StevenLOL** [comment]
？ 所以 qwen 该怎么配置？手头只有  API-KEY ，   使用 "dashscope_api_key":  ？ 这个调用时报错

**Comment by 6vision** [comment]
#1851 已更新支持
