### ISSUE TITLE
通义千问模型，收到微信消息后会报错

### ISSUE THREAD

**Issue by EchoXBR** [zhayujie/chatgpt-on-wechat#1858]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

接收到消息后报错，截图如下
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/10279085/29cc2ab3-f070-4dc2-9785-7240d3237665)
阿里检测该requestID 显示没问题
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/10279085/6b1275bb-afdc-4607-ae6d-5e14cba7e71a)
配置如下
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/10279085/75638a96-1d47-4487-a973-bd5fd95f09bc)

### 问题描述 😯

收到微信消息后会报错

### 终端日志 📒

```log
 raise RuntimeError("create token error, code=%s, message=%s RequestId: %s"
RuntimeError: create token error, code=Forbidden, message=User not authorized to operate on the specified resource. RequestId: 33C627E4-D774-5A57-B23C-427A06A36195
```

**Comment by deand0997** [comment]
阿里云百炼的API接口最近更新了，估计还没有来来得及匹配

**Comment by wangxyd** [comment]
AccessKey的RAM授权不对啊，要AliyunSFMFullAccess(管理阿里云百炼（SFM）的权限)

**Comment by zzl-myh** [comment]
给了ram权限还是不行啊
，有解决办法吗？

**Comment by Zhang-Jikang** [comment]
> 给了ram权限还是不行啊 ，有解决办法吗？

请问解决了吗 遇到了同样的问题

**Comment by Asus-Github** [comment]
> > 给了ram权限还是不行啊 ，有解决办法吗？
> 
> 请问解决了吗 遇到了同样的问题
 请问解决了吗 遇到了同样的问题

**Comment by qshf** [comment]
"channel_type": "wx",
  "model": "qwen-max",
  "dashscope_api_key": "sk-7xxxxxxxxxxxx",
  看了一点源码，这么改，至于那个阿里云那个我的应用那个，我是改了部分源码

**Comment by Asus-Github** [comment]
> "channel_type": "wx", "model": "qwen-max", "dashscope_api_key": "sk-7xxxxxxxxxxxx", 看了一点源码，这么改，至于那个阿里云那个我的应用那个，我是改了部分源码

已解决 感谢大佬

**Comment by 6vision** [comment]
#1851 已支持最新版千问调用
