### ISSUE TITLE
我想问一下，发送邮件或者短信的tool怎么配置，以及在界面上怎么使用

### ISSUE THREAD

**Issue by mashagua** [zhayujie/chatgpt-on-wechat#1859]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

我在输入框中输入
$tool 发送邮件 to:993498039@qq.com subject:"测试邮件" body:"你好"

返回:
[bot] 你好，请收件人地址为993498039@qq.com，主题是'测试邮件'，正文内容为'你好'

收件人：993498039@qq.com
主题：'测试邮件'

正文：你好
但是我的邮箱并没有收到邮件，请问这个是怎么回事？我应该怎么调整才能让它发送邮件

### 问题描述 😯

另外，我已经填写了那个email_code,

### 终端日志 📒

```log
Context(type=TEXT, content=$tool 发送邮件 to:993498039@qq.com subject:"测试邮件" body:"你好", kwargs={})
[INFO][2024-03-28 15:53:01][victorinox.py:108] - 提问: 发送邮件 to:993498039@qq.com subject:"测试邮件" body:"你好"
[INFO][2024-03-28 15:53:09][base.py:223] - LLM-OS想和你说：我会尽力帮助你解答其他问题！
[INFO][2024-03-28 15:53:09][base.py:229] - LLM-OS的内心独白: 
推理：由于用户在使用'mail'工具时遇到了问题，我需要提醒用户这个问题可能无法通过当前工具解决，建议用户寻求其他人的帮助。同时，我可以告诉用户我将会尽力帮助他们解答其他问题.
思考：嗨！看起来你正在使用一个叫做'mail'的工具，想发送一封邮件。然而很抱歉，我刚刚检查了一下，这个工具插件目前似乎无法解决这个问题。你可以尝试等待一下，或者寻求其他人的帮助。不过如果你有其他问题，我会尽力帮你解答的哦！
反思：目前我无法直接帮助用户发送邮件，因为'mail'工具的使用受到了限制。但我可以提醒用户寻求其他人的帮助。

[INFO][2024-03-28 15:53:09][base.py:116] - 输入: 你好，请收件人地址为993498039@qq.com，主题是'测试邮件'，正文内容为'你好'

收件人：993498039@qq.com
主题：'测试邮件'

正文：你好
[INFO][2024-03-28 15:53:10][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 你好，请收件人地址为993498039@qq.com，主题是'测试邮件'，正文内容为'你好'

收件人：993498039@qq.com
主题：'测试邮件'
```

**Comment by 6vision** [comment]
可以到tool插件作者仓库反馈咨询一下
