### ISSUE TITLE
对话上下文信息能存多久？

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#186]
我在群里跟它做自我介绍，开始他还记得我，但是几个回合后，他似乎就忘记了那些信息

**Comment by zhayujie** [comment]
上下文有限制  #43

**Comment by bboychencan** [comment]
这个字数最大可以设到多大呢？ 另外同一个key，在不同群里被at，那么他的上下文字数是综合还是单算的？

**Comment by zhayujie** [comment]
> 这个字数最大可以设到多大呢？ 另外同一个key，在不同群里被at，那么他的上下文字数是综合还是单算的？

最好不要超过1500。  上下文是按发送消息的微信用户 算的

**Comment by 1183747933** [comment]
大佬，有没有考虑过用多key的方法，一个作为总结用，一个作为生成内容用，这样可以存储多一些数据，或者创建个本地临时文件储存一定token信息

**Comment by zhayujie** [comment]
> 大佬，有没有考虑过用多key的方法，一个作为总结用，一个作为生成内容用，这样可以存储多一些数据，或者创建个本地临时文件储存一定token信息

你说的总结是指让chatgpt来总结嘛

存储多的数据貌似没用，因为会话最多只能4096token

**Comment by 1183747933** [comment]
感谢回复，我看见有一个叫chuanhuchatgpt的项目，里面有一个一键优化token的功能，经常想和ai聊很久，却一下子就要清楚记忆了。（请问大佬有交流方式吗）

**Comment by 1183747933** [comment]
好像那个项目的优化方式是和revChatGPT有关
