### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=6aqbsFfDBnDTjgvH&skey=@crypt_7f17dd09_d375657bd960c418d603f9ad2a0404fd&pass_ticket=Gyke0g9JcdELTmJ%2FWti4CrMrTpM8uNjdfXA1bPDeNyeE29ARPEDNLBcCoz%2Fllpo4gWUA7qXoNMO9wEuXzOHr%2FQ%3D%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

### ISSUE THREAD

**Issue by huangjeake** [zhayujie/chatgpt-on-wechat#1861]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=6aqbsFfDBnDTjgvH&skey=@crypt_7f17dd09_d375657bd960c418d603f9ad2a0404fd&pass_ticket=Gyke0g9JcdELTmJ%2FWti4CrMrTpM8uNjdfXA1bPDeNyeE29ARPEDNLBcCoz%2Fllpo4gWUA7qXoNMO9wEuXzOHr%2FQ%3D%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

### 问题描述 😯

大佬们，在win运行代码的时候，一直有个报错就是微信登录报错requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=6aqbsFfDBnDTjgvH&skey=@crypt_7f17dd09_d375657bd960c418d603f9ad2a0404fd&pass_ticket=Gyke0g9JcdELTmJ%2FWti4CrMrTpM8uNjdfXA1bPDeNyeE29ARPEDNLBcCoz%2Fllpo4gWUA7qXoNMO9wEuXzOHr%2FQ%3D%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))，这要怎么修改啊？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by xifeng-li** [comment]
我也是这样的
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/69239944/6a005985-e418-41cf-a7a2-d82882e3792f)

**Comment by 6vision** [comment]
代理开规则模型，不要全局
