### ISSUE TITLE
公众号服务器配置出现403 Forbidden

### ISSUE THREAD

**Issue by lzl2040** [zhayujie/chatgpt-on-wechat#1867]
### 前置确认

- [x] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

参考[官方教程](https://docs.link-ai.tech/cow/multi-platform/wechat-mp)，config.json中wechatmp_token没有填写，因为这个要服务器配置完成才有

### 问题描述 😯

在服务器配置时显示系统错误，同时服务器端显示403 forbidden
![1](https://github.com/zhayujie/chatgpt-on-wechat/assets/59819857/da182587-fd8b-48e9-b18b-2c24d7b6c690)

### 终端日志 📒

![2](https://github.com/zhayujie/chatgpt-on-wechat/assets/59819857/6534a2e0-df07-4224-b3a7-1d393112aac1)

**Comment by 6vision** [comment]
wechatmp_token是自定义的，在json文件配置后，运行项目

**Comment by F1ncyJ** [comment]
映射了json.config，日志也输出的wechatmp_token， 但是公众号配置还是出现错误， 403

**Comment by AprilTong** [comment]
遇到同样的问题，token等已配置
