### ISSUE TITLE
elevenlabs的代码需要更新一下

### ISSUE THREAD

**Issue by flyleegit** [zhayujie/chatgpt-on-wechat#1868]
### 前置确认

- [x] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

1.eleven labs的官网，更新sdk后，不支持直接generate操作了，需要client.generate操作~   详见：https://github.com/elevenlabs/elevenlabs-python/tree/main

2.eleven labs的语音合成功能，在目前代码的elevent_voie.py的第31行，会写入失败，因为返回的audio是一个generator

### 终端日志 📒

1.建议在require-optionals里面加上elevenlabs==v1.0.0b1，否则会无法执行eleven labs~ 
2.eleven labs的官网，更新sdk后，不支持直接generate操作了，需要client.generate操作~   详见：https://github.com/elevenlabs/elevenlabs-python/tree/main

2.eleven labs的语音合成功能，在目前代码的elevent_voie.py的第31行，会写入失败，因为返回的audio是一个generator

**Comment by zhayujie** [comment]
已合并
