### ISSUE TITLE
SD生成不报错，但是无法发送到群里。个人微信，请问什么原因呢？

### ISSUE THREAD

**Issue by kvgary** [zhayujie/chatgpt-on-wechat#1878]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

SD生成图没问题，日志显示发送，但是收不到图片。个人微信，请问什么原因呢？

### 终端日志 📒

[INFO][2024-04-05 11:44:50][sdwebui.py:52] - [SD] image_query=一个兔子
[INFO][2024-04-05 11:44:50][sdwebui.py:84] - [SD] keyword not matched: 一个兔子
[INFO][2024-04-05 11:44:50][sdwebui.py:97] - [SD] translate prompt from zh to en
[INFO][2024-04-05 11:44:50][sdwebui.py:102] - [SD] translated prompt=A rabbit
[INFO][2024-04-05 11:44:50][sdwebui.py:105] - [SD] cover options={'sd_model_checkpoint': 'sd_xl_base_1.0.safetensors [31e35c80fc]'}
[INFO][2024-04-05 11:44:51][sdwebui.py:107] - [SD] params={'sampler_name': 'DPM++ 2M Karras', 'steps': 20, 'width': 512, 'height': 512, 'cfg_scale': 7, 'prompt': 'masterpiece, best quality, A rabbit', 'negative_prompt': '(low quality, worst quality:1.4),(bad_prompt:0.8), (monochrome:1.1), (greyscale)', 'enable_hr': False, 'hr_scale': 2, 'hr_upscaler': 'Latent', 'hr_second_pass_steps': 15, 'denoising_strength': 0.7}
[INFO][2024-04-05 11:44:56][wechat_channel.py:237] - [WX] sendImage, receiver=@d6c87e8eebf703d9ddb8fddd457ad937ddef65b9d3bf271831d59bcd25a9da50

**Comment by kvgary** [comment]
chatgpt-on-wechat 与 SD是分开部署的，是不是chatgpt-on-wechat找不到SD生成图片的那个路径，如果是在哪里修改呢？

**Comment by princeGoo** [comment]
同问

**Comment by kvgary** [comment]
@princeGoo 加一行代码，但是频繁发送图片微信会有封控的危险。
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/16883380/dbc33366-e849-4247-9e1c-972fbb000200)

**Comment by taozhiyuai** [comment]
同问，卡在这里

**Comment by eginner01** [comment]
我之前遇到过图片无法发送的，存储成临时图片再转发成功了，你可以试试。

**Comment by 6vision** [comment]
最新代码已修复
