### ISSUE TITLE
无法创建企业微信中的群聊机器人么？

### ISSUE THREAD

**Issue by ixxmu** [zhayujie/chatgpt-on-wechat#1882]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

目前该项目自建应用没有问题，但是无法方便的接入企业微信群机器人。现有的https://github.com/zhayujie/chatgpt-on-wechat/pull/1385 这个issue是需要下载Windows客户端么？看起来比较繁琐；

企业微信后台是可以将自建应用接入群客服的，参考 这里 https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/custom_support_service.md ，所以该项目是否可以考虑用更简单的方式接入群聊客服？

或者已经可以了只是没有详细说明？ 

### 举例

企业微信后台是可以将自建应用接入群客服的，参考 这里 https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/custom_support_service.md

**Comment by dqzboy** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/pull/1761
克隆这个就可以使用了

**Comment by ixxmu** [comment]
> #1761 克隆这个就可以使用了

感谢回复！
看说明中提到无法支持群聊，不知道现在适配了么？

**Comment by dqzboy** [comment]
> > #1761 克隆这个就可以使用了
> 
> 感谢回复！ 看说明中提到无法支持群聊，不知道现在适配了么？

企业微信客服只能私聊，你提到的项目同样不支持

**Comment by ixxmu** [comment]
> > > #1761 克隆这个就可以使用了
> > 
> > 
> > 感谢回复！ 看说明中提到无法支持群聊，不知道现在适配了么？
> 
> 企业微信客服只能私聊，你提到的项目同样不支持

原来是这样，期待大佬的后续迭代,
感谢回复。
