### ISSUE TITLE
可以增加讯飞的语音识别吗

### ISSUE THREAD

**Issue by xinjiprincess** [zhayujie/chatgpt-on-wechat#1885]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

讯飞的语音识别相对更好用。

### 举例

[www.](https://www.xfyun.cn/services/voicedictation)

### 动机

讯飞语音识别对方言识别能力强。

**Comment by 6vision** [comment]
#1999  已支持
