### ISSUE TITLE
各位有碰到性能问题么？

### ISSUE THREAD

**Issue by thinker007** [zhayujie/chatgpt-on-wechat#1887]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

wechatnt

### 问题描述 😯

python3 app.py 启动之后，基本上 python3 进程会占用 99% 的 CPU，想问下为啥。就算是没有消息处理的时候也会占用 CPU

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
可以更新到最新代码试试

**Comment by 7li7li** [comment]
我也是这样，更新到最新的容器版本也会占用100.老哥解决了吗
