### ISSUE TITLE
建议新增gpt-4-turbo-2024-04-09

### ISSUE THREAD

**Issue by ViperGash** [zhayujie/chatgpt-on-wechat#1889]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

建议新增gpt-4-turbo-2024-04-09

**Comment by zhayujie** [comment]
已经支持的，model字段填写 “gpt-4-turbo-2024-04-09” 即可
