### ISSUE TITLE
直接部署在服务器上可以正常运行，但是使用docker部署能正常登录，但机器人收不到信息，拍一拍服务器端有反应，但是不返回消息。

### ISSUE THREAD

**Issue by choupiyang** [zhayujie/chatgpt-on-wechat#1890]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

测试了三次，相同的代码在服务器上直接部署正常使用，再放到docker里就不行。

### 问题描述 😯

![微信截图_20240413034255](https://github.com/zhayujie/chatgpt-on-wechat/assets/15354374/5c49c5d0-caea-4809-8888-197eb9cca4ce)
直接部署在服务器上可以正常运行，但是使用docker部署能正常登录，但机器人收不到信息，拍一拍服务器端有反应，但是不返回消息。

### 终端日志 📒

没有生成出run.log，debug也是true。

**Comment by you-know-m** [comment]
我昨天刚部署，查到问题说是compose里别配置proxy， 配置 open_ai_api_base.   这太坑了
