### ISSUE TITLE
godcmd在认证的时候增加了2次管理员用户id，不确定是如此设计的，还是重复增加了

### ISSUE THREAD

**Issue by smillsion** [zhayujie/chatgpt-on-wechat#1895]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/30746188/6d55ef54-101a-4446-9cb2-c386e7c0e7fe)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/30746188/0076317b-5a7b-40a1-b8df-ab8ebcc8e9f9)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/30746188/9e74b2dd-b65e-4dd3-b67e-5cc2c9305f17)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/30746188/60f72a0b-ac7a-46a7-94f2-5e9c542f68c3)

### 问题描述 😯

在调试开发插件过程中，发现global_config["admin_users"]管理员用户id一直返回2个重复的管理员id，调试godcmd代码发现添加了2次id，不确定是否是特地如此设计的。如果是，希望知道一下参数的使用说明，以便我调试插件。万分感谢

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by smillsion** [comment]
Sry. Python version correct: python 3.7 => python 3.10

**Comment by 6vision** [comment]
是的，看起来是多余的
