### ISSUE TITLE
长时间挂着，会导致消息发送失败

### ISSUE THREAD

**Issue by puboop** [zhayujie/chatgpt-on-wechat#1898]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

挂着微信登录2两天

### 问题描述 😯

挂着微信消息后2两天会出现这个错误，{'BaseResponse': {'Ret': 3, 'ErrMsg': '', 'RawMsg': ''}, 'MsgID': '', 'LocalID': ''} ，我想知道Ret:3是啥意思，正常结果：{'BaseResponse': {'Ret': 0, 'ErrMsg': '请求成功', 'RawMsg': '请求成功'}, 'MsgID': '881602542589238799', 'LocalID': '17132070177876'}

### 终端日志 📒

正常日志：
{'BaseResponse': {'Ret': 0, 'ErrMsg': '请求成功', 'RawMsg': '请求成功'}, 'MsgID': '881602542589238799', 'LocalID': '17132070177876'}
错误日志：
{'BaseResponse': {'Ret': 3, 'ErrMsg': '', 'RawMsg': ''}, 'MsgID': '', 'LocalID': ''}

**Comment by 6vision** [comment]
可以换服务器部署试试
