### ISSUE TITLE
机器人对群成员的@无红色提示

### ISSUE THREAD

**Issue by Plutoisy** [zhayujie/chatgpt-on-wechat#1899]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

机器人回复群成员时的@没有红色提醒也无法定位到@消息

### 问题描述 😯

以下是我触发机器人@和我登录机器人手动@的区别
![49b15eecb3ccbc319cb33096cc2a001](https://github.com/zhayujie/chatgpt-on-wechat/assets/89139849/47b52e38-fecf-454e-aebc-055fab74b200)
![cb17c680b7c40b80da634280c178cef](https://github.com/zhayujie/chatgpt-on-wechat/assets/89139849/a92d0239-37f6-45e8-afa5-6b56a2e2f74f)

**Comment by 6vision** [comment]
是的，项目使用的协议不支持真实的艾特效果
