### ISSUE TITLE
涉及到代码的部分会输出较少甚至会不输出

### ISSUE THREAD

**Issue by 28H2O2** [zhayujie/chatgpt-on-wechat#19]
和使用原本官方的chatGPT有一些区别，比如“对于WNOHANG的用法，可以举一个例子说明吗”，官方网站上会给出一个可以运行的代码并且有提供解释；而这个机器人无法给出代码。比如“给出一个Dijkstra算法C++的例子”，等待了很长时间之后，这个机器人会没有输出。

**Comment by 28H2O2** [comment]
[INFO][2022-12-30 20:01:09][open_ai_bot.py:21] - [OPEN_AI] query=请给出一个Dijkstra算法C++的例子
[INFO][2022-12-30 20:01:11][open_ai_bot.py:37] - [OPEN_AI] reply=

**Comment by zhayujie** [comment]
用官方api 和  chatGPT界面直接对话 在回答质量的稳定性上还是有些差别。 用api咨询代码问题有时候确实没有回复，但换个问法可能又会有回复，不太稳定：
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/26161723/210128319-f919b534-af4b-4b65-b51d-11bc238ee70b.png">
