### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [zhayujie/chatgpt-on-wechat#1902]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

钉钉流式输出&优化钉钉在输出表格会乱码的情况

### 举例

https://open.dingtalk.com/document/orgapp/typewriter-effect-streaming-ai-card
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/32920883/54feeb41-cb4d-4513-9360-c2c0abb4b1f3)

**Comment by baojingyu** [comment]
> 还有就是是以text显示的 并不是markdown

https://github.com/zhayujie/chatgpt-on-wechat/pull/1994
最新的pull request 已支持 Markdown

https://open.dingtalk.com/document/orgapp/typewriter-effect-streaming-ai-card
业务场景：机器人在回复用户消息时根据用户的输入调用大模型后回复一张流式更新内容的 AI 卡片。

交互形态：机器人

开发目标：开发一个 AI 机器人，他可以在收到用户在私聊、群聊中发送给机器人的消息，并根据收到的消息调用大模型获取答复，回复一张 AI 卡片并流式更新卡片内容（打字机效果）。

**Comment by baojingyu** [comment]
> > 还有就是是以text显示的 并不是markdown
> 
> #1994 最新的pull request 已支持 Markdown
> 
> https://open.dingtalk.com/document/orgapp/typewriter-effect-streaming-ai-card 业务场景：机器人在回复用户消息时根据用户的输入调用大模型后回复一张流式更新内容的 AI 卡片。
> 
> 交互形态：机器人
> 
> 开发目标：开发一个 AI 机器人，他可以在收到用户在私聊、群聊中发送给机器人的消息，并根据收到的消息调用大模型获取答复，回复一张 AI 卡片并流式更新卡片内容（打字机效果）。



> 还有就是是以text显示的 并不是markdown

https://github.com/zhayujie/chatgpt-on-wechat/pull/1994
