### ISSUE TITLE
阿里云docker部署，接入个人订阅号，卡在配置微信服务器，非程序员，帮我看看其他可能出错的地方

### ISSUE THREAD

**Issue by cbaoox** [zhayujie/chatgpt-on-wechat#1903]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

阿里云ubuntu 22.04  部署docker,端口80已开放，防火墙关闭，yml已经修改添加微信配置，80映射已执行，运行docker后未见端口监听，且微信端保存服务器配置报错

### 问题描述 😯

<img width="986" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/2591db00-a55b-4da7-8c4e-7fdd05d9967b">
<img width="852" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/f00261a7-d234-4b84-bf4f-e7d0cb31f664">
<img width="922" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/b7150ccb-eda5-4af1-8ea9-7dab09a7aaa0">
<img width="885" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/119645c7-7681-4c02-bcf0-5e60fdaffb69">

### 终端日志 📒

```log
[WARNING][2024-04-18 16:30:12][banwords.py:54] - [Banwords] init failed, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[WARNING][2024-04-18 16:30:12][plugin_manager.py:150] - Failed to init BANWORDS, diabled. [Errno 2] No such file or directory: '/app/plugins/banwords/banwords.txt'
[INFO][2024-04-18 16:30:12][linkai.py:34] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-04-18 16:30:13][tool.py:28] - [tool] inited
[INFO][2024-04-18 16:30:13][role.py:69] - [Role] inited
[INFO][2024-04-18 16:30:13][dungeon.py:56] - [Dungeon] inited
[WARNING][2024-04-18 16:30:13][bdunit.py:42] - [BDunit] init failed, ignore 
[WARNING][2024-04-18 16:30:13][plugin_manager.py:150] - Failed to init BDUNIT, diabled. config.json not found
[INFO][2024-04-18 16:30:13][hello.py:38] - [Hello] inited
[INFO][2024-04-18 16:30:13][finish.py:23] - [Finish] inited
http://0.0.0.0:8080/
[INFO][2024-04-18 16:30:14][client.py:258] - Client no need connect, ignore
```

**Comment by cbaoox** [comment]
<img width="411" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/a2595dda-7553-4f47-b2ba-9e72a920b6c9">
compose文件添加以上端口配置，已经解决了

**Comment by cbaoox** [comment]
我目前已经跑通了遇到的主要问题如下
1、阿里云 ubuntu 22.04 docker环境  安全组中开启80端口
2、微信服务器配置提交时，服务器未开启80报超时，8080未映射80报内部错误，我的映射配置见上个评论。教程中方法我试了没生效
3、compse.yml文件中新增部分注意格式，大小写都可以，单人回复配置只保留一个，格式如下
      single_chat_prefix: '[""]'     # 推荐设置，任意对话都可以触发回复，不添加前缀
      single_chat_reply_prefix: '""' # 推荐设置，回复不设置前缀
4、跑通后台日志显示如下状态
http://0.0.0.0:8080/
[INFO][2024-04-19 03:18:20][client.py:258] - Client no need connect, ignore
81.69.101.237:10666 - - [19/Apr/2024 03:18:43] "HTTP/1.1 GET /wx" - 200 OK

**Comment by Lands-1203** [comment]
@cbaoox 兄弟 docker-compose配置文件发我一份参考参考被 我这边服务启动不起来

**Comment by acDsp** [comment]
同求
