### ISSUE TITLE
当我使用Azure进行语音识别时，出现 Runtime error: Failed to initialize platform (azure-c-shared). Error: 2176

### ISSUE THREAD

**Issue by lemodragon** [zhayujie/chatgpt-on-wechat#1905]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 问题描述 😯

<img width="1122" alt="屏幕截图 2024-04-20 005844" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/88694954/50af1617-da2d-4af7-b014-a9b2038a2db1">
当我使用Azure用作我的企业微信中识别语音，最初错误经Claude分析为来自 Azure 语音服务 SDK 的错误,错误代码为 0xa (SPXERR_INVALID_HEADER)，当我安装了FFmpeg，原先错误不在出现，但出现新的错误

**Comment by lemodragon** [comment]
在https://stackoverflow.com/questions/72751026/how-to-fix-microsoft-cognitive-speech-error-failed-to-initialize-platform-azur
中好像找到了原因，本人使用的是Debian12，在 Ubuntu 22.04 和 Debian 12 的默认设置，Speech SDK 尚不支持 OpenSSL 3.0

**Comment by lemodragon** [comment]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2272中有提到，
Speech SDK 需要使用 Open SSL 1.x 才能运行。这将在未来版本的 Speech SDK 中提供。目前，请按照以下说明在 Linux 环境中编译和部署 Open SSL 1.x： https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-csharp

**Comment by cbaoox** [comment]
重装系统到20.04再试
