### ISSUE TITLE
钉钉

### ISSUE THREAD

**Issue by adminlove520** [zhayujie/chatgpt-on-wechat#1906]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

钉钉channel是否可以支持markdown输出 有的数据 以文本的形式显示有问题  比如表格

**Comment by baojingyu** [comment]
> ### ⚠️ 搜索是否存在类似issue
> * [x]  我已经搜索过issues和disscussions，没有发现相似issue
> 
> ### 总结
> 钉钉channel是否可以支持markdown输出 有的数据 以文本的形式显示有问题 比如表格
> 
> ### 举例
> _No response_
> 
> ### 动机
> _No response_

最新的pull request 已支持Markdown https://github.com/zhayujie/chatgpt-on-wechat/pull/1994
打字机效果流式 AI 卡片
https://open.dingtalk.com/document/orgapp/typewriter-effect-streaming-ai-card
