### ISSUE TITLE
能否在云端有数据库存储对话内容？把微信号收到的信息，以及chatgpt回复的信息都存在云端数据库里

### ISSUE THREAD

**Issue by petersun2019** [zhayujie/chatgpt-on-wechat#1907]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

能否在云端有数据库存储对话内容？把微信号收到的信息，以及chatgpt回复的信息都存在云端数据库里

### 举例

1.用户发信息给 挂了ChatGPT的微信号
2.云端先把这个信息存起来，存入数据库
3.程序把信息发给ChatGPT
4.程序收到ChatGPT回复的信息，也存入数据库
5.程序再把信息通过微信返回给用户

### 动机

动机：这样做可以把交流的内容记录下来，实现知识积累。也便于未来分析，高频率的用户提问

**Comment by 6vision** [comment]
暂未支持，可以按需要自行开发插件实现，参考[插件开发](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins)
