### ISSUE TITLE
使用docker-docker-compos部署的怎么配置插件？只有一个docker-compose.yml文件

### ISSUE THREAD

**Issue by spoony-Z** [zhayujie/chatgpt-on-wechat#1908]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

使用docker-docker-compos部署的怎么配置插件？只有一个docker-compose.yml文件

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zoecsoulkey** [comment]
docker部署的第四步

**Comment by 6vision** [comment]
[docker部署](https://github.com/zhayujie/chatgpt-on-wechat?tab=readme-ov-file#3docker%E9%83%A8%E7%BD%B2)里有写如何配置插件，映射一个config.json文件
