### ISSUE TITLE
Docker 容器的退出状态码为137，无法响应中止信号

### ISSUE THREAD

**Issue by manjieqi** [zhayujie/chatgpt-on-wechat#1910]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

使用docker compose文件启动容器，使用docker stop停止或者重启系统或者docker compose down，cow都是被kill的

### 问题描述 😯

4499cb8b85e6   zhayujie/chatgpt-on-wechat      "/entrypoint.sh"         2 days ago     Exited (137) 6 seconds ago                  cow

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
还有问题的话，可以提供更多log信息

**Comment by manjieqi** [comment]
啊，这个退出问题就是在compose down的时候需要等10秒，说明容器在接受关闭信号以后没有在10秒内自己关闭，而是被强制关闭的。
