### ISSUE TITLE
后端模型支持图片识别、文件或网页总结，但是CoW不处理

### ISSUE THREAD

**Issue by flyinsz** [zhayujie/chatgpt-on-wechat#1911]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

我接入的模型支持图片识别总结、文件和网页总结，但是CoW接收后并不做任何处理，也没有任何日志。

### 问题描述 😯

我接入的模型支持图片识别总结、文件或网页总结，但是CoW接收后并不做任何处理，除非通过插件才行，但是我又不想用插件，该怎么做呢？请大佬们支支招。

### 终端日志 📒

接收到网址、文件或者图片后没有任何日志

**Comment by 6vision** [comment]
支持部分文件类型，收到这些类型的消息没有打日志信息，所以没显示，具体可以看每个channel的channel message
