### ISSUE TITLE
Azure画图提示 create image error: 'operation-location'

### ISSUE THREAD

**Issue by cbaoox** [zhayujie/chatgpt-on-wechat#1912]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

ubuntu docker部署，接入azure，dalle已经部署，compose已经配置，且文本语音对话均已调通
目前画图返回错误
create image error: 'operation-location'

### 问题描述 😯

<img width="473" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/ce4bf373-516e-4ee3-a439-63daf0c541f6">

### 终端日志 📒

```log
http://0.0.0.0:8080/
[INFO][2024-04-22 12:29:28][passive_reply.py:97] - [wechatmp] Request 1 from oYaM96xwiXl6n-cpHHWGJ2g0jNWk 24535556262443689 175.24.211.157:57952
画一幅画
[INFO][2024-04-22 12:29:28][bridge.py:56] - create bot chatGPTOnAzure for chat
[ERROR][2024-04-22 12:29:29][chat_gpt_bot.py:193] - create image error: 'operation-location'
[INFO][2024-04-22 12:29:29][wechatmp_channel.py:85] - [wechatmp] text cached, receiver oYaM96xwiXl6n-cpHHWGJ2g0jNWk
[ERROR]
图片生成失败
[INFO][2024-04-22 12:29:29][passive_reply.py:153] - [wechatmp] Request 1 do send to oYaM96xwiXl6n-cpHHWGJ2g0jNWk 24535556262443689: 画一幅画
[ERROR]
图片生成失败
175.24.211.157:57952 - - [22/Apr/2024 12:29:29] "HTTP/1.1 POST /wx" - 200 OK


```

**Comment by cbaoox** [comment]
docker部署出的问题，群里有相关更新，因为不会改docker里代码，改为服务器部署后修改了dalle3部分的代码及配置项后成功了！

**Comment by chenbe1990** [comment]
@cbaoox  请问如何修改？我也遇到了，只能用旧版本dalle模型,新版就报错。
