### ISSUE TITLE
接入网页版 OpenAI ChatGPT

### ISSUE THREAD

**Issue by wwx221** [zhayujie/chatgpt-on-wechat#1914]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

目前chatGPT只能通过token来进行连接

### 动机

当没有费用后就无法进行使用，能否增加接入到网页版ChatGPT的功能，通过access_token来进行对话

**Comment by Ngwind** [comment]
目前好像没看到有直接"偷"chatgpt网页版的项目。估计有很严格的防机器人验证。
