### ISSUE TITLE
能不能接入 openai的assistant的支持  想使用自己训练的知识库

### ISSUE THREAD

**Issue by Charo7** [zhayujie/chatgpt-on-wechat#1916]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 动机

询问的问题都是基于网络上有的问题 ，想使用自己的知识库

**Comment by aliushn** [comment]
同问

**Comment by 6vision** [comment]
暂时还未支持，如果有需要使用知识库功能，可以试试[快速开始](https://docs.link-ai.tech/platform/quick-start)
