### ISSUE TITLE
最后一步出现这个是什么情况

### ISSUE THREAD

**Issue by lixingtao888** [zhayujie/chatgpt-on-wechat#192]
root@yy:~# nohup python3 app.py & tail -f nohup.out
[1] 29301
python3: can't open file 'app.py': [Errno 2] No such file or directory
python3: can't open file 'app.py': [Errno 2] No such file or directory
python3: can't open file 'app.py': [Errno 2] No such file or directory
nohup: ignoring input and appending output to 'nohup.out'
python3: can't open file 'app.py': [Errno 2] No such file or directory

**Comment by zhayujie** [comment]
执行 pwd 看下当前目录， 需要进入到项目目录下
