### ISSUE TITLE
微信文章反爬策略影响导致无法总结文章链接

### ISSUE THREAD

**Issue by Magnoliar** [zhayujie/chatgpt-on-wechat#1920]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

发送任何微信链接无法总结，显示因为神秘力量无法获取文章内容，请稍后再试吧~

### 问题描述 😯

发送任何微信链接无法总结，显示因为神秘力量无法获取文章内容，请稍后再试吧~

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by LeanFly** [comment]
确实，最近遇到了这个问题，刚才特意试了以下，发送微信公众号内容，都是提示因为神秘力量无法获取内容，请稍后再试吧~

**Comment by Magnoliar** [comment]
> 确实，最近遇到了这个问题，刚才特意试了以下，发送微信公众号内容，都是提示因为神秘力量无法获取内容，请稍后再试吧~

咨询了客服，Docker版更改镜像标签为[master](https://hub.docker.com/layers/zhayujie/chatgpt-on-wechat/master/images/sha256-14985f20a55aae5754a44013118c552ab75bdc3f21233d5367c9a5e55c9e6ebd?context=explore)，重新拉一下更新可用了
