### ISSUE TITLE
接入飞书无法读取文档内容和发送图片给我

### ISSUE THREAD

**Issue by godyii** [zhayujie/chatgpt-on-wechat#1921]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹
1.发送pdf文档和docx文档没有回复
2.告诉他生成图片，生成图片后日志显示图片文件被其他程序占用，无法用飞书发给我，在linkai后台可以看到图片的链接

配置文件
{
  "channel_type": "feishu",
  "model": "gpt-4",
  "open_ai_api_key": "",
  "text_to_image": "dall-e-2",
  "voice_to_text": "openai",
  "text_to_voice": "openai",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": [
    "bot",
    "@bot"
  ],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": [
    "@bot"
  ],
  "group_name_white_list": [
    "ChatGPT测试群",
    "ChatGPT测试群2"
  ],
  "image_create_prefix": [
    "画"
  ],
  "speech_recognition": true,
  "group_speech_recognition": false,
  "voice_reply_voice": false,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
  "temperature": 0.7,
  "subscribe_msg": "感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,
  "linkai_api_key": "",
  "linkai_app_code": "",

  "feishu_port": ,
  "feishu_app_id": "",
  "feishu_app_secret": "",
  "feishu_token": "",
  "feishu_bot_name": "小狗",
  "debug": true 
}

### 问题描述 😯

![微信截图_20240426025326](https://github.com/zhayujie/chatgpt-on-wechat/assets/168128248/a95c50fd-3348-424f-ac34-fa207c19a4d0)

### 终端日志 📒

[INFO][2024-04-26 01:41:36][feishu_channel.py:221] - [FeiShu] query=帮我画一个男孩和女孩在讲话的照片, type=TEXT
220.243.131.172:49434 - - [26/Apr/2024 01:41:36] "HTTP/1.1 POST /" - 200 OK
[INFO][2024-04-26 01:41:36][link_ai_bot.py:121] - [LINKAI] query=帮我画一个男孩和女孩在讲话的照片, app_code=FXi0fIKx, model=gpt-4-turbo, file_id=None
[INFO][2024-04-26 01:41:58][link_ai_bot.py:134] - [LINKAI] reply=创造一个画面，一个年轻的高加索男孩和一个黑人女孩在阳光明媚的公
园的背景下进行友好的交谈。每个孩子都富有表现力和活力，显然很享受他们的谈话。男孩穿着蓝色t恤，女孩穿着黄色太阳裙。两人都站在草地 上，周围是盛开的花朵和参天的树木，反映了一天的温暖和明亮。, total_tokens=0, res_code=200
[INFO][2024-04-26 01:41:58][feishu_channel.py:65] - [FeiShu] start send reply message, type=TEXT, content=https://image-1317903499.cos.accelerate.myqcloud.com/delle/08771b85-87de-4c50-83b4-09d5782845b5.png
[INFO][2024-04-26 01:41:58][feishu_channel.py:65] - [FeiShu] start send reply message, type=TEXT, content=[bot] 创造一个画面，一个年轻的高加索 男孩和一个黑人女孩在阳光明媚的公园的背景下进行友好的交谈。每个孩子都富有表现力和活力，显然很享受他们的谈话。男孩穿着蓝色t恤，女孩穿着黄色太阳裙。两人都站在草地上，周围是盛开的花朵和参天的树木，反映了一天的温暖和明亮。
[INFO][2024-04-26 01:41:58][feishu_channel.py:95] - [FeiShu] send message success
[INFO][2024-04-26 01:41:59][feishu_channel.py:142] - [FeiShu] upload file, res=b'{"code":0,"data":{"image_key":"img_v3_02aa_ccc1be80-f626-4f3e-958f-d39153b0686g"},"msg":"success"}'
[ERROR][2024-04-26 01:41:59][link_ai_bot.py:422] - [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'a1767cf4-b21c-4f7c-be75-6280aa387081.png'
[INFO][2024-04-26 01:52:13][feishu_channel.py:221] - [FeiShu] query=tmp/file_v3_00aa_ccb5ed30-0e9d-40b4-a38c-fb3a475490eg.pdf, type=FILE       
123.58.10.239:51264 - - [26/Apr/2024 01:52:13] "HTTP/1.1 POST /" - 200 OK
[INFO][2024-04-26 01:53:30][feishu_channel.py:221] - [FeiShu] query=tmp/file_v3_00aa_24ee3b5b-2cca-47a2-bc9d-830d6e6b5edg.pdf, type=FILE       
123.58.10.238:62934 - - [26/Apr/2024 01:53:30] "HTTP/1.1 POST /" - 200 OK
[INFO][2024-04-26 02:02:37][feishu_channel.py:221] - [FeiShu] query=tmp/file_v3_00aa_eb0f06a0-9444-45fb-aa01-cbc8cef71fcg.pdf, type=FILE       
123.58.10.239:26754 - - [26/Apr/2024 02:02:37] "HTTP/1.1 POST /" - 200 OK
[INFO][2024-04-26 02:21:23][feishu_channel.py:221] - [FeiShu] query=你好, type=TEXT
123.58.10.238:56156 - - [26/Apr/2024 02:21:23] "HTTP/1.1 POST /" - 200 OK
[INFO][2024-04-26 02:21:23][link_ai_bot.py:121] - [LINKAI] query=你好, app_code=FXi0fIKx, model=gpt-4-turbo, file_id=None
[INFO][2024-04-26 02:21:28][link_ai_bot.py:134] - [LINKAI] reply=你好！有什么我可以帮助你的吗？, total_tokens=511, res_code=None

**Comment by 6vision** [comment]
现在还有问题嘛，还有问题可以和[LinkAI客服](https://docs.link-ai.tech/contact)联系
