### ISSUE TITLE
本地运行报[ERROR][2024-04-28 16:01:47][wechat_channel.py:135] - No module named 'png'

### ISSUE THREAD

**Issue by FanCheng-HP** [zhayujie/chatgpt-on-wechat#1926]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

本地运行报[ERROR][2024-04-28 16:01:47][wechat_channel.py:135] - No module named 'png'

### 终端日志 📒

C:\Users\fc\AppData\Local\Programs\Python\Python39\python.exe C:/Users/fc/Desktop/chatgpt-on-wechat-master/app.py
[INFO][2024-04-28 16:01:46][config.py:260] - [INIT] load config: {'channel_type': 'wx', 'model': 'gpt-3.5-turbo', 'open_ai_api_key': 'sk-fCYcnXz1FC8q5CbA9xyACU3CT61tydjt1339Reso64W4qVpQ', 'claude_api_key': 'YOUR API KEY', 'text_to_image': 'dall-e-2', 'voice_to_text': 'openai', 'text_to_voice': 'openai', 'proxy': 'https://api.fe8.cn/v1', 'hot_reload': False, 'single_chat_prefix': ['bot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'image_create_prefix': ['画'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '', 'linkai_app_code': ''}
[INFO][2024-04-28 16:01:46][config.py:210] - [Config] User datas file not found, ignore.
[INFO][2024-04-28 16:01:46][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-04-28 16:01:46][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins\banwords
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins\bdunit
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins\dungeon
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins\finish
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins\godcmd
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins\hello
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins\keyword
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins\linkai
[INFO][2024-04-28 16:01:46][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins\role
[WARNING][2024-04-28 16:01:46][plugin_manager.py:113] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
[INFO][2024-04-28 16:01:46][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为7501。
[INFO][2024-04-28 16:01:46][godcmd.py:210] - [Godcmd] inited
[INFO][2024-04-28 16:01:46][keyword.py:40] - [keyword] {}
[INFO][2024-04-28 16:01:46][keyword.py:42] - [keyword] inited.
[INFO][2024-04-28 16:01:46][linkai.py:34] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-04-28 16:01:46][role.py:69] - [Role] inited
[INFO][2024-04-28 16:01:46][dungeon.py:56] - [Dungeon] inited
[INFO][2024-04-28 16:01:46][hello.py:38] - [Hello] inited
[INFO][2024-04-28 16:01:46][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.
Downloading QR code.
[ERROR][2024-04-28 16:01:47][wechat_channel.py:135] - No module named 'png'

**Comment by ClassmateShen** [comment]
你没有安装png的python模块

**Comment by LoveAnd-Share** [comment]
兄弟不要把自己key暴露出来

**Comment by nicolashw** [comment]
same error, have you solved that?

**Comment by 6vision** [comment]
> same error, have you solved that?

按照项目说明，按照依赖文件

**Comment by Yumikolab** [comment]
怎么解决的，知道的，说下呗

**Comment by Yumikolab** [comment]
执行‘pip install pypng’  安装png模块
就解决了，
