### ISSUE TITLE
微信聊天框中安装的插件，重启容器后被清除

### ISSUE THREAD

**Issue by sbcxk** [zhayujie/chatgpt-on-wechat#1927]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1、在微信聊天框中安装[timetask](https://github.com/haikerapples/timetask)、[Apilot](https://github.com/6vision/Apilot)等插件，且能正常使用
2、修改yml中部分配置后，sudo docker-compose down、up重启容器
3、#plist、#scanp指令，发现插件初始化了，安装的被去除了

### 问题描述 😯

微信聊天框中安装的插件，重启容器后被清除

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by ClassmateShen** [comment]
你确定你使用了Docker持久化吗？

**Comment by sbcxk** [comment]
大佬你好，请问你的意思是对这整个插件目录挂载嘛？（docker学的浅，只记得几个常见命令了qwq，不清楚怎么持久化）
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/e578f0c0-f830-433c-a8ed-6e9da92800d1)

**Comment by sbcxk** [comment]
感谢大佬指点，挂载了插件所在的文件夹，没问题了~
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/e61e8a98-fb4e-4824-af15-a1e5415506b8)
