### ISSUE TITLE
chatgpt-on-wechat对接kimi free api，日常正常，上传文档解读后卡死。

### ISSUE THREAD

**Issue by phantasy36** [zhayujie/chatgpt-on-wechat#1929]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1、配置好了kimi的api，此api为kimi free api服务提供。
2、通过微信发送信息测试：bot 你好。返回正常。后续再次测试了两条信息均正常。
3、通过微信发送信息测试：bot 你好，请问以下文档讲的什么？【同时发送word文档】
4、返回了分析结果。返回正常。
5、再次发送信息无反馈：bot 你好。无反馈。接续发了两条一直无反馈。查看docker镜像log。也无收到信息的提示。例如：卡死后我发送：bot 你好。log中没有你好提问的显示。

### 问题描述 😯

1、通过微信发送信息测试：bot 你好，请问以下文档讲的什么？【同时发送word文档】
2、返回了分析结果。返回正常。
3、再次发送信息无反馈：bot 你好。无反馈。接续发了两条一直无反馈。查看docker镜像log。也无收到信息的提示。例如：卡死后我发送：bot 你好。log中没有你好提问的显示。

### 终端日志 📒

```log<img width="717" alt="2024-04-29_143727" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/46774023/d4f31115-fd9c-4b87-88de-56af519f5895">
<img width="1082" alt="2024-04-29_143533" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/46774023/f68960fc-24c0-4fc9-b9ce-c0db11c55cbf">
微信聊天界面截图，后面的几个提问是再次提问，结果就卡死。
```

**Comment by KingStoning** [comment]
你好，我想问一下，您是怎么chatgpt-on-wechat对接kimi free api的？那个配置文件一直出错，我一开始想使用oneapi中转但是出错，直接使用还是出错
谢谢您的帮助与回复，不胜感激

**Comment by Saboteur7** [comment]
最新master分支代码已尝试修改这个问题， docker部署可以拉取 master 标签的镜像
