### ISSUE TITLE
微信总是被封，大佬能不能搞个对接企业微信的？

### ISSUE THREAD

**Issue by Quhz** [zhayujie/chatgpt-on-wechat#193]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by yinuxy** [comment]
可以试试[ntchat](https://gitcode.net/mirrors/smallevilbeast/ntchat)用hook方式交互，不用扫码登陆避免被封，但是我代码能力太差不会改，希望大佬有时间换一下

**Comment by bboychencan** [comment]
同问，可否提供企业微信的接口，跪谢！

**Comment by mostlittlebee** [comment]
我站在大佬肩上做了一个企业微信的版本，需要自己有企业微信应用号的使用经验

https://github.com/mostlittlebee/chatgpt-on-wecom

**Comment by Hanhaijl** [comment]
> 我站在大佬肩上做了一个企业微信的版本，需要自己有企业微信应用号的使用经验
> 
> https://github.com/mostlittlebee/chatgpt-on-wecom

可以对接企业微信的webhook吗？这个就可以在群里用了

**Comment by KKGo1999** [comment]
> 我站在大佬肩上做了一个企业微信的版本，需要自己有企业微信应用号的使用经验
> 
> 
> 
> https://github.com/mostlittlebee/chatgpt-on-wecom

可以搞一个nodejs 版本的？

**Comment by zhayujie** [comment]
> 我站在大佬肩上做了一个企业微信的版本，需要自己有企业微信应用号的使用经验
> 
> https://github.com/mostlittlebee/chatgpt-on-wecom

很棒！ 这个是在企业微信内部群还是能对接到微信的？

我可以集成到这个项目中吗 https://github.com/zhayujie/bot-on-anything，  或者你来PR :)

**Comment by mostlittlebee** [comment]
你需要的话，可以合并到你的项目中的。目前只是基于企业微信的应用号做的，有一定使用门槛。2023年2月19日 00:25，zhayujie ***@***.***>写道：



我站在大佬肩上做了一个企业微信的版本，需要自己有企业微信应用号的使用经验

https://github.com/mostlittlebee/chatgpt-on-wecom



很棒！ 这个是在企业微信内部群还是能对接到微信的？

我可以集成到这个项目中吗 https://github.com/zhayujie/bot-on-anything，  或者你来PR :)

**Comment by mostlittlebee** [comment]
对于个人来说，可以在微信里与企业微信中的应用号对话，实现类似智能助理的功能，但不能用在群里

**Comment by lichengzhe** [comment]
> 你需要的话，可以合并到你的项目中的。目前只是基于企业微信的应用号做的，有一定使用门槛。2023年2月19日 00:25，zhayujie ***@***.***>写道：
> 
> 
> 
> 
> 
> 我站在大佬肩上做了一个企业微信的版本，需要自己有企业微信应用号的使用经验
> 
> 
> https://github.com/mostlittlebee/chatgpt-on-wecom
> 
> 
> 
> 
> 
> 很棒！ 这个是在企业微信内部群还是能对接到微信的？
> 
> 
> 我可以集成到这个项目中吗 https://github.com/zhayujie/bot-on-anything，  或者你来PR :)
> 
> 
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

大米兄 感谢项目贡献 方便微信沟通么 谢谢 leeczleecz
