### ISSUE TITLE
飞书画图无法显示

### ISSUE THREAD

**Issue by mitxmu** [zhayujie/chatgpt-on-wechat#1933]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

飞书画图无法显示

### 问题描述 😯

飞书画图无法显示
<img width="544" alt="屏幕截图 2024-04-30 135009" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/103993378/00ca26e0-5ad5-42bf-a633-025c7339cd28">

### 终端日志 📒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 289, in _send
    self.send(reply, context)
  File "/root/chatgpt-on-wechat/channel/feishu/feishu_channel.py", line 70, in send
    reply_content = self._upload_image_url(reply.content, access_token)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/feishu/feishu_channel.py", line 144, in _upload_image_url
    return upload_response.json().get("data").get("image_key")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by 6vision** [comment]
这个应该是偶尔的错误吧，图片上传失败导致的
