### ISSUE TITLE
临时解决微信公众号消息前[ERROR]

### ISSUE THREAD

**Issue by imhut** [zhayujie/chatgpt-on-wechat#1938]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

https://github.com/zhayujie/chatgpt-on-wechat/issues/1880
这里已经解释了原因了，我这里就不过多说明，只是教大家如何临时解决！
修改文件：
/bot/chatgpt/chat_gpt_bot.py
88行
`reply = Reply(ReplyType.ERROR, reply_content["content"])`
修改为
`reply = Reply(ReplyType.TEXT, reply_content["content"])`

就这么简单
![12](https://github.com/zhayujie/chatgpt-on-wechat/assets/52795669/9932061a-6f0d-4d9d-b189-fcb551e7a1ac)
![123](https://github.com/zhayujie/chatgpt-on-wechat/assets/52795669/850deddb-ca9d-4c23-ad13-ca1628c38275)
![1234](https://github.com/zhayujie/chatgpt-on-wechat/assets/52795669/a214ace5-5bfd-47ca-a613-9fdaaaf7c91c)

**Comment by zhangbinhui** [comment]
> ### ⚠️ 搜索是否存在类似issue
> 
> - [X] 我已经搜索过issues和disscussions，没有发现相似issue
> 
> ### 总结
> 
> https://github.com/zhayujie/chatgpt-on-wechat/issues/1880
> 这里已经解释了原因了，我这里就不过多说明，只是教大家如何临时解决！
> 修改文件：
> /bot/chatgpt/chat_gpt_bot.py
> 88行
> `reply = Reply(ReplyType.ERROR, reply_content["content"])`
> 修改为
> `reply = Reply(ReplyType.TEXT, reply_content["content"])`
> 
> 就这么简单
> ![12](https://github.com/zhayujie/chatgpt-on-wechat/assets/52795669/9932061a-6f0d-4d9d-b189-fcb551e7a1ac)
> ![123](https://github.com/zhayujie/chatgpt-on-wechat/assets/52795669/850deddb-ca9d-4c23-ad13-ca1628c38275)
> ![1234](https://github.com/zhayujie/chatgpt-on-wechat/assets/52795669/a214ace5-5bfd-47ca-a613-9fdaaaf7c91c)
> 
> 
> ### 举例
> 
> _No response_
> 
> ### 动机
> 
> _No response_

👍

**Comment by 6vision** [comment]
根本原因应该是使用的三方key返回的格式不是标准的openai格式
