### ISSUE TITLE
Zeabur上无法扫码登录微信

### ISSUE THREAD

**Issue by johncoker233** [zhayujie/chatgpt-on-wechat#1939]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Other (请在问题中说明)

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

直接将Release文件上传到Github库中使用容器部署
运行后控制台输出的二维码扫描提示:查找失败:4 -1

### 问题描述 😯

运行后控制台输出的二维码扫描提示:查找失败:4 -1
![Uploading Screenshot_2024-05-05-18-38-14-30_e39d2c7de19156b0683cd93e8735f348.jpg…]()

**Comment by johncoker233** [comment]
使用的是Zeabur平台
若需要我可以邀请您进入我的Project

**Comment by 6vision** [comment]
部署教程提供了常规部署方式，可以参考一下[快速开始](https://docs.link-ai.tech/cow/quick-start)
