### ISSUE TITLE
百度语音识别老是识别错内容，微信输入的语音，老是识别错，大家有遇到吗？要如何解决

### ISSUE THREAD

**Issue by flyice8** [zhayujie/chatgpt-on-wechat#1941]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by linxp001** [comment]
我也是这个问题，问过百度，说是音频文件格式不符合要求。

**Comment by linxp001** [comment]
解决了，把baidu_voice.py里面的8000改成16000就好了。

**Comment by flyice8** [comment]
牛，我测试一下

linxp001 ***@***.***>于2024年5月8日 周三10:23写道：

**Comment by 6vision** [comment]
> 解决了，把baidu_voice.py里面的8000改成16000就好了。

感谢反馈，已修复 #2013

**Comment by linxp001** [comment]
> 还是不行，我改了也不行

你咋改的，把修改后的文件截图看看。

**Comment by wy-byte** [comment]
> 解决了，把baidu_voice.py里面的8000改成16000就好了。

厉害，我这么改成功了，chatgpt-on-wechat-1.5.9

**Comment by 2069348297** [comment]
现在代码中是16000还是识别出错
