### ISSUE TITLE
可以给好友推送消息吗

### ISSUE THREAD

**Issue by YuanKyL** [zhayujie/chatgpt-on-wechat#1947]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

定时自动发送

### 举例

给微信好友定时发一下消息或者图片或者文件

### 动机

定时给好友推送一些消息，这个应该什么实现呢

**Comment by YuanKyL** [comment]
定时主动推送

**Comment by sbcxk** [comment]
timetask定时插件，配合Apilot插件可以定时推送早报等等

**Comment by spoony-Z** [comment]
> timetask定时插件，配合Apilot插件可以定时推送早报等等

这个插件只能给自己定时推送，并不能给好友定时推送，而且用户任务没有隔离，请问有其他插件吗

**Comment by 6vision** [comment]
> > timetask定时插件，配合Apilot插件可以定时推送早报等等
> 
> 这个插件只能给自己定时推送，并不能给好友定时推送，而且用户任务没有隔离，请问有其他插件吗

timetask可以给特定群聊定时发消息，项目本身暂不支持定时任务，

**Comment by luisxin** [comment]
有没有提供接口调用的方式发送消息呢？
