### ISSUE TITLE
希望能接入自己开发的bot

### ISSUE THREAD

**Issue by yiouyou** [zhayujie/chatgpt-on-wechat#1948]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

除开各种LLM，不知是否能支持通过web api对接自己开发的 bot，比如：特定目的RAG bot

### 动机

希望能利用此项目对接自己开发的 rag bot，不知是否支持

**Comment by black-zyp** [comment]
＋1 想根据源码改，源码看的我好懵，希望能出一个详细的说明文档

**Comment by Wanghh666** [comment]
> ＋1 想根据源码改，源码看的我好懵，希望能出一个详细的说明文档

+1

**Comment by a-Dmears** [comment]
+1

**Comment by aioffice-charles** [comment]
+1

**Comment by wangguoqiang1** [comment]
智能体吗 我已经接入了智谱AI的智能体

**Comment by kunkeji** [comment]
+1

**Comment by 6vision** [comment]
有python基础的话，可以自己参考[bot目录](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/bot)已有的bot接入，项目都是模板化的，只需要考虑实现bot即可，接入那些无需关心

**Comment by kuangdd2024** [comment]
这个项目可以作为参考，已经实现了RAG功能，用作对话记录的搜索，从而实现记忆提取。

项目：
https://github.com/kuangdd2024/wechatgpt-agent

About：
chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。

**Comment by liguoyu666** [comment]
> 这个项目可以作为参考，已经实现了RAG功能，用作对话记录的搜索，从而实现记忆提取。
> 
> 项目： https://github.com/kuangdd2024/wechatgpt-agent
> 
> About： chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。

大哥，你这项目能做个说明文档吗？readme貌似和原来的一样，我不知道在哪添加知识库，想提问都没法提
