### ISSUE TITLE
没有回复

### ISSUE THREAD

**Issue by victory458537** [zhayujie/chatgpt-on-wechat#1954]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/144669640/0b4adccf-f8c2-4fde-ae37-aab9829e6920)

### 问题描述 😯

登录发送信息，好长时间没有回复，配置的有代理

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by sbcxk** [comment]
日志信息太少了，建议截全一点，看不出来，配置也截图发一下吧

**Comment by 6vision** [comment]
可以换个号测试一下，可能是号问题
