### ISSUE TITLE
接入手机微信的ChatGPT回复今年是2020年

### ISSUE THREAD

**Issue by zhouyu168** [zhayujie/chatgpt-on-wechat#196]
接入手机微信的ChatGPT回复今年是2020年, 这么厉害的AI怎么会不知道当前日期和时间呢?  
![image](https://user-images.githubusercontent.com/124881099/218392570-7084d36d-d557-4f41-83e1-75509168a37c.png)
网页端的ChatGPT知道当前份,不知道当前时间
![image](https://user-images.githubusercontent.com/124881099/218392902-8f18007e-b004-49bb-95de-0ab1b3d460f2.png)

**Comment by Kalpeny** [comment]
用的是2020年的模型
