### ISSUE TITLE
COW是否支持百度英文语音？需要如何配置

### ISSUE THREAD

**Issue by flyice8** [zhayujie/chatgpt-on-wechat#1961]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

COW是否支持百度英文语音？需要如何配置
我使用百度dev_pid设置为1737
同时在百度中已经开通英语付费支持，但输出还是中文，还需要做什么设置吗？

**Comment by flyleegit** [comment]
配置改成不带引号的~ 本项目中的config的value都是string~ 但是百度的api中那个参数是int~ 所以你从"1737" 改成1737就行~ 这个坑我踩过~

**Comment by 6vision** [comment]
已修复，更新项目到最新， 参考 #2005
