### ISSUE TITLE
大老板，什么实现回复图片呢，比我我问它要图片，将本地的图片回复给我。

### ISSUE THREAD

**Issue by YuanKyL** [zhayujie/chatgpt-on-wechat#1962]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
可以使用LinkAI的知识库功能，可以发送图片、视频、文件等多媒体文件，参考：[快速开始](https://docs.link-ai.tech/platform/quick-start)
