### ISSUE TITLE
希望claude 增加 base_url参数，能够使用第三方代理claude api地址。

### ISSUE THREAD

**Issue by psumhm** [zhayujie/chatgpt-on-wechat#1966]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望claude 增加 base_url参数，能够使用第三方代理claude api地址

**Comment by 6vision** [comment]
已有pr #1973 ，可以测试一下

**Comment by pageone-PGA** [comment]
问题解决了，现在也是只有中转api

**Comment by pageone-PGA** [comment]
问题解决了吗？现在也是只有中转api
