### ISSUE TITLE
飞书无法识别图片的类别

### ISSUE THREAD

**Issue by autherlj** [zhayujie/chatgpt-on-wechat#1975]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

当前cow版本：1.6.0-13-ge09f562
通过Linkai接入飞书[自建模式]
问题描述：
通过飞书客户端上传图片错误如下:
[INFO][2024-05-14 08:47:36][feishu_channel.py:95] - [FeiShu] send message success
123.58.10.239:17010 - - [14/May/2024 08:47:37] "HTTP/1.1 POST /" - 200 OK
[ERROR][2024-05-14 08:48:02][feishu_channel.py:225] - Unsupported message type: Type:image
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/30717333/77f38e7d-3c89-4b2d-bd87-8dc9b4903fe7)
期望能够通过飞书上传图片模型进行识别

**Comment by 6vision** [comment]
是的，还不支持图片类型，可以看看后面是否更新支持
