### ISSUE TITLE
最新版Docker无法正常运行

### ISSUE THREAD

**Issue by Magnoliar** [zhayujie/chatgpt-on-wechat#1976]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

拉取最新docker更新后，无法正常启动

### 问题描述 😯

拉取最新docker更新后，无法正常启动，日志显示：
[INFO][2024-05-14 03:30:25][config.py:210] - [Config] User datas file not found, ignore.
Traceback (most recent call last):
  File "/app/app.py", line 53, in run
    channel_name = conf().get("channel_type", "wx")
NameError: name 'conf' is not defined. Did you mean: 'const'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 71, in <module>
    run()
  File "/app/app.py", line 66, in run
    logger.error("App startup failed!")
NameError: name 'logger' is not defined
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/18226972/47bb702c-431f-4115-b0f3-66b0881e1030)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 2588xzn** [comment]
呃，Docker他是在他们那边创建了一个镜像，然后Docker实际上，不管你Python版本或者源代码的安装啥的

**Comment by 2588xzn** [comment]
你这里的错误是conf和logger未定义，他们这个代码也不是拿过去就直接用的，哥们你得全看过一遍知道什么代码或者文件夹对应什么功能

**Comment by 6vision** [comment]
按照[教程](https://docs.link-ai.tech/cow/quick-start#2%E7%A8%8B%E5%BA%8F%E9%83%A8%E7%BD%B2)，下载docker compose 文件，修改该文件配置，然后启动即可，

**Comment by FEEHarrison** [comment]
同一个问题，我复现了，只要我挂载了plugins文件夹到容器外部，安装了插件就会报这个错。卸载了插件也不行了。

**Comment by FEEHarrison** [comment]
<img width="815" alt="image" src="https://github.com/user-attachments/assets/107f70e5-2583-4633-a662-b06595d3ec4a">
