### ISSUE TITLE
语音回复

### ISSUE THREAD

**Issue by chenwenshuo** [zhayujie/chatgpt-on-wechat#1981]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

支持语音回复吗 不是语音文件

**Comment by 6vision** [comment]
默认不支持的

**Comment by piwawa** [comment]
> 默认不支持的

怎么让他支持呢。。。

**Comment by 6vision** [comment]
> > 默认不支持的
> 
> 怎么让他支持呢。。。
itchat协议不支持的，所以咩办法，可以尝试ipad协议，具体不太清楚了
