### ISSUE TITLE
GPT-4o返回的图片是webp格式，微信端无法正确显示，需要进行格式转化优化。

### ISSUE THREAD

**Issue by guangnian9988** [zhayujie/chatgpt-on-wechat#1982]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

GPT-4o返回的图片是webp格式，微信端无法正确显示，需要进行格式转化优化。

### 问题描述 😯

GPT-4o返回的图片是webp格式，微信端无法正确显示，需要进行格式转化优化。
![Uploading 图片_20240514183229.png…]()

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by sbcxk** [comment]
确实，dall-e-3也是纯碰运气，生成不是webp格式的图片才能发出去，感觉还是需要统一转换一下图片格式

**Comment by 6vision** [comment]
gpt-4o目前还不支持直接生成图片吧？
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38057450/e714769d-4dd9-43fa-a8f4-654872b7ed35)

**Comment by innocencefool** [comment]
我也是，dall-e-2生成的貌似都是webp

**Comment by innocencefool** [comment]
> gpt-4o目前还不支持直接生成图片吧？ ![image](https://private-user-images.githubusercontent.com/38057450/332138227-e714769d-4dd9-43fa-a8f4-654872b7ed35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDMwNTksIm5iZiI6MTcyMDAwMjc1OSwicGF0aCI6Ii8zODA1NzQ1MC8zMzIxMzgyMjctZTcxNDc2OWQtNGRkOS00M2ZhLWE4ZjQtNjU0ODcyYjdlZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwMzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZWQyMjQwZjkyYmQxZjBjNzYwMmE2ODc1OTQyMjNiYWE3OGYyMDZiY2VjMTdkZjMzYTAzMGMyYzQ3YmY4NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yvaAFMl43wNbSD_F31kr2nj3YvHBUpfbP8-QAfk0htU)

他可能没指定图片生成模型，所以以为是gpt-4o，实际默认是dall-e-2

**Comment by sbcxk** [comment]
这个issue里面有解决办法哈，改一下代码，加个格式转换
https://github.com/zhayujie/chatgpt-on-wechat/issues/1892
