### ISSUE TITLE
开发大佬们，项目有没有办法获取本地时间并能与提示词提交给大模型

### ISSUE THREAD

**Issue by qjsir** [zhayujie/chatgpt-on-wechat#1984]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 动机

获取本地时间并与提示词一同提交给大模型进一步丰富玩法
![Screenshot_20240515_030331](https://github.com/zhayujie/chatgpt-on-wechat/assets/129706123/1cddc654-a00b-49c4-8abf-c7d9056fd467)

**Comment by Ngwind** [comment]
旧版本的好像不行。
新版本的chatgpt模型（比如chatgpt4），本身有tools功能，默认情况下会自己看情况去调用各种tools。相关资料：https://platform.openai.com/docs/guides/function-calling

例如：
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/41123748/0e17c748-d393-4586-a695-77eb9195e196)
