### ISSUE TITLE
服务时间限制代码的逻辑问题

### ISSUE THREAD

**Issue by infrost** [zhayujie/chatgpt-on-wechat#1985]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在config.json中填入 "chat_start_time": "06:00","chat_stop_time": "01:00"，会报错时间格式不正确。

### 问题描述 😯

我希望bot在次日凌晨1点关闭，早上六点打开（深夜停止服务），但是按照现在版本的代码逻辑在config.json中填入 "chat_start_time": "06:00","chat_stop_time": "01:00"，会报错，原因出在time_check.py中的判断逻辑。

个人临时的解决办法是取消chat_time_check = chat_start_time < chat_stopt_time的检查，加入如下语句

if chat_stopt_time <= now_time <= chat_start_time: 
    期间停止服务
else
  ……

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
已提交修复，等合并后更新即可 #2002 ，也可以先测试一下是否有问题
