### ISSUE TITLE
COW 是否有支持的英文插件，回复英文信息的，如果有是否可以提供一下，感谢。

### ISSUE THREAD

**Issue by flyice8** [zhayujie/chatgpt-on-wechat#1988]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

COW 是否有支持的英文插件，回复英文信息的，如果有是否可以提供一下，感谢。

**Comment by 6vision** [comment]
暂时没有，可以根据需求自己写个插件 参考 [自定义插件](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins)
