### ISSUE TITLE
可不可以支持代码的输出呢

### ISSUE THREAD

**Issue by kirito2014** [zhayujie/chatgpt-on-wechat#199]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 在vscode中有类似的插件可以输出代码，可不可以用纯文本格式或者输出为图片格式输出代码

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
你是说机器人回复代码吗，这个一直可以支持的

**Comment by Hanhaijl** [comment]
> 你是说机器人回复代码吗，这个一直可以支持的

他说的应该是输出代码块，跟直接对话那样的
