### ISSUE TITLE
tag：1.6.5，model填： gpt-4o，无法使用

### ISSUE THREAD

**Issue by mmdctjj** [zhayujie/chatgpt-on-wechat#1990]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

model填的 gpt-4o
确认了open-key是正确的，因为在别的平台可以使用

### 问题描述 😯

Loading the contact, this may take a little while.
[INFO][2024-05-16 13:54:20][wechat_channel.py:131] - Wechat login success, user_id: @b6d17def3014c87e14f0210c97bfa839d1d232242e57dde43b672573997faaf3, nickname: ChatGpt-4
Start auto replying.
[INFO][2024-05-16 13:54:35][bridge.py:61] - create bot chatGPT for chat
[INFO][2024-05-16 13:54:35][chat_gpt_bot.py:49] - [CHATGPT] query=怎么学习物理
[WARNING][2024-05-16 13:54:36][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try again after 00:00 the next day. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.
[WARNING][2024-05-16 13:54:56][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-05-16 13:54:56][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try again after 00:00 the next day. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.
[WARNING][2024-05-16 13:55:16][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-05-16 13:55:17][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try again after 00:00 the next day. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.
[INFO][2024-05-16 13:55:17][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
提问太快啦，请休息一下再问我吧), receiver=@xxxxxx

实际得到的结果：[ERROR]
提问太快啦，请休息一下再问我吧

### 终端日志 📒

```log
Loading the contact, this may take a little while.
[INFO][2024-05-16 13:54:20][wechat_channel.py:131] - Wechat login success, user_id: @b6d17def3014c87e14f0210c97bfa839d1d232242e57dde43b672573997faaf3, nickname: ChatGpt-4
Start auto replying.
[INFO][2024-05-16 13:54:35][bridge.py:61] - create bot chatGPT for chat
[INFO][2024-05-16 13:54:35][chat_gpt_bot.py:49] - [CHATGPT] query=怎么学习物理
[WARNING][2024-05-16 13:54:36][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try again after 00:00 the next day. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.
[WARNING][2024-05-16 13:54:56][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-05-16 13:54:56][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try again after 00:00 the next day. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.
[WARNING][2024-05-16 13:55:16][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-05-16 13:55:17][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try again after 00:00 the next day. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.
[INFO][2024-05-16 13:55:17][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
提问太快啦，请休息一下再问我吧), receiver=@xxxxxx
```

**Comment by 6vision** [comment]
[WARNING][2024-05-16 13:54:36][chat_gpt_bot.py:135] - [CHATGPT] RateLimitError: 免费gpt-4模型限制每日3次请求，请00:00后再试，如有更多需求，请访问 https://buyca.shop/ 购买付费API。The free gpt-4 model is limited to 3 requests per day. Please try

日志提示很明确，使用的api key的限制，可以使用[linkai](https://docs.link-ai.tech/platform/link-app/wechat)的服务，按量付费使用
