### ISSUE TITLE
大佬，请问我在调用 fastgpt的时候，在回复的内容里面是含有图片的，请问如何在 cow 里面修改微信回复的时候，首先发送文本处理内容，然后发送相关的图片，谢谢

### ISSUE THREAD

**Issue by soolecho** [zhayujie/chatgpt-on-wechat#1995]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

大佬，请问我在调用 fastgpt的时候，在回复的内容里面是含有图片的，请问如何在 cow 里面修改微信回复的时候，首先发送文本处理内容，然后发送相关的图片，谢谢

**Comment by 6vision** [comment]
这个需要对项目的架构熟悉修改源码，主要在/channel/wechat/wechat_channel.py修改，或者使用[LinkAI](https://docs.link-ai.tech/platform/version/1.4.5)的服务，已经满足你的需求

**Comment by hd19820806** [comment]
你这问题 我也遇到，用ai帮忙一顿爆肝，现在可以同时回复一群图片 文档 视频出去

**Comment by dandan1232** [comment]
请问大佬，调用 fastgpt的时候，图片格式是markdown格式的 在公众号里会直接以纯文本的形式输出，这该怎么解决呢

<img width="1853" height="374" alt="Image" src="https://github.com/user-attachments/assets/c369e17c-f821-4a42-948e-ef532631e9b8" />
