### ISSUE TITLE
[finish.py:23] - [Finish] inited 然后就一直卡在这里，不动了。

### ISSUE THREAD

**Issue by bingjiw** [zhayujie/chatgpt-on-wechat#1996]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[finish.py:23] - [Finish] inited

然后就一直没反应了，一直没任何动静，卡死了

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Nevada1978** [comment]
1.检查你是否有多个进程同时运行，在COW目录下输入pgrep -f app.py | xargs
先把所有的进程杀掉，kill -9 <进程数字>
2.先把手机登录电脑的选项退出来，再重新操作

**Comment by bingjiw** [comment]
已执行你推荐的步骤，仍无效果。估计还有其他原因。感觉这个项目很buggy。
似乎LINK AI对于用户提交的issue不太关心。
在考虑是否要转用 wechaty 再加上调用  GPT的API。

**Comment by HeiHeiHeMianMa** [comment]
我这也是 一模一样，直接部署和docker都是卡到这里
