### ISSUE TITLE
我看项目介绍是支持多微信账号和多api-key的，但是readme和wiki里没有描述

### ISSUE THREAD

**Issue by defamilo** [zhayujie/chatgpt-on-wechat#200]
能否添加到readme或者wiki里，还有就是服务的内部指令，这样很多问题在md文档或者wiki里就相当于完成解答了。

我想到的可以加进去的：
1、多微信账号的配置方法；
2、多api-key的配置方法；
3、常用对话指令，例如 #清除记忆 这种

1、2这两条我看简介和issue应该是支持的（是需要代码级的修改吗？如果需要，给一点简易步骤也可以）

3这种不是看issue我都不知道可以这样重置

**Comment by zhayujie** [comment]
1 和 3是可以支持的，我有空添加到readme

1.多微信账号直接copy项目，在新的目录下扫码登录即可
2.多apikey暂不支持
