### ISSUE TITLE
请问，不能接入自定义，本地微调后的模型吗？比如LLaMa3

### ISSUE THREAD

**Issue by zzisbeauty** [zhayujie/chatgpt-on-wechat#2000]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

- 有本地训练好的模型，LLaMa3；请问没有接入本地模型的接口吗？
- 我没有仔细读代码，只是大致看了 readme 和 issue，没有找到相关的描述；期待得到一个明确的答复

【更进一步】
- 如果支持本地模型，那么还支持本地的模型读取本地的文件或者知识库吗？或者说查MySQL之类的数据？
  我指的是保留这部分的功能模块，如果训练好一个可以读取本地文件的大模型/Agent后可以直接模块化插入该项目。

### 动机

> mark这个项目很久了，今天忙完手头的工作想着仔细读一读，但是目前看来这个项目纯封装API，对于数据私密性的企业（我们公司的数据是不允许见外网的），好像不适用。

**Comment by 6vision** [comment]
bot类型增加一个应该就可以了，也有一个类似的pr #1932 ，可以看看

**Comment by zzisbeauty** [comment]
> bot类型增加一个应该就可以了，也有一个类似的pr #1932 ，可以看看

感谢老师的答复。我看一看。
