### ISSUE TITLE
使用fastgpt知识库apikey和接口，通过cow接入企微，机器人回复文字正常图片显示的是

### ISSUE THREAD

**Issue by joshzhong66** [zhayujie/chatgpt-on-wechat#2003]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp_service(公众号, 服务号)

### 复现步骤 🕹

企微用户14:00:30
云桌面如何创建用户

 VPN助手 5-21 14:00:46
要在云桌面环境中创建用户，请按照以下步骤操作：

### 1. 创建AD域用户
1. 访问 [AD管理控制台](http://10.22.50.248/home/#/directorytree)。
2. 导航到 `Active Directory` -> `vdesktop.com`。
3. 创建新的AD域用户。

![image-20240521112236631](https://raw.githubusercontent.com/joshzhong66/Pibced/main/blog-images/2024/05/21/1aee300652fd9c940ec14326d8abb97d-image-20240521112236631-eb0fa1.png)

### 2. 登录FusionAccess后台
1. 访问 [FusionAccess后台。
2. 使用刚创建的AD域账户登录。

### 问题描述 😯

<1>fastgpt知识库使用md格式导入
<2>使用fastgpt加载正常，通过cow接入企微，无法直接显示图片的内容，会加载出图片的链接

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
移动端不同web，web可以使用markdown格式直接显示图片，微信不支持直接展示图片，需要修改源码，提取图片链接，另起线程发送。
或者直接使用LinkAI的的服务，已适配知识库中图片链接直接以图片形式发送，参考[应用接入](https://docs.link-ai.tech/platform/link-app/wechat)，[图片输出](https://docs.link-ai.tech/platform/version/1.4.5)

**Comment by dandan1232** [comment]
我也遇到了类似的问题 docker拉取的镜像 请问不改动代码和使用LinkAI的服务 是否能够解决？
