### ISSUE TITLE
百度模型没有反应

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#2007]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

配置文件如下:

  "baidu_wenxin_model": "ERNIE-Speed-128K",
  "baidu_wenxin_api_key": "VJlSL7Zlk4Fu9aGY9",
  "baidu_wenxin_secret_key": "I0ePXF3eye4",
  "channel_type": "wx",
  "model": "",
  "open_ai_api_key": "YOUR API KEY",
  "claude_api_key": "YOUR API KEY",
  "text_to_image": "dall-e-2",
  "voice_to_text": "openai",
  "text_to_voice": "openai",
  "proxy": "",
  "hot_reload": false,

### 问题描述 😯

如果直接在配置文件里面配置,就没有反应.

如果在oneapi里面配置百度信息,在COW里面调用,就可以回复信息.

### 终端日志 📒

```log
运行后的LOG如下
Start auto replying.
[INFO][2024-05-22 11:57:29][bridge.py:61] - create bot chatGPT for chat
[INFO][2024-05-22 11:57:29][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2024-05-22 12:01:14][chat_gpt_bot.py:140] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x12e9c4dd0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
[WARNING][2024-05-22 12:01:19][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
```

**Comment by 6vision** [comment]
model没有设置，走的默认的chatgpt
