### ISSUE TITLE
请求重要对话修复问题，优化对话结果

### ISSUE THREAD

**Issue by zhouxingchi1962** [zhayujie/chatgpt-on-wechat#2019]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我测试了好几天，我发现一个很严重的问题，是否可以优化一下！
在正常人微信表达中，对方的对话会分好几段说或最后带表情，甚至会打错字，那是否可以在对方5秒内的对话中，输出的内容作为一个 problem。

### 举例

比如：
16:05:01 你在干嘛？
16:05:02 哈哈
16:05:04 [微笑]

problem1（应该为）：你在干嘛？哈哈[微笑]
answer1（应该为）：GPT对应反馈的内容

### 动机

![微信图片_20240510162054](https://github.com/zhayujie/chatgpt-on-wechat/assets/170221738/8507df81-f2e1-46a0-900f-1b4195e77cdc)

**Comment by 6vision** [comment]
LinkAI提供的专业版服务中，有该功能
![image](https://github.com/user-attachments/assets/78192a90-87d6-4423-9372-3e483ce33334)，有开发能力的话，可以在该项目源码上二开应该也可以的
