### ISSUE TITLE
关于提问调用插件或程序调用插件的想法

### ISSUE THREAD

**Issue by JimWuuu** [zhayujie/chatgpt-on-wechat#2020]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在使用中我们若需要用到插件，需要一个回复前缀+插件工具前缀才可以实现插件调用，能否实现直接提问然后调用插件之后总结回复的程序。

### 举例

例如我需要调用bingsearch插件我需要进行如下提问：
触发前缀+$tool+问题（示例：&$tool 今天星期几）才可以让其回复 因为chatgpt api无法联网
如果可以实现只要触发前缀+问题（示例：&今天星期几）就可以让其回复就更好了。

### 动机

他人在使用时的觉得麻烦所提出的问题，可我无法实现。故来请求开发者以及广大网友。

**Comment by azz212** [comment]
有需求需要定制的，自己改代码。

**Comment by 6vision** [comment]
使用LinkAI的服务即可，不需要前缀，插件都是基于意图识别：
