### ISSUE TITLE
服务号或者订阅号想要自定义菜单，希望在配置中能添加上这个功能

### ISSUE THREAD

**Issue by Lands-1203** [zhayujie/chatgpt-on-wechat#2022]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

服务号或者订阅号想要自定义菜单，希望在配置中能添加上这个功能，目前开启了服务器配置过后，会自动的将服务号的自定义菜单设置为失效，就更改成立接口管理菜单了，希望添加一个配置，能够在 启动的时候自动发送创建菜单请求

**Comment by 6vision** [comment]
参考一下，卡个bug：https://www.wangpc.cc/aigc/chatgpt-wechat_mp/
