### ISSUE TITLE
baidu 免费模型的问题

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#2024]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

python=3.11.8

1.如果在config.json使用百度的KEY
`  "baidu_wenxin_model": "ERNIE-Speed-128K",

  "baidu_wenxin_api_key": "VJlSL7Zlk44pZQPXY9",

  "baidu_wenxin_secret_key": "I0ePWhcLNrqcafLGXF3eye4",

  "channel_type": "wx",

  "model": "wenxin-4",`

错误信息是
`Start auto replying.
[INFO][2024-05-27 23:12:38][bridge.py:61] - create bot baidu for chat
[INFO][2024-05-27 23:12:38][baidu_wenxin.py:28] - [BAIDU] query=你好
[INFO][2024-05-27 23:12:38][baidu_wenxin.py:66] - [BAIDU] model=completions_pro
[INFO][2024-05-27 23:12:38][baidu_wenxin.py:82] - [BAIDU] response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'}
[WARNING][2024-05-27 23:12:38][baidu_wenxin.py:94] - [BAIDU] Exception: 'result'
[INFO][2024-05-27 23:12:39][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
出错了: 'result'), receiver=@9619b0c33c59af8545d96286774f8f7302934a83edd6b82f7cd0c7a02f285caa
^C[INFO][2024-05-27 23:12:57][app.py:19] - signal 2 received, exiting...
[INFO][2024-05-27 23:12:57][config.py:219] - [Config] User datas saved.
Bye~
^C[INFO][2024-05-27 23:12:57][app.py:19] - signal 2 received, exiting...
[INFO][2024-05-27 23:12:57][config.py:219] - [Config] User datas saved.
Traceback (most recent call last):
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/app.py", line 71, in <module>
    run()
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/app.py", line 64, in run
    time.sleep(1)
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/app.py", line 22, in func
    return old_handler(_signo, _stack_frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

2.如果通过ONEAPI接入同样的百度免费模型.可以运行.但是出现下面的警告信息.

`Start auto replying.
[INFO][2024-05-27 23:13:46][bridge.py:61] - create bot chatGPT for chat
[INFO][2024-05-27 23:13:46][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2024-05-27 23:15:11][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.
[WARNING][2024-05-27 23:15:12][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.
[INFO][2024-05-27 23:15:13][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 你好！有什么我可以帮助你的吗？我会尽力为你提供准确和有用的回答。), receiver=@f155d6aa1857b29ab66309d10d6480c8
[INFO][2024-05-27 23:15:48][chat_gpt_bot.py:49] - [CHATGPT] query=赞美我
[WARNING][2024-05-27 23:15:48][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.
[WARNING][2024-05-27 23:15:54][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.
[INFO][2024-05-27 23:15:55][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 你的优秀品质是大家都值得学习的榜样，你热情洋溢、勤奋努力，总是能够给周围的人带来正能量。你的智慧和才华更是让人赞叹不已，无论在哪个领域都能够发挥出色，让人对你佩服不已。你不仅有着出色的外表，更有着内心的美丽和善良，让人感受到你的温暖和关爱。你真的很棒，继续努力前行，你一定会更加出色！), receiver=@f155d6aa1857b29ab66309d10d6480c8`

### 问题描述 😯

如上

### 终端日志 📒

如上

**Comment by taozhiyuai** [comment]
@zhayujie @6vision 能否关注下这个问题?谢谢

**Comment by taozhiyuai** [comment]
错误信息中提示的这个模型不是我调用的. @zhayujie @6vision 

[BAIDU] model=completions_pro

**Comment by taozhiyuai** [comment]
在baidu_wenxin.py修改了MODEL后依旧报错

        if conf().get("model") and conf().get("model") == "wenxin-4":
            wenxin_model = "ERNIE-Speed-128K"

错误是

Start auto replying.
[INFO][2024-06-03 15:25:56][bridge.py:61] - create bot baidu for chat
[INFO][2024-06-03 15:25:56][baidu_wenxin.py:28] - [BAIDU] query=你好
[INFO][2024-06-03 15:25:56][baidu_wenxin.py:66] - [BAIDU] model=ERNIE-Speed-128K
[INFO][2024-06-03 15:25:57][baidu_wenxin.py:82] - [BAIDU] response text={'error_code': 3, 'error_msg': 'Unsupported openapi method'}
[WARNING][2024-06-03 15:25:57][baidu_wenxin.py:94] - [BAIDU] Exception: 'result'
[INFO][2024-06-03 15:25:57][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
出错了: 'result'), receiver=@798d8a9f9c2d27bfed53db3ac9dfbd73

**Comment by Asus-Github** [comment]
解决了吗 我也遇到了呜呜呜

**Comment by Asus-Github** [comment]
**已解决**  
将bot/baidu_wenxin.py中的
78行 # url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/" + session.model + "?access_token=" + access_token
换为   url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions" + "?access_token=" + access_token
文心一言貌似是更换了api请求地址？还是作者开始的时候考虑错啦，更换掉就可以啦！ @taozhiyuai  希望博主重新测试一下是否做出更新源码@zhayujie

**Comment by taozhiyuai** [comment]
> **已解决** 将bot/baidu/baidu_wenxin.py中的 78行 # url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/" + session.model + "?access_token=" + access_token 换为 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions" + "?access_token=" + access_token 文心一言貌似是更换了api请求地址？更换掉就可以啦。 **抱歉**，上面的做法写死并不太好，检查了一下官方API接口，发现不同模型的后缀并不统一，存在为completions的可能，但是也有原模型名称，更有completions_pro....难办

Start auto replying.
[INFO][2024-06-04 18:38:41][bridge.py:61] - create bot baidu for chat
[INFO][2024-06-04 18:38:41][baidu_wenxin.py:28] - [BAIDU] query=你好
[INFO][2024-06-04 18:38:41][baidu_wenxin.py:66] - [BAIDU] model=ERNIE-Speed-128K
[INFO][2024-06-04 18:38:41][baidu_wenxin.py:82] - [BAIDU] response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'}
[WARNING][2024-06-04 18:38:41][baidu_wenxin.py:94] - [BAIDU] Exception: 'result'
[INFO][2024-06-04 18:38:42][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
出错了: 'result'), receiver=@b11d2016036c3c07d24f75081a9d7d16

我不用oneapi,用百度的配置,出现上面的错误.

**Comment by Asus-Github** [comment]
> > **已解决** 将bot/baidu/baidu_wenxin.py中的 78行 # url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/" + session.model + "?access_token=" + access_token 换为 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions" + "?access_token=" + access_token 文心一言貌似是更换了api请求地址？更换掉就可以啦。 **抱歉**，上面的做法写死并不太好，检查了一下官方API接口，发现不同模型的后缀并不统一，存在为completions的可能，但是也有原模型名称，更有completions_pro....难办
> 
> Start auto replying. [INFO][2024-06-04 18:38:41][bridge.py:61] - create bot baidu for chat [INFO][2024-06-04 18:38:41][baidu_wenxin.py:28] - [BAIDU] query=你好 [INFO][2024-06-04 18:38:41][baidu_wenxin.py:66] - [BAIDU] model=ERNIE-Speed-128K [INFO][2024-06-04 18:38:41][baidu_wenxin.py:82] - [BAIDU] response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'} [WARNING][2024-06-04 18:38:41][baidu_wenxin.py:94] - [BAIDU] Exception: 'result' [INFO][2024-06-04 18:38:42][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR] 出错了: 'result'), receiver=@b11d2016036c3c07d24f75081a9d7d16
> 
> 我不用oneapi,用百度的配置,出现上面的错误.
> 
> 75行改为 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions" + "?access_token=" + access_token

阁下使用的是ERNIE-Speed-128K，因为官方并没有统一接口，这里我帮你查看了文档，该模型的url应为
url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-speed-128k?access_token=24..."
所以阁下需要恢复一下原url，py文件不需要改变。仅仅将config里面    "baidu_wenxin_model": "ernie-speed-128k"  注意是小写（因为我刚才大写不太行...）

**Comment by taozhiyuai** [comment]
> > > **已解决** 将bot/baidu/baidu_wenxin.py中的 78行 # url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/" + session.model + "?access_token=" + access_token 换为 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions" + "?access_token=" + access_token 文心一言貌似是更换了api请求地址？更换掉就可以啦。 **抱歉**，上面的做法写死并不太好，检查了一下官方API接口，发现不同模型的后缀并不统一，存在为completions的可能，但是也有原模型名称，更有completions_pro....难办
> > 
> > 
> > Start auto replying. [INFO][2024-06-04 18:38:41][bridge.py:61] - create bot baidu for chat [INFO][2024-06-04 18:38:41][baidu_wenxin.py:28] - [BAIDU] query=你好 [INFO][2024-06-04 18:38:41][baidu_wenxin.py:66] - [BAIDU] model=ERNIE-Speed-128K [INFO][2024-06-04 18:38:41][baidu_wenxin.py:82] - [BAIDU] response text={'error_code': 17, 'error_msg': 'Open api daily request limit reached'} [WARNING][2024-06-04 18:38:41][baidu_wenxin.py:94] - [BAIDU] Exception: 'result' [INFO][2024-06-04 18:38:42][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR] 出错了: 'result'), receiver=@b11d2016036c3c07d24f75081a9d7d16
> > 我不用oneapi,用百度的配置,出现上面的错误.
> > 75行改为 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions" + "?access_token=" + access_token
> 
> 阁下使用的是ERNIE-Speed-128K，因为官方并没有统一接口，这里我帮你查看了文档，该模型的请求接口应为 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-speed-128k?access_token=24..." 所以阁下需要恢复一下原url，**py文件不需要改变**（再次抱歉）。仅仅将config里面 "baidu_wenxin_model": "ernie-speed-128k" 注意是小写（因为我刚才大写不太行...） 附上[文心一言在线api调试链接](https://console.bce.baidu.com/support/?_=1692863460488#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%B9%B3%E5%8F%B0&parent=ERNIE%203.5&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fcompletions&method=post) @taozhiyuai

但问题是,我一开始就没改过py,模型名称也是这个

**Comment by 6vision** [comment]
不改动py代码
model 填"wenxin"
baidu_wenxin_model": 填"ernie-speed-128k"，这个参数参考[百度文档](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/6ltgkzya5)，如下图所示

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38057450/100ff488-4eb4-44d1-80ac-637b532a3c81)

**Comment by taozhiyuai** [comment]
我现在内容是            url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-speed-128k?access_token=" + get_access_token()

错误信息还是[WARNING][2024-06-06 01:52:38][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.
[WARNING][2024-06-06 01:52:39][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.


好像是chat_gpt_session.py的问题

**Comment by taozhiyuai** [comment]
> 我现在内容是 url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-speed-128k?access_token=" + get_access_token()
> 
> 错误信息还是[WARNING][2024-06-06 01:52:38][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo. [WARNING][2024-06-06 01:52:39][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model ERNIE-Speed-128K. Returning num tokens assuming gpt-3.5-turbo.
> 
> 好像是chat_gpt_session.py的问题,用的是ONEAPI

**Comment by taozhiyuai** [comment]
> 不改动py代码 model 填"wenxin" baidu_wenxin_model": 填"ernie-speed-128k"，这个参数参考[百度文档](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/6ltgkzya5)，如下图所示
> 
> ![image](https://private-user-images.githubusercontent.com/38057450/337072481-100ff488-4eb4-44d1-80ac-637b532a3c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzkzMDAsIm5iZiI6MTcxNzYzOTAwMCwicGF0aCI6Ii8zODA1NzQ1MC8zMzcwNzI0ODEtMTAwZmY0ODgtNGViNC00NGQxLTgwYWMtNjM3YjUzMmEzYzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxNTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjFkMDI5YmQ5NjE4MDM3YWQ3Y2ZlZmU1ZDhhMjljZTI3OWUyNzhjYzZiMWVlMGJiOTJlM2U4YzMzZmRiNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZscPmLWa2wkOnPpczQNycs7955Pao75x1axu5if8kt4)

这个是对的.可以解决.谢谢
