### ISSUE TITLE
飞书应用事件配置失败

### ISSUE THREAD

**Issue by Sojiron777** [zhayujie/chatgpt-on-wechat#2027]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

![20240528-165011](https://github.com/zhayujie/chatgpt-on-wechat/assets/110953764/ac3dcaa0-b059-4045-8fac-2e2a515ced50)

### 问题描述 😯

跟着文档操作但是还是出现这个问题，本地直接请求该返回 Feishu service start success!，不知道是哪里没写正确

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by liurulin** [comment]
你是不是设置了Encrypt Key，如果是的话把他设置为空

**Comment by Sojiron777** [comment]
感谢，已经解决了，研究了一下要用公网IP飞书应用才能创建事件接受消息，我ip填的内网




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [zhayujie/chatgpt-on-wechat] 飞书应用事件配置失败 (Issue #2027)














 
你是不是设置了Encrypt Key，如果是的话把他设置为空

**Comment by 2404589803** [comment]
现在公网的也不行了
