### ISSUE TITLE
百度wenxin-千帆配置建议

### ISSUE THREAD

**Issue by lts8989** [zhayujie/chatgpt-on-wechat#2030]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

配置百度的千帆大模型，我有如下经验。建议作者将下面描述细化到说明文档中。毕竟不是每个人都搞得定openai的翻墙和机场ip。

1. 需要配置model，配置为wenxin 或 wenxin-4，我不知道这两个有什么区别，请作者详述。
2. 需要配置baidu_wenxin_model，它是千帆的大模型名称，但是它与千帆大模型的名称并不完全匹配。例如“ERNIE-3.5-8K”模型对应的名称是“ completions”，详见下面截图的红框。
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/5213613/abf7ef1d-d4ff-434a-a601-20b958fd1e1d)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/5213613/87ba5770-952a-413c-aefe-d6b8b4849be5)

3. 配置baidu_wenxin_api_key与baidu_wenxin_secret_key，这个不多说。

**Comment by Peter0755** [comment]
那请问可以对接 百度的 AppBuilder么？这样会更加厉害

**Comment by 6vision** [comment]
"baidu_wenxin_model"这个参数写对应的名称即可，比如“ERNIE-3.5-8K”模型对应的名称是“ completions”，“ERNIE-4-8K”模型对应的名称是“ completions_pro”，依次类推即可，对应的名称详见[模型列表](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/clntwmv7t)，
