### ISSUE TITLE
应用是否正确处理了健康检查请求，例如响应HTTP状态码200。

### ISSUE THREAD

**Issue by bingjiw** [zhayujie/chatgpt-on-wechat#2032]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在DIGITALOCEAN的APP PLATFORM上DEPLOY 这个 DOCKER就会出现此问题。

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/20619102/5119893f-d784-4c49-9c1a-e3dff9814eca)

如图，在digitalOcean的app platform部署一个app后，app的web service已经正常运行，但digitalOcean平台却一直在"Waiting for service",也就是digitalOcean的container管理平台让为这个app一直在deploying,这是为何？是deploy的这个app没有实现（缺少）某些接口吗？

在DigitalOcean的App Platform上遇到这种问题可能有以下几种原因：

健康检查失败：**DigitalOcean App Platform可能在等待一个健康检查（health check）通过。如果你的应用没有正确响应健康检查请求，平台会认为部署未完成。你可以检查你的应用是否正确处理了健康检查请求，例如响应HTTP状态码200。**

启动时间过长：如果你的应用需要较长时间启动，平台可能会认为部署未完成。确保你的应用在合理时间内完成启动过程。

端口配置错误：确保你在DigitalOcean App Platform的配置中正确指定了应用运行的端口。默认情况下，平台会尝试连接到应用的HTTP端口（通常是80或8080），如果你的应用使用了不同的端口，你需要在配置中指定它。

资源限制：检查你的应用是否因为资源限制（例如内存或CPU不足）而无法正常运行。你可以通过查看应用的日志来了解更多信息。

平台问题：有时问题可能在于DigitalOcean平台本身。你可以尝试重新部署应用，或者联系DigitalOcean的支持团队以获得进一步的帮助。

你可以通过点击“Go to Deploy Logs”查看详细的部署日志，这些日志通常会包含有关问题的更多信息。如果部署日志中有错误信息或提示，可能会帮助你确定问题的根源。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
服务器正常使用docker部署，镜像是经过验证没有问题的。其他平台，建议多查看平台指导
