### ISSUE TITLE
请教COW连接了fastgpt的API后，openai的语音就不能使用有啥好的解决方法？

### ISSUE THREAD

**Issue by flyice8** [zhayujie/chatgpt-on-wechat#2034]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

请教COW连接了fastgpt的API后，openai的语音就不能使用有啥好的解决方法？

**Comment by 6vision** [comment]
可以提供更多信息
