### ISSUE TITLE
扩大模型范围，新增支持用户自己部署的大模型

### ISSUE THREAD

**Issue by NeoFii** [zhayujie/chatgpt-on-wechat#2036]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

建议作者团队能支持将用户自己的大模型接入进来

### 动机

项目很好，我自己从事LLLM方面的研究，建议能够将自己的大模型部署接入到微信中

**Comment by laoji2333** [comment]
其实可以自己改代码实现，之前我就接了自己本地跑的qwen模型

**Comment by NeoFii** [comment]
> 其实可以自己改代码实现，之前我就接了自己本地跑的qwen模型

你好 请问能交流一下吗

**Comment by 6vision** [comment]
项目架构支持自定义bot，在[bot文件夹](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/bot)下增加即可

**Comment by laoji2333** [comment]
> > 其实可以自己改代码实现，之前我就接了自己本地跑的qwen模型
> 
> 你好 请问能交流一下吗

我那种其实是一种临时解决方案，其实就是把接口地址改成局域网里面模型的API地址，就是提供OpenAI格式的API，然后改他这个项目的一些配置去实现，如果要真正一样上接自己的大模型，最好是开发多一种模式
