### ISSUE TITLE
绘图接入Fooocus

### ISSUE THREAD

**Issue by VectorZhao** [zhayujie/chatgpt-on-wechat#2037]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

https://github.com/lllyasviel/Fooocus
不知道能否对接这个绘图，fooocus绘图不需要太多设置，生成的图片质量非常高。

**Comment by 6vision** [comment]
和sd差不多，可以参考[sd插件](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/source.json)，编写自定义插件
