### ISSUE TITLE
如果引用了某个对话内容，机器人将不会回复。

### ISSUE THREAD

**Issue by MILKMILKKING** [zhayujie/chatgpt-on-wechat#2039]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

如果引用了某个对话内容，机器人将不会回复。

### 问题描述 😯

如果引用了某个对话内容，机器人将不会回复。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by aliushn** [comment]
同问

**Comment by cancanjun** [comment]
同问

**Comment by 6vision** [comment]
引用不支持的，项目过滤掉了引用的消息：有时候引用内容拿不到，有时候会误触发

**Comment by kenkyz** [comment]
> 引用不支持的，项目过滤掉了引用的消息：有时候引用内容拿不到，有时候会误触发

群聊中的对话引用很重要，可以明确上下文，而且有时候用户引用的是群中第三人的消息。该bug是否可以进行完善，或者提供开关选项给开发者？目前毫无反应很不友好，请提供指引在哪里可修改取消过滤。
