### ISSUE TITLE
聊天可以，但是不能生成图片，有什么办法嘛？

### ISSUE THREAD

**Issue by Wait1234** [zhayujie/chatgpt-on-wechat#204]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
报错或日志贴一下

**Comment by BadwomenzzzZ** [comment]
![image](https://user-images.githubusercontent.com/70122672/218905590-cb63a2ed-330e-4c40-a126-3d861aedbc06.png)
应该是这种报错把

**Comment by BadwomenzzzZ** [comment]
@zhayujie 这个要怎么解决

**Comment by zhayujie** [comment]
> ![image](https://user-images.githubusercontent.com/70122672/218905590-cb63a2ed-330e-4c40-a126-3d861aedbc06.png) 应该是这种报错把

openai 版本不够，需要0.25.0 才支持画图

pip3 show openai 看下

**Comment by Hanhaijl** [comment]
> > ![image](https://user-images.githubusercontent.com/70122672/218905590-cb63a2ed-330e-4c40-a126-3d861aedbc06.png) 应该是这种报错把
> 
> openai 版本不够，需要0.25.0 才支持画图
> 
> pip3 show openai 看下

这个坑我踩过，openai要0.25.0以上，python版本要3.9以上，不然openai的依赖装不上。不知道是环境问题还是什么，反正我python3.8没部署成功过
还有python的源要用默认源，不要用国内源，国内源最多只有0.8的版本。

**Comment by zhayujie** [comment]
3.7.1以上其实都可以装openai 0.25.0版本，注意更新下pip
