### ISSUE TITLE
已在支付处实名验证过的Wechat帐号（非微信）不可扫码登录

### ISSUE THREAD

**Issue by Simonmxy** [zhayujie/chatgpt-on-wechat#2042]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码后出现“当前帐号无法使用该服务”
除此之外此Wechat号一切正常使用，支付已实名。绑定的是海外实体手机卡。
腾讯到底允许什么样的Wechat号？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by azz212** [comment]
底层我修改了用ipad协议吧

**Comment by Simonmxy** [comment]
> 底层我修改了用ipad协议吧

非常感谢，但在最新的1.6.6环境下（Docker部署），依然提示：当前帐号无法使用该服务
应该是我这个号的问题。辛苦了。

**Comment by ShinJiEDU** [comment]
> 底层我修改了用ipad协议吧

请问如何用ipad协议啊？web协议的刚封了我的号

**Comment by 6vision** [comment]
使用的协议要求的应该是国内实名绑卡的手机号可以登录
