### ISSUE TITLE
配置文生图，cogview-3不生效

### ISSUE THREAD

**Issue by ArlanCooper** [zhayujie/chatgpt-on-wechat#2049]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在 docker-compose.yaml配置智谱的画图参数:
TEXT_TO_IMAGE: 'CogView-3'

调用的时候，不生效:
[ERROR]
Bot不支持处理IMAGE_CREATE类型的消息

### 问题描述 😯

在 docker-compose.yaml配置智谱的画图参数:
TEXT_TO_IMAGE: 'CogView-3'

调用的时候，不生效:
[ERROR]
Bot不支持处理IMAGE_CREATE类型的消息

### 终端日志 📒

```log
chatgpt-on-wechat  | [INFO][2024-06-05 13:53:23][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
                    chatgpt-on-wechat  | Bot不支持处理IMAGE_CREATE类型的消息), receiver=@@bb00d6c4e81ff461ebb75c14a8c605526b3dbfa6b36eb55a38a8b0050690ca9c
```

**Comment by 6vision** [comment]
这边使用最新代码测试，是没问题的，相关配置如下：
"model": "glm-4",
"text_to_image": "cogview-3",
