### ISSUE TITLE
 提问太快啦，请休息一下再问我吧

### ISSUE THREAD

**Issue by lvdqiang** [zhayujie/chatgpt-on-wechat#205]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
这个额度是谁的额度呢，需要怎么才能获取额度
![image](https://user-images.githubusercontent.com/125290837/218629679-e2d51b0a-0cf4-4d07-a864-988d767ee9de.png)

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)
You exceeded your current quota, please check your plan and billing details.
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
账号没额度了

**Comment by lvdqiang** [comment]
> 账号没额度了，在这里查看：https://platform.openai.com/account/usage
> 
> 额度一般注册的都有免费18美金额度

我们可以充值吗

**Comment by zhayujie** [comment]
> > 账号没额度了，在这里查看：https://platform.openai.com/account/usage
> > 额度一般注册的都有免费18美金额度
> 
> 我们可以充值吗

充值也行，  建议换账号

**Comment by Hanhaijl** [comment]
@zhayujie 大佬，怎么充值啊，好像要用国外的银行卡才可以是吗？有充值的教程吗？

**Comment by zhayujie** [comment]
> @zhayujie 大佬，怎么充值啊，好像要用国外的银行卡才可以是吗？有充值的教程吗？

暂时没有充值过，需要国外卡

**Comment by weekyuan** [comment]
我换了一个key怎么还是提示这个？

**Comment by weekyuan** [comment]
@zhayujie 大佬，我更换换了一个新的key，怎么接口还是提示这个You exceeded your current quota, please check your plan and billing details.

**Comment by zhayujie** [comment]
@weekyuan 你是更换账号了吗，要在这里看看有没有额度
https://platform.openai.com/account/usage

现在有时候注册账号不送免费额度了
