### ISSUE TITLE
请增加本地文转音功能:microsoft edge tts

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#2051]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

请增加本地文转音功能:microsoft edge tts. 

### 举例

microsoft edge tts. 

### 动机

可以本地免费使用

**Comment by kuangdd2024** [comment]
这个项目把azure的tts改成了edge-tts，免费的语音合成。

项目：
https://github.com/kuangdd2024/wechatgpt-agent

About：
chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。
