### ISSUE TITLE
扫码登录微信后，发送消息之后日志显示错误

### ISSUE THREAD

**Issue by dengruoqing** [zhayujie/chatgpt-on-wechat#2053]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

<img width="1079" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/13677452/0fd9cc39-314d-48d1-8ded-c1ce73033360">

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by FancyLaw** [comment]
我也遇到了相同的问题， config.json 中增加  "expires_in_seconds": 3600 后解决了

**Comment by dengruoqing** [comment]
邮件收到，我会尽快回复~
