### ISSUE TITLE
换成dall-e-3后，输出的图片分辨率与open_ai_image.py中设定的不一致怎么解决？

### ISSUE THREAD

**Issue by huamike** [zhayujie/chatgpt-on-wechat#2054]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1.查找到  bot/openai/open_ai_image.py，然后# size=conf().get("image_create_size", "256x256")
2.在config.json中将dall-e-2改为dall-e-3
3.#disablep linkai，#stop， #reconf,，#resume,
4.画...

### 问题描述 😯

经过上述步骤，dall-e-3可以正常出图，但会发现画出来的图片默认分辨率为1024*1024，跟上述文件中设定不一致，如果希望修改图片的默认分辨率和图片质量，需要在哪里设定？或者是否可以不做设定，直接在对话中指定？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
有参数可以在config.json文件配置：["image_create_size"](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py#L50)
