### ISSUE TITLE
请求增加glm-4-air等glm其他系列模型

### ISSUE THREAD

**Issue by yueweix** [zhayujie/chatgpt-on-wechat#2055]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

根据官网介绍可以看到glm-4-air这个模型具有不弱于GLM-4的性能和速度，而且价格更加划算

### 举例

https://open.bigmodel.cn/pricing

### 动机

因为GLM-4的api费用比较高，而最近新推出的Air系列在具有比较好的性能的同时，资费也更为合理，希望能够增加对其的支持

**Comment by choupiyang** [comment]
同上

**Comment by alexg9781** [comment]
请问配置 "model": "glm-4", 后， api_key 在上面变量中填写
运行一直提示没有配置 api_key, 不知道配置在那个key 中

**Comment by leesonchen** [comment]
> 请问配置 "model": "glm-4", 后， api_key 在上面变量中填写 运行一直提示没有配置 api_key, 不知道配置在那个key 中

“zhipu_ai_api_key”: "xxx"

**Comment by leesonchen** [comment]
> ### ⚠️ 搜索是否存在类似issue
> * [x]  我已经搜索过issues和disscussions，没有发现相似issue
> 
> ### 总结
> 根据官网介绍可以看到glm-4-air这个模型具有不弱于GLM-4的性能和速度，而且价格更加划算
> 
> ### 举例
> https://open.bigmodel.cn/pricing
> 
> ### 动机
> 因为GLM-4的api费用比较高，而最近新推出的Air系列在具有比较好的性能的同时，资费也更为合理，希望能够增加对其的支持

在我的pr里面增加了这个功能。 #2065

**Comment by yueweix** [comment]
我这边用了一个取巧的办法来实现调用GLM-4-Air系列
但是，我无法确定是否成功，因为我目前处于GLM模型的免费赠送Token阶段，我无法根据价格推算我到底调用的是否是GLM-4Air模型（因为我自己也不会其他方法验证）

## 尝试操作如下
修改 `bot` 文件夹下的 `zhipuai` 文件夹内的 `zhupu_ai_session.py` 和 `zhipuai_bot.py` 两个文件，利用搜索替换其中的 `glm-4` 字段为 `glm-4-air`。

然后在我们的配置文件也就是 `config.json` 中，按照输入 glm-4 模型的方法，配置好我们的 api_key 和 api_url （请注意我这里是举例，实际配置 GLM 模型需要的两个变量名并不是这两个，实际参数见下图）
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/130626337/68efee60-308e-4f82-a91d-01474f9bdf27)

`model` 还是填写 `glm-4`，而不是 `glm-4-air`，因为之前修改好了那两个 py 文件，因此按理说会将我们请求的 glm-4 变成 glm-4-air（我也不知道正不正确，请大佬指正）

## 结果
如果按照以上操作完毕且不出意外的话，就可以成功调用了（我是成功了，但是无法确定是否真的是调用了 `glm-4-air` 还是 `glm-4`。这只是个个人粗糙的取巧尝试，仅供参考

**Comment by 6vision** [comment]
拉取这个pr #2046
在json文件增加配置：
 "bot_type": "glm-4",
  "model": "glm-4-flash",
  "zhipu_ai_api_key": "efd1f61b8a92e.PgCqQPUm14OEchWP",
  "zhipu_ai_api_base": "https://open.bigmodel.cn/api/paas/v4",

**Comment by yueweix** [comment]
感谢🙏帮助
