### ISSUE TITLE
画图有问题

### ISSUE THREAD

**Issue by zandko** [zhayujie/chatgpt-on-wechat#2056]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

dall-e-3 生成图片有问题

### 问题描述 😯

dall-e-3 生成图片有问题

### 终端日志 📒

```log
[INFO][2024-06-06 13:23:47][open_ai_image.py:22] - [OPEN_AI] image_query=一个皮卡丘
[ERROR][2024-06-06 13:23:55][open_ai_image.py:42] - 'data'
Traceback (most recent call last):
  File "/app/bot/openai/open_ai_image.py", line 30, in create_img
    image_url = response["data"][0]["url"]
KeyError: 'data'
```

**Comment by 6vision** [comment]
测试没问题的，解决了吗，看起来你那边没有请求成功，可能网络或者其他问题
