### ISSUE TITLE
想问问怎么自动识别用户微信id，并将提问者的id加入到query前面，从而实现群聊中针对某一用户的对话（结合systemprompt的定制对话）

### ISSUE THREAD

**Issue by BryanMurkyChan** [zhayujie/chatgpt-on-wechat#2057]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

已经完成了基本的部署工作，由于群聊语境下存在多个用户与模型角色的身份关系，需要在query前面，加上提问者的id一起喂给大模型获取返回。
例如，大模型扮演了宠物猫的身份，群聊中有5人，分别是宠物猫的主人、爸爸、妈妈、朋友、敌人。
通过systemprompt可以告知大模型对话者的身份，以及对应的id，但是在实际的交互中，大模型并不能识别哪一位用户是谁，分析得知是query前面并没有用户的id信息。
项目太大，个人能力有限，不太看得懂信息输入部分的代码逻辑，希望能指点一下怎么在query前面拼接上提问者的id

**Comment by flyinsz** [comment]
同问，一直需要这个功能，到现在还是没实现

**Comment by azz212** [comment]
换底层wechat，itchat已经限制了，换IPAD或者hook

**Comment by ShinJiEDU** [comment]
> 换底层wechat，itchat已经限制了，换IPAD或者hook

请问如何更换？

**Comment by Tishon1532** [comment]
> > 换底层wechat，itchat已经限制了，换IPAD或者hook
> 
> 请问如何更换？

可以看看这个https://github.com/Tishon1532/chatgpt-on-wechat-win

**Comment by Namarimizu** [comment]
插件里写：
...
def __init__(self):
  ...
  self.handlers[Event.ON_HANDLE_CONTEXT] = self.on_handle_context
 ...
def on_handle_context(self, e_context: Eventcontext):
  if e_context["context"].type != ContextType.TEXT:
    return
  else:
    msg: ChatMessage = e_context["context"]["msg"]
      if e_context["context"]["isgroup"]:
        username = msg.actual_user_nickname
      else:
        username = msg.from_user_nickname
      e_context["context"].content = f"说话人是{username}，内容是：" + e_context["content"].content
      e_context.action = EventAction.CONTINUE

这样处理不知道行不行……？
