### ISSUE TITLE
运行报错，raise SSLError(e, request=request) You can't get access to internet or wechat domain, so exit.

### ISSUE THREAD

**Issue by JosephKeepLearn** [zhayujie/chatgpt-on-wechat#206]
### 前置确认

1. 运行于国内网络环境，未开代理
2. 在已有 issue 中未搜索到类似问题
3. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:992)')))

You can't get access to internet or wechat domain, so exit.
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
是不是开代理了，要关掉

**Comment by hechengzhang** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/17697859/220138473-70ef983d-53c6-4d7e-af02-4ff20bfa9228.png">

ubuntu 没有开代理，服务器在青岛，无法连接

**Comment by hechengzhang** [comment]
> 

@zhayujie

**Comment by zhayujie** [comment]
@bksheng 使用规则模式
