### ISSUE TITLE
win或服务器按照文档指引，报错，无法获取！

### ISSUE THREAD

**Issue by TerryZT** [zhayujie/chatgpt-on-wechat#2061]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

按照操作文档，安装了 Python3.8 以后，在拉取克隆项目的时候无法获取，国内国外的源都已经试过了，在cmd下面和power shell,都是无法获取。

### 问题描述 😯

![1717749299000](https://github.com/zhayujie/chatgpt-on-wechat/assets/89681010/954067a5-6679-432e-b533-ff143850d11b)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by gzgogogz** [comment]
你需要去安装一个git的软件。https://git-scm.com/

**Comment by 6vision** [comment]
git 工具没有安装，具体可以问问AI
