### ISSUE TITLE
请求开发！对接百度AppBuilder，百度最适合企业的工具

### ISSUE THREAD

**Issue by zhouxingchi1962** [zhayujie/chatgpt-on-wechat#2062]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

百度AppBuilder网站：https://console.bce.baidu.com/ai_apaas/app
OpenAPI对接网站：https://cloud.baidu.com/doc/AppBuilder/s/klv2eywua?feedback=1
AppBuilder-SDK对接网站：https://github.com/baidubce/app-builder/blob/master/cookbooks/agent_builder.ipynb

这是目前百度最主题开发的工具，工具非常强大，可配置多种插件和知识库，费用非常低，完全足够满足企业需求，希望大神可以对接。

### 举例

![微信截图_20240607180738](https://github.com/zhayujie/chatgpt-on-wechat/assets/170221738/d0bcdb1b-d76c-43cf-8bec-602e537028a7)

**Comment by azz212** [comment]
没啥难度，但定制开发需要付费呗
