### ISSUE TITLE
itchat看不到企业微信的群的消息，也看不到企业微信的个人的消息

### ISSUE THREAD

**Issue by ItsBean** [zhayujie/chatgpt-on-wechat#2066]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用企业微信用户给当前这个机器人发送消息。

### 问题描述 😯

```
{
  "BaseResponse": {
    "Ret": 0,
    "ErrMsg": ""
  },
  "AddMsgCount": 0,
  "AddMsgList": [],
  "ModContactCount": 0,
  "ModContactList": [],
  "DelContactCount": 0,
  "DelContactList": [],
  "ModChatRoomMemberCount": 0,
  "ModChatRoomMemberList": [],
```
来自企业微信的用户的消息的`AddMsgList`会变成空，使得机器人无法接收到消息,请问是什么原因呢?
如果是个人用户的消息`AddMsgList`不会变成空.

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
itchat协议貌似没办法拿到企微消息的，

**Comment by azz212** [comment]
换成IPAD协议或者PC HOOK就好了

**Comment by MYP1413** [comment]
> ipadwx是收费的，刚改完，还没开源

大佬 可以付费使用吗？或者有开源计划吗
