### ISSUE TITLE
建议新增gemini_api_base

### ISSUE THREAD

**Issue by Zhangsbo** [zhayujie/chatgpt-on-wechat#2067]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

目前gemini没有对应的base选项，无法通过已经代理好的域名进行国内访问，gemini作为免费api有着较广的应用面，希望能进行更新

### 举例

"gemini_api_base": "https://XXXXX"

### 动机

目前gemini没有对应的base选项，无法通过已经代理好的域名进行国内访问，gemini作为免费api有着较广的应用面，希望能进行更新

**Comment by 6vision** [comment]
代理如果是兼容openai格式的，可以直接使用[open_ai_api_base](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py#L17)即可，
