### ISSUE TITLE
text_to_voice 能否支持chatTTS

### ISSUE THREAD

**Issue by brokenman1** [zhayujie/chatgpt-on-wechat#2073]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

text_to_voice 能否支持chatTTS

**Comment by 6vision** [comment]
可以参考[已有的语音模型](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/voice)自行开发，另外chatTTS也需要自行部署该服务吧
