### ISSUE TITLE
扫码登录出时间异常问题

### ISSUE THREAD

**Issue by sky0987** [zhayujie/chatgpt-on-wechat#2075]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码登录 输入关键词报错

### 问题描述 😯

扫码登录 输入关键词报错

### 终端日志 📒

Traceback (most recent call last):
  File "/data/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
  File "/data/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/data/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/data/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 57, in wrapper
    self.receivedMsgs[msgId] = True
  File "/data/chatgpt-on-wechat/common/expired_dict.py", line 18, in __setitem__
    expiry_time = datetime.now() + timedelta(seconds=self.expires_in_seconds)
TypeError: unsupported type for timedelta seconds component: NoneType

**Comment by 6vision** [comment]
配置文件可以截图看看嘛

**Comment by sky0987** [comment]
{
  "channel_type": "wx",
  "model": "gpt-3.5-turbo",                                  
  "open_ai_api_key": "YOUR API KEY",                          
  "proxy": "",                                                
  "single_chat_prefix": ["bot", "@bot"],                     
  "single_chat_reply_prefix": "[bot] ",                       
  "group_chat_prefix": ["@bot"],                              
  "group_name_white_list": ["ChatGPT测试群", "ChatGPT测试群2"], 
  "group_chat_in_one_session": ["ChatGPT测试群"],               
  "image_create_prefix": ["画", "看", "找"],                   
  "conversation_max_tokens": 1000,                            
  "speech_recognition": false,                                
  "group_speech_recognition": false,                          
  "voice_reply_voice": false,                                 
  "character_desc": "你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。", 
  "subscribe_msg": "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持角色扮演和文字冒险等丰富插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,                                       
  "linkai_api_key": "xx",                                      
  "linkai_app_code": "xxx"                                     
}  用的link

**Comment by 6vision** [comment]
使用linkai的话，是"use_linkai": true，其他配置好像没问题，感觉这个是偶发的，可以重启试试看
