### ISSUE TITLE
Docker部署时，关于依赖的持久化问题

### ISSUE THREAD

**Issue by sbcxk** [zhayujie/chatgpt-on-wechat#2077]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

无需复现

### 问题描述 😯

关于Docker模式的部署，插件可以通过挂载来实现持久化。
但对于某些拓展插件，需要安装对应的依赖，这些依赖在容器重启后也会消失，每次都需要重新下载，有什么解决办法嘛？
（只能通过挂载容器中python依赖所在的目录嘛？暂时只想到这种解决方式）
求大佬们指点一下~

放张弔图
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/ce16a6d9-da6a-4bf0-a698-d9dbcd5800fa)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
目前好像没太好的解决办法，折腾插件可以考虑服务器直接python部署~

**Comment by huangzhitian** [comment]
> ### 前置确认
> * [x]  我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。
> 
> ### ⚠️ 搜索issues中是否已存在类似问题
> * [x]  我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
> 
> ### 操作系统类型?
> Docker
> 
> ### 运行的python版本是?
> python 3.7
> 
> ### 使用的chatgpt-on-wechat版本是?
> Latest Release
> 
> ### 运行的`channel`类型是?
> wx(个人微信, itchat)
> 
> ### 复现步骤 🕹
> 无需复现
> 
> ### 问题描述 😯
> 关于Docker模式的部署，插件可以通过挂载来实现持久化。 但对于某些拓展插件，需要安装对应的依赖，这些依赖在容器重启后也会消失，每次都需要重新下载，有什么解决办法嘛？ （只能通过挂载容器中python依赖所在的目录嘛？暂时只想到这种解决方式） 求大佬们指点一下~
> 
> 放张弔图 ![image](https://private-user-images.githubusercontent.com/67060479/339760258-ce16a6d9-da6a-4bf0-a698-d9dbcd5800fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDUxNjAsIm5iZiI6MTcxOTA0NDg2MCwicGF0aCI6Ii82NzA2MDQ3OS8zMzk3NjAyNTgtY2UxNmE2ZDktZGE2YS00YmYwLWE2OTgtZDlkYmNkNTgwMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA4Mjc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDMyMGNhY2ZhMjg4YTcwMmNjMGMyNmY1OTgwZDNlNzI5YjcxZWIwMjMxYzc0ZjExZDM1MWZlN2Y2YzkxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y44NpOdj4EFobujvlpBakHXwPtHHgd87q0H9_1FAGyU)
> 
> ### 终端日志 📒
> ```
> <此处粘贴终端日志>
> ```

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/129321746/888a04bc-1232-4d6f-be0e-3e289a623273)
可以像这个样，在docker-compose.yml 所在文件夹创建插件文件夹 并映射，然后在创建一个python虚拟环境再映射，当插件需要安装依赖，进去虚拟环境安装依赖就行了
