### ISSUE TITLE
关于group_welcome_msg是否可增加一个，off参数

### ISSUE THREAD

**Issue by chaomarks** [zhayujie/chatgpt-on-wechat#2079]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

group_welcome_msg现在可以自定义或者不定义，若不定义则会随机风格欢迎，是否可以再增加一个off参数，直接取消入群欢迎
group_name_white_list，自动回复群聊列表，群名有符号的怎么定义，跳过好像不行

**Comment by 6vision** [comment]
关闭hello插件即可关闭入群欢迎语 给机器人发送 #disablep hello 即可
群名有符号比较杂乱，不好处理的
