### ISSUE TITLE
Splatoon3 日程查询插件

### ISSUE THREAD

**Issue by sbcxk** [zhayujie/chatgpt-on-wechat#2083]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

新增插件：Splatoon3 日程查询，用于获取游戏【斯普拉通3】中的日常比赛场地信息
https://github.com/sbcxk/MySplatoon
示例：
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/335a4760-31a5-47c8-b38d-7fcdf4ee1932)
![a44c783e84e6f7fbfe0fef3b7df2743](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/d8e3e79a-9df2-4dab-9a90-bd2519c833fb)

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/0236dae0-ac16-4087-8b2c-d84de6b45c5c)
![45a6b6f88d89ae86c102687fce4ddf7](https://github.com/zhayujie/chatgpt-on-wechat/assets/67060479/a5ae2112-baab-41d2-9e63-86be6c93294a)

**Comment by 6vision** [comment]
可以提交到[source.json](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/source.json)哈

**Comment by Namarimizu** [comment]
好巧，我也弄了个一样的😂
