### ISSUE TITLE
[COZE] reply error=[COZE] Error: 当前 Bot 未发布到对应渠道

### ISSUE THREAD

**Issue by jonnyman12345** [zhayujie/chatgpt-on-wechat#2084]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[COZE] reply error=[COZE] Error: 当前 Bot 未发布到对应渠道

### 问题描述 😯

[COZE] reply error=[COZE] Error: 当前 Bot 未发布到对应渠道

### 终端日志 📒

```log
[INFO][2024-06-16 16:12:13][bridge.py:55] - create bot coze for chat
[INFO][2024-06-16 16:12:13][bytedance_coze_bot.py:25] - [COZE] query=你好
[WARNING][2024-06-16 16:12:13][chat_gpt_session.py:84] - num_tokens_from_messages() is not implemented for model coze. Returning num tokens assuming gpt-3.5-turbo.
[ERROR][2024-06-16 16:12:16][bytedance_coze_bot.py:32] - [COZE] reply error=[COZE] Error: 当前 Bot 未发布到对应渠道
[INFO][2024-06-16 16:12:16][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我暂时遇到了一些问题，请您稍后重试~), receiver=@5127d150e03e6f5b6cad95a92f0b8cf35a7cd0d6d66cee92d3e3fad3e1164acc
```

**Comment by 6vision** [comment]
建议咨询coze相关人员

**Comment by yuxx1006** [comment]
有答案吗？


> 建议咨询coze相关人员

**Comment by azz212** [comment]
这不是告诉你原因了吗
