### ISSUE TITLE
新增可以查询高铁（火车）票查询插件

### ISSUE THREAD

**Issue by He0607** [zhayujie/chatgpt-on-wechat#2086]
高铁（火车）票查询插件,可查询直达跟中转两种方式,查询后可发送+问题进行进一步的筛选
具体请看：https://github.com/He0607/HighSpeedTicket

**Comment by 6vision** [comment]
欢迎提交到plugins/source.json文件内

**Comment by He0607** [comment]
> 欢迎提交到plugins/source.json文件内

好的已经提交
