### ISSUE TITLE
有新成员加入时会自动欢迎这个怎么关闭

### ISSUE THREAD

**Issue by ccclllcl** [zhayujie/chatgpt-on-wechat#2087]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

有新成员加入时会自动欢迎这个怎么关闭

### 举例

有新成员加入时会自动欢迎这个怎么关闭

### 动机

有新成员加入时会自动欢迎这个怎么关闭

**Comment by ccclllcl** [comment]
能通过修改配置文件实现吗?具体怎么修改?

**Comment by ccclllcl** [comment]
> 把hello插件禁用了或者删除

能通过修改配置文件实现吗?具体怎么修改?

**Comment by 6vision** [comment]
> > 把hello插件禁用了或者删除
> 
> 能通过修改配置文件实现吗?具体怎么修改?

吧plugins/plugins.json里hello的配置设为false，
更多hello插件的配置可以参考 [hello](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/hello)
