### ISSUE TITLE
钉钉机器人群聊异常

### ISSUE THREAD

**Issue by gaodazhu** [zhayujie/chatgpt-on-wechat#2090]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

配置钉钉机器人stream模式，启动COW，群聊中 @机器人，会报错

### 问题描述 😯

钉钉配置成功后，私聊机器人正常， 在群聊中 @ 机器人 时，会报这个错误

### 终端日志 📒

```log
[INFO][2024-06-19 11:47:21][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2024-06-19 11:47:21][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为3927。
[INFO][2024-06-19 11:47:21][godcmd.py:210] - [Godcmd] inited
[INFO][2024-06-19 11:47:21][keyword.py:40] - [keyword] {}
[INFO][2024-06-19 11:47:21][keyword.py:42] - [keyword] inited.
[INFO][2024-06-19 11:47:21][role.py:69] - [Role] inited
[INFO][2024-06-19 11:47:21][dungeon.py:56] - [Dungeon] inited
[INFO][2024-06-19 11:47:21][hello.py:38] - [Hello] inited
[INFO][2024-06-19 11:47:21][finish.py:23] - [Finish] inited
2024-06-19 11:47:21,735 dingtalk_stream.client INFO     open connection, url=https://api.dingtalk.com/v1.0/gateway/connections/open [stream.py:131]
2024-06-19 11:47:21,868 dingtalk_stream.client INFO     endpoint is {'endpoint': 'wss://wss-open-connection.dingtalk.com:443/connect', 'ticket': 'a2327afb-2dee-11ef-87e2-56d2831a9f9a'} [stream.py:72]
[ERROR][2024-06-19 11:48:09][dingtalk_channel.py:127] - dingtalk process error='NoneType' object does not support item assignment
[INFO][2024-06-19 11:48:09][dingtalk_channel.py:69] - DingTalk message msgshH3vvjGTqR4mgutpqpNoQ== already received, ignore
```

**Comment by keymanlu** [comment]
如果方便可以贴一下你的config.json吗？把api_key和钉钉的secret等打码一下。

**Comment by cwxsss** [comment]
![PixPin_2024-06-21_11-11-41](https://github.com/zhayujie/chatgpt-on-wechat/assets/15844340/e62ad2c1-212c-4660-a530-06322d79f4dd)
同样的问题，我贴一下图

**Comment by keymanlu** [comment]
楼上的把
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/85289355/3524bc8d-1d45-42df-9832-b3f56c8f6533)
这里置空试试

**Comment by cwxsss** [comment]
group_chat_prefix  对这个字段进行了置空或者删除，报错和之前是一样的，还是不行

**Comment by keymanlu** [comment]
> group_chat_prefix 对这个字段进行了置空或者删除，报错和之前是一样的，还是不行

置空是这样的哦：
`"group_chat_prefix": [
    ""
  ],`

**Comment by cwxsss** [comment]
"group_chat_prefix": [ "" ],
制空后，已解决，可以正常回复了，感谢！
