### ISSUE TITLE
kimi api接口问题

### ISSUE THREAD

**Issue by bigKING67** [zhayujie/chatgpt-on-wechat#2091]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/101692994/5863f0ff-d71c-4a17-ab50-06c57c3f28fb)

### 问题描述 😯

换kimi api，测试时候不能返回对话结果，报错error
![ae3a62a7a3add34a332e9d5960a4bf6](https://github.com/zhayujie/chatgpt-on-wechat/assets/101692994/6134d4bc-efcf-4c42-8def-becda30757a1)

### 终端日志 📒

```log
[INFO][2024-06-19 18:07:21][chat_gpt_bot.py:49] - [CHATGPT] query=杭州美食
[WARNING][2024-06-19 18:07:21][chat_gpt_bot.py:145] - [CHATGPT] Bad Gateway: Invalid response object from API: '{"detail":"Model Not Exist"}' (HTTP response code was 400)
[WARNING][2024-06-19 18:07:31][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-06-19 18:07:31][chat_gpt_bot.py:145] - [CHATGPT] Bad Gateway: Invalid response object from API: '{"detail":"Model Not Exist"}' (HTTP response code was 400)
[WARNING][2024-06-19 18:07:41][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-06-19 18:07:41][chat_gpt_bot.py:145] - [CHATGPT] Bad Gateway: Invalid response object from API: '{"detail":"Model Not Exist"}' (HTTP response code was 400)
[INFO][2024-06-19 18:07:41][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
请再问我一次), receiver=@@14824b8ea60962075e15ba4a12009ffbbef4d90dfab07020681b361455c33f93
[INFO][2024-06-19 18:09:13][app.py:19] - signal 2 received, exiting...
[INFO][2024-06-19 18:09:13][config.py:228] - [Config] User datas saved.

```

**Comment by 6vision** [comment]
配置没生效，还是走的chatgpt对话，
