### ISSUE TITLE
个人微信方式支持图片和文章理解吗？

### ISSUE THREAD

**Issue by wolfking2000** [zhayujie/chatgpt-on-wechat#2093]
现在已经可以通过个人微信和chatgpt进行正常的问答。
通过这种方式如何上载图片并加上文本提问让chatgpt进行回答呢？
或者上载一个word之类的文档让chatgpt进行文章总结一类的工作呢？
请各位指教。

**Comment by sbcxk** [comment]
安装https://github.com/fatwang2/sum4all 插件即可

**Comment by lopins** [comment]
> 安装https://github.com/fatwang2/sum4all 插件即可 ![image](https://private-user-images.githubusercontent.com/67060479/341412097-f537cfb4-4611-4cf2-a4e3-d912278d1a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDg5MjMsIm5iZiI6MTcxOTE0ODYyMywicGF0aCI6Ii82NzA2MDQ3OS8zNDE0MTIwOTctZjUzN2NmYjQtNDYxMS00Y2YyLWE0ZTMtZDkxMjI3OGQxYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OTJkN2JjZjEyYzcwNmNkYjk3MmM0YjE2MmUyNzU0Njg1NDcxY2E5YWZhYmNmMzgwOTYxODFkMmU4ZDc3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rF6Orcj98YbSFUErGdvjF3LZtexAyG14v1ImztxUwnQ)

这个方式有点牵强啊，这个方式属于有点弱智了，应该在理解图片后做出对应的回应，而不是解释这个图片

**Comment by sbcxk** [comment]
> > 安装https://github.com/fatwang2/sum4all 插件即可 ![image](https://private-user-images.githubusercontent.com/67060479/341412097-f537cfb4-4611-4cf2-a4e3-d912278d1a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDg5MjMsIm5iZiI6MTcxOTE0ODYyMywicGF0aCI6Ii82NzA2MDQ3OS8zNDE0MTIwOTctZjUzN2NmYjQtNDYxMS00Y2YyLWE0ZTMtZDkxMjI3OGQxYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OTJkN2JjZjEyYzcwNmNkYjk3MmM0YjE2MmUyNzU0Njg1NDcxY2E5YWZhYmNmMzgwOTYxODFkMmU4ZDc3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rF6Orcj98YbSFUErGdvjF3LZtexAyG14v1ImztxUwnQ)
> 
> 这个方式有点牵强啊，这个方式属于有点弱智了，应该在理解图片后做出对应的回应，而不是解释这个图片

？？按自己需求改一下插件，换成自己需要的前缀不就行了？而且插件也支持图片解析后的追问，说这弱智我实在不理解。。。。。。

**Comment by 6vision** [comment]
项目内置了图像识别和文件总结的功能，配置LinkAI的服务即可：
{
"use_linkai": true,
    "linkai_api_key": "",
    "linkai_app_code": "",
}
注册即赠送测试积分，接入详细教程参考：https://docs.link-ai.tech/platform/link-app/wechat

**Comment by wolfking2000** [comment]
sum4all可以用。
