### ISSUE TITLE
drag_sensitive 函数报错

### ISSUE THREAD

**Issue by manjieqi** [zhayujie/chatgpt-on-wechat#2094]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

[ERROR][2024-06-20 17:09:51][config.py:257] - can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "/app/config.py", line 254, in drag_sensitive
    config_copy[key] = config_copy[key][0:3] + "*" * 5 + config_copy[key][-3:]
TypeError: can only concatenate list (not "str") to list

启动报上面的错误
配置文件是这么写的

environment:
      TZ: 'Asia/Shanghai'
      USE_GLOBAL_PLUGIN_CONFIG: True
      # OpenAI配置
      OPEN_AI_API_KEY: 'sk-xxxxxxxx'

### 问题描述 😯

应该是没考虑到KEY的值是一个字符串，而不是一个列表，配置文件中有很多KEY

### 终端日志 📒

```log
[ERROR][2024-06-20 17:09:51][config.py:257] - can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "/app/config.py", line 254, in drag_sensitive
    config_copy[key] = config_copy[key][0:3] + "*" * 5 + config_copy[key][-3:]
TypeError: can only concatenate list (not "str") to list
```

**Comment by zhayujie** [comment]
你好，你的镜像版本是多少，有更新到最新吗

**Comment by manjieqi** [comment]
> 你好，你的镜像版本是多少，有更新到最新吗

最新，就前几天更新的那个

**Comment by 6vision** [comment]
拉取最新代码即可，修复了该问题
