### ISSUE TITLE
Dokcer部署的，在哪个目录配置godcmd的config.json

### ISSUE THREAD

**Issue by willzzq** [zhayujie/chatgpt-on-wechat#2095]
Dokcer部署的，在哪个目录配置godcmd的config.json？

我复制一个docker-compose.yml文件到一个新目录，使用指令 docker compose up -d 启动后，发现向godcmd的config.json是新件的，里面的口令还是为空。原始文件在哪里设置？谢谢

**Comment by willzzq** [comment]
哦，晓得了，通过DockerComposer管理器找到改容器目录。不过复制相同容器每次都要重新设置和安装插件

**Comment by huangzhitian** [comment]
> 哦，晓得了，通过DockerComposer管理器找到改容器目录。不过复制相同容器每次都要重新设置和安装插件

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/129321746/68178d2d-ed7d-4c64-a0b4-23c772fd29ce)
给个建议，这样你随便更新版本随便删除重装容器，安装过的插件和一些插件用到的模块都还在，数据也保留，全映射到本地，另外在微信使用#installp xxxx 安装插件，插件也是安装在这里而不是docker容器

**Comment by willzzq** [comment]
> > 哦，晓得了，通过DockerComposer管理器找到改容器目录。不过复制相同容器每次都要重新设置和安装插件
> 
> ![image](https://private-user-images.githubusercontent.com/129321746/341952274-68178d2d-ed7d-4c64-a0b4-23c772fd29ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTYxMTksIm5iZiI6MTcxOTExNTgxOSwicGF0aCI6Ii8xMjkzMjE3NDYvMzQxOTUyMjc0LTY4MTc4ZDJkLWVkN2QtNGM2NC1hMGI0LTIzYzc3MmZkMjljZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNDEwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTcxMzczMTJiMDFmY2U0ZWMyMjRkMTZhNGY4ZDgxNGZlNTQ2NDhmNTNjOGVkMDg2MWM5Y2I5OWI0OWFjYWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HO0ahFoLrN5aNWG8kXI-IEw-yUy1Mg3TqzY3QjfIq7s) 给个建议，这样你随便更新版本随便删除重装容器，安装过的插件和一些插件用到的模块都还在，数据也保留，全映射到本地，另外在微信使用#installp xxxx 安装插件，插件也是安装在这里而不是docker容器

太感谢了，我试试看。正为此烦恼呢！

**Comment by willzzq** [comment]
太感谢了，我试试看。正为此烦恼呢！

**Comment by willzzq** [comment]
试了一下，有点问题。我把容器中的app目录复制过来，放到项目目录中    - .app/plugins:/app/plugins 。这样就可以了
设置下面的目录，会报错：
     - ./mod/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages
     - ./config.json:/app/config.json
 不知道config.json 是配置哪些参数？配置项目参数还是插件参数？ 我配置插件参数比如tool的，不行。

**Comment by willzzq** [comment]
试了一下，有点问题。我把容器中的app目录复制过来，放到项目目录中    - .app/plugins:/app/plugins 。这样就可以了
设置下面的目录，会报错：
     - ./mod/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages
     - ./config.json:/app/config.json
 不知道config.json 是配置哪些参数？配置项目参数还是插件参数？ 我配置插件参数比如tool的，不行。

**Comment by huangzhitian** [comment]
> 试了一下，有点问题。我把容器中的app目录复制过来，放到项目目录中 - .app/plugins:/app/plugins 。这样就可以了 设置下面的目录，会报错： - ./mod/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages - ./config.json:/app/config.json 不知道config.json 是配置哪些参数？配置项目参数还是插件参数？ 我配置插件参数比如tool的，不行。
在docker-compose.yml文件当前目录运行命令python3 -m venv mod，创建一个名叫mod的虚拟环境目录然后映射，-./mod/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages，把容器里的/usr/local/lib/python3.10/site-packages这个依赖文件夹复制替换到/mod/lib/python3.10/site-packages，大概300m,之后插件如果需要安装依赖，cd到plugins/xxx插件目录，启用虚拟环境命令 source mod/bin/activate ，安装依赖pip3 install -r requirements.txt，依赖会保存在mod目录而不是docker容器，之后deactivate 命令退出虚拟环境。另外- ./config.json:/app/config.json是映射项目的主配置，插件配置前往插件目录填下就行了。还不懂加我335180517我帮你远程

**Comment by willzzq** [comment]
太感谢，我试试看。

**Comment by willzzq** [comment]
我将Python 3.6.8升级到3.10.14，然后按照你这个操作，现在报错：
(mod) [root@VM_0_14_centos timetask]# source ../../../mod/bin/activate
(mod) [root@VM_0_14_centos timetask]# pip3 install -r requirements.txt
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://mirrors.tencent.com/pypi/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi/simple/arrow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi/simple/arrow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi/simple/arrow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi/simple/arrow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi/simple/arrow/
Could not fetch URL https://mirrors.tencent.com/pypi/simple/arrow/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='mirrors.tencent.com', port=443): Max retries exceeded with url: /pypi/simple/arrow/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement arrow>=1.2.3 (from versions: none)
ERROR: No matching distribution found for arrow>=1.2.3
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://mirrors.tencent.com/pypi/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='mirrors.tencent.com', port=443): Max retries exceeded with url: /pypi/simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
=================
暂时先不弄了。 这个config.json 里可以加群名重启容器生效，/plugins/config.json 可设置参数，已经解决了大问题了，让我加群名不要重建容器了。非常感谢！

**Comment by willzzq** [comment]
好像还不行。在config.json中配置的新群名，容器重启后并没有生效。看来必须配ALL_GROUP 了

**Comment by willzzq** [comment]
明白了：配置参数不要放在环境变量里。这样就可以实时重新加载了。感谢！

**Comment by 6vision** [comment]
可以挂载一个config.json来配置插件，
参考[docker部署](https://github.com/zhayujie/chatgpt-on-wechat?tab=readme-ov-file#3docker%E9%83%A8%E7%BD%B2)

也可以参考这个[docker部署cow教程](https://www.wangpc.cc/nec/docker-deploy-cow/)中的插件修改

**Comment by xukongkkkk** [comment]
> 哦，晓得了，通过DockerComposer管理器找到改容器目录。不过复制相同容器每次都要重新设置和安装插件
