### ISSUE TITLE
v1.6.7 为什么会出现这个错误信息呢

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#2096]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

<img width="1348" alt="截屏2024-06-22 18 19 09" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/146583103/571ba6b2-01cb-48d8-b6f2-274ab66fd6d9">

Python 3.11.8

### 问题描述 😯

运行后就出现这个错误信息,但是可以正常工作.不知道是什么原因

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
配置文件可以脱敏后截图看看嘛？

**Comment by 6vision** [comment]
拉取最新代码，修复了这个问题
