### ISSUE TITLE
在微信中发送指令 @bot $tool finance-news 美国 ，收不到信息，后台已经生成

### ISSUE THREAD

**Issue by willzzq** [zhayujie/chatgpt-on-wechat#2098]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Docker安装的CoW，
1. 找到plugins/tool目录，添加参数finance_news：
![微信截图_20240623114821](https://github.com/zhayujie/chatgpt-on-wechat/assets/34177946/4d9bd65b-6c5a-4de4-abec-7b4e25e421c0)
2. 重启容器并扫描日志中的二维码登录
3. 在私聊完成管理员认证
4. 私聊中发送： @bot $tool finance-news 美国 
5. 后台看到已经生成新闻内容，但是没有发到私聊窗口
![微信图片编辑_20240623114343](https://github.com/zhayujie/chatgpt-on-wechat/assets/34177946/076b03af-53e0-49d3-ba65-a614d14d418a)
6. 发送 @bot $tool morning_news 是能正常收到信息的
![微信图片编辑_20240623114237](https://github.com/zhayujie/chatgpt-on-wechat/assets/34177946/64d0acfd-0770-422c-8379-bf882c357a0d)

### 问题描述 😯

如上述复现步骤，执行指令 @bot $tool finance-news 美国    后，后台生成了新闻内容，但私聊窗口无法收到信息

### 终端日志 📒

```log
日志里没有异常信息
```

**Comment by willzzq** [comment]
原来是内容太长了。有什么办法取指定数量的新闻呢？

**Comment by 6vision** [comment]
配了banwords插件了么，也可能是这个插件设置的策略

指定数量那需要修改源码了，可以自己写插件

> 原来是内容太长了。有什么办法取指定数量的新闻呢？
