### ISSUE TITLE
docker部署接入fastgpt异常

### ISSUE THREAD

**Issue by xigexb** [zhayujie/chatgpt-on-wechat#2104]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

我本地部署的fastgpt，配置的oneapi，模型配置的阿里通义千问max
这是docker-compose文件
version: '2.0'
services:
  chatgpt-on-wechat:
    image: mirrors.ktthings.com:444/ktthings-docker/zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'openapi-jzs9s9ZrvCzCGbCieLUYdz3jf9J3jxNd9KinbGBmNmuR3boTvBUsaRC8'
      OPEN_AI_API_BASE: 'http://172.16.8.174:3000/api/v1'
      MODEL: 'qwen-max'
      BOT_TYPE: 'chatGPT'
      USE_AZURE_CHATGPT: 'True'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: 'ALL_GROUP'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      SUBSCRIBE_MSG: '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'

这里是日志

 [INFO][2024-06-24 07:36:38][bridge.py:61] - create bot dashscope for chat
chatgpt-on-wechat  | [ERROR][2024-06-24 07:36:38][chat_channel.py:302] - Worker return exception: str expected, not NoneType
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
chatgpt-on-wechat  |     result = self.fn(*self.args, **self.kwargs)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 169, in _handle
chatgpt-on-wechat  |     reply = self._generate_reply(context)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 192, in _generate_reply
chatgpt-on-wechat  |     reply = super().build_reply_content(context.content, context)
chatgpt-on-wechat  |   File "/app/channel/channel.py", line 38, in build_reply_content
chatgpt-on-wechat  |     return Bridge().fetch_reply_content(query, context)
chatgpt-on-wechat  |   File "/app/bridge/bridge.py", line 76, in fetch_reply_content
chatgpt-on-wechat  |     return self.get_bot("chat").reply(query, context)
chatgpt-on-wechat  |   File "/app/bridge/bridge.py", line 67, in get_bot
chatgpt-on-wechat  |     self.bots[typename] = create_bot(self.btype[typename])
chatgpt-on-wechat  |   File "/app/bot/bot_factory.py", line 55, in create_bot
chatgpt-on-wechat  |     return DashscopeBot()
chatgpt-on-wechat  |   File "/app/bot/dashscope/dashscope_bot.py", line 29, in __init__
chatgpt-on-wechat  |     os.environ["DASHSCOPE_API_KEY"] = self.api_key
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/os.py", line 685, in __setitem__
chatgpt-on-wechat  |     value = self.encodevalue(value)
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/os.py", line 757, in encode
chatgpt-on-wechat  |     raise TypeError("str expected, not %s" % type(value).__name__)
chatgpt-on-wechat  | TypeError: str expected, not NoneType

### 问题描述 😯

接入fastgpt配置的时候发生异常，按照官方配置

### 终端日志 📒

```log
<此处粘贴终端日志>
``` [INFO][2024-06-24 07:36:38][bridge.py:61] - create bot dashscope for chat
chatgpt-on-wechat  | [ERROR][2024-06-24 07:36:38][chat_channel.py:302] - Worker return exception: str expected, not NoneType
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
chatgpt-on-wechat  |     result = self.fn(*self.args, **self.kwargs)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 169, in _handle
chatgpt-on-wechat  |     reply = self._generate_reply(context)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 192, in _generate_reply
chatgpt-on-wechat  |     reply = super().build_reply_content(context.content, context)
chatgpt-on-wechat  |   File "/app/channel/channel.py", line 38, in build_reply_content
chatgpt-on-wechat  |     return Bridge().fetch_reply_content(query, context)
chatgpt-on-wechat  |   File "/app/bridge/bridge.py", line 76, in fetch_reply_content
chatgpt-on-wechat  |     return self.get_bot("chat").reply(query, context)
chatgpt-on-wechat  |   File "/app/bridge/bridge.py", line 67, in get_bot
chatgpt-on-wechat  |     self.bots[typename] = create_bot(self.btype[typename])
chatgpt-on-wechat  |   File "/app/bot/bot_factory.py", line 55, in create_bot
chatgpt-on-wechat  |     return DashscopeBot()
chatgpt-on-wechat  |   File "/app/bot/dashscope/dashscope_bot.py", line 29, in __init__
chatgpt-on-wechat  |     os.environ["DASHSCOPE_API_KEY"] = self.api_key
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/os.py", line 685, in __setitem__
chatgpt-on-wechat  |     value = self.encodevalue(value)
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/os.py", line 757, in encode
chatgpt-on-wechat  |     raise TypeError("str expected, not %s" % type(value).__name__)
chatgpt-on-wechat  | TypeError: str expected, not NoneType

**Comment by FEEHarrison** [comment]
怎么关闭了，怎么解决的？

**Comment by 6vision** [comment]
[INFO][2024-06-24 07:36:38][bridge.py:61] - create bot dashscope for chat

配置文件没生效，没走chatGPT bot
