### ISSUE TITLE
日志有打印出返回的数据，但微信收不到机器人的消息

### ISSUE THREAD

**Issue by wang422403** [zhayujie/chatgpt-on-wechat#2108]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/45872413/d3af8b07-ff70-4d4b-8a0f-2988e36ebb97)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/45872413/836b60be-cceb-41ed-acb0-5acbba9d8033)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
可以排查看看，群聊是否可以收到？重新运行是否可以收到？换号是否可以收到？

**Comment by wang422403** [comment]
群聊也收不到，重启也不行。手机直接登录那个微信是可以回复消息的。换号还没有试

**Comment by wangyang0210** [comment]
的却有类似的问题

**Comment by wang422403** [comment]
> 的却有类似的问题

你有解决吗？怎么解决？

**Comment by wangyang0210** [comment]
可以尝试换个账号，我这边的情况就是A账号存在问题，但是切换到B账号后就没有该问题，A账号是部署在服务器，一直在线的情况；

**Comment by wang422403** [comment]
> 可以尝试换个账号，我这边的情况就是A账号存在问题，但是切换到B账号后就没有该问题，A账号是部署在服务器，一直在线的情况；

那就是还是那个微信账号的问题？

**Comment by wangyang0210** [comment]
不一定的，如果是微信号有问题，可以看手机上是否有被微信拦截的消息，感觉可能是在线太久了，行为比较异常，我尝试把热加载关闭后，重新扫码登录A账号，发现又可以正常的交流了；

**Comment by wang422403** [comment]
> 不一定的，如果是微信号有问题，可以看手机上是否有被微信拦截的消息，感觉可能是在线太久了，行为比较异常，我尝试把热加载关闭后，重新扫码登录A账号，发现又可以正常的交流了；

好的，我到时候试下。的确，我直接用手机上微信人工回复消息是可以正常收到的，就是通过平台调用的就不行

**Comment by wang422403** [comment]
试了下，退出，微信重新扫码登录就可以了
