### ISSUE TITLE
调用fastgpt接口返回报错

### ISSUE THREAD

**Issue by simon0207** [zhayujie/chatgpt-on-wechat#2111]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

微信端输入bot获取当前时间返回

### 问题描述 😯

[WARNING][2024-06-26 11:53:55][session_manager.py:72] - Exception when counting tokens precisely for prompt: expected string or buffer
[ERROR][2024-06-26 11:54:00][chat_channel.py:302] - Worker return exception: can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/root/anaconda3/envs/chat/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 175, in _handle
    reply = self._decorate_reply(context, reply)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 260, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38057450/50604db8-a552-4b12-8717-510b9df77d82)
参数格式配置有问题，不要改变参数的类型

**Comment by mess-in-a-dress** [comment]
> 我也遇到了这个问题，我发现当fastgpt配置使用“工具调用”后，返回过来的reply.content是一个数组 ![image](https://private-user-images.githubusercontent.com/33646381/348966086-a24ba266-a6b7-4198-8f77-140ef654d15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjkxMTQsIm5iZiI6MTcyNDgyODgxNCwicGF0aCI6Ii8zMzY0NjM4MS8zNDg5NjYwODYtYTI0YmEyNjYtYTZiNy00MTk4LThmNzctMTQwZWY2NTRkMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3MDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NDZhODY5NWMwNzZhNTI4NTVkZjA0ZmY4YThlMThkYjViMTk2YjQwYTY4Yzg5OGU0NTI2MDIzNmRkZGVmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yzg67JLO-noG3keYIJ2cK0ldDq6bQV7KeBeo6RKpVnk) 这就导致了下面字符串拼接出错的问题

怎么解决呢

**Comment by Linnnkkk** [comment]
解决了吗？
