### ISSUE TITLE
建议代理参数添加 socks5 类型

### ISSUE THREAD

**Issue by hyjk555** [zhayujie/chatgpt-on-wechat#2115]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

代理参数目前只支持 http/https 有些代理软件只支持socks5。这就不好弄了。

### 举例

proxy="socks5://host:port"

### 动机

丰富代理支持类型

**Comment by 6vision** [comment]
测试过了，可以直接使用socks5h协议：
  "proxy": "socks5h://username:password@host:port",

**Comment by hyjk555** [comment]
感谢。5后面有个h，原来如此。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月8日(星期一) 凌晨0:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhayujie/chatgpt-on-wechat] 建议代理参数添加 socks5 类型 (Issue #2115)





 
测试过了，可以直接使用socks5h协议：
 "proxy": ***@***.***:port",
 
&mdash;

**Comment by melfebulu** [comment]
docker-compose.yaml 里面配置了 
      PROXY: 'socks5h://127.0.0.1:10808'
但是运行报错
[CHATGPT] APIConnectionError: Error communicating with OpenAI: Missing dependencies for SOCKS support.

SOCKS5h代理是可以工作的 在宿主机配置了/etc/systemd/system/docker.service.d/http-proxy.conf  ----- [Service]
Environment="HTTP_PROXY=socks5h://127.0.0.1:10808"
Environment="HTTPS_PROXY=socks5h://127.0.0.1:10808"   用docker pull 试过可以的

**Comment by melfebulu** [comment]
openai api不支持 socks5代理，需要修改。用下面这个可以用

# encoding:utf-8

import time
import openai
import openai.error
import logging
import httpx

from bot.bot import Bot
from bot.openai.open_ai_image import OpenAIImage
from bot.openai.open_ai_session import OpenAISession
from bot.session_manager import SessionManager
from bridge.context import ContextType
from bridge.reply import Reply, ReplyType
from common.log import logger
from config import conf

user_session = dict()

# 设置日志记录
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()

# OpenAI对话模型API (可用)
class OpenAIBot(Bot, OpenAIImage):
    def __init__(self):
        super().__init__()
        openai.api_key = conf().get("open_ai_api_key")
        if conf().get("open_ai_api_base"):
            openai.api_base = conf().get("open_ai_api_base")
        
        # 配置代理
        proxy = conf().get("proxy")
        if proxy:
            self.session = httpx.Client(proxies=proxy)
            openai.session = self.session

        self.sessions = SessionManager(OpenAISession, model=conf().get("model"))
        self.args = {
            "model": conf().get("model") ,  # 对话模型的名称
            "temperature": conf().get("temperature", 0.9),  # 值在[0,1]之间，越大表示回复越具有不确定性
            "max_tokens": 1200,  # 回复最大的字符数
            "top_p": 1,
            "frequency_penalty": conf().get("frequency_penalty", 0.0),  # [-2,2]之间，该值越大则更倾向于产生不同的内容
            "presence_penalty": conf().get("presence_penalty", 0.0),  # [-2,2]之间，该值越大则更倾向于产生不同的内容
            "request_timeout": conf().get("request_timeout", None),  # 请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
            "timeout": conf().get("request_timeout", None),  # 重试超时时间，在这个时间内，将会自动重试
            "stop": ["\n\n\n"],
        }

    def reply(self, query, context=None):
        # acquire reply content
        if context and context.type:
            if context.type == ContextType.TEXT:
                logger.info("[OPEN_AI] query={}".format(query))
                session_id = context["session_id"]
                reply = None
                if query == "#清除记忆":
                    self.sessions.clear_session(session_id)
                    reply = Reply(ReplyType.INFO, "记忆已清除")
                elif query == "#清除所有":
                    self.sessions.clear_all_session()
                    reply = Reply(ReplyType.INFO, "所有人记忆已清除")
                else:
                    session = self.sessions.session_query(query, session_id)
                    result = self.reply_text(session)
                    total_tokens, completion_tokens, reply_content = (
                        result["total_tokens"],
                        result["completion_tokens"],
                        result["content"],
                    )
                    logger.debug(
                        "[OPEN_AI] new_query={}, session_id={}, reply_cont={}, completion_tokens={}".format(str(session), session_id, reply_content, completion_tokens)
                    )

                    if total_tokens == 0:
                        reply = Reply(ReplyType.ERROR, reply_content)
                    else:
                        self.sessions.session_reply(reply_content, session_id, total_tokens)
                        reply = Reply(ReplyType.TEXT, reply_content)
                return reply
            elif context.type == ContextType.IMAGE_CREATE:
                ok, retstring = self.create_img(query, 0)
                reply = None
                if ok:
                    reply = Reply(ReplyType.IMAGE_URL, retstring)
                else:
                    reply = Reply(ReplyType.ERROR, retstring)
                return reply

    def reply_text(self, session: OpenAISession, retry_count=0):
        try:
            response = openai.ChatCompletion.create(messages=[{"role": "user", "content": str(session)}], **self.args)
            res_content = response.choices[0]["message"]["content"].strip()
            total_tokens = response["usage"]["total_tokens"]
            completion_tokens = response["usage"]["completion_tokens"]
            logger.info("[OPEN_AI] reply={}".format(res_content))
            return {
                "total_tokens": total_tokens,
                "completion_tokens": completion_tokens,
                "content": res_content,
            }
        except Exception as e:
            need_retry = retry_count < 2
            result = {"completion_tokens": 0, "content": "我现在有点累了，等会再来吧"}
            if isinstance(e, openai.error.RateLimitError):
                logger.warn("[OPEN_AI] RateLimitError: {}".format(e))
                result["content"] = "提问太快啦，请休息一下再问我吧"
                if need_retry:
                    time.sleep(20)
            elif isinstance(e, openai.error.Timeout):
                logger.warn("[OPEN_AI] Timeout: {}".format(e))
                result["content"] = "我没有收到你的消息"
                if need_retry:
                    time.sleep(5)
            elif isinstance(e, openai.error.APIConnectionError):
                logger.warn("[OPEN_AI] APIConnectionError: {}".format(e))
                need_retry = False
                result["content"] = "我连接不到你的网络"
            else:
                logger.warn("[OPEN_AI] Exception: {}".format(e))
                need_retry = False
                self.sessions.clear_session(session.session_id)

            if need_retry:
                logger.warn("[OPEN_AI] 第{}次重试".format(retry_count + 1))
                return self.reply_text(session, retry_count + 1)
            else:
                return result
