### ISSUE TITLE
为什么要把大语言模型固定，不可以像open webui一样灵活调用模型吗？

### ISSUE THREAD

**Issue by kpsmail** [zhayujie/chatgpt-on-wechat#2116]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

首先我不会编程，所以只能发这里来求助。
在open webui中(https://github.com/open-webui/open-webui/blob/main/backend/apps/openai/main.py)，向open ai key中填入one api key 和url，可以选择one api 中已有的任何模型，并且成功调用。

### 举例

https://github.com/open-webui/open-webui/blob/main/backend/apps/openai/main.py

### 动机

更灵活的使用大语言模型

**Comment by huangzhitian** [comment]
可以使用管理员命令改模型啊，wx不像网站点点鼠标救能改模型

**Comment by kpsmail** [comment]
> 可以使用管理员命令改模型啊，wx不像网站点点鼠标就能改模型

只能改提前写进去的模型，比如我在one api里有llama3 8B，COW里没有写llama3 8B，是选择不了的llama 8B的

**Comment by 6vision** [comment]
使用bot_type参数，详见 #2046

**Comment by huangzhitian** [comment]
> > 可以使用管理员命令改模型啊，wx不像网站点点鼠标就能改模型
> 
> 只能改提前写进去的模型，比如我在one api里有llama3 8B，COW里没有写llama3 8B，是选择不了的llama 8B的

别人不能预知未来，出什么模型就慢慢加上

**Comment by kpsmail** [comment]
> 使用bot_type参数，model写自定义的模型即可，不限于CoW项目内置模型名称，详见 #2046

学会了，确实是这个方法，到处都没找到教程，非常感谢兄弟

**Comment by t1804330987** [comment]
> 可以使用管理员命令改模型啊，wx不像网站点点鼠标就能改模型

这个管理员命令，可以在登录的时候更改使用的模型吗，想问下是什么命令，谢谢！

**Comment by huangzhitian** [comment]
> > 可以使用管理员命令改模型啊，wx不像网站点点鼠标就能改模型
> 
> 这个管理员命令，可以在登录的时候更改使用的模型吗，想问下是什么命令，谢谢！

#model 模型名字
