### ISSUE TITLE
不会回复信息

### ISSUE THREAD

**Issue by wh-yuxuan** [zhayujie/chatgpt-on-wechat#2117]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

接入企业微信机器人，不能回复信息，可以正常运行，也没报错。

### 问题描述 😯

version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      open_ai_api_key: 'sk-xxxxxxxx'
      open_ai_api_base: 'https://api.chatanywhere.com.cn/v1'
      model: 'gpt-3.5-turbo'
      proxy: ''
      single_chat_prefix: ''
      single_chat_reply_prefix: ''
      group_chat_prefix: ''
      group_name_white_list: ''
      image_create_prefix: ''
      conversation_max_tokens: 5000
      speech_recognition: 'False'
      character_desc: '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      expires_in_seconds: 3600
      use_global_plugin_config: 'True'
      use_linkai: 'False'
      channel_type: "wechatcom_app"
      wechatcom_corp_id: "wwxxxxxxx"
      wechatcomapp_secret: "xsxxxxxxxaWM"
      wechatcomapp_agent_id: "1000002"
      wechatcomapp_token: "1xxxxxxxxxz"
      wechatcomapp_aes_key: "2pxxxxxxxxxxxPoe"
      wechatcomapp_port: 9898
    ports:
      - 9898:9898

使用的是docker部署，宝塔面板，访问方式是http://ip:port/wxcomapp，企业微信配置成功了，使用的是第三方的API和PAIKEY,在其他方式调用这个是没问题的，麻烦帮我看一下是什么问题。

### 终端日志 📒

[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: wechatcomapp_agent_id=1000002
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: wechatcomapp_token=1MPcsBnmGd9chp0uoUdcmNDggMz
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: group_chat_prefix=
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: open_ai_api_base=https://api.chatanywhere.com.cn/v1
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: single_chat_prefix=
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: single_chat_reply_prefix=
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: wechatcom_corp_id=ww4be80922cee76a69
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: group_name_white_list=
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: speech_recognition=False
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: use_global_plugin_config=True
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: character_desc=你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: image_create_prefix=
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: wechatcomapp_port=9898
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: wechatcomapp_secret=xsRoHiAWD900G0m_MCSo3W13EnOfn1KB6SI3NQ2qaWM
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: open_ai_api_key=sk-iIJvJNH9QOXQp1kM28nGTHvrJPCZndZgqafqzoZLWBmTjfxO
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: wechatcomapp_aes_key=2pifvwOnVu1Kk38pTY9bMYfDLGCVeWn1NSJdrvUsPoe
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: expires_in_seconds=3600
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: proxy=
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: conversation_max_tokens=5000
[INFO][2024-06-30 14:38:28][config.py:280] - [INIT] override config by environ args: use_linkai=False
[INFO][2024-06-30 14:38:29][config.py:280] - [INIT] override config by environ args: model=gpt-3.5-turbo
[INFO][2024-06-30 14:38:29][config.py:280] - [INIT] override config by environ args: channel_type=wechatcom_app
[INFO][2024-06-30 14:38:29][config.py:295] - [INIT] load config: {'channel_type': 'wechatcom_app', 'model': 'gpt-3.5-turbo', 'open_ai_api_key': 'sk-*****fxO', 'claude_api_key': 'YOU*****KEY', 'text_to_image': 'dall-e-2', 'voice_to_text': 'openai', 'text_to_voice': 'openai', 'proxy': '', 'hot_reload': False, 'single_chat_prefix': '', 'single_chat_reply_prefix': '', 'group_chat_prefix': '', 'group_name_white_list': '', 'image_create_prefix': '', 'speech_recognition': False, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 5000, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '*****', 'linkai_app_code': '', 'wechatcomapp_agent_id': 1000002, 'wechatcomapp_token': '1MPcsBnmGd9chp0uoUdcmNDggMz', 'open_ai_api_base': 'https://api.chatanywhere.com.cn/v1', 'wechatcom_corp_id': 'ww4be80922cee76a69', 'use_global_plugin_config': True, 'wechatcomapp_port': 9898, 'wechatcomapp_secret': 'xsR*****aWM', 'wechatcomapp_aes_key': '2pi*****Poe'}
[INFO][2024-06-30 14:38:29][config.py:221] - [Config] User datas file not found, ignore.
ww4be80922cee76a69 xsRoHiAWD900G0m_MCSo3W13EnOfn1KB6SI3NQ2qaWM 1000002 1MPcsBnmGd9chp0uoUdcmNDggMz 2pifvwOnVu1Kk38pTY9bMYfDLGCVeWn1NSJdrvUsPoe
[INFO][2024-06-30 14:38:29][wechatcomapp_channel.py:39] - [wechatcom] init: corp_id: ww4be80922cee76a69, secret: xsRoHiAWD900G0m_MCSo3W13EnOfn1KB6SI3NQ2qaWM, agent_id: 1000002, token: 1MPcsBnmGd9chp0uoUdcmNDggMz, aes_key: 2pifvwOnVu1Kk38pTY9bMYfDLGCVeWn1NSJdrvUsPoe
[INFO][2024-06-30 14:38:29][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-06-30 14:38:29][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
chatgpt-tool-hub version: 0.5.0
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin tool_v0.5 registered, path=./plugins/tool
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2024-06-30 14:38:29][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2024-06-30 14:38:29][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为7231。
[INFO][2024-06-30 14:38:29][godcmd.py:210] - [Godcmd] inited
[INFO][2024-06-30 14:38:29][keyword.py:40] - [keyword] {}
[INFO][2024-06-30 14:38:29][keyword.py:42] - [keyword] inited.
[INFO][2024-06-30 14:38:29][linkai.py:35] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
█ [INFO][2024-06-30 14:38:29][tool.py:28] - [tool] inited
[INFO][2024-06-30 14:38:29][role.py:69] - [Role] inited
[INFO][2024-06-30 14:38:29][dungeon.py:56] - [Dungeon] inited
[INFO][2024-06-30 14:38:29][hello.py:38] - [Hello] inited
[INFO][2024-06-30 14:38:29][finish.py:23] - [Finish] inited
http://0.0.0.0:9898/
[INFO][2024-06-30 14:40:32][wechatcomapp_channel.py:147] - [wechatcom] receive params: <Storage {'timestamp': '1719758432', 'nonce': '1719965974', 'msg_signature': '475b9c20bab11bf20856512f1c2d84947ae6e241'}>
112.53.2.93:36050 - - [30/Jun/2024 14:40:32] "HTTP/1.1 POST /wxcomapp" - 200 OK

**Comment by 6vision** [comment]
参数的原本格式不要改变，
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/38057450/4279b368-b59f-43f3-8911-b34fad92c0f4)
