### ISSUE TITLE
是否考虑下提供企微群聊机器人的支持

### ISSUE THREAD

**Issue by ilikes** [zhayujie/chatgpt-on-wechat#2121]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

是否考虑下提供企微群聊机器人的支持，群聊机器人不需要设置可信IP，对于家庭使用来说方便些

**Comment by azz212** [comment]
企微可以，但底层就要完全替换了

**Comment by ilikes** [comment]
Get,我将在稍后回复你,^_^
