### ISSUE TITLE
当接收到微信发出的图片时，能自动转换成图片url，这样方便LLM调用和后续处理

### ISSUE THREAD

**Issue by longxingdeng** [zhayujie/chatgpt-on-wechat#2122]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 举例

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/134866140/753ca808-6a79-465c-b339-762fe0523e85)
像这样，每次需要LLM处理图片时的时候微信先要转换链接，就很不方便

### 动机

方便LLM对图片的后续处理，比如分析、调整、编辑等功能

**Comment by single228758** [comment]
识图不是有sum4all插件吗，如果要转成URL还得在把图片上传图床，再不行就魔改下大佬的插件![Screenshot_20240702-085736.png](https://github.com/zhayujie/chatgpt-on-wechat/assets/122099583/00f05a3b-b714-469d-b045-66decb5f327e)
