### ISSUE TITLE
群聊能否无需@ 直接触发?

### ISSUE THREAD

**Issue by 617450941** [zhayujie/chatgpt-on-wechat#2125]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

群聊能否无需@ 直接触发?

### 举例

群里有新的消息 机器人收到后自动回复 不需要@才触发回复

### 动机

用于快速回答群里的问题  @微信 太繁琐了

**Comment by sbcxk** [comment]
配置文件里面有，设置回复前缀就行了，设置为空就每条都回复。（这群就“热闹”了）
