### ISSUE TITLE
合并聊天记录如何获取内容触发AI？

### ISSUE THREAD

**Issue by SpringZhang1978** [zhayujie/chatgpt-on-wechat#2126]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

微信群多选多个聊天记录合并触发机器人，机器人读取不到合并消息

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by SpringZhang1978** [comment]
想找开发微信AI的伙伴一块探讨技术和问题，加v [Zhang__Spring]

**Comment by azz212** [comment]
解析xml里面的内容，提取关键信息
参考 https://github.com/azz212/chatgpt-on-wechat-ipad.git
