### ISSUE TITLE
寻开发伙伴组群一块探讨问题、互通有无、提高效率，加v 【Zhang__Spring】 （双下划线）暗号“AIBot”，谢谢！

### ISSUE THREAD

**Issue by SpringZhang1978** [zhayujie/chatgpt-on-wechat#2127]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

合并聊天不能被识别

### 问题描述 😯

合并聊天不能被识别

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by single228758** [comment]
有什么好玩插件分享吗🫣

**Comment by azz212** [comment]
https://github.com/azz212/chatgpt-on-wechat-ipad 很多插件
