### ISSUE TITLE
能否搞一个开关在群聊中@机器的人情况下不触发，只触发指定关键字

### ISSUE THREAD

**Issue by Zhengjie610** [zhayujie/chatgpt-on-wechat#2129]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

能否搞一个开关在群聊中@机器的人情况下不触发，只触发指定关键字

**Comment by single228758** [comment]
配置文件里修改

**Comment by Zhengjie610** [comment]
> 配置文件里修改
###是这一个参数吗，那如果需要关闭拍一拍触发呢
 "trigger_by_self": False,  # 是否允许机器人触发

**Comment by single228758** [comment]
> > 配置文件里修改
> ###是这一个参数吗，那如果需要关闭拍一拍触发呢
>  "trigger_by_self": False,  # 是否允许机器人触发  

是这里"group_chat_prefix": [
    "@bot",
    "@ai",
    "@AI",
    "@GPT"
  ],关闭拍一拍的话好像是help插件里

**Comment by Zhengjie610** [comment]
> > > 配置文件里修改
> > > ###是这一个参数吗，那如果需要关闭拍一拍触发呢
> > > "trigger_by_self": False,  # 是否允许机器人触发
> 
> 是这里"group_chat_prefix": [ "@bot", "@ai", "@ai", "@GPT" ],关闭拍一拍的话好像是help插件里

感谢回答，这个group_chat_prefix我试了，如果对@自己不生效。

**Comment by azz212** [comment]
自己改代码啊，不会可以学

**Comment by Zhengjie610** [comment]
> 自己改代码啊，不会可以学

好的谢谢你，已经改完了

**Comment by 6vision** [comment]
"group_at_off": False,  这个配置改为 true，在group_chat_prefix参数配置需要触发的关键词即可
