### ISSUE TITLE
【新增Suno音乐插件】可以文件图片分析，同时支持群聊模型控制，且实现Stable Diffusion图生图，文生图

### ISSUE THREAD

**Issue by Yanyutin753** [zhayujie/chatgpt-on-wechat#2130]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

最近和同学上python课，将之前的pictureChange升级更新了一下，现如今可以实现一下的功能：

- 支持运用百度AI进行图像处理
- 支持运用stable diffusion webui进行图像处理
- 支持运用stable diffusion webui画图，不影响dall-3画图
- 支持运用suno音乐组合AI进行图生音，文生音
- 支持运用AI进行文件总结，图片总结等
- 支持多种stable diffusion模型
- 支持管理员控制群聊图像，文件，音乐，更改群聊模型等功能
- 支持并发控制，管理员参数控制
- 支持stable diffusion图生图，文生图自定义模板
- 支持企业微信，个人号，公众号部署

#### Stable diffusion文生图，图生图

- 1. 文生图
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/132346501/4837ca40-d06e-48f0-ba45-24359bb3c244)

- 2. 图生图
![image](https://github.com/Yanyutin753/pictureChange/assets/132346501/4d6f16b0-136a-48d6-991e-482ce3bbc701)

![image](https://github.com/Yanyutin753/pictureChange/assets/132346501/783d6f22-c18e-4368-bc91-aa62a24c0c78)

#### 文件识别

![dd0b8389d12a753f37781259c0f6ea7](https://github.com/Yanyutin753/pictureChange/assets/132346501/d973d5ce-b228-4d98-8771-7ffddccaecb1)

#### 图片识别

![cf7e611c93f674098a3752f4f720a93](https://github.com/Yanyutin753/pictureChange/assets/132346501/94c171e4-2a96-4553-be82-998b39a962a5)

#### suno音乐

![ff731f85a945cac88772af6f2cad790](https://github.com/Yanyutin753/pictureChange/assets/132346501/dde5488a-d9b2-4c71-b971-28074a477db1)

![d2f549aec32642e0ff2dbc9ad4f8956](https://github.com/Yanyutin753/pictureChange/assets/132346501/264ede7d-e162-423b-b9d3-2cb145fd4cd5)

#### 点个星星吧！

**Comment by kpsmail** [comment]
suno模型要怎么配置？可以通过one api或者new api吗？

**Comment by Yanyutin753** [comment]
可以的 请参考suno2openai项目

**Comment by 6vision** [comment]
可以提交到该[source.json](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/source.json)文件

**Comment by Yanyutin753** [comment]
已经提交过了哈 谢谢🥳

**Comment by Yanyutin753** [comment]
不过可以改改插件的介绍 之前只是画图哈哈哈

**Comment by 6vision** [comment]
> 不过可以改改插件的介绍 之前只是画图哈哈哈

可以的，可以提交修改~

**Comment by BruceStayHungry** [comment]
您好，想问一下，微信场景下，可以支持局部重绘吗（手动选定区域）

**Comment by Yanyutin753** [comment]
这个功能不太行 目前都是按照参数进行重绘
