### ISSUE TITLE
无前缀私聊自问自答

### ISSUE THREAD

**Issue by xycjscs** [zhayujie/chatgpt-on-wechat#2134]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

设置 single-chat-prefix =[""]
私人对话提问任意问题。
机器人将会自问自答。

### 问题描述 😯

无前缀提问可以自动回答，但是回答后机器人就和自己自问自答了。
有没有办法让机器人不要回答来自自己的提问。屏蔽wxid？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
屏蔽了机器人自身的消息的
