### ISSUE TITLE
进群欢迎语怎么变成json结构数据了

### ISSUE THREAD

**Issue by willzzq** [zhayujie/chatgpt-on-wechat#2135]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

有新人进群时，弹出欢迎语

### 问题描述 😯

在微信群中欢迎语变成了json结构的数据：
@钱歌
{
    "thoughts": {
        "text": "需要随机选择一种风格来欢迎新用户'钱歌'加入群聊。",
        "reasoning": "决定采用热情活泼的风格来打招呼，以增加群聊的活力和新用户的归属感。",
        "criticism": "热情活泼的风格能够快速拉近与新用户的距离，让群聊显得更加友好。",
        "speak": ""
    },
    "tool": {
        "name": "answer-user",
        "input": "嗨～'钱歌'，热烈欢迎你加入我们的大家庭！在这里，你可以畅所欲言，分享快乐，我们期待与你一起开启精彩纷呈的群聊时光！"
    }
}

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
第三方api？使用的什么模型

**Comment by willzzq** [comment]
重新拉了最新版的，好了，没有这个问题了。应该老版本的bug
