### ISSUE TITLE
群里的定时任务早报 连续发了12条，前几天都是好的

### ISSUE THREAD

**Issue by willzzq** [zhayujie/chatgpt-on-wechat#2136]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在私聊中定义了
【IW9XBsOk】@慧可: 每天 09:02:00 虎嗅热榜

### 问题描述 😯

定时任务出现故障，今天早上连发了12条新闻。前几天都好的每天早上一条。我检查过，并没有在同一时间定时了多个任务
强烈建议：对于连续相同的内容限制最多只能发两条。
以前也发生过。
刚刚更新了最新版，看看这几天有没有这个问题。 

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
可以到[time task插件](https://github.com/haikerapples/timetask)仓库反馈~
