### ISSUE TITLE
OSError: No socket could be created -- (('0.0.0.0', 7870): [Errno 98] Address already in use)

### ISSUE THREAD

**Issue by Modas-Li** [zhayujie/chatgpt-on-wechat#2138]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

nohup python3 app.py & tail -f nohup.out

### 问题描述 😯

端口明明未被占用

### 终端日志 📒

[INFO][2024-07-08 11:14:39][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-07-08 11:14:39][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
chatgpt-tool-hub version: 0.5.0
[INFO][2024-07-08 11:14:39][plugin_manager.py:41] - Plugin tool_v0.5 registered, path=./plugins/tool
[INFO][2024-07-08 11:14:39][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为0679。
[INFO][2024-07-08 11:14:39][godcmd.py:210] - [Godcmd] inited
[INFO][2024-07-08 11:14:39][keyword.py:40] - [keyword] {}
[INFO][2024-07-08 11:14:39][keyword.py:42] - [keyword] inited.
[INFO][2024-07-08 11:14:39][linkai.py:35] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-07-08 11:15:02][tool.py:28] - [tool] inited
[INFO][2024-07-08 11:15:02][role.py:69] - [Role] inited
[INFO][2024-07-08 11:15:02][dungeon.py:56] - [Dungeon] inited
[INFO][2024-07-08 11:15:02][hello.py:38] - [Hello] inited
[INFO][2024-07-08 11:15:02][finish.py:23] - [Finish] inited
http://0.0.0.0:7870/
[ERROR][2024-07-08 11:15:02][app.py:66] - App startup failed!
[ERROR][2024-07-08 11:15:02][app.py:67] - No socket could be created -- (('0.0.0.0', 7870): [Errno 98] Address already in use)
Traceback (most recent call last):
  File "/data/chatgpt-on-wechat/app.py", line 61, in run
    start_channel(channel_name)
  File "/data/chatgpt-on-wechat/app.py", line 40, in start_channel
    channel.startup()
  File "/data/chatgpt-on-wechat/channel/wechatcom/wechatcomapp_channel.py", line 50, in startup
    web.httpserver.runsimple(app.wsgifunc(), ("0.0.0.0", port))
  File "/data/anaconda3/envs/wechat/lib/python3.10/site-packages/web/httpserver.py", line 176, in runsimple
    server.start()
  File "/data/anaconda3/envs/wechat/lib/python3.10/site-packages/cheroot/server.py", line 1844, in start
    self.prepare()
  File "/data/anaconda3/envs/wechat/lib/python3.10/site-packages/cheroot/server.py", line 1799, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('0.0.0.0', 7870): [Errno 98] Address already in use)

**Comment by 6vision** [comment]
端口占用，先结束之前运行的进程，报错复制给GPT，解释会很清楚~
