### ISSUE TITLE
是否可以外挂第三方知识库，有大佬实现的吗

### ISSUE THREAD

**Issue by Zhaogou721** [zhayujie/chatgpt-on-wechat#2143]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 举例

比如像智谱一样的知识库，该如何外挂

**Comment by hecunjie** [comment]
在zhipuai_bot.py文件中添加在知识库中的查询即可

**Comment by Zhaogou721** [comment]
> 在zhipuai_bot.py文件中添加在知识库中的查询即可

感谢
