### ISSUE TITLE
流式打字机效果如何修改文件

### ISSUE THREAD

**Issue by samqin123** [zhayujie/chatgpt-on-wechat#2144]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

有个话题被关掉了，但是readme里没看到对于stream sse的配置修改说明，请求添加

**Comment by 6vision** [comment]
这个项目的模型输出还不支持流式输出，流式输出也需要移动端支持，比如钉钉/飞书等可以支持，微信/公众号就不行，如果是刚需没有开发能力的话，可以使用LinkAI的服务，已实现钉钉和飞书接入的流式输出：[飞书](https://docs.link-ai.tech/platform/link-app/feishu)、[钉钉](https://docs.link-ai.tech/platform/link-app/dingtalk)
