### ISSUE TITLE
各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！

### ISSUE THREAD

**Issue by CCCpan** [zhayujie/chatgpt-on-wechat#2145]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！

### 问题描述 😯

各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by joyce677** [comment]
> ### 前置确认
> 
>     * [x]  我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。
> 
> 
> ### ⚠️ 搜索issues中是否已存在类似问题
> 
>     * [x]  我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
> 
> 
> ### 操作系统类型?
> 
> Windows
> ### 运行的python版本是?
> 
> python 3.7
> ### 使用的chatgpt-on-wechat版本是?
> 
> Latest Release
> ### 运行的`channel`类型是?
> 
> wx(个人微信, itchat)
> ### 复现步骤 🕹
> 
> 各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！
> ### 问题描述 😯
> 
> 各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！
> ### 终端日志 📒
> 
> ```
> <此处粘贴终端日志>
> ```

cow用的itchat发不了小程序的，可以用这个https://github.com/Tishon1532/chatgpt-on-wechat-win

**Comment by joyce677** [comment]
> > > ### 前置确认
> > > ```
> > > * [x]  我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### ⚠️ 搜索issues中是否已存在类似问题
> > > ```
> > > * [x]  我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 操作系统类型?
> > > Windows
> > > ### 运行的python版本是?
> > > python 3.7
> > > ### 使用的chatgpt-on-wechat版本是?
> > > Latest Release
> > > ### 运行的`channel`类型是?
> > > wx(个人微信, itchat)
> > > ### 复现步骤 🕹
> > > 各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！
> > > ### 问题描述 😯
> > > 各位大佬，求帮组，需要发送小程序，指定参数，路径，有偿，私聊！！
> > > ### 终端日志 📒
> > > ```
> > > <此处粘贴终端日志>
> > > ```
> > 
> > cow用的itchat发不了小程序的，可以用这个https://github.com/Tishon1532/chatgpt-on-wechat-win
> 
> linux服务器上能跑吗？还是只能win啊

只有win才能发，其他都不行
