### ISSUE TITLE
增加接入更多的其它的客户端，比如自部署的群晖 synology chat

### ISSUE THREAD

**Issue by rogerc66** [zhayujie/chatgpt-on-wechat#2150]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

微信本身并不可靠，官方会对长期挂桌面程序的号封号，可否增加接入其它的客户端，比如自部署的群晖 synology chat，这样一劳永逸，不用因为微信官方的原因造成服务中断

### 举例

微信本身并不可靠，官方会对长期挂桌面程序的号封号，可否增加接入其它的客户端，比如自部署的群晖 synology chat，这样一劳永逸，不用因为微信官方的原因造成服务中断

### 动机

微信本身并不可靠，官方会对长期挂桌面程序的号封号，可否增加接入其它的客户端，比如自部署的群晖 synology chat，这样一劳永逸，不用因为微信官方的原因造成服务中断

**Comment by 6vision** [comment]
参考[channel](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/channel)里的代码，根据需求增加新的客户端
