### ISSUE TITLE
认证的企业微信，设置域名回调，应该放在本项目的那个文件夹下

### ISSUE THREAD

**Issue by doman601** [zhayujie/chatgpt-on-wechat#2157]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

将下载的文件上传至填写域名根目录下 例如
http://xxxx/WW_verify_Fq59yEz1hetrogRO.txt

docker下怎么放这个文件

### 问题描述 😯

将下载的文件上传至填写域名根目录下 例如
http://xxxx/WW_verify_Fq59yEz1hetrogRO.txt

docker下怎么放这个文件

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
一般不需要，在购买域名的平台做个解析，用子域名指向服务器IP，然后填入企微后台的url里即可。参考[企微应用接入](https://docs.link-ai.tech/cow/multi-platform/wechat-com)
