### ISSUE TITLE
你好，我同时使用了openai的key和linkai的api 为什么每次回答我的都是linkai呢？

### ISSUE THREAD

**Issue by mcdullles** [zhayujie/chatgpt-on-wechat#2158]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by mcdullles** [comment]
我最初的想法是又能使用chatgpt又能通过linkai调用他的个人知识库，求大神帮忙，我是个纯纯的小白

**Comment by 6vision** [comment]
> 我最初的想法是又能使用chatgpt又能通过linkai调用他的个人知识库，求大神帮忙，我是个纯纯的小白

使用知识库就得使用linkai key，不然怎么对话呢~，LinkAI支持gpt模型，linkai-3.5即gpt-3.5，价格都差不多的。

use linkai 这个参数决定了是否使用linkai的对话服务，true是使用，false是不使用

**Comment by 205637827** [comment]
解决了吗这个
