### ISSUE TITLE
我想实现 发送自定义的消息，程序接收到后执行我写的代码，并返回

### ISSUE THREAD

**Issue by 754628709** [zhayujie/chatgpt-on-wechat#2161]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

能

### 问题描述 😯

我想实现 发送自定义的消息，接收到后执行我写的代码，并返回，例如我发送关键字/cmd time，系统看到/cmd命令就会调用我的代码，并找到time项，执行后并返回消息。

### 终端日志 📒

```log
无
```

**Comment by 6vision** [comment]
参考 [自定义插件开发](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins)，根据需求写个插件
