### ISSUE TITLE
对方发消息时引用了我的消息的话，bot就无法识别该消息并回复，这种有解决办法吗

### ISSUE THREAD

**Issue by PenguinYuhuan** [zhayujie/chatgpt-on-wechat#2162]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Sendu-sanxing** [comment]
因为微信的引用消息是xml消息，不是txt消息，要转换为txt消息发给bot，bot才能识别

**Comment by PenguinYuhuan** [comment]
> 因为微信的引用消息是xml消息，不是txt消息，要转换为txt消息发给bot，bot才能识别

好的，谢谢，我试试看
