### ISSUE TITLE
希望能够提供一个网络图片获取的插件，以便获取网络图片

### ISSUE THREAD

**Issue by JimWuuu** [zhayujie/chatgpt-on-wechat#2168]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望能够提供一个网络图片获取的插件，以便获取网络图片，之前接入了一个图片获取api，但过于死板。

### 举例

网络图片获取

### 动机

网络图片获取

**Comment by 6vision** [comment]
1、具备代码开发能力，根据[plugins开发文档](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins)写个插件，网上有些平台提供api接口，比如[vvhan](https://api.vvhan.com/)
2、无代码开发能力，可以使用LinkAI平台的[自定义插件](https://docs.link-ai.tech/platform/plugins/custom-plugins)，无需代码，填入相关参数即可，同样可以使用上边的[接口](https://api.vvhan.com/)
