### ISSUE TITLE
能升级机器人的版本吗？1.5.5有点太傻了

### ISSUE THREAD

**Issue by O-king** [zhayujie/chatgpt-on-wechat#217]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by live4fun** [comment]
的确够笨，比网页上回答差多了，另外用new bing回答更专业

**Comment by YYForReal** [comment]
可以试试在bot/openai/open_ai_bot.py文件第43行将原本的准确度`temperature`从0.9调低，0代表选取一个最准确的答案。

![image](https://user-images.githubusercontent.com/66943144/219826474-d65330c9-7c59-4421-80fd-55257c711c05.png)
