### ISSUE TITLE
Hello与BDunit插件无法使用，但能成功init和启动

### ISSUE THREAD

**Issue by Abyss-Seeker** [zhayujie/chatgpt-on-wechat#2170]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在拍一拍/拉新人入群的时候不会有反应，明明plugin的config.json（和hello插件的config.json，保险起见）都按要求配置好了
BDunit也是
在使用#help的时候显示这两个都已经启用，成功init，但是不在 可用插件 中
（虽然归根结底应该是我菜的原因

### 问题描述 😯

可用插件中只有
tool:这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
角色扮演:让机器人扮演不同的角色。
文字冒险:可以和机器人一起玩文字冒险游戏。
且的确只能用这几个；然而在启动的时候都能成功init。
**无法使用Hello和BDunit，但可以使用其他的**

plugin/config.json中有
    "hello": {
        "group_welc_fixed_msg": {
            "群聊1": "群聊1的固定欢迎语",
            "群聊2": "群聊2的固定欢迎语"
        },
        "group_welc_prompt": "请你随机使用一种可爱的风格说一句问候语来欢迎新用户\"{nickname}\"加入群聊。",

        "group_exit_prompt": "请你随机使用一种可爱的风格跟其他群用户说他\"{nickname}\"退出群聊并道别。",

        "patpat_prompt": "请你随机使用一种可爱的风格介绍你自己，并告诉用户输入#help可以查看帮助信息。",

        "use_character_desc": false
    }
    
   格式应该没错

### 终端日志 📒

```log
[INFO][2024-07-23 03:00:03][godcmd.py:210] - [Godcmd] inited
[INFO][2024-07-23 03:00:03][keyword.py:40] - [keyword] {}
[INFO][2024-07-23 03:00:03][keyword.py:42] - [keyword] inited.
[WARNING][2024-07-23 03:00:04][tool.py:234] - [tool] filter invalid tool: 'browser'
[WARNING][2024-07-23 03:00:04][tool.py:234] - [tool] filter invalid tool: 'news'
[WARNING][2024-07-23 03:00:04][tool.py:234] - [tool] filter invalid tool: 'visual'
[INFO][2024-07-23 03:00:04][tool.py:28] - [tool] inited
[INFO][2024-07-23 03:00:04][hello.py:38] - [Hello] inited
[INFO][2024-07-23 03:00:04][role.py:69] - [Role] inited
[INFO][2024-07-23 03:00:04][dungeon.py:56] - [Dungeon] inited
[INFO][2024-07-23 03:00:05][bdunit.py:40] - [BDunit] inited
[INFO][2024-07-23 03:00:05][finish.py:23] - [Finish] inited


[DEBUG][2024-07-23 03:08:53][wechat_channel.py:45] - [WX]group message 2885427936572881918 skipped: Unsupported note message: You invited <用户> to the group chat.   
```
同时在拍一拍(tickle)的时候也只会有类似上面的终端消息，不会自动回复。

**Comment by 6vision** [comment]
如果是python部署，插件配置是在**每个插件目录**下修改配置，不是plugins/config.json。

因配置文件错误可能导致插件被禁用，在plugins/plugins.json中开启再启动即可。
