### ISSUE TITLE
问问题一直提示[ERROR][2023-02-15 18:23:41][open_ai_bot.py:64] - Must provide an 'engine' parameter to create a <class 'openai.api_resources.completion.Completion'>

### ISSUE THREAD

**Issue by Duanxc-git** [zhayujie/chatgpt-on-wechat#218]
### 前置确认

1. 运行于国内网络环境，已经开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

问问题提示：[ERROR][2023-02-15 18:23:41][open_ai_bot.py:64] - Must provide an 'engine' parameter to create a <class 'openai.api_resources.completion.Completion'>

![}QCIGZU2PH9C385036EDDVS](https://user-images.githubusercontent.com/92433003/219001979-410d35eb-f26f-4ace-b6c2-3d70ab10dc7a.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：centos7.5
 - Python版本  ( 执行 `python3 -V` )：        Python 3.6.8              
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)

**Comment by duan-9991** [comment]
已经在config.json中填写了openai的apikey

**Comment by zhayujie** [comment]
openai的版本是多少
pip3 show openai

如果太低了可以先升级下pip
pip3 install --upgrade pip

再升级openai 
pip3 install --upgrade openai

**Comment by duan-9991** [comment]
> openai的版本是多少 pip3 show openai
> 
> 如果太低了可以先升级下pip pip3 install --upgrade pip
> 
> 再升级openai pip3 install --upgrade openai

我的openai版本是0.6.0但是我的系统是centos7.5不知道是不是系统的原因，Python版本是3.6。我准备用Ubuntu试一下

**Comment by zhayujie** [comment]
> > openai的版本是多少 pip3 show openai
> > 如果太低了可以先升级下pip pip3 install --upgrade pip
> > 再升级openai pip3 install --upgrade openai
> 
> 我的openai版本是0.6.0但是我的系统是centos7.5不知道是不是系统的原因，Python版本是3.6。我准备用Ubuntu试一下

升级下pip和openai就好了

**Comment by Duanxc-git** [comment]
> > > openai的版本是多少 pip3 show openai
> > > 如果太低了可以先升级下pip pip3 install --upgrade pip
> > > 再升级openai pip3 install --upgrade openai
> > 
> > 
> > 我的openai版本是0.6.0但是我的系统是centos7.5不知道是不是系统的原因，Python版本是3.6。我准备用Ubuntu试一下
> 
> 升级下pip和openai就好了

是的，谢谢大佬，我升级了openai 和pip可以正常聊天了，我看您说的是使用的uos的微信，这个现在还会封号吗。
还有一个问题，我现在不能根据描述生成图片，而是返回一个链接，但是这个链接是打不开的
![1676533743427](https://user-images.githubusercontent.com/92433003/219301108-08025b8b-c005-4275-b29f-efba06e06ec7.jpg)

**Comment by zhayujie** [comment]
1.会的
2.生成图片要命中 image_prefix 配置， 可以直接发送 "画一棵树"
