### ISSUE TITLE
如何关键字触发机器人？新人进群欢迎呢？

### ISSUE THREAD

**Issue by LoveClears** [zhayujie/chatgpt-on-wechat#2191]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

请帮我看一下的配置，这边好像都没进行生效

### 问题描述 😯

![image](https://github.com/user-attachments/assets/7cb0d549-7dc4-4b93-9e2b-868c6f82eb5b)
这是我的配置，我希望新人进群后 有个欢迎，也希望通过关键字能触发机器人的自动回复，目前来说好像都失效了，私聊没任何问题
@机器人 都能进行正常回复

是钉钉群

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by LoveClears** [comment]
看过#35 但是我没有解决 我不知道配置还要改哪里

**Comment by 6vision** [comment]
钉钉不支持进群欢迎，只能艾特触发。
微信是可以的关键词 ，前缀，艾特触发，以及进群欢迎。进群欢迎设置参考[hello插件](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/hello)

**Comment by LoveClears** [comment]
> 钉钉不支持进群欢迎，只能艾特触发。 微信是可以的关键词，远端，艾特触发，以及进群欢迎。进群欢迎设置参考[hello插件](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/hello)

非常感谢能够回复~
