### ISSUE TITLE
拍一拍和拉新人入群无响应，debug模式显示[WX]group message 2885427936572881918 skipped: Unsupported note message

### ISSUE THREAD

**Issue by Abyss-Seeker** [zhayujie/chatgpt-on-wechat#2205]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

**在拍一拍/拉新人入群的时候不会有反应。**
Hello似乎是正常启动了，因为我回复Hello或者End的时候都会回复插件中对应的消息和图片。

我确定我hello的config的**配置正确**

### 问题描述 😯

**在拍一拍/拉新人入群的时候不会有反应。**

可用插件中有

> tool:这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
> 角色扮演:让机器人扮演不同的角色。
> 文字冒险:可以和机器人一起玩文字冒险游戏。

且的确只能用这几个；然而在启动的时候**都能成功init。**

### 终端日志 📒

```[INFO][2024-07-23 03:00:03][godcmd.py:210] - [Godcmd] inited
[INFO][2024-07-23 03:00:03][keyword.py:40] - [keyword] {}
[INFO][2024-07-23 03:00:03][keyword.py:42] - [keyword] inited.
[WARNING][2024-07-23 03:00:04][tool.py:234] - [tool] filter invalid tool: 'browser'
[WARNING][2024-07-23 03:00:04][tool.py:234] - [tool] filter invalid tool: 'news'
[WARNING][2024-07-23 03:00:04][tool.py:234] - [tool] filter invalid tool: 'visual'
[INFO][2024-07-23 03:00:04][tool.py:28] - [tool] inited
[INFO][2024-07-23 03:00:04][hello.py:38] - [Hello] inited
[INFO][2024-07-23 03:00:04][role.py:69] - [Role] inited
[INFO][2024-07-23 03:00:04][dungeon.py:56] - [Dungeon] inited
[INFO][2024-07-23 03:00:05][bdunit.py:40] - [BDunit] inited
[INFO][2024-07-23 03:00:05][finish.py:23] - [Finish] inited


[DEBUG][2024-07-23 03:08:53][wechat_channel.py:45] - [WX]group message 2885427936572881918 skipped: Unsupported note message: You invited <用户> to the group chat.   
```
在排一排的时候也会有**[WX]group message 2885427936572881918 skipped: Unsupported note message**之类的，我怀疑是这个的问题。

**Comment by Abyss-Seeker** [comment]
问题解决了！发现是微信语言的问题。我使用的是英文端，拍一拍会显示为"tickled"而不是"拍了拍"，因此不会触发wechat_message.py中的以下行：
elif "拍了拍我" in itchat_msg["Content"]:
拉入群聊等同理。。希望能支持更多语言！

**Comment by Abyss-Seeker** [comment]
上传了一个pr支持英文端，望通过，感谢~

**Comment by Abyss-Seeker** [comment]
#2207

**Comment by Saboteur7** [comment]
已合并
