### ISSUE TITLE
部署完 python3 app.py报错。。。。。(已解决)

### ISSUE THREAD

**Issue by sparkshou** [zhayujie/chatgpt-on-wechat#221]
[root@www chatgpt-on-wechat]# python3 app.py
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from channel import channel_factory
  File "/root/chatgpt-on-wechat/channel/channel_factory.py", line 5, in <module>
    from channel.wechat.wechat_channel import WechatChannel
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 6, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'

**Comment by zhayujie** [comment]
itchat-uos 依赖安装了吗

**Comment by 1320611670** [comment]
![image](https://user-images.githubusercontent.com/77874445/219305562-dce39335-288a-428c-ac66-fc7cb93594d4.png)
我也是一样的错误

**Comment by moonspring233** [comment]
我也是报错，扫码后报错，
![企业微信截图_16765358249256](https://user-images.githubusercontent.com/112363009/219308508-4e1f8588-dd01-47cc-b843-66b2f56ff801.png)

**Comment by sparkshou** [comment]
我是挂在云服务器上的，需要用下面代码启动：一切正常了

touch nohup.out                                   # 首次运行需要新建日志文件                     
nohup python3 app.py & tail -f nohup.out          # 在后台运行程序并通过日志输出二维码

**Comment by lkyuier** [comment]
> itchat-uos

有谁知道怎么解决不？

**Comment by zhayujie** [comment]
> > itchat-uos
> 
> 有谁知道怎么解决不？

先看依赖安装情况：
pip3 show itchat-uos
pip3 show itchat
