### ISSUE TITLE
config.json中配置好 "hot_reload": true,

### ISSUE THREAD

**Issue by willzzq** [zhayujie/chatgpt-on-wechat#2213]
Linux解决方案（Docker Compose部署）：
1.  在config.json中配置好 "hot_reload": true,
2. 计划任务重添加定时执行 docker restart <container_id>

**Comment by qazxswaaa** [comment]
@willzzq 你好，计划任务是在哪设置啊

**Comment by qazxswaaa** [comment]
@willzzq 你好，计划任务具体要怎么设置呢
