### ISSUE TITLE
可以加入ip定位机制

### ISSUE THREAD

**Issue by JimWuuu** [zhayujie/chatgpt-on-wechat#2217]
### ⚠️ 搜索是否存在类似issue

- [ ] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

获取用户ip定位，当前位置定位以实现一些特殊功能

### 举例

比如地图导航路线规划，周边环境获取，基础设施，餐厅获取，等需要当前位置的信息获取

### 动机

使项目更加好用

**Comment by JimWuuu** [comment]
emmm我指的是cow获取微信消息发送者的ip或者位置定位噢😯

**Comment by 6vision** [comment]
开源项目仅供个人娱乐使用，暂不会提供涉及过度敏感内容及收付款等商业功能
