### ISSUE TITLE
Vllm部署在本地的模型提供出的Openai接口这边无法接通

### ISSUE THREAD

**Issue by Bkk-shuai** [zhayujie/chatgpt-on-wechat#2219]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Vllm部署，python3 -m vllm.entrypoints.openai.api_server --trust-remote-code   --model='/mnt/workspace/.cache/modelscope/hub/qwen/Qwen1___5-7B-Chat' --gpu-memory-utilization=0.95 --enforce-eager --port=5000 --host=172.xx.xx.xxx --tokenizer='/mnt/workspace/.cache/modelscope/hub/qwen/Qwen1___5-7B-Chat' --max-model-len=2000 --enable-lora --lora-modules sql=/mnt/workspace/lora/sleep --api-key '3f6b8a12-4d56-47e9-bf8c-2384e45a9cd2'

### 问题描述 😯

  "open_ai_api_key": "3f6b8a12-4d56-47e9-bf8c-2384e45a9cd2",
  "bot_type": "chatGPT",
  "model": "/root/.cache/modelscope/hub/qwen/Qwen1___5-7B-Chat",
  "open_ai_api_base":"http://172.xx.xx.xxx:5000/v1/chat/completions",

### 终端日志 📒

[WARNING][2024-08-08 14:26:49][chat_gpt_bot.py:145] - [CHATGPT] Bad Gateway: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)
[WARNING][2024-08-08 14:26:59][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-08-08 14:26:59][chat_gpt_bot.py:145] - [CHATGPT] Bad Gateway: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)
[WARNING][2024-08-08 14:27:09][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-08-08 14:27:09][chat_gpt_bot.py:145] - [CHATGPT] Bad Gateway: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)

**Comment by Bkk-shuai** [comment]
是不是response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)
只能用在官方的API上呢

**Comment by 6vision** [comment]
"open_ai_api_base":"http://172.xx.xx.xxx:5000/v1   写到这里即可，后面部分无需填写
