### ISSUE TITLE
回复中包含未定义的字符串“0:”

### ISSUE THREAD

**Issue by monk-after-90s** [zhayujie/chatgpt-on-wechat#2225]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用docker部署

### 问题描述 😯

机器人回复的消息都会有未定义的字符串“0:”，例如（SINGLE_CHAT_REPLY_PREFIX: ""）：
![image](https://github.com/user-attachments/assets/0c483801-da6f-4b75-808c-81931cf7d357)
或者（SINGLE_CHAT_REPLY_PREFIX: "[bot ]"）：
![image](https://github.com/user-attachments/assets/62eefd5e-36bf-471d-a498-bb46d29b33f6)

### 终端日志 📒

```log
[INFO][2024-08-09 04:12:54][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=0: 你好，有什么可以帮助你的么？), receiver=@b2acdb53b09748792df93a464b6a3a4d
```

**Comment by 6vision** [comment]
可以查看项目启动的日志中SINGLE_CHAT_REPLY_PREFIX参数的值是什么，可能是修改配置未生效

**Comment by monk-after-90s** [comment]
经检查，应该是fastgpt的问题，不是chatgpt-on-wechat的问题
