### ISSUE TITLE
同时使用两个API 

### ISSUE THREAD

**Issue by bonnie366** [zhayujie/chatgpt-on-wechat#2229]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

和其他第三方的API对比了一下，文本类模型的价格偏贵，但语音识别、合成的价格倒算合理，所以才有了这个想法，不知道能否实现，要怎么配置？

### 举例

例如：使用linkai 的语音识别、合成，再使用第三方的API的文字聊天

### 动机

出于价格考虑，可以接入两个最有性价比的API，使用成本最低

**Comment by bonnie366** [comment]
linkai和其他第三方API对比，文本价格偏贵

**Comment by 6vision** [comment]
> linkai和其他第三方API对比，文本价格偏贵

模型聚合只是linkai提供的基本服务，linkai更主要是一个应用创建平台，有插件，知识库，工作流等，这些也都是成本和服务，且平台价格和各个模型厂商官方价格差不多的。三方api只是提供api，不可只比价格~

**Comment by lopins** [comment]
> linkai和其他第三方API对比，文本价格偏贵

可以使用 [one-api](https://github.com/songquanpeng/one-api) 或者 [simple-one-api](https://github.com/fruitbars/simple-one-api)
