### ISSUE TITLE
微信自动收款以及发起收款请求的功能

### ISSUE THREAD

**Issue by hepengfe** [zhayujie/chatgpt-on-wechat#2232]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

希望bot能够完成自动收款的相关功能

### 举例

比如说企业微信做agent按月收费, 这样就可以让bot自动完成

**Comment by 6vision** [comment]
微信接入仅供个人娱乐使用，不宜提供商业相关功能~
