### ISSUE TITLE
多模型随机调用缓解速率不够或者回复较慢的问题

### ISSUE THREAD

**Issue by lopins** [zhayujie/chatgpt-on-wechat#2234]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

多模型随机调用，缓解速率不够或者回复较慢的问题：
同时启用多个模型，每次请求时遍历并随机 `"model": "openai,claude,gemini,wenxin,xunfei",` 调用一个

**Comment by 6vision** [comment]
每类模型的性能不同，同一个提示词不太适合所有模型；项目不支持同时启用多个模型
