### ISSUE TITLE
日志提示错误。不支持的bot: linkai

### ISSUE THREAD

**Issue by 13860605362** [zhayujie/chatgpt-on-wechat#2235]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

每次发送消息给AI就会提示

### 问题描述 😯

日志提示
[WARNING][2024-08-14 04:06:58][role.py:103] - 不支持的bot: linkai
以前没有这条提示，很久没关注了，没有修改过配置，好像有更新过容器。但是询问能正常回复

### 终端日志 📒

```log
<[WARNING][2024-08-14 04:06:58][role.py:103] - 不支持的bot: linkai>
```

**Comment by 6vision** [comment]
这个是role插件的warning日志，不影响正常对话，如果是python部署，可以直接拉取最新代码更新一下，如果是docker部署，等下次发版更新即可~

**Comment by 13860605362** [comment]
> 这个是role插件的warning日志，不影响正常对话，如果是python部署，可以直接拉取最新代码更新一下，如果是docker部署，等下次发版更新即可~

感谢解答，我是docker部署的。坐等更新了

**Comment by 6vision** [comment]
> > 这个是role插件的warning日志，不影响正常对话，如果是python部署，可以直接拉取最新代码更新一下，如果是docker部署，等下次发版更新即可~
> 
> 感谢解答，我是docker部署的。坐等更新了

已更新，不会再打印该日志
