### ISSUE TITLE
无法使用delle3画图.

### ISSUE THREAD

**Issue by 619dev** [zhayujie/chatgpt-on-wechat#2236]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

我使用的是docker compose部署.
在yaml文件里面配置好了
-----
version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'sk-x8fNJ******Ot1ua1AwM1j'
      OPEN_AI_API_BASE: 'https://api.aiproxy.io/v1'
      MODEL: 'gpt-4-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT私人助手", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      IMAGE_CREATE_SIZE: 1024x1024
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'True'
      CHARACTER_DESC: '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
    volumes:
      - ./config.json:/app/plugins/config.json

--------------config.json
{
  "channel_type": "wx",
  "model": "gpt-4-turbo",
  "bot_type": "chatGPT",
  "open_ai_api_key": "sk-x8f**********t1ua1AwM1j",
  "open_ai_api_base": "https://api.aiproxy.io/v1"
  "claude_api_key": "YOUR API KEY",
  "text_to_image": "dall-e-3",
  "voice_to_text": "openai",
  "text_to_voice": "openai",
  "proxy": "",
  "hot_reload": false,
  "use_azure_chatgpt": true,  # 是否使用azure的chatgpt
  "azure_deployment_id": "",  # azure 模型部署名称
  "azure_api_version": "",  # azure api版本
  # Bot触发配置
  "single_chat_prefix": ["bot", "@bot"],  # 私聊时文本需要包含该前缀才能触发机器人回复
  "single_chat_reply_prefix": "[bot] ",  # 私聊时自动回复的前缀，用于区分真人
  "single_chat_reply_suffix": "",  # 私聊时自动回复的后缀，\n 可以换行
  "group_chat_prefix": ["@bot"],  # 群聊时包含该前缀则会触发机器人回复
  "group_chat_reply_prefix": "",  # 群聊时自动回复的前缀
  "group_chat_reply_suffix": "",  # 群聊时自动回复的后缀，\n 可以换行
  "group_chat_keyword": [],  # 群聊时包含该关键词则会触发机器人回复
  "group_at_off": False,  # 是否关闭群聊时@bot的触发
  "group_name_white_list": ["ChatGPT私人助手", "ChatGPT测试群2"],  # 开启自动回复的群名称列表
  "group_name_keyword_white_list": [],  # 开启自动回复的群名称关键词列表
  "group_chat_in_one_session": ["ChatGPT测试群"],  # 支持会话上下文共享的群名称
  "nick_name_black_list": [],  # 用户昵称黑名单
  "group_welcome_msg": "",  # 配置新人进群固定欢迎语，不配置则使用随机风格欢迎
  "trigger_by_self": False,  # 是否允许机器人触发
  "text_to_image": "dall-e-3",  # 图片生成模型，可选 dall-e-2, dall-e-3
    # Azure OpenAI dall-e-3 配置
  "dalle3_image_style": "vivid", # 图片生成dalle3的风格，可选有 vivid, natural
  "dalle3_image_quality": "hd", # 图片生成dalle3的质量，可选有 standard, hd
  "image_create_prefix": [
    "画"
  ],
  "image_create_size": "1024x1024",
  "speech_recognition": true,
  "group_speech_recognition": true,
  "voice_reply_voice": true,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "character_desc": "你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
  "temperature": 0.7,
  "subscribe_msg": "感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,
  "linkai_api_key": "",
  "linkai_app_code": ""
}
--------------

### 问题描述 😯

普通的文字问答没有问题.
画图,语音识别都不能用.
感谢看到这里,请稍微指点,不胜感激.

### 终端日志 📒

```log
chatgpt-on-wechat  | [INFO][2024-08-14 11:18:28][wechat_channel.py:131] - Wechat login success, user_id: @6bef62b46b547855392768a5c6d55524ee7a2cebad6f2d0d8cbf79450e574d76, nickname: 619
chatgpt-on-wechat  | Start auto replying.
chatgpt-on-wechat  | [INFO][2024-08-14 11:18:36][bridge.py:68] - create bot chatGPT for chat
chatgpt-on-wechat  | [INFO][2024-08-14 11:18:37][open_ai_image.py:22] - [OPEN_AI] image_query=一只小猫
chatgpt-on-wechat  | [ERROR][2024-08-14 11:18:38][open_ai_image.py:42] - Invalid Resolution,Only support 1024x1024,1024x1792,1792x1024
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/app/bot/openai/open_ai_image.py", line 23, in create_img
chatgpt-on-wechat  |     response = openai.Image.create(
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/image.py", line 39, in create
chatgpt-on-wechat  |     response, _, api_key = requestor.request(
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
chatgpt-on-wechat  |     resp, got_stream = self._interpret_response(result, stream)
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
chatgpt-on-wechat  |     self._interpret_response_line(
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
chatgpt-on-wechat  |     raise self.handle_error_response(
chatgpt-on-wechat  | openai.error.InvalidRequestError: Invalid Resolution,Only support 1024x1024,1024x1792,1792x1024
chatgpt-on-wechat  | [INFO][2024-08-14 11:18:38][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
chatgpt-on-wechat  | 画图出现问题，请休息一下再问我吧), receiver=@f9e58aeb34da829783d4d216f658f830b981776b6f855b3a8c001a6628ce899a
root@racknerd-1fded96:~/chatgpt-on-wechat# 
```

**Comment by Standy0215** [comment]
感觉试试把image_create_size这个配置去掉看看呢

休息一下感觉像是没有额度了

**Comment by 619dev** [comment]
注册了linkai,画图可以用了.
但是发语音条机器人还是没反应.
wechaty也用不了.

**Comment by kuangdd2024** [comment]
这个项目把增加了notebot的bot，notebot的文生图用的是免费的pollinations，效果还不错，可以参考。

项目：
https://github.com/kuangdd2024/wechatgpt-agent

About：
chatgpt agent for wechat，基于大模型（LLM）搭建的聊天机器人（Chatbot），支持RAG的记忆智能体（Memory Agent），用户随时随地随心随意地记录点滴。
