### ISSUE TITLE
tool工具发送的早报如何发送图片？

### ISSUE THREAD

**Issue by zeto1366** [zhayujie/chatgpt-on-wechat#2243]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by CJSen** [comment]
仔细看配置项，里头有一个“morning_news_output_type”用于配置文本还是图片。

**Comment by 6vision** [comment]
也可以用这个插件，比较简单点，可选文本还是图片：[apilot](https://github.com/6vision/Apilot)

**Comment by CJSen** [comment]
> 仔细看配置项，里头有一个“morning_news_output_type”用于配置文本还是图片。

也可以看看我自己写的一个小插件，仅早报功能。支持自定义早报消息格式（图片，文字），支持自定义关键词。
https://github.com/CJSen/mnews

**Comment by bin862324915** [comment]
> > 仔细看配置项，里头有一个“morning_news_output_type”用于配置文本还是图片。
> 
> 也可以看看我自己写的一个小插件，仅早报功能。支持自定义早报消息格式（图片，文字），支持自定义关键词。 https://github.com/CJSen/mnews

大佬，，这个可以写成同时发送文本跟图片吗

**Comment by zeto1366** [comment]
> 仔细看配置项，里头有一个“morning_news_output_type”用于配置文本还是图片。

这个我设置了image的格式，但是发送到微信是一条链接，无办法显示图片

**Comment by zeto1366** [comment]
> 也可以用这个插件，比较简单点，可选文本还是图片：[apilot](https://github.com/6vision/Apilot)

谢谢大佬，这个好用！
