### ISSUE TITLE
讯飞星火调用出现请求错误: 10003

### ISSUE THREAD

**Issue by Rensr0** [zhayujie/chatgpt-on-wechat#2252]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1、创建并启动 XunFei 聊天机器人。
2、发送示例查询 (你好)。
3、启动 WebSocket 连接并尝试处理请求。
Start auto replying.
[INFO][2024-08-18 23:02:31][bridge.py:68] - create bot xunfei for chat
[INFO][2024-08-18 23:02:31][xunfei_spark_bot.py:60] - [XunFei] query=你好
[INFO][2024-08-18 23:02:31][xunfei_spark_bot.py:107] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好'}]
[INFO][2024-08-18 23:02:32][xunfei_spark_bot.py:206] - [XunFei] Start websocket, session_id=@00fb96fefb106905ec4e06713da5ab09096593e15238de48bd028beca7e4efa8_172399335183
[ERROR][2024-08-18 23:02:32][xunfei_spark_bot.py:225] - 请求错误: 10003, {'header': {'code': 10003, 'message': 'ClientMsgError:(23:02:32.721) invalid model domain', 'sid': 'cht000b0c24@dx1916602ea10b808550', 'status': 2}}
[INFO][2024-08-18 23:03:03][xunfei_spark_bot.py:93] - [XunFei-API] response=, time=31.159862518310547s, usage={}

### 问题描述 😯

在使用 xunfei_spark_bot.py 进行聊天请求时，遇到了请求错误代码 10003。以下是相关的日志记录：

### 终端日志 📒

```log
[INFO][2024-08-18 23:02:31][bridge.py:68] - create bot xunfei for chat
[INFO][2024-08-18 23:02:31][xunfei_spark_bot.py:60] - [XunFei] query=你好
[INFO][2024-08-18 23:02:31][xunfei_spark_bot.py:107] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好'}]
[INFO][2024-08-18 23:02:32][xunfei_spark_bot.py:206] - [XunFei] Start websocket, session_id=@00fb96fefb106905ec4e06713da5ab09096593e15238de48bd028beca7e4efa8_172399335183
[ERROR][2024-08-18 23:02:32][xunfei_spark_bot.py:225] - 请求错误: 10003, {'header': {'code': 10003, 'message': 'ClientMsgError:(23:02:32.721) invalid model domain', 'sid': 'cht000b0c24@dx1916602ea10b808550', 'status': 2}}
[INFO][2024-08-18 23:03:03][xunfei_spark_bot.py:93] - [XunFei-API] response=, time=31.159862518310547s, usage={}
```

**Comment by 6vision** [comment]
参数配置有问题，参考：https://github.com/zhayujie/chatgpt-on-wechat/pull/2198
