### ISSUE TITLE
怎么实现在群聊中@某人

### ISSUE THREAD

**Issue by wumengze1993** [zhayujie/chatgpt-on-wechat#2254]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

it_chat和we_chaty里有没有在群聊中固定@某人的功能？

### 举例

比如我在群A里想要@群友B，然后我在工作流中实现了自动寻找群友B的昵称。现在需要@群友B昵称。

### 动机

自动应答功能

**Comment by AlayaElla** [comment]
找到方法了吗？

**Comment by wumengze1993** [comment]
> 找到方法了吗？

没有。我自己修改了下代码，但是没有效果。

**Comment by 6vision** [comment]
应该是协议不支持
