### ISSUE TITLE
请问一下开发大佬们,这个linkai插件中的mj画图是使用的哪里的api啊? 我在lnik-ai没看到提供mj画图的接口啊.

### ISSUE THREAD

**Issue by 619dev** [zhayujie/chatgpt-on-wechat#2258]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

难道是免费的mj接口吗?

**Comment by part221** [comment]
同问，生成图片是否只能用linkai的api，如果想要接入通义千问大模型的api生成图片需要如何改配置

**Comment by 6vision** [comment]
是的，可以在项目里使用或者平台使用mj画图，没有对外提供mj的api服务。

**Comment by 6vision** [comment]
> 同问，生成图片是否只能用linkai的api，如果想要接入通义千问大模型的api生成图片需要如何改配置

项目里通义千问大模型代码应该没有支持画图。项目支持dalle画图，可以不用linkai的api。
用linkai的api的话，可以直接用dalle和mj画图。
