### ISSUE TITLE
docker-compose.yml的角色不生效

### ISSUE THREAD

**Issue by Arrding** [zhayujie/chatgpt-on-wechat#2259]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

docker-compose.yml：

      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是生活顾问 ABC，负责回答有关生活常识相关问题。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'

### 问题描述 😯

采用docker安装，docker-compose.yml里设置的角色，没有起作用。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Arrding** [comment]
请问要怎么设置才生效？

**Comment by Arrding** [comment]
我接的是星火，该不会是星火的原因吧

**Comment by 6vision** [comment]
> 我接的是星火，该不会是星火的原因吧

是的，星火官方之前的模型没支持system ，Spark 4.0Ultra/Max才支持。
项目的代码目前还没支持system

**Comment by 6vision** [comment]
最新代码已优化，讯飞支持角色设定，等过两天发版，更新镜像即可，参考：https://github.com/zhayujie/chatgpt-on-wechat/pull/2268
