### ISSUE TITLE
Pycharm  py3.9环境,登录成功后聊天报错

### ISSUE THREAD

**Issue by privateheart** [zhayujie/chatgpt-on-wechat#226]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```
[在此处粘贴终端日志]
```
![image](https://user-images.githubusercontent.com/20622090/219298596-06bad181-ea04-4c54-bb38-6641a86b10eb.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
python版本多少， 是否在 3.7~3.9 ?

**Comment by privateheart** [comment]
我的是py3.9，我已经改好了，我把itchat 里的 utils.py里的代码我改了

from HTMLParser import HTMLParser
import html #首先导入html

htmlParser = HTMLParser()

d[k]  = html.unescape(d[k]) #这里把htmlParser改成html

来自：https://www.cnblogs.com/xiu123/p/16718798.html
