### ISSUE TITLE
我自己搭建了 ollama，能够直接给这个项目使用吗？

### ISSUE THREAD

**Issue by liuhedev** [zhayujie/chatgpt-on-wechat#2263]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我自己搭建了 ollama，能够直接给这个项目使用吗？

### 举例

无

### 动机

无

**Comment by 6vision** [comment]
如果你想使用本地部署的大模型，并且该模型兼容OpenAI的接口，可以按照以下配置接入：

{
“open_ai_api_key”: “你的密钥”,
“bot_type”: “chatGPT”,
“model”: “本地模型名字”,
“open_ai_api_base”: “本地模型接口地址”
}

如果你的本地模型不兼容OpenAI接口，你需要自己新写一个bot类型，可以参考已有的bots代码：[https://github.com/zhayujie/chatgpt-on-wechat/tree/master/bot。](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/bot%E3%80%82)
