### ISSUE TITLE
是否支持第三方的openai代理和key？

### ISSUE THREAD

**Issue by jiaokele** [zhayujie/chatgpt-on-wechat#2270]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 举例

第三方免费的代理key，我看bot是直连open ai的地址的不是使用代理地址

**Comment by 6vision** [comment]
支持第三方的OpenAI代理和API Key。你可以在config.py文件中找到"open_ai_api_base"参数，将其复制到config.json文件，并填入代理服务的URL即可
回答来自，[项目助手](https://link-ai.tech/app/Kv2fXJcH)

**Comment by 449121927** [comment]
> 请问成功了吗？我用了第三方服务的api，也改了url，但是还是报错了。出现了以下情况： Bad Gateway: HTTP code 200 from API (<!doctype html><title>B3n AI Relay System</title><script defer="defer" src="/static/js/main.ae12e722.js"></script>You need to enable JavaScript to run this app.
> 
> )

解决了，是没有加路径上少加了个 /v1
