### ISSUE TITLE
如何监听群成员是否改名

### ISSUE THREAD

**Issue by lovehug-lin** [zhayujie/chatgpt-on-wechat#2280]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

如何鉴定群成员是否改名

### 举例

🔔改名报告🔔
😱群里有个小可爱改了昵称哦
👉原昵称是:仙
👉新昵称是:仙儿2.9而已

### 动机

如何监听群成员是否改名

**Comment by 6vision** [comment]
项目不支持，需要看看itchat协议是否会有该事件，可以自行查看源码
