### ISSUE TITLE
请问如何适配本地大模型 例如Ollama3 glm4

### ISSUE THREAD

**Issue by MichaelPanwenjie** [zhayujie/chatgpt-on-wechat#2283]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

请问如何适配本地大模型 例如Ollama3 glm4
能否实现这个功能呢？

**Comment by lucifer6120** [comment]
> 已存在分支 https://github.com/Joycc/chatgpt-on-wechat/tree/feature-branch-add_ollama

没看出和现在MAIN区别啊

**Comment by taozhiyuai** [comment]
有免费的API后,本地ollama就没那么重要了. 搜索下issue,还有其他作者的修改,我用的蛮好. 但还是用免费glm flash吧.

**Comment by 6vision** [comment]
如果是openai格式的，可以使用bot_type参数，然后把api base写本地的地址即可
