### ISSUE TITLE
请问有打算支持gpt-4o-2024-08-06吗

### ISSUE THREAD

**Issue by lazybabyz** [zhayujie/chatgpt-on-wechat#2284]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

已经在这里[common](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/common)
/const.py看过并没有gpt-4o-2024-08-06

**Comment by 6vision** [comment]
配置文件可以这么写，即可调用：

**Comment by 6vision** [comment]
最新代码也支持了0806模型，可以拉取最新代码，配置model即可

**Comment by lazybabyz** [comment]
可以应用了 感谢
