### ISSUE TITLE
钉钉感知卡片没有逐步展示内容

### ISSUE THREAD

**Issue by OSOPEN** [zhayujie/chatgpt-on-wechat#2294]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1. config.json配置dingtalk_card_enabled为true
2. 配置钉钉感知卡片
3. 在钉钉聊天窗口发送内容。
4. 查看打印chatgpt回复内容的日志，内容为流式输出，还是一次展示。

### 问题描述 😯

目前展示效果，获取chatgpt全部内容后，再通过钉钉卡片逐步展示到聊天窗口。
正确展示效果应该是，一边从chatgpt逐步获取内容，一边展示到钉钉聊天窗口。

### 终端日志 📒

```log
[INFO][2024-09-09 11:16:34][dingtalk_channel.py:181] - [Dingtalk] sendMsg=Reply(type=TEXT, content=[bot] 你好！有什么问 题我可以帮助你解决呢？)
```

**Comment by 6vision** [comment]
是的，项目还没支持大模型的流式输出
