### ISSUE TITLE
gemini api 现在可以图生文和文生图吗

### ISSUE THREAD

**Issue by lazybabyz** [zhayujie/chatgpt-on-wechat#2295]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在gemini网站上已经可以图生文和文生图了,在cow chatgpt和claude也可以文生图 就不知道gemini什么时候可以.

### 举例

https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=web&authuser=4&%3Bhl=zh-tw&hl=zh-cn#generate-text-from-text-and-image-input

**Comment by FIELA** [comment]
why is this issue colse?do we have a solutions?

**Comment by Bronylaw** [comment]
Vc

Pada Kha, 1 Mei 2025, 6:40 PM FIELA ***@***.***> menulis:
