### ISSUE TITLE
对话代码部分会被省略？

### ISSUE THREAD

**Issue by Basyaact** [zhayujie/chatgpt-on-wechat#23]
在微信端提问例如“如何使用x语言实现xxx”，而返回的结果没有代码部分。

**Comment by zhayujie** [comment]
这个是 openAI 提供接口的问题，有时候会不太问题。暂时没有什么太好的方法， 只能换个问法试试。 我试了下是有代码部分的

<img width="955" alt="image" src="https://user-images.githubusercontent.com/26161723/210360015-f74b099f-02b2-4fc0-9cca-61a402b3b5fc.png">

另外确认下，你的openai版本是 0.25.0 吗
