### ISSUE TITLE
能否可以选择在微信的ai回复中不显示*和#符号

### ISSUE THREAD

**Issue by JimWuuu** [zhayujie/chatgpt-on-wechat#2302]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在微信与ai交流中总是会出现#和*符号，可以选择不显示他们吗。

### 举例

![IMG_0839](https://github.com/user-attachments/assets/1f89c115-3462-4b82-81d9-e99914af0120)

### 动机

可以使回复更加简洁易懂，美观

**Comment by 6vision** [comment]
这是markdown格式，模型生成回复时候会偏向于以markdown格式，可以在设定中，告诉模型不要使用markdown格式输出。
以上能降低，但不能保证一定不会出现这些符号。
可以考虑修改代码，输出时候，通过工程能力去掉这些符号

**Comment by 6vision** [comment]
可以更新到最新代码，初步优化了markdown格式展示，去掉了常见的**对
