### ISSUE TITLE
账户免费的18美金用完之后，更新APIKEY ，为什么更新了以后，还是不能用？

### ISSUE THREAD

**Issue by LTalong** [zhayujie/chatgpt-on-wechat#231]
![image](https://user-images.githubusercontent.com/49200327/219415349-831f0e46-c3ee-4fe4-aef9-6520fd903d87.png)
![image](https://user-images.githubusercontent.com/49200327/219415612-c39d6923-22ba-43ec-a6e3-d053cb4f380f.png)
这里的秘钥已经更改过，请问如何关掉进程，重启进程？

**Comment by zhayujie** [comment]
参考README中服务器部署一节， kill掉进程重新启动

**Comment by LTalong** [comment]
> 
谢谢，我重新生成二维码，并退出已经登录的微信，重新扫码解决了，

**Comment by LIU-ZHIHAO** [comment]
> 



> > 
> 
> 谢谢，我重新生成二维码，并退出已经登录的微信，重新扫码解决了，

你wx还没被封？

**Comment by Rwindest168888** [comment]
这么厉害，没封号？我的号一周不敢上了
