### ISSUE TITLE
有算命，测八字的插件嘛？

### ISSUE THREAD

**Issue by Yumikolab** [zhayujie/chatgpt-on-wechat#2312]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

有的话，告知下地址，谢谢

**Comment by ejohnyu** [comment]
直接连接百度

**Comment by 6vision** [comment]
如果是用的LinkAI的服务，吧linkai app code改为这个[应用](https://link-ai.tech/app/zgXaOntR)的即可：zgXaOntR

**Comment by Yumikolab** [comment]
> 如果是用的LinkAI的服务，吧linkai app code改为这个[应用](https://link-ai.tech/app/zgXaOntR)的即可：zgXaOntR

如果把应用设置成这个，那么机器人，就只能是这个算命的机器人吗？

**Comment by 6vision** [comment]
> > 如果是用的LinkAI的服务，吧linkai app code改为这个[应用](https://link-ai.tech/app/zgXaOntR)的即可：zgXaOntR
> 
> 如果把应用设置成这个，那么机器人，就只能是这个算命的机器人吗？

是的。其实也可以用linkai提供的自定义插件功能，去调用这个应用，把这个应用当一个插件
