### ISSUE TITLE
使用Moonshot Bot发现疑似Bug，正常对话时输入Token数量异常增加，产生大量计费

### ISSUE THREAD

**Issue by MaFuyan** [zhayujie/chatgpt-on-wechat#2315]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

部署Moonshot api 对话可复现
Json配置如下：
{
  "channel_type": "wx",
  "bot_type": "moonshot",
  "moonshot_api_key":"key",
  "moonshot_base_url": "https://api.moonshot.cn/v1/chat/completions",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": [
    ""
  ],
  "single_chat_reply_prefix": "",
  "group_chat_prefix": [
    "@bot"
  ],
  "group_name_white_list": [
    ""
  ],
  "image_create_prefix": [
    ""
  ],
  "speech_recognition": false,
  "group_speech_recognition": false,
  "voice_reply_voice": false,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "character_desc": "你一个机器人，可以根据用户的输入生成回复。",
  "temperature": 0.7,
  "subscribe_msg": "感谢您的关注！\n这里是AI智能助手，可以自由对话。",
  "use_linkai": false,
  "linkai_api_key": "",
  "linkai_app_code": ""
}

### 问题描述 😯

![屏幕截图 2024-09-26 011325](https://github.com/user-attachments/assets/d21d674f-544f-4e1d-bb2c-5fb4c20b3cfa)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by MaFuyan** [comment]
是将 conversation_max_tokens 修改小一点？

**Comment by Saboteur7** [comment]
> 是将 conversation_max_tokens 修改小一点？

对的，因为会携带上下文记忆，有两个参数可以控制

 "conversation_max_tokens": 1000,        # 上下文最大token数
 "expires_in_seconds": 3600,                  # 上下文的过期时间，单位秒

**Comment by xiaofan4122** [comment]
@Saboteur7 我想请教下这个上下文过期时间可以设成无限长吗，我直接删掉这个限制会报错
