### ISSUE TITLE
扫描二维码报错

### ISSUE THREAD

**Issue by jipigeda** [zhayujie/chatgpt-on-wechat#2316]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫描二维码出现截图里的错误 账户已经实名认证

### 问题描述 😯

![screenshot](https://github.com/user-attachments/assets/2d72053f-0213-4280-9adf-a080ed66771f)
扫描二维码出现截图里的错误 账户已经实名认证

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
更换其他账号

**Comment by jipigeda** [comment]
试了两个账号都报错 请问出这个错是什么原因？

**Comment by 6vision** [comment]
> 试了两个账号都报错 请问出这个错是什么原因？

新注册的大部分账号可能无法使用网页版登录功能

**Comment by jipigeda** [comment]
用的两个号都是注册很多年的了 我是在国外登陆的微信 这个会有影响吗

**Comment by 6vision** [comment]
> 用的两个号都是注册很多年的了 我是在国外登陆的微信 这个会有影响吗

正常时显示登录桌面版微信，你这个显示时web端，语言切换为中文试试？
