### ISSUE TITLE
wechat_message.py代码逻辑有问题‘拍一拍’等群聊不触发。‘移除成员’群聊通知消息不识别并卡住。

### ISSUE THREAD

**Issue by xiaohuialg** [zhayujie/chatgpt-on-wechat#2318]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

机器人进群之后，有群员移出了群聊的通知消息，itchat识别不到，并卡住应该是（@itchat.msg_register这个有问题，获取不到移除群聊的消息）。而且新版群聊拍一拍，条件逻辑写的有问题。在这个文件中channel\wechat中wechat_message.py的逻辑问题。

### 问题描述 😯

机器人进群之后，有群员移出了群聊的通知消息，itchat识别不到，并卡住应该是（@itchat.msg_register这个有问题，获取不到移除群聊的消息）。而且新版群聊拍一拍，条件逻辑写的有问题。在这个文件中channel\wechat中wechat_message.py的逻辑问题。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
1、移除群聊指定消息？这边试了，没有卡住呀，有没有日志提供？
2、新版群聊拍一拍具体哪里的逻辑有问题呢？有什么影响？是否有日志提供？

**Comment by xiaohuialg** [comment]
我已经收到，谢谢您！

**Comment by MasterKe2003** [comment]
确实，群聊拍一拍没有反应，单聊可以触发

**Comment by MasterKe2003** [comment]
![image](https://github.com/user-attachments/assets/1da45d48-57d9-4491-bbc1-4e33e8406d12)
![image](https://github.com/user-attachments/assets/b3542f87-aa7a-42fe-b32d-2d5f3f60a9b0)
![image](https://github.com/user-attachments/assets/061f9cb2-faa9-471f-bf85-ac67a90cfbf3)

**Comment by 6vision** [comment]
> 确实，群聊拍一拍没有反应，单聊可以触发

更新最新代码，已修复

**Comment by MasterKe2003** [comment]
点赞👍
