### ISSUE TITLE
使用企业微信时，能否获得发送者的userid呢？

### ISSUE THREAD

**Issue by simpsonyang** [zhayujie/chatgpt-on-wechat#2319]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我想拿到userid后去做鉴权，但我跟踪了chat_chanel.py中的变量cmsg，里面有发送者的名字，但没有userid，请问有没有办法呢？

**Comment by 6vision** [comment]
cmsg里面没有的话，那应该就是没有了
