### ISSUE TITLE
微信群中如果是企业微信客服与bot沟通则没有反应，使用普通微信则有回应

### ISSUE THREAD

**Issue by luojin520520** [zhayujie/chatgpt-on-wechat#2320]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

项目搭在了普通微信上，可以正常使用，一切正常。
但是如果通过我朋友的企业微信，对bot发消息，则没有任何回应。
如果是普通的微信，对bot发消息就没问题。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by xh4160** [comment]
企业微信的协议Token设置了么，我记得需要这个东西的

**Comment by 6vision** [comment]
接入微信，企微号艾特机器人，机器人是收不到消息的，所以没反应，不支持回复企微消息
