### ISSUE TITLE
请问各位大佬，应该怎么样才能把这个项目上传到huggingface上，并且通过它的免费docker容器进行部署呢？谢谢

### ISSUE THREAD

**Issue by keyikai** [zhayujie/chatgpt-on-wechat#2322]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

利用huggingface的免费docker容器部署

### 举例

在huggingface上更方便地快速部署，一键copy运行

### 动机

我有一个n1盒子，但是因为arm64和网络问题无法部署。然后我尝试了railway和koyeb，railway是无法部署，koyeb是扫码报错，所以我想到了huggingface，它的免费额度更高，部署更加便捷，访问别人部署好的空间可以一键copy运行

**Comment by 6vision** [comment]
建议直接搞个服务器吧，那种平台一般不适合，有新增一键部署和管理的脚本：[一键部署](https://github.com/zhayujie/chatgpt-on-wechat/wiki/%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E5%90%AF%E5%8A%A8%E8%84%9A%E6%9C%AC)
