### ISSUE TITLE
cow会支持接入视频生成吗

### ISSUE THREAD

**Issue by kingdocker** [zhayujie/chatgpt-on-wechat#2325]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

智谱清言发布了视频生成的API接口，模型cogvideox。分别支持文生视频、图生视频。想了解下cow会接入嘛？~

### 举例

参考：
https://bigmodel.cn/dev/api/videomodel/cogvideox

### 动机

智谱已经有如上API，以及之前的可灵。
最近字节跳动也发布了视频生成的模型，感觉接入cow会比较惊艳。

**Comment by KimYx0207** [comment]
试试我做的插件：https://github.com/KimYx0207/CogView2Cow

**Comment by kingdocker** [comment]
> 试试我做的插件：https://github.com/KimYx0207/CogView2Cow

大佬，试用了下，很赞~ 已star

**Comment by 6vision** [comment]
这个利用插件的功能写一个插件或者使用别人写好的插件即可~
