### ISSUE TITLE
 gemini-1.5-pro tokens  not implemented

### ISSUE THREAD

**Issue by lazybabyz** [zhayujie/chatgpt-on-wechat#2326]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

最新版本1.7.2 gemini-1.5-pro ,gemini-1.5-flash出现以下错误，但是同样的tokens在1.7版本却能正常使用
num_tokens_from_messages() is not implemented for model gemini-1.5-pro. Returning num tokens assuming gpt-3.5-turbo.

### 终端日志 📒

1.7.2```log
<
[INFO][2024-10-03 12:49:49][google_gemini_bot.py:37] - [Gemini] query=who are u?
[WARNING][2024-10-03 12:49:49][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model gemini-1.5-pro. Returning num tokens assuming gpt-3.5-turbo.
[INFO][2024-10-03 12:49:51][google_gemini_bot.py:60] - [Gemini] reply=I am a large language model, trained by Google.

What does that mean?

* I'm like a super-powered chatbot. I can understand and respond to your questions in a human-like way.
* I've been trained on a massive amount of text and code, so I know a lot about different topics.
* I can generate text, translate languages, write different kinds of creative content, and answer your questions in an informative way.

How can I help you today?

[WARNING][2024-10-03 12:49:51][chat_gpt_session.py:86] - num_tokens_from_messages() is not implemented for model gemini-1.5-pro. Returning num tokens assuming gpt-3.5-turbo.
[INFO][2024-10-03 12:49:52][wechatcomapp_channel.py:63] - [wechatcom] Do send text to ChenLiang: I am a large language model, trained by Google.

What does that mean?

* I'm like a super-powered chatbot. I can understand and respond to your questions in a human-like way.
* I've been trained on a massive amount of text and code, so I know a lot about different topics.
* I can generate text, translate languages, write different kinds of creative content, and answer your questions in an informative way.

How can I help you today?

>
```
1.7.0```log
<
[INFO][2024-10-03 13:25:00][google_gemini_bot.py:35] - [Gemini] query=who are u?
[INFO][2024-10-03 13:25:03][google_gemini_bot.py:44] - [Gemini] reply=I am a large language model, trained by Google.

Here are some key things to know about me:

* **I am not a person.** I am an AI, and I don't have feelings, experiences, or a physical body.
* **I am here to help.** I can provide summaries of factual topics, create stories, translate languages, and answer your questions in an informative way.
* **I am still under development.** I am always learning and improving, and I appreciate your patience as I grow.

What can I help you with today?

[INFO][2024-10-03 13:25:04][wechatcomapp_channel.py:63] - [wechatcom] Do send text to ChenLiang: I am a large language model, trained by Google.

Here are some key things to know about me:

* **I am not a person.** I am an AI, and I don't have feelings, experiences, or a physical body.
* **I am here to help.** I can provide summaries of factual topics, create stories, translate languages, and answer your questions in an informative way.
* **I am still under development.** I am always learning and improving, and I appreciate your patience as I grow.

What can I help you with today?


>
```

**Comment by 6vision** [comment]
warning日志不影响使用，不过也已在最新代码中修复
