### ISSUE TITLE
如何切换openai的api地址,强行切换报错,openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

### ISSUE THREAD

**Issue by TotoQWQ** [zhayujie/chatgpt-on-wechat#2327]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by qyinter** [comment]
API 有问题。不是chatgpt 标准

**Comment by TotoQWQ** [comment]
> API 有问题。不是chatgpt 标准

但是在MaxKB可以识别并使用

**Comment by 6vision** [comment]
三方api是使用参数 "open_ai_api_base": "https://api.openai.com/v1"。你这个问题应该是api服务有问题
