### ISSUE TITLE
我扫码登陆时遇到了错误

### ISSUE THREAD

**Issue by lienting885** [zhayujie/chatgpt-on-wechat#2328]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1.启动容器
2.登录
3.出现错误

### 问题描述 😯

扫码登录后它返回了一条错误信息

### 终端日志 📒

```log
Please press confirm on your phone.
<PIL.PngImagePlugin.PngImageFile image mode=1 size=450x450 at 0x7FA6C38206A0>
[ERROR][2024-10-05 13:42:36][wechat_channel.py:138] - 'wxsid'
Traceback (most recent call last):
  File "/app/channel/wechat/wechat_channel.py", line 124, in startup
    itchat.auto_login(
  File "/app/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/app/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/app/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/app/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```

**Comment by lienting885** [comment]
![image](https://github.com/user-attachments/assets/f62cfdb0-cc40-4f6e-a010-978f779d605f)

**Comment by guang1220** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/issues/2239 这个可以解决

**Comment by 6vision** [comment]
实名认证，绑定银行卡。

**Comment by lienting885** [comment]
好吧......新问题：
`Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}`
他弹出了这条消息后就没法自动恢复了

**Comment by 6vision** [comment]
> 好吧......新问题： `Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}` 他弹出了这条消息后就没法自动恢复了

这是掉线了，需要重新运行项目了
