### ISSUE TITLE
返回消息总带着【ERROR】

### ISSUE THREAD

**Issue by longxingdeng** [zhayujie/chatgpt-on-wechat#2334]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

每次回复消息都会带着【ERROR】

### 问题描述 😯

![image](https://github.com/user-attachments/assets/760d9e1c-cdf1-4567-b38c-70a12b6c2bc8)

### 终端日志 📒

[INFO][2024-10-11 01:08:20][wechat_channel.py:220] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我响度呀，你有咩想问嘅？), receiver=@cf759f9fa56af4e32aff7c2bef573983fa110727cc8fddc956ffdefe66190d7

**Comment by kingdocker** [comment]
你用的应该是chat2api转的api，不是原生api，所以没法计算token消耗。
不过忽略的话，也不影响使用。

**Comment by 6vision** [comment]
使用的api接口的返回信息不完整，不是标准的openai接口，参考[代码](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/bot/chatgpt/chat_gpt_bot.py#L96)
