### ISSUE TITLE
在群聊中如何实现图片理解

### ISSUE THREAD

**Issue by dawn2766** [zhayujie/chatgpt-on-wechat#2335]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

群聊发图片，然后@bot，机器人无法对图片做出响应

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by single228758** [comment]
[参考一下这个插件](https://github.com/fatwang2/sum4all)

**Comment by 6vision** [comment]
如果使用linkai的服务，可以在linkai平台的应用里开启图像识别插件，直接发送图片，然后提问即可触发。参考[LinkAI平台插件](https://www.wangpc.cc/ai/tutorial-wechatbot-with-linkai-cow/)

**Comment by vashtsp** [comment]
> 如果使用linkai的服务，可以在linkai平台的应用里开启图像识别插件，直接发送图片，然后提问即可触发。参考[LinkAI平台插件](https://www.wangpc.cc/ai/tutorial-wechatbot-with-linkai-cow/)

请教如何在不提问的前提下让AI直接触发图片理解？（就是发送图片后AI直接回复图片内容）

**Comment by 6vision** [comment]
> > 如果使用linkai的服务，可以在linkai平台的应用里开启图像识别插件，直接发送图片，然后提问即可触发。参考[LinkAI平台插件](https://www.wangpc.cc/ai/tutorial-wechatbot-with-linkai-cow/)
> 
> 请教如何在不提问的前提下让AI直接触发图片理解？（就是发送图片后AI直接回复图片内容）

在`plugins/linkai/config.json`中， `"summary"`字段里`"type"改为: ["FILE", "SHARING", "IMAGE"]` 试试
