### ISSUE TITLE
无法回复消息

### ISSUE THREAD

**Issue by yantaosun** [zhayujie/chatgpt-on-wechat#2336]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/user-attachments/assets/8efcf9db-fecd-439d-98bb-15aaec5a0b74)

### 问题描述 😯

无法回复消息

### 终端日志 📒

```log
Start auto replying.
[WARNING][2024-10-11 17:04:22][wechat_message.py:109] - [WX]get other_user_id failed: 'UserName'
[WARNING][2024-10-11 17:04:22][chat_channel.py:231] - [chat_channel] unknown context type: ACCEPT_FRIEND

```

**Comment by 6vision** [comment]
参考#2197 排查看看
