### ISSUE TITLE
所有的微信消息都经过了linkai的中转，想做什么啊

### ISSUE THREAD

**Issue by aling1472** [zhayujie/chatgpt-on-wechat#2337]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by 6vision** [comment]
![image](https://github.com/user-attachments/assets/75ef983d-2c91-4045-8374-3402afe3c5ea)
确定有认真看readme？项目默认关闭使用linkai，有需要可以自行开启并配置LinkAI API KEY。

可以把配置以及有问题的服务器log贴出来一起看看
