### ISSUE TITLE
docker配置proxy后回复消息链接不上，使用clash订阅配置代理

### ISSUE THREAD

**Issue by qq910696606** [zhayujie/chatgpt-on-wechat#2338]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1. 使用docker+服务器部署，clash服务器配置rule模式，开启后可以curl访问：

INFO[2024-10-14T10:38:25.186129666+08:00] [TCP] 127.0.0.1:51538 --> openai.com:80 match DomainSuffix(openai.com) using 🚀 节点选择[🇸🇬 [v1] 新加坡・02] 
INFO[2024-10-14T10:38:30.46380724+08:00] [TCP] 127.0.0.1:51544 --> api.openai.com:443 match DomainSuffix(openai.com) using 🚀 节点选择[🇸🇬 [v1] 新加坡・02]

[root@lavm-n220uj3l8e ~]#  curl -L https://api.openai.com
{
    "message": "Welcome to the OpenAI API! Documentation is available at https://platform.openai.com/docs/api-reference"

2. docker-compose.yml配置proxy代理地址：
      OPEN_AI_API_KEY: 'XXXX'
      MODEL: ''
      PROXY: 'http://127.0.0.1:7890'
3. 访问失败
[ERROR]
我连接不到你的网络

### 问题描述 😯

回复消息显示“我连接不到你的网络”
[WARNING][2024-10-14 03:00:58][chat_gpt_bot.py:158] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f539284f730>: Failed to establish a new connection: [Errno 111] Connection refused')))

### 终端日志 📒

```log
[WARNING][2024-10-14 03:00:58][chat_gpt_bot.py:158] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f539284f730>: Failed to establish a new connection: [Errno 111] Connection refused')))
[WARNING][2024-10-14 03:01:03][chat_gpt_bot.py:168] - [CHATGPT] 第1次重试
```

**Comment by 6vision** [comment]
yml文件加个端口映射试试呢，把7890映射到宿主机的7890端口

**Comment by qq910696606** [comment]
@6vision 加了端口映射启动docker 会占用宿主机clash 7890端口
[root@lavm-n220uj3l8e mihomo]# ./clash                      
ERRO[2024-10-14T14:18:46.870130327+08:00] Start HTTP server error: listen tcp :7890: bind: address already in use 
ERRO[2024-10-14T14:18:46.870142027+08:00] Start HTTP server error: listen tcp :7890: bind: address already in use

services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    ports:
      - "7890:7890"
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'XXX'
      MODEL: ''
      PROXY: 'http://127.0.0.1:7890'
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'

**Comment by 6vision** [comment]
那试试直接python部署吧，不用docker了
