### ISSUE TITLE
module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: ‘zipimporter

### ISSUE THREAD

**Issue by liuzixiao666** [zhayujie/chatgpt-on-wechat#2340]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

因为requirements-optional.txt的依赖在python版本3.11之后都被移除了，所以卸载python，安装3.11以下的版本，我这里是3.11.6和3.11.8都可以

**Comment by 6vision** [comment]
装python3.8
