### ISSUE TITLE
输出的日报会自动折叠，需要点击更多展开

### ISSUE THREAD

**Issue by ZackYJz** [zhayujie/chatgpt-on-wechat#2342]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

定时任务输出日报

### 问题描述 😯

![IMG_3430](https://github.com/user-attachments/assets/0c8202ff-4543-44a3-8140-09a8a9b5a422)

有办法不折叠消息吗？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
这是微信app的机制，长消息自动折叠
