### ISSUE TITLE
微信群无法使用。

### ISSUE THREAD

**Issue by iday99** [zhayujie/chatgpt-on-wechat#2349]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

将机器人添加到群里后，@机器人或者用户无回复。  直接发个人是能够正常回复。

### 终端日志 📒

```log
[WARNING][2024-10-23 10:32:04][wechat_message.py:109] - [WX]get other_user_id failed: 'NickName'
[WARNING][2024-10-23 10:39:25][wechat_message.py:36] - 机器人加入群聊消息，不处理~
```

**Comment by iday99** [comment]
37行的 pass 改为：                    return 
 97行使用get方法。
           self.other_user_id = itchat_msg["User"].get("UserName", None)  
            self.other_user_nickname = itchat_msg["User"].get("NickName", "Unknown")  
修改后正常。

**Comment by 6vision** [comment]
项目原本的代码也有键不能存在的处理逻辑，这里更改应该没实际的影响吧，且这部分代码是针对私聊的。
