### ISSUE TITLE
建议新增 claude-3-5-sonnet-20241022 和 chatgpt-4o-latest 大模型

### ISSUE THREAD

**Issue by 1-bytes** [zhayujie/chatgpt-on-wechat#2351]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

chatgpt-4o-latest 大模型是 chatgpt-4o的升级版
claude-3-5-sonnet-20241022 大模型刚出来两天，表现优异，远超 gpt-4o

建议这两个都加上！

**Comment by 6vision** [comment]
可以试试这个pr：#2361

**Comment by 6vision** [comment]
最新更新已支持，参考pr #2361
