### ISSUE TITLE
用linkAI没有问题，调用文心一言的时候报错了

### ISSUE THREAD

**Issue by kinacover** [zhayujie/chatgpt-on-wechat#2357]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

配置了文心一眼的id 和key后运行后登陆微信后，发送消息就报错说权限不足

### 问题描述 😯

在个人微信反馈的了错误，在后台看报错{'error_code': 6, 'error_msg': 'No permission to access data'}

### 终端日志 📒

[INFO][2024-10-25 14:08:55][chat_channel.py:117] - [chat_channel]receive group at
[INFO][2024-10-25 14:08:55][bridge.py:68] - create bot baidu for chat
[INFO][2024-10-25 14:08:55][baidu_wenxin.py:41] - [BAIDU] query=你好
[INFO][2024-10-25 14:08:55][baidu_wenxin.py:79] - [BAIDU] model=eb-instant
[INFO][2024-10-25 14:08:56][baidu_wenxin.py:95] - [BAIDU] response text={'error_code': 6, 'error_msg': 'No permission to access data'}
[WARNING][2024-10-25 14:08:56][baidu_wenxin.py:107] - [BAIDU] Exception: 'result'
[INFO][2024-10-25 14:08:56][wechat_channel.py:220] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
出错了: 'result'), receiver=@@3fd2c49fc98a3c55e6da87c2d60b068811ff6fdfc4691d169cea85f69b6a1790

**Comment by ejohnyu** [comment]
你的百度的KEY有问题吧

**Comment by 6vision** [comment]
看起来参数有误：[BAIDU] response text={'error_code': 6, 'error_msg': 'No permission to access data'}

**Comment by kinacover** [comment]
> 你的百度的KEY有问题吧

正常用python调是没问题的，我也在想是不是百度给的key有问题，百度交ID和KEY

**Comment by kinacover** [comment]
问题解决，文心现在不能直接用模型为“wenxin”进去调取，要改成实际要调取的模型名字才行

**Comment by 6vision** [comment]
> 问题解决，文心现在不能直接用模型为“wenxin”进去调取，要改成实际要调取的模型名字才行

两种情况：
1、"model"可以直接填”wenxin“，代码有做兼容。
2、"baidu_wenxin_model"需要填具体的model名称
![image](https://github.com/user-attachments/assets/6d3efac3-b928-4907-a91d-64e02050607d)
