### ISSUE TITLE
教程文档ISSUE

### ISSUE THREAD

**Issue by Country-If** [zhayujie/chatgpt-on-wechat#236]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> README.md中，OpenAI账号注册部分，接收虚拟手机号的博客教程不存在了，望更新新的教程

![1676648422175](https://user-images.githubusercontent.com/62837275/219699238-4092b14e-c2df-4570-b328-6e60ed9f81a6.jpg)

![image](https://user-images.githubusercontent.com/62837275/219698666-c919549f-89c0-4648-8022-074fc962f13a.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
已更新
