### ISSUE TITLE
使用linkai，如何配置text-to-image使用豆包文生图插件

### ISSUE THREAD

**Issue by ejohnyu** [zhayujie/chatgpt-on-wechat#2360]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在linkai应用的插件里把dall-e-3删除，但在config.json里的text-to-image里配置还是dall-e-3时，要求文生图后，查看linkai我的帐户时，发现被扣了200积分，使用dall-e-3的模型/插件，但我在我的应用的插件配置里已经把dall的插件删除了，加了豆包文生图的插件。

### 问题描述 😯

我的config.json的配置是：
 "model": "linkai-4o",
 "text_to_image": "dall-e-3",
 "use_linkai": true,
 "linkai_api_key":我的KEY
"linkai_app_code":我的code

我猜是因为text-to-image里我配的是dall-e-3，但我查了不知道要linkai用我在我的应用里配置的豆包文生图的插件模型名是什么，如果要让我的应用里的豆包文生图插件生效，text-to-image配置什么。
我试过填写Stable-Diffusion，出错

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
你应该是以画开头来画图的，对吧，实际上是这样的：
项目配置文件有个参数 "image_create_prefix": ["画" ],  如果提问时以画开头，就会先走项目自带的画图逻辑，也即是使用text-to-image，
解决：可以把这个参数里留空： "image_create_prefix": [""],或者直接删除，然后在linkai应用里开启豆包画图插件即可调用

**Comment by ejohnyu** [comment]
> 你应该是以画开头来画图的，对吧，实际上是这样的： 项目配置文件有个参数 "image_create_prefix": ["画" ], 如果提问时以画开头，就会先走项目自带的画图逻辑，也即是使用text-to-image， 解决：可以把这个参数里留空： "image_create_prefix": [""],或者直接删除，然后在linkai应用里开启豆包画图插件即可调用

把image_create_prefix留空或者删除，测试可以了，非常感谢
