### ISSUE TITLE
能否支持不同的群组/消息来源，分别使用不同的模型？

### ISSUE THREAD

**Issue by LNN-code** [zhayujie/chatgpt-on-wechat#2362]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

能否支持不同的群组/消息来源，分别使用不同的模型？
比如： 
在私聊的情况下，用户A对机器人发消息，使用GPT3.5的模型/百度的模型。用户B对机器人发消息，使用GPT4.0的模型/讯飞的模型。
在群聊的情况下，群聊A对机器人发消息，使用GPT3.5的模型/百度的模型。群聊B对机器人发消息，使用GPT4.0的模型/讯飞的模型。

**Comment by 6vision** [comment]
用户维度设置模型不太现实，目前可以通过linkai的服务，不同群组使用不同的模型：给不同的群绑定不同的app_code，在应用里设置默认模型即可，详细参考：[issue 2179](https://github.com/zhayujie/chatgpt-on-wechat/issues/2179)
