### ISSUE TITLE
AI语音识别无法在wx群聊使用

### ISSUE THREAD

**Issue by TotoQWQ** [zhayujie/chatgpt-on-wechat#2367]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在已经信任的微信群中发送语音,AI不予理会

### 问题描述 😯

在已经信任的微信群中发送语音,AI不予理会

### 终端日志 📒

[INFO][2024-11-02 00:26:39][baidu_voice.py:67] - 百度语音识别到了：['测试语音。']
[INFO][2024-11-02 00:26:39][chat_channel.py:134] - [chat_channel]receive group voice, but checkprefix didn't match

**Comment by 6vision** [comment]
参考项目[机器人助手的回复](https://link-ai.tech/app/Kv2fXJcH)![image](https://github.com/user-attachments/assets/b32e7a2e-6d7d-4791-94ce-823c46beddd6)
