### ISSUE TITLE
能否在两个群直接相互转发消息？

### ISSUE THREAD

**Issue by zhaolu1206** [zhayujie/chatgpt-on-wechat#2368]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

因为我们群人比较多，有分成了两个群但基本上有些消息是需要两边都参与的，所以如何bot能够把两边群的消息互相转发就好了。

**Comment by 6vision** [comment]
项目本身不支持，特殊需求，可以考虑在项目基础上二开

**Comment by ayasa520** [comment]
这个可以写插件
