### ISSUE TITLE
GPT-4o 是否可以返回联网搜索结果。

### ISSUE THREAD

**Issue by rogerc66** [zhayujie/chatgpt-on-wechat#2372]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

之前必须要用插件来实现联网结果的搜索，现在 GPT-4o 官网已经可以支持返回实时搜索的结果，是否可以支持这个最新的功能，目前选择 gpt-4o 的 model 好像不能实现联网功能。

**Comment by 6vision** [comment]
通过gpt-4o的api 调用本身不支持联网搜索，你说的应该是chatgpt网站对话时候支持网络搜索，这两个不一样
