### ISSUE TITLE
支持 dify吗？

### ISSUE THREAD

**Issue by peterwillcn** [zhayujie/chatgpt-on-wechat#2391]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

支持 dify吗？

### 举例

支持 dify吗？

### 动机

支持 dify吗？

**Comment by l137295** [comment]
我也想问似乎接入失败···

**Comment by peterwillcn** [comment]
这个 支持 https://github.com/hanfangyuan4396/dify-on-wechat

**Comment by l137295** [comment]
> 这个 支持 https://github.com/hanfangyuan4396/dify-on-wechat

是的，谢谢你，刚才看到，不过进行频繁封号
