### ISSUE TITLE
项目文档以及README不够清晰

### ISSUE THREAD

**Issue by Brave963** [zhayujie/chatgpt-on-wechat#2396]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

使小白能更容易上手使用，减少折腾搜索调试的时间

### 举例

1.api_key_base的使用在文档中未有说明，config-template的配置也没用提及，导致我想使用第三方提供的api服务，想填入相应的代理网址的时候，要去搜索半天才找到相应的方案。
2.linux的一键安装脚本也需要根据requirement的配置以及选择配置去安装依赖，而文档里没有提及这一点，导致我出现一大堆依赖没有，需要自己安装，有的例如openai的库安装了还报错说没有openai.error，我甚至手搓了个error.py最后还是不行 说attribute not found "RateLimit" 太出生了 搞了一下午 最后在FAQ发现一键安装脚本也要去安装pip requirement.txt才解决依赖的问题 你可以说我傻 但是这些东西也不是谁第一次就一定能弄明白的，希望后人能吸取我的经验，希望作者能添加到文档里提醒后人

### 动机

在部署的时候会遇到许多的问题，因为文档以及README都没有提及相关的内容，导致小白或者大部分没有经验的人都需要花费不少时间去调试搜索，总而言之是很折腾的。希望提出此issue作者可以接纳意见，优化文档。（我写这份也不容易，折腾了一下午，实在气不过，想提意见帮助后来人）

**Comment by 6vision** [comment]
![image](https://github.com/user-attachments/assets/d2f10c7b-9d46-432e-a3fb-839e726d64da)
1、项目所有配置都在config.py文件找到，有问题多看readme。另外：也考虑你的建议，把`"open_ai_api_base"`参数现在已加入到readme说明；
2、没搞清楚说的是什么，用一键安装脚本安装的是openai==0.27.8，不存在报openai.error的问题；用脚本一键安装，不配置或者少许配置直接就可以扫码登录。一键安装脚本是提供了一个微信登录最小可用环境，安装了`requirement.txt`中的依赖，进一步接入其他通道，需要看项目其他文档，都有说明。
3、注意文明发言讨论
