### ISSUE TITLE
reloadp 工作不正常问题排查

### ISSUE THREAD

**Issue by ayasa520** [zhayujie/chatgpt-on-wechat#2406]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

启动后修改注册名称为全小写的插件配置, 然后使用管理员命令 `#reloadp 插件名`, 插件配置不会重新加载

### 问题描述 😯

reloadp 首先调用 `reload_plugin`, 然后调用 `activate_plugins` 重新生成插件实例, 每个插件的 `__init__` 中会调用 plugin.py 的 `load_config`, 问题就出在这里:

```python
# plugin.py
class Plugin:
    def __init__(self):
        self.handlers = {}

    def load_config(self) -> dict:
        """
        加载当前插件配置
        :return: 插件配置字典
        """
        # 优先获取 plugins/config.json 中的全局配置
        plugin_conf = pconf(self.name)
        if not plugin_conf:
            # 全局配置不存在，则获取插件目录下的配置
            plugin_config_path = os.path.join(self.path, "config.json")
            logger.debug(f"loading plugin config, plugin_config_path={plugin_config_path}, exist={os.path.exists(plugin_config_path)}")
            if os.path.exists(plugin_config_path):
                with open(plugin_config_path, "r", encoding="utf-8") as f:
                    plugin_conf = json.load(f)

                # 写入全局配置内存
                plugin_config[self.name] = plugin_conf
        logger.debug(f"loading plugin config, plugin_name={self.name}, conf={plugin_conf}")
        return plugin_conf
# config.py
def pconf(plugin_name: str) -> dict:
    """
    根据插件名称获取配置
    :param plugin_name: 插件名称
    :return: 该插件的配置项
    """
    return plugin_config.get(plugin_name.lower())
```
注意到 `load_config` 会通过 `pconf` 检查 `plugin_config` 是否有当前插件的配置项, 而 `pconf` 将插件名转为小写在 `plugin_config` 查找. 如果没有找到的话, 会直接执行 `plugin_config[self.name] = plugin_conf` 将配置写入, 此时却 **没有处理大小写的问题**.

这就导致如果插件注册名称恰好有大写字母时 reloadp 才可以凑巧工作, 因为 plugin_config 存的 key 含有大写字母, 而查找时全部用小写字母, `load_config` 方法认为 `plugin_conf` 中没有该插件的配置项, 此时才会重载配置.

要修复这个问题只要避免外部直接访问 `plugin_config` , 并且在 `reload_plugin` 中删除该插件的配置项即可, 我可以做一个 PR, 但是我看到许多地方都引用了 `plugin_config`, 我不太清楚是否会有副作用

### 终端日志 📒

无需日志

**Comment by Saboteur7** [comment]
Merged, thanks!
