### ISSUE TITLE
可否在启动的时候选择直接生成二维码或给出二维码URL的选择，或者传参设定？

### ISSUE THREAD

**Issue by Jas0n0ss** [zhayujie/chatgpt-on-wechat#241]
### 建议

> 简要说明、截图、复现步骤等，也可以是需求或想法
>> 能否在运行的时候输入变量，让用户运行的时候自行选择登录方式
 - 生成二维码登陆 
 - 显示二维码url（方便我将输出导入到nginx 默认page，在网页实现登陆）
 
### 需求
我想将输出导入到nginx 默认page index.html，在网页实现登陆,然而重定向以后，web显示的二维码就乱了，不能登陆了
乱的二维码登陆如下图：
![image](https://user-images.githubusercontent.com/88020021/219945371-b2c3cb16-74fa-4349-90cf-ecd0acbead7e.png)

如果展示了生成二维码的`URL`,就好了应该直接访问url获取完整的二维码就可以登陆，网页可以作为查看聊天内容渠道。python玩的不6，不知道在怎么在基础代码上如何改的显示二维码 `url`

**Comment by lanvent** [comment]
目前已提供URL。
