### ISSUE TITLE
handler 对 插件实例的引用导致 scanp 命令引起内存泄漏

### ISSUE THREAD

**Issue by ayasa520** [zhayujie/chatgpt-on-wechat#2412]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

开启管理员插件以及任意其他插件, 执行 `#scanp`  命令

### 问题描述 😯

期待行为是原本插件的实例被 gc 回收, 但是由于插件中 handler 对插件 self 的引用, 导致之前的插件实例永远不会被销毁.
执行 `gc.get_referrers(self.instances[name])` 结果如下图
![image](https://github.com/user-attachments/assets/4f835cf8-6ff6-46b6-b4c1-5c70c88e4583)

解决方法有两种:
1. 在`self.instances[name] = instance`之前清空 `self.instances[name].handlers`, 以消除对插件实例的引用.
![image](https://github.com/user-attachments/assets/dd2f1912-f634-4e7c-b71d-836cf0be1fe1)

2. 使用 weakref
在插件中添加handler时
```python
self.handlers[event.on_handle_context] = weakref.weakmethod(self.on_handle_context)
```
在 emit_event 中
```python
    def emit_event(self, e_context: EventContext, *args, **kwargs):
                    ...
                    handler = instance.handlers[e_context.event]()
                    if handler:
                        handler(e_context, *args, **kwargs)
```

显然方法 1  改动更少, 方法 2 需要更改现存的所有插件. 我会就方法 1 提一个 PR

### 终端日志 📒

无需日志

**Comment by Saboteur7** [comment]
Thanks for the PR, it has been merged.

**Comment by spacex-3** [comment]
> Thanks for the PR, it has been merged.

大佬，同理在Event.ON_RECEIVE_MESSAGE也存在这种情况，只要每scanp一次，这个就会重复出现多一次，可否也帮忙调整下？具体怎么解决我就真的小白搞不懂了不好意思

`[DEBUG][2024-12-19 09:46:05][plugin_manager.py:194] - Plugin DOUYINPLUGIN triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-12-19 09:46:05][plugin_manager.py:194] - Plugin DOUYINPLUGIN triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-12-19 09:46:05][plugin_manager.py:194] - Plugin DOUYINPLUGIN triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-12-19 09:46:05][plugin_manager.py:194] - Plugin DOUYINPLUGIN triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-12-19 09:46:05][plugin_manager.py:194] - Plugin DOUYINPLUGIN triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-12-19 09:46:05][plugin_manager.py:194] - Plugin DOUYINPLUGIN triggered by event Event.ON_RECEIVE_MESSAGE`
