### ISSUE TITLE
TOOL插件启用失败

### ISSUE THREAD

**Issue by 0xDkd** [zhayujie/chatgpt-on-wechat#2414]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

tool插件一直显示未启用，在godcmd输入#enablep tool ，启用该插件 

### 问题描述 😯

微信无回复，后续发内容也不再回复

### 终端日志 📒

```log
[DEBUG][2024-12-03 16:11:59][plugin.py:21] - loading plugin config, plugin_config_path=./plugins/tool/config.json, exist=False
[DEBUG][2024-12-03 16:11:59][plugin.py:28] - loading plugin config, plugin_name=tool, conf=None
Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
[WARNING][2024-12-03 16:12:04][tool.py:27] - [tool] init failed, ignore 
[WARNING][2024-12-03 16:12:04][plugin_manager.py:150] - Failed to init TOOL, diabled. config.json not found
[DEBUG][2024-12-03 16:12:04][role.py:62] - [Role] no role found for tag comments 
[INFO][2024-12-03 16:12:04][role.py:69] - [Role] inited
[INFO][2024-12-03 16:12:04][dungeon.py:56] - [Dungeon] inited
[DEBUG][2024-12-03 16:12:04][plugin.py:21] - loading plugin config, plugin_config_path=./plugins/hello/config.json, exist=False
[DEBUG][2024-12-03 16:12:04][plugin.py:28] - loading plugin config, plugin_name=Hello, conf=None
[DEBUG][2024-12-03 16:12:04][hello.py:119] - No Hello plugin config.json, use plugins/hello/config.json.template
[INFO][2024-12-03 16:12:04][hello.py:38] - [Hello] inited
[INFO][2024-12-03 16:12:04][finish.py:23] - [Finish] inited
[DEBUG][2024-12-03 16:12:04][godcmd.py:421] - [Godcmd] admin command: enablep by @7975d55a2c91911ed76899dc78dad6174e9a28dd6f7539a5872791819bbdb806
[DEBUG][2024-12-03 16:12:04][plugin_manager.py:194] - Plugin GODCMD breaked event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-12-03 16:12:04][chat_channel.py:172] - [chat_channel] ready to decorate reply: Reply(type=ERROR, content=插件开启失败)
[DEBUG][2024-12-03 16:12:04][chat_channel.py:284] - [chat_channel] ready to send reply: Reply(type=ERROR, content=[ERROR]
插件开启失败), context: Context(type=TEXT, content=#enablep  tool, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7f6827b3d0>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@7975d55a2c91911ed76899dc78dad6174e9a28dd6f7539a5872791819bbdb806', 'receiver': '@7975d55a2c91911ed76899dc78dad6174e9a28dd6f7539a5872791819bbdb806'})
[INFO][2024-12-03 16:12:04][wechat_channel.py:222] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件开启失败), receiver=@7975d55a2c91911ed76899dc78dad6174e9a28dd6f7539a5872791819bbdb806
```

**Comment by JLWY2233** [comment]
同样问题，求解

**Comment by JLWY2233** [comment]
如图，疑似无法识别指令
![mmexport1733316827027](https://github.com/user-attachments/assets/da02aa1d-387f-44d1-a9fd-06bce922d74e)

**Comment by 6vision** [comment]
> 如图，疑似无法识别指令 ![mmexport1733316827027](https://private-user-images.githubusercontent.com/146161031/392386391-da02aa1d-387f-44d1-a9fd-06bce922d74e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjQ2ODgsIm5iZiI6MTczMzM2NDM4OCwicGF0aCI6Ii8xNDYxNjEwMzEvMzkyMzg2MzkxLWRhMDJhYTFkLTM4N2YtNDRkMS1hOWZkLTA2YmNlOTIyZDc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwMjA2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWIyODg2MDJjMGY1Y2EyODIxZWY3YTk5YTFiM2Q2ZmNmZjBhMDVlZmUwYmYwMjhhYjgxMTI2ZTEyOTkxZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yJ7Uk51gcfXlyCkizKwNuqtuLywd8LOW6CBwlb5Ru3o)

你这个应该是插件配置出现问题了，最简单的方法，重新部署即可，不修改插件配置，直接用这个插件即可

**Comment by 6vision** [comment]
> 后续，根据报错提示手动复制一个config.json，成功开启，但是微信端再发消息没有任何回复，debug页面也看不到任何日志输出

重新运行项目，另外tool插件作者也很久没维护了，
