### ISSUE TITLE
为什么无法在群聊中触发Apilot插件？@机器人发送早报，只会正常回复，私聊却没有问题。

### ISSUE THREAD

**Issue by iceiccy** [zhayujie/chatgpt-on-wechat#2416]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![1](https://github.com/user-attachments/assets/4ee74b56-a65b-47c9-a43b-345434de708a)
![2](https://github.com/user-attachments/assets/e18bb307-2d53-4419-ad95-a92bb7db234f)

### 问题描述 😯

1：在Cow中安装Apilot插件后，私聊发送早报是没问题的，但是在群里@机器人发送早报后，无法触发，只能正常回复，请问是哪里没设置或者修改么？？
2：机器人运行的时候，间隔久了后，如果直接发送早报两个字，先是没有反应，代码也没反应，但是发送对话是没问题的，之后会突然把之前的早报全部发送出来。

### 终端日志 📒

[INFO][2024-12-07 01:30:38][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: @小柠檬丶 早报
[INFO][2024-12-07 01:30:38][chat_gpt_bot.py:57] - [CHATGPT] query=丶 早报
[INFO][2024-12-07 01:30:43][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=@锦城丶y（新微信）
当然可以！以下是今日早报的一些要点总结：

1. 国际新闻：
   - 各国领导人正在参加重要的国际会议，讨论全球经济和环境问题。
   - 某个地区的地缘政治局势紧张，国际社会呼吁和平对话。

2. 国内新闻：
   - 政府宣布了一项新的经济刺激计划，旨在促进中小企业的发展。
   - 某个地方的自然灾害导致了人员伤亡和财产损失，救援工作正在进行中。

3. 科技新闻：
   - 一家科技公司发布了创新的新产品，吸引了全球消费者的关注。
   - 科学家们在某个研究领域取得了重大突破，可能会影响未来的技术应用。

4. 财经新闻：
   - 全球股市波动，投资者对未来经济走势仍然持观望态度。
   - 某些大公司的财报超出预期，股价应声上涨。

5. 文化与娱乐：
   - 一部备受期待的电影即将上映，影迷们期待已久。
   - 某个音乐巡演开票，引发了粉丝的抢购热潮。

如果你对某一方面特别感兴趣，或者需要更详细的信息，请告诉我！), receiver=@@ff135b0f2c863400cc7d39aa68418e8528776d17ae90e20c6166591dd36bbb3b
[INFO][2024-12-07 01:32:22][wechat_channel.py:235] - [WX] download image success, size=767368, img_url=https://file.alapi.cn/60s/202412061733420049.png
[INFO][2024-12-07 01:32:23][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412061733420049.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 01:33:47][chat_channel.py:117] - [chat_channel]receive group at
[INFO][2024-12-07 01:33:47][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: @小柠檬丶 早报
[INFO][2024-12-07 01:33:47][chat_gpt_bot.py:57] - [CHATGPT] query=丶 早报
[INFO][2024-12-07 01:33:52][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=@锦城丶y（新微信）
当然！以下是一些假设性的早报内容：

1. 国际新闻：
   - 某国与邻国达成和平协议，结束了多年的冲突。
   - 全球气候峰会召开，各国领导人承诺加强减排措施。

2. 国内新闻：
   - 政府推出新政策，旨在支持可再生能源的发展。
   - 某城市启动大规模基建项目，预计将创造数万个就业机会。

3. 科技新闻：
   - 一家知名科技公司发布最新款智能手机，加入了多项创新功能。
   - 科学家在医疗研究上取得突破，发现某种疾病的潜在治疗方法。

4. 财经新闻：
   - 股市持续上涨，投资者对经济复苏持乐观态度。
   - 某大型企业宣布收购计划，预计将扩大其市场份额。

5. 文化与娱乐：
   - 知名乐队宣布全球巡演计划，粉丝们期待不已。
   - 某著名导演的新电影获得多项国际大奖提名。

如果你有特定的兴趣或需要更详细的信息，请告诉我！), receiver=@@ff135b0f2c863400cc7d39aa68418e8528776d17ae90e20c6166591dd36bbb3b
[INFO][2024-12-07 01:46:32][app.py:19] - signal 2 received, exiting...
[INFO][2024-12-07 01:46:32][config.py:234] - [Config] User datas saved.
[INFO][2024-12-07 01:46:32][app.py:19] - signal 2 received, exiting...
[INFO][2024-12-07 01:46:32][config.py:234] - [Config] User datas saved.
[INFO][2024-12-07 01:46:34][config.py:299] - [INIT] load config: {'channel_type': 'wx', 'model': 'gpt-4o-2024-08-06', 'open_ai_api_key': 'sk-*****d05', 'open_ai_api_base': 'https://api.rcouyi.com/v1', 'claude_api_key': 'YOU*****KEY', 'text_to_image': 'dall-e-3', 'voice_to_text': 'openai', 'text_to_voice': 'openai', 'proxy': '', 'hot_reload': True, 'single_chat_prefix': [''], 'single_chat_reply_prefix': '[小柠檬] ', 'group_chat_prefix': ['@小柠檬'], 'group_name_white_list': ['墨团（谁来安慰太湖）', '信息价格记录本'], 'image_create_prefix': ['画'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '*****', 'linkai_app_code': ''}
[INFO][2024-12-07 01:46:34][config.py:223] - [Config] User datas loaded.
[INFO][2024-12-07 01:46:34][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-12-07 01:46:34][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin MemberMonitor_v1.0 registered, path=./plugins/MemberMonitor
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Apilot_v0.2 registered, path=./plugins/Apilot
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin tool_v0.5 registered, path=./plugins/tool
[INFO][2024-12-07 01:46:34][plugin_manager.py:41] - Plugin SimpleTimeTask_v1.0 registered, path=./plugins/SimpleTimeTask
[INFO][2024-12-07 01:46:34][godcmd.py:210] - [Godcmd] inited
[INFO][2024-12-07 01:46:34][Apilot.py:35] - [Apilot] inited and alapi_token loaded successfully
[INFO][2024-12-07 01:46:34][SimpleTimeTask.py:105] - [SimpleTimeTask] Loaded tasks from database: []
[INFO][2024-12-07 01:46:34][SimpleTimeTask.py:51] - [SimpleTimeTask] initialized
[INFO][2024-12-07 01:46:34][MemberMonitor.py:37] - [MemberMonitor] 插件已初始化
[INFO][2024-12-07 01:46:34][dungeon.py:56] - [Dungeon] inited
[INFO][2024-12-07 01:46:34][hello.py:38] - [Hello] inited
[INFO][2024-12-07 01:46:34][finish.py:23] - [Finish] inited
[INFO][2024-12-07 01:46:35][wechat_channel.py:134] - Wechat login success, user_id: @2f1d568306435287871c7be7232b76c2f01dbe0311cb2c18a8abb33553796291, nickname: 小柠檬丶
[INFO][2024-12-07 01:46:48][wechat_channel.py:235] - [WX] download image success, size=767368, img_url=https://file.alapi.cn/60s/202412061733420049.png
[INFO][2024-12-07 01:46:49][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412061733420049.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 01:46:55][chat_channel.py:117] - [chat_channel]receive group at
[INFO][2024-12-07 01:46:55][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: @小柠檬丶 早报
[INFO][2024-12-07 01:46:55][bridge.py:68] - create bot chatGPT for chat
[INFO][2024-12-07 01:46:55][chat_gpt_bot.py:57] - [CHATGPT] query=丶 早报
[INFO][2024-12-07 01:46:58][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=@锦城丶y（新微信）
你好！你想了解什么方面的早报呢？是新闻、财经、科技还是其他领域的资讯？请告诉我你的具体需求，我可以为你提供相关的信息和总结。), receiver=@@ff135b0f2c863400cc7d39aa68418e8528776d17ae90e20c6166591dd36bbb3b
[INFO][2024-12-07 01:48:53][wechat_channel.py:235] - [WX] download image success, size=767368, img_url=https://file.alapi.cn/60s/202412061733420049.png
[INFO][2024-12-07 01:48:55][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412061733420049.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 11:19:06][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: ？？？
[INFO][2024-12-07 11:19:06][chat_gpt_bot.py:57] - [CHATGPT] query=？？？
[INFO][2024-12-07 11:19:09][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=[小柠檬] 你好！有什么我可以帮助你的吗？如果有任何问题或需要的信息，请随时告诉我。), receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 11:19:25][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: .....
[INFO][2024-12-07 11:19:25][chat_gpt_bot.py:57] - [CHATGPT] query=.....
[INFO][2024-12-07 11:19:27][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=[小柠檬] 如果你有任何问题或需要帮助，请随时告诉我。我在这里为你提供支持！), receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 11:19:29][wechat_channel.py:235] - [WX] download image success, size=1053711, img_url=https://file.alapi.cn/60s/202412071733508003.png
[INFO][2024-12-07 11:19:31][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412071733508003.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 11:19:38][chat_channel.py:117] - [chat_channel]receive group at
[INFO][2024-12-07 11:19:38][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: @小柠檬丶 早报
[INFO][2024-12-07 11:19:38][chat_gpt_bot.py:57] - [CHATGPT] query=丶 早报
[INFO][2024-12-07 11:19:41][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=@锦城丶y（新微信）
你是在寻找今天的新闻早报吗？虽然我不能提供实时信息，但我可以告诉你一些截至2023年10月的重要新闻话题。如果你有具体的兴趣领域或主题，请告诉我，我会尽量提供相关的信息。), receiver=@@ff135b0f2c863400cc7d39aa68418e8528776d17ae90e20c6166591dd36bbb3b
[INFO][2024-12-07 11:19:46][chat_channel.py:117] - [chat_channel]receive group at
[INFO][2024-12-07 11:19:46][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: @小柠檬丶 ？？？
[INFO][2024-12-07 11:19:46][chat_gpt_bot.py:57] - [CHATGPT] query=丶 ？？？
[INFO][2024-12-07 11:19:47][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=@锦城丶y（新微信）
如果你有任何具体问题或需要帮助的地方，请告诉我。我在这里随时为你提供支持和解答。), receiver=@@ff135b0f2c863400cc7d39aa68418e8528776d17ae90e20c6166591dd36bbb3b
[INFO][2024-12-07 11:19:51][chat_channel.py:117] - [chat_channel]receive group at
[INFO][2024-12-07 11:19:51][SimpleTimeTask.py:572] - [SimpleTimeTask] Command received: @小柠檬丶 早报
[INFO][2024-12-07 11:19:51][chat_gpt_bot.py:57] - [CHATGPT] query=丶 早报
[INFO][2024-12-07 11:19:54][wechat_channel.py:218] - [WX] sendMsg=Reply(type=TEXT, content=@锦城丶y（新微信）
好的，以下是一些截至2023年10月的重要新闻话题摘要：

1. 国际局势：
   - 地缘政治紧张局势依然存在，特别是在一些热点地区，国际社会密切关注。
   - 各国在气候变化问题上的合作与分歧仍然是全球关注的焦点。

2. 科技与创新：
   - 人工智能技术继续快速发展，在各个行业的应用日益广泛。
   - 电动车与可再生能源技术的进步推动了全球能源结构的转型。

3. 经济动态：
   - 各大经济体在应对通货膨胀和经济增长放缓的挑战。
   - 数字经济和绿色经济成为新的增长点。

4. 社会与文化：
   - 全球范围内对多样性与包容性的讨论持续进行。
   - 文化产业在数字化背景下不断创新。

如果你对某个特定领域或事件感兴趣，请告诉我，我可以提供更详细的信息。), receiver=@@ff135b0f2c863400cc7d39aa68418e8528776d17ae90e20c6166591dd36bbb3b
[INFO][2024-12-07 11:20:29][wechat_channel.py:235] - [WX] download image success, size=1053711, img_url=https://file.alapi.cn/60s/202412071733508003.png
[INFO][2024-12-07 11:20:31][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412071733508003.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 11:21:06][wechat_channel.py:235] - [WX] download image success, size=1053711, img_url=https://file.alapi.cn/60s/202412071733508003.png
[INFO][2024-12-07 11:21:08][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412071733508003.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5
[INFO][2024-12-07 11:21:18][wechat_channel.py:235] - [WX] download image success, size=1053711, img_url=https://file.alapi.cn/60s/202412071733508003.png
[INFO][2024-12-07 11:21:20][wechat_channel.py:244] - [WX] sendImage url=https://file.alapi.cn/60s/202412071733508003.png, receiver=@0fd0ccf532704b7610de663784992a3d816e568371cce0192f534c40e05dcad5

**Comment by 6vision** [comment]
![image](https://github.com/user-attachments/assets/e9dd0d99-a4a2-4a62-bd11-bbee4a766482)
你的问题前面问什么都自动加了顿号 、？

**Comment by iceiccy** [comment]
> ![image](https://private-user-images.githubusercontent.com/38057450/393585733-e9dd0d99-a4a2-4a62-bd11-bbee4a766482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjAzNDIsIm5iZiI6MTczMzY2MDA0MiwicGF0aCI6Ii8zODA1NzQ1MC8zOTM1ODU3MzMtZTlkZDBkOTktYTRhMi00YTYyLWJkMTEtYmJlZTRhNzY2NDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDEyMTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZGNjY2IzZjYzM2JmYjdiNzQ1ZWUzNWJjMjMxMWMzMWU2YTg2YTMzMzFmMzlkMTVhNjVkMzNlMTc0N2ZjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.atalaig_LDiRobbOwNj2dJyWnBdpwdsCQUnkSLzxEu4) 你的问题前面问什么都自动加了顿号 、？

啊...确实是这个问题，当我把机器人的微信名从小柠檬丶改为小柠檬之后，确实可以正常返回早报图片了，代码中也从丶早报变成了早报，我又详细检查了一下配置文件，是我把group_chat prefix设置为了@小柠檬，而微信名多了个丶，所以@的时候就变样了，感谢感谢，辛苦了
