### ISSUE TITLE
发送消息过于频繁，可稍后再试。

### ISSUE THREAD

**Issue by LeiWangJava** [zhayujie/chatgpt-on-wechat#2417]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

机器人发送没有几条消息，会提示：发送消息过于频繁，可稍后再试。，消息一直发不出去，给所有用户都一样

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
使用的中转的三方api key吧，这是他们的限制。可以试试linkai的服务，参考：[linkai微信接入](https://www.wangpc.cc/ai/tutorial-wechatbot-with-linkai-cow/)
