### ISSUE TITLE
在群聊不艾特机器人使用插件

### ISSUE THREAD

**Issue by xiaojie1421852616** [zhayujie/chatgpt-on-wechat#2418]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我写了一个自定义api的功能 不把"single_chat_prefix": [""],设置为空的话 在群聊里面 直接发送命令 签到或者其它是没有反应的 必须要@机器人 命令 才会触发，只要把"single_chat_prefix": [""],设置为空 可以直接发送发送 签到 也可以触发了 但是 发送其它消息 会提交给ai，于是我数据全给我插件处理不做回复 这样我插件可以用了 但是群聊里面@机器人没反应 有什么办法鱼和熊掌都兼得

### 举例

![image](https://github.com/user-attachments/assets/1e26814f-ee98-49e6-b0ac-51247c560f91)
![image](https://github.com/user-attachments/assets/5ad7e01e-01bb-4e39-bb0a-b44f3f7b9875)
![image](https://github.com/user-attachments/assets/47c68b7a-b01a-4132-96be-c9126284a88a)

![image](https://github.com/user-attachments/assets/de393600-e108-49a3-86c0-5ca9bf1966cc)

### 动机

用户的id每次登录都会变

**Comment by mela93** [comment]
参考config.py里的触发配置呢
```
    # Bot触发配置
    "single_chat_prefix": ["bot", "@bot"],  # 私聊时文本需要包含该前缀才能触发机器人回复
    "single_chat_reply_prefix": "[bot] ",  # 私聊时自动回复的前缀，用于区分真人
    "single_chat_reply_suffix": "",  # 私聊时自动回复的后缀，\n 可以换行
    "group_chat_prefix": ["@bot"],  # 群聊时包含该前缀则会触发机器人回复
    "no_need_at": False,  # 群聊回复时是否不需要艾特
    "group_chat_reply_prefix": "",  # 群聊时自动回复的前缀
    "group_chat_reply_suffix": "",  # 群聊时自动回复的后缀，\n 可以换行
    "group_chat_keyword": [],  # 群聊时包含该关键词则会触发机器人回复
    "group_at_off": False,  # 是否关闭群聊时@bot的触发
    "group_name_white_list": ["ChatGPT测试群", "ChatGPT测试群2"],  # 开启自动回复的群名称列表
    "group_name_keyword_white_list": [],  # 开启自动回复的群名称关键词列表
    "group_chat_in_one_session": ["ChatGPT测试群"],  # 支持会话上下文共享的群名称
    "nick_name_black_list": [],  # 用户昵称黑名单
    "group_welcome_msg": "",  # 配置新人进群固定欢迎语，不配置则使用随机风格欢迎
    "trigger_by_self": False,  # 是否允许机器人触发
```

**Comment by xiaojie1421852616** [comment]
投个h5管理：https://wwee.lanzouu.com/ikuvG2i0cu5i




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月13日(星期五) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 在群聊不艾特机器人使用插件 (Issue #2418)





 
参考config.py里的触发配置呢
     # Bot触发配置     "single_chat_prefix": ["bot", ***@***.***"],  # 私聊时文本需要包含该前缀才能触发机器人回复     "single_chat_reply_prefix": "[bot] ",  # 私聊时自动回复的前缀，用于区分真人     "single_chat_reply_suffix": "",  # 私聊时自动回复的后缀，\n 可以换行     "group_chat_prefix": ***@***.***"],  # 群聊时包含该前缀则会触发机器人回复     "no_need_at": False,  # 群聊回复时是否不需要艾特     "group_chat_reply_prefix": "",  # 群聊时自动回复的前缀     "group_chat_reply_suffix": "",  # 群聊时自动回复的后缀，\n 可以换行     "group_chat_keyword": [],  # 群聊时包含该关键词则会触发机器人回复     "group_at_off": False,  # ***@***.***的触发     "group_name_white_list": ["ChatGPT测试群", "ChatGPT测试群2"],  # 开启自动回复的群名称列表     "group_name_keyword_white_list": [],  # 开启自动回复的群名称关键词列表     "group_chat_in_one_session": ["ChatGPT测试群"],  # 支持会话上下文共享的群名称     "nick_name_black_list": [],  # 用户昵称黑名单     "group_welcome_msg": "",  # 配置新人进群固定欢迎语，不配置则使用随机风格欢迎     "trigger_by_self": False,  # 是否允许机器人触发

**Comment by kokojacket** [comment]
<img width="530" alt="1734107663985" src="https://github.com/user-attachments/assets/4ece44d3-eb4a-4727-8e79-3a60fb4497a8" />
是这样吧

**Comment by woshidama323** [comment]
@kokojacket 这个如何实现的？

**Comment by kokojacket** [comment]
> @kokojacket 这个如何实现的？

def on_receive_message(self, e_context: EventContext):
        """处理接收到的消息"""
        context = e_context['context']
        if context.type != ContextType.TEXT:
            return
            
我用的这个，直接获取消息记录。
