### ISSUE TITLE
智普只能用GLM_4，其他的配置了不生效？

### ISSUE THREAD

**Issue by Y000J** [zhayujie/chatgpt-on-wechat#2421]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

{
  "channel_type": "wx",
  "zhipu_ai_api_key": "",
  "zhipu_ai_api_base": "https://open.bigmodel.cn/api/paas/v4/chat/completions",
  "model": "glm-4-flash",
  "text_to_image": "cogview-3",
  "voice_to_text": "openai",
  "text_to_voice": "openai",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": [""],
  "group_chat_keyword": [
    "XY",
    "@XY",
    "xy",
    "@xy"
  ],
  "single_chat_reply_prefix": "",
  "group_chat_prefix": [
    "XY",
    "@XY",
    "xy",
    "@xy"
  ],
  "group_name_white_list": [
    "ALL_GROUP",
    "1"
  ],
  "image_create_prefix": [
    "画"
  ],
  "group_welcome_msg": "欢迎进群！美食红黑榜地址：https://kdocs.cn/l/cnYnX7as6lvn", 
  "speech_recognition": true,
  "group_speech_recognition": false,
  "group_at_off": false,
  "voice_reply_voice": false,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "character_desc": "你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。你是内置在微信的机器人，请遵守相关法律法规",
  "temperature": 0.7,
  "subscribe_msg": "感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。",
  "use_linkai": false,
  "linkai_api_key": "",
    "use_global_plugin_config": false,
    "max_media_send_count": 3, 
    "media_send_interval": 3
}

### 问题描述 😯

智普只能用GLM_4，其他的配置了不生效？

### 终端日志 📒

nohup: ignoring input and appending output to 'nohup.out'
[INFO][2024-12-10 22:50:10][config.py:299] - [INIT] load config: {'channel_type': 'wx', 'zhipu_ai_api_key': '775*****YW9', 'zhipu_ai_api_base': 'https://open.bigmodel.cn/api/paas/v4/chat/completions', 'moonshot_api_key': '775*****YW9', 'moonshot_base_url': 'https://open.bigmodel.cn/api/paas/v4/chat/completions', 'model': 'glm-4-flash', 'text_to_image': 'cogview-3', 'voice_to_text': 'openai', 'text_to_voice': 'openai', 'proxy': '', 'hot_reload': False, 'single_chat_prefix': [''], 'group_chat_keyword': ['XY', '@XY', 'xy', '@xy'], 'single_chat_reply_prefix': '', 'group_chat_prefix': ['XY', '@XY', 'xy', '@xy'], 'group_name_white_list': ['ALL_GROUP', '1'], 'image_create_prefix': ['画'], 'group_welcome_msg': '欢迎进群！美食红黑榜地址：https://kdocs.cn/l/cnYnX7as6lvn', 'speech_recognition': True, 'group_speech_recognition': False, 'group_at_off': False, 'voice_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。你是内置在微信的机器人，请遵守相关法律法规', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '*****', 'linkai_app_code': ''}
[INFO][2024-12-10 22:50:10][config.py:223] - [Config] User datas loaded.
/usr/local/lib/python3.10/dist-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[INFO][2024-12-10 22:50:10][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-12-10 22:50:10][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2024-12-10 22:50:10][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
chatgpt-tool-hub version: 0.5.0
[INFO][2024-12-10 22:50:11][plugin_manager.py:41] - Plugin tool_v0.5 registered, path=./plugins/tool
[INFO][2024-12-10 22:50:11][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2024-12-10 22:50:11][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为0571。
[INFO][2024-12-10 22:50:11][godcmd.py:210] - [Godcmd] inited
[INFO][2024-12-10 22:50:11][keyword.py:40] - [keyword] {}
[INFO][2024-12-10 22:50:11][keyword.py:42] - [keyword] inited.
[INFO][2024-12-10 22:50:11][linkai.py:35] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-12-10 22:50:11][role.py:69] - [Role] inited
[INFO][2024-12-10 22:50:11][dungeon.py:56] - [Dungeon] inited
[INFO][2024-12-10 22:50:11][hello.py:38] - [Hello] inited
[INFO][2024-12-10 22:50:11][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.
Downloading QR code.
You can also scan QRCode in any website below:
https://api.pwmqr.com/qrcode/create/?url=https://login.weixin.qq.com/l/IfnaKRZy4A==
https://my.tv.sohu.com/user/a/wvideo/getQRCode.do?text=https://login.weixin.qq.com/l/IfnaKRZy4A==
https://api.qrserver.com/v1/create-qr-code/?size=400×400&data=https://login.weixin.qq.com/l/IfnaKRZy4A==
https://api.isoyu.com/qr/?m=1&e=L&p=20&url=https://login.weixin.qq.com/l/IfnaKRZy4A==
█▀▀▀▀▀▀▀██▀█▀█▀█████▀██▀▀▀▀▀▀▀█
█ █▀▀▀█ █▄█▀▀▀█▀ ▀▄█▄ █ █▀▀▀█ █
█ █   █ █▀▄█▀█▀▄▄▄▀▀ ▄█ █   █ █
█ ▀▀▀▀▀ █▀█▀█ ▄▀▄ █ ▄▀█ ▀▀▀▀▀ █
█▀█▀█▀█▀██▀▄█   ▀▀ █▀ ███▀██▀██
█ █▄▄▀ ▀▀██ ▄▄▄▄▄▄ ▀█▀ ▄▀▀▄▀▀ █
█▀▄ ▄█▀▀▀██ ▀ ▄█▄▀ ▄▀ ▄ ▄▄▀█ ▀█
██▀▄ ▄▀▀▀▀██▀ ▄▀█ ▀██▄ ▄▀█ █▀ █
██▄▀▀▀█▀▀▀ ██   ▀  ▄ ▀  ██ █ ▀█
█▀▄ ▄ ▀▀ ▀▄ █ █▄█ ███ ▀ ▀█▄▄▀ █
█▀▄▀  █▀▄█ ▀ ▀  █    ▀▀ ▀ ▄█▄██
█▀▀▀▀▀▀▀█▄ █  █▄█▄▀█▀ █▀█ ▀▄  █
█ █▀▀▀█ █▀█ ▀▀▄  ▀ ▄█ ▀▀▀ ▄█▄▄█
█ █   █ █▀ ▀ ██▀▄▄██████  ▀▄▄ █
█ ▀▀▀▀▀ █▀▀▀ ▄▀ ▀  ▀  ▀▀ ███ ▀█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

**Comment by mela93** [comment]
是智普的baseurl 错了吗？

**Comment by 6vision** [comment]
改`model`参数即可，支持的模型参考：[智谱模型](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/common/const.py#L65)
