### ISSUE TITLE
为什么先说内容后@，不会触发机器人。例如：```你好@Bot ```就不触发

### ISSUE THREAD

**Issue by Xmei1002** [zhayujie/chatgpt-on-wechat#2425]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

你好@Bot 

### 问题描述 😯

你好@Bot 

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by ayasa520** [comment]
```python
# channel/chat_channel.py
def check_prefix(content, prefix_list):
    if not prefix_list:
        return None
    for prefix in prefix_list:
        if content.startswith(prefix):
            return prefix
    return None
```

`@` 是作为字符串处理的, 源代码中写的是 `content.startswith(prefix)`, 所以前面有其他内容的时候就不会触发

**Comment by Xmei1002** [comment]
> ```python
> # channel/chat_channel.py
> def check_prefix(content, prefix_list):
>     if not prefix_list:
>         return None
>     for prefix in prefix_list:
>         if content.startswith(prefix):
>             return prefix
>     return None
> ```
> 
> `@` 是作为字符串处理的, 源代码中写的是 `content.startswith(prefix)`, 所以前面有其他内容的时候就不会触发

谢谢你的回复。我注意到这里的代码了。我之所以有这个疑问是因为，在我配置@Bot触发时，无论@Bot是否在开头，都会触发；但当我换了一个触发前缀后，就只能在开头触发了，一度让我以为是哪里有问题。

**Comment by Xmei1002** [comment]
> ```python
> # channel/chat_channel.py
> def check_prefix(content, prefix_list):
>     if not prefix_list:
>         return None
>     for prefix in prefix_list:
>         if content.startswith(prefix):
>             return prefix
>     return None
> ```
> 
> `@` 是作为字符串处理的, 源代码中写的是 `content.startswith(prefix)`, 所以前面有其他内容的时候就不会触发

谢谢你的回复。我注意到这里的代码了。我之所以有这个疑问是因为，在我配置@Bot触发时，无论@Bot是否在开头，都会触发；但当我换了一个触发前缀后，就只能在开头触发了，一度让我以为是哪里有问题。

**Comment by 6vision** [comment]
![image](https://github.com/user-attachments/assets/2548f5fb-3dda-40f4-ba90-111d80e08daa)
有不同的参数设置:
- `"group_chat_prefix"` 这是设置的前缀触发，那触发词肯定要放到问题的最前面的
-  `"group_chat_keyword"` 这是设置关键词触发，那触发词放到问题的哪个位置都可以

**Comment by 6vision** [comment]
> > ```python
> > # channel/chat_channel.py
> > def check_prefix(content, prefix_list):
> >     if not prefix_list:
> >         return None
> >     for prefix in prefix_list:
> >         if content.startswith(prefix):
> >             return prefix
> >     return None
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `@` 是作为字符串处理的, 源代码中写的是 `content.startswith(prefix)`, 所以前面有其他内容的时候就不会触发
> 
> 谢谢你的回复。我注意到这里的代码了。我之所以有这个疑问是因为，在我配置@bot触发时，无论@bot是否在开头，都会触发；但当我换了一个触发前缀后，就只能在开头触发了，一度让我以为是哪里有问题。

如果你的机器人微信昵称恰好是bot，那@bot放到哪里都无所谓的，默认是开启了群聊艾特触发的。
