### ISSUE TITLE
无法企业微信扫码

### ISSUE THREAD

**Issue by huchao-hu** [zhayujie/chatgpt-on-wechat#2427]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

我在Windows上 使用 python app.py 启动 但是出来的二维码只能微信 不能企业微信

### 问题描述 😯

我在Windows上 使用 python app.py 启动 但是出来的二维码只能微信 不能企业微信

### 终端日志 📒

我在Windows上 使用 python app.py 启动 但是出来的二维码只能微信 不能企业微信

**Comment by mela93** [comment]
企业微信channel不应该用企业微信吗？
```
"channel_type": "",  # 通道类型，支持：{wx,wxy,terminal,wechatmp,wechatmp_service,wechatcom_app,dingtalk}
```

**Comment by 6vision** [comment]
企微个人号接入，开源项目现在已经不支持了
