### ISSUE TITLE
我可以将对话模型改成GPT-3吗？

### ISSUE THREAD

**Issue by jackyzyaq** [zhayujie/chatgpt-on-wechat#25]
现有代码里的对话模型是：text-davinci-003 我可以改成GPT-3吗，如：
#model="text-davinci-003",  # 对话模型的名称
  model="GPT-3",  # 对话模型的名称

**Comment by zhayujie** [comment]
text-davinci-003 就是 GPT-3模型中的一种， 可选参数可以参考文档：
https://beta.openai.com/docs/models/gpt-3

![image](https://user-images.githubusercontent.com/26161723/210705319-5b71edca-ae97-4646-819c-17eb11d3b5b0.png)

**Comment by jackyzyaq** [comment]
好的，谢谢！

现在发现一个问题就是 登录二维码总是失效 - 貌似3秒刷新一次，而手机确认界面 需要5秒；这个你们有碰到吗？有什么设置里可以调整这个失效时间吗？谢谢！

**Comment by jackyzyaq** [comment]
[ERROR][2023-01-05 13:31:23][wechat_channel.py:115] - 'OpenAIBot' object has no attribute 'chatbot'
Traceback (most recent call last):
  File "/opt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 111, in _do_send
    reply_text = super().build_reply_content(query, context).strip()
  File "/opt/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/opt/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/opt/chatgpt-on-wechat/bot/bot_factory.py", line 25, in create_bot
    return OpenAIBot()
  File "/opt/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 13, in __init__
    logger.info("[GPT]convId={}, parentId={}".format(self.chatbot.conversation_id, self.chatbot.parent_id))
AttributeError: 'OpenAIBot' object has no attribute 'chatbot'


这个是不是微信账号被限制了？

**Comment by zhayujie** [comment]
> 好的，谢谢！
> 
> 现在发现一个问题就是 登录二维码总是失效 - 貌似3秒刷新一次，而手机确认界面 需要5秒；这个你们有碰到吗？有什么设置里可以调整这个失效时间吗？谢谢！

这个问题参考这个 issue: https://github.com/zhayujie/chatgpt-on-wechat/issues/8

**Comment by zhayujie** [comment]
> [ERROR][2023-01-05 13:31:23][wechat_channel.py:115] - 'OpenAIBot' object has no attribute 'chatbot' Traceback (most recent call last): File "/opt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 111, in _do_send reply_text = super().build_reply_content(query, context).strip() File "/opt/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content return Bridge().fetch_reply_content(query, context) File "/opt/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content return bot_factory.create_bot("openAI").reply(query, context) File "/opt/chatgpt-on-wechat/bot/bot_factory.py", line 25, in create_bot return OpenAIBot() File "/opt/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 13, in **init** logger.info("[GPT]convId={}, parentId={}".format(self.chatbot.conversation_id, self.chatbot.parent_id)) AttributeError: 'OpenAIBot' object has no attribute 'chatbot'
> 
> 这个是不是微信账号被限制了？

你的项目代码是拉取的最新的吗，按理说不会报这个错出来

**Comment by jackyzyaq** [comment]
> > [ERROR][2023-01-05 13:31:23][wechat_channel.py:115] - 'OpenAIBot' object has no attribute 'chatbot' Traceback (most recent call last): File "/opt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 111, in _do_send reply_text = super().build_reply_content(query, context).strip() File "/opt/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content return Bridge().fetch_reply_content(query, context) File "/opt/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content return bot_factory.create_bot("openAI").reply(query, context) File "/opt/chatgpt-on-wechat/bot/bot_factory.py", line 25, in create_bot return OpenAIBot() File "/opt/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 13, in **init** logger.info("[GPT]convId={}, parentId={}".format(self.chatbot.conversation_id, self.chatbot.parent_id)) AttributeError: 'OpenAIBot' object has no attribute 'chatbot'
> > 这个是不是微信账号被限制了？
> 
> 你的项目代码是拉取的最新的吗，按理说不会报这个错出来

我编辑了一下 图片的大小和回复字数的限制 - 可能是编辑过程中改了 代码的字符集，回退后可以执行了

谢谢！

**Comment by zhayujie** [comment]
> 

 好的，修改这两处应该不会有问题，如果还是报错可以 git diff 一下，把变更的地方贴出来看看
 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/26161723/210797771-235c3eb8-0a96-41a9-9344-b5589bfdbbfd.png">

**Comment by zhayujie** [comment]
> 我用最新的代码部署在服务器上也是这样 要扫多次才能登陆

参考这个 issue: https://github.com/zhayujie/chatgpt-on-wechat/issues/8
