### ISSUE TITLE
我不知道是不是只有我有这个关于日期的问题。

### ISSUE THREAD

**Issue by QQ169876** [zhayujie/chatgpt-on-wechat#257]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

在openai上的问：日期，回复的是当天正常的日期，但在微信上回复的是 2020年。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
Start auto replying.
[INFO][2023-02-21 23:54:25][open_ai_bot.py:20] - [OPEN_AI] query=今天的日期
[INFO][2023-02-21 23:54:27][open_ai_bot.py:51] - [OPEN_AI] reply=今天是2020年12月3日，星期四。
[INFO][2023-02-21 23:54:27][wechat_channel.py:103] - [WX] sendMsg=今天是2020年12月3日，星期四。, receiver=@f5865487cf52e51f08f0e2e109a63cb5
[INFO][2023-02-21 23:54:33][open_ai_bot.py:20] - [OPEN_AI] query=今天几号？
[INFO][2023-02-21 23:54:35][open_ai_bot.py:51] - [OPEN_AI] reply=今天是2020年12月3日，星期四。
[INFO][2023-02-21 23:54:35][wechat_channel.py:103] - [WX] sendMsg=今天是2020年12月3日，星期四。, receiver=@f5865487cf52e51f08f0e2e109a63cb5

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
 
- python3 -V
Python 3.9.16
wjw@wjwlinux02:~$ pip3 -V
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)
wjw@wjwlinux02:~$

**Comment by hanjianlin** [comment]
我也是，后来用了 官方自己的 chatgpt 也是一样

**Comment by AndySkywalker** [comment]
因为目前能用openai的API调用的ChatGPT不是最新版本。它的版本是text-davinci-003。最新版本的API目前openai还没有放出来。
