### ISSUE TITLE
貌似不能生成一张图片，是代码问题？

### ISSUE THREAD

**Issue by dissminghwm** [zhayujie/chatgpt-on-wechat#259]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
[](![](https://doc.oneboy.cc/server/index.php?s=/api/attachment/visitFile&sign=181d670a352789a9836285e8acca25cf))

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by dissminghwm** [comment]
![Uploading a.png…]()

**Comment by dissminghwm** [comment]
![a](https://user-images.githubusercontent.com/104350115/220522654-3609eb7f-1c51-423d-9a02-254f09a1a832.png)

**Comment by zhayujie** [comment]
要和配置中的 img_prefix 参数匹配， 你可以直接说 "bot 画一只狗"

**Comment by dissminghwm** [comment]
> 要和配置中的 img_prefix 参数匹配， 你可以直接说 "bot 画一只狗"

![aa](https://user-images.githubusercontent.com/104350115/220533470-b81bcd0b-309c-47e2-b8f8-64aef272c87a.png)
![aaa](https://user-images.githubusercontent.com/104350115/220533556-47a31c15-07f9-4ca0-9419-5adc4dacf84f.png)
这是没有触发到吗还是，都是默认的配置

**Comment by renny-ren** [comment]
配置里的 prefix 是“画”啊，你实际的 prefix 是 \n

**Comment by dissminghwm** [comment]
> 配置里的 prefix 是“画”啊，你实际的 prefix 是 \n
噢谢谢你啊，是你说的问题，解决了，但是它似乎只给出连接，在WeChat上并不能直接生成一张图片
