### ISSUE TITLE
无法用prompt的tag生成图片，openai报错

### ISSUE THREAD

**Issue by weishijie-detail** [zhayujie/chatgpt-on-wechat#262]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本是3.9，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
无法用prompt的英文tag生成图片，openai报错
![image](https://user-images.githubusercontent.com/89627521/220580914-675e5428-9f30-47ac-9892-a66808e4a81e.png)

### 终端日志 (如有报错)
![image](https://user-images.githubusercontent.com/89627521/220580958-75495640-a465-4bb3-bfa6-53b9b76ab558.png)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Windows)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by weishijie-detail** [comment]
prompt的tag生成方式已经让bot学习过了

**Comment by zhayujie** [comment]
看报错显示应该是 有敏感词汇，被openai过滤了？
