### ISSUE TITLE
stream模式如何使用，b/s架构

### ISSUE THREAD

**Issue by vector4wang** [zhayujie/chatgpt-on-wechat#264]
如题，官方提供了stream参数，但是我用http也是一股脑返回一坨，该用什么技术实现前后端+openapi实时返回呢？JAVA

**Comment by zwssunny** [comment]
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpHeaders;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.ByteBuffer;
import java.util.concurrent.CompletableFuture;

public class OpenAIStreamExample {
    public static void main(String[] args) throws IOException, InterruptedException {
        // 设置OpenAI API 访问密钥
        String apiKey = "YOUR_API_KEY";

        // 构建请求URL和参数
        String url = "https://api.openai.com/v1/completions";
        String prompt = "Once upon a time";
        String model = "text-davinci-002";
        double temperature = 0.5;
        int maxTokens = 10;

        // 构建请求体
        String requestBody = String.format("{\"prompt\":\"%s\",\"model\":\"%s\",\"temperature\":%f,\"max_tokens\":%d,\"stream\":true}", prompt, model, temperature, maxTokens);

        // 构建请求对象
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + apiKey)
                .build();

        // 构建HttpClient对象
        HttpClient httpClient = HttpClient.newHttpClient();

        // 发送请求
        CompletableFuture<HttpResponse<ByteBuffer>> responseFuture = httpClient.sendAsync(request, HttpResponse.BodyHandlers.ofByteBuffer());

        // 处理响应
        responseFuture.thenAccept(response -> {
            // 检查响应状态码
            if (response.statusCode() != 200) {
                System.err.println("Request failed: " + response.statusCode() + " " + response.body());
                return;
            }

            // 从响应头中获取响应流的编码方式
            String encoding = HttpHeaders.fromMap(response.headers().map()).firstValue("Content-Encoding").orElse("identity");

            // 获取响应体的ByteBuffer对象
            ByteBuffer buffer = response.body();

            // 循环从ByteBuffer对象中读取数据并处理
            while (buffer.hasRemaining()) {
                byte[] bytes = new byte[buffer.remaining()];
                buffer.get(bytes);

                // 如果响应流的编码方式为gzip，则需要进行解压缩
                if ("gzip".equalsIgnoreCase(encoding)) {
                    bytes = decompress(bytes);
                }

                // 处理解码后的数据，例如将其打印出来
                System.out.print(new String(bytes));
            }
        });

        // 等待响应完成
        responseFuture.join();
    }

    // 解压缩gzip格式的数据
    private static byte[] decompress(byte[] compressed) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream(); GZIPInputStream gzip = new GZIPInputStream(new ByteArrayInputStream(compressed))) {
            byte[] buffer = new byte[1024];
            int len;
            while ((len = gzip.read(buffer)) > 0) {
                out.write(buffer, 0, len);
            }
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}

**Comment by vector4wang** [comment]
我感觉你们再使用chatgpt。。。
