### ISSUE TITLE
微信扫码登录后报错

### ISSUE THREAD

**Issue by Luuuuuuuuu1** [zhayujie/chatgpt-on-wechat#265]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
`Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-23 01:53:48][app.py:19] - App startup failed!
[ERROR][2023-02-23 01:53:48][app.py:20] - list index out of range
Traceback (most recent call last):
  File "C:\Users\15416\Desktop\chatgpt-on-wechat\app.py", line 17, in <module>
    channel.startup()
  File "C:\Users\15416\Desktop\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "C:\Python311\Lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Python311\Lib\site-packages\itchat\components\login.py", line 60, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\itchat\components\login.py", line 151, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\itchat\components\login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`



### 终端日志 (如有报错)
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

```
[在此处粘贴终端日志]
`Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
``
我比较确定我是有Python3的



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Luuuuuuuuu1** [comment]
我是python3.11.0
还有一个是我目前在美国
请问跟这些有关系吗

**Comment by zhayujie** [comment]
> 我是python3.11.0 还有一个是我目前在美国 请问跟这些有关系吗

python版本太高了，而且运行环境需要在国内哈
