### ISSUE TITLE
群聊包含特殊字符-，无法进行回复

### ISSUE THREAD

**Issue by RossZhang-cpu** [zhayujie/chatgpt-on-wechat#27]
### <u> Describe the Bug </u>
群聊名称设置 "group_name_white_list": ”ChatGPT-交流“ 后无法进行回复，删除字符"-”可以

### <u> Steps to Reproduce </u>
设置包含“-”的群聊进行测试，无法进行回复

**Comment by zhayujie** [comment]
我在 MacOS 上试了下，可以进行回复， 请问你的操作系统是什么，Python版本是多少， group_name_white_list 有配置为列表结构嘛？

```
"group_name_white_list": ["ChatGPT-交流", "ChatGPT测试群2"]
```
![3371672932593_ pic](https://user-images.githubusercontent.com/26161723/210818564-40783033-196a-4c28-8ab9-1ed01a77302d.jpg)

**Comment by RossZhang-cpu** [comment]
Thanks for your replay. 我重新测试现在正常了，thanks again
