### ISSUE TITLE
is:issue is:open 大佬您好，请问可以更改对话模型吗？想改成收费最低的那一档或者改成完全免费的那个模型，请问怎么操作呢？

### ISSUE THREAD

**Issue by yxj1010** [zhayujie/chatgpt-on-wechat#275]
is:issue is:open 大佬您好，请问可以更改对话模型吗？想改成收费最低的那一档或者改成完全免费的那个模型，请问怎么操作呢？

**Comment by zhayujie** [comment]
在 bot/openai/open_ai_bot.py 中修改传参即可额
<img width="885" alt="image" src="https://user-images.githubusercontent.com/26161723/221230754-c308df5e-68fb-4805-996b-892c935064a0.png">

**Comment by yxj1010** [comment]
大佬您好，我尝试了更改此处的参数，但是改成其他模型之后ai回复就开始智障了，明显无法理解我的意思了，我尝试了其他几种模型，都是要么是回答乱码，要么是回答重复的话，要么不回答（后台显示no model），只有“text-davinci-003”这个模型是可用的，请问这是怎么回事呢？求解答，谢谢大佬！
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月25日 0:18
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [zhayujie/chatgpt-on-wechat] is:issue is:open 大佬您好，请问可以更改对话模型吗？想改成收费最低的那一档或者改成完全免费的那个模型，请问怎么操作呢？ (Issue #275)


在 bot/openai/open_ai_bot.py 中修改传参即可额
[image]<https://user-images.githubusercontent.com/26161723/221230754-c308df5e-68fb-4805-996b-892c935064a0.png>

―

**Comment by zhayujie** [comment]
如果是No model就说明 openai接口不支持这个模型，   其他模型可能不支持多轮会话， 而现在的问答是基于会话设计的，所以可能出现混乱

**Comment by yxj1010** [comment]
那大佬能不能给我提供一些其他对话模型的正确名字呢，不知道是不是因为我模型的名字没输入正确导致模型无法识别，谢谢啦！

**Comment by zhayujie** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/26161723/221350356-7ad07448-2a93-4810-8def-ac353c844550.png">

**Comment by yxj1010** [comment]
谢谢您，那么现在看来只有“text-davinci-003”这个模型是可用的，其他几个我都试过了，无法正常使用，不知道其他人的情况是不是和我一样……

**Comment by leonxiaopeng** [comment]
> 

好像这个模型有点呆,有点小爱同学的感觉
