### ISSUE TITLE
问一下最新版的解决方案，封号严重吗

### ISSUE THREAD

**Issue by knigth95** [zhayujie/chatgpt-on-wechat#279]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
不会封号，会警告和限制功能

**Comment by knigth95** [comment]
限制功能和警告时会不会强制退出登录（无法用）发自我的平板-------- 原始邮件 --------发件人： zhayujie ***@***.***>日期： 2023年2月25日周六 下午3:38收件人： zhayujie/chatgpt-on-wechat ***@***.***>抄送： knight_zzm ***@***.***>, Author ***@***.***>主    题： Re: [zhayujie/chatgpt-on-wechat] 问一下最新版的解决方案，封号严重吗 (Issue #279)

不会封号，会警告和限制功能

**Comment by knigth95** [comment]
> 不会封号，会警告和限制功能

这个警告和限制会使账号强制退出吗

**Comment by zhayujie** [comment]
> > 不会封号，会警告和限制功能
> 
> 这个警告和限制会使账号强制退出吗

会限制朋友圈和加好友功能，次数多了可能限制登录
