### ISSUE TITLE
安装登录后未自动回复信息

### ISSUE THREAD

**Issue by tofindnorthstar** [zhayujie/chatgpt-on-wechat#282]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

微信登录成功，已检查配置无误，未自动回复消息
bot前缀已添加

### 终端日志 (如有报错)
无报错，

```
[在此处粘贴终端日志]
```
最后一行日志：
Please scan the QR code to log in

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：      Python 3.8.13                
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 19.3.1 from /opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pip (python 3.8)

**Comment by zhayujie** [comment]
说明没有登录成功，要显示 Start auto replying 才能自动回复

如果是二维码一直出现，看下 #8

**Comment by wangwanjie** [comment]
> 说明没有登录成功，要显示 Start auto replying 才能自动回复
> 
> 如果是二维码一直出现，看下 #8

我确定配置无误，也是一直不回复

**Comment by zhayujie** [comment]
@wangwanjie  可以贴一下控制台日志

**Comment by wangwanjie** [comment]
> 可以贴一下控制台日志
 后面可以了，忽略了一点，我开脚本时应该开启梯子，开了就可以了，我感觉脚本可以加个日志输出，比如网络不通啥的

**Comment by RuanXuan** [comment]
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 天青色
[INFO][2023-10-27 14:57:37][wechat_channel.py:126] - Wechat login success, user_id: @8093, nickname: 天青色
Start auto replying.

登录后未自动回复，但是控制台也没什么反应
