### ISSUE TITLE
请教一下，数据模型是新的吗？

### ISSUE THREAD

**Issue by ThowF** [zhayujie/chatgpt-on-wechat#283]
你好！我想接入wechat实现学习上的查询，但是显示的日期是不正确的，这样能够保证数据的时效性，数据是最新的吗？

> 这是接入chatgpt后，openai回复的
![image](https://user-images.githubusercontent.com/82104966/221400872-a2c1a255-b134-41f4-8f47-11df183fd31d.png)

> 但是现在的日期是：
![image](https://user-images.githubusercontent.com/82104966/221400955-0e89f724-1d70-4ffc-ad41-ed95901b2c2e.png)

**Comment by knigth95** [comment]
> 你好！我想接入wechat实现学习上的查询，但是显示的日期是不正确的，这样能够保证数据的时效性，数据是最新的吗？
> 
> > 这是接入chatgpt后，openai回复的
> > ![image](https://user-images.githubusercontent.com/82104966/221400872-a2c1a255-b134-41f4-8f47-11df183fd31d.png)
> 
> > 但是现在的日期是：
> > ![image](https://user-images.githubusercontent.com/82104966/221400955-0e89f724-1d70-4ffc-ad41-ed95901b2c2e.png)

GPT-3.0模型不具备时效性，21年后的信息都是推测，要联网的你得看new bing

**Comment by leonxiaopeng** [comment]
很明显不是,  api调用和网页版的模型相比明显差了很多

**Comment by ThowF** [comment]
好的 非常感谢您的解答
