### ISSUE TITLE
"WECHATY PUPPET SERVICE TOKEN",这个参数怎么获取，readme里没有描述

### ISSUE THREAD

**Issue by liliwen365** [zhayujie/chatgpt-on-wechat#288]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> "wechaty_puppet_service_token": "WECHATY PUPPET SERVICE TOKEN",这个参数怎么获取，readme里没有描述，感谢

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
参考 https://github.com/zhayujie/chatgpt-on-wechat/pull/244
