### ISSUE TITLE
> 对，我修改的是config.json里面的character_desc 内容修改成英文描述了，应该没有操作错误吧？

### ISSUE THREAD

**Issue by ghostvarg** [zhayujie/chatgpt-on-wechat#291]
> 对，我修改的是config.json里面的character_desc 内容修改成英文描述了，应该没有操作错误吧？

你可以在 character_desc 中告诉它用英文回答， 然后你用英文提问题

_Originally posted by @zhayujie in https://github.com/zhayujie/chatgpt-on-wechat/discussions/290#discussioncomment-5152018_
      好用了，谢谢，已经是全英文回复了！

**Comment by zhayujie** [comment]
没问题
