### ISSUE TITLE
ALL_GROUP参数无法正确执行

### ISSUE THREAD

**Issue by Evenji184** [zhayujie/chatgpt-on-wechat#299]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
group_name_white_list的ALL_GROUP无法正确执行

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by sunguanghui** [comment]
用["ALL_GROUP"]，或者"ALL_GROUP"，分别尝试一下。
这个真没办法。有的服务器支持第一个，有的第二个有效。
亲测。

**Comment by Evenji184** [comment]
@zhayujie 
![image](https://user-images.githubusercontent.com/56332856/222374858-11fabc30-797e-47d1-b6f8-d7256136d7e6.png)
这里加个判断应该可以了
