### ISSUE TITLE
"single_chat_prefix": [""]配置无法生效

### ISSUE THREAD

**Issue by Evenji184** [zhayujie/chatgpt-on-wechat#300]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
设置为"single_chat_prefix": [""]后无法生效

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
有效果截图吗

**Comment by Evenji184** [comment]
> 有效果截图吗

现在是指定的配置，回去我看下

**Comment by chinesewebman** [comment]
遇到同样的问题。日志里能看到已有回复内容，但无法发出去，报错信息如下：
[ERROR][2023-03-05 15:51:14][wechat_channel.py:121] - can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "/home/webman/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 119, in _do_send
    self.send(conf().get("single_chat_reply_prefix") + reply_text, reply_user_id)
TypeError: can only concatenate list (not "str") to list

python版本是3.8.8

**Comment by zhayujie** [comment]
> 遇到同样的问题。日志里能看到已有回复内容，但无法发出去，报错信息如下： [ERROR][2023-03-05 15:51:14][wechat_channel.py:121] - can only concatenate list (not "str") to list Traceback (most recent call last): File "/home/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 119, in _do_send self.send(conf().get("single_chat_reply_prefix") + reply_text, reply_user_id) TypeError: can only concatenate list (not "str") to list
> 
> python版本是3.8.8

是 single_chat_prefix 设置成 [""]，  single_chat_reply_prefix 是字符串哦，不能设置成列表

**Comment by chinesewebman** [comment]
是这样么？可是如果把列表符从配置文件的这两个单聊参数设置里去掉之后，虽然不报错，但私聊依然没有响应。

**Comment by zhayujie** [comment]
single_chat_prefix: [""]

**Comment by shxch** [comment]
你好，用railway一键部署，群聊没问题，但是单聊就会报错，试过你给的"single_chat_prefix": [""]，日志里依然报一样的错

[INFO][2023-07-12 18:17:23][chat_gpt_bot.py:49] - [CHATGPT] query=hi
﻿[ERROR][2023-07-12 18:17:26][chat_channel.py:270] - Worker return exception: can only concatenate list (not "str") to list
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
﻿result = self.fn(*self.args, **self.kwargs)
﻿File "/app/channel/chat_channel.py", line 150, in _handle
﻿reply = self._decorate_reply(context, reply)
﻿File "/app/channel/chat_channel.py", line 228, in _decorate_reply
﻿reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
﻿TypeError: can only concatenate list (not "str") to list
