### ISSUE TITLE
哪里能删除账号啊，想切换小号使用显示list index out of range了或者说在哪改列表大小

### ISSUE THREAD

**Issue by 0a1b2c** [zhayujie/chatgpt-on-wechat#301]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
你是说关闭进程吗

ps -ef | grep app.py | grep -v grep 命令可查看运行于后台的进程，如果想要重新启动程序可以先 kill 掉对应的进程。

如果你下载了最新的代码，还可以使用脚本快速关闭服务:

```bash
cd scripts
./shutdown.sh 
./start.sh
```
