### ISSUE TITLE
关于接入语言模型的怀疑

### ISSUE THREAD

**Issue by SaintTom** [zhayujie/chatgpt-on-wechat#302]
### 前置确认

环境均无问题，能正常使用

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
1.版本过久，知识库截至2020年7月6日，官网的试用模型都已经截止到了2021年9月
2.想问下这个接入的模型具体是哪一个，感觉和官网的那个比较差了很多；就比如问一个“帮我写一篇某某主题的专利”，它的回答太过简洁，远远比不上官网上的模型

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
chatgpt api发布了，可以在 #297 中解决
