### ISSUE TITLE
【修改】特殊指令： 用户向机器人发送 #清除记忆 即可清空该用户的上下文记忆。

### ISSUE THREAD

**Issue by zgxtao** [zhayujie/chatgpt-on-wechat#306]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
能否修改清空该用户上下文记忆的 关键词？（目前是 #清除记忆，比如改成 @bot 新的话题）
在哪里修改？
是否可以更新成config.json的配置参数？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zgxtao** [comment]
问题已经得到50%解决。

方法：

1.打开最新的文件，vim /chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py
2在第1行（line 21），将 if query == '#清除记忆': 改为  if query == 'xxx':   xxx是你想改的内容，比如新的话题。

遗留问题：
能否将一些参数的配置，都写到脚本里config.json，直接方便配置，每次重启也好改。

**Comment by zhayujie** [comment]
后面可以做成可选参数
