### ISSUE TITLE
更新后无法访问

### ISSUE THREAD

**Issue by Lijinging** [zhayujie/chatgpt-on-wechat#307]
### 前置确认

1. 新加坡环境
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

今天更新代码后，出现报错

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[ERROR][2023-03-02 18:57:25][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 43, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：CentOS 7
 - Python版本  ( 执行 `python3 -V` )：3.9.16
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：22.0.4

**Comment by JcMm529** [comment]
同样

**Comment by Lijinging** [comment]
看官方文档，是请求格式和返回格式发生变化了
https://platform.openai.com/docs/api-reference/chat

**Comment by unlsycn** [comment]
把`ChatCompletion`改成`Completion`应该就好了

**Comment by unlsycn** [comment]
> > ### 前置确认
> > 
> > 1. 新加坡环境
> > 2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
> > 3. 在已有 issue 中未搜索到类似问题
> > 4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
> > 
> > ### 问题描述
> > 今天更新代码后，出现报错
> > > 简要说明、截图、复现步骤等，也可以是需求或想法
> > 
> > 
> > ### 终端日志 (如有报错)
> > ```
> > [ERROR][2023-03-02 18:57:25][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion'
> > Traceback (most recent call last):
> >   File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 43, in reply_text
> >     response = openai.ChatCompletion.create(
> > AttributeError: module 'openai' has no attribute 'ChatCompletion'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 环境
> > 
> > * 操作系统类型  (Mac/Windows/Linux)：CentOS 7
> > * Python版本  ( 执行 `python3 -V` )：3.9.16
> > * pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：22.0.4
> 
> 更新 openai sdk 版本

是的..很多pip的镜像源还没同步到0.27.0..

**Comment by MooreFoss** [comment]
pip提示我已经是最新版本

**Comment by unlsycn** [comment]
> pip提示我已经是最新版本

是0.27.0吗？我服务器上默认用的阿里源还在0.26.5
你可以试试-i https://pypi.tuna.tsinghua.edu.cn/simple some-package

**Comment by MooreFoss** [comment]
pip3 install --upgrade openai -i https://pypi.python.org/simple/

**Comment by unlsycn** [comment]
> pip3 install --upgrade openai -i https://pypi.python.org/simple/ 我默认是清华源，可以临时使用官方源

清华源已经更新了 你试试清一下cache

**Comment by Lijinging** [comment]
更新后确实可以用了，赞！
不过我从后台检查，发现访问的是gpt-3.5-turbo-0301模型，这个是否符合预期呢？

**Comment by zhayujie** [comment]
> 更新后确实可以用了，赞！ 不过我从后台检查，发现访问的是gpt-3.5-turbo-0301模型，这个是否符合预期呢？

就是这个模型

**Comment by fdc310** [comment]
其他都没问题连接报错，一直找不出原因 # Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (C
aused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B0742F1D90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接
的主机没有反应，连接尝试失败。'))
Traceback (most recent call last):
  File "D:\appfile\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\appfile\anaconda\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\appfile\anaconda\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by fdc310** [comment]
其他都没问题连接报错，一直找不出原因 # Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (C
aused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B0742F1D90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接
的主机没有反应，连接尝试失败。'))
Traceback (most recent call last):
  File "D:\appfile\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\appfile\anaconda\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\appfile\anaconda\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by unlsycn** [comment]
> 

API被墙了，挂个代理就行。

**Comment by fdc310** [comment]
> > 
> 
> API被墙了，挂个代理就行。

挂了v2但是依旧被墙，很迷茫

**Comment by unlsycn** [comment]
> > > 
> > 
> > 
> > API被墙了，挂个代理就行。
> 
> 挂了v2但是依旧被墙，很迷茫

检查一下代理的Log看看实际走的是哪呗
