### ISSUE TITLE
提问太快啦，请休息一下再问我吧

### ISSUE THREAD

**Issue by jianyanqing** [zhayujie/chatgpt-on-wechat#309]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

You exceeded your current quota, please check your plan and billing details.

### 终端日志 (如有报错)

Login successfully as ChatGPT
Start auto replying.
[INFO][2023-03-02 20:28:58][chat_gpt_bot.py:19] - [OPEN_AI] query=你好
[WARNING][2023-03-02 20:29:00][chat_gpt_bot.py:58] - You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-03-02 20:29:05][chat_gpt_bot.py:61] - [OPEN_AI] RateLimit exceed, 第1次重试
[WARNING][2023-03-02 20:29:05][chat_gpt_bot.py:58] - You exceeded your current quota, please check your plan and billing details.
[INFO][2023-03-02 20:29:05][wechat_channel.py:103] - [WX] sendMsg= 提问太快啦，请休息一下再问我吧, receiver=@f89f9ec37dbe017792bdd7d5c2978b3cfe2d99efb5f557d1c103250d4644ce08

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：ubuntu20.04
 - Python版本  ( 执行 `python3 -V` )： python3.8.10                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.0.2

**Comment by zhayujie** [comment]
api 被墙了

**Comment by zhayujie** [comment]
see #310

**Comment by jianyanqing** [comment]
> api 被墙了

我开了代理的，之前一直能用的，api是不是只有18美元的额度可用？好像是这个原因
