### ISSUE TITLE
网络无法连接OpenAI: Failed to establish a new connection

### ISSUE THREAD

**Issue by EnochYe** [zhayujie/chatgpt-on-wechat#310]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
[INFO][2023-03-02 20:14:08][chat_gpt_bot.py:19] - [OPEN_AI] query=介绍下你自己
[ERROR][2023-03-02 20:20:40][chat_gpt_bot.py:67] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc94c9cc4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/root/anaconda3/envs/chat/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/envs/chat/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/envs/chat/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by linjumble** [comment]
好像是api.openai.com被墙了，但是打开代理后，微信又无法登陆，不知道怎么解决了

**Comment by zhayujie** [comment]
> 登陆

我本地开了一个hk的代理，微信可以连诶

**Comment by zhayujie** [comment]
目前国内网络无法访问 api.openai.com， 暂时只能通过开代理解决，寻找其他方案中。

**Comment by aqlkzf** [comment]
请问可以给一些 服务器配置代理的方法推荐吗

**Comment by fu9809** [comment]
> 目前国内网络无法访问 api.openai.com， 暂时只能通过开代理解决，寻找其他方案中。

 请问哪些代理可以呢，我开启了代理还是无法访问

**Comment by zhayujie** [comment]
我是在本地开发机开了一个hk的代理，ok了

**Comment by Smawexi** [comment]
现在可以把之前的openai的那个库版本发一下吗？重新装一下之前的包版本，先暂时用之前的模型

**Comment by Smawexi** [comment]
> 我是在本地开发机开了一个hk的代理，ok了

现在可以把之前的openai的那个库版本发一下吗？重新装一下之前的包版本，先暂时用之前的模型

**Comment by zhayujie** [comment]
> 现在可以把之前的openai的那个库版本发一下吗？重新装一下之前的包版本，先暂时用之前的模型

openai后台的域名直接被墙的，之前的也调不通的

**Comment by EnochYe** [comment]
邮件已收到，祝好！

**Comment by Smawexi** [comment]
> 

噢噢，好的

**Comment by Smawexi** [comment]
> > 现在可以把之前的openai的那个库版本发一下吗？重新装一下之前的包版本，先暂时用之前的模型
> 
> openai后台的域名直接被墙的，之前的也调不通的

噢噢，好的

**Comment by sorrrrrry** [comment]
开了hk代理还是不行呢

**Comment by sorrrrrry** [comment]
开了hk代理没法登录 等登录了再开代理又会报错。。。

**Comment by linjumble** [comment]
> > 现在可以把之前的openai的那个库版本发一下吗？重新装一下之前的包版本，先暂时用之前的模型
> 
> openai后台的域名直接被墙的，之前的也调不通的

最好做个反向代理

**Comment by Sir1usss** [comment]
怎么搞呢，目前返回不了信息。

**Comment by zhayujie** [comment]
暂时通过代理或者外网服务器来解决吧， 其他方案我周末更新下

**Comment by sorrrrrry** [comment]
> 暂时通过代理或者外网服务器来解决吧， 其他方案我周末更新下
> 
> 大家有什么可行的方案也可以发出来讨论下

请问为什么我在启动前开代理 会不出二维码，扫玩码再开代理，过会系统又崩了，用的新加坡代理

**Comment by zhayujie** [comment]
> > 暂时通过代理或者外网服务器来解决吧， 其他方案我周末更新下
> > 大家有什么可行的方案也可以发出来讨论下
> 
> 请问为什么我在启动前开代理 会不出二维码，扫玩码再开代理，过会系统又崩了，用的新加坡代理

有hk的节点吗

**Comment by sorrrrrry** [comment]
> > > 暂时通过代理或者外网服务器来解决吧， 其他方案我周末更新下
> > > 大家有什么可行的方案也可以发出来讨论下
> > 
> > 
> > 请问为什么我在启动前开代理 会不出二维码，扫玩码再开代理，过会系统又崩了，用的新加坡代理
> 
> 有hk的节点吗

试过了，也不行。。。请问你是在运行代码前就开了代理吗

**Comment by xingchenhai-x** [comment]
整个服务器走代理吗，能重写访问类解决吗

**Comment by explorerJi** [comment]
Traceback (most recent call last):
  File "/root/bot-on-anything/model/chatgpt/chatgpt_model.py", line 44, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa38e0d4c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[INFO][2023-03-03 12:50:25][wechat_mp_channel.py:60] - [WX_Public] reply content: 请再问我一次吧

**Comment by zhayujie** [comment]
几种可能的方案：

1.直接用能访问外网的服务器：  比如 阿里云香港服务器            --  已试验

2.开代理：
   - 本地开发环境： 直接开启vpn就行，但要保证运行python程序的 命令行 或 IDE 也能生效          -- 已试验，用的hk节点
   - 服务器环境：  需要服务器运行代理软件          --   待试验
   
3.托管到能访问外网的容器平台           --  比如railway等，  待试验

**Comment by zeschi** [comment]
服务器是日本的，但是还是不行。
![1677820241139](https://user-images.githubusercontent.com/12479798/222636740-50834745-df68-4e99-a32d-950e186cca84.png) ping Google是通的

**Comment by xingchenhai-x** [comment]
python\Lib\site-packages\openai\__init__.py里有一个proxy是库提供的代理位置，使用proxy={'https': 'http://localhost:port'}可以单独走代理

**Comment by zhayujie** [comment]
> python\Lib\site-packages\openai__init__.py里有一个proxy是库提供的代理位置，使用proxy={'https': '[http://localhost:port'}可以单独走代理](http://localhost:port'%7D%E5%8F%AF%E4%BB%A5%E5%8D%95%E7%8B%AC%E8%B5%B0%E4%BB%A3%E7%90%86)

是不是把这个proxy 配置成服务器上部署的代理软件的端口 就可以了？

**Comment by explorerJi** [comment]
（ping api.openai.com）是不是在本地用代理ping通这个openai的调用地址，就意味着服务器上也能调通openai的接口了？

**Comment by xingchenhai-x** [comment]
> 

是的，我就是想问怎么在程序里把这个init改掉

**Comment by zhayujie** [comment]
> 是的，我就是想问怎么在程序里把这个init改掉

不错的方法。   实在改不掉 就不用sdk了，改成自己发送http请求好了

**Comment by Kinsenlin** [comment]
服务器上装个v2raya，配置一下代理就行了，我也遇到这个问题，昨晚解决了

**Comment by zhayujie** [comment]
> 服务器上装个v2raya，配置一下代理就行了，我也遇到这个问题，昨晚解决了

你的代理哪里的节点， 不会影响wechat的回复吗

**Comment by ADARKLIGHT** [comment]
想问下怎么用企业微信扫码登陆呀

**Comment by Akavice** [comment]
可以尝试使用代理，我在本地配了v2ray，然后在chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py第15行配置一下代理就行
openai.proxy = conf().get('#你的代理地址')
另外我试了sock5似乎跑不通，得http代理
以及可以试试升级一下openAI版本，pip install openai --upgrade

**Comment by Kinsenlin** [comment]
> > 服务器上装个v2raya，配置一下代理就行了，我也遇到这个问题，昨晚解决了
> 
> 你的代理哪里的节点， 不会影响wechat的回复吗

不会，设置一下代理模式就好了，使用大陆白名单模式

**Comment by Sir1usss** [comment]
> > > 服务器上装个v2raya，配置一下代理就行了，我也遇到这个问题，昨晚解决了
> > 
> > 
> > 你的代理哪里的节点， 不会影响wechat的回复吗
> 
> 不会，设置一下代理模式就好了，使用大陆白名单模式

想请教一下这个怎么设置啊，搞一上午了。

**Comment by ADARKLIGHT** [comment]
> 

用自己号老是被封怎么搞

**Comment by jiangzhenxiang** [comment]
> 好像是api.openai.com被墙了，但是打开代理后，微信又无法登陆，不知道怎么解决了

api.openai.com是刚被墙的吗，我昨天用还好好的

**Comment by hugegedegege** [comment]
我用的腾讯云，服务器硅谷的，可以

**Comment by Sir1usss** [comment]
> 我用的腾讯云，服务器硅谷的，可以

我也想去买，个人实名过了还不够是么，他说要实名之后才能买海外的云

**Comment by yxn4065** [comment]
> ### 前置确认
> 1. 运行于国内网络环境，未开代理
> 2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
> 3. 在已有 issue 中未搜索到类似问题
> 4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
> 
> ### 问题描述
> > 简要说明、截图、复现步骤等，也可以是需求或想法
> > [INFO][2023-03-02 20:14:08][chat_gpt_bot.py:19] - [OPEN_AI] query=介绍下你自己
> > [ERROR][2023-03-02 20:20:40][chat_gpt_bot.py:67] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc94c9cc4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> > Traceback (most recent call last):
> > File "/root/anaconda3/envs/chat/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
> > conn = connection.create_connection(
> > File "/root/anaconda3/envs/chat/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
> > raise err
> > File "/root/anaconda3/envs/chat/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
> > sock.connect(sa)
> > OSError: [Errno 101] Network is unreachable
> 
> ### 终端日志 (如有报错)
> ```
> [在此处粘贴终端日志]
> ```
> 
> ### 环境
> * 操作系统类型  (Mac/Windows/Linux)：
> * Python版本  ( 执行 `python3 -V` )：
> * pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

国内被墙了,可参考 #321 进行尝试

**Comment by unlsycn** [comment]
> 整个服务器走代理吗，能重写访问类解决吗

可以在代理处分流，openai走代理，微信直连。

**Comment by WenkangHu** [comment]
> '#你的代理地址'

求教程

**Comment by WenkangHu** [comment]
> 可以尝试使用代理，我在本地配了v2ray，然后在chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py第15行配置一下代理就行 openai.proxy = conf().get('#你的代理地址') 以及可以试试升级一下openAI版本，pip install openai --upgrade

求教程

**Comment by 0a1b2c** [comment]
用v2ray能用那我试试clash

**Comment by peterzhen40** [comment]
代理设置白名单还是报错 You can't get access to internet or wechat domain

**Comment by explorerJi** [comment]
> > 可以尝试使用代理，我在本地配了v2ray，然后在chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py第15行配置一下代理就行 openai.proxy = conf().get('#你的代理地址') 以及可以试试升级一下openAI版本，pip install openai --upgrade
> 
> 求教程
![image](https://user-images.githubusercontent.com/126233847/222725060-2ebe197a-c65e-48aa-8d46-84c2d4d11c23.png)
![image](https://user-images.githubusercontent.com/126233847/222725185-1a5dfa9a-a8f6-44df-bced-a6585f7acf58.png)
按照你说的配置了，也开启了v2ray
![image](https://user-images.githubusercontent.com/126233847/222725444-956fd811-9ded-4e68-86ab-d084a8dca398.png)
但还是不行啊，收不到openai的结果呢？

**Comment by explorerJi** [comment]
> > > 可以尝试使用代理，我在本地配了v2ray，然后在chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py第15行配置一下代理就行 openai.proxy = conf().get('#你的代理地址') 以及可以试试升级一下openAI版本，pip install openai --upgrade
> > 
> > 
> > 求教程
> > ![image](https://user-images.githubusercontent.com/126233847/222725060-2ebe197a-c65e-48aa-8d46-84c2d4d11c23.png)
> > ![image](https://user-images.githubusercontent.com/126233847/222725185-1a5dfa9a-a8f6-44df-bced-a6585f7acf58.png)
> > 按照你说的配置了，也开启了v2ray
> > ![image](https://user-images.githubusercontent.com/126233847/222725444-956fd811-9ded-4e68-86ab-d084a8dca398.png)
> > 但还是不行啊，收不到openai的结果呢？

![image](https://user-images.githubusercontent.com/126233847/222726789-b11fb0f7-4c88-4f44-b7b7-84cc51de99ef.png)
![image](https://user-images.githubusercontent.com/126233847/222726904-3cab3657-71ea-47ef-b5e0-616d05dafbba.png)
阿里云服务器，配的v2ray代理并已开启，也配置了代理地址，为啥还是不行？是不是只配置代理地址不够，还需要配置那些uuid和端口参数，类似于这个：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/126233847/222727486-515f6d89-f377-423c-a6a1-6513cb773228.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/126233847/222727557-fbf41b44-508f-455d-b455-dc858625cafb.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/126233847/222727613-45c6a491-846d-4169-9b64-1979152a5738.png">

**Comment by EnochYe** [comment]
自用的已经稳定了，个人使用的方案是国内服务器+代理配置，代理我使用的是clash 一般机场都会提供大陆白名单模式，这样微信的登录也不会被影响。配置clash可以参考这个（https://einverne.github.io/post/2021/03/linux-use-clash.html）

**Comment by explorerJi** [comment]
终于调通了！
![image](https://user-images.githubusercontent.com/126233847/222873880-94cb94f2-374d-4fa9-a61a-cfdce199e40f.png)

**Comment by Segho** [comment]
> url打不开了欸

**Comment by Segho** [comment]
你好，这个url打不开了，我目前开代理之后登录还是遇到问题，以及参考过楼上修改openai init脚本的方式，依然无效。

**Comment by whalefall123456** [comment]
> 终于调通了！ ![image](https://user-images.githubusercontent.com/126233847/222873880-94cb94f2-374d-4fa9-a61a-cfdce199e40f.png)

方便教一下你是怎么做的吗？我用的也是clash，但是一直无法ping通api.openai.com

**Comment by Espererr** [comment]
> > 终于调通了！ ![image](https://user-images.githubusercontent.com/126233847/222873880-94cb94f2-374d-4fa9-a61a-cfdce199e40f.png)
> 
> 方便教一下你是怎么做的吗？我用的也是clash，但是一直无法ping通api.openai.com

怎么api.openai.com网址打开是法轮功页面，麻了

**Comment by zhayujie** [comment]
@E

**Comment by zhayujie** [comment]
@Espererr  应该是你的代理有问题， 域名被劫持了

**Comment by yhaiqiang** [comment]
> 

亲测有效

**Comment by yhaiqiang** [comment]
> python\Lib\site-packages\openai__init__.py里有一个proxy是库提供的代理位置，使用proxy={'https': '[http://localhost:port'}可以单独走代理](http://localhost:port'%7D%E5%8F%AF%E4%BB%A5%E5%8D%95%E7%8B%AC%E8%B5%B0%E4%BB%A3%E7%90%86)

这个方法实测有效
![image](https://user-images.githubusercontent.com/41229517/222884665-860ba1bd-b257-410a-a514-5b7a4ea0a00b.png)

**Comment by Mywbj** [comment]
香港服务器可以访问openai么

**Comment by explorerJi** [comment]
> > > 终于调通了！ ![image](https://user-images.githubusercontent.com/126233847/222873880-94cb94f2-374d-4fa9-a61a-cfdce199e40f.png)
> > 
> > 
> > 方便教一下你是怎么做的吗？我用的也是clash，但是一直无法ping通api.openai.com
> 
> 怎么api.openai.com网址打开是法轮功页面，麻了

踩着大神们的脚步过来的，按照上面大神们的教程一步一步来，ping在代理服务器中不支持转发，用curl指令访问谷歌来测试代理有没有配成功。

**Comment by WenkangHu** [comment]
> > python\Lib\site-packages\openai__init__.py里有一个proxy是库提供的代理位置，使用proxy={'https': '[http://localhost:port'}可以单独走代理](http://localhost:port'%7D%E5%8F%AF%E4%BB%A5%E5%8D%95%E7%8B%AC%E8%B5%B0%E4%BB%A3%E7%90%86)
> 
> 这个方法实测有效 ![image](https://user-images.githubusercontent.com/41229517/222884665-860ba1bd-b257-410a-a514-5b7a4ea0a00b.png)
实测有效+1

**Comment by YoungXu06** [comment]
> 独走代理
你好 这个代理地址怎么才能获取到呢？

**Comment by YoungXu06** [comment]
@WenkangHu 你好，需要自己搭代理吗？

**Comment by Smawexi** [comment]
> python\Lib\site-packages\openai__init__.py里有一个proxy是库提供的代理位置，使用proxy={'https': '[http://localhost:port'}可以单独走代理](http://localhost:port'%7D%E5%8F%AF%E4%BB%A5%E5%8D%95%E7%8B%AC%E8%B5%B0%E4%BB%A3%E7%90%86)

让openai单独走代理是可行的呢
![image](https://user-images.githubusercontent.com/103298985/222893774-95a5a6cd-11c8-4b3f-8275-3b3ef4cb6ef5.png)

**Comment by zhayujie** [comment]
> python\Lib\site-packages\openai__init__.py里有一个proxy是库提供的代理位置，使用proxy={'https': '[http://localhost:port'}可以单独走代理](http://localhost:port'%7D%E5%8F%AF%E4%BB%A5%E5%8D%95%E7%8B%AC%E8%B5%B0%E4%BB%A3%E7%90%86)

在 config.json 中增加了一个 proxy 配置，可以这样添加：

```
{
    "proxy": "http://127.0.0.1:1080"
}

```

**Comment by zhayujie** [comment]
详细步骤：https://github.com/zhayujie/chatgpt-on-wechat/issues/351

**Comment by Chenkx-0907** [comment]
> 服务器上装个v2raya，配置一下代理就行了，我也遇到这个问题，昨晚解决了



> > > 服务器上装个v2raya，配置一下代理就行了，我也遇到这个问题，昨晚解决了
> > 
> > 
> > 你的代理哪里的节点， 不会影响wechat的回复吗
> 
> 不会，设置一下代理模式就好了，使用大陆白名单模式

请教一下，v2rayN怎么搞呢？白名单里加入微信的域名吗

**Comment by explorerJi** [comment]
> > 服务器上安装一个v2raya，配置一下代理就进行了，我也遇到这个问题，昨晚解决了
> 
> > > > 服务器上安装一个v2raya，配置一下代理就进行了，我也遇到这个问题，昨晚解决了
> > > 
> > > 
> > > 你的代理在哪里的节点，不会影响微信的回复吗
> > 
> > 
> > 不会，设置一下代理模式就好了，使用大陆白名单模式
> 
> 请教一下，v2rayN怎么搞呢？白名单里加入微信的域名吗

v2rayn图文详细教程参考：
https://w1.v2free.top/auth/register?code=DD3Q
![image](https://user-images.githubusercontent.com/126233847/224521588-f9f87319-f2a6-4dd2-a6ef-abdd5ff2fc61.png)

**Comment by explorerJi** [comment]
> > 终于调通了！![图像](https://user-images.githubusercontent.com/126233847/222873880-94cb94f2-374d-4fa9-a61a-cfdce199e40f.png)
> 
> 方方便教一下你是怎么做的？我用的也是clash，但是是直接无法ping通api.openai.com

calsh图文详细教程参考：
https://w1.v2free.top/auth/register?code=DD3Q
![image](https://user-images.githubusercontent.com/126233847/224521629-7a820e6b-e767-4bbf-ba90-f61d42b4ca6e.png)

**Comment by bh-ying** [comment]
[WARNING][2023-03-13 22:18:21][chat_gpt_bot.py:87] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found')))
[WARNING][2023-03-13 22:18:21][chat_gpt_bot.py:88] - [OPEN_AI] APIConnection failed

我是租了日本的VPS，但是还会报这个错

**Comment by zhayujie** [comment]
@bh-ying  你是不是在 config.json中配置了proxy，国外服务器不用配置

**Comment by YSN-commits** [comment]
![屏幕截图 2023-03-14 162405](https://user-images.githubusercontent.com/122069194/224940327-d961bd50-8e2c-4105-9016-69685bff8bb6.png)
到这一步了，还是不能ping通

**Comment by EnochYe** [comment]
> 

有没有export到环境变量中？像这样 
```shell
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```

**Comment by YSN-commits** [comment]
> > > 终于调通了！![图像](https://user-images.githubusercontent.com/126233847/222873880-94cb94f2-374d-4fa9-a61a-cfdce199e40f.png)
> > 
> > 
> > 方方便教一下你是怎么做的？我用的也是clash，但是是直接无法ping通api.openai.com
> 
> calsh图文详细教程参考： https://w1.v2free.top/auth/register?code=DD3Q ![image](https://user-images.githubusercontent.com/126233847/224521629-7a820e6b-e767-4bbf-ba90-f61d42b4ca6e.png)
我就按这个配的，还是不行啊

**Comment by YSN-commits** [comment]
> @bh-ying 你是不是在 config.json中配置了proxy，国外服务器不用配置

破案了，没在环境变量里配，在系统设置里填的

**Comment by YSN-commits** [comment]
> > 
> 
> 有没有export到环境变量中？像这样
> 
> ```shell
> export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
> ```

破案了，没在环境变量里配，在系统s里填的

**Comment by huangwenhui123** [comment]
阿里云服务器如何配置clash

**Comment by wjfkook** [comment]
我来推荐一个我目前在用的解决方案：
在外网服务器搭建一个api.openai.com的反向代理，使用这个教程里面的链接去购买外网服务器
[https://www.typemylife.com/how-to-register-openai-chatgpt-get-api-key-create-api-proxy-in-china/](url)
推荐买这个[https://my.racknerd.com/aff.php?aff=7407&pid=358](url)，一年才几十块钱
在VPS上安装Docker服务后，使用[此镜像服务](https://hub.docker.com/r/mirrors2/chatgpt-api-proxy)，一键搭建反向代理

之后修改config.json文件
把
"proxy": "127.0.0.1:7890",
去掉，换成
"open_ai_api_base": "http://xxx.xxx.xxx.xxx:port/v1",         # 其中xxx和port是上面你搭建的反向代理openapi的ip和端口

非常香！

**Comment by mrzhao1277891** [comment]
> 服务器是日本的，但是还是不行。 ![1677820241139](https://user-images.githubusercontent.com/12479798/222636740-50834745-df68-4e99-a32d-950e186cca84.png) ping Google是通的

解决了吗兄弟，我在腾讯云上申请的硅谷服务器，curl openai正常返回，但是从代码接口走显示网络不通

**Comment by lanvent** [comment]
你的是Openai包版本过低

**Comment by juziguai** [comment]
File "D:\Tools\Akai\Python\3.8.10\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

You can't get access to internet or wechat domain, so exit.

开了代理之后，在启动项目就报错了，但是浏览器是可以正常访问login.weixin.qq.com，大佬们这是咋回事啊，拜托给小弟指点下

**Comment by EnochYe** [comment]
邮件已收到，祝好！

**Comment by juziguai** [comment]
> > 好象是api.openai.com被墙了，但是打开代理后，微信又无法登录，不知道怎么解决了
> > 同，解决了么

同，解决了吗

**Comment by lllpxxx** [comment]
core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxs
id"]                                                                             
KeyError: 'wxsid'
这是啥啊
