### ISSUE TITLE
微信扫码登陆时，屡次显示time out

### ISSUE THREAD

**Issue by ShowUNow** [zhayujie/chatgpt-on-wechat#311]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 微信再扫码登陆时，扫完码之后来不及点击登录，很快就提示time out。

这个破微信每次扫完码都需要等5秒才能点击登录，而这时刚好就提示time out....

### 终端日志 (如有报错)

```
Please scan the QR code to log in.
Please press confirm on your phone.
**Log in time out, reloading QR code.**
Getting uuid of QR code.
Downloading QR code.
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows 10
 - Python版本  ( 执行 `python3 -V` )：python 3.9             
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
see #8
