### ISSUE TITLE
执行 python3 app.py后不弹出二维码

### ISSUE THREAD

**Issue by rongmengmeng** [zhayujie/chatgpt-on-wechat#312]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

在项目根目录下执行 python3 app.py后不弹出二维码

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows11
 - Python版本  ( 执行 `python3 -V` )：  3.10.10                    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.01

**Comment by rongmengmeng** [comment]
在pycharm中能够正常生成二维码

**Comment by yuany3906** [comment]
windows的是py app.py吧

**Comment by Smawexi** [comment]
> windows的是py app.py吧



> windows的是py app.py吧

执行python3 app.py 也可以弹出二维码呀，我就是windows系统

**Comment by Smawexi** [comment]
不过我的是Windows10系统

**Comment by rongmengmeng** [comment]
> > windows的是py app.py吧
> 
> 执行python3 app.py 也可以弹出二维码呀，我就是windows系统

我的Windows11 python3 app.py执行后无响应;py app.py生成二维码

**Comment by Smawexi** [comment]
> 

我的Windows10，执行哪个命令都可以，比如python3 app.py或者python app.py或者py app.py都行

**Comment by rongmengmeng** [comment]
> windows的是py app.py吧
