### ISSUE TITLE
关于升级到3.5后，人格描述不受控制的问题

### ISSUE THREAD

**Issue by hecarli555** [zhayujie/chatgpt-on-wechat#316]
升级到3.5后，人格描述不受控制了，我自己编辑的描述，它只抓取了一个名字使用了，其它一个都没说出来，甚至有时候根本就不按照我给它的描述来描述自己。。。。只是因为3.5模型的原因么？能否修复？

**Comment by zhayujie** [comment]
gpt-3.5模型自身有限制， 不管你输入什么它都会记住自己是语言模型，但是你输入的信息它也会接收，问到相关问题时会关联出来

**Comment by hecarli555** [comment]
> gpt-3.5模型自身有限制， 不管你输入什么它都会记住自己是语言模型，但是你输入的信息它也会接收，问到相关问题时会关联出来

哈哈哈哈哈，我感觉到他变聪明同时也感觉到他变危险了。。。。因为不能通过人格描述来做一些敏感词限制。。。他现在可以通过层层渐进式的“审问”出一些不可描述之事。。。。有点后怕哈哈哈哈
