### ISSUE TITLE
无法回复

### ISSUE THREAD

**Issue by Tenkkk** [zhayujie/chatgpt-on-wechat#317]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
3.2号傍晚出现的问题
另外什么时候更新docker镜像，limccn/chatgpt-on-wechat
### 终端日志 (如有报错)

```
![image](https://user-images.githubusercontent.com/50854602/222493329-17369e34-734f-4112-b483-440d0f7846b4.png)
![image](https://user-images.githubusercontent.com/50854602/222493418-e1513bef-4241-4697-afe8-6c42a946b533.png)
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：群晖docker
![image](https://user-images.githubusercontent.com/50854602/222492748-6e02caf1-6987-47f5-a0ec-669e0fb93456.png)

**Comment by Tenkkk** [comment]
![image](https://user-images.githubusercontent.com/50854602/222493964-98af4252-28df-4589-9543-512215af0e26.png)
![image](https://user-images.githubusercontent.com/50854602/222493993-bb32f9e3-9023-436a-a2c0-05f7d1565ed8.png)

**Comment by zhayujie** [comment]
see #310

**Comment by Tenkkk** [comment]
docker容器运行中，打开软路由代理hk，秒解决

> see #310

docker镜像啥时候更新gpt-3.5-turbo，现在的回答感觉有点蠢，login.py里调参也还是
