### ISSUE TITLE
自动回复的调用

### ISSUE THREAD

**Issue by haorenzhou** [zhayujie/chatgpt-on-wechat#32]
您好在显示“Start auto replying”后，如何在微信中调用出Chatgpt的机器人？
在微信里输入“@bot”和“bot”后没有任何反应？

**Comment by zhayujie** [comment]
使用扫码的那个微信账号在手机端向好友输入 @bot 的吗？ 输入后在 "Start auto replying" 之后 有没有其他报错或者日志显示呢

**Comment by haorenzhou** [comment]
ok，看来是要连着@bot后直接输入问题。我这边搞定了，谢谢！
