### ISSUE TITLE
ChatGPT国内被墙问题(已解决)

### ISSUE THREAD

**Issue by yxn4065** [zhayujie/chatgpt-on-wechat#321]
#### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似前置确认
5. 仅仅由于是网络原因造成的(国内被墙)

经过排查发现是国内网络已经无法调用, ~~暂时无解决方案~~ 

### **解决方案**如下: (使用代理)
本人使用 阿里云服务器搭建国外代理环境:

自建教程: [ https://w1.v2free.top/auth/register?code=7np0]( https://w1.v2free.top/auth/register?code=7np0)

参考教程: [https://github.com/bannedbook/fanqiang](https://github.com/bannedbook/fanqiang)

根据自己使用的操作系统选择搭建的流程.我使用的Linux操作系统,亲测有效
[https://github.com/bannedbook/fanqiang/tree/master/linux](https://github.com/bannedbook/fanqiang/tree/master/linux)
环境变量添加如下:
```bash
//编辑配置文件
vim /etc/profile
 
//在该配置文件的最后添加代理配置
export http_proxy='http://ip:port'    //代理服务器ip地址和端口号
export https_proxy='http://ip:port'   //代理服务器ip地址和端口号
 
 
// 退出profile文件并保存
source /etc/profile     // 使配置文件生效
```

![image](https://user-images.githubusercontent.com/76934061/222694873-cd98f67f-1c95-4d7c-8628-6cb426aa6fd6.png)

希望此处理方法能够对大家有帮助.

**Comment by sorrrrrry** [comment]
api被墙了

**Comment by yxn4065** [comment]
> api被墙了

是的,国内api被墙了有没有什么解决方法,(国外服务器除外)

**Comment by sorrrrrry** [comment]
老哥说的用hk代理 我试了还是不行

**Comment by yxn4065** [comment]
香港openai官方本来就不支持,不过应该可以尝试香港的服务器接入vx

**Comment by Cupcc** [comment]
### 正解在这里：
若正确使用代理，第一次能通过，而后续不能使用api_key。可能是频繁更换ip导致的，openai对api_key具有安全检查，会自动更换api_key。 
解决方案：在每次启动前，去生成一个新的api_key填入即可。

**Comment by Cupcc** [comment]
> 拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：
> 
> ![image](https://user-images.githubusercontent.com/8436305/222620924-27f86fc6-ed7e-485d-a3b6-a13d4745dda2.png) 还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, receiver=@b2beb360347cc73355b5478c9b6f4674

### 可能的解决方案
若正确使用代理，第一次能通过，而后续不能使用api_key。可能是频繁更换ip导致的，openai对api_key具有安全检查，会自动更换api_key。 
解决方案：在每次启动前，去生成一个新的api_key填入即可。

**Comment by MinovskyRickland** [comment]
阿里云，腾讯云均已屏蔽api直接接口，需要在服务器端配置代理，比如调用requests 库来发送 HTTP 请求

**Comment by zhayujie** [comment]
网络不通问题在 #310 讨论吧

**Comment by Akavice** [comment]
可以尝试使用代理，我在本地配了v2ray，然后在chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py第15行配置一下代理就行
openai.proxy = conf().get('#你的代理地址')
另外我试了sock5似乎跑不通，得http代理

**Comment by blackhorse1234** [comment]
阿里云，腾讯云购买国外服务器是否可以？

**Comment by zhayujie** [comment]
@baichisong  你这个问题是openai没有更新

**Comment by Sir1usss** [comment]
> #### 前置确认
> 1. 运行于国内网络环境，未开代理
> 2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
> 3. 在已有 issue 中未搜索到类似问题
> 4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似前置确认
> 5. 仅仅由于是网络原因造成的(国内被墙)
> 
> 经过排查发现是国内网络已经无法调用, ~暂时无解决方案~
> 
> ### **解决思路:** 使用国外服务器 或者 使用代理(免费)
> ### **解决方案**如下: (使用代理)
> 本人使用 阿里云服务器搭建国外代理环境:
> 
> 自建教程: [ https://w1.v2free.top/auth/register?code=7np0](https://w1.v2free.top/auth/register?code=7np0)
> 
> 参考教程: https://github.com/bannedbook/fanqiang
> 
> 根据自己使用的操作系统选择搭建的流程.我使用的Linux操作系统,亲测有效 https://github.com/bannedbook/fanqiang/tree/master/linux 环境变量添加如下:
> 
> ```shell
> //编辑配置文件
> vim /etc/profile
>  
> //在该配置文件的最后添加代理配置
> export http_proxy='http://ip:port'    //代理服务器ip地址和端口号
> export https_proxy='http://ip:port'   //代理服务器ip地址和端口号
>  
>  
> // 退出profile文件并保存
> source /etc/profile     // 使配置文件生效
> ```
> 
> ![image](https://user-images.githubusercontent.com/76934061/222694873-cd98f67f-1c95-4d7c-8628-6cb426aa6fd6.png)
> 
> 希望此处理方法能够对大家有帮助.

您好，我按照教程配置到了“下载 clash 配置文件”，接下来是配置
```
//编辑配置文件
vim /etc/profile
 
//在该配置文件的最后添加代理配置
export http_proxy='http://ip:port'    //代理服务器ip地址和端口号
export https_proxy='http://ip:port'   //代理服务器ip地址和端口号
 
 
// 退出profile文件并保存
source /etc/profile     // 使配置文件生效
```
了么，这个代理服务器ip端口是在网上找个免费的测试一下吗？

**Comment by Sir1usss** [comment]
> > api被墙了
> 
> 是的,国内api被墙了有没有什么解决方法,(国外服务器除外)

![1677840968713](https://user-images.githubusercontent.com/16861124/222702873-365fbb56-b5d8-4b10-8f0b-7afd0ddfb528.jpg)
我到这一步了，接下来应该怎么做呢，第一次配代理，不懂~~见谅

**Comment by GriMu** [comment]
> 拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：
> 
> ![image](https://user-images.githubusercontent.com/8436305/222620924-27f86fc6-ed7e-485d-a3b6-a13d4745dda2.png) 还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, receiver=@b2beb360347cc73355b5478c9b6f4674

您好，有解决吗，我也是使用的腾讯云新加坡的服务器，应该不会墙吧，但是扫码后提示 的这个
`Traceback (most recent call last):
  File "app.py", line 21, in <module>
    channel.startup()
  File "/www/wwwroot/ChatGpt/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login
    status = self.check_login()
  File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'`

**Comment by unlsycn** [comment]
> > > api被墙了
> > 
> > 
> > 是的,国内api被墙了有没有什么解决方法,(国外服务器除外)
> 
> ![1677840968713](https://user-images.githubusercontent.com/16861124/222702873-365fbb56-b5d8-4b10-8f0b-7afd0ddfb528.jpg) 我到这一步了，接下来应该怎么做呢，第一次配代理，不懂~~见谅

在Clash配置文件里添加匹配规则 openai.com走代理

**Comment by Sir1usss** [comment]
> > > > api被墙了
> > > 
> > > 
> > > 是的,国内api被墙了有没有什么解决方法,(国外服务器除外)
> > 
> > 
> > ![1677840968713](https://user-images.githubusercontent.com/16861124/222702873-365fbb56-b5d8-4b10-8f0b-7afd0ddfb528.jpg) 我到这一步了，接下来应该怎么做呢，第一次配代理，不懂~~见谅
> 
> 在Clash配置文件里添加匹配规则 openai.com走代理

![image](https://user-images.githubusercontent.com/16861124/222712713-e67c9caa-866a-498c-b72a-ca3474c91ffa.png)
这样配置吗？随便选了个ProxyName，还是Ping不通

**Comment by 199074343** [comment]
我用的就是新加坡的机器，不用再翻墙了吧

**Comment by unlsycn** [comment]
> > > > > api被墙了
> > > > 
> > > > 
> > > > 是的,国内api被墙了有没有什么解决方法,(国外服务器除外)
> > > 
> > > 
> > > ![1677840968713](https://user-images.githubusercontent.com/16861124/222702873-365fbb56-b5d8-4b10-8f0b-7afd0ddfb528.jpg) 我到这一步了，接下来应该怎么做呢，第一次配代理，不懂~~见谅
> > 
> > 
> > 在Clash配置文件里添加匹配规则 openai.com走代理
> 
> ![image](https://user-images.githubusercontent.com/16861124/222712713-e67c9caa-866a-498c-b72a-ca3474c91ffa.png) 这样配置吗？随便选了个ProxyName，还是Ping不通

你这分组明显是直连的吧..

**Comment by Sir1usss** [comment]
> > > > > > api被墙了
> > > > > 
> > > > > 
> > > > > 是的,国内api被墙了有没有什么解决方法,(国外服务器除外)
> > > > 
> > > > 
> > > > ![1677840968713](https://user-images.githubusercontent.com/16861124/222702873-365fbb56-b5d8-4b10-8f0b-7afd0ddfb528.jpg) 我到这一步了，接下来应该怎么做呢，第一次配代理，不懂~~见谅
> > > 
> > > 
> > > 在Clash配置文件里添加匹配规则 openai.com走代理
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16861124/222712713-e67c9caa-866a-498c-b72a-ca3474c91ffa.png) 这样配置吗？随便选了个ProxyName，还是Ping不通
> 
> 你这分组明显是直连的吧..

我把config里面的所有自己添加的rules删掉了，然后把etc/profile下面的http_proxy和https_proxy都设置为127.0.0.1:7890跑openai 的 demo还是Cannot connect to proxy, 是什么问题呢？

**Comment by baichisong** [comment]
已经解决，是没有升级openapi 看git代码最新gpt3.5的更新说明里面有。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月03日 19:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] ChatGPT国内被墙问题(已解决) (Issue #321) |

拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：

还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, ***@***.***

您好，有解决吗，我也是使用的腾讯云新加坡的服务器，应该不会墙吧，但是扫码后提示 的这个
Traceback (most recent call last): File "app.py", line 21, in <module> channel.startup() File "/www/wwwroot/ChatGpt/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login status = self.check_login() File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login if process_login_info(self, r.text): File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"] KeyError: 'wxsid'

**Comment by baichisong** [comment]
感谢，已解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月03日 18:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] ChatGPT国内被墙问题(已解决) (Issue #321) |

@baichisong 你这个问题是openai没有更新

**Comment by 199074343** [comment]
不知道为什么自己和自己聊天是不行的

**Comment by baichisong** [comment]
> > 拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：
> > ![image](https://user-images.githubusercontent.com/8436305/222620924-27f86fc6-ed7e-485d-a3b6-a13d4745dda2.png) 还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, receiver=@b2beb360347cc73355b5478c9b6f4674
> 
> 您好，有解决吗，我也是使用的腾讯云新加坡的服务器，应该不会墙吧，但是扫码后提示 的这个 `Traceback (most recent call last): File "app.py", line 21, in <module> channel.startup() File "/www/wwwroot/ChatGpt/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login status = self.check_login() File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login if process_login_info(self, r.text): File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"] KeyError: 'wxsid'`

我用的是亚马逊云，新加坡节点的服务器，我解决了是openai没有升级，最新gpt3.5代码下面有更新说明，我没执行导致的，执行完后就可以了

**Comment by explorerJi** [comment]
![image](https://user-images.githubusercontent.com/126233847/222770439-d84149b3-3408-4b98-a2d5-43fa4b41292a.png)
按照上面配置了，为啥还是不行？大神求解答～
![image](https://user-images.githubusercontent.com/126233847/222770755-18ba6c0f-f466-49c4-a45a-5b98fe40e4cb.png)

**Comment by explorerJi** [comment]
![image](https://user-images.githubusercontent.com/126233847/222771561-81de45ec-dca8-4648-a6e6-4ec98c3b2014.png)
![image](https://user-images.githubusercontent.com/126233847/222771846-0774274d-7350-4f04-9fb9-c21c9d1ee781.png)
环境变量也配置了，帮忙看一下是哪的问题～

**Comment by explorerJi** [comment]
![image](https://user-images.githubusercontent.com/126233847/222772293-9566d207-166e-4090-9d06-0407c066821b.png)
![image](https://user-images.githubusercontent.com/126233847/222772982-180ceca1-f8ce-4d91-a2ff-aa3ab63dfa9e.png)
![image](https://user-images.githubusercontent.com/126233847/222773125-ca9d4668-6933-405c-8566-537f09bcda91.png)
还是没有返回结果呢？

**Comment by min1854** [comment]
> ```shell
> 代理服务器ip地址和端口号
> ```
这里的 **代理服务器ip地址和端口号** 怎么理解？

**Comment by min1854** [comment]
> #### 前置确认
> 1. 运行于国内网络环境，未开代理
> 2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
> 3. 在已有 issue 中未搜索到类似问题
> 4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似前置确认
> 5. 仅仅由于是网络原因造成的(国内被墙)
> 
> 经过排查发现是国内网络已经无法调用, ~暂时无解决方案~
> 
> ### **解决思路:** 使用国外服务器 或者 使用代理(免费)
> ### **解决方案**如下: (使用代理)
> 本人使用 阿里云服务器搭建国外代理环境:
> 
> 自建教程: [ https://w1.v2free.top/auth/register?code=7np0](https://w1.v2free.top/auth/register?code=7np0)
> 
> 参考教程: https://github.com/bannedbook/fanqiang
> 
> 根据自己使用的操作系统选择搭建的流程.我使用的Linux操作系统,亲测有效 https://github.com/bannedbook/fanqiang/tree/master/linux 环境变量添加如下:
> 
> ```shell
> //编辑配置文件
> vim /etc/profile
>  
> //在该配置文件的最后添加代理配置
> export http_proxy='http://ip:port'    //代理服务器ip地址和端口号
> export https_proxy='http://ip:port'   //代理服务器ip地址和端口号
>  
>  
> // 退出profile文件并保存
> source /etc/profile     // 使配置文件生效
> ```
> 
> ![image](https://user-images.githubusercontent.com/76934061/222694873-cd98f67f-1c95-4d7c-8628-6cb426aa6fd6.png)
> 
> 希望此处理方法能够对大家有帮助.

请问 /etc/profile 需要配置代理服务器的ip和端口，这个怎么理解？应该从哪里获取填的地址

**Comment by Espererr** [comment]
> > > 拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：
> > > ![图像](https://user-images.githubusercontent.com/8436305/222620924-27f86fc6-ed7e-485d-a3b6-a13d4745dda2.png) 还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, receiver=@b2beb360347cc73355b5478c9b6f4674
> > 
> > 
> > 您好，有解决吗，我也是使用的腾讯云新加坡的服务器，应该不会墙吧，但是扫码后提示 的这个 `Traceback (most recent call last): File "app.py", line 21, in <module> channel.startup() File "/www/wwwroot/ChatGpt/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login status = self.check_login() File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login if process_login_info(self, r.text): File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"] KeyError: 'wxsid'`
> 
> 我用的是亚马逊云，新加坡节点的服务器，我解决了是openai没有升级，最新gpt3.5代码下面有更新说明，我没执行导致的，执行完后就可以了

请问你的openai依赖版本是多少，我升级了openai版本到0.27.0，也是提示你这个错误

**Comment by Mywbj** [comment]
香港服务器可以访问openai么

**Comment by sw0210** [comment]
python3.9版本在开了代理的情况下会运行报错，请降低urllib3模块的版本即可，pip install urllib3==1.25.11

**Comment by baichisong** [comment]
你直接按照代码下面提示升级openai就好了，那个升级openai命令没说明版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月04日 10:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] ChatGPT国内被墙问题(已解决) (Issue #321) |

拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：
还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, ***@***.***

您好，有解决吗，我也是使用的腾讯云新加坡的服务器，应该不会墙吧，但是扫码后提示 的这个 Traceback (most recent call last): File "app.py", line 21, in <module> channel.startup() File "/www/wwwroot/ChatGpt/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login status = self.check_login() File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login if process_login_info(self, r.text): File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"] KeyError: 'wxsid'

我用的是亚马逊云，新加坡节点的服务器，我解决了是openai没有升级，最新gpt3.5代码下面有更新说明，我没执行导致的，执行完后就可以了

请问你的openai依赖版本是多少，我升级了openai版本到0.27.0，也是提示你这个错误

**Comment by zhayujie** [comment]
网络问题解决：https://github.com/zhayujie/chatgpt-on-wechat/issues/351

**Comment by porvinci** [comment]
> ![image](https://user-images.githubusercontent.com/126233847/222770439-d84149b3-3408-4b98-a2d5-43fa4b41292a.png) 按照上面配置了，为啥还是不行？大神求解答～ ![image](https://user-images.githubusercontent.com/126233847/222770755-18ba6c0f-f466-49c4-a45a-5b98fe40e4cb.png)

请问你的问题解决了嘛？ 我现在的情况跟你一样

**Comment by lewjine** [comment]
> 阿里云，腾讯云购买国外服务器是否可以？

2023-06-04，购买阿里云美国节点window server服务器，尝试登录chatgpt，被提示 IP被限制，说明阿里云海外服务器也被墙了。
不知道用其它原生海外服务器供应商的服务器是否可以，比如亚马逊之类的服务器？

**Comment by zzzanejuuze** [comment]
> > 拉取最新的 chatgpt3.5项目： 1、我网络是新加坡节点， 2、配置如下：
> > ![image](https://user-images.githubusercontent.com/8436305/222620924-27f86fc6-ed7e-485d-a3b6-a13d4745dda2.png) 还是报错： [ERROR][2023-03-03 09:47:44][chat_gpt_bot.py:67] - module 'openai' has no attribute 'ChatCompletion' Traceback (most recent call last): File "C:\application\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text response = openai.ChatCompletion.create( AttributeError: module 'openai' has no attribute 'ChatCompletion' [INFO][2023-03-03 09:47:44][wechat_channel.py:103] - [WX] sendMsg=[bb] 请再问我一次吧, receiver=@b2beb360347cc73355b5478c9b6f4674
> 
> 您好，有解决吗，我也是使用的腾讯云新加坡的服务器，应该不会墙吧，但是扫码后提示 的这个 `Traceback (most recent call last): File "app.py", line 21, in <module> channel.startup() File "/www/wwwroot/ChatGpt/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login status = self.check_login() File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login if process_login_info(self, r.text): File "/usr/local/python3.7/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"] KeyError: 'wxsid'`

core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"] KeyError: 'wxsid'`我想问问，这个问题解决了吗？ 本地登录没问题，但服务器登录就会出现这个问题。FYI，服务器在新加坡。

**Comment by wenshan** [comment]
这个翻墙方案没走通
