### ISSUE TITLE
一直无回复

### ISSUE THREAD

**Issue by mx2013713828** [zhayujie/chatgpt-on-wechat#322]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

日志中能收到好友的消息，但是一直没有回复，用python写了一个responese测试也同意收不到回复，我开了全局代理，电脑能访问openai。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Runner1107** [comment]
和上述一致

**Comment by yxn4065** [comment]
我的开了代理能用,检查一下自己的代码ip地址位置,建议使用美国ip

**Comment by Runner1107** [comment]
> 我的开了代理能用,检查一下自己的代码ip地址位置,建议使用美国ip

我有自己的梯子和机场，能否教一下如何开启服务器代理呢，是在shell里实现还是说？先谢谢了

**Comment by mx2013713828** [comment]
```
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e36d4e4c0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
几分钟后报错，Failed to establish a new connection

**Comment by 0a1b2c** [comment]
都一样0.0求教一下

**Comment by mx2013713828** [comment]
> 都一样0.0求教一下 openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7934865e80>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 我是这个报错 昨天还在用，今天看更新了然后重新弄了一下就没了

尝试换几个代理，有时候能回复，但是很慢，我推测是需要连代理访问openai，然后又要回来访问wechat，导致网络连接不稳定

**Comment by zhayujie** [comment]
在 #310  讨论吧

**Comment by mx2013713828** [comment]
> 在 #310 讨论吧

ok!
