### ISSUE TITLE
二维码刷新过快

### ISSUE THREAD

**Issue by DreamNextHeart** [zhayujie/chatgpt-on-wechat#323]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
之前有个issues说到二维码刷新过快，扫码登录还没来得及点击确定新的二维码就出来了，没办法登录，然后要改python的一个文件，现在找不到这个issues了，希望能再解答一次

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
see #8
