### ISSUE TITLE
容器运行时：json.decoder.JSONDecodeError: 

### ISSUE THREAD

**Issue by Cupcc** [zhayujie/chatgpt-on-wechat#324]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
使用docker启动，在本地和在远程服务器都会莫名其妙的出现这个问题。第一次部署没有任何报错，再次启动容器就会奇怪的出现下面报错。  这个json我在拉去后，就没有修改过，git记录还是在几周前。
json.decoder.JSONDecodeError: Expecting value: line 5 column 30 (char 241)

<img width="812" alt="image" src="https://user-images.githubusercontent.com/53716543/222622364-970ea4e4-9963-430b-8d7a-bfb14fb8b74b.png">

### 终端日志 (如有报错)

```
[ERROR][2023-03-03 03:06:15][app.py:19] - App startup failed!
[ERROR][2023-03-03 03:06:15][app.py:20] - Expecting value: line 5 column 30 (char 241)
Traceback (most recent call last):
File "app.py", line 11, in <module>
config.load_config()
File "/app/config.py", line 18, in load_config
config = json.loads(config_str)
File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 30 (char 241)
```

### 环境

 - 操作系统类型  (MacOS Monterey 12.6.1)：
 - Python版本  ( Python 3.10.9)：                      
 - pip版本  ( pip 22.3.1)：

**Comment by water-root** [comment]
我也遇到类似的问题，请问你是怎么解决的
