### ISSUE TITLE
扫描二维码并点击登录但未成功会有封号危险嘛

### ISSUE THREAD

**Issue by tglf** [zhayujie/chatgpt-on-wechat#329]
我扫描了二维码在手机上点击登录后出现了二维码刷新现象，经过几次登录无果后去寻找解决问题的方法，然后发现有封号危险，我就没继续做下去了，我现在这样只扫描了二维码并在手机上点击了登录会有封号危险嘛

**Comment by zhayujie** [comment]
没事的， 有问题也会先警告

**Comment by tglf** [comment]
> 
好的谢谢大佬的回复
