### ISSUE TITLE
console输出barcode前含有空格和字符“#015”，无法正常扫描

### ISSUE THREAD

**Issue by yujuanjiang** [zhayujie/chatgpt-on-wechat#33]
请问大家知道这是什么问题吗？stdout输出log好像总是含有字符“#015”。
目前使用的服务器是PythonAnywhere。
之前有尝试过部署在Heroku上是可以正常输出barcode的，所以是环境的问题吗？

console输出如下：

```
Feb  1 15:41:38 Getting uuid of QR code.
Feb  1 15:41:39 Downloading QR code.
Feb  1 15:41:39                                                   #015██████████████████████████████████████████████████████████████████████████████
Feb  1 15:41:39 ██              ████    ██  ██  ████████    ██████  ██  ██████              ██
Feb  1 15:41:39 ██  ██████████  ████  ██  ██    ████████  ████  ████  ████████  ██████████  ██
Feb  1 15:41:39 ██  ██      ██  ██      ████████    ██  ██████  ████  ██    ██  ██      ██  ██

```

**Comment by zhayujie** [comment]
多调整下二维码生成的参数试试，代码在  chatgpt-on-wechat/channel/wechat/wechat_channel.py 的第37行，把enableCmdQR改成其他值试试

<img width="1494" alt="WeChatb8d3e52d112146a246a34c63cb05e6e8" src="https://user-images.githubusercontent.com/26161723/216110403-694bd2f7-2362-4d1e-928f-19dcc4d3f528.png">

**Comment by yujuanjiang** [comment]
谢谢回复！

我试过enableCmdQR=4/-1了，但是生成的二维码不可用。
赋值为2的时候生成的二维码是正确的，就仅仅是第一行因为这些空格和多余的字符导致错位。

除了二维码，在读config文件时也会输出这些字符：

```
Feb  2 02:07:21 █#015[INFO][2023-02-02 02:07:21][config.py:19] - [INIT] load config: {'open_ai_api_key': '', 'single_chat_prefix': ['', '@'], 'single_chat_reply_prefix': '[] ', 'group_chat_prefix': ['@'], 'group_name_white_list': ['ChatGPT测试群', '', ''], 'image_create_prefix': ['画', '看', '找']}
```
所以应该不是itchat的参数问题。

**Comment by zhayujie** [comment]
> 谢谢回复！
> 
> 我试过enableCmdQR=4/-1了，但是生成的二维码不可用。 赋值为2的时候生成的二维码是正确的，就仅仅是第一行因为这些空格和多余的字符导致错位。
> 
> 除了二维码，在读config文件时也会输出这些字符：
> 
> ```
> Feb  2 02:07:21 █#015[INFO][2023-02-02 02:07:21][config.py:19] - [INIT] load config: {'open_ai_api_key': '', 'single_chat_prefix': ['', '@'], 'single_chat_reply_prefix': '[] ', 'group_chat_prefix': ['@'], 'group_name_white_list': ['ChatGPT测试群', '', ''], 'image_create_prefix': ['画', '看', '找']}
> ```
> 
> 所以应该不是itchat的参数问题。

有可能是服务器命令行编码之类的问题，可以加下我wx帮你看下
