### ISSUE TITLE
可以添加敏感内容检测吗?

### ISSUE THREAD

**Issue by yxn4065** [zhayujie/chatgpt-on-wechat#332]
### 问题描述
可以添加关键词检测吗? 避免微信因为敏感内容被官方封号.
目前正在尝试百度云文本审核

**Comment by hecarli555** [comment]
我也觉得太有必要了，3.5模型是真的你敢问它敢答。。。。

**Comment by hecarli555** [comment]
> 目前`banwords`插件可用于屏蔽敏感内容。

请问如何使用这个插件？
