### ISSUE TITLE
登录失败: mismatched tag: line 64, column 4

### ISSUE THREAD

**Issue by dapao111** [zhayujie/chatgpt-on-wechat#333]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
确认

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
登录失败，但是一开始是能正常运行的，后面掉线后，再登录就出现问题了，其中装了itchat，问题如下

### 终端日志 (如有报错)

```
[ERROR][2023-03-03 19:52:59][app.py:19] - App startup failed!
[ERROR][2023-03-03 19:52:59][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1969, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4
```

### 环境
Linux，python3.8 pip3 20.0.2
 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
检查是否安装了 itchat-uos，以及版本是否为 1.5.0.dev0

**Comment by dapao111** [comment]
已经装上了的，开始的时候都能运行几个小时的了

**Comment by zhayujie** [comment]
执行下 
pip3 show itchat-uos
pip3 show itchat

**Comment by xiaoqixian** [comment]
> 执行下 pip3 show itchat-uos pip3 show itchat

Name: itchat
Version: 1.3.10
Summary: A complete wechat personal account api
Home-page: https://github.com/littlecodersh/ItChat
Author: LittleCoder
Author-email: i7meavnktqegm1b@qq.com
License: MIT
Location: /Users/lunar/Library/Python/3.8/lib/python/site-packages
Requires: pypng, pyqrcode, requests
Required-by: 

Name: itchat-uos
Version: 1.5.0.dev0
Summary: 复活Itchat, 仅仅需要 pip install itchat-uos, good luck !
Home-page: https://github.com/why2lyj/ItChat-UOS
Author: Snow Wang
Author-email: admin@farseer.vip
License: MIT
Location: /Users/lunar/Library/Python/3.8/lib/python/site-packages
Requires: pypng, pyqrcode, requests
Required-by:

**Comment by zhayujie** [comment]
@xiaoqixian 

正常应该是这样：
pip3 show itchat-uos      # 依赖存在
pip3 show itchat              # 依赖不存在

所以要把 itcaht 卸载掉， 只需要itchat-uos  依赖

**Comment by h-gj** [comment]
我也遇到了这个报错 

“
正常应该是这样：
pip3 show itchat-uos # 依赖存在
pip3 show itchat # 依赖不存在
”

我的是正常的

貌似是微信不能登录网页版造成的这个报错

**Comment by h-gj** [comment]
刚去itchat issue里看了下 果然是:  https://github.com/littlecodersh/ItChat/issues/960

**Comment by dapao111** [comment]
我微信是有问题的了，，现在解决拉。

**Comment by xiaozhiling2** [comment]
[ERROR][2023-03-08 12:55:48][app.py:19] - App startup failed!
[ERROR][2023-03-08 12:55:48][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "E:\chatgpt-on-wechat\chatgpt-on-wechat-master\app.py", line 17, in <module>
    channel.startup()
  File "E:\chatgpt-on-wechat\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "E:\python\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "E:\python\lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
  File "E:\python\lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "E:\python\lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "E:\python\lib\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "E:\python\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "E:\python\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4
，也卸载了itchat还是不行，itchat-uos1.5

**Comment by maple-dawn** [comment]
> 我微信是有问题的了，，现在解决拉。

怎么解决的

**Comment by maple-dawn** [comment]
我解决了，是因为少装了pip的库，试试 pip3 install itchat-uos==1.5.0.dev0

**Comment by xiaozhiling2** [comment]
能给帮我看看吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333)





 
我解决了，是因为少装了pip的库，试试 pip3 install itchat-uos==1.5.0.dev0

**Comment by xiaozhiling2** [comment]
你能发送了吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333)





  
我微信是有问题的了，，现在解决拉。
  
怎么解决的

**Comment by zhibei2000** [comment]
> 你能发送了吗 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhayujie/chatgpt-on-wechat" ***@***.***&gt;; 发送时间:&nbsp;2023年3月10日(星期五) 下午2:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333) 我微信是有问题的了，，现在解决拉。 怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

解决了么兄台

**Comment by xiaozhiling2** [comment]
没有解决，一直没有查找到哪里出现问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333)





  
你能发送了吗 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhayujie/chatgpt-on-wechat" @.&gt;; 发送时间:&nbsp;2023年3月10日(星期五) 下午2:17 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333) 我微信是有问题的了，，现在解决拉。 怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
解决了么兄台

**Comment by zhibei2000** [comment]
> 没有解决，一直没有查找到哪里出现问题 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhayujie/chatgpt-on-wechat" ***@***.***&gt;; 发送时间:&nbsp;2023年3月11日(星期六) 晚上6:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333) 你能发送了吗 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhayujie/chatgpt-on-wechat" @.&gt;; 发送时间:&nbsp;2023年3月10日(星期五) 下午2:17 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 登录失败: mismatched tag: line 64, column 4 (Issue #333) 我微信是有问题的了，，现在解决拉。 怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 解决了么兄台 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

昨天已经解决了  也是因为pip3 install itchat-uos==1.5.0.dev0   ，你可以把库卸载重装一下，或者把itchat卸载再装 itchat-uos，
pip3 install itchat-uos==1.5.0.dev0
pip3 install --upgrade openai

**Comment by dapao111** [comment]
就是你们登录一下自己的微信，然后我当时是发消息出去都不能了，要求我再验证什么，才行的

**Comment by Terryzhang-jp** [comment]
> 我解决了，是因为少装了pip的库，试试 pip3 install itchat-uos==1.5.0.dev0
这个解决了我的问题

**Comment by totootao** [comment]
pip3 install itchat-uos==1.5.0.dev0这个也不管用，我用下面这个docker镜像解决了
https://github.com/HoganGolden/efb-wechat-docker-itchat-uos

**Comment by Vincent-Crawl** [comment]
> 我解决了，是因为少装了pip的库，试试 pip3 install itchat-uos==1.5.0.dev0

非常感谢老哥
