### ISSUE TITLE
ChatGPTBot中为何不实现会话超长删除功能

### ISSUE THREAD

**Issue by zwssunny** [zhayujie/chatgpt-on-wechat#335]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
OpenAIBot有实现session的discard_exceed_conversation函数，去除超长的记录
在ChatGPTBot中为何不用，这样会增加占用传输资源，时间和费用吗？

**Comment by zhayujie** [comment]
这个问题会优化 #343
