### ISSUE TITLE
请问能打包到railway吗

### ISSUE THREAD

**Issue by iknow2333** [zhayujie/chatgpt-on-wechat#336]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Cupcc** [comment]
我已经实现部署到了railway，可以拉取我fork的仓库进行部署，启动时添加变量。

**Comment by iknow2333** [comment]
> 我已经实现部署到了railway，可以拉取我fork的仓库进行部署，启动时添加变量。
部署到railway后打印的二维码扫不出来
![image](https://user-images.githubusercontent.com/103983460/222913333-253efcfc-55eb-4250-b6df-5b6e6c8ce350.png)

可以像这个项目一样打印二维码的链接吗[https://github.com/kx-Huang/ChatGPT-on-WeChat](url)

**Comment by iknow2333** [comment]
> 我已经实现部署到了railway，可以拉取我fork的仓库进行部署，启动时添加变量。

问题已经解决了，截屏然后把中间那行字涂黑就可以识别了😂

**Comment by callmesummer** [comment]
> 我已经实现部署到了railway，可以拉取我fork的仓库进行部署，启动时添加变量。

假的，跟官方的回答都不一样，语言模型还能画图吗

**Comment by fh12** [comment]
> 我已经实现部署到了railway，可以拉取我fork的仓库进行部署，启动时添加变量。
@zhayujie 坐等大佬安排

**Comment by lanvent** [comment]
已支持railway一键部署

**Comment by 1797072990** [comment]
> 

这个长方形的二维码确定能扫上吗
