### ISSUE TITLE
请问数据源还可以使用原来的从 ChatGPT页面 获取session_token 的方案吗？

### ISSUE THREAD

**Issue by lpflhh** [zhayujie/chatgpt-on-wechat#338]
apikey 消耗的太快了，以前的方案直接从网页里提取，而且完全免费，真的很棒

**Comment by EnochYe** [comment]
很麻烦，有人机检测

**Comment by lpflhh** [comment]
我们可以手动添加，类似于这个 手动从网页中提取一个session_toke，用到现在已经2周了，https://github.com/SnapdragonLee/ChatGPT-weBot/，供参考
