### ISSUE TITLE
代理过了，还是终端还是会报错，用的虚拟机，不知道是不是虚拟机的问题

### ISSUE THREAD

**Issue by 0a1b2c** [zhayujie/chatgpt-on-wechat#341]
![image](https://user-images.githubusercontent.com/126233847/222770439-d84149b3-3408-4b98-a2d5-43fa4b41292a.png)
按照上面配置了，为啥还是不行？大神求解答～
![image](https://user-images.githubusercontent.com/126233847/222770755-18ba6c0f-f466-49c4-a45a-5b98fe40e4cb.png)

_Originally posted by @explorerJi in https://github.com/zhayujie/chatgpt-on-wechat/issues/321#issuecomment-1453766410_

**Comment by 0a1b2c** [comment]
代理过了还是报错

**Comment by 0a1b2c** [comment]
主机需不需要挂一个啊0.0

**Comment by zhayujie** [comment]
是不是没生效
