### ISSUE TITLE
升级到3.5后，依赖也安装了，运行登录后，发送消息后台请求超时

### ISSUE THREAD

**Issue by 1574162728** [zhayujie/chatgpt-on-wechat#342]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
考虑是网络不通问题 #310

**Comment by 1574162728** [comment]
![QQ截图20230305094239](https://user-images.githubusercontent.com/121914609/222937026-05c1c098-80e7-4cc7-bb7c-1a25a8719018.png)
网络应该是通的，官网能正常访问

**Comment by 1574162728** [comment]
前段时间都正常的

**Comment by 1574162728** [comment]
解决了，科学上网用的浏览器插件
