### ISSUE TITLE
对话超长问题 This model's maximum context length is 4096 tokens

### ISSUE THREAD

**Issue by txz-code-farmer** [zhayujie/chatgpt-on-wechat#343]
openai.error.InvalidRequestError: This model's maximum context length is 4096 tokens. However, you requested 4170 tokens (74 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
[INFO][2023-03-04 14:46:16][wechat_channel.py:103] - [WX] sendMsg=[bot] 请再问我一次吧, receiver=@bd6f7640bf7b574ddbd639f67f6a5c9a5f0f0cc12692a785d9164e56d77587e0
[INFO][2023-03-04 14:46:48][chat_gpt_bot.py:20] - [OPEN_AI] query=请回复不超过4000个字数的回答
[ERROR][2023-03-04 14:46:48][chat_gpt_bot.py:68] - This model's maximum context length is 4096 tokens. However, you requested 4178 tokens (82 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
Traceback (most recent call last):
  File "/home/txz/chatgpt/chatgpt-on-wechat-master/bot/chatgpt/chat_gpt_bot.py", line 44, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4096 tokens. However, you requested 4178 tokens (82 in the messages, 4096 in the completion). Pl

**Comment by as5846197** [comment]
我也是这个问题

**Comment by Zhang-Henry** [comment]
我也是这个问题

**Comment by apango** [comment]
我也是这个问题
[INFO][2023-03-04 14:57:41][chat_gpt_bot.py:20] - [OPEN_AI] query=用js写一段快速排序的代码例子
[ERROR][2023-03-04 14:57:42][chat_gpt_bot.py:68] - This model's maximum context length is 4096 tokens. However, you requested 4176 tokens (80 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
Traceback (most recent call last):
  File "/home/apango/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 44, in reply_text
    response = openai.ChatCompletion.create(
  File "/home/apango/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/apango/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/apango/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/apango/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/apango/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4096 tokens. However, you requested 4176 tokens (80 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
[INFO][2023-03-04 14:57:42][wechat_channel.py:103] - [WX] sendMsg=[bot] 请再问我一次吧, receiver=@a48e715d3a307792a3a34477368f9d9e

**Comment by Zhang-Henry** [comment]
刚刚才出现这个问题吗

**Comment by muxw** [comment]
+1

**Comment by datonli** [comment]
同样问题

**Comment by aisuyi065** [comment]
+1

**Comment by wojoker** [comment]
![image](https://user-images.githubusercontent.com/81979996/222884823-359d1eac-8621-4187-a40a-74290c29d8be.png)
更改一下maxtoken

**Comment by dsantial** [comment]
> ![image](https://user-images.githubusercontent.com/81979996/222884823-359d1eac-8621-4187-a40a-74290c29d8be.png) 更改一下maxtoken

正解,更改之后就可以了

**Comment by sunxin18** [comment]
更改了也是不行

**Comment by zhayujie** [comment]
拉一下最新代码， 或者把max_tokens 注释掉，参考  https://github.com/zhayujie/chatgpt-on-wechat/commit/f67dae5b0baaece9294acda8f0802b545a359396

**Comment by zhayujie** [comment]
问题：  gpt-3.5-turbo 模型限制最大对话长度为 4096 tokens (包括提问 和 回答)，  这里max_tokens 参数设置的是 回复的最大长度，设置成4096的话，再加上提问就超长了。  

解决： 临时方案先不传这个参数， 默认的 max_tokens 就等于 4096 - prompt 的长度。  但没有彻底解决问题，随着对话轮数的增加，回复的字数会越来越少。

TODO： 需要做一个优化， 超限自动移除最早的对话。

**Comment by lichengzhe** [comment]
几个思路供参考
1. 自动清理（可以设置一个阀值，比如过了2000 tokens，清理最早的，按条完整切）。
2. 自动精简之前的（用chatgpt自己来汇总精简之前的话题context）。
3. 加个参数，空闲多少小时后，新问题自动开启新的话题。

**Comment by RustingSword** [comment]
精确的 token 数量可以用 [tiktoken](https://github.com/openai/tiktoken) 来获取，`gpt-3.5-turbo`用的 encoder 是`tiktoken.encoding_for_model("gpt-3.5-turbo")` (`cl100k_base`)

**Comment by mymhzm** [comment]
这边加了一个自动清理最早对话的方法：由于api的最大tokens是4096（包括问题和回答），所以在每次得到问题的时候拼上历史数据，看看这时候超不超给定的maxtokens，然后再限制下api返回的tokens数即可。maxtokens值的确定，需要满足的规则是：历史问答tokens + 本次提问tokens + api返回tokens <= 4096，也就是设置maxtokens=历史问答tokens+本次提问tokens，就好。ps，记得修改api返回的tokens数。
![image](https://user-images.githubusercontent.com/59270781/223662623-20ab231d-1b06-4542-8732-ceb2365f9f34.png)

**Comment by zhayujie** [comment]
@mymhzm  每次可以pop(1)两次，删除一对问答

**Comment by lingvisa** [comment]
但 chatGPT 能够一直聊下去没有限制，不知怎么实现的？

**Comment by edmodoWorld-Justin** [comment]
> > ![image](https://user-images.githubusercontent.com/81979996/222884823-359d1eac-8621-4187-a40a-74290c29d8be.png) 更改一下maxtoken
> 
> 正解,更改之后就可以了

为啥呢？？我不太理解，max_token指的是一个我设置的值，比如当前设置为4000，然后后我当前的token才200多，API就报错了呢

**Comment by weatherman6996** [comment]
> 

请教：怎么利用chatgpt汇总精简上文？
