### ISSUE TITLE
香港服务器可以访问openai么？

### ISSUE THREAD

**Issue by Mywbj** [zhayujie/chatgpt-on-wechat#344]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by MinimalistRecommend** [comment]
我的香港服务器可以

**Comment by Mywbj** [comment]
> 我的香港服务器可以

可以推荐哪里买香港服务器比较优惠吗？

**Comment by MinimalistRecommend** [comment]
> 

我也不知道，我用的是华为云的香港服务器。续费很贵，还有两个月到期最近也在寻找替代品。

**Comment by HyperHare** [comment]
> > 我的香港服务器可以
> 
> 可以推荐哪里买香港服务器比较优惠吗？

用aws的服务器 免费12个月，挂个机器人足够

**Comment by Mywbj** [comment]
> > > 我的香港服务器可以
> > 
> > 
> > 可以推荐哪里买香港服务器比较优惠吗？
> 
> 用aws的服务器 免费12个月，挂个机器人足够

支持选window系统吗？

**Comment by HyperHare** [comment]
> > > > 我的香港服务器可以
> > > 
> > > 
> > > 可以推荐哪里买香港服务器比较优惠吗？
> > 
> > 用aws的服务器 免费12个月，挂个机器人足够
> 
> 支持选window系统吗？

支持 我已经试验过了

**Comment by Mywbj** [comment]
> > > > > 我的香港服务器可以
> > > > 
> > > > 
> > > > 可以推荐哪里买香港服务器比较优惠吗？
> > > 
> > > 
> > > 用aws的服务器 免费12个月，挂个机器人足够
> > 
> > 
> > 支持选window系统吗？
> 
> 支持 我已经试验过了

这恐怕有点儿麻烦，注册这么多步骤，还要信用卡那些

**Comment by HyperHare** [comment]
> 

淘宝上有代注册的 还有教程告诉你怎么弄 不过得花钱

**Comment by HyperHare** [comment]
> > > > > > 我的香港服务器可以
> > > > > 
> > > > > 
> > > > > 可以推荐哪里买香港服务器比较优惠吗？
> > > > 
> > > > 
> > > > 用aws的服务器 免费12个月，挂个机器人足够
> > > 
> > > 
> > > 支持选window系统吗？
> > 
> > 
> > 支持 我已经试验过了
> 
> 这恐怕有点儿麻烦，注册这么多步骤，还要信用卡那些

淘宝上有代注册的 还有教程告诉你怎么弄 不过得花钱

**Comment by etianwang** [comment]
> > 我的香港服务器可以
> 
> 可以推荐哪里买香港服务器比较优惠吗？

hostyun，dogyun，

**Comment by Kevin111369** [comment]
> 我的香港服务器可以

你好，我是用的新加坡的服务器，宝塔面板端口已经放行，为什么没有网络连接呢？

**Comment by MinimalistRecommend** [comment]
> 
请除去敏感信息后把日志发出来看看，你这样问，我是神仙也不知道什么问题（笑哭）

**Comment by Kevin111369** [comment]
已经解决了，作者给出了解决方案，把proxy改成""> > 
> 
> 请除去敏感信息后把日志发出来看看，你这样问，我是神仙也不知道什么问题（笑哭）

**Comment by blackhorse1234** [comment]
求大神指点？

**Comment by Kevin111369** [comment]
> 求大神指点？

我也遇到了同样的问题，我的python版本为3.8.1，将pip3 install换成python3 -m pip install再执行这两个安装命令就解决了

**Comment by MinimalistRecommend** [comment]
python 版本不对，6.几太低了，用3.8吧

**Comment by johnathonyeo** [comment]
[WARNING][2023-04-20 21:32:33][chat_gpt_bot.py:152] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f72ef5988b0>: Failed to establish a new connection: [Errno -2] Name or service not known')))
哪个大神可以帮看看这个报错，不知道是不是我地址有问，不太知道proxy该怎么填

**Comment by Lingxiaocong** [comment]
> 

AWS的什么节点的服务器，也是香港吗？

**Comment by johnathonyeo** [comment]
> > 
> 
> AWS的什么节点的服务器，也是香港吗？
解决了，是服务器节点的问题
