### ISSUE TITLE
这是什么问题啊？貌似连不上

### ISSUE THREAD

**Issue by eeeit819** [zhayujie/chatgpt-on-wechat#347]
[ERROR][2023-03-04 18:58:59][chat_gpt_bot.py:67] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0287793f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
是请求地址错了吗？

**Comment by zhayujie** [comment]
see #310
