### ISSUE TITLE
 ChatGPT-3.5 官方API被墙解决方案

### ISSUE THREAD

**Issue by reBiocoder** [zhayujie/chatgpt-on-wechat#353]
### 问题
- 微信容易封号
- gpt3.5API国内被墙了，无法直接访问

### 前置条件
关注订阅号【AI守门员】

### 使用方法
在聊天框输入 api-key=openai秘钥（你的openai账号的秘钥），即可激活私人GPT3.5AI

### 如图
![image](https://user-images.githubusercontent.com/39401819/222918635-ffbcbead-8384-4f16-a08b-cd5e853bd371.png)

### 原理
UCCLOUD 香港服务器部署，给兄弟们做贡献了，直接用吧

**Comment by LiangLiangGong** [comment]
还是一样的，并没有解决

**Comment by reBiocoder** [comment]
> 还是一样的，并没有解决

用的gpt-3.5-turbo接口啊，可以直接用

**Comment by ZihaoZheng98** [comment]
> 

你在国内不挂代理能用吗？

**Comment by reBiocoder** [comment]
> 

可以啊，香港的服务器

**Comment by reBiocoder** [comment]
> > 
> 
> 你在国内不挂代理能用吗？
可以啊，香港的服务器
