### ISSUE TITLE
丰富功能建议

### ISSUE THREAD

**Issue by lichengzhe** [zhayujie/chatgpt-on-wechat#355]
希望可以参考 https://github.com/RockChinQ/QChatGPT 丰富功能，热更最优先！感谢~

✅支持敏感词过滤，避免账号风险
难以监测机器人与用户对话时的内容，故引入此功能以减少机器人风险
编辑sensitive.json，并在config.py中修改sensitive_word_filter的值以开启此功能
✅群内多种响应规则，不必at
默认回复ai作为前缀或@机器人的消息
详细见config.py中的response_rules字段
✅完善的多api-key管理，超额自动切换
支持配置多个api-key，内部统计使用量并在超额时自动切换
请在config.py中修改openai_config的值以设置api-key
可以在config.py中修改api_key_fee_threshold来自定义切换阈值
运行期间向机器人说!usage以查看当前使用情况
✅支持预设指令文字
支持以自然语言预设文字，自定义机器人人格等信息
详见config.py中的default_prompt部分
支持设置多个预设情景，并通过!reset、!default等指令控制
✅支持对话、绘图等模型，可玩性更高
现已支持OpenAI的对话Completion API和绘图Image API
向机器人发送指令!draw <prompt>即可使用绘图模型
✅支持指令控制热重载、热更新
允许在运行期间修改config.py或其他代码后，以管理员账号向机器人发送指令!reload进行热重载，无需重启
运行期间允许以管理员账号向机器人发送指令!update进行热更新，拉取远程最新代码并执行热重载
✅支持插件加载🧩
自行实现插件加载器及相关支持
✅私聊、群聊黑名单机制
支持将人或群聊加入黑名单以忽略其消息
详见Wiki加入黑名单节
✅回复速度限制
支持限制单会话内每分钟可进行的对话次数
具有“等待”和“丢弃”两种策略
“等待”策略：在获取到回复后，等待直到此次响应时间达到对话响应时间均值
“丢弃”策略：此分钟内对话次数达到限制时，丢弃之后的对话

**Comment by chuxiongzhu** [comment]
请问如何调整回复速度限制呢？现在的回复速度有点过于慢了。谢谢！
