### ISSUE TITLE
出来的二维码无法扫描，不是正方形的二维码

### ISSUE THREAD

**Issue by AndyHuyidi** [zhayujie/chatgpt-on-wechat#359]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by nocatlll** [comment]
正确安装itchat-uos库，运行app.py后根目录会出现对应二维码的截图

**Comment by AndyHuyidi** [comment]
好的，谢谢。已经解决
