### ISSUE TITLE
扫码登录 一直超时问题

### ISSUE THREAD

**Issue by ergwang** [zhayujie/chatgpt-on-wechat#36]
项目跑起来之后，我用微信扫码登录，但是微信有个安全验证需要5s时间，5s还没结束，控制台就报超时，然后给我一个新的二维码，然后就陷入循环。。。
![image](https://user-images.githubusercontent.com/37934035/216595557-275280b8-f7ce-4b67-84e9-31acf41cac27.png)

**Comment by zhayujie** [comment]
参考这个issue https://github.com/zhayujie/chatgpt-on-wechat/issues/8   需要改一行代码

**Comment by lvbuwei520** [comment]
> 参考这个issue #8 需要改一行代码

改了也不行。没有生效。是啥原因呢？
