### ISSUE TITLE
后台报错“由于目标计算机积极拒绝，无法连接。”

### ISSUE THREAD

**Issue by Joelsenior** [zhayujie/chatgpt-on-wechat#361]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
后台报错“由于目标计算机积极拒绝，无法连接。”
> 简要说明、截图、复现步骤等，也可以是需求或想法
l
![image](https://user-images.githubusercontent.com/54619146/222968275-bda37483-e250-4f69-b673-a559b32d2faf.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
[INFO][2023-03-05 22:53:07][chat_gpt_bot.py:26] - [OPEN_AI] query=你是谁
[WARNING][2023-03-05 22:53:13][chat_gpt_bot.py:74] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C85C64E2E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[WARNING][2023-03-05 22:53:13][chat_gpt_bot.py:75] - [OPEN_AI] APIConnection failed
[INFO][2023-03-05 22:53:13][wechat_channel.py:108] - [WX] sendMsg=[bot] 我连接不到你的网络, receiver=@8eda300adfadb0cc88ec738e008a1d28e3977b4d727caa0769b04437a8b241ec

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：window 11
 - Python版本  ( 执行 `python3 -V` )：  python 9.1                    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
see #310
