### ISSUE TITLE
小白微信二维码无法扫描

### ISSUE THREAD

**Issue by xwj2** [zhayujie/chatgpt-on-wechat#365]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
本地运行app.py出现QR code让我扫描，但是扫不了啊

### 终端日志 (如有报错)

```
![image](https://user-images.githubusercontent.com/111725640/223011031-fa3b635e-9e3f-4f26-b061-6a2c5a169cf3.png)

[在此处粘贴终端日志]
```Please scan the QR code to log in.



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by reBiocoder** [comment]
微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353

**Comment by zhayujie** [comment]
具体二维码是什么样的，可以把日志贴出来一下

什么系统环境，python版本多少

**Comment by kky529999** [comment]
这个问题我也有，用的server2008的服务器，python3.7，该装的都装了，出来的二维码不对

**Comment by kky529999** [comment]
![1678163036049](https://user-images.githubusercontent.com/10071138/223320304-383eaefb-ddad-411a-8751-b387628e93ec.jpg)
这种的二维码，应该是不对的吧

**Comment by zhayujie** [comment]
@kky529999  参考这个 修改行代码试试
