### ISSUE TITLE
如何在bot回答内容头或尾部增加回复的问题

### ISSUE THREAD

**Issue by ynzheng** [zhayujie/chatgpt-on-wechat#37]
群里,很多人@机器人时候,因为机器人一一回复, 且较慢

导致回答的内容和回复的问题,都不在一起, 很乱, 

建议在bot回答内容头或尾部增加回复的问题, 并且@提问人

**Comment by zhayujie** [comment]
现在群聊@提问人的功能已经有了吧？  回答头部增加问题引用的 我考虑加一下

**Comment by zqm11** [comment]
为什么完成扫描登入后，微信没有聊天窗口

**Comment by zhayujie** [comment]
> 为什么完成扫描登入后，微信没有聊天窗口

扫描二维码登录后，你的wx就已经成为机器人了， 你可以找一个好友向他发送  @bot xxx ，触发自动回复

**Comment by kurtn2005** [comment]
> > 为什么完成扫描登入后，微信没有聊天窗口
> 
> 扫描二维码登录后，你的wx就已经成为机器人了， 你可以找一个好友向他发送 @bot xxx ，触发自动回复

大佬，我在企业微信中申请一个机器人，可以让它代替我吗？

**Comment by zhayujie** [comment]
> > > 为什么完成扫描登入后，微信没有聊天窗口
> > 
> > 
> > 扫描二维码登录后，你的wx就已经成为机器人了， 你可以找一个好友向他发送 @bot xxx ，触发自动回复
> 
> 大佬，我在企业微信中申请一个机器人，可以让它代替我吗？

企业微信貌似不行，接口不同

**Comment by kurtn2005** [comment]
> > > > 为什么完成扫描登入后，微信没有聊天窗口
> > > 
> > > 
> > > 扫描二维码登录后，你的wx就已经成为机器人了， 你可以找一个好友向他发送 @bot xxx ，触发自动回复
> > 
> > 
> > 大佬，我在企业微信中申请一个机器人，可以让它代替我吗？
> 
> 企业微信貌似不行，接口不同

那我看你说明中截图答复的是机器人呢，是一个单独账号（角色），而不是自问自答那种效果，我现在就是在充当机器人了，你那个是怎么做到的呢？难道是单独一个微信账号？

**Comment by zhayujie** [comment]
> > > > > 为什么完成扫描登入后，微信没有聊天窗口
> > > > 
> > > > 
> > > > 扫描二维码登录后，你的wx就已经成为机器人了， 你可以找一个好友向他发送 @bot xxx ，触发自动回复
> > > 
> > > 
> > > 大佬，我在企业微信中申请一个机器人，可以让它代替我吗？
> > 
> > 
> > 企业微信貌似不行，接口不同
> 
> 那我看你说明中截图答复的是机器人呢，是一个单独账号（角色），而不是自问自答那种效果，我现在就是在充当机器人了，你那个是怎么做到的呢？难道是单独一个微信账号？

是的，我的小号

**Comment by zhayujie** [comment]
这段时间群聊试用和反馈来看，好像回复@ 足以支持， 暂时不考虑

**Comment by guoqn** [comment]
> > > > 为什么完成扫描登入后，微信没有聊天窗口
> > > 
> > > 
> > > 扫描二维码登录后，你的wx就已经成为机器人了， 你可以找一个好友向他发送 @bot xxx ，触发自动回复
> > 
> > 
> > 大佬，我在企业微信中申请一个机器人，可以让它代替我吗？
> 
> 企业微信貌似不行，接口不同

大佬，正常群里中的微信机器人指的就是小号是吧
