### ISSUE TITLE
运行python3 app.py报错；

### ISSUE THREAD

**Issue by yixmlh90** [zhayujie/chatgpt-on-wechat#371]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
拉取最新代码后，改了图片规格，加了配置"group_at_off": true,
  "group_chat_reply_prefix": "[bot] "，然后运行python3 app.py报错；

:~/chatgpt-on-wechat $ python3 app.py
[ERROR][2023-03-06 09:25:31][app.py:19] - App startup failed!
[ERROR][2023-03-06 09:25:31][app.py:20] - Expecting ',' delimiter: line 10 column 3 (char 326)
Traceback (most recent call last):
  File "/home/pi/chatgpt-on-wechat/app.py", line 11, in <module>
    config.load_config()
  File "/home/pi/chatgpt-on-wechat/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 10 column 3 (char 326)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lihuaiyu0131** [comment]
你检查下配置文件是不是有个逗号是不是没有删除？
