### ISSUE TITLE
二维码等待时间不足

### ISSUE THREAD

**Issue by ZhenBab** [zhayujie/chatgpt-on-wechat#372]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
微信扫码登陆手机端会提示陌生设备登陆，需要等5秒，但是系统这事会告知超时，重新发送二维码
Please scan the QR code to log in.
Please press confirm on your phone.
Log in time out, reloading QR code.
Getting uuid of QR code.
Downloading QR code.

> 简要说明、截图、复现步骤等，也可以是需求或想法

可以设置可调节二维码过期时长

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
see #8

**Comment by ZhenBab** [comment]
谢谢大佬！
