### ISSUE TITLE
我连接不到你的网络

### ISSUE THREAD

**Issue by BianXuerui** [zhayujie/chatgpt-on-wechat#374]
我使用的是新加坡的服务器的外网ip地址，然而发送消息的时候提醒，我连接不到你的网络，不知道该如何解决。
![image](https://user-images.githubusercontent.com/50104688/223077879-88ac2f7a-dd67-4a72-8942-ea9de6e015c6.png)

**Comment by EnochYe** [comment]
新加坡服务器不能用微信发消息，建议用hk的服务器，或者在新加坡的服务器上代理到国内。

**Comment by zhayujie** [comment]
贴下具体的报错日志

**Comment by godblessbb** [comment]
遇到了同样的问题，也是新加坡的服务器。
Start auto replying.
[INFO][2023-03-06 22:44:10][chat_gpt_bot.py:26] - [OPEN_AI] query=请为我写一首五言绝句诗
[WARNING][2023-03-06 22:44:10][chat_gpt_bot.py:84] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))
[WARNING][2023-03-06 22:44:10][chat_gpt_bot.py:85] - [OPEN_AI] APIConnection failed
[INFO][2023-03-06 22:44:10][wechat_channel.py:108] - [WX] sendMsg=[bot] 我连接不到你的网络, receiver=@2ecf108bf4e4b5575fa7bebe289d9796

> 贴下具体的报错日志

**Comment by zhayujie** [comment]
@BianXuerui @godblessbb  在外网服务器proxy字段保持为 "" 就行了，不用配置代理

**Comment by godblessbb** [comment]
> @BianXuerui @godblessbb 在外网服务器proxy字段保持为 "" 就行了，不用配置代理

照您说的，解决了问题。不过还有个问题想问一下，如果我想单聊的时候随时可以触发回答该咋做，似乎直接删掉jasn里的bot不解决问题。

**Comment by godblessbb** [comment]
以及，作者您知道如何添加字数限制吗

**Comment by zhangiou0** [comment]
![捕获3](https://user-images.githubusercontent.com/11896872/223358487-d3e185de-27b4-4dfb-a26a-ed05ca1fb60d.JPG)
你好我这个也是无法连接到网络

**Comment by BianXuerui** [comment]
统一回复，如果是外网服务器，proxy：""即可，不需要填写ip地址

**Comment by zhangshuodale** [comment]
我docker上安装的，机场用的hk的。。。还是找不到网络，请问如何解决？

**Comment by zhangshuodale** [comment]
<html>
<body>


date | stream | content
-- | -- | --
2023/07/22 18:50:23 | stdout | 我连接不到你的网络), receiver=@916f06980084a05ef4d955343842f6
2023/07/22 18:50:23 | stdout | [INFO][2023-07-22 10:50:23][wechat_channel.py:186] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
2023/07/22 18:50:23 | stdout | [WARNING][2023-07-22 10:50:23][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023/07/22 18:50:22 | stdout | [INFO][2023-07-22 10:50:22][chat_gpt_bot.py:49] - [CHATGPT] query=hello
2023/07/22 18:47:47 | stdout | 我连接不到你的网络), receiver=@916f069804a05ef4dcb955343842f6
2023/07/22 18:47:47 | stdout | [INFO][2023-07-22 10:47:47][wechat_channel.py:186] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
2023/07/22 18:47:47 | stdout | [WARNING][2023-07-22 10:47:47][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023/07/22 18:47:45 | stdout | [INFO][2023-07-22 10:47:45][chat_gpt_bot.py:49] - [CHATGPT] query=你好
2023/07/22 18:47:45 | stdout | [INFO][2023-07-22 10:47:45][bridge.py:32] - create bot chatGPT for chat
2023/07/22 18:47:36 | stderr | Start auto replying.
2023/07/22 18:47:36 | stdout | [INFO][2023-07-22 10:47:36][wechat_channel.py:123] - Wechat login success, user_id: @91d62850f2f7830a238b348601abfadfff242464be70947dd0d570f021aef, nickname: 雪
2023/07/22 18:47:36 | stderr | Login successfully as 雪
2023/07/22 18:47:34 | stderr | Loading the contact, this may take a little while.
2023/07/22 18:47:16 | stderr | Please press confirm on your phone


</body>
</html>

**Comment by PalmerWang** [comment]
![Snipaste_2024-05-14_16-58-03](https://github.com/zhayujie/chatgpt-on-wechat/assets/22316532/e82a4dad-4edb-488c-9c4a-cad72c259cdb)
我也是一样的情况，求解决方案
