### ISSUE TITLE
提个建议，可不可以让它每次对话都使用emoji呢，就比如在问题前加上use emoji之类字段

### ISSUE THREAD

**Issue by iknow2333** [zhayujie/chatgpt-on-wechat#379]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
配置在 single_chat_reply_prefix 试试看

**Comment by iknow2333** [comment]
> 配置在 single_chat_reply_prefix 试试看

是想让它发东西的时候带上emoji；像bing一样，不是用来区分机器人的，也许可以试试在每个问题后加上“使用emoji回答”？

**Comment by oreeke** [comment]
人格描述里添加，"character_desc": “"每句话里都有emoji”，效果如下
![微信图片_20230308024552](https://user-images.githubusercontent.com/22180904/223521879-0a24a3e6-4c90-426e-b774-4a0c27eb7796.jpg)
如果把"emoji"换成"表情"，它会发用符号构成的表情，类似~(●'◡'●)
