### ISSUE TITLE
群聊 时不支持图片生成、单聊才会画图

### ISSUE THREAD

**Issue by iostony** [zhayujie/chatgpt-on-wechat#380]
群聊 时不支持图片生成。单聊才会画图。

### 环境

 - 操作系统类型 Linux)：
 - Python版本  ( 执行 `python3 -V` )：    3.10                  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：3.10

**Comment by zhayujie** [comment]
群聊也是支持的，可以发一下日志等截图

**Comment by ssqtom** [comment]
群聊前端有个空格，去除就好了，如图：
<img width="589" alt="image" src="https://user-images.githubusercontent.com/28641782/224245192-cdf1b805-9b8b-4d03-8dd4-bc1eaa5049dc.png">

**Comment by iostony** [comment]
[按照上面的办法，还是无法在群聊中回复图片，只是以文字的方式回复。
