### ISSUE TITLE
登录后手机断网退出微信过24小时后pc端也会退出

### ISSUE THREAD

**Issue by sunzhuo** [zhayujie/chatgpt-on-wechat#381]
在win10下的python3.9版本中可以运行
希望能使用pc运行本库后登录微信，然后手机断网退出保留pc端登录状态，但是登录状态不能持续超过24小时。

**Comment by Gavincent1** [comment]
找一部旧手机一直登陆着

**Comment by Gavincent1** [comment]
> 在win10下的python3.9版本中可以运行 希望能使用pc运行本库后登录微信，然后手机断网退出保留pc端登录状态，但是登录状态不能持续超过24小时。

找一部旧手机一直登陆着

**Comment by sunzhuo** [comment]
问题是没有旧手机啊

**Comment by zhayujie** [comment]
微信的设定就是 手机退出其他端都下线

**Comment by HenMie** [comment]
> 问题是没有旧手机啊

如果你是安卓，可以用微信分身，一般主流系统都自带的。如果你已经开了微信分身，可以用第三方软件来分身，比如“小X分身”之类的（我自己用的是这个，效果还可以）
