### ISSUE TITLE
服务器是在纽约，微信输入@bot或bot结果不出来

### ISSUE THREAD

**Issue by albanana** [zhayujie/chatgpt-on-wechat#387]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 
服务器是自己搭的，IP显示在纽约。
微信按照规定后输入文字不出现结果

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

<img width="1432" alt="Screen Shot 2023-03-07 at 3 57 40 PM" src="https://user-images.githubusercontent.com/43054529/223359734-8ecc4b6a-5404-4ec0-9392-2197f7fc3f98.png">

### 环境

 - 操作系统类型  (Mac)：MAC
 - Python版本  ( 执行 `python3 -V` )：    3.9                  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.1.3

**Comment by reBiocoder** [comment]
微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353 ， 用的香港服务器搭建平台，给兄弟们做贡献了

**Comment by zhayujie** [comment]
问题是网络访问不了openai后台，你是国外服务器还是搭的代理？

如果用代理的话需要在 config.json的 proxy 配置一下端口

**Comment by albanana** [comment]
> 

搭的代理，代理客户端监听那块也配置了。不过我挂vpn上去以后，有时候登录不上chatGPT网站，显示Access denied 错误1020，不知道是不是这个问题。

**Comment by zhayujie** [comment]
> 录不上chatGPT网站，显示Access denied 错误1020，不知道是不是这个问题。

是的，网络没通

**Comment by Cdcjk** [comment]
> 微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353 ， 用的香港服务器搭建平台，给兄弟们做贡献了

#353是啥意思？求教

**Comment by reBiocoder** [comment]
ChatGPT-3.5 官方API被墙解决方案

**Comment by reBiocoder** [comment]
> > 微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：#353 ， 用的香港服务器搭建平台，给兄弟们做贡献了
> 
> #353是啥意思？求教

ChatGPT-3.5 官方API被墙解决方案
