### ISSUE TITLE
module 'openai.error' has no attribute 'Timeout'

### ISSUE THREAD

**Issue by yangbinmao** [zhayujie/chatgpt-on-wechat#389]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/44470220/223376224-c3f01d36-60d9-49d9-872b-19bb8280d226.png)

在linux中应该是在调用chatGtp的时候报错，在windows中无异常   这是什么原因喃。
### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by reBiocoder** [comment]
微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353 ， 用的香港服务器搭建平台，给兄弟们做贡献了

**Comment by zhayujie** [comment]
openai需要更新至 0.27.0

**Comment by yangbinmao** [comment]
确定了，是因为python版本过低的问题。已解决

**Comment by dqoobp** [comment]
你好！很想认识你，得到你的指导
