### ISSUE TITLE
微信Bot封号，以及gpt-3.5-turbo接口国内被墙解决方案

### ISSUE THREAD

**Issue by reBiocoder** [zhayujie/chatgpt-on-wechat#390]
### 问题
- 微信容易封号
- gpt3.5API国内被墙了，无法直接访问

### 前置条件
关注订阅号【AI守门员】

### 使用方法
在聊天框输入 api-key=openai秘钥（你的openai账号的秘钥），即可激活私人GPT3.5AI

### 如图
![image](https://user-images.githubusercontent.com/39401819/222918635-ffbcbead-8384-4f16-a08b-cd5e853bd371.png)

### 原理
UCCLOUD 香港服务器部署，给兄弟们做贡献了，直接用吧

**Comment by Tyler201609** [comment]
反映个使用情况：从周五晚上开始接入wechat，扔到250群里，不停地刷屏，回复问题，好歹运行过了周末，然后周一中午就被腾讯禁言了，一个月后才能申请解除。接着换个新号，一会功夫就就被限制发言了。当天再换小号，没个把小时就被禁止群聊和加好友了，只能单聊，到3.20止。但是在后台依然能看到它每个的群回复，只是都发不出去了。估计是它发言太频繁了，被检测到，至今没号可接了，唉，它空有一身本事无处施展啊~不知道wechaty那个pad协议的版本接入，会咋样

**Comment by reBiocoder** [comment]
> 3.20止。但是在后台依然能看到它每个的群回复，只是都发不出去了。估计是它发言太频繁了，被检测到，至今没号可接了，唉，它空有一身本事无处施展啊~不知道wechaty那个pad协议的版本接入，会咋样

微信检测很严重，我大号差点被封了， 别冒险

**Comment by Tyler201609** [comment]
申请那个padlocal的token，把它复制给谁啊？没找到设置处啊？
       wechaty-channel.py里
        # 使用PadLocal协议 比较稳定(免费web协议 os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = '127.0.0.1:8080')
     token = config.get('wechaty_puppet_service_token')
        os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token （这个token替换成申请的长串就行 了么？
        ）

**Comment by lkyuier** [comment]
gpt-3.5-turbo 是不是收费的？

**Comment by Tyler201609** [comment]
直接改成 gpt-3.5-turbo -0301，新模型， 能用

**Comment by Tyler201609** [comment]
> > 3.20止。但是在后台依然能看到它每个的群回复，只是都发不出去了。估计是它发言太频繁了，被检测到，至今没号可接了，唉，它空有一身本事无处施展啊~不知道wechaty那个pad协议的版本接入，会咋样
> 
> 微信检测很严重，我大号差点被封了， 别冒险

你用的哪个协议？padlocal还是wechat的

**Comment by reBiocoder** [comment]
> gpt-3.5-turbo 是不是收费的？

不收费，openai接口文档已经开放了啊， 这个仓库的大佬已经更新代码了， 你push最新代码看看

**Comment by lkyuier** [comment]
> > gpt-3.5-turbo 是不是收费的？
> 
> 不收费，openai接口文档已经开放了啊， 这个仓库的大佬已经更新代码了， 你pull最新代码看看

只要pull最新代码就可以嘛？token那些，还是用这个地址下的token? https://platform.openai.com/account/api-keys

**Comment by zhayujie** [comment]
兄弟，你在一个issue里广告我没意见，但不要每个问题都发哈，影响别人解决问题哦

**Comment by reBiocoder** [comment]
> > > gpt-3.5-turbo 是不是收费的？
> > 
> > 
> > 不收费，openai接口文档已经开放了啊， 这个仓库的大佬已经更新代码了， 你pull最新代码看看
> 
> 只要pull最新代码就可以嘛？token那些，还是用这个地址下的token? https://platform.openai.com/account/api-keys

国内服务器要开代理， 只能用hk服务器

**Comment by HenMie** [comment]
> > gpt-3.5-turbo 是不是收费的？
> 
> 不收费，openai接口文档已经开放了啊， 这个仓库的大佬已经更新代码了， 你pull最新代码看看

都收费的，只不过新账号都送$18额度，少量使用的话够用一段时间

**Comment by reBiocoder** [comment]
> 

是的，现在好像只有5$了

**Comment by knigth95** [comment]
现在hk云服务还顺畅吗，会不会时不时回传等待

**Comment by reBiocoder** [comment]
> 现在hk云服务还顺畅吗，会不会时不时回传等待

后台我做了一些优化，很流畅   没有报错。  你关注体验试试

**Comment by Kys10000** [comment]
这次 turbo 3.5 微信会墙吗？

**Comment by reBiocoder** [comment]
没有，使用体验良好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月13日(周一) 晚上11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 微信Bot封号，以及gpt-3.5-turbo接口国内被墙解决方案 (Issue #390)




 
这次 turbo 3.5 微信会墙吗？

**Comment by Kys10000** [comment]
请问~~这样搭载的情况，什么时候会掉线呢？比如我的Bot微信锁屏？或者Finalshell因为电脑锁屏关掉了之类的？会因为这些情况掉线吗？

**Comment by reBiocoder** [comment]
> 请问~~这样搭载的情况，什么时候会掉线呢？比如我的Bot微信锁屏？或者Finalshell因为电脑锁屏关掉了之类的？会因为这些情况掉线吗？

不会啊，部署在服务器上的，不是本机电脑

**Comment by Kys10000** [comment]
> > 请问~~这样搭载的情况，什么时候会掉线呢？比如我的Bot微信锁屏？或者Finalshell因为电脑锁屏关掉了之类的？会因为这些情况掉线吗？
> 
> 不会啊，部署在服务器上的，不是本机电脑

我搭了一个，结果2天就被微信警告违规了，请问，有什么办法可以不被封啊？

**Comment by HelloTooi** [comment]
本地服务器可以使用全局代理搭建GPT微信吗？如果可以请问可以去哪里参考啊

**Comment by aqpmzngldh** [comment]
> ### 问题
 gpt3.5内部API被墙了，无法直接访问
请问你这个问题怎么解决的，本地我可以开魔法访问，但是代码部署在服务器上没魔法了，我是国内云服务器，这该咋整
