### ISSUE TITLE
优化配置参数建议

### ISSUE THREAD

**Issue by lichengzhe** [zhayujie/chatgpt-on-wechat#392]
希望可以配置参数中增加几条
temperature = 0.65
session_clear = [ "#清除记忆“, "new", "clear"],
session_clear_all = [ "#清除所有记忆“, "newall", "clearall"],

如果能获得bot的名字，其实可以动态获取bot的名字作为清除会话的指令，这样就可以长按机器人，自动出来名字，发送就可以清空了，操作很方便。

**Comment by zhayujie** [comment]
很好的建议，计划更新
