### ISSUE TITLE
我在服务器上启动clash 并监听7890端口，但是发微信消息时连不上api 是什么原因呢？clash代理没开对吗？> ## 方案二

### ISSUE THREAD

**Issue by zoukun120** [zhayujie/chatgpt-on-wechat#394]
## 方案二 
[root@localhost chatgpt-on-wechat]# sudo ./clash-linux-amd64-v1.13.0
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:7890 
WARN[0012] [TCP] dial DIRECT 127.0.0.1:40299 --> api.openai.com:443 error: dial tcp4 199.16.156.71:443: i/o timeout 
WARN[0017] [TCP] dial DIRECT 127.0.0.1:40301 --> api.openai.com:443 error: dial tcp4 157.240.6.35:443: i/o timeout 
WARN[0022] [TCP] dial DIRECT 127.0.0.1:40303 --> api.openai.com:443 error: dial tcp4 199.16.156.71:443: i/o timeout

**Comment by Melonan** [comment]
export 一下https_proxy ? 
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
或者你需要手动切换clash节点

**Comment by li-aolong** [comment]
> 日志显示的是 DIRECT (直连)，代理没有生效

@zhayujie 那应该怎么设置呢，我export了之后也还是显示直连
