### ISSUE TITLE
消息成功接收不回复

### ISSUE THREAD

**Issue by jcguang** [zhayujie/chatgpt-on-wechat#396]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
大佬，消息成功接收不回复可能是什么原因
![image](https://user-images.githubusercontent.com/42328767/223492119-476b8c25-60d8-4839-936c-32dea1a18899.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
是不是网络不能访问 openai接口，参考#351

**Comment by jcguang** [comment]
感谢大佬，换了服务器问题解决了



贾晨光
***@***.***







                       
Original Email
                       
                     

Sender:"zhayujie"< ***@***.*** &gt;;

Sent Time:2023/3/8 1:14

To:"zhayujie/chatgpt-on-wechat"< ***@***.*** &gt;;

Cc recipient:"jcguang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [zhayujie/chatgpt-on-wechat] 消息成功接收不回复 (Issue #396)




 
是不是网络不能访问 openai接口，参考#351
