### ISSUE TITLE
登陆成功，接受不到消息

### ISSUE THREAD

**Issue by 2406450951** [zhayujie/chatgpt-on-wechat#399]
### 前置确认

可以访问openAI的接口。
一切正常。没有报错之类的

### 问题描述

> 
运行了一天一夜，今天发现不触发了，然后关掉cmd窗口重启了一下。还是不触发。
![image](https://user-images.githubusercontent.com/48074721/223590918-9fc055f7-847b-4fa8-9cad-047d60fa14bf.png)

![image](https://user-images.githubusercontent.com/48074721/223590586-124ff549-c580-4fc4-b6e9-361a172550fd.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows10 
 - Python版本  ( 执行 `python3 -V` )：3.9.7                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)： 21.2.3

**Comment by 2406450951** [comment]
这样就是被封号了么

**Comment by Chopain996** [comment]
我也出现了同样的问题
