### ISSUE TITLE
Group name white name list

### ISSUE THREAD

**Issue by chgy188** [zhayujie/chatgpt-on-wechat#4]
For http will send escaped char，&-&amp; So is Group nickname with those special chat, code cannot identify. 

Use group_name=html.escape(group_name) maybe good

**Comment by zhayujie** [comment]
I just tried, special symbols such as facial expressions can be successfully matched in the configuration on MacOS :)

<img width="823" alt="image" src="https://user-images.githubusercontent.com/26161723/208297707-f86df191-dbf6-4736-b2bd-d7ad0063ead4.png">

**Comment by chgy188** [comment]
You can try on windows with group name like this:
![image](https://user-images.githubusercontent.com/18696823/208303446-d00f841b-2fff-46b3-b335-652e7c4fe218.png)

**Comment by zhayujie** [comment]
OK, I'll  test this case on windows. By the way, for normal conditions, can you run successfully on windows？
