### ISSUE TITLE
超过24小时自动log out问题，以及如何更新的问题

### ISSUE THREAD

**Issue by jlynnc** [zhayujie/chatgpt-on-wechat#402]
两个小问题
1.超过24小时后会自动log out，我已经在家里闲置的ipad上登陆了微信，而且一直保持在线，但是还会发生log out
2.更新到最新版就是直接git clone就完事了，对吧？

**Comment by zhayujie** [comment]
1.考虑是网络不稳定，或者有在其他端登录？
2.是的

**Comment by jlynnc** [comment]
我再看一下我ipad上的设置，感谢回答
