### ISSUE TITLE
扫码时多次出现 Log in time out, reloading QR code.

### ISSUE THREAD

**Issue by Jeff-Hugh** [zhayujie/chatgpt-on-wechat#403]
### 问题描述

> 登录的时候需要扫码很多次，总是出现 Log in time out, reloading QR code. 手机端扫码后需要等待5秒，等待的时候二维码又刷新了。扫很多次才能成功登录。

### 环境

 - 操作系统类型  (Mac/Windows/Linux)： Linux
 - Python版本  ( 执行 `python3 -V` )：3.10.6
 -  - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：22.0.2

**Comment by 2406450951** [comment]
[Issue#8](https://github.com/zhayujie/chatgpt-on-wechat/issues/8)
看这个

**Comment by Jeff-Hugh** [comment]
> [Issue#8](https://github.com/zhayujie/chatgpt-on-wechat/issues/8) 看这个

谢谢，搞定。
