### ISSUE TITLE
没有生成QR.PNG文件

### ISSUE THREAD

**Issue by AndyHuyidi** [zhayujie/chatgpt-on-wechat#404]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

昨天用的时候还好好的，今天用时显示downloading QR code，但QR.PNG文件一直没出来
<img width="897" alt="image" src="https://user-images.githubusercontent.com/48292864/223646450-d8b849df-2f63-47ef-abf2-b453b44cfe51.png">

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
本地环境可以看下 https://github.com/zhayujie/chatgpt-on-wechat/issues/74 ，把二维码改成弹出试试

**Comment by AndyHuyidi** [comment]
看这里，https://github.com/zhayujie/chatgpt-on-wechat/issues/74#issuecomment-1460386233

**Comment by zhayujie** [comment]
正常应该是这样：
pip3 show itchat-uos # 依赖存在
pip3 show itchat # 依赖不存在

如果itchat在要把 itcaht 卸载掉， 只需要itchat-uos 依赖
