### ISSUE TITLE
运行第一步就报错了！

### ISSUE THREAD

**Issue by cntink** [zhayujie/chatgpt-on-wechat#405]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)  可以
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装   已经安装
3. 在已有 issue 中未搜索到类似问题   没有
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

运行python app.py报错，貌似编码错误，错误信息见日志；
config.json的配置如下：
```
{
  "open_ai_api_key": "sk-***********************",
  "proxy": "",
  "single_chat_prefix": ["bot", "@bot"],
  "group_chat_prefix": ["@bot"],
  "group_at_off": "true",
  "group_name_white_list": ["ChatGPT测试群", "ChatGPT测试群2"],
  "image_create_prefix": ["画", "看", "找"],
  "conversation_max_tokens": 1000,
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。",
  "expires_in_seconds": 3600
}
```

### 终端日志 (如有报错)

```
C:\Users\Administrator\Desktop\ChatGPT_WX\chatgpt-on-wechat>python app.py
[ERROR][2023-03-08 15:27:06][app.py:19] - App startup failed!
[ERROR][2023-03-08 15:27:06][app.py:20] - 'utf-8' codec can't decode byte 0xb2 in position 235: invalid start byte
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    config.load_config()
  File "C:\Users\Administrator\Desktop\ChatGPT_WX\chatgpt-on-wechat\config.py", line 11, in load_config
    config_str = read_file(config_path)
  File "C:\Users\Administrator\Desktop\ChatGPT_WX\chatgpt-on-wechat\config.py", line 18, in read_file
    return f.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 235: invalid start byte
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows 2012
 - Python版本  ( 执行 `python3 -V` )：3.8.10                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.1.1

**Comment by zhayujie** [comment]
修改config.json文件的时候改变了编码，换个编辑器试试

**Comment by jkjoy** [comment]
[ERROR][2023-03-11 15:06:56][app.py:19] - App startup failed!
[ERROR][2023-03-11 15:06:56][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

**Comment by zhayujie** [comment]
> [ERROR][2023-03-11 15:06:56][app.py:19] - App startup failed! [ERROR][2023-03-11 15:06:56][app.py:20] - list index out of range Traceback (most recent call last): File "app.py", line 17, in channel.startup() File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 60, in login status = self.check_login() File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 151, in check_login if process_login_info(self, r.text): File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 196, in process_login_info skey = re.findall('(.*?)', r.text, re.S)[0] IndexError: list index out of range

账号需要实名

**Comment by jkjoy** [comment]
> @jkjoy 群名称有配置吗，私聊带上触发前缀能回复不

群名称是按照文档改成all 私聊带上前缀也是不能回复
