### ISSUE TITLE
二维码分裂，登录后无效重复生成二维码

### ISSUE THREAD

**Issue by socekin** [zhayujie/chatgpt-on-wechat#41]
使用群晖docker部署的python3.9，运行app.py后，二维码是分裂的，想办法拼接扫码后，会重新生成新的二维码，如此往复。不知道有没有解决办法？谢谢

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/874961/216820026-e163bb6c-716c-4c76-b6b0-c2615b525029.png">

**Comment by zhayujie** [comment]
应该是超时重新生成二维码的问题， 看下这个 [issue](https://github.com/zhayujie/chatgpt-on-wechat/issues/8)，该一行代码试试

**Comment by socekin** [comment]
> 应该是超时重新生成二维码的问题， 看下这个 [issue](https://github.com/zhayujie/chatgpt-on-wechat/issues/8)，该一行代码试试

增加了，还是不行

**Comment by zhayujie** [comment]
> > 应该是超时重新生成二维码的问题， 看下这个 [issue](https://github.com/zhayujie/chatgpt-on-wechat/issues/8)，该一行代码试试
> 
> 增加了，还是不行

加下我帮你看看

**Comment by socekin** [comment]
> > > 应该是超时重新生成二维码的问题， 看下这个 [issue](https://github.com/zhayujie/chatgpt-on-wechat/issues/8)，该一行代码试试
> > 
> > 
> > 增加了，还是不行
> 
> 加下我帮你看看

刚好今天的版本更新了，试了一下最新的版本OK了，谢谢

**Comment by socekin** [comment]
新版本又出现了该问题，能否输出二维码的同时，输出二维码的链接，直接copy链接使用，二维码一直分裂，不太好扫码，谢谢

**Comment by zhayujie** [comment]
我没有更新二维码相关的代码，感觉和你的部署环境有关。 先加下我一起看看吧

**Comment by Jacky-Bruse** [comment]
> 我没有更新二维码相关的代码，感觉和你的部署环境有关。 先加下我一起看看吧

你好，大佬，我也是用nas的docker部署的，也是出现这样的问题，二维码错位

**Comment by zhayujie** [comment]
@socekin @Jacky-Bruse 

这个解决了吗， 通过打开保存下来的QR.png 可以吗

**Comment by Jacky-Bruse** [comment]
我发现是偶发的，多几次二维码就是正常的

**Comment by socekin** [comment]
> @socekin @Jacky-Bruse
> 
> 这个解决了吗， 通过打开保存下来的QR.png 可以吗

可以，保存下来的图片可以扫描，谢谢
