### ISSUE TITLE
今天的新版本，二维码出错

### ISSUE THREAD

**Issue by Martianxhc** [zhayujie/chatgpt-on-wechat#411]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
今天的新版本，能正常运行，但是出现的二维码变形了 特别宽。。无法扫码登陆

![Uploading 42ce17de86095269b87401f036df7c1.png…]()

### 终端日志 (如有报错)

```无
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Windows)：Windows 10
 - Python版本  ( 执行 `python3 -V` )：       3.19.3               
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by CXXHK** [comment]
可以尝试把chatgpt-on-wechat/channel/wechat/wechat_channel.py ，45行代码itchat.auto_login(enableCmdQR=2)改为，itchat.auto_login()，重新运行。
