### ISSUE TITLE
没有错误提示，windows无法登录微信

### ISSUE THREAD

**Issue by senryouun** [zhayujie/chatgpt-on-wechat#414]
### 问题描述
Python 3.9.2
安装过程无任何错误发生，windows10系统（debian系统也测试，同样问题），
登录微信时，正常扫了二维码，也无任何错误提示。

但是手机微信并没在顶部显示微信登录了，收发bot微信也无返回。
试了2个微信账号，都是这样。

**Comment by linxkon** [comment]
我也遇到了这个问题

**Comment by flywanyi** [comment]
我也是哎，没有Start auto replying打印

**Comment by zhayujie** [comment]
@flywanyi 手机有确认吗， 截下日志的图看看
