### ISSUE TITLE
KeyError: 'wxsid'报错 求解

### ISSUE THREAD

**Issue by Ricky-Ay** [zhayujie/chatgpt-on-wechat#416]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

KeyError: 'wxsid'
这个报错 请问下怎么解决 弄了好久没弄好

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
[ERROR][2023-03-09 22:48:26][app.py:19] - App startup failed!
[ERROR][2023-03-09 22:48:26][app.py:20] - 'wxsid'
Traceback (most recent call last):
  File "C:\Google\WeChat-GPT\chatgpt-on-wechat-1.0.5\app.py", line 17, in <module>
    channel.startup()
  File "C:\Google\WeChat-GPT\chatgpt-on-wechat-1.0.5\channel\wechat\wechat_channel.py", line 45, in startup
    itchat.auto_login()
  File "D:\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\lib\site-packages\itchat\components\login.py", line 56, in login
    status = self.check_login()
  File "D:\lib\site-packages\itchat\components\login.py", line 142, in check_login
    if process_login_info(self, r.text):
  File "D:\lib\site-packages\itchat\components\login.py", line 184, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

### 环境

 - 操作系统类型  (Windows)：
 - Python版本  ( 执行 `python3 -3.10` )：                      
 - pip版本  ( pip3)：

**Comment by zhayujie** [comment]
一般原因为使用了itchat且无法登录网页版微信，解决方法是先卸载itchat，然后安装itchat-uos 1.5.0.dev0版本。

**Comment by Ricky-Ay** [comment]
> 

解决了 谢谢 然后我想问下 群里艾特机器人不回复是为什么 私聊却可以

**Comment by ShowUNow** [comment]
@Ricky-Ay config.json里面的"group_chat_prefix"改为@<机器人的名字>
"group_name_white_list"改为ALL_GROUP

**Comment by Learn-py1988** [comment]
@Ricky-Ay 怎么解决的？我按照[zhayujie]的方法，还是报错KeyError: 'wxsid'

**Comment by ranpin** [comment]
> @Ricky-Ay 怎么解决的？我按照[zhayujie]的方法，还是报错KeyError: 'wxsid'

我也是，请问你解决了吗？

**Comment by EvansSec** [comment]
> 
同样的问题，请问是如何解决的呀

**Comment by wunuo1** [comment]
新微信号绑定一下银行卡，实名认证就可以了

**Comment by 1053574174** [comment]
大佬们，微信@机器人后回复ERROR是什么情况哇

**Comment by AlaricReed0** [comment]
要实名认证
