### ISSUE TITLE
API突然频繁被封

### ISSUE THREAD

**Issue by olafzhx666** [zhayujie/chatgpt-on-wechat#419]
# 已重新编辑到[423](https://github.com/zhayujie/chatgpt-on-wechat/issues/423)

### 是部署在新加坡的服务器上的

终端报
your access was terminated due to violation of our policies, please check your email for more information. if you believe this is in error and would like to appeal, please contact support@openai.com.

然后收到邮件
![266612525003c7b6e7613affdf9cb05](https://user-images.githubusercontent.com/122070985/224205883-ca525142-851f-4a59-8060-175098f80c09.png)

### 刚开始以为是偶发性事件，然后注册了个新号，然后用了不到一天，又寄了。。。

是官方开始限制微信的登录了吗？
用的itchat-uos

**Comment by niufox** [comment]
我的也被封了

**Comment by Ayuyyae** [comment]
大家用全局代理了吗？

**Comment by GZYZhy** [comment]
日本服务器部署，我的也被封了

**Comment by olafzhx666** [comment]
> 大家用全局代理了吗？

我挂在新加坡服务器上的不用走代理

**Comment by olafzhx666** [comment]
我又搞了个新的，看看能用多久吧。。。

**Comment by olafzhx666** [comment]
哦豁，新搞的用两小时又寄了。。。

**Comment by HenMie** [comment]
个人认为，你反复部署都寄了，可能是服务器IP的问题，你试试换一下服务器IP，或者加代理试试。我是国内服务器+clash部署的，一个月暂无问题。

**Comment by olafzhx666** [comment]
> 个人认为，你反复部署都寄了，可能是服务器IP的问题，你试试换一下服务器IP，或者加代理试试。我是国内服务器+clash部署的，一个月暂无问题。

确实有可能，我换个服务器试一试

**Comment by olafzhx666** [comment]
好吧，换了个服务器，布置完后上个厕所回来又被ban了。。。

**Comment by zhayujie** [comment]
这是被openAI限制了，可能的原因有：

+ 违反 OpenAI 使用条款
+ 在不支持的地区使用 (不包括HK)

使用条款：https://openai.com/policies/terms-of-use
支持的地区：https://platform.openai.com/docs/supported-countries

**Comment by iammpy** [comment]
我在同一台日本的服务器上，前两天部署的qq机器人用了几天都没事，今天试了一下这个项目，刚用几分钟api就被ban了。。

**Comment by HenMie** [comment]
> 好吧，换了个服务器，布置完后上个厕所回来又被ban了。。。

不清楚了，玄学。我是用机场的台湾节点的

**Comment by olafzhx666** [comment]
> 这是被openAI限制了 (封的ip)，可能的原因有：
> 
> * 违反 OpenAI 使用条款
> * 在不支持的地区使用
> 
> 使用条款：https://openai.com/policies/terms-of-use 支持的地区：https://platform.openai.com/docs/supported-countries

那如果这样的话，在服务器上使用代理服务能解决问题吗，但我也更换过服务器，新服务器是如何触发它的封禁机制的呢

**Comment by FFFFourwood** [comment]
+1

**Comment by zhayujie** [comment]
目前 tx 广州CVM + AU地区的trojan daili， 用了一天暂时正常， 看看情况

**Comment by jlynnc** [comment]
腾讯云硅谷节点，运行2周，没被封

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227758340-ad0d57ff-b430-4162-a434-8816ed9936e9.png)

**Comment by dee1024** [comment]
> 个人认为，你反复部署都寄了，可能是服务器IP的问题，你试试换一下服务器IP，或者加代理试试。我是国内服务器+clash部署的，一个月暂无问题。

是不是用了VPN就没事？
