### ISSUE TITLE
API突然频繁被封（原#419）

### ISSUE THREAD

**Issue by olafzhx666** [zhayujie/chatgpt-on-wechat#423]
## 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
5. 所使用服务器有 腾讯轻量云新加坡 和 rackned纽约

## 问题描述

API被封，之前都能正常使用，收到如下邮件
![image](https://user-images.githubusercontent.com/122070985/224244529-4eed0308-694e-47f8-bc1d-3dd5ededd16c.png)

刚开始以为是偶发性事件，遂重新注册了openai账户并且尝试更换服务器，但问题仍存在，具体见下文

### 第一次尝试
重新注册了openai，在腾讯轻量云上重新布置，被封

### 第二次尝试
重新注册了，在rackned纽约上首次布置，被封

### 第三次尝试
经过提醒，可能是ip被封，从注册开始就更换梯子节点，在腾讯轻量云上重新布置，被封

### [帖子一](https://twitter.com/Cydiar404/status/1634036689986523137?s=05)
![1678431460423](https://user-images.githubusercontent.com/122070985/224245544-cdb6a432-5aff-4073-af2c-0dee4460ee36.png)

### [帖子二](https://51.ruyo.net/18313.html)
帖子二的评论区中看起来，似乎和所使用的服务器也有关系（暂不确定）
帖子二提到要避免使用公共反代接口服务，非专业人员，不太懂本项目是如何运行的

**Comment by yxn4065** [comment]
![image](https://user-images.githubusercontent.com/76934061/224252346-0d33768f-7c4f-4c3f-a9d5-bda2f4980231.png)
没了

**Comment by kdyzm** [comment]
有后续了吗

**Comment by ShawnSheno** [comment]
被封+1
腾讯云香港轻量服务器
重新注册继续被封

**Comment by olafzhx666** [comment]
### 2023.3.11第一次更新
尝试更换机场节点重新注册账号，没调用api，被ban
尝试使用自建的vpn服务重新注册账号，没调用api，被ban

目前看来，检测机制十分严格，如果说后几次被ban是同一ip多次注册触发的话，那么第一次被ban就挺没有理由的。。。
尚不清楚到底是怎么触发到了它的封禁机制

**Comment by olafzhx666** [comment]
> ### 2023.3.11第一次更新
> #### 尝试更换机场节点重新注册账号，没调用api，被ban
> #### 尝试使用自建的vpn服务重新注册账号，没调用api，被ban
> 目前看来，检测机制十分严格，如果说后几次被ban是同一ip多次注册触发的话，那么第一次被ban就挺没有理由的。。。 尚不清楚到底是怎么触发到了它的封禁机制

之前都用谷歌浏览器弄的，上面登陆了我的谷歌账号，但每次弄之前都会清cookie，今天换了火狐试了下，网页端可以正常使用了，但还没有试过api

**Comment by olafzhx666** [comment]
> > ### 2023.3.11第一次更新
> > #### 尝试更换机场节点重新注册账号，没调用api，被ban
> > #### 尝试使用自建的vpn服务重新注册账号，没调用api，被ban
> > 目前看来，检测机制十分严格，如果说后几次被ban是同一ip多次注册触发的话，那么第一次被ban就挺没有理由的。。。 尚不清楚到底是怎么触发到了它的封禁机制
> 
> 之前都用谷歌浏览器弄的，上面登陆了我的谷歌账号，但每次弄之前都会清cookie，今天换了火狐试了下，网页端可以正常使用了，但还没有试过api

没用api挂这个项目，就用网页端稳定使用了一下午，刚刚挂这个项目又被ban了。。。

**Comment by fattank** [comment]
服务器换到洛杉矶的搬瓦工试试呢？

**Comment by GZYZhy** [comment]
## 查阅官方文档零星得到一些信息，分享一下：
> OpenAI可以通过多种方式来检测和识别批量注册的账号，例如：
>······
>2. 注册信息：OpenAI可以检查账户的注册信息，例如注册时间、注册的电子邮件地址、用户名、IP地址等。如果OpenAI检测到大量的相似或相同的注册信息，可能会认为这是批量注册。
>3. 行为模式：OpenAI可以检测到账户的行为模式。如果OpenAI检测到一些账户进行了大量的相似或相同的操作，例如请求API、创建模型等，可能会认为这是自动化软件或脚本生成的。
>······
## 个人见解，仅供参考：
在多次更换服务器和IP地址，清除cookie，换云厂商，换地域，尝试各种梯子等均被秒封的情况下， 我  ~哭的有点想笑了~  得出一些猜测：
### 针对2:
淘宝10元15元那种批量注册的账号/送微软和谷歌账号的那种账号应该不行了，自己邮箱买虚拟手机号的应该也悬。~结果没账号用了~
### 针对3:
有可能本项目很多人被封的原因是前期一些人用那种批量账号的API部署或者访问量很大，甚至不配置代理直接国内访问，结果openai把本项目的调用方式或者某种调用特征识别了，可能需要变换一下请求方式什么的，但是仍有人成功稳定运行，说明这些被识别的特征可能不明显（？）或者导致被ban的是其他玄学问题。

现在openai暂停了注册，应该就是被大量滥用了，下一步要严厉清理这些所谓“滥用”的账号，所以换账号可能不解决问题，还得封。这些账户好像都只是封了API访问权限而不是彻底封号，所以我觉得如果被封之后历尽九九八十一难成功申诉解封  ~(或者换个号发挥钞能力付费使用）要钱没有，要命一条~  ，可能情况会不一样。解封要提供一些难搞的证据：
> 如果您的OpenAI账号被判定为批量注册，API密钥会被封禁，此时您可以按照以下步骤来解封：
>······
>3. 提供证明：为了证明您的账号是真实的，您需要提供一些证据。例如，可以提供您的个人身份证件、公司名片、相关的工作文件或其他证明文件。证明文件可以帮助OpenAI确认您的身份，并且您的账号并非用于批量注册。
>······

简单来讲：证明你真的是个人且真的是自己在用账户，API请求是你这个人发出的。当然这些得是外国的，甚至为了增强可信度还得是部署IP所在地/账户注册电话所在地的，跟账户姓名一致的，公司知名度高点的，熬夜等IP所在地的工作时间发邮件等等。
~几乎不可能~  真是太难了（且：伪造某些东西游走在法律边缘，要做守法好公民）。哪位大神尝试一下成功了出个攻略啥的。
### 以上胡诹各位看看就好，很可能不对，仅供参考，不负责嗷。

**Comment by GZYZhy** [comment]
已知测试:使用本项目上游1.0.2版本，配合未被封禁的API密钥，调用到“GPT-2”(它自己说的)，不会被秒封，已稳定运行1天多。缺点:无法使用后续更新中的修正和新功能，比GPT3.5笨一些。建议作者大大在新版本调用方式中增加1.0.2旧版调用作为可配置的可选项，让我们这些被封党先运行上。

**Comment by olafzhx666** [comment]
> 

暂时没钱去买新服务器了（

**Comment by olafzhx666** [comment]
> 服务器换到洛杉矶的搬瓦工试试呢？

暂时没钱买新服务器了（

**Comment by olafzhx666** [comment]
> 已知测试:使用本项目上游1.0.2版本，配合未被封禁的API密钥，调用到“GPT-2”(它自己说的)，不会被秒封，已稳定运行1天多。缺点:无法使用后续更新中的修正和新功能，比GPT3.5笨一些。建议作者大大在新版本调用方式中增加1.0.2旧版调用作为可配置的可选项，让我们这些被封党先运行上。

其实本身如果需求不高，只是想有一个“便捷便携的智能机器人”（至少我是这样）的话，可以看下tg的机器人，参考下这个[项目](https://github.com/karfly/chatgpt_telegram_bot)，我甚至懒得弄就用了作者部署的机器人。

**Comment by olafzhx666** [comment]
> ## 查阅官方文档零星得到一些信息，分享一下：
> > OpenAI可以通过多种方式来检测和识别批量注册的账号，例如：
> > ······
> > 2. 注册信息：OpenAI可以检查账户的注册信息，例如注册时间、注册的电子邮件地址、用户名、IP地址等。如果OpenAI检测到大量的相似或相同的注册信息，可能会认为这是批量注册。
> > 3. 行为模式：OpenAI可以检测到账户的行为模式。如果OpenAI检测到一些账户进行了大量的相似或相同的操作，例如请求API、创建模型等，可能会认为这是自动化软件或脚本生成的。
> > ······
> 
> ## 个人见解，仅供参考：
> 在多次更换服务器和IP地址，清除cookie，换云厂商，换地域，尝试各种梯子等均被秒封的情况下， 我 ~哭的有点想笑了~ 得出一些猜测：
> 
> ### 针对2:
> 淘宝10元15元那种批量注册的账号/送微软和谷歌账号的那种账号应该不行了，自己邮箱买虚拟手机号的应该也悬。~结果没账号用了~
> 
> ### 针对3:
> 有可能本项目很多人被封的原因是前期一些人用那种批量账号的API部署或者访问量很大，甚至不配置代理直接国内访问，结果openai把本项目的调用方式或者某种调用特征识别了，可能需要变换一下请求方式什么的，但是仍有人成功稳定运行，说明这些被识别的特征可能不明显（？）或者导致被ban的是其他玄学问题。
> 
> ### 封号和解封
> 现在openai暂停了注册，应该就是被大量滥用了，下一步要严厉清理这些所谓“滥用”的账号，所以换账号可能不解决问题，还得封。这些账户好像都只是封了API访问权限而不是彻底封号，所以我觉得如果被封之后历尽九九八十一难成功申诉解封 ~(或者换个号发挥钞能力付费使用，它居然还不接受银联卡）要钱没有，要命一条~ ，可能情况会不一样。解封要提供一些难搞的证据：
> 
> > 如果您的OpenAI账号被判定为批量注册，API密钥会被封禁，此时您可以按照以下步骤来解封：
> > ······
> > 3. 提供证明：为了证明您的账号是真实的，您需要提供一些证据。例如，可以提供您的个人身份证件、公司名片、相关的工作文件或其他证明文件。证明文件可以帮助OpenAI确认您的身份，并且您的账号并非用于批量注册。
> > ······
> 
> 简单来讲：证明你真的是个人且真的是自己在用账户，API请求是你这个人发出的。当然这些得是外国的，甚至为了增强可信度还得是部署IP所在地/账户注册电话所在地的，跟账户姓名一致的，公司知名度高点的，熬夜等IP所在地的工作时间发邮件等等。 ~几乎不可能~ 真是太难了（且：伪造某些东西游走在法律边缘，要做守法好公民）。哪位大神尝试一下成功了出个攻略啥的。
> 
> ### 以上胡诹各位看看就好，很可能不对，仅供参考，不负责嗷。

笑死，我拿可以用的bot让它写了封解封邮件，官方甚至没回我。这样看来的话，确实是误判被AOE到了，不过本身严格来说也确实是不支持的地区，申诉可能确实有点难。等之后有空了去找几个国外的朋友拿他们的账号试试水吧，不过现在都暂停注册了那应该是要开始大清洗了，等风头过了再看看吧（累）
感觉确实虚拟手机号注册之后会比较的难了，我之前注册的时候就出现过好多次号码被检测可疑的情况。

**Comment by kdyzm** [comment]
> 被封+1 腾讯云香港轻量服务器 重新注册继续被封

香港本来就不在支持的区域列表里啊，香港和中国大陆都不行

**Comment by ShawnSheno** [comment]
有没有小伙伴试过，付费使用api还会被封吗？

**Comment by ShawnSheno** [comment]
> > 被封+1 腾讯云香港轻量服务器 重新注册继续被封
> 
> 香港本来就不在支持的区域列表里啊，香港和中国大陆都不行

后来换成新加坡服务器，还是秒封

**Comment by zhayujie** [comment]
目前用的 tx云CVM服务器， australia 的trojan代理， 试了一天暂时没封

**Comment by ShawnSheno** [comment]
亲测，换了亚马逊云海外服务器，运行半天了，暂时没封。
在网上看到说，可能有些代理、服务器不是gpt区域内的ip，可能导致被封

**Comment by twosix26** [comment]
因为开会的原因，这几天梯子被墙了，今天更新了梯子之后也被封了

**Comment by ShawnSheno** [comment]
API被封解决方案更新，亲测有效，已正常运行2天

一般是服务器ip不在OpenAI服务区域，比较好解决。国内有些云厂商海外服务器也不太行。
换成亚马逊云海外服务器即可。见https://www.pmssw.com/44.html

**Comment by MysteryGuest-b** [comment]
我的账号之前一直使用正常，前两天chrome安装了一个 ChatGPT for Google 的插件需要使用api。我申请了一个api key，在chrome上调用过几次，可能当时调用使用的是香港的线路，于是就被封了🤷‍♀️。
我的账号是使用QQ邮箱自己申请的，于是我用这个QQ邮箱向<support@openai.com>发送了一封申诉邮件，两天过去了，一直也没有回应，账号还是封禁状态。

**Comment by kurpaikt** [comment]
> 我的账号之前一直使用正常，前两天chrome安装了一个 ChatGPT for Google 的插件需要使用api。我申请了一个api key，在chrome上调用过几次，可能当时调用使用的是香港的线路，于是就被封了🤷‍♀️。 我的账号是使用QQ邮箱自己申请的，于是我用这个QQ邮箱向[support@openai.com](mailto:support@openai.com)发送了一封申诉邮件，两天过去了，一直也没有回应，账号还是封禁状态。

兄弟我也是这样的情况，昨天下的那个插件，今天就收到邮件被封号，直接账号封禁不只是api被限制，我直接醉了。一样也是用的香港线路，qq邮箱和一样的插件。

**Comment by MysteryGuest-b** [comment]
> 
想办法找回账号吧，有进展互相同步🤝

**Comment by MysteryGuest-b** [comment]
> > 我的账号之前一直使用正常，前两天chrome安装了一个 ChatGPT for Google 的插件需要使用api。我申请了一个api key，在chrome上调用过几次，可能当时调用使用的是香港的线路，于是就被封了🤷‍♀️。 我的账号是使用QQ邮箱自己申请的，于是我用这个QQ邮箱向[support@openai.com](mailto:support@openai.com)发送了一封申诉邮件，两天过去了，一直也没有回应，账号还是封禁状态。
> 
> 兄弟我也是这样的情况，昨天下的那个插件，今天就收到邮件被封号，直接账号封禁不只是api被限制，我直接醉了。一样也是用的香港线路，qq邮箱和一样的插件。

想办法找回账号吧，有进展互相同步🤝

**Comment by mushanzi1216** [comment]
请问发申诉邮件的话是哪个邮箱呢

**Comment by kurpaikt** [comment]
> 

付费也被封，应该是一视同仁，付费免费都按照同一套风控及权重。我的PLUS才充了一天不够就被封了，就因为装了个插件调用过api，气死了。

**Comment by xiaokai0203** [comment]
谁微信有交流群,拉个讨论组呗

**Comment by xiaokai0203** [comment]
我本地挂了马来西亚的梯子, 一访问就被封,都没挂服务器上

**Comment by ShawnSheno** [comment]
我开了个交流群，可以一起讨论下经验。
<img width="268" alt="image" src="https://user-images.githubusercontent.com/34580770/225825978-4aaf23c5-4727-4201-917c-03e849e38fa6.png">

**Comment by cavalrica** [comment]
> 我的账号之前一直使用正常，前两天chrome安装了一个 ChatGPT for Google 的插件需要使用api。我申请了一个api key，在chrome上调用过几次，可能当时调用使用的是香港的线路，于是就被封了🤷‍♀️。 我的账号是使用QQ邮箱自己申请的，于是我用这个QQ邮箱向[support@openai.com](mailto:support@openai.com)发送了一封申诉邮件，两天过去了，一直也没有回应，账号还是封禁状态。

+1，看来那个插件有问题，之前无论是官网登还是web版调用API用了n久都没事，插件用了一天直接被ban

**Comment by cavalrica** [comment]
> > 
> 
> 付费也被封，应该是一视同仁，付费免费都按照同一套风控及权重。我的PLUS才充了一天不够就被封了，就因为装了个插件调用过api，气死了。

看来这个插件有问题，不会是钓鱼插件吧，怪不得这么好用....

**Comment by VanJiaEmo** [comment]
我服了啊，我前后花了两百多开了个虚拟银行卡，才好不容易开通了PLUS，前后5分钟，我刚问了4.0两个问题，他就给我封了，不只是API啊，账号直接被封了

**Comment by tietou6666** [comment]
腾讯云新加坡节点. 秒封. 试了三个号都秒封.  今天才出现的.

**Comment by guaobai** [comment]
![image](https://user-images.githubusercontent.com/49296770/226517138-071ad69f-6808-4b6c-8bd7-633bcb1e4e15.png)上面群满了 建了一个

**Comment by ShawnSheno** [comment]
> ![image](https://user-images.githubusercontent.com/49296770/226517138-071ad69f-6808-4b6c-8bd7-633bcb1e4e15.png)上面群满了 建了一个

群那里满了？大哥，你要引流就引流，别拿正经交流群搞事情啊。

**Comment by guaobai** [comment]
> > ![图像](https://user-images.githubusercontent.com/49296770/226517138-071ad69f-6808-4b6c-8bd7-633bcb1e4e15.png)上面群满了建了一个
> 
> 群那里满了？大哥，你要引流就引流，别拿正经交流群搞事情啊。

满200人了 你自己都说了 哎。。。你说引流就引流吧 你是大哥

**Comment by Ansle2015** [comment]
怎么解封吖？chatgpt被封了，在chatgpt for google里调用了API。

**Comment by kvenLin** [comment]
> 怎么解封吖？chatgpt被封了，在chatgpt for google里调用了API。

我也是

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![WechatIMG1115](https://user-images.githubusercontent.com/50973253/227758116-1befa673-2fa7-4d82-a993-779e1b26d832.jpeg)

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227758262-8fa4b1d4-d544-40d3-b274-824ce5436795.png)

**Comment by 416207298** [comment]
我也是网页一直用的好好的，一用vscode上的chatgpt插件，调用了api立马就被封了。

**Comment by myrisc** [comment]
被封是什么提示？我上个星期注册的账号没问题，用的美国vps，接码用的波兰的，然后网页也能进去，昨天开始登陆就提示不支持的国家，还是一样的vps，用脚本检测ip没问题，这算封号吗

**Comment by 416207298** [comment]
> 被封是什么提示？我上个星期注册的账号没问题，用的美国vps，接码用的波兰的，然后网页也能进去，昨天开始登陆就提示不支持的国家，还是一样的vps，用脚本检测ip没问题，这算封号吗

收到了一封标题为“OpenAI API - Access Terminated”的邮件，账号无法登录，网页的也进不去。

**Comment by myrisc** [comment]
> > 被封是什么提示？我上个星期注册的账号没问题，用的美国vps，接码用的波兰的，然后网页也能进去，昨天开始登陆就提示不支持的国家，还是一样的vps，用脚本检测ip没问题，这算封号吗
> 
> 收到了一封标题为“OpenAI API - Access Terminated”的邮件，账号无法登录，网页的也进不去。

我倒是没收到邮件，就是登陆一直unsupported_country，搞的一头雾水，新买的vps，两天前还能登陆还能注册，昨天开始就不行了，也不知道哪里的问题

**Comment by 416207298** [comment]
> > > 被封是什么提示？我上个星期注册的账号没问题，用的美国vps，接码用的波兰的，然后网页也能进去，昨天开始登陆就提示不支持的国家，还是一样的vps，用脚本检测ip没问题，这算封号吗
> > 
> > 
> > 收到了一封标题为“OpenAI API - Access Terminated”的邮件，账号无法登录，网页的也进不去。
> 
> 我倒是没收到邮件，就是登陆一直unsupported_country，搞的一头雾水，新买的vps，两天前还能登陆还能注册，昨天开始就不行了，也不知道哪里的问题

这个错误是梯子节点不对，换节点试试。

**Comment by myrisc** [comment]
> > > > 被封是什么提示？我上个星期注册的账号没问题，用的美国vps，接码用的波兰的，然后网页也能进去，昨天开始登陆就提示不支持的国家，还是一样的vps，用脚本检测ip没问题，这算封号吗
> > > 
> > > 
> > > 收到了一封标题为“OpenAI API - Access Terminated”的邮件，账号无法登录，网页的也进不去。
> > 
> > 
> > 我倒是没收到邮件，就是登陆一直unsupported_country，搞的一头雾水，新买的vps，两天前还能登陆还能注册，昨天开始就不行了，也不知道哪里的问题
> 
> 这个错误是梯子节点不对，换节点试试。

自建的节点，买的美国vps，ip也是绿的，用这个注册的头几天，当时也能登陆网页，都没问题，昨天开始就不成了，刚才脚本检测这个ip还是绿的也没问题，所有的openai的相关分流域名也写规则里了，也试了全局，开了无痕都没用

**Comment by 416207298** [comment]
openAI的封禁规则也是很迷，至今还没找到啥规律。。

**Comment by roryye** [comment]
> 搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者： ![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227758262-8fa4b1d4-d544-40d3-b274-824ce5436795.png)

失效了

**Comment by Wetiqe** [comment]
> 被封+1 腾讯云香港轻量服务器 重新注册继续被封

香港在openai那里和大陆算在一起的，也是被限制的地区，你这个IP就违规了，换个国外的服务器再搞吧

**Comment by dfldylan** [comment]
套个cloudflare的warp试试？

**Comment by li-Coulson** [comment]
> 腾讯云新加坡节点. 秒封. 试了三个号都秒封. 今天才出现的.
兄弟我也一样，买了个新加坡的服务器，还以为是我安装了 v2ray的问题
