### ISSUE TITLE
为什么回复问题有时候会有奇怪的信息在尾部

### ISSUE THREAD

**Issue by LeonLee888** [zhayujie/chatgpt-on-wechat#428]
偶尔回复会带这个信息在回答的最后：![chatgpt-product-demo](https://raw.githubusercontent.com/tylerharter/cs320/master/s21/p5/chatgpt-product-demo.png)

**Comment by zhayujie** [comment]
截图挂了

**Comment by LeonLee888** [comment]
没截图，就是有个信息在尾巴 ‘ ![chatgpt-product-demo](https://raw.githubusercontent.com/tylerharter/cs320/master/s21/p5/chatgpt-product-demo.pn    g)  ’
