### ISSUE TITLE
好吧，换了个服务器，布置完后上个厕所回来又被ban了。。。

### ISSUE THREAD

**Issue by Lxb921006** [zhayujie/chatgpt-on-wechat#429]
好吧，换了个服务器，布置完后上个厕所回来又被ban了。。。

_Originally posted by @olafzhx666 in https://github.com/zhayujie/chatgpt-on-wechat/issues/419#issuecomment-1463283145_
            你这也太惨了!

**Comment by frankchn-x** [comment]
你用的什么机器人

**Comment by hellokeki** [comment]
牛啊，比我还快，我是去楼下吃个饭回来就 ban了
