### ISSUE TITLE
发送成功，无回复

### ISSUE THREAD

**Issue by sonnyHen** [zhayujie/chatgpt-on-wechat#430]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

发送成功，日志能看到提问，但是一直无回复

[INFO][2023-03-10 23:14:26][chat_gpt_bot.py:26] - [OPEN_AI] query=你好，你叫什么

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：MacPython 3.9.6
 - Python版本  ( 执行 `python3 -V` )：Python 3.9.6                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.2.4

**Comment by frankchn-x** [comment]
兄弟，你配的什么机器人是itchat还是wechaty

**Comment by sonnyHen** [comment]
> 

itchat

**Comment by sonnyHen** [comment]
itchat
