### ISSUE TITLE
建议：流式输出支持

### ISSUE THREAD

**Issue by HenMie** [zhayujie/chatgpt-on-wechat#431]
微信无法做到逐字输出，但可以实现每句输出的效果（以“。”划分即可），支持流式输出的话可以大幅减少等待时间，提升使用体验。

如“aaaaa。bbbbb。ccccc。ddddd。”
可拆分为“aaaaa。”，“bbbbb。”，“ccccc。”，“ddddd。”四句逐一输出。

**Comment by samqin123** [comment]
解决方案是啥？closed掉后到哪里知道解决的内容？
