### ISSUE TITLE
谷歌文本转语音问题

### ISSUE THREAD

**Issue by Martianxhc** [zhayujie/chatgpt-on-wechat#433]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

切换成谷歌的语音是在哪里更改呢？

另外谷歌的不需要填写API吗？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：            3.9.13        
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Martianxhc** [comment]
找到了bridge里修改，但是使用谷歌语音，IOS设备无法接收语音消息，后台记录正常；百度和安卓没测过
有知道的来说说

**Comment by shuodehaoa** [comment]
我用安卓设备+百度语音，可以正常接收和发送语音消息，但是没能合成英文语音；
用安卓设备+谷歌语音，遇到了和你一样的问题，后台记录正常，但是终端收不到语音消息。

**Comment by Chiaki-Chan** [comment]
Google生成的语音似乎是格式有异，合成最终发送的格式卡住了，还需要进一步排查和优化。
