### ISSUE TITLE
运行2天就挂了

### ISSUE THREAD

**Issue by baichisong** [zhayujie/chatgpt-on-wechat#435]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
![b64577947d1d684e5ac892743d9438c](https://user-images.githubusercontent.com/8436305/224463458-298ed744-d187-4f6a-ad01-2a1b6980e694.png)

### 环境

 - 操作系统类型  (/Windows/)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by baichisong** [comment]
我是没用nohup启动的

**Comment by goldfishh** [comment]
话说itchat最多支持多久登录状态

**Comment by pm0725** [comment]
我也是2天前挂的，目前还稳定

**Comment by zhayujie** [comment]
可能原因：
1.手机端下线
2.其他端登录
3.网络不稳定

**Comment by Martianxhc** [comment]
> 可能原因： 1.手机端下线 2.其他端登录 3.网络不稳定

我今天也发现了这个问题，tail -f nohup.out，只显示了一部分日志，最后LOG OUT，但实际上机器人还在运行

**Comment by Martianxhc** [comment]
root@ecs-f3be:~/chatgpt-on-wechat# tail -f nohup.out
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 145, in _do_send_voice
    reply_text = super().build_reply_content(query, context)
  File "/root/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt-on-wechat/bridge/bridge.py", line 10, in fetch_reply_content
    return bot_factory.create_bot("chatGPT").reply(query, context)
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 27, in reply
    session_id = context['session_id']
KeyError: 'session_id'
LOG OUT!

**Comment by zhayujie** [comment]
@Martianxhc 这个问题只会在发送语音时出现，昨天已经修复了，获取下最新的代码就好了

**Comment by Martianxhc** [comment]
> @Martianxhc 这个问题只会在发送语音时出现，昨天已经修复了，获取下最新的代码就好了

好的 谢谢大哥！

**Comment by baichisong** [comment]
同问，今天一天就挂了！是因为我手机微信关机造成的吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月11日 12:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] 运行2天就挂了 (Issue #435) |

话说itchat最多支持多久登录状态

**Comment by Melonan** [comment]
一样的问题，每两天得重启重新登录一次，并无其他端登陆的情况

**Comment by nodesire7** [comment]
一样的问题，已经好几次了，每次登录差不多一天就掉线了

**Comment by zhayujie** [comment]
这个问题是因为目前itchat 和wx建立连接时， 如果5s没有网络，就会自动掉线。

@lanvent 在 https://github.com/zhayujie/chatgpt-on-wechat/pull/587 中修复了这个问题， 可以观察下有没有解决
