### ISSUE TITLE
最新更换的wechaty报错

### ISSUE THREAD

**Issue by frankchn-x** [zhayujie/chatgpt-on-wechat#436]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/124376835/224467158-775d23ae-ad8b-411a-9e26-56a0a18249c3.png">

**Comment by frankchn-x** [comment]
@ZQ7 老哥，有空来看看么

**Comment by Martianxhc** [comment]
虽然我不知道怎么解决这个错误

但是听说，wechaty貌似容易被封号

**Comment by frankchn-x** [comment]
> 虽然我不知道怎么解决这个错误
> 
> 但是听说，wechaty貌似容易被封号

itchat容易呗封号
