### ISSUE TITLE
API提示错误

### ISSUE THREAD

**Issue by wwyyff123** [zhayujie/chatgpt-on-wechat#438]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
API提示错误
![Snipaste_2023-03-11_14-18-39](https://user-images.githubusercontent.com/32731927/224468608-11253508-92fb-474d-868b-7a1e2f6e0d43.png)
但是API是从openai官网复制的，config.json里面也填了

### 终端日志 (如有报错)

```
Login successfully as Mmmmmmm。
Start auto replying.
[INFO][2023-03-11 14:14:15][chat_gpt_bot.py:26] - [OPEN_AI] query=写一篇小说
[ERROR][2023-03-11 14:14:15][chat_gpt_bot.py:96] - Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys.
Traceback (most recent call last):
  File "D:\chaty\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 63, in reply_text
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys.
[INFO][2023-03-11 14:14:16][wechat_channel.py:137] - [WX] sendMsg=@Ervan 请再问我一次吧, receiver=@@11f1840886def37caecfb0723ad4f9f272307a7e4a824844693ee48e1b67509b
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
打开 config.json 文件看下里面的 api_key 配置是不是没填

**Comment by zhayujie** [comment]
在当前目录下输入 cat config.json 可以看到 a'p'i

**Comment by three-tech** [comment]
Incorrect API key provided: sk-x1f0U***************************************Iys9. You can find your API key at https://platform.openai.com/account/api-keys.
Traceback (most recent call last):
  File "/root/app/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 68, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/python3/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/python3/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/python3/lib/python3.8/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/python3/lib/python3.8/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: sk-x1f0U***************************************Iys9. You can find your API key at https://platform.openai.com/account/api-keys.

apikey明明是正确的，他说不对，换了好几个了，不知道啥问题

**Comment by glsilover** [comment]
各位朋友，看看是不是把key写到config-template.json这里了。我也是遇到这个问题，最后发现一直在修改config-template.json，应该是修改config.json

**Comment by huiguangx** [comment]
> 有没有填写

哥们 你的解决了吗

**Comment by huiguangx** [comment]
> Incorrect API key provided: sk-x1f0U*****Iys9. You can find your API key at https://platform.openai.com/account/api-keys. Traceback (most recent call last): File "/root/app/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 68, in reply_text response = openai.ChatCompletion.create( File "/usr/local/python3/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create return super().create(_args, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File "/usr/local/python3/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) File "/usr/local/python3/lib/python3.8/site-packages/openai/api_requestor.py", line 619, in _interpret_response self._interpret_response_line( File "/usr/local/python3/lib/python3.8/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line raise self.handle_error_response( openai.error.AuthenticationError: Incorrect API key provided: sk-x1f0U**_**Iys9. You can find your API key at https://platform.openai.com/account/api-keys.
> 
> apikey明明是正确的，他说不对，换了好几个了，不知道啥问题

哥们 你的当时有解决吗

**Comment by Wanghh666** [comment]
> as
大佬你的处理了嘛？
我的也是的一模一样的情况，正确的api，却一直显示是错误的
