### ISSUE TITLE
关于微信机器人封号以及penai接口国内被墙的解决方案

### ISSUE THREAD

**Issue by reBiocoder** [zhayujie/chatgpt-on-wechat#439]
### 问题
- 微信容易封号
- gpt3.5API国内被墙了，无法直接访问

### 前置条件
关注订阅号【AI守门员】

### 使用方法
在聊天框输入 api-key=openai秘钥（你的openai账号的秘钥），即可激活私人GPT3.5AI

### 如图
![image](https://user-images.githubusercontent.com/39401819/222918635-ffbcbead-8384-4f16-a08b-cd5e853bd371.png)

### 原理
UCCLOUD 香港服务器部署，很便宜    给兄弟们做贡献了，直接用吧

### 作者仓库订阅号方法优化方案
[关于微信订阅号服务的一点优化建议](https://github.com/zhayujie/bot-on-anything/issues/99#top)

### 建议
建议仓库作者加个二维码，付费喝杯咖啡   代码写得很好

**Comment by Martianxhc** [comment]
这。。。在这打广告不合适吧？

**Comment by reBiocoder** [comment]
> 这。。。在这打广告不合适吧？
不是广告啊，兄弟  友好交流，我先close了
