### ISSUE TITLE
最新版启动报错，如下提示，更新前可正常运行

### ISSUE THREAD

**Issue by fj9876** [zhayujie/chatgpt-on-wechat#44]
[ERROR][2023-02-05 23:28:27][app.py:19] - App startup failed!
[ERROR][2023-02-05 23:28:27][app.py:20] - Expecting property name enclosed in double quotes: line 8 column 63 (char 327)
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    config.load_config()
  File "/home/fujia/chatgpt-on-wechat/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 63 (char 327)

**Comment by zhayujie** [comment]
把 config.json 中除了api_key之外的内容贴出来看下

**Comment by fj9876** [comment]
{
  "open_ai_api_key": "i", 
  "single_chat_prefix": [""],
  "single_chat_reply_prefix": "[来自AI回复] ",
  "group_chat_prefix": ["@AI机器人"],
  "group_name_white_list": ["羊毛群"],
  "image_create_prefix": ["画", "看", "找"],
  "conversation_max_tokens": 1200,                            # 支持上下文记忆的最多字符数
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你乐于回答人们的各种问题。"  # 人格描述
}

**Comment by zhayujie** [comment]
> { "open_ai_api_key": "i", "single_chat_prefix": [""], "single_chat_reply_prefix": "[来自AI回复] ", "group_chat_prefix": ["@ai机器人"], "group_name_white_list": ["羊毛群"], "image_create_prefix": ["画", "看", "找"], "conversation_max_tokens": 1200, # 支持上下文记忆的最多字符数 "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你乐于回答人们的各种问题。" # 人格描述 }

需要把注释部分删掉 ("#以及后面的内容")，    或者从 config-template.json 中复制过来

**Comment by zhayujie** [comment]
最好可以再更新下代码，我刚更新了一个别的bug
