### ISSUE TITLE
从企业微信给bot发消息，不会有响应

### ISSUE THREAD

**Issue by dashi6174** [zhayujie/chatgpt-on-wechat#441]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

1. 我的bot是一个普通的微信；
2. 另一个企业微信添加乐上面的bot
3. 企微给bot发消息，带了bot前缀，bot不会回答；

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by 312818545** [comment]
我也遇到同样的问题，请问找到解决方案了吗

**Comment by dashi6174** [comment]
还没有，我打算自己debug，看下是哪里的问题，自己打个patch

**Comment by luojin520520** [comment]
大佬们解决了吗？？我也遇到了
