### ISSUE TITLE
本项目很好，但有没有办法做成公众号部署，自动回复的办法？

### ISSUE THREAD

**Issue by fattank** [zhayujie/chatgpt-on-wechat#443]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
如题

> 简要说明、截图、复现步骤等，也可以是需求或想法
本地开发机用起来提心吊胆，能不能做成公众号，这样用起来，可能就不容易被微信封号了。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by frankchn-x** [comment]
看作者另外一个项目，chatgpt-on-anything，我用另外一个项目在公众号上部署，没问题

**Comment by fattank** [comment]
感谢，已经看到了，真棒👍。
