### ISSUE TITLE
换了新加坡服务器，openai新注册key，秒封，有解决办法吗？

### ISSUE THREAD

**Issue by ShawnSheno** [zhayujie/chatgpt-on-wechat#445]
1.换了新加坡服务器
2.openai新注册key，
3.问了一句话，结果api秒封
有解决办法吗？

**Comment by frankchn-x** [comment]
itchat?
试试用wechaty

**Comment by zhayujie** [comment]
现在搞不清楚openai啥检测机制了，按理说新加坡在support area list里面

**Comment by ShawnSheno** [comment]
> 现在搞不清楚openai啥检测机制了，按理说新加坡在support area list里面

是的。很疑惑。现在封了api，账号也会被封

**Comment by qigegenb** [comment]
我的账号不到一天就直接被封了

**Comment by li-Coulson** [comment]
同样，我的腾讯云新加坡服务器被秒封 ip，官网首页都进不去
