### ISSUE TITLE
免科学上网访问方案，看下这个，我实测是可以的

### ISSUE THREAD

**Issue by liaocatcat** [zhayujie/chatgpt-on-wechat#446]
https://github.com/noobnooc/noobnooc/discussions/9

**Comment by baichisong** [comment]
看了你的连接说明，好繁琐呀

**Comment by liuao5201314** [comment]
> [noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9)

说白了就是配一个域名的反向代理,通过国外域名托管把你自己的域名反向代理到openai域名

**Comment by 18376932936** [comment]
> 

但是一劳永逸，不用考虑机场稳定性，每天20万次请求，挺划算的

**Comment by baichisong** [comment]
可以试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月14日 18:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] 免科学上网访问方案，看下这个，我实测是可以的 (Issue #446) |

但是一劳永逸，不用考虑机场稳定性，每天20万次请求，挺划算的

**Comment by baichisong** [comment]
但是现在项目有问题，老是会休眠吖



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月14日 18:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] 免科学上网访问方案，看下这个，我实测是可以的 (Issue #446) |

但是一劳永逸，不用考虑机场稳定性，每天20万次请求，挺划算的

**Comment by Kiteflyingee** [comment]
我尝试了重启代理休眠的问题就会解决，但是总要重启，这个链接的方法还是可以试试，就是我的一级域名已经在其他地方用了，没法尝试了

> 但是现在项目有问题，老是会休眠吖
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月14日 18:10 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [zhayujie/chatgpt-on-wechat] 免科学上网访问方案，看下这个，我实测是可以的 (Issue #446) | 但是一劳永逸，不用考虑机场稳定性，每天20万次请求，挺划算的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by KFC-vme-50** [comment]
这个我倒是创建成功了，但是作者的json文件里没有让改api地址的地方啊，只有一个open ai api key

**Comment by lsCoding666** [comment]
这个方案 其实并不完美。因为实际上中国大陆很多地区的cloudflare worker是被墙的。我的做法是使用腾讯云函数香港节点做中转，然后改baseurl就行，机器人运行在家里自己wiindows电脑上，而且归属地也在本地，账号更安全，
https://github.com/Ice-Hazymoon/openai-scf-proxy

**Comment by lsCoding666** [comment]
> 这个方案 其实并不完美。因为实际上中国大陆很多地区的cloudflare worker是被墙的。我的做法是使用腾讯云函数香港节点做中转，然后改baseurl就行，机器人运行在家里自己wiindows电脑上，而且归属地也在本地，账号更安全， https://github.com/Ice-Hazymoon/openai-scf-proxy

而且也不需要服务器 而且画图就用本地画就行了

**Comment by KFC-vme-50** [comment]
> 这个方案 其实并不完美。因为实际上中国大陆很多地区的cloudflare worker是被墙的。我的做法是使用腾讯云函数香港节点做中转，然后改baseurl就行，机器人运行在家里自己wiindows电脑上，而且归属地也在本地，账号更安全， https://github.com/Ice-Hazymoon/openai-scf-proxy

你属实是有点多此一举了，用自己的域名绑定workers就是为了绕过.dev域名的dns污染，使用自己域名访问就能直接打到目的，没必要专门买一个节点来中专

**Comment by lsCoding666** [comment]
> > 这个方案 其实并不完美。因为实际上中国大陆很多地区的cloudflare worker是被墙的。我的做法是使用腾讯云函数香港节点做中转，然后改baseurl就行，机器人运行在家里自己wiindows电脑上，而且归属地也在本地，账号更安全， https://github.com/Ice-Hazymoon/openai-scf-proxy
> 
> 你属实是有点多此一举了，用自己的域名绑定workers就是为了绕过.dev域名的dns污染，使用自己域名访问就能直接打到目的，没必要专门买一个节点来中专

是哦 你这么说也对 自己域名总不会被墙。不过我的意思不是购买一个节点，腾讯云函数的香港节点不是服务器，而且调用量根本够不到付费标准，说白了就是白嫖

**Comment by lsCoding666** [comment]
> > > 这个方案 其实并不完美。因为实际上中国大陆很多地区的cloudflare worker是被墙的。我的做法是使用腾讯云函数香港节点做中转，然后改baseurl就行，机器人运行在家里自己wiindows电脑上，而且归属地也在本地，账号更安全， https://github.com/Ice-Hazymoon/openai-scf-proxy
> > 
> > 
> > 你属实是有点多此一举了，用自己的域名绑定workers就是为了绕过.dev域名的dns污染，使用自己域名访问就能直接打到目的，没必要专门买一个节点来中专
> 
> 是哦 你这么说也对 自己域名总不会被墙。不过我的意思不是购买一个节点，腾讯云函数的香港节点不是服务器，而且调用量根本够不到付费标准，说白了就是白嫖

而且连域名都不用买 这回真的0成本了

**Comment by KFC-vme-50** [comment]
> > > > 这个方案 其实并不完美。因为实际上中国大陆很多地区的cloudflare worker是被墙的。我的做法是使用腾讯云函数香港节点做中转，然后改baseurl就行，机器人运行在家里自己wiindows电脑上，而且归属地也在本地，账号更安全， https://github.com/Ice-Hazymoon/openai-scf-proxy
> > > 
> > > 
> > > 你属实是有点多此一举了，用自己的域名绑定workers就是为了绕过.dev域名的dns污染，使用自己域名访问就能直接打到目的，没必要专门买一个节点来中专
> > 
> > 
> > 是哦 你这么说也对 自己域名总不会被墙。不过我的意思不是购买一个节点，腾讯云函数的香港节点不是服务器，而且调用量根本够不到付费标准，说白了就是白嫖
> 
> 而且连域名都不用买 这回真的0成本了

哥们儿，你这个相当于是二次反代理了，cloudflare本身就是所谓的云函数即severless，你相当于用腾讯的serverless去反代理cloudflare，再用cloudflare去反代理OpenAI的服务器。

我用域名其实是还有其他项目，对我来说不算是多的花销。

**Comment by lsCoding666** [comment]
> 

看仔细点 是云函数直接反代openai了，没用到cloudflare。当然域名很便宜，我自己也有，但是我还是用了选择了腾讯云没有用cloudflare workers。主要是觉得，节点在香港，用起来速度快。
