### ISSUE TITLE
最新代码在window下，dos后台启动命令  start /b  python app.py  & tail -f nohup.out 有点问题

### ISSUE THREAD

**Issue by baichisong** [zhayujie/chatgpt-on-wechat#449]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

最新代码在window下，dos后台启动命令  start /b  python app.py  & tail -f nohup.out 有点问题：启动后用微信恢复机器人，发现不回答问题，然后我在启动的日志dos打印页面按了几个enter机器人才会回复。看终端日志

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
![14d70fcb89cab0d5235900c3d2b4933](https://user-images.githubusercontent.com/8436305/224619063-263e2fc6-bdb3-4e71-a3b7-237bc98635fd.png)

### 环境

 - 操作系统类型  (/Windows)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by yangchaoya** [comment]
![image](https://user-images.githubusercontent.com/51851780/224635321-d6faa840-1d3b-4e4b-a8d3-51378991bd39.png)
一样， 登录成功后 不会接受消息 也不回答问题

**Comment by jkjoy** [comment]
一样 我的也是登录成功 没啥反应

**Comment by baichisong** [comment]
告诉你们，你们先用微信给机器人发几条信息，然后到那个页面敲几个enter键就可以了，不知道为啥。
