### ISSUE TITLE
能否支持自定义openai的API域名

### ISSUE THREAD

**Issue by chrischjh** [zhayujie/chatgpt-on-wechat#453]
能否支持自定义openai的API域名

**Comment by chrischjh** [comment]
可以的，用cloudflare进行中转，在客户端这里用自定义域名代替api.openai.com。用官方sdk估计也可以

**Comment by chrischjh** [comment]
应该是openai.api_base

**Comment by chrischjh** [comment]
@zhayujie  测试成功。后面一定要加上`/v1/` 

`openai.api_base = 'https://自定义域名/v1/'`

**Comment by zhayujie** [comment]
@B1gM8c 已在 https://github.com/zhayujie/chatgpt-on-wechat/pull/465 中支持

**Comment by cxfksword** [comment]
> @B1gM8c 已在 #465 中支持

能同时支持下docker环境变量传入吗
