### ISSUE TITLE
亲测，API被封后，账号也会被封禁

### ISSUE THREAD

**Issue by ShawnSheno** [zhayujie/chatgpt-on-wechat#454]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/34580770/224872267-71f46bf9-9842-4ac3-91cf-c5ec8293d55e.png">

**Comment by kdyzm** [comment]
是的，我的也被封禁了

**Comment by colaKot** [comment]
你们是怎么被封禁的?

**Comment by pm0725** [comment]
我也被封了。。

**Comment by FFFFourwood** [comment]
+1 今天早上被封了
刚才又买了个号 不到20分钟又被封了

**Comment by ShawnSheno** [comment]
> 

@colaKot 不是一般都会被封吗？

**Comment by FFFFourwood** [comment]
我不信又买了一个
洗个澡回来又没了。。。

**Comment by FFFFourwood** [comment]
跟这个没关系，，最后这次被封 我没跑wechat bot，，

**Comment by FFFFourwood** [comment]
只是跑了 tg bot + bob翻译，，， 
tg bot走的 cloudflare 
bob翻译走的sg proxy

洗个澡回来就没了。。。

**Comment by ShawnSheno** [comment]
> 只是跑了 tg bot + bob翻译，，， tg bot走的 cloudflare bob翻译走的sg proxy
> 
> 洗个澡回来就没了。。。

那就很奇怪了，不知道付费购买api会不会被封。

**Comment by ronansparks** [comment]
> 

tb 买的 现成号？同一个账号，他卖给多个人使用，你也不知道吧。卖多，利益最大化

**Comment by dlwang624** [comment]
> > 
> 
> tb 买的 现成号？同一个账号，他卖给多个人使用，你也不知道吧。卖多，利益最大化

谁还通过tb买，傻嘛

**Comment by missy0u** [comment]
> 只是跑了 tg bot + bob翻译，，， tg bot走的 cloudflare bob翻译走的sg proxy
> 
> 洗个澡回来就没了。。。

我也就前几天apikey绑了bob翻译，用得极少，一天划词翻译那么几次，今晚划词翻译了一次后，立马就封了！！
bob翻译绑的apikey是否会有可能被它收集滥用？

**Comment by FFFFourwood** [comment]
> > 只是跑了 tg bot + bob翻译，，， tg bot走的 cloudflare bob翻译走的sg proxy
> > 洗个澡回来就没了。。。
> 
> 我也就前几天apikey绑了bob翻译，用得极少，一天划词翻译那么几次，今晚划词翻译了一次后，立马就封了！！ bob翻译绑的apikey是否会有可能被它收集滥用？

不可能，我有的没挂bob也被封了，应该就是openai突然变严格了
我的三个号分别是是
1，挂了一个tg bot（cloudflare），一个微信bot（hk proxy），bob（hk），两个web，  用了10多天昨天早上挂了
2，只挂了微信bot（jp proxy）， 20分钟不到就挂了
3，只挂了tg bot（cloudflare）和bob（sg proxy），洗个澡回来也就20来分钟不到 又挂了


然后我一群友今天中午开的plus，到晚上吃完饭也被封了

**Comment by ShawnSheno** [comment]
目前遇到被封的情况
1.API被封（已测）
一般是服务器ip不在OpenAI服务区域，比较好解决。国内有些云厂商海外服务器也不太行。
换成亚马逊云海外服务器即可。见https://www.pmssw.com/44.html
2.微信被封
尝试wechaty，或者换成web端吧，这个没办法。。

**Comment by qigegenb** [comment]
我的什么也没有挂，还在代码调试请求阶段，就被封了

**Comment by ShawnSheno** [comment]
> 

应该是访问的IP问题，海外的才行

**Comment by ZihaoZheng98** [comment]
请问plus会被封吗

**Comment by ShawnSheno** [comment]
> 

会

**Comment by ShawnSheno** [comment]
我开了个交流群，可以一起讨论下经验。
<img width="268" alt="image" src="https://user-images.githubusercontent.com/34580770/225826069-ed470699-b817-4c18-8030-a6c5b822350c.png">

**Comment by webj1011** [comment]
是永封吗？色色发抖。。。

**Comment by ShawnSheno** [comment]
> 

应该是的

**Comment by laohuan12138** [comment]
你们是买的的号还是自己注册的号，买的号大多是批量注册的，openai对批量注册的号进行大规模封堵

**Comment by explorerJi** [comment]
> 我开了个交流群，可以一起讨论下经验。 <img alt="image" width="268" src="https://user-images.githubusercontent.com/34580770/225826069-ed470699-b817-4c18-8030-a6c5b822350c.png">

拉我一下，JYF20101121

**Comment by glorysaladin** [comment]
> +1 今天早上被封了 刚才又买了个号 不到20分钟又被封了

在哪里买的号，我的也被封了。 要买个号，按照文档说的，需要实名的才可以
