### ISSUE TITLE
 "group_chat_prefix": [""], 时可不可以在群聊里不@的情况下自动回复。

### ISSUE THREAD

**Issue by superlambkin** [zhayujie/chatgpt-on-wechat#456]
### 前置确认
# config.json文件内容示例
{ 
  "open_ai_api_key": "YOUR API KEY",                          # 填入上面创建的 OpenAI API KEY
  "proxy": "127.0.0.1:7890",                                  # 代理客户端的ip和端口
  "single_chat_prefix": [""],                      # 私聊时文本需要包含该前缀才能触发机器人回复
  "single_chat_reply_prefix": "[bot] ",                       # 私聊时自动回复的前缀，用于区分真人
  "group_chat_prefix": [""],                              # 群聊时包含该前缀则会触发机器人回复
  "group_name_white_list": ["ChatGPT测试群", "ChatGPT测试群2"], # 开启自动回复的群名称列表
  "image_create_prefix": ["画", "看", "找"],                   # 开启图片回复的前缀
  "conversation_max_tokens": 1000,                            # 支持上下文记忆的最多字符数
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。"  # 人格描述
}

### 问题描述
 "group_chat_prefix": [""], 时可不可以在群聊里不@的情况下自动回复。

**Comment by Martianxhc** [comment]
好像是可以的，但是每嘴都会回复，体验极差，慎用啊；
另外这个你简单拉个小群测试就可以了，没必要发issues的

**Comment by superlambkin** [comment]
谢谢回复。试过了，结果没有反应。

**Comment by zhayujie** [comment]
先添加一个参数  "group_at_off": true  之后，再加上 "group_chat_prefix": [""] 试试

**Comment by Pumpkinkj** [comment]
有人遇到过，私聊可以，群聊没有回复的情况吗？

config.json是这样的：
{
  "open_ai_api_key": "sk-OavplUsnzI9xqm9RT3BlbkFJ6VsdeRDg4c8qnJReyeNn2",
  "proxy": "",
  "single_chat_prefix": [""],
  "single_chat_reply_prefix": "",
  "group_chat_prefix": ["@鸡飞飞"],
  "group_name_white_list": [""],
  "image_create_prefix": ["画", "想看", "draw"],
  "conversation_max_tokens": 1000,
  "speech_recognition": false,
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，帮助人类学习各类知识，并且可以使用多种语言与人交流。",
  "expires_in_seconds": 3600
}

返回错误信息jian见图片：
![1](https://user-images.githubusercontent.com/126487568/225262922-0012539a-1271-4a1f-8911-44789b321fdf.png)

**Comment by zhayujie** [comment]
@Pumpkinkj 
group_name_white_list 中填空不行的哈， 要填 ALL_GROUP
