### ISSUE TITLE
扫码出现问题

### ISSUE THREAD

**Issue by BianXuerui** [zhayujie/chatgpt-on-wechat#459]
![image](https://user-images.githubusercontent.com/50104688/224904665-17096c2a-89a4-415f-aa05-6d5c8b22a2b0.png)
不知道为什么？

**Comment by BianXuerui** [comment]
换个微信就可以登录成功，不知道为什么...

**Comment by zhayujie** [comment]
see #9

**Comment by BianXuerui** [comment]
> see #9

我的微信认证过了，正在使用的突然就不能用了（好像是微信在手机上退出了，然后再扫码登录就不行了）

**Comment by BianXuerui** [comment]
同样的程序 一个微信可以 一个微信不可以（之前都正在使用的）

**Comment by zhayujie** [comment]
> > see #9
> 
> 我的微信认证过了，正在使用的突然就不能用了（好像是微信在手机上退出了，然后再扫码登录就不行了）

手机退出后有重新启动程序扫码吗， 或者是不是账号被冻结了

**Comment by BianXuerui** [comment]
> > > see #9
> > 
> > 
> > 我的微信认证过了，正在使用的突然就不能用了（好像是微信在手机上退出了，然后再扫码登录就不行了）
> 
> 手机退出后有重新启动程序扫码吗， 或者是不是账号被冻结了

有退出程序重新扫码，甚至都重新clone了一下项目，微信还可以正常登录.

**Comment by zhayujie** [comment]
看一下 ps -ef | grep app.py

**Comment by BianXuerui** [comment]
> ps -ef | grep app.py

<img width="672" alt="image" src="https://user-images.githubusercontent.com/50104688/225217505-3b08b4ab-7fa1-438b-ab1c-d455a0d3a9fe.png">

**Comment by 18410100944** [comment]
我也遇到了这个问题，新注册的微信账号，re.findall('<skey>(.*?)</skey>', r.text, re.S)返回值是[],所以取第一个元素的时候出错
debug看到存在r.text内部的信息是：
'<error><ret>1203</ret><message>你需要开通微信支付，才可继续操作。</message></error>'
所以是要求我们绑定银行卡才能继续。

**Comment by pk350** [comment]
群晖修改login.py提示readonly怎么办
