### ISSUE TITLE
扫码登录成功，显示开始自动回复，但是发消息后台没有任何反应

### ISSUE THREAD

**Issue by Chopain996** [zhayujie/chatgpt-on-wechat#460]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
一开始是好的，关闭调整了一下pefix，就再也没反应了，以及恢复到最开始，后台也没有反应，只显示开始自动回复

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by wan766405890** [comment]
同问

**Comment by wan766405890** [comment]
> ### 前置确认
> 1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
> 2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
> 3. 在已有 issue 中未搜索到类似问题
> 4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
> 
> ### 问题描述
> > 简要说明、截图、复现步骤等，也可以是需求或想法
> > 一开始是好的，关闭调整了一下pefix，就再也没反应了，以及恢复到最开始，后台也没有反应，只显示开始自动回复
> 
> ### 终端日志 (如有报错)
> ```
> [在此处粘贴终端日志]
> ```
> 
> ### 环境
> * 操作系统类型  (Mac/Windows/Linux)：
> * Python版本  ( 执行 `python3 -V` )：
> * pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

网上说需要把python升级到3.7.1

**Comment by Fan-Yu-Feng** [comment]
怀疑是给微信限制了，我换了个微信又好了，好奇怪

**Comment by honemleysm** [comment]
打开debug信息，我这边看到的是，消息已经从openai返回了。但是准备通过微信后台发送的时候，微信后台连接失败，超出最大尝试次数，不知道各位什么情况，大神可否指点下

**Comment by zhayujie** [comment]
@honemleysm  看看是不是开了全局daili ，导致网络不通
