### ISSUE TITLE
加了time.sleep(15)导致登陆一直失败

### ISSUE THREAD

**Issue by honemleysm** [zhayujie/chatgpt-on-wechat#462]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
微信扫码登录失败。今天上午还可以用，下午再次扫码登录就不行了，反复试了多次，一直报错说登录失败，但是微信号本身收发消息没问题。

> 简要说明、截图、复现步骤等，也可以是需求或想法
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/121627131/224933122-a248c3c6-28d0-45fd-872e-b7bd51af6077.png">
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/121627131/224933216-c952656c-19c7-44d5-8fbd-7bbf4ed43c4b.png">

我上午只是试着就是加了一行time.sleep(15)。去掉这一行之后，又可以登录了。但是没有这一行，登陆要尝试很多次，才可能成功一次，请问下，加上这个延迟导致无法登陆的问题，是否有更好的解决办法？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
先解决网络问题，看报错是访问不了wx后台， 如果开了代理需要调成规则模式

**Comment by honemleysm** [comment]
> 先解决网络问题，看报错是访问不了wx后台， 如果开了代理需要调成规则模式

”规则模式“是指只代理被封锁的流量，而不是代理全部流量？如果是指这个，这个我已经开启了。如果是其它的意思，烦请明示，谢谢！

**Comment by Demandredt** [comment]
你检查一下是不是time.sleep(15)的格式有问题。之前我在time.sleep(15)前面不小心多加了一个空格，所以一直登录出错。我把代码复制到vs code中检查没问题之后复制回去才成功的

**Comment by zhayujie** [comment]
@honemleysm  是这个意思， 看日志显示访问 wx 网络不通
