### ISSUE TITLE
itchat-uos==1.5.0.dev0

### ISSUE THREAD

**Issue by YSN-commits** [zhayujie/chatgpt-on-wechat#464]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 使用pip3 install itchat-uos==1.5.0.dev0下载不了

> 还能从哪下

### 终端日志 (如有报错)

```
[ERROR: Could not find a version that satisfies the requirement itchat-uos==1.5.0.dev0 (from versions: none)
ERROR: No matching distribution found for itchat-uos==1.5.0.dev0]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
pip3 install itchat-uos==1.5.0.dev0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by nicohmx** [comment]
我也遇到一样的问题，查到的信息是**源有问题**。
1、源有问题，网络不好，换源`-i https://pypi.tuna.tsinghua.edu.cn/simple`
2、源有问题，估计是开了墙，关闭后就正常了
