### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by Ser-MingShao** [zhayujie/chatgpt-on-wechat#47]
扫码之后测试中报错ModuleNotFoundError: No module named 'openai'

**Comment by zhayujie** [comment]
这个是openai没有安装，要确认安装在用于启动程序的python下

如果你使用python3.8 app.py  来启动程序，可以通过 `python3.8 -m pip show openai` 来查看是否安装。

**Comment by Ser-MingShao** [comment]
![image](https://user-images.githubusercontent.com/67584847/216910895-56256c6f-0b25-4279-a995-724b02cd4bf4.png)
不好意思，在麻烦请你再看看这个问题

**Comment by Ser-MingShao** [comment]
好像一直安装不上

**Comment by Ser-MingShao** [comment]
![image](https://user-images.githubusercontent.com/67584847/216918426-6f6051f7-853a-45fb-98fb-659ed1cf1114.png)

**Comment by zhayujie** [comment]
现在 pip3 和 python3 用的都是python3.6的
你先把安装好的 python3.7.15 配置到环境变量中，这个查一下应该很好弄

需要实现：  python3 --version 可以显示 python3.7.15.     或者   python3.7 --version能够成功执行

**Comment by Ser-MingShao** [comment]
好的好的，谢谢

**Comment by Ser-MingShao** [comment]
![image](https://user-images.githubusercontent.com/67584847/216922426-2c25a85d-e958-46c3-8ff9-484c66894b70.png)
你好，请问这样可以了吗

**Comment by Ser-MingShao** [comment]
![image](https://user-images.githubusercontent.com/67584847/216923238-bdf53b54-0a24-4434-b3bd-98426b131d0d.png)
是不是我环境还没配好的问题啊，还是抓不到openai的资源包

**Comment by zhayujie** [comment]
是的，看起来你的 python3.7安装有点问题， 你先查一下报错信息看看能不能解决
可以加我下 我晚点给你看看

**Comment by zhayujie** [comment]
已解决
