### ISSUE TITLE
接入chatGPT4

### ISSUE THREAD

**Issue by txz-code-farmer** [zhayujie/chatgpt-on-wechat#471]
请问有接入chatGPT4的打算吗

**Comment by godblessbb** [comment]
应该不会，chatgpt4需要在openai购买每个月20美元每个月的增值服务，gpt4的api现在只开放企业用户申请试用。

**Comment by zhayujie** [comment]
gpt4.0接口完全复用， 理论上只用修改模型类型即可， 稍后把model参数加到配置文件，自由切换

**Comment by txz-code-farmer** [comment]
那bot-on-anything也会集成吗

**Comment by shuyaoyao** [comment]
> gpt4.0接口完全复用， 理论上只用修改模型类型即可， 稍后把model参数加到配置文件，自由切换

4.0之前能不能像webchatgpt插件一样提供联网搜索和数据来源功能呀？

**Comment by sorrrrrry** [comment]
同求4

**Comment by redquilt** [comment]
可不可以在配置文件里增加一个选项，让用户自定义模型呢？隔壁**fuergaosi233/wechat-chatgpt**就可以自定义MODEL参数

**Comment by MinovskyRickland** [comment]
目前GPT4的反馈速度只有3.5turbo的1/3左右，而且公开价格较贵，如果API还可以读取图像或画，代价可能较高了

**Comment by wzq10314** [comment]
> gpt4.0接口完全复用，理论上只用修改模型类即可，稻后把模型参数加到配置文件，自由切换

现在GPT-4只能用PLUS来使用，还无法用API好像，希望能出个账号密码登录来使用GPT-4

**Comment by HeYeshuai** [comment]
可以配置根据不同的前缀词调用不同的模型吗，这样到时候需要gpt4的时候就用gpt4的前缀词提问，用gpt3.5就用gpt3.5的前缀提问，可以便宜好多^_^, gpt4 api有点贵

**Comment by HenMie** [comment]
> 可以配置根据不同的前缀词调用不同的模型吗，这样到时候需要gpt4的时候就用gpt4的前缀词提问，用gpt3.5就用gpt3.5的前缀提问，可以便宜好多^_^, gpt4 api有点贵

这个提议不错，支持
