### ISSUE TITLE
全新的,我连接不到你的网络

### ISSUE THREAD

**Issue by colaKot** [zhayujie/chatgpt-on-wechat#472]
### 问题描述

今天早上更新以后出现了这个报错,我还有另外一个项目也在同一台机器,是没有问题的,都是国内的机器,走Clash代理.配置的key和代理也是一样
{
  "open_ai_api_key": "xxxxx",
  "proxy": "http://127.0.0.1:7890",
  "single_chat_prefix": [""],
  "single_chat_reply_prefix": "",
  "group_chat_prefix": ["@bot"],
  "group_name_white_list": ["ChatGPT测试群2"],
  "image_create_prefix": ["画", "看", "找"],
  "conversation_max_tokens": 1000,
  "character_desc": "你是一个25岁的超可爱程序员，你性格活泼幽默开朗，爱好游泳和打羽毛球",
  "expires_in_seconds": 3600
}

### 终端日志 (如有报错)

```
[INFO][2023-03-15 09:27:50][chat_gpt_bot.py:27] - [OPEN_AI] query=你是男生还是女生
[WARNING][2023-03-15 09:27:50][chat_gpt_bot.py:88] - Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://None/chat/completions?
[WARNING][2023-03-15 09:27:50][chat_gpt_bot.py:89] - [OPEN_AI] APIConnection failed
[INFO][2023-03-15 09:27:50][wechat_channel.py:137] - [WX] sendMsg=我连接不到你的网络, receiver=@757623c2b159213bd366586ea467166c
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：windos10
 - Python版本  ( 执行 `python3 -V` )： 3.9.10                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by colaKot** [comment]
换了新的key也是这样,另外一个web端的工程,是可以正常使用的.

**Comment by colaKot** [comment]
在配置里面添加一行
  "open_ai_api_base":"https://api.openai.com/v1",
就可以了

**Comment by zhayujie** [comment]
应该是昨天提交有个兼容问题，拉取最新的代码应该修复了

默认的 api_base 就是这个，应该不用在配置中声明

**Comment by Hwangzhiyoung** [comment]
> 应该是昨天提交有个兼容问题，拉取最新的代码应该修复了
> 
> 默认的 api_base 就是这个，应该不用在配置中声明

我亲测有效，更新代码后不用配置api_base

**Comment by zhangshuodale** [comment]
配置完apibase也连接不上，群晖docker上安装完，端口3000，机器本身可以科学上网，hk机场，请问是什么问题呢？
