### ISSUE TITLE
扫码登录后，直接log out!

### ISSUE THREAD

**Issue by fatboy1994** [zhayujie/chatgpt-on-wechat#478]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 扫码之后就这样了：
Start auto replying.
LOG OUT!

![image](https://user-images.githubusercontent.com/55662670/225305624-ee37ff88-1c6f-44c3-83f6-9fec51dad1a8.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by fatboy1994** [comment]
已经查明了，被微信临时限制了

**Comment by zhayujie** [comment]
批量封的

**Comment by fatboy1994** [comment]
>还好只是小号，问题不大，可以造作

**Comment by fatboy1994** [comment]
> 批量封的
还好只是小号，问题不大，可以造作
