### ISSUE TITLE
扫码过的账号被踢下线，检测为"使用第三方软件、外挂、插件等"

### ISSUE THREAD

**Issue by goldenLii** [zhayujie/chatgpt-on-wechat#479]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 扫码登录过的微信号，在一个时间点都被系统踢下线了。是触发了微信的检测么？这个我们有办法解决么？

![img_v2_dacb38ed-55a5-40c6-a297-fd4da091e8ag](https://user-images.githubusercontent.com/40637401/225311085-98a9817f-e7c0-4e94-81d0-c5809cd6a014.jpg)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
see #115

**Comment by nate872** [comment]
我也是 咋办啊。。

**Comment by Tyler201609** [comment]
我今天就没登录，下午也接收到这个警告。就昨晚上接了一个Go语言的登录测试了几分钟，今天就被检测了么，还是主号。

**Comment by shuyaoyao** [comment]
我一共用了两天半，也是被踢下线，和你提示一样
