### ISSUE TITLE
图片无法发到聊天中，实际生成了url

### ISSUE THREAD

**Issue by acbogeh** [zhayujie/chatgpt-on-wechat#48]
r日志如下

[INFO][2023-02-06 11:19:11][open_ai_bot.py:20] - [OPEN_AI] query=麻烦画一个美丽的少女
[INFO][2023-02-06 11:19:24][open_ai_bot.py:54] - [OPEN_AI] reply=这是一个美丽的少女，她身穿粉色连衣裙，穿在身上显得格外洋气。她靓丽的发型披散在肩膀上，双手捧着雪白的花朵，显得格外清新可爱。她秀美的脸庞宛如仙子，白皙的皮肤发出晶莹的光芒，温柔的眼神透出淡淡的温柔，令人心神难忘。
[INFO][2023-02-06 11:19:24][wechat_channel.py:103] - [WX] sendMsg=[bot] 这是一个美丽的少女，她身穿粉色连衣裙，穿在身上显得格外洋气。她靓丽的发型披散在肩膀上，双手捧着雪白的花朵 ，显得格外清新可爱。她秀美的脸庞宛如仙子，白皙的皮肤发出晶莹的光芒，温柔的眼神透出淡淡的温柔，令人心神难忘。, receiver=@8f6eb09cf8a9a7d9c80a32ad5952c6f1
[INFO][2023-02-06 11:20:02][open_ai_bot.py:59] - [OPEN_AI] image_query=一个美丽的少女
[INFO][2023-02-06 11:20:32][open_ai_bot.py:66] - [OPEN_AI] image_url=https://oaidalleapiprodscus.blob.core.windows.net/private/org-acHM3NsBHWRkW4SAjgYUZzMm/user-Ll86hYYaFr2JC3Uw0ynnUMj1/img-YszG2tGNN0TQC2YuXZ2KEvF9.png?st=2023-02-06T02%3A20%3A32Z&se=2023-02-06T04%3A20%3A32Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-02-05T18%3A50%3A33Z&ske=2023-02-06T18%3A50%3A33Z&sks=b&skv=2021-08-06&sig=SCx%2BZIDVVyWHAJfo%2BU/ofKdk54Ujh024Df0Ps2Y2OPE%3D
[INFO][2023-02-06 11:20:57][open_ai_bot.py:59] - [OPEN_AI] image_query=的快一点
[INFO][2023-02-06 11:21:09][open_ai_bot.py:66] - [OPEN_AI] image_url=https://oaidalleapiprodscus.blob.core.windows.net/private/org-acHM3NsBHWRkW4SAjgYUZzMm/user-Ll86hYYaFr2JC3Uw0ynnUMj1/img-aE7Ww1ByTTwg4LNc51lG6fcJ.png?st=2023-02-06T02%3A21%3A09Z&se=2023-02-06T04%3A21%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-02-05T21%3A10%3A56Z&ske=2023-02-06T21%3A10%3A56Z&sks=b&skv=2021-08-06&sig=Ui9zQAaA7d6xF5l%2BQ8Th6K8YVZVChOh53n21/NiNabg%3D

**Comment by zhayujie** [comment]
对于图像生成，需要关键词前缀来触发，对应配置 image_create_prefix 

你直接和它说 "画一个xxx" 试试

**Comment by acbogeh** [comment]
> 对于图像生成，需要关键词前缀来触发，对应配置 image_create_prefix
> 
> 你直接和它说 "画一个xxx" 试试


可以看我的日志，首字的画貌似都被自动截掉了

**Comment by zhayujie** [comment]
> 可以看我的日志，首字的画貌似都被自动截掉了

私聊有点问题看来，我晚点改下。 群聊里应该是正常的吧
