### ISSUE TITLE
一直报HTTPSConnectionPool 是ip被封了吗？

### ISSUE THREAD

**Issue by wang-hk** [zhayujie/chatgpt-on-wechat#482]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

之前可用，下线过几次后一直报这个err，看起来是请求次太多未正常断开导致的，有遇到这样情况的吗？

### 终端日志 (如有报错)

Login successfully as  
Start auto replying.
[INFO][2023-03-15 22:21:08][chat_gpt_bot.py:28] - [OPEN_AI] query= 我连接不到你的网络
[WARNING][2023-03-15 22:21:11][chat_gpt_bot.py:86] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03EE56D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[WARNING][2023-03-15 22:21:11][chat_gpt_bot.py:87] - [OPEN_AI] APIConnection failed
[INFO][2023-03-15 22:21:11][wechat_channel.py:137] - [WX] sendMsg= 我连接不到你的网络, receiver=@299b2f31cbcc7ab3b371e74b4bfc15eb

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
这个是网络连不上了， 你是运行在什么环境的

**Comment by wang-hk** [comment]
> win7 python3.7.4

代理clash和V2rayn都这样  google可以访问但刚看好像ping不通
