### ISSUE TITLE
无法正常回复

### ISSUE THREAD

**Issue by Arong1984** [zhayujie/chatgpt-on-wechat#484]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述 无法正常回复

> 简要说明、截图、复现步骤等，也可以是需求或想法

微信上私聊时回复：[bot]我连接不到你的网络 群聊无回复
终端日志上也是这样显示，应该是代理的问题，因为我用的是谷歌的一个叫穹顶穿越的插件，网页上可以访问外网，但是软件上无法实现，有没有办法解决？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
Start auto replying.
[INFO][2023-03-16 10:06:48][chat_gpt_bot.py:28] - [OPEN_AI] query=你好
[WARNING][2023-03-16 10:06:49][chat_gpt_bot.py:89] - Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[WARNING][2023-03-16 10:06:49][chat_gpt_bot.py:90] - [OPEN_AI] APIConnection failed
[INFO][2023-03-16 10:06:49][wechat_channel.py:137] - [WX] sendMsg=[bot] 我连接不到你的网络, receiver=@78e0e6164ca3605243b31dd329a5977f6f85e4dc1af8777ccb4df2b19ee2bc6c
[INFO][2023-03-16 10:15:28][chat_gpt_bot.py:28] - [OPEN_AI] query=你好
[WARNING][2023-03-16 10:15:28][chat_gpt_bot.py:89] - Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[WARNING][2023-03-16 10:15:28][chat_gpt_bot.py:90] - [OPEN_AI] APIConnection failed
[INFO][2023-03-16 10:15:28][wechat_channel.py:137] - [WX] sendMsg=[bot] 我连接不到你的网络, receiver=@78e0e6164ca3605243b31dd329a5977f6f85e4dc1af8777ccb4df2b19ee2bc6c
[INFO][2023-03-16 10:35:32][chat_gpt_bot.py:28] - [OPEN_AI] query=你好
[WARNING][2023-03-16 10:36:35][chat_gpt_bot.py:89] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000004F7F460>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[WARNING][2023-03-16 10:36:35][chat_gpt_bot.py:90] - [OPEN_AI] APIConnection failed
[INFO][2023-03-16 10:36:35][wechat_channel.py:137] - [WX] sendMsg=[bot] 我连接不到你的网络, receiver=@78e0e6164ca3605243b31dd329a5977f6f85e4dc1af8777ccb4df2b19ee2bc6c

### 环境

 - 操作系统类型  (Windows7)：
 - Python版本  ( 执行 `python3.8.10` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 21.1.1`)：

**Comment by zhayujie** [comment]
浏览器插件只能用于web代理，系统不一定能生效
