### ISSUE TITLE
连接不到网络

### ISSUE THREAD

**Issue by FlyM3** [zhayujie/chatgpt-on-wechat#487]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

提示连接不到我的网络，我在mac电脑上运行的，proxy：127.9.0.1:7890

### 终端日志 (如有报错)
[WARNING][2023-03-16 17:08:29][chat_gpt_bot.py:89] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1056edf70>: Failed to establish a new connection: [Errno 61] Connection refused')))
[WARNING][2023-03-16 17:08:29][chat_gpt_bot.py:90] - [OPEN_AI] APIConnection failed
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：mac
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by FlyM3** [comment]
我的问题，我漏掉了一个步骤，后面回复了，但是显示连接不到我的网络，求大神帮助

**Comment by FlyM3** [comment]
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/68105229/225567117-ec839286-e109-4eef-8ca4-bb3aeb3594f9.png">

**Comment by chaojibendan** [comment]
同问，频繁出现此问题，问十次只能回答一次
