### ISSUE TITLE
Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.

### ISSUE THREAD

**Issue by Arxchibo** [zhayujie/chatgpt-on-wechat#489]
Login successfully as Arxchibo
Start auto replying.
[INFO][2023-03-16 17:46:37][chat_gpt_bot.py:28] - [OPEN_AI] query=嗨
[WARNING][2023-03-16 17:46:37][chat_gpt_bot.py:80] - Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
[WARNING][2023-03-16 17:46:42][chat_gpt_bot.py:83] - [OPEN_AI] RateLimit exceed, 第1次重试
[WARNING][2023-03-16 17:46:42][chat_gpt_bot.py:80] - Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
[INFO][2023-03-16 17:46:43][wechat_channel.py:137] - [WX] sendMsg=[bot] 提问太快啦，请休息一下再问我吧, receiver=@96bee06808003b4248a8b1e4087ab90fd482257618b07a80d8b62d02497f3183
[INFO][2023-03-16 17:46:51][chat_gpt_bot.py:28] - [OPEN_AI] query=推荐一些高端楼盘
[WARNING][2023-03-16 17:46:52][chat_gpt_bot.py:80] - Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
[WARNING][2023-03-16 17:46:57][chat_gpt_bot.py:83] - [OPEN_AI] RateLimit exceed, 第1次重试
[WARNING][2023-03-16 17:46:57][chat_gpt_bot.py:80] - Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
[INFO][2023-03-16 17:46:57][wechat_channel.py:137] - [WX] sendMsg=[bot] 提问太快啦，请休息一下再问我吧, receiver=@96bee06808003b4248a8b1e4087ab90fd482257618b07a80d8b62d02497f318

**Comment by wutian1314** [comment]
一样的问题
