### ISSUE TITLE
完全不回复图片怎么办

### ISSUE THREAD

**Issue by jokerlinnn** [zhayujie/chatgpt-on-wechat#490]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

"image_create_prefix": ["画", "看", "找"],
### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

bot 画一张猫的图片
[bot] 非常抱歉，由于我的设计能力有限，我无法为您绘制一张猫的图片。但是，我可以向您推荐一些在线绘画工具，例如PaintZ，Sketchpad或Autodesk Sketchbook，您可以使用这些工具之一来绘制自己的猫的图片。如果您有其他问题需要我的帮助，请随时告诉我。
bot 生成一张猫的图片
[bot] 很抱歉，我无法生成图片。但是，我可以向你推荐一些在线工具或应用程序，例如 PicsArt 和 Canva，这些工具可以帮助你创建自己的猫的图片。你可以在这些工具中寻找现成的模板和素材，或者上传自己的照片并进行编辑和设计。

### 终端日志 (如有报错)

没有报错`

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( 3.7.3)：                      
 - pip版本  ( 23.0.1)：

**Comment by zhayujie** [comment]
这个是群聊还是私聊？

**Comment by jokerlinnn** [comment]
群聊私聊都不行   昨天重新运行程序又可以了   但是只回复很简单的那种  复杂了又说不支持了

**Comment by zhayujie** [comment]
使用itchat 还是wechaty呢
