### ISSUE TITLE
服务启动报错

### ISSUE THREAD

**Issue by wangziqin123** [zhayujie/chatgpt-on-wechat#492]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/20764518/225602528-6f48362b-dea7-44c0-bf55-4882fd5bc5bd.png)

### 终端日志 (如有报错)

```
[ERROR][2023-03-16 19:20:54][app.py:19] - App startup failed!     
[ERROR][2023-03-16 19:20:54][app.py:20] - No module named 'itchat'
Traceback (most recent call last):
  File "D:\mylearn\chatgpt-on-wechat\app.py", line 14, in <module>
    channel = channel_factory.create_channel("wx")
  File "D:\mylearn\chatgpt-on-wechat\channel\channel_factory.py", line 12, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "D:\mylearn\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 7, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
pip3 install itchat-uos

**Comment by charles365ab1** [comment]
[ERROR][2023-03-16 13:04:13][app.py:19] - App startup failed!
[ERROR][2023-03-16 13:04:13][app.py:20] - No module named 'itchat'
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    channel = channel_factory.create_channel("wx")
  File "/home/ec2-user/chatgpt-on-wechat/channel/channel_factory.py", line 12, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "/home/ec2-user/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 7, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'

我也是这个错误。Python3.8，linux，itchat-uos已经安装
Name: itchat-uos
Version: 1.5.0.dev0
Summary: 复活Itchat, 仅仅需要 pip install itchat-uos, good luck !
Home-page: https://github.com/why2lyj/ItChat-UOS
Author: Snow Wang
Author-email: admin@farseer.vip
License: MIT
Location: /home/ec2-user/.local/lib/python3.7/site-packages
Requires: pypng, pyqrcode, requests
Required-by: 

key是新申请的，账号没有问题，没有被封。请问这个错误如何解决，谢谢。

**Comment by zhayujie** [comment]
@charles365ab1 确认下你启动app.py 的python版本是3.8嘛

**Comment by charles365ab1** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/128054168/225785641-bf685799-ef88-43e6-b14a-90ee3ca182c5.png">
使用的是3.8的

**Comment by wangziqin123** [comment]
> itchat



> pip3 安装 itchat-uos
