### ISSUE TITLE
网页端受到限制无法登陆

### ISSUE THREAD

**Issue by Leceue** [zhayujie/chatgpt-on-wechat#493]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

在扫描二维码之后，仍然无法登录

### 终端日志 (如有报错)

```
Your wechat account may be LIMITED to log in WEB wechat, error info:
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  3.9.0：                      
 - pip版本 2023.0.1：

**Comment by Leceue** [comment]
补充 Window10

**Comment by Leceue** [comment]
> 执行看下结果： pip3 show itchat-uos pip3 show itchat
> 
> 如果没有 itchat-uos 要安装下

itchat没有下载，需要下载吗

**Comment by zhayujie** [comment]
@Leceue  itchat正常就是没有的，只要 itchat-uos

**Comment by Leceue** [comment]
但是我有uos
![image](https://user-images.githubusercontent.com/52389430/225620722-0bf194c4-0306-4ec0-8a0d-b12648b491d2.png)

**Comment by zhayujie** [comment]
@Leceue 看下账号是不是被限制或者冻结了

**Comment by Leceue** [comment]
重装之后解决了，非常感谢
