### ISSUE TITLE
注意，Plus不在服务地区的ip调用api也会被封！

### ISSUE THREAD

**Issue by kurpaikt** [zhayujie/chatgpt-on-wechat#495]
![微信图片_20230317061206](https://user-images.githubusercontent.com/84442576/225764440-c1e8c719-0960-4df4-bc4c-b6a8a607eeac.png)
![微信图片_20230317061134](https://user-images.githubusercontent.com/84442576/225764447-d170cd39-3df2-40ea-b82e-a0674b3a18b2.png)
![微信图片_20230317061117](https://user-images.githubusercontent.com/84442576/225764455-6a8e2d00-20a6-494f-afe2-0993ff88b4c9.png)

钞能力也没用，封api直接连账号一起封。充了PLUS没半天就封号了，大无语事件。

**Comment by eiyen** [comment]
用户也需要翻墙才能用API吗

**Comment by charles365ab1** [comment]
我也是plus，

> ![微信图片_20230317061206](https://user-images.githubusercontent.com/84442576/225764440-c1e8c719-0960-4df4-bc4c-b6a8a607eeac.png) ![微信图片_20230317061134](https://user-images.githubusercontent.com/84442576/225764447-d170cd39-3df2-40ea-b82e-a0674b3a18b2.png) ![微信图片_20230317061117](https://user-images.githubusercontent.com/84442576/225764455-6a8e2d00-20a6-494f-afe2-0993ff88b4c9.png)
> 
> 钞能力也没用，封api直接连账号一起封。充了PLUS没半天就封号了，大无语事件。

哈哈，我也是，我被封了7，8个账号，我寻思充个plus试试吧，结果也是瞬间就被封了，真乃无语。我被封是因为使用的是阿里云的北美服务器。后来换成aws了，目前还没被封。

**Comment by logan333111** [comment]
我下午试了好几个号，都是秒封，这个原因有谁知道吗

**Comment by naonaoming** [comment]
今天试了下接入微信也被封了，整个OpenAI账号都不给用了，原因也不清楚；
然后试了是现在QQ和163邮箱也不给注册了

**Comment by HenMie** [comment]
但我暂时没出现状况呀，一个月左右了，香港IP

**Comment by 853126386** [comment]
> 我也是plus，
> 
> > ![微信图片_20230317061206](https://user-images.githubusercontent.com/84442576/225764440-c1e8c719-0960-4df4-bc4c-b6a8a607eeac.png) ![微信图片_20230317061134](https://user-images.githubusercontent.com/84442576/225764447-d170cd39-3df2-40ea-b82e-a0674b3a18b2.png) ![微信图片_20230317061117](https://user-images.githubusercontent.com/84442576/225764455-6a8e2d00-20a6-494f-afe2-0993ff88b4c9.png)
> > 钞能力也没用，封api直接连账号一起封。充了PLUS没半天就封号了，大无语事件。
> 
> 哈哈，我也是，我被封了7，8个账号，我寻思充个plus试试吧，结果也是瞬间就被封了，真乃无语。我被封是因为使用的是阿里云的北美服务器。后来换成aws了，目前还没被封。

现在咋样了，换成aws还好吗

**Comment by kurpaikt** [comment]
> 
aws美区的也不行，换了azure可以。

**Comment by charles365ab1** [comment]
> 

换成AWS的北美用了快一周了，没有问题

**Comment by laohuan12138** [comment]
> 

你是不是几乎没调用过哈哈哈

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227758922-3e6df7d5-19ff-4f9d-98c7-b4f2c062e04a.png)

**Comment by li-aolong** [comment]
> 搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者： ![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227758922-3e6df7d5-19ff-4f9d-98c7-b4f2c062e04a.png)

能再发一个二维码么

**Comment by AI-Rocket-Camp** [comment]
> > 搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者： ![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227758922-3e6df7d5-19ff-4f9d-98c7-b4f2c062e04a.png)
> 
> 能再发一个二维码么

现在群聊接近二百人了，二维码也失效，请加微信AI-camp-666，然后拉进群

**Comment by AI-Rocket-Camp** [comment]
> 能再发一个二维码么？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月31日(周五) 晚上8:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [zhayujie/chatgpt-on-wechat] 注意，Plus不在服务地区的ip调用api也会被封！ (Issue #495) 搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者： 能再发一个二维码么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

现在群聊接近二百人了，二维码也失效，请加微信AI-camp-666，然后拉进群
