### ISSUE TITLE
加了第三个群无回复

### ISSUE THREAD

**Issue by kine0808** [zhayujie/chatgpt-on-wechat#502]
一切都正常但是加了第三个群没有反应

**Comment by YaxinCui** [comment]
顶，我也是

**Comment by YaxinCui** [comment]
我是在超过3个人的大群里，机器人就没有反应。

**Comment by vaan89** [comment]
封号神器 尽量不要用

**Comment by zhayujie** [comment]
群名有加在配置吗

**Comment by MinovskyRickland** [comment]
我有另外一个情况，把机器人加入群里，起名叫张三，当第1个人@张三  与机器人发生对话回复后，如果机器人后面改名叫李四，@李四就不能回应了，必须重新@张三 ，或者关闭重新执行程序。
试过改备注，退群再加群，以及不同人@均不行

**Comment by YaxinCui** [comment]
> 

群昵称也有随之变化，不然没反应。
