### ISSUE TITLE
语音消息无法接收，但无报错

### ISSUE THREAD

**Issue by jlynnc** [zhayujie/chatgpt-on-wechat#503]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

<img width="876" alt="image" src="https://user-images.githubusercontent.com/21292983/226107129-9d521195-5a53-4540-9f06-ebf682d6bfc6.png">
如上图所示，所有转换一切正常，send_file方法也已经调用了，但是并没有收到，此时，文字消息还能继续发送，但是语音功能就完全不能使用了

我使用的是google voice，也已经使用pip安装了itchat

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Jwnie** [comment]
+1， 但我是 能登录成功， cmd窗口会回复， 但微信收不到 回复的消息:
![image](https://user-images.githubusercontent.com/13820400/226532810-21122a91-40c3-4489-a615-2b8685343796.png)

**Comment by Tyler913** [comment]
same

**Comment by luluo123** [comment]
我排查出来的问题用“语音回复”这个文件名貌似会乱码，所以将“语音回复”改成英文就能发送了

**Comment by jlynnc** [comment]
> 我排查出来的问题用“语音回复”这个文件名貌似会乱码，所以将“语音回复”改成英文就能发送了

哦，我尝试一下
