### ISSUE TITLE
登陆不了，怎样不需要实名登陆？

### ISSUE THREAD

**Issue by guocity** [zhayujie/chatgpt-on-wechat#508]
![issue](https://user-images.githubusercontent.com/1127820/226142155-96cd9d40-cda6-40dd-baf5-58ca1f39b9c3.jpg)

**Comment by q23339860** [comment]
应该需要实名账号

**Comment by guocity** [comment]
> 应该需要实名账号

那海外怎么解决实名账号？

**Comment by zhayujie** [comment]
@guocity 海外账号登录不了哈

**Comment by guocity** [comment]
> @guocity 海外账号登录不了哈

是啊，海外服务很差，

**Comment by jiferent** [comment]
> 对了，可不可以fix 一下，不需要实名也可以登陆？

不可能，这是wx控制的，底层就是需要登陆网页版wx。
