### ISSUE TITLE
大佬能优化一下吗？有时人多点会漏不少问题，能否多线程处理

### ISSUE THREAD

**Issue by Rwindest168888** [zhayujie/chatgpt-on-wechat#51]
大佬能优化一下吗？有时人多点会漏不少问题，能否多线程处理？谢谢

**Comment by zhayujie** [comment]
目前就是多线程并发处理的， 漏问题 可能和最近常出现的 RateLimitError 有关系，这个我想办法优化下

之后如果遇到对话没有回复的，可以关注下当时日志有没有报错， 贴出来方便我定位下问题

**Comment by Rwindest168888** [comment]
好的，大佬，好像就是这个问题openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!

**Comment by zhayujie** [comment]
see #50
