### ISSUE TITLE
其他的都弄好了，就是现在好像连不上api

### ISSUE THREAD

**Issue by q23339860** [zhayujie/chatgpt-on-wechat#516]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

[WARNING][2023-03-19 12:50:18][chat_gpt_bot.py:90] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde5f7832e0>: Failed to establish a new connection: [Errno 110] Connection timed out')))
[WARNING][2023-03-19 12:50:18][chat_gpt_bot.py:91] - [OPEN_AI] APIConnection failed
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：全部满足
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Chinesejzp** [comment]
请问怎么解决啦~

**Comment by q23339860** [comment]
我本来就是海外服务器又去加了代理就连不上了&hellip;&hellip;&hellip;


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516)




 
请问怎么解决啦~
 
&mdash;

**Comment by Chinesejzp** [comment]
怎么解决呀，我快崩了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516)





 我本来就是海外服务器又去加了代理就连不上了&amp;hellip;&amp;hellip;&amp;hellip; 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年3月26日(周日) 晚上8:17 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;&amp;quot;State ***@***.***&amp;gt;; 
 主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516) 
 
 
 
 
   
 请问怎么解决啦~ 
   
 &amp;mdash;

**Comment by 2734847914** [comment]
问一下，解决了吗？

**Comment by q23339860** [comment]
解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上10:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516)




 
问一下，解决了吗？

**Comment by 2734847914** [comment]
> 解决了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月28日(周二) 晚上10:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516) 问一下，解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

怎么解决的啊，半天没搞懂，求教一下

**Comment by Chinesejzp** [comment]
可以交一下吗,我不会写python代码,现在苦了好久,能把您的代码发一下,或者加一个微信嘛






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516)





 解决了 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年3月28日(周二) 晚上10:03 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516) 
 
 
 
 
   
 问一下，解决了吗？

**Comment by q23339860** [comment]
可以的，这边加zhouyunjie003



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月29日(周三) 上午8:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516)




 可以交一下吗,我不会写python代码,现在苦了好久,能把您的代码发一下,或者加一个微信嘛 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月28日(星期二) 晚上10:04 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516) 
 
 
 
 
 
  解决了  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年3月28日(周二) 晚上10:03  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题: Re: [zhayujie/chatgpt-on-wechat] 其他的都弄好了，就是现在好像连不上api (Issue #516)  
   
   
   
   
     
  问一下，解决了吗？
