### ISSUE TITLE
text to voice 无法配置google的key

### ISSUE THREAD

**Issue by charleschen2006** [zhayujie/chatgpt-on-wechat#519]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

想使用google语音回复，怎么配置google的api key呢？全文都只有baidu的

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
目前没做成配置，要在代码里修改下

<img width="717" alt="image" src="https://user-images.githubusercontent.com/26161723/226193289-b0ba03c5-e395-4ca5-b86e-65a5ba53da65.png">

相应参数改成 "google"

**Comment by charleschen2006** [comment]
已解决。google采用的办法不同，在环境变量中指定专门的key文件
