### ISSUE TITLE
请问大佬，#清除记忆 指令是清除说话人之前的会话上下文数据，还是清除所有人上下文数据呢？

### ISSUE THREAD

**Issue by Johnny970** [zhayujie/chatgpt-on-wechat#52]
如题

**Comment by zhayujie** [comment]
只清除指令发送人的

**Comment by Johnny970** [comment]
> 只清除指令发送人的

那如何清除所有人的记忆呢？是直接关闭下线微信，终止程序运行，还是有其他的操作咧？

**Comment by zhayujie** [comment]
清除所有人的暂时没有实现，目前只能通过重启程序

你是有这个需求嘛，是什么样的场景

**Comment by Johnny970** [comment]
> 清除所有人的暂时没有实现，目前只能通过重启程序
> 
> 你是有这个需求嘛，是什么样的场景

嗯，是有一个群的老师会问各种各样的问题，而且提问间隔短，内容也多，大部分都是直接写一篇作文之类，我会担心答案串了或者openai.error.RateLimitError的问题频现。重启程序就是关掉重开，重新扫码登录就可以了是吗？我目前是用vscode里面调试打开的。

**Comment by zhayujie** [comment]
> 嗯，是有一个群的老师会问各种各样的问题，而且提问间隔短，内容也多，大部分都是直接写一篇作文之类，我会担心答案串了或者openai.error.RateLimitError的问题频现。重启程序就是关掉重开，重新扫码登录就可以了是吗？我目前是用vscode里面调试打开的。

是的，关掉重新登录就好了。  不过清除会话和RateLimitError倒没关系。

你这个场景是不是不需要多轮会话， 是不是我们增加一个开关，支持关闭上下文记忆会更好？

**Comment by Johnny970** [comment]
> > 嗯，是有一个群的老师会问各种各样的问题，而且提问间隔短，内容也多，大部分都是直接写一篇作文之类，我会担心答案串了或者openai.error.RateLimitError的问题频现。重启程序就是关掉重开，重新扫码登录就可以了是吗？我目前是用vscode里面调试打开的。
> 
> 是的，关掉重新登录就好了。 不过清除会话和RateLimitError倒没关系。
> 
> 你这个场景是不是不需要多轮会话， 是不是我们增加一个开关，支持关闭上下文记忆会更好？

是的，这个功能看起来很好。辛苦大佬看看怎么实现。我这个场景多轮对话是需要的，因为有的人觉得答案不清楚或者不太好的话，会提出follow-up的修正和补充细节。

**Comment by zhayujie** [comment]
> > > 嗯，是有一个群的老师会问各种各样的问题，而且提问间隔短，内容也多，大部分都是直接写一篇作文之类，我会担心答案串了或者openai.error.RateLimitError的问题频现。重启程序就是关掉重开，重新扫码登录就可以了是吗？我目前是用vscode里面调试打开的。
> > 
> > 
> > 是的，关掉重新登录就好了。 不过清除会话和RateLimitError倒没关系。
> > 你这个场景是不是不需要多轮会话， 是不是我们增加一个开关，支持关闭上下文记忆会更好？
> 
> 是的，这个功能看起来很好。辛苦大佬看看怎么实现。我这个场景多轮对话是需要的，因为有的人觉得答案不清楚或者不太好的话，会提出follow-up的修正和补充细节。

好的，那我先加一个 #清除所有 的指令， 只有机器人自己给自己发才生效，你看可以不？

**Comment by Johnny970** [comment]
嗯嗯，可以，感谢大佬！

**Comment by Johnny970** [comment]
> > > > 嗯，是有一个群的老师会问各种各样的问题，而且提问间隔短，内容也多，大部分都是直接写一篇作文之类，我会担心答案串了或者openai.error.RateLimitError的问题频现。重启程序就是关掉重开，重新扫码登录就可以了是吗？我目前是用vscode里面调试打开的。
> > > 
> > > 
> > > 是的，关掉重新登录就好了。 不过清除会话和RateLimitError倒没关系。
> > > 你这个场景是不是不需要多轮会话， 是不是我们增加一个开关，支持关闭上下文记忆会更好？
> > 
> > 
> > 是的，这个功能看起来很好。辛苦大佬看看怎么实现。我这个场景多轮对话是需要的，因为有的人觉得答案不清楚或者不太好的话，会提出follow-up的修正和补充细节。
> 
> 好的，那我先加一个 #清除所有 的指令， 只有机器人自己给自己发才生效，你看可以不？

就是我用机器人微信艾特自己，发送这个指令就可以了对吗？

**Comment by zhayujie** [comment]
> > > > > 嗯，是有一个群的老师会问各种各样的问题，而且提问间隔短，内容也多，大部分都是直接写一篇作文之类，我会担心答案串了或者openai.error.RateLimitError的问题频现。重启程序就是关掉重开，重新扫码登录就可以了是吗？我目前是用vscode里面调试打开的。
> > > > 
> > > > 
> > > > 是的，关掉重新登录就好了。 不过清除会话和RateLimitError倒没关系。
> > > > 你这个场景是不是不需要多轮会话， 是不是我们增加一个开关，支持关闭上下文记忆会更好？
> > > 
> > > 
> > > 是的，这个功能看起来很好。辛苦大佬看看怎么实现。我这个场景多轮对话是需要的，因为有的人觉得答案不清楚或者不太好的话，会提出follow-up的修正和补充细节。
> > 
> > 
> > 好的，那我先加一个 #清除所有 的指令， 只有机器人自己给自己发才生效，你看可以不？
> 
> 就是我用机器人微信艾特自己，发送这个指令就可以了对吗？

晚点我更新了通知你

**Comment by zhayujie** [comment]
这个功能暂时没来得及弄，不过我优化了下 RateLimitError 的问题， 你明天看下有没有问题，  如果没法解决的话我再加下这个指令

**Comment by Johnny970** [comment]
> 这个功能暂时没来得及弄，不过我优化了下 RateLimitError 的问题， 你明天看下有没有问题， 如果没法解决的话我再加下这个指令

辛苦了，谢谢

**Comment by ynzheng** [comment]
#清除记忆 指令

没看到有这个指令的说明啊

**Comment by Rwindest168888** [comment]
> > #清除记忆 指令
> > 没看到有这个指令的说明啊
> 
> 这个我还在调试，只在代码里有， 不过你可以先用用看

今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。

**Comment by zhayujie** [comment]
> > > #清除记忆 指令
> > > 没看到有这个指令的说明啊
> > 
> > 
> > 这个我还在调试，只在代码里有， 不过你可以先用用看
> 
> 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。

你是说想默认不使用上下文对话吗？

**Comment by Rwindest168888** [comment]
就是重新执行代码后，一下子问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆不再向api人家提交不，谢谢

> > > > #清除记忆 指令
> > > > 没看到有这个指令的说明啊
> > > 
> > > 
> > > 这个我还在调试，只在代码里有， 不过你可以先用用看
> > 
> > 
> > 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。
> 
> 你是说想默认不使用上下文对话吗？

就是重新执行代码后，一下子好友问过的问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆，不再向api人家提交不，谢谢

**Comment by zhayujie** [comment]
> 就是重新执行代码后，一下子问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆不再向api人家提交不，谢谢
> 
> > > > > #清除记忆 指令
> > > > > 没看到有这个指令的说明啊
> > > > 
> > > > 
> > > > 这个我还在调试，只在代码里有， 不过你可以先用用看
> > > 
> > > 
> > > 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。
> > 
> > 
> > 你是说想默认不使用上下文对话吗？
> 
> 就是重新执行代码后，一下子好友问过的问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆，不再向api人家提交不，谢谢

不会这样的，重启代码之后，所有记忆自动就清除了，  重启前的问题不会再发送了， 除非好友重新提问

**Comment by Rwindest168888** [comment]
> > 就是重新执行代码后，一下子问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆不再向api人家提交不，谢谢
> > > > > > #清除记忆 指令
> > > > > > 没看到有这个指令的说明啊
> > > > > 
> > > > > 
> > > > > 这个我还在调试，只在代码里有， 不过你可以先用用看
> > > > 
> > > > 
> > > > 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。
> > > 
> > > 
> > > 你是说想默认不使用上下文对话吗？
> > 
> > 
> > 就是重新执行代码后，一下子好友问过的问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆，不再向api人家提交不，谢谢
> 
> 不会这样的，重启代码之后，所有记忆自动就清除了， 重启前的问题不会再发送了， 除非好友重新提问

我今天重启了几次，一堆长文都是几小时前的提问，重新返回答案给他们，我有空再试下吧，谢谢了。

**Comment by Rwindest168888** [comment]
是不是与我删了那个itchat.pkl,弄重新扫码有关，我再试下吧

**Comment by zhayujie** [comment]
> > > 就是重新执行代码后，一下子问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆不再向api人家提交不，谢谢
> > > > > > > #清除记忆 指令
> > > > > > > 没看到有这个指令的说明啊
> > > > > > 
> > > > > > 
> > > > > > 这个我还在调试，只在代码里有， 不过你可以先用用看
> > > > > 
> > > > > 
> > > > > 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。
> > > > 
> > > > 
> > > > 你是说想默认不使用上下文对话吗？
> > > 
> > > 
> > > 就是重新执行代码后，一下子好友问过的问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆，不再向api人家提交不，谢谢
> > 
> > 
> > 不会这样的，重启代码之后，所有记忆自动就清除了， 重启前的问题不会再发送了， 除非好友重新提问
> 
> 我今天重启了几次，一堆长文都是几小时前的提问，重新返回答案给他们，我有空再试下吧，谢谢了。

应该不会有这种情况，你是在服务器还是本地， 换账号登录了吗

**Comment by dcLunatic** [comment]
> > > 就是重新执行代码后，一下子问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆不再向api人家提交不，谢谢
> > > > > > > #清除记忆 指令
> > > > > > > 没看到有这个指令的说明啊
> > > > > > 
> > > > > > 
> > > > > > 这个我还在调试，只在代码里有， 不过你可以先用用看
> > > > > 
> > > > > 
> > > > > 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。
> > > > 
> > > > 
> > > > 你是说想默认不使用上下文对话吗？
> > > 
> > > 
> > > 就是重新执行代码后，一下子好友问过的问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆，不再向api人家提交不，谢谢
> > 
> > 
> > 不会这样的，重启代码之后，所有记忆自动就清除了， 重启前的问题不会再发送了， 除非好友重新提问
> 
> 我今天重启了几次，一堆长文都是几小时前的提问，重新返回答案给他们，我有空再试下吧，谢谢了。

这个问题我在另外一个库中有遇到过

**Comment by dcLunatic** [comment]
> > > 就是重新执行代码后，一下子问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆不再向api人家提交不，谢谢
> > > > > > > #清除记忆 指令
> > > > > > > 没看到有这个指令的说明啊
> > > > > > 
> > > > > > 
> > > > > > 这个我还在调试，只在代码里有， 不过你可以先用用看
> > > > > 
> > > > > 
> > > > > 今天一下子用了6美金的流量，就是因为我调试代码，重新登录了几次微信，然后好友问的问题，又重新问一次发到opeanapiＩ那了，流费了好多额度，大佬，几时能搞好这问题。
> > > > 
> > > > 
> > > > 你是说想默认不使用上下文对话吗？
> > > 
> > > 
> > > 就是重新执行代码后，一下子好友问过的问题，重新向API那提问，然后又返回给好友，一下子好多条。有办法清除这些记忆，不再向api人家提交不，谢谢
> > 
> > 
> > 不会这样的，重启代码之后，所有记忆自动就清除了， 重启前的问题不会再发送了， 除非好友重新提问
> 
> 我今天重启了几次，一堆长文都是几小时前的提问，重新返回答案给他们，我有空再试下吧，谢谢了。

这个问题我在另外一个库有遇到过[ChatGPT-wechat-bot](https://github.com/AutumnWhj/ChatGPT-wechat-bot)，具体原因没看，不知道那边修了没，或许你可以参考下

**Comment by linkboy2007** [comment]
的确需要 #清除所有   而且需要定期执行。我发现聊天内容超过3000字（可能）就会导致出错。
