### ISSUE TITLE
画图报错 AttributeError: module 'openai' has no attribute 'Image'

### ISSUE THREAD

**Issue by wangken82** [zhayujie/chatgpt-on-wechat#53]
[INFO][2023-02-06 12:32:52][open_ai_bot.py:60] - [OPEN_AI] image_query=一只老虎
[ERROR][2023-02-06 12:32:52][open_ai_bot.py:69] - module 'openai' has no attribute 'Image'
Traceback (most recent call last):
  File "/chatgpt/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 61, in create_img
    response = openai.Image.create(
AttributeError: module 'openai' has no attribute 'Image'

**Comment by zhayujie** [comment]
你的openai版本是多少，需要是 0.25.0 以上才能支持画图

**Comment by zhayujie** [comment]
查看openai当前版本:
```
pip3 show openai
```
> 注意要使用 用来运行程序的python 下的 pip

**Comment by Referer01** [comment]
> 你的openai版本是多少，需要是 0.25.0 以上才能支持画图
我的 Version: 0.8.0  也不行  报错
] - module 'openai' has no attribute 'Image'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 72, in create_img
    response = openai.Image.create(
AttributeError: module 'openai' has no attribute 'Image'

**Comment by zhayujie** [comment]
> > 你的openai版本是多少，需要是 0.25.0 以上才能支持画图
> > 我的 Version: 0.8.0  也不行  报错
> > ] - module 'openai' has no attribute 'Image'
> > Traceback (most recent call last):
> > File "/root/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 72, in create_img
> > response = openai.Image.create(
> > AttributeError: module 'openai' has no attribute 'Image'

0.8.0 不够，需要升级

**Comment by BadwomenzzzZ** [comment]
@zhayujie 怎么升级版本啊，我发现pip的镜像网站里面没有这个版本的openai了

**Comment by zhayujie** [comment]
> @zhayujie 怎么升级版本啊，我发现pip的镜像网站里面没有这个版本的openai了

pip3 install --upgrade openai -i https://pypi.tuna.tsinghua.edu.cn/simple
