### ISSUE TITLE
App startup failed!

### ISSUE THREAD

**Issue by laowaiz** [zhayujie/chatgpt-on-wechat#532]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 显示以下错误，无法运行，是字符编码的问题吗？
(base) E:\chatgpt-on-wechat-master>python app.py
[ERROR][2023-03-21 15:17:16][app.py:19] - App startup failed!
[ERROR][2023-03-21 15:17:16][app.py:20] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "E:\chatgpt-on-wechat-master\app.py", line 11, in <module>
    config.load_config()
  File "E:\chatgpt-on-wechat-master\config.py", line 18, in load_config
    config = json.loads(config_str)
  File "e:\Anaconda3\lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Windows)：
 - Python版本  ( 执行 `python3 -V` )：      3.9.13                
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.2.2

**Comment by laowaiz** [comment]
直接下载，按要求修改的，启动失败

**Comment by zhayujie** [comment]
config.json 修改的时候 改变了编码， 可以换个编辑器试试
