### ISSUE TITLE
想用wechaty功能，出现错误，请问怎么解决啊？

### ISSUE THREAD

**Issue by yysuper008** [zhayujie/chatgpt-on-wechat#533]
/usr/local/python39/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[ERROR][2023-03-21 15:41:43][app.py:19] - App startup failed!
[ERROR][2023-03-21 15:41:43][app.py:20] - str expected, not NoneType
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-master/app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat-master/channel/wechat/wechaty_channel.py", line 32, in startup
    asyncio.run(self.main())
  File "/usr/local/python39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/chatgpt-on-wechat-master/channel/wechat/wechaty_channel.py", line 38, in main
    os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token
  File "/usr/local/python39/lib/python3.9/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/python39/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

**Comment by lihuaiyu0131** [comment]
应该是Python环境问题，`Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work`

**Comment by Chiaki-Chan** [comment]
大兄弟，要装 ffmpeg的。

**Comment by yysuper008** [comment]
<img width="1131" alt="微信截图_20230321194001" src="https://user-images.githubusercontent.com/66710185/226595669-d55f5720-1d98-4971-a696-cfeacb5680
千秋老师，我用的centos系统 我是yum install ffmpeg espeak安装的时候出错了。这个是怎么回事啊

**Comment by yysuper008** [comment]
千秋兄，我用的centos系统 我是yum install ffmpeg espeak安装的时候出错了。这个是怎么回事啊
libogg-1.3.0-7.el7.x86_64.rpm  FAILED                                          
http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libogg-1.3.0-7.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"]  0.0 B/s |    0 B  --:--:-- ETA 
正在尝试其它镜像。
libvorbis-1.3.3-8.el7.1.x86_64 FAILED                                          
http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libvorbis-1.3.3-8.el7.1.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"0 B/s |    0 B  --:--:-- ETA 
正在尝试其它镜像。
libsndfile-1.0.25-12.el7_9.1.x FAILED                                          
http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/libsndfile-1.0.25-12.el7_9.1.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error" 0 B  --:--:-- ETA 
正在尝试其它镜像。
pulseaudio-libs-10.0-6.el7_9.x FAILED                                          
http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/pulseaudio-libs-10.0-6.el7_9.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error" 0 B  --:--:-- ETA 
正在尝试其它镜像。


Error downloading packages:
  libasyncns-0.8-7.el7.x86_64: [Errno 256] No more mirrors to try.
  1:libvorbis-1.3.3-8.el7.1.x86_64: [Errno 256] No more mirrors to try.
  pulseaudio-libs-10.0-6.el7_9.x86_64: [Errno 256] No more mirrors to try.
  flac-libs-1.3.0-5.el7_1.x86_64: [Errno 256] No more mirrors to try.
  gsm-1.0.13-11.el7.x86_64: [Errno 256] No more mirrors to try.
  2:libogg-1.3.0-7.el7.x86_64: [Errno 256] No more mirrors to try.
  libsndfile-1.0.25-12.el7_9.1.x86_64: [Errno 256] No more mirrors to try.
  espeak-1.47.11-4.el7.x86_64: [Errno 256] No more mirrors to try.
  libXtst-1.2.3-1.el7.x86_64: [Errno 256] No more mirrors to try.

**Comment by yysuper008** [comment]
@Chiaki-Chan 
千秋兄，我用的centos系统 我是yum install ffmpeg espeak安装的时候出错了。这个是怎么回事啊
libogg-1.3.0-7.el7.x86_64.rpm 失败
http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libogg-1.3.0-7.el7.x86_64.rpm： [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“] 0.0 B/s |0 B --：--：-- ETA
正在尝试其它镜像。
libvorbis-1.3.3-8.el7.1.x86_64 失败
http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libvorbis-1.3.3-8.el7.1.x86_64.rpm： [错误 14] curl#6 - “无法解析主机：mirrors.cloud.aliyuncs.com;未知错误“0 B/s |0 B --：--：-- ETA
正在尝试其它镜像。
libsndfile-1.0.25-12.el7_9.1.x 失败
http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/libsndfile-1.0.25-12.el7_9.1.x86_64.rpm： [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“ 0 B --：--：-- ETA
正在尝试其它镜像。
pulseaudio-libs-10.0-6.el7_9.x 失败
http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/pulseaudio-libs-10.0-6.el7_9.x86_64.rpm： [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“ 0 B --：--：-- ETA
正在尝试其它镜像。

下载软件包时出错： libasyncns-0.8-7.el7.x86_64：
[Errno 256] 没有更多的镜像可以尝试。
1：libvorbis-1.3.3-8.el7.1.x86_64： [Errno 256] 没有更多的镜像可以尝试。
pulseaudio-libs-10.0-6.el7_9.x86_64： [Errno 256] 没有更多的镜像可以尝试。
flac-libs-1.3.0-5.el7_1.x86_64： [Errno 256] 没有更多的镜像可以尝试。
gsm-1.0.13-11.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。
2：libogg-1.3.0-7.el7.x86_64： [Errno 256] 没有更多的镜子可以尝试。
libsndfile-1.0.25-12.el7_9.1.x86_64： [Errno 256] 没有更多的镜像可以尝试。
espeak-1.47.11-4.el7.x86_64： [Errno 256] 没有更多的镜子可以尝试了。
libXtst-1.2.3-1.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。

**Comment by yysuper008** [comment]
> 

111

**Comment by lihuaiyu0131** [comment]
要编译安装

**Comment by yysuper008** [comment]
@lihuaiyu0131 请教下怎么编译安装啊？我用的centos系统 教我一下呗谢谢了

**Comment by yysuper008** [comment]
> 大兄弟，要装 ffmpeg的。
> 
> 安装 ffmpeg 和 espeak
> 
> * MacOS: brew install ffmpeg espeak
> * Windows: 下载ffmpeg.exe
> * Linux: apt-get install ffmpeg espeak
> 
> 注：在itchat中只能回复mp3文件；在wechaty中可以回复语音消息，wechaty中使用需要安装额外依赖：
> 
> pip3 install pysilk pip3 install pysilk-mod pip3 install pydub

1111

**Comment by yysuper008** [comment]
> @Chiaki-Chan 千秋兄，我用的centos系统 我是yum install ffmpeg espeak安装的时候出错了。这个是怎么回事啊 libogg-1.3.0-7.el7.x86_64.rpm 失败 [http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libogg-1.3.0-7.el7.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libogg-1.3.0-7.el7.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“] 0.0 B/s |0 B --：--：-- ETA 正在尝试其它镜像。 libvorbis-1.3.3-8.el7.1.x86_64 失败 [http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libvorbis-1.3.3-8.el7.1.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libvorbis-1.3.3-8.el7.1.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机：mirrors.cloud.aliyuncs.com;未知错误“0 B/s |0 B --：--：-- ETA 正在尝试其它镜像。 libsndfile-1.0.25-12.el7_9.1.x 失败 [http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/libsndfile-1.0.25-12.el7_9.1.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/libsndfile-1.0.25-12.el7_9.1.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“ 0 B --：--：-- ETA 正在尝试其它镜像。 pulseaudio-libs-10.0-6.el7_9.x 失败 [http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/pulseaudio-libs-10.0-6.el7_9.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/pulseaudio-libs-10.0-6.el7_9.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“ 0 B --：--：-- ETA 正在尝试其它镜像。
> 
> 下载软件包时出错： libasyncns-0.8-7.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。 1：libvorbis-1.3.3-8.el7.1.x86_64： [Errno 256] 没有更多的镜像可以尝试。 pulseaudio-libs-10.0-6.el7_9.x86_64： [Errno 256] 没有更多的镜像可以尝试。 flac-libs-1.3.0-5.el7_1.x86_64： [Errno 256] 没有更多的镜像可以尝试。 gsm-1.0.13-11.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。 2：libogg-1.3.0-7.el7.x86_64： [Errno 256] 没有更多的镜子可以尝试。 libsndfile-1.0.25-12.el7_9.1.x86_64： [Errno 256] 没有更多的镜像可以尝试。 espeak-1.47.11-4.el7.x86_64： [Errno 256] 没有更多的镜子可以尝试了。 libXtst-1.2.3-1.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。

@Chiaki-Chan
千秋兄，我用的centos系统 我是yum install ffmpeg espeak安装的时候出错了。这个是怎么回事啊
libogg-1.3.0-7.el7.x86_64.rpm 失败
[http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libogg-1.3.0-7.el7.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libogg-1.3.0-7.el7.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“] 0.0 B/s |0 B --：--：-- ETA
正在尝试其它镜像。
libvorbis-1.3.3-8.el7.1.x86_64 失败
[http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libvorbis-1.3.3-8.el7.1.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/Packages/libvorbis-1.3.3-8.el7.1.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机：mirrors.cloud.aliyuncs.com;未知错误“0 B/s |0 B --：--：-- ETA
正在尝试其它镜像。
libsndfile-1.0.25-12.el7_9.1.x 失败
[http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/libsndfile-1.0.25-12.el7_9.1.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/libsndfile-1.0.25-12.el7_9.1.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“ 0 B --：--：-- ETA
正在尝试其它镜像。
pulseaudio-libs-10.0-6.el7_9.x 失败
[http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/pulseaudio-libs-10.0-6.el7_9.x86_64.rpm：](http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/Packages/pulseaudio-libs-10.0-6.el7_9.x86_64.rpm%EF%BC%9A) [错误 14] curl#6 - “无法解析主机： mirrors.cloud.aliyuncs.com;未知错误“ 0 B --：--：-- ETA
正在尝试其它镜像。

下载软件包时出错： libasyncns-0.8-7.el7.x86_64：
[Errno 256] 没有更多的镜像可以尝试。
1：libvorbis-1.3.3-8.el7.1.x86_64： [Errno 256] 没有更多的镜像可以尝试。
pulseaudio-libs-10.0-6.el7_9.x86_64： [Errno 256] 没有更多的镜像可以尝试。
flac-libs-1.3.0-5.el7_1.x86_64： [Errno 256] 没有更多的镜像可以尝试。
gsm-1.0.13-11.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。
2：libogg-1.3.0-7.el7.x86_64： [Errno 256] 没有更多的镜子可以尝试。
libsndfile-1.0.25-12.el7_9.1.x86_64： [Errno 256] 没有更多的镜像可以尝试。
espeak-1.47.11-4.el7.x86_64： [Errno 256] 没有更多的镜子可以尝试了。
libXtst-1.2.3-1.el7.x86_64： [Errno 256] 没有更多的镜像可以尝试。

**Comment by Chiaki-Chan** [comment]
> 

可以换个yum源试试
比如中科大的，https://mirrors.ustc.edu.cn/help/centos.html

**Comment by yysuper008** [comment]
> > 
> 
> 可以换个yum源试试 比如中科大的，https://mirrors.ustc.edu.cn/help/centos.html
> 
> ## 安装FFmpeg可以通过两种方式来实现：
> 1. 安装官方版本
> 
> CentOS官方软件源中的ffmpeg旧且不够稳定，但您仍然可以使用以下命令安装：
> 
> ```
> sudo yum install ffmpeg
> ```
> 
> 2. 安装最新版本
> 
> 要安装最新版本的FFmpeg，您需要手动安装。以下是在CentOS中安装FFmpeg最新版本的步骤：
> 
> 1. 安装一些必要的工具：
> 
> ```
> sudo yum install epel-release
> sudo yum install autoconf automake cmake freetype-devel gcc gcc-c++ git libtool make mercurial nasm pkgconfig zlib-devel
> ```
> 
> 2. 安装Yasm：
> 
> ```
> cd ~/ffmpeg_sources
> wget -O yasm-1.3.0.tar.gz https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
> tar xzvf yasm-1.3.0.tar.gz
> cd yasm-1.3.0
> ./configure --prefix="/usr/local" --bindir="/usr/local/bin"
> make
> sudo make install
> ```
> 
> 3. 安装x264：
> 
> ```
> cd ~/ffmpeg_sources
> git clone --depth 1 https://code.videolan.org/videolan/x264.git
> cd x264
> PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" ./configure --prefix="/usr/local" --bindir="/usr/local/bin" --enable-static
> make
> sudo make install
> ```
> 
> 4. 安装x265：
> 
> ```
> cd ~/ffmpeg_sources
> hg clone https://bitbucket.org/multicoreware/x265
> cd ~/ffmpeg_sources/x265/build/linux
> cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/usr/local" -DENABLE_SHARED:bool=off ../../source
> make
> sudo make install
> ```
> 
> 5. 安装AAC：
> 
> ```
> cd ~/ffmpeg_sources
> wget -O fdk-aac-2.0.1.tar.gz https://github.com/mstorsjo/fdk-aac/archive/v2.0.1.tar.gz
> tar xzvf fdk-aac-2.0.1.tar.gz
> cd fdk-aac-2.0.1
> autoreconf -fiv
> ./configure --prefix="/usr/local" --disable-shared
> make
> sudo make install
> ```
> 
> 6. 安装LAME：
> 
> ```
> cd ~/ffmpeg_sources
> wget -O lame-3.99.5.tar.gz https://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
> tar xzvf lame-3.99.5.tar.gz
> cd lame-3.99.5
> ./configure --prefix="/usr/local" --bindir="/usr/local/bin" --disable-shared --enable-nasm
> make
> sudo make install
> ```
> 
> 7. 安装Opus：
> 
> ```
> cd ~/ffmpeg_sources
> wget -O opus-1.1.2.tar.gz https://archive.mozilla.org/pub/opus/opus-1.1.2.tar.gz
> tar xzvf opus-1.1.2.tar.gz
> cd opus-1.1.2
> ./configure --prefix="/usr/local" --disable-shared
> make
> sudo make install
> ```
> 
> 8. 安装FFmpeg：
> 
> ```
> cd ~/ffmpeg_sources
> wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
> tar xjvf ffmpeg-snapshot.tar.bz2
> cd ffmpeg
> PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" ./configure --prefix="/usr/local" --bindir="/usr/local/bin" --enable-gpl --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-libx265 --enable-nonfree
> make
> sudo make install
> ```
> 
> 安装完成后，您可以通过以下命令检查FFmpeg是否安装成功：
> 
> ```
> ffmpeg -version
> ```
> 
> ## 要在CentOS中安装eSpeak，您可以按照以下步骤进行：
> 1. 安装espeak及其依赖项：
> 
> ```
> sudo yum install espeak espeak-devel libsndfile
> ```
> 
> 2. 尝试运行espeak：
> 
> ```
> espeak "Hello, world!"
> ```
@Chiaki-Chan 安装是在chatgpt-on-wechat目录下安装对吗？

**Comment by yysuper008** [comment]
> 比如中科大的，https://mirrors.ustc.edu.cn/help/centos.html

@Chiaki-Chan 千秋大师这个镜像是在哪里设置啊？

**Comment by yysuper008** [comment]
> ffmpeg -version

@Chiaki-Chan 大神兄，CentOS-Base.repo 这个文件让我搞乱了，我现在怎么输入命令都出错。

**Comment by yysuper008** [comment]
> sudo yum install ffmpeg

@Chiaki-Chan 
[admin@iZ7xv9dwxu0l7u17aywh4gZ ~]$ sudo yum install ffmpeg
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * centos-sclo-rh: mirror.corbina.net
http://mirrors.cloud.aliyuncs.com/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"
Trying other mirror.


 One of the configured repositories failed (Extra Packages for Enterprise Linux 7 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=epel ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable epel
        or
            subscription-manager repos --disable=epel

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=epel.skip_if_unavailable=true

failure: repodata/repomd.xml from epel: [Errno 256] No more mirrors to try.
http://mirrors.cloud.aliyuncs.com/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"

**Comment by Chiaki-Chan** [comment]
> > ffmpeg -version
> 
> @Chiaki-Chan 大神兄，CentOS-Base.repo 这个文件让我搞乱了，我现在怎么输入命令都出错。

你加我微信(Chiaki-Chen)吧= =

**Comment by yysuper008** [comment]
> 

@Chiaki-Chan 千秋兄我加你的微信了：网名叫追风，账号是YUNY5882
