### ISSUE TITLE
大兄弟，要装 ffmpeg的。

### ISSUE THREAD

**Issue by yysuper008** [zhayujie/chatgpt-on-wechat#538]
大兄弟，要装 ffmpeg的。

安装 ffmpeg 和 espeak

* MacOS: brew install ffmpeg espeak

* Windows: 下载ffmpeg.exe

* Linux: apt-get install ffmpeg espeak

注：在itchat中只能回复mp3文件；在wechaty中可以回复语音消息，wechaty中使用需要安装额外依赖：

pip3 install pysilk
pip3 install pysilk-mod
pip3 install pydub

_Originally posted by @Chiaki-Chan in https://github.com/zhayujie/chatgpt-on-wechat/issues/533#issuecomment-1477556567_

**Comment by Tyler913** [comment]
这就是我看到了语言生成了但是发不出的原因吗

**Comment by LeafBanks** [comment]
我装了还是出错，你跟大神对话那七八个软件我也装了，哈哈

**Comment by LeafBanks** [comment]
> 这就是我看到了语言生成了但是发不出的原因吗

我现在也是这一步，我等下把所有依赖再装一遍

**Comment by doublet44** [comment]
目前到显示已发送MP3文件，但是wx上面不显示

**Comment by LeafBanks** [comment]
> 目前到显示已发送MP3文件，但是wx上面不显示

解决了么？我的wechaty成功，也是微信没回复
