### ISSUE TITLE
关于群聊各用户上下文的能否统一？

### ISSUE THREAD

**Issue by armilkchen** [zhayujie/chatgpt-on-wechat#544]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

群聊基本是每个人@一次bot相当于是一个新的会话，能否多个群友一个会话呢？
这样可以更好的实现一些文字游戏或者讨论

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by sherlockBJ** [comment]
同想问这个问题

**Comment by armilkchen** [comment]
> 请参考 #382

感谢！
