### ISSUE TITLE
config路径设置问题导致找不到config.json文件

### ISSUE THREAD

**Issue by a5225662** [zhayujie/chatgpt-on-wechat#547]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 
简要说明：
1、服务器中项目源代码目录： /chatgpt-on-wechat
2、在使用宝塔面板时的python项目管理器管理项目时发现，当我点击运行代码的时候，config.py找不到我的config.json

3、问题在于使用宝塔面板python项目管理器的时候，它竟然是从系统根目录去找config.json
4、于是乎，当我把config.json复制到 / (根目录)下的时候，程序正常运行，然后二维码也生成在了根目录
5、查看config.py代码后发现，它的第12行代码是（config_path = "config.json"） 这个路径比较模糊
6、测试后，我将config.py第12行代码修改为（config_path = "./config.json"）  这个路径比较确定，当前目录的config.json
7、此时，问题解决，然后也不会影响程序的正常运行。

8、我还想给wechat-on-wechat贡献一个定时开启和发送email提醒的功能，所以这个isuue是我在github上提交的第一个，请问我需要如何做才能将代码贡献进去，这只是一个开始，我想知道从一个issues 到解决到代码测试，到整合到主分支的流程，感谢大佬！
9、宝塔面板python管理器配置图
![image](https://user-images.githubusercontent.com/12531661/226954988-814b3e0f-fc7d-4924-889e-4c056dd9fb02.png)

### 终端日志 (如有报错)

```
[ERROR][2023-03-22 23:26:12][app.py:19] - App startup failed!
[ERROR][2023-03-22 23:26:12][app.py:20] - 配置文件不存在，请根据config-template.json模板创建config.json文件
Traceback (most recent call last):
  File "/chatgpt-on-wechat/app.py", line 11, in <module>
    config.load_config()
  File "/chatgpt-on-wechat/config.py", line 14, in load_config
    raise Exception('配置文件不存在，请根据config-template.json模板创建config.json文件')
Exception: 配置文件不存在，请根据config-template.json模板创建config.json文件
[ERROR][2023-03-22 23:27:03][app.py:19] - App startup failed!
[ERROR][2023-03-22 23:27:03][app.py:20] - 配置文件不存在，请根据config-template.json模板创建config.json文件
Traceback (most recent call last):
  File "/chatgpt-on-wechat/app.py", line 11, in <module>
    config.load_config()
  File "/chatgpt-on-wechat/config.py", line 14, in load_config
    raise Exception('配置文件不存在，请根据config-template.json模板创建config.json文件')
Exception: 配置文件不存在，请根据config-template.json模板创建config.json文件
[ERROR][2023-03-22 23:27:03][app.py:19] - App startup failed!
[ERROR][2023-03-22 23:27:03][app.py:20] - 配置文件不存在，请根据config-template.json模板创建config.json文件
Traceback (most recent call last):
  File "/chatgpt-on-wechat/app.py", line 11, in <module>
    config.load_config()
  File "/chatgpt-on-wechat/config.py", line 14, in load_config
    raise Exception('配置文件不存在，请根据config-template.json模板创建config.json文件')
Exception: 配置文件不存在，请根据config-template.json模板创建config.json文件
```

### 环境

 - Linux：
 - 宝塔面板
 - Python版本  ( 3.7.9)：

**Comment by zhayujie** [comment]
合并的流程：
1. fork项目到自己的仓库
2. 本地修改代码并测试  ( 你改的这个问题涉及相对路径，要测试下在 windows 下能不能兼容 )
3. 提交代码到你的远程分支
4. 发起 Pull Request

**Comment by jason-xiaobaiai** [comment]
有人遇到这样的问题吗，宝塔python项目管理器，日志提示当前的ssl模块是使用较旧的OpenSSL 1.0.2k编译的，需要更新 Python 的 ssl 模块

**Comment by jason-xiaobaiai** [comment]
宝塔python项目文件相对路径一直有问题
