### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by Jacobew** [zhayujie/chatgpt-on-wechat#548]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
config中已配置proxy端口7890端口，请问clash应该怎么设置？
<img width="424" alt="image" src="https://user-images.githubusercontent.com/26053586/226971415-411d44d6-fcb2-46fd-9f70-aadde258bfb5.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/26053586/226971468-b25c621b-f35b-4a97-978d-fdd9a900a3c8.png">
目前在这种设置下无法连接，提示You exceeded your current quota, please check your plan and billing details.

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Mac
 - Python版本  ( 执行 `python3 -V` )： v3.9.7                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.2.4

**Comment by a5225662** [comment]
windows下我的配置，mac系统请搜索mac clash开启全局代理

![image](https://user-images.githubusercontent.com/12531661/226980366-b37e109c-fab3-420c-a472-704d6623338b.png)
![image](https://user-images.githubusercontent.com/12531661/226980555-2c30b046-d944-4d3d-926c-76b3a5e61030.png)

**Comment by zhayujie** [comment]
这个错是openai没有额度了，现在新注册的号没有免费额度了

**Comment by jiaofengzi** [comment]
我也遇到了这个问题，但我检查过免费额度明明还有【

**Comment by Jacobew** [comment]
> 这个错是openai没有额度了，现在新注册的号没有免费额度了

@zhayujie 怎么查看确认是否有免费额度呢？

clash的端口一定是7890么？我看控制台有多个端口，每个节点的配置也有对应的端口
<img width="699" alt="image" src="https://user-images.githubusercontent.com/26053586/227080391-db5bfb46-429b-4798-90d4-d4ad16ca9f73.png">

**Comment by a5225662** [comment]
1.登录：https://platform.openai.com/
2.
![image](https://user-images.githubusercontent.com/12531661/227083437-53f1f98a-1ab6-46b0-a840-ba65e77be626.png)
3.
![image](https://user-images.githubusercontent.com/12531661/227083665-d157c751-e7e7-42e8-9063-4149e465e27b.png)
4.
![image](https://user-images.githubusercontent.com/12531661/227083829-11b2c74a-c42c-4498-a3d9-c79bd0aae1da.png)

**Comment by Jacobew** [comment]
> 这个错是openai没有额度了，现在新注册的号没有免费额度了

@zhayujie 你好，我看了下确实是没有免费额度了，那大陆地区有什么渠道可以申请付费usage呢？除了depay信用卡以外有什么方便的途径不？

**Comment by a5225662** [comment]
新买个账号就可以了

**Comment by Jacobew** [comment]
> 新买个账号就可以了

请问现在还有可靠的买账号的途径吗？
