### ISSUE TITLE
修改图片大小后不生效是怎么回事？

### ISSUE THREAD

**Issue by rklhxyk1128** [zhayujie/chatgpt-on-wechat#552]
def create_img(self, query, retry_count=0):
        try:
            logger.info("[OPEN_AI] image_query={}".format(query))
            response = openai.Image.create(
                prompt=query,    #图片描述
                n=1,             #每次生成图片的数量
                size="1024x1024"   #图片大小,可选有 256x256, 512x512, 1024x1024
            )
            image_url = response['data'][0]['url']
            logger.info("[OPEN_AI] image_url={}".format(image_url))
            return image_url

RT，我参考说明在bot/openai/open_ai_bot.py这样改的，但是回复还是256的图片。 停用进程，重新登录了一下账号也不行

**Comment by aburdchen415** [comment]
chat_gpt_bot.py,修改这个文件
