### ISSUE TITLE
有时候对话会出现错误

### ISSUE THREAD

**Issue by 1579704169** [zhayujie/chatgpt-on-wechat#556]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
有时候对话会出现错误，重新问一下又可以正常对话，但是重新问后，对话的上下文会没有，会直接开始新的对话
> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/105210815/227172091-d1d024ff-daa2-455e-b3c1-4f17983037f5.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
这个是使用openai sdk出现的偶发不稳定
