### ISSUE TITLE
可以正常访问chatgpt，但终端报错：我连接不到你的网络

### ISSUE THREAD

**Issue by Ancss** [zhayujie/chatgpt-on-wechat#560]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

终端报错：我连接不到你的网络

使用clash，可以正常使用chatgpt

这是我的配置
<img width="930" alt="image" src="https://user-images.githubusercontent.com/61501274/227252793-b56b5fd7-419d-4668-99d7-e56d11f7d5cb.png">

这是终端报错截图
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/61501274/227251759-e896475b-c21e-45ae-826b-aad2fb32f010.png">

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：macos
 - Python版本  ( 执行 `python3 -V` )：3.9.6                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.2.4

**Comment by Ancss** [comment]
urllib3进行了降级
也有直接在os.environ里直接加peoxy
```python
import os
os.environ["http_proxy"] = "127.0.0.1:7890"
os.environ["https_proxy"] = "127.0.0.1:7890"
```
但都没有用

如果使用http工具进行对https://api.openai.com/v1/chat/completions 发起请求，是可以请求到的
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/61501274/227301189-ba03f17a-9cd4-4a37-98ce-39a0505a5dd3.png">

不知道还有什么办法可以解决

**Comment by a5225662** [comment]
连不上网的原因可能有很多，节点，梯子本身会挂，配置也会挂，建议选用clash的增强模式试一试，稍后我把教程发出来🙈，测试没问题再改成proxy模式就好了，我基本不用代理模式，因为不想让终端加速还得写环境变量

**Comment by Viceeee** [comment]
> 

有教程么，同求

**Comment by a5225662** [comment]
windows下我的配置，mac系统请搜索mac clash开启全局代理

[image](https://user-images.githubusercontent.com/12531661/226980366-b37e109c-fab3-420c-a472-704d6623338b.png)
[image](https://user-images.githubusercontent.com/12531661/226980555-2c30b046-d944-4d3d-926c-76b3a5e61030.png)

**Comment by a5225662** [comment]
> > 连不上网的原因可能有很多，节点，梯子本身会挂，配置也会挂，建议选用clash的增强模式试一试，稍后我把教程发出来🙈，测试没问题再改成proxy模式就好了，我基本不用代理模式，因为不想让终端加速还得写环境变量
> 
> 有教程吗？球球

跟梯子有关系，你的梯子是什么这个你得知道，他支不支持clash，如果支持的话，步骤是这样的：
1、打开服务模式
![image](https://user-images.githubusercontent.com/12531661/228192357-8969062a-bba1-49dd-9757-1b32b094fd7a.png)
2、打开TUN模式、关闭系统代理
3、选择合适节点(美国、日本、在chatgpt支持范围内的国家的都可以)

**Comment by a5225662** [comment]
> > > 连不上网的原因可能有很多，节点，梯子本身会挂，配置也会挂，建议选用clash的增强模式试一试，稍后我把教程发出来🙈，测试没问题再改成proxy模式就好了，我基本不用代理模式，因为不想让终端加速还得写环境变量
> > 
> > 
> > 有教程吗？球球
> 
> 同求clash增强模式教程！

研究明白了没？

**Comment by hy546880109** [comment]
> urllib3进行了降级 也有直接在os.environ里直接加peoxy
> 
> ```python
> import os
> os.environ["http_proxy"] = "127.0.0.1:7890"
> os.environ["https_proxy"] = "127.0.0.1:7890"
> ```
> 
> 但都没有用
> 
> 如果使用http工具进行对https://api.openai.com/v1/chat/completions 发起请求，是可以请求到的 <img alt="image" width="1094" src="https://user-images.githubusercontent.com/61501274/227301189-ba03f17a-9cd4-4a37-98ce-39a0505a5dd3.png">
> 
> 不知道还有什么办法可以解决

谢谢，这个解决了我本地搭建的问题

**Comment by Viceeee** [comment]
> > > > 连不上网的原因可能有很多，节点，梯子本身会挂，配置也会挂，建议选用clash的增强模式试一试，稍后我把教程发出来🙈，测试没问题再改成proxy模式就好了，我基本不用代理模式，因为不想让终端加速还得写环境变量
> > > 
> > > 
> > > 有教程吗？球球
> > 
> > 
> > 同求clash增强模式教程！
> 
> 研究明白了没？

对于linux的clash你知道怎么用么？

**Comment by a5225662** [comment]
> > > > > 连不上网的原因可能有很多，节点，梯子本身会挂，配置也会挂，建议选用clash的增强模式试一试，稍后我把教程发出来🙈，测试没问题再改成proxy模式就好了，我基本不用代理模式，因为不想让终端加速还得写环境变量
> > > > 
> > > > 
> > > > 有教程吗？球球
> > > 
> > > 
> > > 同求clash增强模式教程！
> > 
> > 
> > 研究明白了没？
> 
> 对于linux的clash你知道怎么用么？

![image](https://user-images.githubusercontent.com/12531661/229047068-3695a427-54cd-484d-ab8e-fcb1472da8ed.png)

**Comment by daerzhu** [comment]
请问这个问题现在解决了吗

**Comment by qcoltma** [comment]
我开启了voice_to_voice为true参数后也出现了这个问题，关了这个参数就好了，很奇怪，难道程序有bug？
