### ISSUE TITLE
可私聊不可群聊问题

### ISSUE THREAD

**Issue by Huasongl** [zhayujie/chatgpt-on-wechat#561]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

可以私聊，但是不能群聊。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
![image](https://user-images.githubusercontent.com/71997252/227263154-be9959e9-f83c-4d67-b01a-12d2960f5294.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python3 -V` )：Python 3.9.12                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.0.4

**Comment by Huasongl** [comment]
添加群聊白名单

**Comment by xxball1111** [comment]
加白名单后是可以的
