### ISSUE TITLE
新功能开发：定时上线下线，不用多次扫码登录

### ISSUE THREAD

**Issue by a5225662** [zhayujie/chatgpt-on-wechat#562]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 由于人懒，不想每天定时定点扫码上线，朋友喊我写个脚本自动上线
于是，在尽量不改动源代码的基础上，加入了time_checker模块，实现了：
1、时间管理功能：插件化，随时开随时关
2、热加载服务时间变化
3、微信只要不自己点退出登录，不会下线，可以长期挂机，定时开启chatgpt服务
4、项目目前已经挂到服务器测试，想提前体验的可以去我的代码仓库去体验一下，测试几天没问题后会提交合并到作者的主分支~
5、感谢作者支持~哈哈

### 终端日志 (如有报错)

```
报了一天错了- -！
找程序流和数据流的工作还是比较麻烦的，不过好在，功能完成了。
```

### 环境

 - 操作系统类型  (Windows/Linux)：
 - Python版本  ( 3.7.16 )：

**Comment by a5225662** [comment]
![Snipaste_2023-03-24_00-20-57](https://user-images.githubusercontent.com/12531661/227271438-5a22b65e-ef68-492d-85ed-45ac9969589b.png)

**Comment by zhayujie** [comment]
已合并 ， 感谢
https://github.com/zhayujie/chatgpt-on-wechat/pull/569
