### ISSUE TITLE
运行脚本报错

### ISSUE THREAD

**Issue by t-aest** [zhayujie/chatgpt-on-wechat#567]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

执行nohup python3 app.py & tail -f nohup.out    报错
ModuleNotFoundError: No module named 'common.log'

### 终端日志 (如有报错)

```
nohup: ignoring input and appending output to ‘nohup.out’
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from common.log import logger
ModuleNotFoundError: No module named 'common.log'
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import config
  File "/home/chatGPT/chatgpt-on-wechat/config.py", line 5, in <module>
    from common.log import logger
ModuleNotFoundError: No module named 'common.log'
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import config
  File "/home/chatGPT/chatgpt-on-wechat/config.py", line 5, in <module>
    from common.log import logger
ModuleNotFoundError: No module named 'common.log'
```

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( Python 3.7.9 )：                      
 - pip版本  ( pip 22.3.1 from /www/server/panel/pyenv/lib/python3.7/site-packages/pip (python 3.7))：

**Comment by zhayujie** [comment]
你是怎么启动的，当前路径是在项目根目录吗

**Comment by t-aest** [comment]
> 你是怎么启动的，当前路径是在项目根目录吗

/chatgpt-on-wechat目录下，含有app.py的目录下
