### ISSUE TITLE
安装的时候提示报错 Could not find a version that satisfies the requirement pandas>=1.2.3 (from openai)

### ISSUE THREAD

**Issue by BaoHeTaiHe** [zhayujie/chatgpt-on-wechat#57]
大佬看看这是啥问题，是环境配置的问题么

pip3 install --upgrade openai
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting openai
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/79/b8/8d3986ab63b4a6d6149d015e3f4ddd3d3eac4a3dc71c484d448f138940e1/openai-0.10.5.tar.gz (157kB)
    100% |████████████████████████████████| 163kB 463kB/s 
Requirement already up-to-date: requests>=2.20 in /usr/local/lib/python3.6/site-packages (from openai)
Collecting tqdm (from openai)
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 371kB/s 
Collecting pandas>=1.2.3 (from openai)
  Could not find a version that satisfies the requirement pandas>=1.2.3 (from openai) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
No matching distribution found for pandas>=1.2.3 (from openai)

**Comment by wzy157179** [comment]
python版本应该是要大于3.7
