### ISSUE TITLE
想问一下，新拉入一个新群回复不了消息，如何发送什么指令让它刷新一下识别新群？

### ISSUE THREAD

**Issue by songdone** [zhayujie/chatgpt-on-wechat#572]
我新拉入一个微信群，都要重启再登录一次才能识别到，不然在新加入的群里@是没回复的，有没有什么指令是直接刷新一下就可以呢？

**Comment by zhayujie** [comment]
新群有群名称嘛， 你配置配的是 ALL_GROUP？

**Comment by songdone** [comment]
> 新群有群名嘛，你配置的是ALL_GROUP？

原来是要改群名称，试了一下可以了
