### ISSUE TITLE
怎么提高画画的清晰度

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#574]
目前运行一切正常，但是画画都很模糊，人的面部表情几乎看不清。请问如何提高画画的清晰度？
谢谢！

**Comment by zhayujie** [comment]
在chat_gpt_bot.py 中修改

<img width="869" alt="image" src="https://user-images.githubusercontent.com/26161723/227565860-335dd0bd-5e16-4857-9aad-aeaed1abffa4.png">
