### ISSUE TITLE
询问下，这样的机制有被微信封号的风险么？

### ISSUE THREAD

**Issue by wwb306** [zhayujie/chatgpt-on-wechat#58]

**Comment by zhayujie** [comment]
暂时没遇到，不过建议用小号

**Comment by 1195458334** [comment]
![a308b9cbb101d9b1aa3fde564dd92f9](https://user-images.githubusercontent.com/26034265/217737529-9042b635-9ab6-432c-a976-2301ce4bba1e.jpg)
