### ISSUE TITLE
无前缀自动回复配置失效single_chat_prefix": [""]（最新版）

### ISSUE THREAD

**Issue by hunduncn** [zhayujie/chatgpt-on-wechat#584]
### **前置确认**

- 网络能够访问openai接口
- python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
- 在已有 issue 中未搜索到类似问题
- FAQS 中无类似问题
- 在群聊中可直接@

### **问题描述**

- 配置 "single_chat_prefix": [""]) 不用前缀自动回复失效

**Comment by zhayujie** [comment]
获取下最新的代码哈，已经解决了

**Comment by hunduncn** [comment]
> 获取下最新的代码哈，已经解决了

谢谢
