### ISSUE TITLE
启动异常

### ISSUE THREAD

**Issue by GuangXinXueYuan** [zhayujie/chatgpt-on-wechat#585]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
  

### 终端日志 (如有报错)
![image](https://user-images.githubusercontent.com/22358502/227683592-daaaa457-43e7-474d-808d-2be074898fdf.png)

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( 执行 `python3.9 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
请问你使用的python版本是3.9嘛，   我用  3.7~ 3.10 貌似都没有复现这个问题

**Comment by GuangXinXueYuan** [comment]
3.9
