### ISSUE TITLE
如何在回复末尾加上自定义的短句呢？

### ISSUE THREAD

**Issue by 1378056564** [zhayujie/chatgpt-on-wechat#590]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

请教一下大佬们，如果我打算把机器人放在别的群里实现自动回复。想让他在每一句的回复中都加上自定义的广告词？或者说自定义话语作为最后的结尾。
那么我应该在哪个文件进行添加呢？/bot/chatgpt里面的吗？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux-centos8.1
 - Python版本  ( 执行 `python3 -V` )：  python3.9.9             
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1

**Comment by lanvent** [comment]
可以实现插件，绑定`ON_SEND_REPLY`事件。
或者自行修改`wechatchannel.py`中`handle`函数的代码。
