### ISSUE TITLE
插件不是必须的，最好改成没有插件，不影响以前的功能

### ISSUE THREAD

**Issue by xgd561** [zhayujie/chatgpt-on-wechat#599]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
plugins.json这个文件里面的内容是什么样子的？
不配置运行不起来，插件不是必须的，最好改成没有插件，不影响以前的功能

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
[INFO][2023-03-25 21:44:07][plugin_manager.py:39] - Loading plugins config...
[ERROR][2023-03-25 21:44:07][app.py:23] - App startup failed!
[ERROR][2023-03-25 21:44:07][app.py:24] - [Errno 2] No such file or directory: 'plugins/plugins.json'
Traceback (most recent call last):
  File "/www/wwwroot/325webot/app.py", line 18, in run
    PluginManager().load_plugins()
  File "/www/wwwroot/325webot/plugins/plugin_manager.py", line 116, in load_plugins
    self.load_config()
  File "/www/wwwroot/325webot/plugins/plugin_manager.py", line 51, in load_config
    self.save_config()
  File "/www/wwwroot/325webot/plugins/plugin_manager.py", line 35, in save_config
    with open("plugins/plugins.json", "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/plugins.json'

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
请问你是在什么环境下， 用什么命令启动的呢

**Comment by xgd561** [comment]
> 请问你是在什么环境下， 用什么命令启动的呢
使用的腾讯云centos服务器，使用宝塔的python项目管理器部署的

**Comment by xgd561** [comment]
没有使用容器部署，宝塔直接拉起app.py

**Comment by xgd561** [comment]
和服务器部署是一样的

**Comment by lanvent** [comment]
之前也有宝塔相关的相对路径issue #547 ， 拉取下最新的代码吧。

**Comment by xgd561** [comment]
plugins/plugins.json这个文件有example吗？我需要参考一下

**Comment by xgd561** [comment]
> plugins/plugins.json这个文件有example吗？我需要参考一下

文件路径修改好后，自动产生了，使用宝塔，必须使用绝对路径
