### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 3

### ISSUE THREAD

**Issue by shixpGit** [zhayujie/chatgpt-on-wechat#600]
### 前置确认

1. 网络能够访问openai接口 - 确认可以
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装 - conda--py3.8
3. 在已有 issue 中未搜索到类似问题 - 未搜到
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题 - 确认

### 问题描述
使用docker部署服务,遇到json解析问题
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 3
如下图:
![image](https://user-images.githubusercontent.com/26370270/227722839-3ae78928-470d-426c-9c25-56c4b0ad28de.png)

### 终端日志 (如有报错)

uccessfully built pyqrcode
Installing collected packages: pyqrcode, pypng, urllib3, typing-extensions, tqdm, multidict, idna, frozenlist, charset-normalizer, certifi, attrs, asynctest, yarl, requests, async-timeout, aiosignal, itchat-uos, aiohttp, openai
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 asynctest-0.13.0 attrs-22.2.0 certifi-2022.12.7 charset-normalizer-3.1.0 frozenlist-1.3.3 idna-3.4 itchat-uos-1.5.0.dev0 multidict-6.0.4 openai-0.27.2 pypng-0.20220715.0 pyqrcode-1.2.1 requests-2.28.2 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.15 yarl-1.8.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
(1/7) Purging curl (7.79.1-r3)
(2/7) Purging wget (1.21.1-r1)
(3/7) Purging libcurl (7.79.1-r3)
(4/7) Purging brotli-libs (1.0.9-r3)
(5/7) Purging nghttp2-libs (1.42.0-r1)
(6/7) Purging libidn2 (2.3.0-r0)
(7/7) Purging libunistring (0.9.10-r0)
Executing busybox-1.32.1-r2.trigger
OK: 13 MiB in 36 packages
Removing intermediate container 6b54d33bd39e
 ---> b01ec3b8f997
Step 7/11 : WORKDIR ${BUILD_PREFIX}
 ---> Running in 0369cb507940
Removing intermediate container 0369cb507940
 ---> 7ded9052a5d7
Step 8/11 : ADD ./entrypoint.sh /entrypoint.sh
 ---> cb3fe9130b8d
Step 9/11 : RUN chmod +x /entrypoint.sh     && adduser -D -h /home/noroot -u 1000 -s /bin/bash noroot     && chown noroot:noroot ${BUILD_PREFIX}
 ---> Running in 44c3c7f7c8e8
Removing intermediate container 44c3c7f7c8e8
 ---> 02a901016503
Step 10/11 : USER noroot
 ---> Running in 4f2a97ae70eb
Removing intermediate container 4f2a97ae70eb
 ---> 8b3eee087a63
Step 11/11 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 8b0d40a3ec13
Removing intermediate container 8b0d40a3ec13
 ---> d66846818c6c
Successfully built d66846818c6c
Successfully tagged zhayujie/chatgpt-on-wechat:latest
WARNING: Image for service chatgpt-on-wechat was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating sample-chatgpt-on-wechat ... done
Attaching to sample-chatgpt-on-wechat
sample-chatgpt-on-wechat | [ERROR][2023-03-25 14:17:50][app.py:22] - App startup failed!
sample-chatgpt-on-wechat | [ERROR][2023-03-25 14:17:50][app.py:23] - Expecting ',' delimiter: line 15 column 3 (char 509)
sample-chatgpt-on-wechat | Traceback (most recent call last):
sample-chatgpt-on-wechat |   File "app.py", line 11, in <module>
sample-chatgpt-on-wechat |     config.load_config()
sample-chatgpt-on-wechat |   File "/app/config.py", line 17, in load_config
sample-chatgpt-on-wechat |     config = json.loads(config_str)
sample-chatgpt-on-wechat |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
sample-chatgpt-on-wechat |     return _default_decoder.decode(s)
sample-chatgpt-on-wechat |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
sample-chatgpt-on-wechat |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
sample-chatgpt-on-wechat |   File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
sample-chatgpt-on-wechat |     obj, end = self.scan_once(s, idx)
**sample-chatgpt-on-wechat | json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 3 (char 509)**
sample-chatgpt-on-wechat exited with code 0

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：              Python 3.8.13        
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.2.2 from ***/install/miniconda3/envs/py3.8/lib/python3.8/site-packages/pip (python 3.8)
 - commit ID: bebe8c1b1d86fd8e633a5b25cc1da806b16d5eb5

**Comment by zhuchao941** [comment]
一样的问题

**Comment by shixpGit** [comment]
> 一样的问题

确实, 我大概正常运转了docker服务一周, 昨晚发现container突然exit(0)了(不知道是不是存在7天倒计时限制), 再重启docker-compose up就各种问题, 最后pull到最新代码, 就这样了.

**Comment by lx1234156** [comment]
我也遇到相同的问题，请问解决了吗？

**Comment by zhayujie** [comment]
see #601
