### ISSUE TITLE
这个可以加一个配置支持关闭上下文功能么，账号使用上下文很容易触发限制

### ISSUE THREAD

**Issue by felixzhang-glitch** [zhayujie/chatgpt-on-wechat#602]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
可以将最大上下文设置到很小的数字。

**Comment by Payne-Wang** [comment]
> 可以将最大上下文设置到很小的数字。

我把expires_in_seconds和conversation_max_tokens都设置成0了依然不行，因为刚申请到GPT4的api，接入群聊后有上下文太伤了，玩不起，希望大佬解答，谢谢！
