### ISSUE TITLE
二维码出码混乱，求解决！

### ISSUE THREAD

**Issue by LeafBanks** [zhayujie/chatgpt-on-wechat#603]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
二维码混乱，能不能Put个网址的啊！

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
![T((HLX0H462`N% UZPAG3_A](https://user-images.githubusercontent.com/122428986/227730713-0649d62b-7242-411a-aaba-7830f9124254.png)
![(AKUQ0G}5)3R`Z3{62(0{M](https://user-images.githubusercontent.com/122428986/227730724-e59dd3d1-c16a-4e72-b35c-f87fdefc2619.png)

**Comment by LeafBanks** [comment]
![T((HLX0H462`N% UZPAG3_A](https://user-images.githubusercontent.com/122428986/227730784-f1004c5e-c6c8-4d82-9630-1e6fcc077212.png)

**Comment by zhayujie** [comment]
你用的是什么终端软件， 换一个试试

**Comment by spectramaster** [comment]
![微信图片_20230326103602](https://user-images.githubusercontent.com/76525587/227752181-f89a22ac-4006-42c1-9c50-6ff5ae7b3495.png)
这是什么情况？换了好几个终端都没有解决

**Comment by spectramaster** [comment]
这个二维码的形状和里面的信息会随着终端窗口的大小而变化

**Comment by zhayujie** [comment]
@spectramaster  看下 #134 ， 试试改一行代码能不能解决

**Comment by spectramaster** [comment]
> @spectramaster 看下 #134 ， 试试改一行代码能不能解决

哈哈哈，解决了，每次在终端运行app.py后，根目录里面会自动生成一个新的二维码的图片，你扫它就可以啦~~~~

**Comment by spectramaster** [comment]
> ![T((HLX0H462`N% UZPAG3_A](https://user-images.githubusercontent.com/122428986/227730784-f1004c5e-c6c8-4d82-9630-1e6fcc077212.png)

看我的回答，那个图片的名字就叫QR如果我没有记错

**Comment by Cirzear** [comment]
> ![微信图片_20230326103602](https://user-images.githubusercontent.com/76525587/227752181-f89a22ac-4006-42c1-9c50-6ff5ae7b3495.png) 这是什么情况？换了好几个终端都没有解决
复制粘贴到编辑器里就正常了，我是这么解决的

**Comment by COOk921** [comment]
> ![微信图片_20230326103602](https://user-images.githubusercontent.com/76525587/227752181-f89a22ac-4006-42c1-9c50-6ff5ae7b3495.png) 这是什么情况？换了好几个终端都没有解决
别翻译网页好像就行了
