### ISSUE TITLE
Allow the user to up load the audio file 

### ISSUE THREAD

**Issue by Tyler913** [zhayujie/chatgpt-on-wechat#604]
希望可以新增这个功能，这样对于拿chatGPT练习雅思口语或者是其他类型的朋友可以上传语音文件，不然微信60秒的限制有点短，或者是能不能推出一个机制是只有当发出某个指令的时候才开始语音转文字然后合并起来同时处理，这样可哟增加发语音的时长。

**Comment by lanvent** [comment]
推荐做成插件的形式
