### ISSUE TITLE
总是登录超时，重新生成二维码

### ISSUE THREAD

**Issue by wenzhongfa** [zhayujie/chatgpt-on-wechat#608]
请问这是什么意思啊，每次扫码登陆以后，都会显示登陆超时，然后重新生成二维码
![微信图片_20230326132014](https://user-images.githubusercontent.com/47892441/227756944-90b10828-0677-4be5-ba6a-65b2cf7868e8.png)
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by rongmengmeng** [comment]
我也碰到了这个问题，关闭重启有时候可以正常登陆，有时候不行

**Comment by rongmengmeng** [comment]
see https://github.com/zhayujie/chatgpt-on-wechat/issues/8
