### ISSUE TITLE
查的图片报错

### ISSUE THREAD

**Issue by Sirius2016** [zhayujie/chatgpt-on-wechat#61]
[INFO][2023-02-07 10:46:05][open_ai_bot.py:71] - [OPEN_AI] image_query=画一只黑色的狗
[ERROR][2023-02-07 10:46:05][open_ai_bot.py:89] - module 'openai' has no attribute 'Image'
Traceback (most recent call last):
  File "/usr/local/src/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 72, in create_img
    response = openai.Image.create(
AttributeError: module 'openai' has no attribute 'Image'

![image](https://user-images.githubusercontent.com/23203953/217135481-803abe58-c73a-4ace-8293-dae85f543fb3.png)

**Comment by zhayujie** [comment]
see #53
