### ISSUE TITLE
openai只有Completion没有ChatCompletion啊？

### ISSUE THREAD

**Issue by TeacherPeng** [zhayujie/chatgpt-on-wechat#612]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
openai里只查到Completion，没有查到ChatCompletion。

> 简要说明、截图、复现步骤等，也可以是需求或想法
dir(openai)
['APIError',
 'Answer',
 'Classification',
 'Completion',
 'Engine',
 'ErrorObject',
 'File',
 'FineTune',
 'InvalidRequestError',
 'OpenAIError',
 'Snapshot',
......

### 终端日志 (如有报错)
AttributeError: module 'openai' has no attribute 'ChatCompletion

 - 操作系统类型  (Windows)：
 - Python版本  ( 执行 `python3 -V` )：3.11.2                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by zhayujie** [comment]
openai版本要0.27.0以上，更新下试试

而且你的python版本貌似有点高，不知道能否正常使用

**Comment by TeacherPeng** [comment]
果然如此，现在成功了，python版本3.11.2也没问题。
