### ISSUE TITLE
机器人响应时间在1分钟以上

### ISSUE THREAD

**Issue by jiashuai123** [zhayujie/chatgpt-on-wechat#615]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[INFO][2023-03-26 17:53:49][chat_gpt_bot.py:32] - [OPEN_AI] query=讲个笑话吧
[INFO][2023-03-26 17:55:23][wechat_channel.py:176] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 好的，我来给您讲一个笑话：
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by ArtisanM** [comment]
+1 耗时在1分钟左右  为什么这么慢

**Comment by Kiteflyingee** [comment]
速度确实慢
