### ISSUE TITLE
问答时出现这个错误。

### ISSUE THREAD

**Issue by thexqn** [zhayujie/chatgpt-on-wechat#62]
[ERROR][2023-02-07 10:48:44][open_ai_bot.py:89] - module 'openai' has no attribute 'Image'
Traceback (most recent call last):
  File "/home/ubuntu/python2/env/code/chatgpt-on-wechat-master/bot/openai/open_ai_bot.py", line 72, in create_img
    response = openai.Image.create(
AttributeError: module 'openai' has no attribute 'Image'

**Comment by zhayujie** [comment]
see #53

**Comment by thexqn** [comment]
> 

![image](https://user-images.githubusercontent.com/11768476/217146403-6a3edc5f-3f02-46d4-88b0-617e1b05028d.png)
这个问题为什么会触发画图呢？

**Comment by zhayujie** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/11768476/217146403-6a3edc5f-3f02-46d4-88b0-617e1b05028d.png) 这个问题为什么会触发画图呢？

配置image_create_prefix 里面的画图关键字有一个  "看" ，我后面从模板里移除掉吧
