### ISSUE TITLE
分支增加百度语音，UNIT技能，增加群语音交流，安装完后，在尝试使用 OpenAI API 时遇到了错误，因为没有提供 API 密钥

### ISSUE THREAD

**Issue by zxr11241** [zhayujie/chatgpt-on-wechat#624]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

安装完后，在尝试使用 OpenAI API 时遇到了错误，因为没有提供 API 密钥，
API 密钥是正确的，我在另一台服务搭建的chatgpt机器人能正常使用api key
不知道问题出在哪里

### 终端日志 (如有报错)
Login successfully as 小羊😜
Start auto replying.
[INFO][2023-03-27 01:36:00][bridge.py:28] - create bot openai for voice_to_text
[INFO][2023-03-27 01:36:00][wechat_channel.py:179] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://onboard.openai.com for details, or email support@openai.com if you have any questions.), receiver=@be96367f45f454bb96480dbb9fa28738
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型   ( Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
检查下`config.json`
