### ISSUE TITLE
用wechaty报错

### ISSUE THREAD

**Issue by gwailee** [zhayujie/chatgpt-on-wechat#627]
### 问题描述

运行报错：
[ERROR][2023-03-27 05:37:28][app-wx308-1.py:23] - App startup failed!
[ERROR][2023-03-27 05:37:28][app-wx308-1.py:24] - No module named 'wechaty_puppet'
Traceback (most recent call last):
  File "app-wx308-1.py", line 16, in run
    channel = channel_factory.create_channel(channel_name)
  File "/root/WX-ChatGPT-308-1/channel/channel_factory.py", line 15, in create_channel
    from channel.wechat.wechaty_channel import WechatyChannel
  File "/root/WX-ChatGPT-308-1/channel/wechat/wechaty_channel.py", line 18, in <module>
    from wechaty_puppet import MessageType, FileBox, ScanStatus  # type: ignore
ModuleNotFoundError: No module named 'wechaty_puppet'

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境
1.config.json增加了：wechaty_puppet_service_token
2.app.py中的wx改成wxy
3.用的是ubuntu20.04，python是3.8版本
4.已经安装wetchaty包
 - 操作系统类型  (Mac/Windows/Linux)：Linux/ubuntu20.04
 - Python版本  ( 执行 `python3 -V` )：python3 -V                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by akushonkamen** [comment]
要pip install wechat-puppet
