### ISSUE TITLE
ImportError: cannot import name 'itchat' from 'lib' (unknown location)

### ISSUE THREAD

**Issue by SherlockSalvatore** [zhayujie/chatgpt-on-wechat#631]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
运行后报错找不到lib

### 终端日志 (如有报错)

```
Traceback (most recent call last):
  File "d:\Project_Python\ChatGPT\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 8, in <module>
    from lib import itchat
ImportError: cannot import name 'itchat' from 'lib' (unknown location)
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python3 -V` )：Python 3.10.2               
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1

**Comment by hotdogarea** [comment]
我也是同样问题，请问解决了吗？

**Comment by hotdogarea** [comment]
我也遇到同样问题，请问解决了吗，啊
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/11146882/2bbc57ed-a295-466f-922d-ad2e574e8fa1)
