### ISSUE TITLE
大佬，itchat怎么保持一直在线呢

### ISSUE THREAD

**Issue by jearhe** [zhayujie/chatgpt-on-wechat#64]
备用机登录的小号，放在家里，突然就退出登录了

**Comment by zhayujie** [comment]
程序是部署在个人电脑的吗，需要电脑一直运行不能休眠。 或者用服务器的话是最稳定的。  参考 文档里 "服务器部署" 相关内容。

**Comment by SKKAC** [comment]
@zhayujie 我就是在服务器上登录的，它会自己退出，是因为没有连接vpn吗
运行结果如下
Login successfully as skkac
Start auto replying.
Log in time out, reloading QR code.
Getting uuid of QR code.
Downloading QR code.

**Comment by zhayujie** [comment]
> @zhayujie 我就是在服务器上登录的，它会自己退出，是因为没有连接vpn吗 运行结果如下 Login successfully as skkac Start auto replying. Log in time out, reloading QR code. Getting uuid of QR code. Downloading QR code.

一般出现 Start auto replying. 就表示成功了， 不会再 log in time out了， 你现在能自动回复了吗？

不行的话把程序关掉再启动一次试试
