### ISSUE TITLE
您好，我看到一个公众号在利用这个开源项目进行收费，请问这个公众号是您的嘛

### ISSUE THREAD

**Issue by xufabing** [zhayujie/chatgpt-on-wechat#640]
如下两个链接
https://mp.weixin.qq.com/s?__biz=MzIxNjM4NDE2MA==&mid=2247523091&idx=1&sn=95104d6599d36e2d19f2b919772fa04b&chksm=978b0cdca0fc85ca6dc55217a70f94c86ad6c2bb891fb6b16f6a22614ed2afcd122df9e2c2c1&scene=126&sessionid=1679964971#rd

https://mp.weixin.qq.com/s?__biz=MzIxNjM4NDE2MA==&mid=2247523117&idx=1&sn=7db7267dba1cde07b06e36d7e4278d69&chksm=978b0ce2a0fc85f47f06e68346a7eef5051dd0441cdc537981dd08f39bfaa475b940acf8c4bf&scene=126&sessionid=1679964971#rd

**Comment by lichengzhe** [comment]
有很多套壳收费的，开发伙伴们注意甄别，本项目完全开源无收费内容。

**Comment by HenMie** [comment]
一个相当于是卖手把手教程，一个相当于是卖现成服务，无可厚非吧，虽然没直接提供项目地址确实有点不太厚道。不过这个项目是MIT协议，允许贩卖源码，保留LICENSE和署名即可

**Comment by MinovskyRickland** [comment]
再pull一个文件夹说明和readme里面告知完全免费吧
