### ISSUE TITLE
ModuleNotFoundError: No module named 'pysilk'

### ISSUE THREAD

**Issue by linmp4** [zhayujie/chatgpt-on-wechat#641]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[ERROR][2023-03-28 09:55:42][app.py:24] - No module named 'pysilk'
Traceback (most recent call last):
  File "H:\github\chatgpt-on-wechat\app.py", line 16, in run
    channel = channel_factory.create_channel(channel_name)
  File "H:\github\chatgpt-on-wechat\channel\channel_factory.py", line 12, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "H:\github\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 23, in <module>
    from voice.audio_convert import mp3_to_wav
  File "H:\github\chatgpt-on-wechat\voice\audio_convert.py", line 2, in <module>
    import pysilk
ModuleNotFoundError: No module named 'pysilk'
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by 931122** [comment]
pip install silk-python

**Comment by zhayujie** [comment]
改了下，不使用语音转文字的时候默认不需要这个依赖

**Comment by ss1969** [comment]
> pip install silk-python

No module named 'pysilk.backends.cython._silk'

**Comment by zhayujie** [comment]
更新下代码应该就好了 @ss1969

**Comment by mari1995** [comment]
> 更新下代码应该就好了 @ss1969

No module named 'pysilk.backends.cython._silk'
还是报错，

**Comment by zhaoxitao** [comment]
尝试卸载silk-python然后用编译的方式重新安装 pysilk-mod
`pip uninstall silk-python && pip install git+https://github.com/DCZYewen/Python-Silk-Module`
