### ISSUE TITLE
1.1.3版本本身需要python最新到3.9.x，但是stable diffusion插件要求python3.10.6

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#643]
请问怎么把这两个不同版本的python3装在同一个环境，且做到互不影响？

**Comment by lanvent** [comment]
本项目在python3.10上可用，安装stable diffusion webui的教程也一般都会使用virtualenv来创建python虚拟环境，跟系统环境隔离。

**Comment by zhangzhanhui** [comment]
请问stable diffusion webui安装和运行需要多大内存？我在2GB内存环境安装时报错Mem Error，经查询是内存不足导致。
