### ISSUE TITLE
PS E:\chatgpt-on-wechat> python app.py [ERROR][2023-03-28 10:55:05][app.py:23] - App startup failed! [ERROR][2023-03-28 10:55:05][app.py:24] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by HuaChuangSoft** [zhayujie/chatgpt-on-wechat#644]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by HuaChuangSoft** [comment]
环境在Windows下，python版本是3.8.10，运行指令python app.py然后出现
PS E:\chatgpt-on-wechat> python app.py
[ERROR][2023-03-28 10:55:05][app.py:23] - App startup failed!
[ERROR][2023-03-28 10:55:05][app.py:24] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by zhayujie** [comment]
windows编辑config.json的时候编码有点问题，建议换一个编辑器进行修改，比如 sublime

**Comment by HuaChuangSoft** [comment]
config.json这里面什么格式的编码，我用utf-8也不行
