### ISSUE TITLE
docker端发信息出错。

### ISSUE THREAD

**Issue by yaogame** [zhayujie/chatgpt-on-wechat#646]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 
电脑端用vs运行python一切正常，就是时间久会出错，于是在nas上部署了docker端24小时运行，把运行程序拖到群晖的nas文件夹中，参数启动（环境参数已经设置好1.env）：

OPEN_AI_API_KEY=YOUR API KEY
OPEN_AI_PROXY=
SINGLE_CHAT_PREFIX=["bot", "@bot"]
SINGLE_CHAT_REPLY_PREFIX="[bot] "
GROUP_CHAT_PREFIX=["@bot"]
GROUP_NAME_WHITE_LIST=["ChatGPT测试群", "ChatGPT测试群2"]
IMAGE_CREATE_PREFIX=["画", "看", "找"]
CONVERSATION_MAX_TOKENS=1000
CHARACTER_DESC=你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。
EXPIRES_IN_SECONDS=3600

docker run -it --name sample-chatgpt-on-wechat --env-file=1.env zhayujie/chatgpt-on-wechat     

启动后成功，但是发消息后有下面错误提示，请求大神解答！

### 终端日志 (如有报错)

Start auto replying.
[INFO][2023-03-28 02:55:49][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-03-28 02:55:50][chat_gpt_bot.py:32] - [OPEN_AI] query=1
[WARNING][2023-03-28 02:55:50][chat_gpt_bot.py:118] - Error communicating with OpenAI: ('Connection aborted.', OSError(22, 'Invalid argument'))
[WARNING][2023-03-28 02:55:50][chat_gpt_bot.py:119] - [OPEN_AI] APIConnection failed
[INFO][2023-03-28 02:55:51][wechat_channel.py:179] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
我连接不到你的网络), receiver=@7d4ccfd6b33f3c3cd5795ad521874fc4
^CBye~

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
网络问题，你的环境可以访问openai吗
#351

**Comment by yaogame** [comment]
> 

感谢回复，用的是路由器openwrt翻墙，网络正常的，nas上的docker需要单独用代理命令吗，谢谢
