### ISSUE TITLE
为什么登录后，过几秒钟就直接退出

### ISSUE THREAD

**Issue by a472691** [zhayujie/chatgpt-on-wechat#647]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

在MacOS下，使用ubuntu容器部署没有任何问题，在window的VM虚拟机中安装centos、ubuntu，不管是在docker中部署还是在原系统中部署，扫码登录后，过10秒左右吧，就显示LOG OUT退出微信了，手速快一些发个问题，还来得及回复，手速慢一点，就LOG OUT退出了。pyhont3.8、3.9、3.10都试过了。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Centos、Ubuntu
 - Python版本  ( 执行 `python3 -V` )：    3.8、3.9、3.10
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.3.1

**Comment by zhayujie** [comment]
登录账号的 手机端有下线吗， 其他端有登陆吗

**Comment by a472691** [comment]
可能是我代理问题，mac下可以正常访问openai，window下无法正常使用代理访问ai，必须设置成全局才正常，但是看不到任何错误就LOG OUT
