### ISSUE TITLE
WEchaty通了没任何反应

### ISSUE THREAD

**Issue by LeafBanks** [zhayujie/chatgpt-on-wechat#648]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

搞了两天的wechaty，其中各种错误，还有docker那个IP127.0.0.1:9001，各种都搞定了通了，结果发消息还是服务器第一条又回复，之后就瘫了，不说了上图，有大神出来解决下不

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
![95(KHU Y4KV_YG)W}9 @~CB](https://user-images.githubusercontent.com/122428986/228122437-f0623e03-e9cf-4f8c-a57c-00e3b9806900.png)

**Comment by lanvent** [comment]
配置文件里没有选择wechaty
