### ISSUE TITLE
特殊字符的处理问题

### ISSUE THREAD

**Issue by gejiyu** [zhayujie/chatgpt-on-wechat#65]
#号这种字符会被截断 应该怎么处理

**Comment by zhayujie** [comment]
来个例子，对话截图和日志

**Comment by gejiyu** [comment]
已经解决 修改open_ai_bot.py的openai.Completion.create()里的stop标识 不然回复的#会被截断

**Comment by acbogeh** [comment]
> 已经解决 修改open_ai_bot.py的openai.Completion.create()里的stop标识 不然回复的#会被截断

你改成啥了
