### ISSUE TITLE
语音输入错误

### ISSUE THREAD

**Issue by SnowbambooXsshallot** [zhayujie/chatgpt-on-wechat#650]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
4. 在已有 issue 中未搜索到类似问题
5. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
语音输入报错

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by gwailee** [comment]
我也碰到这个问题，昨天版本还能用，更新之后就不行了。

**Comment by lanvent** [comment]
感谢issue，已修复，请拉取最新代码
