### ISSUE TITLE
配置更新问题

### ISSUE THREAD

**Issue by TSummerDay** [zhayujie/chatgpt-on-wechat#653]
### 问题描述
更新配置的时候，更新了config。
能否增加在更新配置是，同步更新插件，也就是调用
PluginManager().load_plugins()
修改文件为chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py
> 简要说明、截图、复现步骤等，也可以是需求或想法

![Dingtalk_20230328165254](https://user-images.githubusercontent.com/100781829/228183365-71009f85-6483-4ba8-b523-f25a7f49ab9c.jpg)

**Comment by lanvent** [comment]
请使用`godcmd`插件中的`reloadp`指令，参考 https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/godcmd
