### ISSUE TITLE
小号微信登陆扫码后，手机切换了其他微信登陆，项目直接下线，显示为：LOG OUT!

### ISSUE THREAD

**Issue by leealu** [zhayujie/chatgpt-on-wechat#655]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

小号微信登陆扫码后，手机切换了其他微信登陆，项目直接下线，显示为：LOG OUT!，这个怎么解决？还是说只能一直登陆着？

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zousoo** [comment]
只能一直登录

**Comment by 0QwQ0** [comment]
你好，经过我多次部署测试，目前看来只能一直保持登录状态。
1) 手机/平板 登陆你要作为机器人使用的微信账号 并确认可以正常扫码
2) 使用该设备扫描二维码登录chatgpt项目
3) 保持第1步中的设备微信账户一直在线，机器人使用过程中不能在该设备上切换使用其他微信账号，如有需求可以尝试双开微信。

**Comment by leealu** [comment]
> 你好，经过我多次部署测试，目前看来只能一直保持登录状态。
> 
> 1. 手机/平板 登陆你要作为机器人使用的微信账号 并确认可以正常扫码
> 2. 使用该设备扫描二维码登录chatgpt项目
> 3. 保持第1步中的设备微信账户一直在线，机器人使用过程中不能在该设备上切换使用其他微信账号，如有需求可以尝试双开微信。

看来只能这样了

**Comment by xiebaiyuan** [comment]
现在还会被封么。。。

**Comment by leealu** [comment]
> 现在还会被封么。。。

不知道，还没用，要一直登陆就没用

**Comment by ledrsnet** [comment]
登录小号之后，关闭流量和wifi，这时候退出小号。然后开流量wifi登录大号就可以

**Comment by wangycc** [comment]
> 登录小号之后，关闭流量和wifi，这时候退出小号。然后开流量wifi登录大号就可以

飞行模式，直接无法退出。。。。

**Comment by leealu** [comment]
完了试试，谢谢> 登录小号之后，关闭流量和wifi，这时候退出小号。然后开流量wifi登录大号就可以

**Comment by jcdiv47** [comment]
> 登录小号之后，关闭流量和wifi，这时候退出小号。然后开流量wifi登录大号就可以

iOS 16.5 经测试没成功哎，关闭移动数据和WIFI（或者打开飞行模式），然后尝试退出小号，这时会卡在“正在加载”，整个微信都会没有响应，直到重新有网络，此时小号会成功退出，但是bot端也会随之log out

[尝试断网退出微信号](https://ibb.co/YtXfhx6)

**Comment by ledrsnet** [comment]
> > 登录小号之后，关闭流量和wifi，这时候退出小号。然后开流量wifi登录大号就可以
> 
> iOS 16.5 经测试没成功哎，关闭移动数据和WIFI（或者打开飞行模式），然后尝试退出小号，这时会卡在“正在加载”，整个微信都会没有响应，直到重新有网络，此时小号会成功退出，但是bot端也会随之log out
> 
> [尝试断网退出微信号](https://ibb.co/YtXfhx6)

我也是等了一会就退出了。ios16.0.2

**Comment by jcdiv47** [comment]
> > > 登录小号之后，关闭流量和wifi，这时候退出小号。然后开流量wifi登录大号就可以
> > 
> > 
> > iOS 16.5 经测试没成功哎，关闭移动数据和WIFI（或者打开飞行模式），然后尝试退出小号，这时会卡在“正在加载”，整个微信都会没有响应，直到重新有网络，此时小号会成功退出，但是bot端也会随之log out
> > [尝试断网退出微信号](https://ibb.co/YtXfhx6)
> 
> 我也是等了一会就退出了。ios16.0.2

感谢感谢，已经成功了，确实得等大概半分钟，之前太没耐心了

**Comment by hecarli555** [comment]
mark一下，下次试试
