### ISSUE TITLE
Docker部署使用-v指定配置文件无效

### ISSUE THREAD

**Issue by hilphen** [zhayujie/chatgpt-on-wechat#657]
### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

更新1.1.3后使用Docker部署 -v /volume1/docker/chatgpt/config.json:/app/config.json 指定配置文件无效

**Comment by lanvent** [comment]
1.1.3会读取环境变量来重载配置，可以将entrypoint.sh中的`export`语句注释掉或者改用环境变量来传参。
