### ISSUE TITLE
请问在部署完毕后更新JSON的参数？

### ISSUE THREAD

**Issue by kz1802** [zhayujie/chatgpt-on-wechat#658]
我第一次部署完忘记修改群的名称了。直接修改没有反应，请问如何更新？  还有就是我更改了微信号的名字后，在群里@他没有反应怎么办？

**Comment by lanvent** [comment]
修改`config.json`，然后重新运行程序。 
或使用[`godcmd`](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/godcmd)插件，执行`#reconf`指令。

**Comment by kz1802** [comment]
> 修改`config.json`，然后重新运行程序。 或使用[`godcmd`](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/godcmd)插件，执行`#reconf`指令。

重新运行程序是要输什么命令？

**Comment by lanvent** [comment]
python app.py

**Comment by jcdiv47** [comment]
抱歉顺便问一下，[chat_gpt_bot.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/66a81cd47cef3efceec41e88559a039322d3033d/bot/chatgpt/chat_gpt_bot.py#L38) 里的命令，比如 `#清除记忆`是不是都用不上了，所有指令都改由`godcmd`去修改？

**Comment by lanvent** [comment]
> > 修改`config.json`，然后重新运行程序。 或使用[`godcmd`](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/godcmd)插件，执行`#reconf`指令。
> 
> 抱歉顺便问一下，[chat_gpt_bot.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/66a81cd47cef3efceec41e88559a039322d3033d/bot/chatgpt/chat_gpt_bot.py#L38) 里的命令，比如 `#清除记忆`和`#更新配置`，是不是都用不上了，所有指令都改由`godcmd`去修改？

是的，`godcmd`会拦截
