### ISSUE TITLE
大佬好，微信机器人拉入新群或者私聊新的好友无法返回结果，需要重启应用

### ISSUE THREAD

**Issue by LoveMyGitHub** [zhayujie/chatgpt-on-wechat#66]
如题，不知道其他G友有没有遇到这个问题

**Comment by zhayujie** [comment]
有日志输出吗，群聊名称有配置在config.json 嘛

**Comment by LoveMyGitHub** [comment]
> 
无日志输出，历史群聊日志正常。
群聊名称设置为 "group_name_white_list": "ALL_GROUP"

<img width="399" alt="image" src="https://user-images.githubusercontent.com/30399551/217168139-734edc09-21a6-449c-8712-8db00485f19f.png">

**Comment by LoveMyGitHub** [comment]
已解决。
拉入的群未设置群名称，大佬可以看看是不是这个原因导致。

**Comment by zhayujie** [comment]
> 已解决。 拉入的群未设置群名称，大佬可以看看是不是这个原因导致。

是的，需要有群名称，这里可以优化下，针对ALL_GROUP的情况
