### ISSUE TITLE
如何使用wechaty进而使用语音识别

### ISSUE THREAD

**Issue by Sebastronne** [zhayujie/chatgpt-on-wechat#669]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

不好意思，纯小白尝试在railway成功部署了本项目。也成功和bot完成对话。但在功能介绍中有写到的关于发语音的问题。尝试发语音后，机器人并不能正确回复。进而发现可能是没有使用wechaty的问题。但在项目中并未看到如何调用wechaty的教学，特此提问。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
重新拉取最新的代码吧，昨晚的代码增加了对私聊时语音判断触发前缀，语音触发条件变苛刻了。
目前已经修复。

更新方式：
1. 在自己的仓库点击`sync fork`。
2. 在`railway`里如下的界面点击`update`再在自己仓库同意`railway`的pr。
![image](https://user-images.githubusercontent.com/26515464/228421597-ce22ec25-5563-4ec1-b7cc-bcfa401860f0.png)
