### ISSUE TITLE
大佬，我在微信上提问，只在日志上能看到回答，传不回微信，同时，电脑上的微信也被踢下线了。

### ISSUE THREAD

**Issue by tomsyang0** [zhayujie/chatgpt-on-wechat#67]

**Comment by zhayujie** [comment]
日志截图贴一下。电脑上的下线是正常的，程序和电脑只能登一个

**Comment by nomas** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/57502/217277233-1e042c58-101f-4ff4-aa9b-6f15a96fc413.png">

手机微信端收不到恢复。但日志里有。

**Comment by zhayujie** [comment]
> <img alt="image" width="408" src="https://user-images.githubusercontent.com/57502/217277233-1e042c58-101f-4ff4-aa9b-6f15a96fc413.png">
> 
> 手机微信端收不到回复。但日志里有。

看到这个日志应该就是成功了， 是好友给自己发的吗？私聊还是群聊？

**Comment by nomas** [comment]
私聊，就是自己发给自己。

**Comment by zhayujie** [comment]
> 私聊，就是自己发给自己。

自己发给自己是没办法收到自动回复的 ，你可以发给好友

**Comment by nomas** [comment]
嗯，谢谢，测试成功了。
