### ISSUE TITLE
求基于Google Colab 部署 sdwebui的配置解决方案

### ISSUE THREAD

**Issue by gudong-mengxi** [zhayujie/chatgpt-on-wechat#671]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by gudong-mengxi** [comment]
请问用谷歌colab的https地址，如何配置到到config里启动

**Comment by lanvent** [comment]
修改`sdwebui/config.json`哈， 有`use_https`的选项， 
参考https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui

**Comment by zhangzhanhui** [comment]
Colab90分钟还是多长时间不用就会给停掉，难道每次手动启动一下？

**Comment by gudong-mengxi** [comment]
> 修改`sdwebui/config.json`哈， 有`use_https`的选项， 参考https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui

大佬，我拉取更新后修改了config，但是我发现Colab部署的openapi.json里面没有sdapi/v1/txt2img，请问必须是本地部署的才有嘛

**Comment by akushonkamen** [comment]
> 修改`sdwebui/config.json`哈， 有`use_https`的选项，
> 参考https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui

大佬，请问use_https这个选项要怎么用呢？改成true？那么public link应该放在哪里呢？

**Comment by adminlove520** [comment]
我找到一个解决方案，但是得改代码。就是利用koishi的https://bot.novelai.dev/插件。里面有连接sd私服的。这样就可以解决sd不方便部署的问题了。亲爱哒开发者，可以改一下代码嘛~

**Comment by adminlove520** [comment]
https://github.com/db0/AI-Horde/blob/main/README_StableHorde.md#joining-the-horde
这个是私服仓库，其实可以考虑后续加入mj的

**Comment by adminlove520** [comment]
> > 修改`sdwebui/config.json`哈， 有`use_https`的选项， 参考https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui
> 
> 大佬，我拉取更新后修改了config，但是我发现Colab部署的openapi.json里面没有sdapi/v1/txt2img，请问必须是本地部署的才有嘛

这是因为你没有配置－－api参数启动

**Comment by adminlove520** [comment]
谷歌云有个风险就是特别容易无法使用gpu计算单元，所以不是很稳定，这个私服可以通过命令来解决模型切换等问题，还是挺方便的

**Comment by adminlove520** [comment]
我想了个方案，就是koishi启一个公网地址，指向sd私服，然后sd插件调这个地址，但是api地址估计有变化呢

**Comment by gudong-mengxi** [comment]
> > > 修改`sdwebui/config.json`哈， 有`use_https`的选项， 参考https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui
> > 
> > 
> > 大佬，我拉取更新后修改了config，但是我发现Colab部署的openapi.json里面没有sdapi/v1/txt2img，请问必须是本地部署的才有嘛
> 
> 这是因为你没有配置－－api参数启动

解决了，谢谢大佬
