### ISSUE TITLE
openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)

### ISSUE THREAD

**Issue by create-info** [zhayujie/chatgpt-on-wechat#673]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
railway上部署成功后，扫码登录成功，微信私聊页面输入”bot 你好“，返回ERROR ,
Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)

### 终端日志 (如有报错)
[INFO][2023-03-29 04:02:29][wechat_channel.py:234] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
请再问我一次吧), receiver=@944adbb36abde485a71ad0255d0cc231f1d214805c18347f3c90ba5c571adf92
resp, got_stream = self._interpret_response(result, stream)
File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
self._interpret_response_line(
File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
[INFO][2023-03-29 04:02:29][wechat_channel.py:234] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
请再问我一次吧), receiver=@944adbb36abde485a71ad0255d0cc231f1d214805c18347f3c90ba5c571adf92
File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
self._interpret_response_line(
File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
```
[在此处粘贴终端日志]
```

### 环境
live
 - 操作系统类型  (Mac/Windows/Linux)：railway上部署的
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by handongfang** [comment]
这问题有人解决了吗？

**Comment by lanvent** [comment]
检查配置看是否开启了`azure gpt`，把这行删除。

**Comment by handongfang** [comment]
好的，非常感谢您的解答😄，明天我找找我还有一个小疑问，就是开启百度的插件机器人后，所有回答都是百度的机器人的答案，不是应该只有部分chatgpt回答不了的比如天气，今日日期等问题，是哪里有开关提示由谁作答吗🧐发自我的 iPhone在 2023年4月2日，16:18，Jianglang ***@***.***> 写道：﻿
检查配置看是否开启了azure gpt，把这行删除。

**Comment by lanvent** [comment]
可能是技能加太多了，比如闲聊这种技能很大程度上会命中。
我只开启了天气时间笑话跟计算，不常触发

**Comment by handongfang** [comment]
嗦嘎嗦嘎，确实我开了很多，哈哈哈   果然还是要作者更能知晓问题根源，经验少加上不是自己写的代码啥问题都不知道🤣。我只注意到 会话意图都被dbunit 插件拦截，没想到是因为给这个插件机器人开过多技能了，再次感谢你的解答发自我的 iPhone在 2023年4月2日，22:10，Jianglang ***@***.***> 写道：﻿
可能是技能加太多了，比如闲聊这种技能很大程度上会命中。
我只开启了天气时间笑话跟计算，不常触发
