### ISSUE TITLE
关于docker使用及版本更新

### ISSUE THREAD

**Issue by Sebastronne** [zhayujie/chatgpt-on-wechat#680]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

最近几天都在关注这个项目，大佬持续更新各种功能修复bug速度太快了。因为自己目前是fork并同步本项目然后用railway部署，有修改的话railway就会自己重新部署，并且我自己也重新弄了个branch可以做一些个性化的修改（涉及代码本身而非配置文件，比如对.py文件的修改，或者在插件里面改配置啥的)，这样可以比较快用上新功能，做新的尝试。

同时这两天也用了docker成功部署并且登录。但就版本而言，似乎只能是本项目master branch下大佬release了新版本的tag以后才可以用，从迭代上来说相对被动。

因为用nas的原因可能docker方面不是纯小白，但是也是个外行人。如果在docker-compose up --build 命令运行时，是否可以特定链接到我自己fork的repo，这样比较自由的根据自己fork下来修改过的文件来运行？以及关于插件的使用，是否可以通过确定插件在容器内运行的位置，在compose文件里的volume链接一下/plugin是否可以实现？

提前谢谢大佬解答~

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：群晖nas
 - Python版本  ( 执行 `python3 -V` )：   3.8                
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23

**Comment by lanvent** [comment]
你好，可以使用[build.latest.sh](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/docker/build.latest.sh)，它会使用你当前的工作目录来构建镜像。
