### ISSUE TITLE
加入对GPT4模型的支持（如何配置）

### ISSUE THREAD

**Issue by zgxtao** [zhayujie/chatgpt-on-wechat#681]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

如何在现有项目里，用最简单的方式实现项目支持GPT4模型？

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by wittefeng** [comment]
4的api没有开放，别想了

**Comment by zgxtao** [comment]
我有GPT4的API接口

**Comment by lanvent** [comment]
参照主页的`model`配置项

**Comment by wittefeng** [comment]
现有api支持GPT4，只需要将model的参数改为gpt-4就可以了。

**Comment by zgxtao** [comment]
> 参照主页的`model`配置项

你是说直接在config.json中增加 “model”:"gpt4"这个配置吗？

**Comment by wittefeng** [comment]
> > 参照主页的`model`配置项
> 
> 你是说直接在config.json中添加“model”:"gpt4"这个配置吗？

对

**Comment by danielqingz** [comment]
> > > 参照主页的`model`配置项
> > 
> > 
> > 你是说直接在config.json中添加“model”:"gpt4"这个配置吗？
> 
> 对

你好，请问我也获得了api并且修改了model中的配置，但是还是使用的gpt3，甚至不是3.5，请问你有遇到类似的情况么，感谢！

**Comment by ZackPu** [comment]
> 



> 

我也是这种情况，麻烦问一下目前解决了吗？

**Comment by ZackPu** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/issues/681#issuecomment-1493571580
我也是这个情况，@danielqingz 您解决了吗？
