### ISSUE TITLE
bdunit插件用不了，调试了下，很奇怪，大家没用这个么？

### ISSUE THREAD

**Issue by lious68** [zhayujie/chatgpt-on-wechat#682]
bdunit插件用不了啊。

我调试了下，看和baidu文档里请求参数和返回对象都不一样。

报错如下：
1、参数不对，用原参数和URL报始终返回： {"error_code":292002,"error_msg":"未找到相应的技能"} .
![微信图片_20230329201733](https://user-images.githubusercontent.com/15836048/228535793-ba7a598c-048c-4542-8f24-8611772df5b4.png)

2、返回值里和作者要提取的不对，图2
![微信图片_20230329201807](https://user-images.githubusercontent.com/15836048/228535891-9c71e944-11f9-4e71-ad4d-dccb916675cb.png)

![微信图片_20230329201814](https://user-images.githubusercontent.com/15836048/228535918-cf723c5c-51b1-4a94-af57-da4b879c6ac4.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
需要在机器人上添加技能， 测试只有时间，天气有用。

**Comment by lious68** [comment]
机器人上添加了技能呢

**Comment by lanvent** [comment]
检查下`config.json`看看，装备的技能有天气吗

**Comment by lious68** [comment]
是这样配置么？
![image](https://user-images.githubusercontent.com/15836048/228582205-973ec0f9-0293-4245-9798-4baaab95ee12.png)
![image](https://user-images.githubusercontent.com/15836048/228582298-8c138796-0379-4170-a31f-74a4afe36606.png)

**Comment by zwssunny** [comment]
service_id配置要用机器人ID ，s开头的ID号，不是APP_ID号
1、这个连接进入智能UNIT云端，进入平台后申请机器人，会得到机器人ID ，如：s123456
https://ai.baidu.com/unit/home#/home?track=61fe1b0d3407ce3face1d92cb5c291087095fc10c8377aaf
![myrobot](https://user-images.githubusercontent.com/14110660/228588271-8bc2df09-1fd0-43ac-bc8a-843ab5de59a6.png)

2、这个连节创建应用，得到api key 和secret key
https://console.bce.baidu.com/ai/?_=1680102559804#/ai/unit/overview/index
![Uploading unitapi_key.png…]()

**Comment by zwssunny** [comment]
service_id配置要用机器人ID ，s开头的ID号，不是APP_ID号
1、这个连接进入智能UNIT云端，进入平台后申请机器人，会得到机器人ID ，如：s123456
https://ai.baidu.com/unit/home#/home?track=61fe1b0d3407ce3face1d92cb5c291087095fc10c8377aaf
![myrobot](https://user-images.githubusercontent.com/14110660/228588271-8bc2df09-1fd0-43ac-bc8a-843ab5de59a6.png)

2、这个连节创建应用，得到api key 和secret key
https://console.bce.baidu.com/ai/?_=1680102559804#/ai/unit/overview/index
![Uploading unitapi_key.png…]()

**Comment by lious68** [comment]
OK了。多谢大佬

**Comment by zwssunny** [comment]
![63cfea5e6e527380b982a7f2490a5f03](https://user-images.githubusercontent.com/14110660/228592284-36cd2d8b-76db-4d98-bba4-5e5cb7f978cc.png)

**Comment by goxofy** [comment]
奇怪啊，我配置好了但是不起作用是什么情况。。貌似触发不了百度的api

**Comment by zwssunny** [comment]
> 奇怪啊，我配置好了但是不起作用是什么情况。。貌似触发不了百度的api

1、有没有在plugins.json中添加启用BDunit?
2、有没有在你的机器人中添加预训练技能？

**Comment by goxofy** [comment]
@zwssunny 感谢大佬回复，应该是都ok的，我能看到bdunit插件初始化成功，但是无论我怎么尝试，都无法触发，在百度平台上也看不到请求

![image](https://user-images.githubusercontent.com/1695416/229013527-a068e035-4c31-429d-bdd1-55ff7ef0372e.png)
![image](https://user-images.githubusercontent.com/1695416/229013567-4fc556db-fdfb-4a53-96f6-7913f679657a.png)
![image](https://user-images.githubusercontent.com/1695416/229013598-9c7fbb8b-ccf9-4509-b16c-56f03e0a0ae5.png)

**Comment by zwssunny** [comment]
有没有输出日志
https://github.com/zhayujie/chatgpt-on-wechat/issues/682#issuecomment-1488838253

**Comment by goxofy** [comment]
@zwssunny 我重新部署了一次项目，这次可以了~感谢！

**Comment by LeafBanks** [comment]
> @zwssunny 我重新部署了一次项目，这次可以了~感谢！

只是重新装了这个板块吗

**Comment by hecarli555** [comment]
貌似群聊无法触发？

**Comment by zwssunny** [comment]
> 

1、具体配置往上面看或者看百度unit官网，需要相应创建unit机器人（记得导入已有的技能：天气，日期时间，数学运算...）和unit应用调用API参数
2、使用很简单，没有特殊输入要求，如果插件bdunit 能解析出意图就回答，否则就交给后续的插件或者chatgpt

**Comment by hecarli555** [comment]
> > 
> 
> 1、具体配置往上面看或者看百度unit官网，需要相应创建unit机器人（记得导入已有的技能：天气，日期时间，数学运算...）和unit应用调用API参数 2、使用很简单，没有特殊输入要求，如果插件bdunit 能解析出意图就回答，否则就交给后续的插件或者chatgpt

这个插件貌似不能在群聊中触发？？？只有私聊的时候能运作

**Comment by zwssunny** [comment]
> > > 
> > 
> > 
> > 1、具体配置往上面看或者看百度unit官网，需要相应创建unit机器人（记得导入已有的技能：天气，日期时间，数学运算...）和unit应用调用API参数 2、使用很简单，没有特殊输入要求，如果插件bdunit 能解析出意图就回答，否则就交给后续的插件或者chatgpt
> 
> 这个插件貌似不能在群聊中触发？？？只有私聊的时候能运作
![bdunit群聊](https://user-images.githubusercontent.com/14110660/231315038-06a18ecf-f726-473e-a4ce-c679cdfbb1ad.jpg)
