### ISSUE TITLE
现在微信部署，还会封号吗？

### ISSUE THREAD

**Issue by Wait1234** [zhayujie/chatgpt-on-wechat#684]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by qiukaiclub** [comment]
会，刚刚被封

**Comment by a472691** [comment]
会的，刚被封，应该是有解决方案啊，不知道有谁知道

**Comment by lious68** [comment]
微信真聪明，封了大家都去飞书玩。
作者弄个支持飞书版本的把。
用户都去飞书了，呵呵

**Comment by jk256** [comment]
有个实名微信小号只是个人用，两个星期被限制，感觉没有被针对，只是检测用户行为和外挂特征，然后被误伤。你可以尝试扫码登录后的传文件功能，时不时发点东西发个消息。。。猜测有效但未验证。

**Comment by gwailee** [comment]
> 有个实名微信小号只是个人用，两个星期被限制，感觉没有被针对，只是检测用户行为和外挂特征，然后被误伤。你可以尝试扫码登录后的传文件功能，时不时发点东西发个消息。。。猜测有效但未验证。

没有用，听说用你的机器人找腾讯借钱有用，话说借钱是大爷，不会封号的，封了就不用还钱了。

**Comment by leealu** [comment]
刚被封·说风险·无语

**Comment by a472691** [comment]
我该用wechaty方案了，目前运行暂时稳定，就是没有各种插件，在研究怎么接入

**Comment by joeleo** [comment]
> 
wechaty是什么方案，不是用这个仓库的代码搞吗

**Comment by gwailee** [comment]
今天开始全面封号，我的几个全部被封，QQ版和微信版都一样，因为断人家财路吧



***@***.***
 
发件人： Dee1024
发送时间： 2023-03-31 22:37
收件人： zhayujie/chatgpt-on-wechat
抄送： gwailee; Comment
主题： Re: [zhayujie/chatgpt-on-wechat] 现在微信部署，还会封号吗？ (Issue #684)
这是什么呢

**Comment by leealu** [comment]
> 我改用wechaty方案了，目前运行暂时稳定，就是没有各种插件，在研究怎么接入

wechat不封号吗？我今天很久之前部署的一个都没用的微信，也没对话，都被警告了

**Comment by a472691** [comment]
> > 我改用wechaty方案了，目前运行暂时稳定，就是没有各种插件，在研究怎么接入
> 
> wechat不封号吗？我今天很久之前部署的一个都没用的微信，也没对话，都被警告了

昨天被封号了。。。但是提示是被举报

**Comment by gwailee** [comment]
有没有教程，我是直接源码按照requirements安装的，提示一堆错误。换成wetchat就可以正常跑。



***@***.***
 
发件人： a472691
发送时间： 2023-04-01 10:56
收件人： zhayujie/chatgpt-on-wechat
抄送： gwailee; Comment
主题： Re: [zhayujie/chatgpt-on-wechat] 现在微信部署，还会封号吗？ (Issue #684)
我改用wechaty方案了，目前运行暂时稳定，就是没有各种插件，在研究怎么接入
wechat不封号吗？我今天很久之前部署的一个都没用的微信，也没对话，都被警告了
昨天被封号了。。。但是提示是被举报

**Comment by ringki** [comment]
用hook的方式 桌面端微信 模拟人工操作的形式就不会被封号吧

**Comment by kakarala** [comment]
中午接入，下午被封了
