### ISSUE TITLE
能支持Dall·E吗，可以加入进去 吗

### ISSUE THREAD

**Issue by oneeno** [zhayujie/chatgpt-on-wechat#685]

**Comment by oneeno** [comment]
https://labs.openai.com/
这个

**Comment by lanvent** [comment]
我没使用过，它和目前带的`openai`画图有区别吗。

**Comment by autherlj** [comment]
OpenAI的画图技术是基于GPT模型的，而DALL·E则是基于GPT和Transformer的结合模型。DALL·E不仅可以生成图像，还可以生成复杂的图像场景、图像排版和图像操作等，因此它的应用场景更加广泛。
理论上这个的接入实现应该比SDWEBUI方便一些，SD的专业参数调试还是有一定门槛的。希望大佬可以看下是否可以接入。不过DALL·E 115个信用点需要￥15 刀
