### ISSUE TITLE
Audio chat error

### ISSUE THREAD

**Issue by mobilEKG** [zhayujie/chatgpt-on-wechat#687]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

Get the following error message when send a audio
```
ERROR:
Failed to connect. Probable cause: Unknown
```

### 终端日志 (如有报错)

```
[INFO][2023-03-29 20:15:15][openai_voice.py:25] - [Openai] voiceToText text=Any update with OpenAI? voice file name=tmp/230329-201511.wav
[INFO][2023-03-29 20:15:15][chat_gpt_bot.py:34] - [CHATGPT] query=Any update with OpenAI?
[INFO][2023-03-29 20:15:26][bridge.py:28] - create bot google for text_to_voice
[INFO][2023-03-29 20:15:38][wechat_channel.py:235] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
Failed to connect. Probable cause: Unknown), receiver=@27a7ea1b0e94fde1ceaa74fcd048eced5bcf17c185154ef4a5b7639eecec5ffc
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zwssunny** [comment]
连接不上服务器，google语音需要科学上网

**Comment by mobilEKG** [comment]
部署在Oracle韩国的服务器上，仍然需要科学上网吗？

**Comment by zwssunny** [comment]
这个第三方库封装了，估计调用额度问题；建议先用百度语音把，注册一下有免费资源用

**Comment by mobilEKG** [comment]
百度语音工作正常
