### ISSUE TITLE
画图生成简笔画，无法生成图片

### ISSUE THREAD

**Issue by Danggui-8** [zhayujie/chatgpt-on-wechat#689]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖满足
5. 在已有 issue 中未搜索到类似问题，#259 中没理解怎么修改
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
只能画简笔画
![20230330-112112](https://user-images.githubusercontent.com/129157274/228720567-f1822664-d99b-4490-8c73-f8b594d8847f.jpg)
![screenshot-20230330-112022](https://user-images.githubusercontent.com/129157274/228720595-088ce85b-9ea3-47c8-81c3-3b9aee130364.png)

### 终端日志 (如有报错)
无报错

### 环境

操作系统 阿里云linux；Python 3.9.3；pip 23.0.1

**Comment by jcdiv47** [comment]
试下这个：“小空 画一个老虎”

**Comment by Danggui-8** [comment]
解决了！感谢，应该是逗号造成了干扰...
