### ISSUE TITLE
如何配置禁止被自己触发

### ISSUE THREAD

**Issue by Muchenyao** [zhayujie/chatgpt-on-wechat#694]
### 问题描述

> 不使用关键字的话，如何配置禁止被自己触发，特别是单聊时

**Comment by lanvent** [comment]
当前没有提供这个配置，建议不用大号当bot哈

**Comment by jcdiv47** [comment]
> 当前没有提供这个配置，建议不用大号当bot哈

请问如果有两个微信号，但是只有一台iPhone的情况下，有没有办法用小号当bot啊？我没找到手机使用大号，但是又不会导致小号退出登录的办法

**Comment by lanvent** [comment]
现在不允许自己触发了
