### ISSUE TITLE
生成不了画，也调用不了角色扮演

### ISSUE THREAD

**Issue by soso010816** [zhayujie/chatgpt-on-wechat#699]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
<img width="719" alt="image" src="https://user-images.githubusercontent.com/79573430/228856182-8e4660e8-3cef-4c4e-8365-5789b8c7d0ea.png">

![IMG_2491(20230330-214625)](https://user-images.githubusercontent.com/79573430/228857007-b2dfe6cb-a266-4a37-a0bf-3c854a8a9368.PNG)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
触发前缀是空的话，就不要加前缀了。
