### ISSUE TITLE
扫码后报错

### ISSUE THREAD

**Issue by yunyunxixia** [zhayujie/chatgpt-on-wechat#7]
这个错误消息显示，你在调用 itchat 库中的 process_login_info() 函数时出现了 IndexError: list index out of range 错误。这意味着你尝试访问一个列表中不存在的索引。

在这个函数中，你使用了正则表达式来查找 <skey> 标签中的值，并使用 re.findall() 函数返回匹配结果。如果找不到匹配的内容，则返回空列表，导致 IndexError: list index out of range 错误。

**Comment by zhayujie** [comment]
是不是微信号没有实名认证

**Comment by yunyunxixia** [comment]
上述错误为没有实名认证

python版本3.11太新会报错，改为python3.9
 itchat报错 , 用 itchat-uos 1.5.0 dev0
登入成功，但是机器人没有回复，也没有报错

**Comment by yunyunxixia** [comment]
上述错误为没有实名认证

python版本3.11太新会报错，改为python3.9
 itchat报错 , 用 itchat-uos 1.5.0 dev0
登入成功，但是机器人没有回复，也没有报错

**Comment by zhayujie** [comment]
1.python版本只支持 3.7.1 - 3.9，文档已更新
2.使用itchat-uos
3.触发前缀匹配问题，已修复
