### ISSUE TITLE
私聊设置无触发词""后无法正确触发机器人回复

### ISSUE THREAD

**Issue by Sebastronne** [zhayujie/chatgpt-on-wechat#703]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
私聊设置无触发词""后无法正确触发机器人回复。但是在群聊中直接艾特却可以(groupchatprefix也是"")
railway从本项目直接部署，以及在我自己fork的项目中部署均有这种问题。
docker部署也有这种问题
但上述问题若使用"bot"或其他有内容的触发词就可以正确触发
![Uploading 1680186104212.png…]()

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
这个在最新的commit里修复了吧，railway上redeploy下吧。

**Comment by Sebastronne** [comment]
> 这个在最新的commit里修复了吧，railway上redeploy下吧。

收到，redeploy后问题已修复，谢谢大佬
