### ISSUE TITLE
pysilk-mod安装失败

### ISSUE THREAD

**Issue by lp651190021** [zhayujie/chatgpt-on-wechat#704]
### 前置确认
确认没有

### 问题描述

![image](https://user-images.githubusercontent.com/40174597/228867239-2dbd2b12-7e47-4483-92d8-766e50f32295.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by mari1995** [comment]
@lanvent 这个问题怎么解决的？

      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -DVERSION_INFO=1.6.2 -Isrc/silk/interface -I/private/var/folders/jr/5p9hkcw16z3_d8rd5lmn6hy40000gn/T/pip-build-env-72fuhm13/overlay/lib/python3.10/site-packages/pybind11/include -I/Users/mario/Documents/GitHub/chatgpt-on-wechat/venv/include -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/silk/src/SKP_Silk_interpolate.c -o build/temp.macosx-13-arm64-cpython-310/src/silk/src/SKP_Silk_interpolate.o -mmacosx-version-min=10.14 -fvisibility=hidden -g0 -stdlib=libc++
      src/silk/src/SKP_Silk_interpolate.c:28:10: fatal error: 'SKP_Silk_main.h' file not found
      #include "SKP_Silk_main.h"
               ^~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysilk_mod
Failed to build pysilk_mod
ERROR: Could not build wheels for pysilk_mod, which is required to install pyproject.toml-based projects

**Comment by zhaoxitao** [comment]
同样的问题，我是一个特殊的32位arm环境，pip自动安装无论如何都会出错，因为安装工具把系统识别位64位了，尝试手工编译安装可以解决。
`pip install git+https://github.com/DCZYewen/Python-Silk-Module`

**Comment by caizhuoyue77** [comment]
> pip install git+https://github.com/DCZYewen/Python-Silk-Module

MacOS m1芯片 亲测成功了！非常感谢！🌹
