### ISSUE TITLE
Exception: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by qinbatista** [zhayujie/chatgpt-on-wechat#705]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

麻烦问一下用的是哪个版本的openai库呢，这个方法好像没有，目前在测试chatgpt4，刚刚得到了权限

### 终端日志 (如有报错)

Login successfully as Batista
[INFO][2023-03-30 09:07:03][wechat_channel.py:95] - Wechat login success, username: @05032bcff7a8b03e9a764f8490e09497, nickname: Batista
Start auto replying.
[INFO][2023-03-30 09:07:08][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-03-30 09:07:08][chat_gpt_bot.py:34] - [CHATGPT] query=实话实说
[WARNING][2023-03-30 09:07:08][chat_gpt_bot.py:127] - [CHATGPT] Exception: module 'openai' has no attribute 'ChatCompletion'
[INFO][2023-03-30 09:07:08][wechat_channel.py:263] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
我现在有点累了，等会再来吧), receiver=@05032bcff7a8b03e9a764f8490e09497

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Mac
 - Python版本  ( 执行 `python3 -V` )：Python 3.11.2                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)

**Comment by lanvent** [comment]
`pip3 install -r requirements.txt`
