### ISSUE TITLE
Railway部署后可以正常识别语音，但无法识别文字，报错如下，大佬帮忙看一下

### ISSUE THREAD

**Issue by wang-hk** [zhayujie/chatgpt-on-wechat#706]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
Start auto replying.
[INFO][2023-03-30 16:08:24][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-03-30 16:08:25][chat_gpt_bot.py:34] - [CHATGPT] query=J
[ERROR][2023-03-30 16:08:46][wechat_channel.py:34] - Worker return exception: can only concatenate list (not "str") to list
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/app/channel/wechat/wechat_channel.py", line 297, in handle
reply = self._decorate_reply(context, reply)
File "/app/channel/wechat/wechat_channel.py", line 358, in _decorate_reply
reply_text = conf().get("single_chat_reply_prefix", "")+reply_text
TypeError: can only concatenate list (not "str") to list

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by hy546880109** [comment]
请问你部署到Railway需要配置代理吗？
