### ISSUE TITLE
bdunit使用迷思，无法调用bdunit的服务

### ISSUE THREAD

**Issue by akushonkamen** [zhayujie/chatgpt-on-wechat#707]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

在bdunit文件夹下已将config.json.template复制成config.json, 并配置好了sid, api, secret key
<img width="377" alt="Screen Shot 2023-03-31 at 01 18 24" src="https://user-images.githubusercontent.com/74654766/228914915-c2f5d8d6-3345-4bc0-a600-4958e342e833.png">

但是启动服务后既没有显示bdunit的服务代码，也无法调用bdunit的服务，同时也没有报错。但其他插件和聊天服务均可正常使用

求大佬们帮助

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
[INFO][2023-03-31 01:34:35][plugin_manager.py:30] - Plugin BDunit_v0.1 registered
﻿[INFO][2023-03-31 01:34:35][plugin_manager.py:78] - Plugin BDUNIT not found in pconfig, adding to pconfig...
﻿[WARNING][2023-03-31 01:34:35][bdunit.py:39] - BDunit init failed: config.json not found, ignore

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by goxofy** [comment]
我的bdunit 初始化都成功了，但是不管怎么搞都触发不了，这是啥情况啊

**Comment by LeafBanks** [comment]
是不是没有装USKit

**Comment by akushonkamen** [comment]
重新fork后可以了。。怪异。。。
