### ISSUE TITLE
用阿里云部署，怎么安装核心依赖这么多错误 pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by lkyuier** [zhayujie/chatgpt-on-wechat#710]
在阿里云的centos7上部署的时候， pip3 install -r requirements.txt 跑这个命令，几乎都会遇到版本问题，有没有办法解决？

最后有个大神说指定python 用这个命令跑： python -m pip install -r requirements.txt or python3 -m pip install -r requirements.txt

**Comment by zzchust** [comment]
https://mp.weixin.qq.com/s/E4lPoRga27u4VpevgUfGzw

可以参考这里的教程，先下载miniconda3，再安装。

云服务器默认的python是python2， 你需要先安装python3
