### ISSUE TITLE
记录一下2023.3.31，微信封号大地震。关注：Youngerer，扫码进群交流（不要加我为微信啦）

### ISSUE THREAD

**Issue by 6vision** [zhayujie/chatgpt-on-wechat#718]
被封的这里集合
不知道这里允不允许留下联系方式，可以加我vx:Bear_Ab，可以建个群互通信息！

**Comment by helloyan** [comment]
没封，被警告了，但是警告的并不是用于登录的号，是与bot对话的号

**Comment by rhy12345** [comment]
被警告了

**Comment by bigfoot88** [comment]
被封了

**Comment by hpsprger** [comment]
有没有交流群？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月31日(周五) 晚上9:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 记录一下2023.3.31，微信封号大地震 (Issue #718)




 
被封了

**Comment by rhy12345** [comment]
没有，你可以创建个，微信玩不起

**Comment by zken2002** [comment]
临时限制

**Comment by rhy12345** [comment]
用大佬的这个项目把接入公众号订阅号 https://github.com/zhayujie/bot-on-anything

**Comment by joeleo** [comment]
看来警告的人很多，我在想是不是异地登录的原因，加群名称chatGPT关键字的原因，还有一些聊天中的关键字

**Comment by helloyan** [comment]
说不定只是不停查询github看看有没有开源的微信机器人，然后人工验证，微信这种说一不二，你想复议都没机会，真希望有软件可以打败他

**Comment by jk256** [comment]
+1 ，九点左右bot提示logout，强制退出登录，弹出外挂警告，需要你点同意不在使用才能手机登录，其他功能没提示限制。只是个警告，另外问一下sms再注册个新微信要登陆网页版微信是不是需要实名？是否接着能用呢

**Comment by dee1024** [comment]
被警告⚠️

**Comment by jobs9527** [comment]
被警告了

**Comment by jokerlinnn** [comment]
被警告了

**Comment by hankeyyh** [comment]
同样被警告

**Comment by 6vision** [comment]
> 

contact me：Bear_Ab

**Comment by explorerJi** [comment]
同样被警告。接入了这么久，第一次被警告。近期换节点了，感觉和换节点有关系。

**Comment by 6vision** [comment]
> 告

应该不是的，是腾讯不定时来一波，文心发布前一晚封一波，今晚又是一波

**Comment by hustyichi** [comment]
昨天登陆了一次，今天被警告了，要求承诺再不用了

**Comment by judge135** [comment]
被警告

**Comment by zhangdayeIMAX** [comment]
被警告了

**Comment by ZHYuXi21** [comment]
被警告，并且限制功能了。。。

**Comment by warsofroses** [comment]
被封了，验证人脸和手机后恢复了

**Comment by leealu** [comment]
公众号现在有问题没？有没有被封？> > 用大佬的这个项目把接入公众号订阅号 https://github.com/zhayujie/bot-on-anything
> 
> 
> 
> 是的，我接入了，目前正常使用，公众号这个应该比较稳，可以关注我的  Youngerer  体验使用！

**Comment by Lettingoo** [comment]
瑟瑟发抖。 有群的发一下

**Comment by lichengzhe** [comment]
https://github.com/mostlittlebee/chatgpt-on-wecom

**Comment by ningminynwa** [comment]
封了，昨晚七点多

**Comment by gwailee** [comment]
> 公众号现在有问题没？有没有被封？> > 用大佬的这个项目把接入公众号订阅号 https://github.com/zhayujie/bot-on-anything
> 
> > 是的，我接入了，目前正常使用，公众号这个应该比较稳，可以关注我的  Youngerer  体验使用！

公众号有被封的风险，有人提过issue，你可以查看，并且是永久封号，慎重用

**Comment by congxuma** [comment]
被警告

**Comment by autherlj** [comment]
> +1 ，九点左右bot提示logout，强制退出登录，弹出外挂警告，需要你点同意不在使用才能手机登录，其他功能没提示限制。只是个警告，另外问一下sms再注册个新微信要登陆网页版微信是不是需要实名？是否接着能用呢
/

**Comment by autherlj** [comment]
> > +1 ，九点左右bot提示logout，强制退出登录，弹出外挂警告，需要你点同意不在使用才能手机登录，其他功能没提示限制。只是个警告，另外问一下sms再注册个新微信要登陆网页版微信是不是需要实名？是否接着能用呢
> > 
-------------------------------------
新的微信号需要实名才能用，但是如果你用小号实名的话，到时候是大号也要被警告，只要是用一个人名的号都直接警告
