### ISSUE TITLE
启动项目时生成的二维码乱码，且二维码接口的网址显示超时

### ISSUE THREAD

**Issue by 1553497378** [zhayujie/chatgpt-on-wechat#730]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/33971782/229333783-14ab4cb1-e54d-4829-90b3-bab828152e30.png)

![image](https://user-images.githubusercontent.com/33971782/229333812-c4cd012b-5cef-4efd-97e9-df211ceec650.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by YBL1984** [comment]
SSH 登陆即可解决

**Comment by lanvent** [comment]
拉取最新版本吧，增加了3个二维码api

**Comment by 1553497378** [comment]
> 拉取最新版本吧，增加了3个二维码api

刚刚重新pull过了，好像还是不行

**Comment by lanvent** [comment]
打印出来的4个网址都不行吗

**Comment by 1553497378** [comment]
> 打印出来的4个网址都不行吗

只有一个网址哦

![image](https://user-images.githubusercontent.com/33971782/229336287-6e92c5f6-93d6-4291-98bc-6b60a939c9ba.png)
![image](https://user-images.githubusercontent.com/33971782/229336294-648f4484-3684-4b02-aab5-c243700dc2e6.png)

**Comment by lanvent** [comment]
那还需要pull下最新版本

**Comment by 1553497378** [comment]
> 那还需要pull下最新版本，最新版本有4个网址

好的，谢谢

**Comment by ZhangHafa** [comment]
如图一样的乱码，更新于4/9号，还是乱码

**Comment by lanvent** [comment]
乱码是你Terminal的字体问题，你可以随意选择一个二维码网址登陆
