### ISSUE TITLE
提问太快啦，请休息一下再问我吧 是什么原因啊？

### ISSUE THREAD

**Issue by jiuchu** [zhayujie/chatgpt-on-wechat#731]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

[INFO][2023-04-02 14:57:40][chat_gpt_bot.py:34] - [CHATGPT] query=你好
[WARNING][2023-04-02 14:57:41][chat_gpt_bot.py:113] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-04-02 14:57:46][chat_gpt_bot.py:132] - [CHATGPT] 第1次重试
[WARNING][2023-04-02 14:58:00][chat_gpt_bot.py:113] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-04-02 14:58:05][chat_gpt_bot.py:132] - [CHATGPT] 第2次重试
[WARNING][2023-04-02 14:58:06][chat_gpt_bot.py:113] - [CHATGPT] RateLimitError: You exceeded your current quota, please check your plan and billing details.
[INFO][2023-04-02 14:58:06][wechat_channel.py:181] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
提问太快啦，请休息一下再问我吧), receiver=@686588029306293e0c84a64832fb9d95
### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by RuijieZhang2** [comment]
同问哈

**Comment by unique-Elven** [comment]
环境都没问题呀，我也遇到了这样的问题，请问怎么解决？

**Comment by deng3shui** [comment]
解决了吗
