### ISSUE TITLE
用了一天一夜，提个改进意见：做一个api key的列表文件，随机抽取key，这样解决高并发的时候对单个key调用频率过高的问题。今天早上起来我的openAI账号直接被封禁了，同时微信也收到了警告。

### ISSUE THREAD

**Issue by rover1003** [zhayujie/chatgpt-on-wechat#732]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by bennywnn** [comment]
封禁这事应该不赖API，今天openai大屠杀。。。

**Comment by yhfgyyf** [comment]
我也挂了一个账号，还好自己的PLUS账号没事

**Comment by Wetiqe** [comment]
> 我也挂了一个账号，还好自己的PLUS账号没事

是纯海外账号被封了吗，还是虚拟手机号注册的那种
