### ISSUE TITLE
二维码生成后，微信扫码不出来

### ISSUE THREAD

**Issue by smallcups** [zhayujie/chatgpt-on-wechat#736]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

二维码生成后，微信扫码不出来，放到其他解码工具也不能识别
![image](https://user-images.githubusercontent.com/94780217/229397905-635050bc-fb4a-4aec-8dac-dd86f6952aa2.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Windows
 - Python版本  ( 执行 `python3 -V` )： 
 - Python 3.9.7                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
 - pip 23.0.1

**Comment by hecarli555** [comment]
窗口放大一些

**Comment by smallcups** [comment]
> 

已经是最大了呀

**Comment by econe-zhangwei** [comment]
请问解决了吗？我也是这个问题

**Comment by kongwz** [comment]
我的wx之前被封了  解封后就扫不了码了

**Comment by lanvent** [comment]
登录时还会给出4个二维码网址，往上翻下

**Comment by forczc** [comment]
大部分人的控制台输出的二维码是扫不出来的，但二维码的上方有几个链接，随便一个复制到普通浏览器打开就可以了

**Comment by lanvent** [comment]
拉取最新代码
