### ISSUE TITLE
配置正确，扫码登陆后触发不了回复，似乎没有接受到消息一样（问题原因是自动跳过自己对话，不知是否有配置项设置不跳过？）

### ISSUE THREAD

**Issue by handongfang** [zhayujie/chatgpt-on-wechat#737]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

已确认
### 问题描述

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/82168448/229408351-d353bb77-9a11-4624-999c-df5a3a1f8f1e.png">
<img width="687" alt="image" src="https://user-images.githubusercontent.com/82168448/229408502-b12e556e-b4a9-4d24-b2c2-e8be9f42aae0.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/82168448/229410298-4811d7a5-c520-45ae-849a-62220b1348bb.png">

新拉取代码 扫码登陆成功，配置文件也配置好了触发关键词，但是似乎新的WeChat_channel接受不到我消息一样，旧版代码倒是可以接收

旧版是下载一个微信登陆图片那个，新版现在是直接弹出一个微信登录图片，这个好评！

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Mac
 - Python版本  ( 执行 `python3 -V` )：  3.9                    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1

**Comment by lanvent** [comment]
自己给自己发吗？

**Comment by handongfang** [comment]
不是，其他人  以及群里  都尝试了发自我的 iPhone在 2023年4月3日，15:59，Jianglang ***@***.***> 写道：﻿
自己给自己发吗？

**Comment by lanvent** [comment]
把[这行](https://github.com/zhayujie/chatgpt-on-wechat/blob/b74274b96b48efa5b291f1f4baa4f7fddfd311d8/common/log.py#L7)改成DEBUG，打印下log看看。
```python
log.setLevel(logging.DEBUG)
```

**Comment by congxuma** [comment]
> 

怎么设置自己可以触发么？

**Comment by handongfang** [comment]
***@***.*** 没用，会跳过自己发送的消息，那这样自己账号就不能触发了，更接近一个纯机器人了发自我的 iPhone在 2023年4月3日，18:44，Jianglang ***@***.***> 写道：﻿
把这行改成DEBUG，打印下log看看。
log.setLevel(logging.DEBUG)

**Comment by jianghongping** [comment]
十分钟之后才回复，怎么回事还不如旧版本。。。

**Comment by EasonSun615** [comment]
加下“trigger_by_self”: true就可以了

**Comment by handongfang** [comment]
> 加下“trigger_by_self”: true就可以了

在哪里加呀

**Comment by handongfang** [comment]
> 自己给自己发吗？新版默认不能自己触发了。

上次没看清就回复了，我看到有跳过自己对话的代码，这个可以哪里配置不跳过自己吗？

**Comment by lanvent** [comment]
在`config.json`内加。( 此时决定把允许自己触发的默认值改成True

**Comment by handongfang** [comment]
> 在`config.json`内加。( 此时决定把允许自己触发的默认值改成True)

> 在`config.json`内加。( 此时决定把允许自己触发的默认值改成True

嗯嗯，感觉可以把这个提示更新到首页的readme.md里面，大多数人应该都是先自己测试，还以为出问题了，或者用info日志提示自己的话被跳过


"trigger_by_self": False,  # 是否允许自己触发机器人
