### ISSUE TITLE
新版本报错

### ISSUE THREAD

**Issue by raydoomed** [zhayujie/chatgpt-on-wechat#738]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
[INFO][2023-04-03 19:40:10][plugin_manager.py:39] - Loading plugins config...
[INFO][2023-04-03 19:40:10][plugin_manager.py:55] - Scaning plugins ...
[INFO][2023-04-03 19:40:10][plugin_manager.py:30] - Plugin Banwords_v1.0 registered
[INFO][2023-04-03 19:40:10][plugin_manager.py:30] - Plugin BDunit_v0.1 registered
[INFO][2023-04-03 19:40:10][plugin_manager.py:30] - Plugin Dungeon_v1.0 registered
[INFO][2023-04-03 19:40:10][plugin_manager.py:30] - Plugin Godcmd_v1.0 registered
[INFO][2023-04-03 19:40:10][plugin_manager.py:30] - Plugin Hello_v0.1 registered
[INFO][2023-04-03 19:40:10][plugin_manager.py:30] - Plugin Role_v1.0 registered
[WARNING][2023-04-03 19:40:10][plugin_manager.py:68] - Failed to import plugin sdwebui: No module named 'webuiapi'
[INFO][2023-04-03 19:40:10][godcmd.py:135] - [Godcmd] inited
[WARNING][2023-04-03 19:40:10][banwords.py:41] - Banwords init failed: [Errno 2] No such file or directory: 'C:\\Users\\xRay\\chatgpt-on-wechat\\plugins\\banwords\\banwords.txt', ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[INFO][2023-04-03 19:40:10][role.py:46] - [Role] inited
[INFO][2023-04-03 19:40:10][dungeon.py:43] - [Dungeon] inited
[WARNING][2023-04-03 19:40:10][bdunit.py:39] - BDunit init failed: config.json not found, ignore
[INFO][2023-04-03 19:40:10][hello.py:16] - [Hello] inited
Getting uuid of QR code.
Downloading QR code.
[ERROR][2023-04-03 19:40:10][app.py:28] - App startup failed!
[ERROR][2023-04-03 19:40:10][app.py:29] - No module named 'qrcode'
Traceback (most recent call last):
  File "C:\Users\xRay\chatgpt-on-wechat\app.py", line 26, in run
    channel.startup()
  File "C:\Users\xRay\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 118, in startup
    raise e
  File "C:\Users\xRay\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 110, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
  File "C:\Users\xRay\chatgpt-on-wechat\lib\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\xRay\chatgpt-on-wechat\lib\itchat\components\login.py", line 55, in login
    qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xRay\chatgpt-on-wechat\lib\itchat\components\login.py", line 131, in get_QR
    qrCallback(uuid=uuid, status='0', qrcode=qrStorage.getvalue())
  File "C:\Users\xRay\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 80, in qrCallback
    import qrcode
ModuleNotFoundError: No module named 'qrcode'

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
`pip3 install -r requirements.txt`

**Comment by raydoomed** [comment]
pip3 install -r requirements.txt输过了，还是报错

**Comment by kimyLee** [comment]
同样qrcode库报错
