### ISSUE TITLE
二维码中间有乱码，扫描没有反应

### ISSUE THREAD

**Issue by heyanfeng** [zhayujie/chatgpt-on-wechat#74]
程序应该是启动成功了，二维码失效，间隔一段时间更新一个新的二维码，但是扫描都没反应。
![image](https://user-images.githubusercontent.com/15811017/217205263-0381a2ed-e5b9-4fed-81a7-7eefdbd0cdbc.png)

**Comment by zhayujie** [comment]
什么系统上运行的，换个终端程序试试？

**Comment by 1195458334** [comment]
> 什么系统上运行的，换个终端程序试试？

我也遇到了，windows，cmd 、powershell、git、idea 都试过了 都是乱码

换成ConEmu 可以

**Comment by zhayujie** [comment]
> ws，cmd 、powe

你的python版本是多少

**Comment by Yan0789** [comment]
您好，我的系统是win10,python3.8，运行后二维码显示不全，请问怎么调试

**Comment by zhayujie** [comment]
> 您好，我的系统是win10,python3.8，运行后二维码显示不全，请问怎么调试

如果是本地环境的话，可以改一行代码试试：
https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechat_channel.py

把37行括号里的 enableCmdQR=2 去掉试试
![image](https://user-images.githubusercontent.com/26161723/217436213-e64727e6-b6c3-4055-9a1c-d342c4de713b.png)

**Comment by Yan0789** [comment]
> > 您好，我的系统是win10,python3.8，运行后二维码显示不全，请问怎么调试
> 
> 如果是本地环境的话，可以改一行代码试试： https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechat_channel.py
> 
> 把37行括号里的 enableCmdQR=2 去掉试试 ![image](https://user-images.githubusercontent.com/26161723/217436213-e64727e6-b6c3-4055-9a1c-d342c4de713b.png)

您好，我按您的指导去掉了，虽然可以在弹出的“画图”显示二维码，扫描后，程序又重新生成了张二维码让我扫描，是哪里死循环了吗，怎么解决呢

**Comment by Yan0789** [comment]
> > > 您好，我的系统是win10,python3.8，运行后二维码显示不全，请问怎么调试
> > 
> > 
> > 如果是本地环境的话，可以改一行代码试试： https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechat_channel.py
> > 把37行括号里的 enableCmdQR=2 去掉试试 ![image](https://user-images.githubusercontent.com/26161723/217436213-e64727e6-b6c3-4055-9a1c-d342c4de713b.png)
> 
> 您好，我按您的指导去掉了，虽然可以在弹出的“画图”显示二维码，扫描后，程序又重新生成了张二维码让我扫描，是哪里死循环了吗，怎么解决呢
上面问题出现的原因：用的微X小号扫描，下号没有实名绑定，换了个号扫描可以了。显示“Login successfully as Start auto replying.”，但是我用别的账号发起@bot没有应答，咋了。

**Comment by Yan0789** [comment]
> > > > 您好，我的系统是win10,python3.8，运行后二维码显示不全，请问怎么调试
> > > 
> > > 
> > > 如果是本地环境的话，可以改一行代码试试： https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechat_channel.py
> > > 把37行括号里的 enableCmdQR=2 去掉试试 ![image](https://user-images.githubusercontent.com/26161723/217436213-e64727e6-b6c3-4055-9a1c-d342c4de713b.png)
> > 
> > 
> > 您好，我按您的指导去掉了，虽然可以在弹出的“画图”显示二维码，扫描后，程序又重新生成了张二维码让我扫描，是哪里死循环了吗，怎么解决呢
> > 上面问题出现的原因：用的微X小号扫描，下号没有实名绑定，换了个号扫描可以了。显示“Login successfully as Start auto replying.”，但是我用别的账号发起@bot没有应答，咋了。

这里跟其它的分享下：如果添加了唤醒bot前缀，不能只发bot@bot，还得连着你想问的问题一起发，就有相应，刚开始我理解程序是可以比如像叫它 小A同学，它也能回我，后面试着 bot+问题，就可以。

**Comment by heyanfeng** [comment]
> 什么系统上运行的，换个终端程序试试？

之前是用腾讯云控制台内置的终端登录的，换成本地终端可以了

**Comment by zheng96** [comment]
我用的也是腾讯云终端，同样的问题，只有腾讯云服务器，大家有解决的吗

**Comment by zhayujie** [comment]
> 我用的也是腾讯云终端，同样的问题，只有腾讯云服务器，大家有解决的吗

换个本地的终端吧，这种软件很多， mac下自带的terminal，  windows 的 xshell  等等

**Comment by KevinJun2017** [comment]
time out  无限循环 弹登陆码

**Comment by zhayujie** [comment]
@AndyHuyidi   看下依赖
pip3 show itchat-uos

**Comment by zhayujie** [comment]
@KevinJun2017  see #8
