### ISSUE TITLE
Railway部署环境变量问题

### ISSUE THREAD

**Issue by i-kirito** [zhayujie/chatgpt-on-wechat#742]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 变量设置字符问题，本地部署没问题。用railway不能加[] 去掉就就问不了

![image](https://user-images.githubusercontent.com/79130542/229687151-d3992e75-ff13-445f-ac16-02938046346d.png)
![image](https://user-images.githubusercontent.com/79130542/229687742-2485e55d-10ca-462a-8efc-c219036c11f7.png)

**Comment by lanvent** [comment]
railway可以使用env编辑器，json编辑需自行转义
```json
"group_name_white_list": "[\"ALL_GROUP\"]",
```

`admin_users`没有这个配置项哈。

**Comment by i-kirito** [comment]
好的
