### ISSUE TITLE
安装没有报错，运行app.py时二维码下方有报错，扫码后消息能收到但是无法回复

### ISSUE THREAD

**Issue by Huang17485** [zhayujie/chatgpt-on-wechat#743]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
安装没有出现报错，运行app.py之后，有如下报错，扫码能够正常登录，别人发送的消息也能正常收到，但是没有回复；
![image](https://user-images.githubusercontent.com/97492590/229693529-5e2558cb-a433-42f8-9460-5b892622fed6.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux Ubuntu 20.04
 - Python版本  ( 执行 `python3 -V` )：Python 3.8.10                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by cross2to** [comment]
使用国内的vps记得翻墙..
