### ISSUE TITLE
成功布署,成功扫二维码,微信成功登陆,不出聊天界面,没有机器人.

### ISSUE THREAD

**Issue by Sunpulseqd** [zhayujie/chatgpt-on-wechat#747]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by handongfang** [comment]
新版代码默认跳过自己的问题，看下别人是否可以触发，目前为止哪里可以配置触发自己问题回复，应该是有地方触发的，想必作者肯定有说明就是没找到目前
