### ISSUE TITLE
google 语音生成参数设置

### ISSUE THREAD

**Issue by nagaki09** [zhayujie/chatgpt-on-wechat#749]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 使用google voice，用来生成回复的mp3
在代码中，只到使用了GoogleVoice 
结合google官方api的说明示例，好像没有找到控制语速，音色之类的参数

**Comment by zwssunny** [comment]
google语音生成部分代码调用引用第三方库gtts，非官方库，具体请看[https://github.com/zwssunny/gTTS](https://github.com/zwssunny/gTTS)
