### ISSUE TITLE
You requested a model that is not compatible with this engine.

### ISSUE THREAD

**Issue by WeiZhang-bigdata** [zhayujie/chatgpt-on-wechat#75]
INFO][2023-02-07 10:15:12][open_ai_bot.py:20] - [OPEN_AI] query=有多少种颜色
[ERROR][2023-02-07 10:15:28][open_ai_bot.py:64] - You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.
Traceback (most recent call last):
  File "E:\chatwithpy\chatgpt-on-wechat-master\bot\openai\open_ai_bot.py", line 40, in reply_text
    response = openai.Completion.create(
  File "E:\pyhton\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "E:\pyhton\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "E:\pyhton\lib\site-packages\openai\api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "E:\pyhton\lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "E:\pyhton\lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.
[INFO][2023-02-07 10:15:28][wechat_channel.py:103] - [WX] sendMsg=[bot] 请再问我一次吧, receiver=@14f901d78cbd9ee84f210b7067318978be97fb11187a24219a075ca851d5d661

报的这个错    You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.

**Comment by WeiZhang-bigdata** [comment]
这个错 我用其他转发微信的程序  也报这个错  ， 是不是我账号的问题。 我账号能在网页上和机器人chat.      我每次起程序都是开的VPN，全局代理。

**Comment by HaoGuo98** [comment]
同样报错 但是可以问图片 比如画个兔子就可以

**Comment by HaoGuo98** [comment]
用官方api（https://platform.openai.com/docs/api-reference/completions/create?lang=python）也报错
![image](https://user-images.githubusercontent.com/42510628/217220934-5d2739f6-8366-4a64-8dfd-060b45be1fd3.png)

**Comment by HaoGuo98** [comment]
换模型为text-davinci-001可以跑

**Comment by WeiZhang-bigdata** [comment]
咋换&nbsp; 兄弟&nbsp; 能附上个截图吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月7日(周二) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 启动后，无法恢复，有报错 (Issue #75)




 
换模型为text-davinci-001可以跑

**Comment by HaoGuo98** [comment]
看报错啊 File "E:\chatwithpy\chatgpt-on-wechat-master\bot\openai\open_ai_bot.py", line 40, in reply_text
response = openai.Completion.create

**Comment by WeiZhang-bigdata** [comment]
谢了 大兄弟&nbsp; ！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月7日(周二) 晚上6:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhayujie/chatgpt-on-wechat] 启动后，无法恢复，有报错 (Issue #75)




 
看报错啊 File "E:\chatwithpy\chatgpt-on-wechat-master\bot\openai\open_ai_bot.py", line 40, in reply_text
 response = openai.Completion.create

**Comment by HaoGuo98** [comment]
问题是text-davinci-003才是官网指定低配版chatgpt哇。。

**Comment by Xzqaj** [comment]
我也是同样的问题，而且改成davinci001还是一样报错提示not compatible

**Comment by wuxs231** [comment]
一样的问题

**Comment by honeyou** [comment]
我也出现相同问题了，是账号问题吗，各位大佬

**Comment by Xzqaj** [comment]
> 我也是同样的问题，而且改成davinci001还是一样报错提示not compatible

可能确实是账号的问题，我换了一个账号就能调用davinci003了

**Comment by zhayujie** [comment]
应该可以确认是账号的问题， 不过没发现 账号在注册的时候哪里会有差异
