### ISSUE TITLE
无法使用百度语音

### ISSUE THREAD

**Issue by qcoltma** [zhayujie/chatgpt-on-wechat#754]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
已按要求配置了百度语音，但是使用时发现它还是会去用google语音做text_to_voice，求大佬帮助，谢谢。

> 简要说明、截图、复现步骤等，也可以是需求或想法
![image](https://user-images.githubusercontent.com/126476212/230076059-3822edaf-f3fa-4383-8918-a89c7ba8cbb7.png)

### 终端日志 (如有报错)
[WARNING][2023-04-05 20:03:10][chat_channel.py:153] - [WX]any to wav error, use raw path. name 'any_to_wav' is not defined
[INFO][2023-04-05 20:03:10][bridge.py:28] - create bot openai for voice_to_text
[INFO][2023-04-05 20:03:11][openai_voice.py:25] - [Openai] voiceToText text=Hi. voice file name=tmp/230405-200310.mp3
[INFO][2023-04-05 20:03:11][chat_gpt_bot.py:34] - [CHATGPT] query=Hi.
[INFO][2023-04-05 20:03:13][bridge.py:28] - create bot google for text_to_voice

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
请参考该[文件](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)中的可用设置，添加相应设置。

**Comment by qcoltma** [comment]
> 请参考该[文件](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)中的可用设置，添加相应设置。

感谢。添加了 "text_to_voice": "baidu"后就可以使用baidu来文本转语言了，但是又出现了ModuleNotFoundError: No module named 'pysilk'的错误，使用pip install pysilk成功安装后，还是识别相同错误，目前还不知道怎么解决，有大神来帮个忙吗？

**Comment by qcoltma** [comment]
> > 请参考该[文件](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)中的可用设置，添加相应设置。
> 
> 感谢。添加了 "text_to_voice": "baidu"后就可以使用baidu来文本转语言了，但是又出现了ModuleNotFoundError: No module named 'pysilk'的错误，使用pip install pysilk成功安装后，还是识别相同错误，目前还不知道怎么解决，有大神来帮个忙吗？
找到了，运行这个命令后成功了感谢各位大佬，此问题已解决。
pip install silk-python
