### ISSUE TITLE
运行起来后问问题连接超时

### ISSUE THREAD

**Issue by Arturia169** [zhayujie/chatgpt-on-wechat#756]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 部署在云且服务器在境外，确定能正常联网，服务器为洛杉矶加利福尼亚地区。
![image](https://user-images.githubusercontent.com/69199123/230085500-572b4d42-6829-4b02-a250-a48e5e8d12b3.png)

![image](https://user-images.githubusercontent.com/69199123/230123105-10efc018-5920-4f1c-894f-ba8b613e19dc.png)

### 终端日志 (如有报错)

```
[INFO][2023-04-05 20:49:15][chat_gpt_bot.py:36] - [CHATGPT] query=帮我写一篇关于程序员的日记
[WARNING][2023-04-05 20:49:45][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-05 20:49:50][chat_gpt_bot.py:139] - [CHATGPT] 第1次重试
[WARNING][2023-04-05 20:50:20][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-05 20:50:25][chat_gpt_bot.py:139] - [CHATGPT] 第2次重试

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：Python 3.9.2                 
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1

**Comment by Shawn-Guo-CN** [comment]
我这里有一样的问题。

**Comment by ChangYanwei** [comment]
使用railway部署的，也经常出现这个问题Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)

可以通过升级railway会员解决超时问题吗
![image](https://user-images.githubusercontent.com/48378463/230285143-4f2bf09b-fe23-4021-8fe4-0a100307fdf3.png)

**Comment by lanvent** [comment]
@ChangYanwei 升级会员应该没有，是openai的回复慢了。

之前默认时间设置的过短，现在的默认超时时间设为60秒了，railway需要redeploy。

如果还是不能及时回复，请设置环境变量`request_timeout`和`timeout`。

**配置含义参考该[文件](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)。**

**Comment by fangtong1234** [comment]
我想问下这个错误 是要更改config.py文件来增加回答的等待时间吗 比如这个样子
 chatgpt api参数 参考https://platform.openai.com/docs/api-reference/chat/create
    "temperature": 0.9,
    "top_p": 1,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "request_timeout": 420, # chatgpt请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
    "timeout": 500,

**Comment by lanvent** [comment]
@fangtong1234 对的

**Comment by fangtong1234** [comment]
@lanvent 可是我已经修改了配置文件  实际使用时还只是 1分钟的等待时间并没有变化### 
![微信截图_20230407150413](https://user-images.githubusercontent.com/129706079/230559464-9080733a-2d0b-4a9d-b7e4-7ad5277dbb6e.png)
![微信截图_20230407150338](https://user-images.githubusercontent.com/129706079/230559481-80c696dd-ab19-4fb5-9a08-3ef87128d57d.png)

**Comment by lanvent** [comment]
不好意思，我看错了，要在`config.json`里添加配置。
