### ISSUE TITLE
azure tts 是否可以设定语音库

### ISSUE THREAD

**Issue by Gogoworks** [zhayujie/chatgpt-on-wechat#758]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

之前用百度甄选语音库，费用太高，感谢大佬们接入了azure tts，目前成功接入azure，希望可以自定义语音库。

由默认的自定义为 zh-CN-XiaoyouNeural

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
可以修改，在`voice/azure/ `下有`config.json.template`文件

**Comment by Gogoworks** [comment]
> 可以修改，在`voice/azure/ `下有`config.json.template`文件

azure-cognitiveservices-speech 依赖装不了，所以我打包了镜像。尝试修改config.json.template的参数，但是貌似没有生效。麻烦大佬帮忙看一下。

**Comment by Gogoworks** [comment]
> 可以修改，在`voice/azure/ `下有`config.json.template`文件

azure-cognitiveservices-speech 依赖装不了，所以我打包了镜像。尝试修改config.json.template的参数，但是貌似没有生效。麻烦大佬帮忙看一下。

**Comment by Gogoworks** [comment]
> 需要去掉.template

感谢回复，去掉.template后，镜像需要从新打包吗？

**Comment by lanvent** [comment]
使用的是docker吗，需要的

**Comment by Gogoworks** [comment]
> 

感谢，重新打包后生效！

**Comment by lichengzhe** [comment]
可否帮忙汇总更新为文档pr，感谢。
