### ISSUE TITLE
运行脚本./start.sh后CTRL+C 不能后台使用

### ISSUE THREAD

**Issue by xiaohei6856** [zhayujie/chatgpt-on-wechat#759]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/80569851/230255131-2df8a9ce-4a10-4572-91f3-b7f584d48741.png)

每次在我登陆成功后可以使用，但是当我CTRL+C后，就无法使用了，我再用./tout.sh查看就会发现这句话
[Config] User datas saved.
同时进程查看并没有被结束掉...

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

![image](https://user-images.githubusercontent.com/80569851/230255926-8d1ed45d-37da-43f8-9539-fbbb7c3ac1ff.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
是说后台运行，然后ctrl+c也会停止程序嘛？

试试拉下最新代码，看还有这种情况吗
