### ISSUE TITLE
tokens验证失败

### ISSUE THREAD

**Issue by qpqoqp000** [zhayujie/chatgpt-on-wechat#761]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
个人订阅号按流程至验证token失败
> 简要说明、截图、复现步骤等，也可以是需求或想法

网页发起token验证，服务器有响应但是404，是不是监听问题，我在etc目录下没有iptables文件夹

### 终端日志 (如有报错)

http://0.0.0.0:8080/
162.62.80.8:54051 - - [06/Apr/2023 15:57:58] "HTTP/1.1 GET /ws" - 404 Not Found
162.62.80.8:59077 - - [06/Apr/2023 15:58:47] "HTTP/1.1 GET /ws" - 404 Not Found

[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：linux
 - Python版本  ( 执行 `python3 -V` )：     3.9                 
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by qpqoqp000** [comment]
粗心了

**Comment by Martin-dq** [comment]
所以是什么原因？我也是这个

**Comment by wxpftd** [comment]
![image](https://user-images.githubusercontent.com/5720352/232324022-7eab0f83-659d-49b2-9dfe-8342081d0c53.png)
估计是因为要把在公众号服务配置上加上这个
