### ISSUE TITLE
安装插件指令报错

### ISSUE THREAD

**Issue by Li-Eternally** [zhayujie/chatgpt-on-wechat#762]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 卸载指令正常，使用 #installp sdwebui 指令后报错，但是plugins目录下会生成 plugin_sdwebui 文件夹和文件，这是怎么回事？

![image](https://user-images.githubusercontent.com/128838111/230472639-007f1929-486d-49e9-95ce-bebedf49aeb5.png)
![image](https://user-images.githubusercontent.com/128838111/230472676-ffd96b80-2b8c-4458-8c87-e7d34149b556.png)

### 终端日志 (如有报错)

```
[INFO][2023-04-06 18:54:00][plugin_manager.py:217] - clone git repo: sdwebui
[INFO][2023-04-06 18:54:02][plugin_manager.py:239] - detect requirements.txt，installing...
[ERROR][2023-04-06 18:54:02][plugin_manager.py:243] - Failed to install plugin, module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[INFO][2023-04-06 18:54:03][wechat_channel.py:177] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
安装插件失败，module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'), receiver=@6eafae28affa2dc49b992ac4c6ec12b78baacf2172ec6cef6411274ac3d0e397
[INFO][2023-04-06 18:54:09][plugin_manager.py:217] - clone git repo: sdwebui
[ERROR][2023-04-06 18:54:09][plugin_manager.py:243] - Failed to install plugin, [Errno 17] File exists: './plugins/plugin_sdwebui/.git'
[INFO][2023-04-06 18:54:09][wechat_channel.py:177] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
安装插件失败，[Errno 17] File exists: './plugins/plugin_sdwebui/.git'), receiver=@6eafae28affa2dc49b992ac4c6ec12b78baacf2172ec6cef6411274ac3d0e397

```

### 环境

 - 操作系统类型 ：Ubuntu Server 20.04 LTS 64
 - Python版本 ：3.8.10                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by 4331599** [comment]
1.0.6版本是集成而且能成功配置好的，最近更新之后好像把这个插件删掉了。

**Comment by 4331599** [comment]
1.0.6版本是集成而且能成功配置好的，最近更新之后好像把这个插件删掉了。

**Comment by lanvent** [comment]
前面这个报错搜索下跟你本机的环境有关。

如果还是不能安装的话，可采用手动安装方式。

**Comment by Li-Eternally** [comment]
> 前面这个报错搜索下跟你本机的环境有关。
> 
> 如果还是不能安装的话，可删除该文件夹，采用手动安装方式。

感谢解答，确实是我本机环境的问题，目前已解决
