### ISSUE TITLE
无法pip3安装requirements.txt

### ISSUE THREAD

**Issue by ByOpenAI** [zhayujie/chatgpt-on-wechat#763]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
无法执行【 pip3 install -r requirements.txt】命令，单独按照的openai 版本，是openai 0.27.4，下面是命令行及截图
[root@ecs-mI4SE chatgpt-on-wechat]# openai -V
openai 0.27.4

### 终端日志 (如有报错)
[root@ecs-mI4SE chatgpt-on-wechat]# pip3 install -r requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting openai>=0.27.2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement openai>=0.27.2 (from -r requirements.txt (line 1)) (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
No matching distribution found for openai>=0.27.2 (from -r requirements.txt (line 1))

[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]

![企业微信截图_16808352662671](https://user-images.githubusercontent.com/127028141/230530241-062430bc-20ac-4315-96af-6b503e28fb50.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Centos7.6
 - Python版本  ( 执行 `python3 -V` )：            Python 3.6.8        
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)： pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)

**Comment by 954545647** [comment]
遇到同样问题，有佬有解决方案吗

**Comment by ByOpenAI** [comment]
换成ubuntu系统

**Comment by ByOpenAI** [comment]
> 遇到同样问题，有佬有解决方案吗

换成ubuntu系统

**Comment by pqshao** [comment]
centos系统咋办呢？有人解决了吗？

**Comment by lanvent** [comment]
因为你的python版本过低了，请升级python到3.8

**Comment by pqshao** [comment]
> 因为你的python版本过低了，请升级python到3.8

谢谢大佬，之前没仔细看，确实是这样的，我的系统centos7.9，默认安装了3.6版本
