### ISSUE TITLE
Railway一键部署后如何实现个人微信公众号的接入？

### ISSUE THREAD

**Issue by hy546880109** [zhayujie/chatgpt-on-wechat#764]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

部署Railway能使用微信接入了但是有封号风险，想换成公众号请问如何接入微信公众号

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
railway的app是可以绑定域名，我也尝试过部署，但开发者后台提示token验证失败，可能是微信屏蔽了railway的服务器。

**Comment by hy546880109** [comment]
谢谢你回答，那我使用其他方法吧

**Comment by Tinotz** [comment]
也是搞了半天 对接railway 和公众号也是一直提示token验证失败。  请问你们用的是什么方式部署的呢？  有没有比较建议的步骤。 谢谢 

> 

也是搞了半天 对接railway 和公众号也是一直提示token验证失败。  请问你们用的是什么方式部署的呢？  有没有比较建议的步骤。 谢谢
