### ISSUE TITLE
微信公众号能不能对接语音

### ISSUE THREAD

**Issue by LeafBanks** [zhayujie/chatgpt-on-wechat#765]
1.非常感谢各路大神的贡献，让我体验了一把非常6的wechat-gpt！
2.现在封号那么严重，个人号不长久，能不能把语音功能接进公众号
3.尝试了tool跟bdunit，一言难尽，看图!![image](https://user-images.githubusercontent.com/122428986/230536602-ddd6c355-1ee7-4239-bc2f-034569e85530.jpeg)![image](https://user-images.githubusercontent.com/122428986/230536625-cdebf784-4edf-478d-b7e5-2999adc04004.jpeg)
4.希望插件的大神更新下，谢谢

**Comment by hy546880109** [comment]
请问你是如何配置微信公众号的token和url，为什么我一直提交token失败，还有服务器是否需要海外的？

**Comment by LeafBanks** [comment]
> 请问你是如何配置微信公众号的token和url，为什么我一直提交token失败，还有服务器是否需要海外的？
几个因素，我也是搞了一段时间才琢磨明白，
1.你说的token自己设置，你喜欢的暗号之类，微信后台与服务器的json文件一致就行
2.微信后台IP地址加/wx，举个例子：你申请的网址www.baidu.com,根据微信官网文档网址后加入/wx，即：www.baidu.com/wx
3.你可以用反代NPM(Nginx Proxy Manager),还有一个叫npm那个比较麻烦，你在网上搜索记得输入全名
4.技术大神说把app.py指向80端，借花献佛：sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080，sudo iptables-save > /etc/iptables/rules.v4，如果没有iptables文件自己mkdir一个.
5.希望能帮到你

**Comment by hy546880109** [comment]
谢谢你的回答，但是我无法保存token，关于token如何验证，我看官方文档没看懂，是要自己编辑脚本验证吗

**Comment by LeafBanks** [comment]
> 谢谢你的回答，但是我无法保存token，关于token如何验证，我看官方文档没看懂，是要自己编辑脚本验证吗
就两个选项要注意
1.url，一个重点是公网端口是不是80，另一个是你的服务器有没有其他程序占用了冲突。
2.token，公众号后台的token跟服务器文件json里面一致就行。
3.它的逻辑是这样，你在公众号填入url跟token，按保存之后，公众号发送验证信息去你的服务器，然后回调回来，如果这条指令发出去服务器收不到或者收到了不回调，那么就保存不了。
4.希望我的回答可以帮到你

**Comment by hy546880109** [comment]
意思是我要在服务器上先运行app.py程序，然后去微信公众号进行填写url和token保存吗？我的服务器在国内也可以吗？

**Comment by LeafBanks** [comment]
> 意思是我要在服务器上先运行app.py程序，然后去微信公众号进行填写url和token保存吗？我的服务器在国内也可以吗？

是的，没错！穿透内网你最好是看看大神的攻略，文件里readme你翻翻

**Comment by jerichobf** [comment]
大佬  能有偿帮我在windows上安装python实现吗？实在不会用 看的头大！~

**Comment by JS00000** [comment]
目前已经支持语音输入了。
