### ISSUE TITLE
希望可以支持微信客服的接口

### ISSUE THREAD

**Issue by binbin407** [zhayujie/chatgpt-on-wechat#767]
希望可以支持微信客服的接口：https://developer.work.weixin.qq.com/document/path/94638

**Comment by LeafBanks** [comment]
+1

**Comment by 8955107** [comment]
+1

**Comment by lichengzhe** [comment]
企业微信，众望所归，这里有个早期fork出去的，可以尝试合并回来。
https://github.com/mostlittlebee/chatgpt-on-wecom

**Comment by 6vision** [comment]
> 尝试
感觉第二个基于企业微信客服用的更方便，现在咱项目的企业微信是创建企业应用

**Comment by 6vision** [comment]
> 企业微信，众望所归，这里有个早期fork出去的，可以尝试合并回来。 https://github.com/mostlittlebee/chatgpt-on-wecom https://github.com/razertory/gpt-wework


感觉第二个基于企业微信客服用的更方便，现在咱项目的企业微信是创建企业应用

**Comment by JS00000** [comment]
目前已经支持了。

**Comment by JS00000** [comment]
> 目前已经支持了。

不好意思我看错了，现在支持的是微信公众号的客服接口，还不支持微信客服的接口，这俩搞混了。
