### ISSUE TITLE
ERROR: 我没有收到你的消息

### ISSUE THREAD

**Issue by qcoltma** [zhayujie/chatgpt-on-wechat#769]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

自从更新了3.25日的版本后，提问题时，经常会回复“ERROR:
我没有收到你的消息”的错误，开始以为是网络问题，但是此时我只要重新启一下app.py就会好用了，但是过段时间又出现该错误了。不知道是不是程序bug问题，求助大佬们。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
查看日志，尝试在`config.json`增加或调整以下配置，可以调大一点。(去掉注释)
```json
  "concurrency_in_session": 1, # 同一会话最多有多少条消息在处理中，大于1可能乱序
  "request_timeout": 60, # chatgpt请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
  "timeout": 120,         # chatgpt重试超时时间，在这个时间内，将会自动重试
```

**Comment by wangxin2023** [comment]
执行 pip3 install -r requirements-optional.txt
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.

**Comment by qcoltma** [comment]
> 查看日志，尝试在`config.json`增加或调整以下配置，可以调大一点(去掉注释)。 配置前请拉取最新的代码。
> 
> ```json
>   "concurrency_in_session": 1, # 同一会话最多有多少条消息在处理中，大于1可能乱序
>   "request_timeout": 60, # chatgpt请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
>   "timeout": 120,         # chatgpt重试超时时间，在这个时间内，将会自动重试
> ```

谢谢，我试试看。

**Comment by qcoltma** [comment]
> > 查看日志，尝试在`config.json`增加或调整以下配置，可以调大一点(去掉注释)。 配置前请拉取最新的代码。
> > ```json
> >   "concurrency_in_session": 1, # 同一会话最多有多少条消息在处理中，大于1可能乱序
> >   "request_timeout": 60, # chatgpt请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
> >   "timeout": 120,         # chatgpt重试超时时间，在这个时间内，将会自动重试
> > ```
> 
> 谢谢，我试试看。

改了参数现在好多了，谢谢。

**Comment by cshuo** [comment]
@lanvent docker 这边如何更新配置呢？

**Comment by lanvent** [comment]
> @lanvent docker 这边如何更新配置呢？

docker可以传递环境变量，或者映射config.json进去

**Comment by cshuo** [comment]
@lanvent 请教下, 目前的 docker 镜像支持配置下面的三个参数了吗？或者是需要自己基于最新代码重新 build 景象呢

> 查看日志，尝试在`config.json`增加或调整以下配置，可以调大一点(去掉注释)。 配置前请拉取最新的代码。
> 
> ```json
>   "concurrency_in_session": 1, # 同一会话最多有多少条消息在处理中，大于1可能乱序
>   "request_timeout": 60, # chatgpt请求超时时间，openai接口默认设置为600，对于难问题一般需要较长时间
>   "timeout": 120,         # chatgpt重试超时时间，在这个时间内，将会自动重试
> ```

**Comment by lanvent** [comment]
都支持从环境变量读取

**Comment by lsCoding666** [comment]
现在还是会timeout吗？我设置了80秒还是超时。是openai的问题吗
