### ISSUE TITLE
启动了，但是报错access was terminated due to violation of our policies

### ISSUE THREAD

**Issue by CherryQii** [zhayujie/chatgpt-on-wechat#77]
这是我第一次启动啊，是现在用不了了嘛？还是什么原因？

[INFO][2023-02-07 19:07:16][open_ai_bot.py:20] - [OPEN_AI] query=今天天气怎么样
[WARNING][2023-02-07 19:07:17][open_ai_bot.py:55] - Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
[WARNING][2023-02-07 19:07:22][open_ai_bot.py:58] - [OPEN_AI] RateLimit exceed, 第1次重试
[WARNING][2023-02-07 19:07:22][open_ai_bot.py:55] - Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
[INFO][2023-02-07 19:07:22][wechat_channel.py:103] - [WX] sendMsg=@虹名 提问太快啦，请休息一下再问我吧, receiver=@@438fa95f0fd8866bbf4448ccb52e131a6c06623c2d2f4fc241f30cb162d001d1

**Comment by zhayujie** [comment]
看报错是被 openai 后台把账号封了，  你账号是自己邮箱注册的吗？

**Comment by CherryQii** [comment]
> 看报错是被 openai 后台把账号封了， 你账号是自己邮箱注册的吗？

感谢如此迅速的回复！是下午在tb买的账号，那边说是独立专人账号(8.8元)。

**Comment by fj9876** [comment]
> > 看报错是被 openai 后台把账号封了， 你账号是自己邮箱注册的吗？
> 
> 感谢如此迅速的回复！是下午在tb买的账号，那边说是独立专人账号(8.8元)。

申请退款去吧，自己注册也就话费1人民币差不多，注册又不复杂

**Comment by CherryQii** [comment]
> 

自己注册的账号马上成功了！感谢！

**Comment by Li-Z-Q** [comment]
> > 
> 
> 自己注册的账号马上成功了！感谢！

请问怎么注册的呀，国内手机号不允许使用呀

**Comment by kdyzm** [comment]
我也是自己注册的，但是还是被封禁了
