### ISSUE TITLE
更新1.2.1.3后出现超时的问题

### ISSUE THREAD

**Issue by mctds** [zhayujie/chatgpt-on-wechat#775]
前置确认
网络能够访问openai接口
python 已安装：版本在 3.7 ~ 3.10 之间
git pull 已拉取最新代码
已执行pip3 install -r requirements.txt
已执行pip3 install -r requirements-optional.txt

问题描述
偶发性且频发
[WARNING][2023-04-08 10:17:15][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12).
 
操作系统类型 (Linux)：
Python版本 (3.10)：

**Comment by lanvent** [comment]
看看#769， 你的timeout时间设置太低了，昨天开始openai的接口就一直是缓慢状态

**Comment by cshuo** [comment]
@lanvent docker 这边如何更新 timeout 配置呢？

**Comment by mctds** [comment]
> 看看#769， 你的timeout时间设置太低了，昨天开始openai的接口就一直是缓慢状态

确认是chatgpt_tool_hub插件配置问题，会在下个版本中修复

**Comment by goldfishh** [comment]
> @lanvent docker 这边如何更新 timeout 配置呢？

pip install -i https://pypi.python.org/simple chatgpt_tool_hub==0.3.7

**Comment by hy546880109** [comment]
更新后确实慢了

**Comment by lonny1987** [comment]
昨天更新 了新版本，确实 老是超时，又切回了老版本正常运行

**Comment by cshuo** [comment]
@lonny1987 hi, 您用的是哪个版本比较稳定快速

**Comment by lanvent** [comment]
最新版本[1.2.2.2](https://github.com/zhayujie/chatgpt-on-wechat/releases/tag/1.2.2.2)已取消设置`request_timeout`的默认值(60s)，`openai`会使用默认值600秒来完成请求。

有耐心可自行根据网络环境进行参数的调优，可选配置项可在[文件](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)中找到。

**Comment by jokerlinnn** [comment]
> 

兄弟  你用的哪个版本

**Comment by jokerlinnn** [comment]
> 昨天更新 了新版本，确实 老是超时，又切回了老版本正常运行

兄弟 你用的哪个版本
