### ISSUE TITLE
天气插件无法触发

### ISSUE THREAD

**Issue by charleschen2006** [zhayujie/chatgpt-on-wechat#779]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
你问 今天深圳天气如何？ 还是瞎回答。
你问 4月9号深圳天气情况？ 还是一样瞎回答。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：linux
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zwssunny** [comment]
参考  #682

**Comment by 6vision** [comment]
> 参考 #682

我这边也是参考682配置好了，触发了bdunit，但百度控制台那边显示全都调用失败：请求参数错误

**Comment by zwssunny** [comment]
> (已解决，service_id里面多了个空格> 参考 #682
> 
> 我这边也是参考682配置好了，触发了bdunit，但百度控制台那边显示全都调用失败：请求参数错误

把配置参数确认一下，有日志吗？
