### ISSUE TITLE
banwords

### ISSUE THREAD

**Issue by nbdxrycyl** [zhayujie/chatgpt-on-wechat#780]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.8之间

### 问题描述

> banwords插件无法屏蔽特殊词
配置了json文件，也在banwords.txt放入了词，但是在微信中提及还是会触发GPT回复，没头脑。

**Comment by Li-Eternally** [comment]
banwords插件没问题，你尝试拉取最新代码，或者重新配置一下

**Comment by nbdxrycyl** [comment]
谢谢回复
