### ISSUE TITLE
插件开发问题

### ISSUE THREAD

**Issue by qcoltma** [zhayujie/chatgpt-on-wechat#783]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
想在on_handle_context(self, e_context: EventContext)事件中处理语音，看到之前所有的插件例子中没有处理语音的案例，因此也没有参考的地方，在处理语音，想下载语音时出现了AttributeError: 'WeChatMessage' object has no attribute 'download'的错误，也就是说msg实例中不存在dowonload方法，这就郁闷了，之前看插件说中有说msg是一个itchat对象呀，请大佬帮忙分析，谢谢。
简短代码如下： def on_handle_context(self, e_context: EventContext):

                               if e_context['context'].type != ContextType.VOICE: #插件用来处理语言发送的技能包，如果发送的不是语音就退出事件不再处理。
                                  return
                                 #处理voice消息，转换成text
                                 logger.info("handling voice...")
                                 msg = e_context['context']['msg']
                                 file_name = TmpDir().path() + e_context['context'].content
                                 logger.info(file_name)
                                 msg.download(file_name)（到这一步就出错了！！）
                                 reply = super().build_voice_to_text(file_name)
> 简要说明、截图、复现步骤等，也可以是需求或想法

[INFO][2023-04-09 08:57:44][skills.py:45] - handling voice...
[INFO][2023-04-09 08:57:44][skills.py:50] - tmp/tmp/230409-085744.mp3
[ERROR][2023-04-09 08:57:44][chat_channel.py:235] - Worker return exception: 'WeChatMessage' object has no attribute 'download'
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/qcolt/chatgpt-on-wechat/channel/chat_channel.py", line 128, in _handle
    reply = self._generate_reply(context)
  File "/home/qcolt/chatgpt-on-wechat/channel/chat_channel.py", line 138, in _generate_reply
    e_context = PluginManager().emit_event(EventContext(Event.ON_HANDLE_CONTEXT, {
  File "/home/qcolt/chatgpt-on-wechat/plugins/plugin_manager.py", line 159, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/home/qcolt/chatgpt-on-wechat/plugins/skills/skills.py", line 51, in on_handle_context
    msg.download(file_name)
AttributeError: 'WeChatMessage' object has no attribute 'download'

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
语音和图片需要调用cmsg.prepare()，你可以看下默认的处理逻辑

**Comment by qcoltma** [comment]
> 语音和图片需要调用cmsg.prepare()，你可以看下默认的处理逻辑

好的，谢谢。

**Comment by lanvent** [comment]
插件文档中的片段还是v1.1.0的老片段，最新逻辑可以参考[chat_channel.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/chat_channel.py) 中的`_handle`函数。声音的处理可以参考`_generate_reply`中处理声音的逻辑。

PS: 如果还需要接管文本转语音的话，这里提供一个接管文本转语音的插件示例，https://github.com/zhayujie/chatgpt-on-wechat/pull/750#issuecomment-1496482789

**Comment by qcoltma** [comment]
> 插件文档中的片段还是v1.1.0的老片段，最新逻辑可以参考[chat_channel.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/chat_channel.py) 中的`_handle`函数。声音的处理可以参考`_generate_reply`中处理声音的逻辑。
> 
感谢大佬指点，参考_generate_reply代码后发现还存在一个问题，那就是super().build_voice_to_text(wav_path)方法中的Channel类，在事件处理函数中是没有继承这个类的，该函数调用不了，有点小复杂了。。

**Comment by lanvent** [comment]
事件的上下文有带channel实例，`e_context['channel']`

**Comment by qcoltma** [comment]
> 事件的上下文有带channel实例，`e_context['channel']`
大佬牛，感谢。
看来还是我对插件开发的文档没有研究透，这就简单了。
