### ISSUE TITLE
登陆成功对话报错

### ISSUE THREAD

**Issue by nicole711** [zhayujie/chatgpt-on-wechat#785]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
问问题后报重试连接，
<img width="565" alt="image" src="https://user-images.githubusercontent.com/54565580/230752833-2bedc8b2-f4f8-4b74-9283-a17c7adf020e.png">
已经修改过cofig.py的request_time_out参数从60到120，没有解决问题。

环境：macOS，本机开发环境部署
网络：科学上网支持
账号：可以从openAI网页上正常使用chatGPT
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/54565580/230752953-bbff8936-d246-42ba-8e1d-24a296a3c899.png">

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```
<img width="567" alt="image" src="https://user-images.githubusercontent.com/54565580/230753039-a00cd39e-b38e-4847-8e1e-81fee81b38cc.png">

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Mac
 - Python版本  ( 执行 `python3 -V` )：  3.8.8            
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.0.1

**Comment by zhayujie** [comment]
这个问题是openai免费额度用完了，或者注册的时候就没送免费额度，在这里查看：
https://platform.openai.com/account/usage
