### ISSUE TITLE
持续Timout

### ISSUE THREAD

**Issue by byYufeng** [zhayujie/chatgpt-on-wechat#786]
4.5日 clone下来的版本，部署成功后对话功能均正常可用。
但运行十分钟后开始频繁Timeout，直至完全不可用。持续30s无响应，但单独测试openai api均可在几秒内正常回复

[WARNING][2023-04-09 02:36:25][chat_gpt_bot.py:119] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-09 02:36:30][chat_gpt_bot.py:133] - [CHATGPT] 第1次重试
[WARNING][2023-04-09 02:37:00][chat_gpt_bot.py:119] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-09 02:37:05][chat_gpt_bot.py:133] - [CHATGPT] 第2次重试
[WARNING][2023-04-09 02:37:35][chat_gpt_bot.py:119] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[INFO][2023-04-09 02:37:37][wechat_channel.py:176] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
我没有收到你的消息), receiver=@a4cf2bb53541ce323a5b12dbddcfdfdd6e57a655284d8a29267d258ed287abb6
[INFO][2023-04-09 02:37:37][wechat_channel.py:176] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
我没有收到你的消息), receiver=@a4cf2bb53541ce323a5b12dbddcfdfdd6e57a655284d8a29267d258ed287abb6

更新至最新版本后问题依旧

**Comment by lanvent** [comment]
单独测试的是网页版吗，它跟api走的是两个服务。api如果使用的是免费额度，也会影响openai的回复速度。这几天openai的接口确实很缓慢。

可参考#769，提高`request_timeout`。

**Comment by lichengzhe** [comment]
充值plus即可恢复正常速度，多人亲测有效，充值更强大。

**Comment by JS00000** [comment]
怀疑是openai检测到了你的调用可能有问题，所以把你的优先级降低了。确实充钱可以加。
