### ISSUE TITLE
部署微信机器人的时候，请问如何设置回复字数上限？

### ISSUE THREAD

**Issue by hecarli555** [zhayujie/chatgpt-on-wechat#788]
部署微信机器人的时候，请问如何设置回复字数上限？有时候想写个3000字作文都提示写不了

**Comment by zhayujie** [comment]
目前回复字数默认使用的是最大上线，gpt-3.5要求， 问题+回复要在 4096 tokens 之内，所以现在的回复字数是 4096 减去问题的长度。
3000汉字可能超出4096token的范围了
