### ISSUE TITLE
sdwebui部署问题

### ISSUE THREAD

**Issue by akushonkamen** [zhayujie/chatgpt-on-wechat#790]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

想请问大佬用https部署sd-webui的时候出现这个错误，请问可以怎么解决呢？

### 终端日志 (如有报错)

```
[ERROR][2023-04-09 10:35:25][sdwebui.py:100] - [SD] exception: HTTPSConnectionPool(host='61.139.65.134', port=45329): Max retries exceeded with url: /sdapi/v1/options (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
﻿
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
这个应该是ssl证书的问题，建议google一下
