### ISSUE TITLE
docker部署出错

### ISSUE THREAD

**Issue by water-root** [zhayujie/chatgpt-on-wechat#791]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> docker部署出错

### 终端日志 (如有报错)

![屏幕截图 2023-04-09 205106](https://user-images.githubusercontent.com/124557984/230773864-3f361a45-3557-47f4-a4d2-f07d2593281e.png)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-47-generic x86_64)
 - Python版本  ( 执行 `python3 -V` )： Python 3.8.10                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.0.2

**Comment by zhayujie** [comment]
你是怎么运行的， 有拉取镜像吗

**Comment by songdone** [comment]
大佬能再出个群晖docker版的部署教程吗？那个分支镜像一直搭建不成功呢。

> 你是怎么运行的， 有拉取镜像吗
