### ISSUE TITLE
设置私有API，修改open_ai_api_base 和open_ai_api_key 两个参数后不生效

### ISSUE THREAD

**Issue by wangchan123** [zhayujie/chatgpt-on-wechat#796]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

设置私有API，修改open_ai_api_base 和open_ai_api_key 两个参数后不生效，请问还需要设置哪里呢，还是不支持重新设置API？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```
Start auto replying.
[INFO][2023-04-10 16:17:18][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-04-10 16:17:18][chat_gpt_bot.py:36] - [CHATGPT] query=你好
[WARNING][2023-04-10 16:20:18][chat_gpt_bot.py:126] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1020ba370>, 'Connection to api.openai.com timed out. (connect timeout=60)'))
[WARNING][2023-04-10 16:20:23][chat_gpt_bot.py:140] - [CHATGPT] 第1次重试
[WARNING][2023-04-10 16:20:24][chat_gpt_bot.py:135] - [CHATGPT] Exception: Incorrect API key provided: xizJDlG6****EoBU. You can find your API key at https://platform.openai.com/account/api-keys.

### 环境

 - 操作系统类型  Mac：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
正常只需要在config.json 配置上 open_ai_api_base 就可以指向这个地址了

**Comment by wangchan123** [comment]
应该是需要其他字段和open_ai_api_base拼成完成的API，就是不知道在哪里

**Comment by JS00000** [comment]
看起来是你的key不对？没错的话应该是“sk-”开头。

**Comment by zhayujie** [comment]
> 看起来是你的key不对？没错的话应该是“sk-”开头。

是这样的 @wangchan123

**Comment by wangchan123** [comment]
因为使用的是加密后的key，格式不是sk-开头的。
只能设置sk-开头的key吗？
