### ISSUE TITLE
项目代码有暴露的监控端点吗？想把服务加到我的监控页里

### ISSUE THREAD

**Issue by BertramRay** [zhayujie/chatgpt-on-wechat#797]
如上所示，如果有一个接口能确定服务是否正常运行就好了

**Comment by zhayujie** [comment]
这个暂时没有诶， 现在只有公众号模式有监听端口

**Comment by BertramRay** [comment]
> 这个暂时没有诶， 现在只有公众号模式有监听端口

暂时没有的意思是以后会考虑加一个吗？

**Comment by goldfishh** [comment]
你可以考虑监控一下进程呀

**Comment by BertramRay** [comment]
> 你可以考虑监控一下进程呀

是个选项，不过相比通过http响应状态码监控还是会麻烦一些的
![image](https://user-images.githubusercontent.com/42647595/231046802-01d3c6e4-870b-475f-b371-cfc89046e914.png)
