### ISSUE TITLE
根据关键字自动回复功能

### ISSUE THREAD

**Issue by theLastWinner** [zhayujie/chatgpt-on-wechat#798]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

想实现类似微信公众号那种，根据关键字自动回复的功能。目前是否支持？想直接通过配置文件的方式实现这个，而不需要编码？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
你是说关键字不走 chatgpt，回复一个固定的内容嘛

**Comment by theLastWinner** [comment]
> 你是说关键字不走 chatgpt，回复一个固定的内容嘛

是的。 @zhayujie

**Comment by 6vision** [comment]
> > 你是说关键字不走 chatgpt，回复一个固定的内容嘛
> 
> 是的。 @zhayujie

可以，bot-on-anthing那个我已经实现了，这个正在看他写的代码。创建一个字典，存储关键词和回复内容。这只是实现了文本内容的回复

**Comment by theLastWinner** [comment]
> > > 你是说关键字不走 chatgpt，回复一个固定的内容嘛
> > 
> > 
> > 是的。 @zhayujie
> 
> 可以，我记录在这里了，可以参考修改一下源码！https://www.wangpc.cc/python/chatgpt-wechat_mp/

@6vision 好的，谢谢。
