### ISSUE TITLE
小白，希望有更详细的tool配置和使用说明。

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#799]
小白，希望有更详细的tool配置和使用说明。

**Comment by Maddaxman** [comment]
现在tool的介绍页面对小白不是太友好。希望有一个页面汇总一下现在tool的使用，和配置方法。

**Comment by goldfishh** [comment]
你有哪些不明白的或者文档哪里没有描述清楚的，你可以说说看呀。
PS：回头我整理一下

**Comment by Maddaxman** [comment]
> 你有哪些不明白的或者文档哪里没有描述清楚的，你可以说说看呀。 PS：回头我整理一下
比如：
1、tool hub和其他GUI能结合吗，该如何配置使用，如果不能，那tool hub能独立在终端使用？该如何配置使用。
2、tool hub和chatgpt-on-wechat结合时，如何配置使用，在chatgpt-on-wechat项目的哪个文件夹和文件里配置，如何增加和配置插件，以及插件的使用方法

**Comment by Li-dacheng** [comment]
想问下用railway部署的话如何设置相关tool的配置，比如想使用meteo-weather询问天气时，发送$tool 现在时间是2023.4.11 北京天气怎么样 回答会失败：Action Input: requests_get, https://api.openweathermap.org/data/2.5/weather?q=Beijing&appid=your_api_key&lang=zh_cn&units=metric

**Comment by goldfishh** [comment]
> 想问下用railway部署的话如何设置相关tool的配置，比如想使用meteo-weather询问天气时，发送$tool 现在时间是2023.4.11 北京天气怎么样 回答会失败：Action Input: requests_get, https://api.openweathermap.org/data/2.5/weather?q=Beijing&appid=your_api_key&lang=zh_cn&units=metric

meteo是默认工具，使用哪个工具是chatgpt判断的，因此你需要在问题中指定具体工具名

**Comment by goldfishh** [comment]
> > 你有哪些不明白的或者文档哪里没有描述清楚的，你可以说说看呀。 PS：回头我整理一下
> > 比如：
> > 1、tool hub和其他GUI能结合吗，该如何配置使用，如果不能，那tool hub能独立在终端使用？该如何配置使用。
> > 2、tool hub和chatgpt-on-wechat结合时，如何配置使用，在chatgpt-on-wechat项目的哪个文件夹和文件里配置，如何增加和配置插件，以及插件的使用方法（表示想要再详细一点）
> > 3、比如想用news、bing-search插件，在包里应该如何配置（表示想要再详细一点）
> > @goldfishh

你好，最近我整理了一下tool-hub的readme，那里有一个独立在终端使用的demo，你可以去试一试
目前还没有和GUI结合的计划（有人pr就万分感谢），之后应该会一直维护终端交互的方式

2. 在chaatgpt-on-wechat结合使用，你需要安装可选依赖：
```bash
pip install -r requirements-optional.txt
```
如果你不使用需要额外服务api-key的工具，那么你不需要配置，配置文件路径在plugin/tool/config.json
增加tool只需要在config.json的tool列表填入对应tool名，如果这个tool需要api-key, 那么在kwargs填入对应的key
验证tool插件成功加载方法是 回复：@或前缀 $tool，正常bot会返回你tool插件的描述
如果没有安装好请检查日志

3. 
https://github.com/goldfishh/chatgpt-tool-hub/blob/master/docs/apply_optional_tool.md

配置好了 $tool reset 可以热加载配置
