### ISSUE TITLE
扫完码之后闪退

### ISSUE THREAD

**Issue by chengqiangjun** [zhayujie/chatgpt-on-wechat#80]
前几次试了还可以，突然就不行了，扫码就闪退

**Comment by zhayujie** [comment]
程序闪退还是手机，什么环境

**Comment by chengqiangjun** [comment]
程序闪退，就是扫完码 py就自动关闭了 后台也没有看到程序

**Comment by chengqiangjun** [comment]
环境应该配置好了，因为前几次都出现了start auto replying

**Comment by chengqiangjun** [comment]
是不是因为我install了itchat-desktop

**Comment by zhayujie** [comment]
> 是不是因为我install了itchat-desktop

用 itchat-uos
