### ISSUE TITLE
可以接入每日新闻的接口吗

### ISSUE THREAD

**Issue by zpc126** [zhayujie/chatgpt-on-wechat#800]
www.alapi.cn

![image](https://user-images.githubusercontent.com/57617236/230897777-1c61bab1-c431-4678-9391-c353809bea5d.png)

![](https://file.alapi.cn/60s/202304101681063203.png)

### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zpc126** [comment]
直接发送图片

**Comment by zhayujie** [comment]
不错的想法，欢迎做成插件
https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins

**Comment by goldfishh** [comment]
这个想法我来接吧

**Comment by goldfishh** [comment]
已实现：https://github.com/zhayujie/chatgpt-on-wechat/issues/776#issuecomment-1500771334

**Comment by zpc126** [comment]
插件已跟新，配置了，插件启动不了
