### ISSUE TITLE
大佬们咱就是说能不能把文字转语音的接口转到本地的vits，这样可以不用听百度或者谷歌太机械的发音

### ISSUE THREAD

**Issue by Xuj69** [zhayujie/chatgpt-on-wechat#802]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Xuj69** [comment]
大佬如果我只要调用本地的vits可以嘛

**Comment by Xuj69** [comment]
大佬还有就是长文本你们是怎么解决合成失败的问题的，租别人的服务器嘛

**Comment by lanvent** [comment]
> 大佬如果我只要调用本地的vits可以嘛

你只要在插件里把生成音频文件的逻辑写清楚就好了

**Comment by Xuj69** [comment]
大佬您用的vits是那个是so-vits-svc-4.0还是什么别的，我一直引用不好，可不可以借鉴一下您的

**Comment by lanvent** [comment]
我使用的是https://github.com/fumiama/MoeGoe的代码，在它的基础上我改了一些

**Comment by Xuj69** [comment]
大佬可以帮我部署一下吗，有偿

**Comment by lanvent** [comment]
最近太忙，以后可能会出相关教程
