### ISSUE TITLE
使用$tool bing命令无效

### ISSUE THREAD

**Issue by Klaudiadee** [zhayujie/chatgpt-on-wechat#807]
为什么使用$tool bing 搜索总是调用到requests_get而不是bing-search  反复尝试还是这样  求解决！

**Comment by Maddaxman** [comment]
> 为什么使用$tool bing 搜索总是调用到requests_get而不是bing-search 反复尝试还是这样 求解决！

@Klaudiadee 大佬你用过没的visa卡注册的bing api key吗？
