### ISSUE TITLE
[功能]能否支持保持微信登录信息,避免每次重启后都需要扫描登录

### ISSUE THREAD

**Issue by 1178615156** [zhayujie/chatgpt-on-wechat#809]
- 部署方式: `docker`用的`build.latest.sh`
- 不确定别的方式是否也会有这个问题.

**Comment by 1178615156** [comment]
翻了下代码,是不是在`config.json`里配置`"hot_reload": true`,就会保存微信登录信息.
```python
class WechatChannel(ChatChannel):
    NOT_SUPPORT_REPLYTYPE = []
    def __init__(self):
        super().__init__()
        self.receivedMsgs = ExpiredDict(60*60*24) 

    def startup(self):

        itchat.instance.receivingRetryCount = 600  # 修改断线超时时间
        # login by scan QRCode
        hotReload = conf().get('hot_reload', False)
        try:
            itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
        except Exception as e:
            if hotReload:
                logger.error("Hot reload failed, try to login without hot reload")
                itchat.logout()
                os.remove("itchat.pkl")
                itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
            else:
                raise e
        self.user_id = itchat.instance.storageClass.userName
        self.name = itchat.instance.storageClass.nickName
        logger.info("Wechat login success, user_id: {}, nickname: {}".format(self.user_id, self.name))
        # start message listener
        itchat.run()
```

**Comment by zhayujie** [comment]
没错的，加上 hot_reload  配置就可以了

**Comment by mmm1h** [comment]
> 翻了下代码,是不是在`config.json`里配置`"hot_reload": true`,就会保存微信登录信息.
> 
> ```python
> class WechatChannel(ChatChannel):
>     NOT_SUPPORT_REPLYTYPE = []
>     def __init__(self):
>         super().__init__()
>         self.receivedMsgs = ExpiredDict(60*60*24) 
> 
>     def startup(self):
> 
>         itchat.instance.receivingRetryCount = 600  # 修改断线超时时间
>         # login by scan QRCode
>         hotReload = conf().get('hot_reload', False)
>         try:
>             itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
>         except Exception as e:
>             if hotReload:
>                 logger.error("Hot reload failed, try to login without hot reload")
>                 itchat.logout()
>                 os.remove("itchat.pkl")
>                 itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
>             else:
>                 raise e
>         self.user_id = itchat.instance.storageClass.userName
>         self.name = itchat.instance.storageClass.nickName
>         logger.info("Wechat login success, user_id: {}, nickname: {}".format(self.user_id, self.name))
>         # start message listener
>         itchat.run()
> ```

请问docker部署流程麻烦讲下吗。。。 我构建好久了总是失败，至今没有头绪
