### ISSUE TITLE
只有私聊有用，群聊没有收到任何消息，当然也没有回复

### ISSUE THREAD

**Issue by wegi8** [zhayujie/chatgpt-on-wechat#81]

**Comment by puguomai** [comment]
> _No description provided._
你的群聊名称跟配置地一样吗，有使用@bot关键词吗，我测试过来都可以。持续运行了6小时了

**Comment by wegi8** [comment]
我没有配置群名称，因为它标明自动回复嘛……

**Comment by wegi8** [comment]
> > _No description provided._
> 
> 你的群聊名称跟配置地一样吗，有使用@bot关键词吗，我测试过来都可以。持续运行了6小时了
> 
> 

可能明天配置下群名称试试，谢谢啦

**Comment by wegi8** [comment]
解决啦
