### ISSUE TITLE
bdunit插件可以对话么

### ISSUE THREAD

**Issue by congxuma** [zhayujie/chatgpt-on-wechat#815]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

官网上测试的时候是可以连续补充信息对话的，但是在微信上追加的信息不能够加到上一个sessnion中，没有走bdunit走的默认OPENAI
是否可以增加个关键字比如bdunit配置，命中这个关键字继续之前的对话？

比如检测到bdunit开头的对话全程使用bdunit来接管

![image](https://user-images.githubusercontent.com/12965750/231366803-40228f7c-bb8e-496b-8a05-bee30bb048dc.png)
![image](https://user-images.githubusercontent.com/12965750/231367150-68d53f5c-8e2e-45e0-ab8c-654d929a0081.png)

**Comment by Li-Eternally** [comment]
BDunit不支持上下文，你需要一次性讲问题说清楚

**Comment by dqzboy** [comment]
不知道为啥 我测试 私聊和群聊 问比如天气或者时间，一会是chatGPT回答，一会又可以给出信息，但是看百度面板数据没有任何请求；技能已经添加了时间跟天气

**Comment by congxuma** [comment]
> 不知道为啥 我测试 私聊和群聊 问比如天气或者时间，一会是chatGPT回答，一会又可以给出信息，但是看百度面板数据没有任何请求；技能已经添加了时间跟天气

百度是通过意图识别的，他自己训练的一套意图逻辑，意图命中查天气的意图就走的天气的技能，是不是有的表达百度没识别到天气的意图？可以在百度unit上面用相同的话术测试一下返回什么意图，可以标记识别不准的数据
