### ISSUE TITLE
私聊都没反应，有配置关键字

### ISSUE THREAD

**Issue by alianrock** [zhayujie/chatgpt-on-wechat#82]
私聊都没反应，有配置关键字，用自己的微信扫码。需要用什么样的步骤呢？

**Comment by zhayujie** [comment]
日志有输出吗

网络没开代理吧？    发送的消息有命中关键字吗

**Comment by alianrock** [comment]
> 日志有输出吗
> 
> 网络没开代理吧？ 发送的消息有命中关键字吗

感谢作者，代理的问题~，感谢开源
