### ISSUE TITLE
求一微信群聊天内容总结插件

### ISSUE THREAD

**Issue by nbdxrycyl** [zhayujie/chatgpt-on-wechat#821]
朋友的一群内有个GPT机器人，能总结所有 在上一次输入命令后的微信群聊天记录的内容。
然后我是代码小白嘛，找了大概两星期也没能在网上找个实现这个功能的插件。想来发个Issue看看有没有大佬可以写一个。
------------------------------------
我是对这个功能比较有需求，因为微信群的聊天记录太多了，个个999+，如果有这个插件的话，调整收集需要的内容，就可以不看聊天记录，大大节省时间 - -！
如果有大佬愿意写的话，赞赏个洗脚钱( $ _ $ )，如果有同样需求的同学，在下面一起赞赏好吗~

**Comment by hccccli** [comment]
可以可以

**Comment by Maddaxman** [comment]
这个功能可以

**Comment by forczc** [comment]
挺好的，就是感觉有点废钱

**Comment by lanvent** [comment]
之前想过但鸽掉了，最近我开发一下，请我喝一杯咖啡吧。 有一个问题是，如果聊天记录过长，超过4096tokens的限制，你朋友群里的bot是分段后进行总结的吗？有聊天记录截图看看就更好了。

<img width="200" alt="image" src="https://user-images.githubusercontent.com/26515464/231639321-b9646598-d1b1-4bb5-af13-df4c82b65b99.jpg">

**Comment by nbdxrycyl** [comment]
已赞助，快来更多小伙伴~

**Comment by nbdxrycyl** [comment]
@lanvent，哥你加我vx，我发截图给你：langjizhuzhu

**Comment by lanvent** [comment]
#852

**Comment by gop167** [comment]
> 之前想过但鸽掉了，最近我开发一下，请我喝一杯咖啡吧。 有一个问题是，如果聊天记录过长，超过4096tokens的限制，你朋友群里的bot是分段后进行总结的吗？有聊天记录截图看看就更好了。
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/26515464/231639321-b9646598-d1b1-4bb5-af13-df4c82b65b99.jpg">

你还在做吗，我也想开发这个

**Comment by Fatemin** [comment]
同蹲更新 现在GPT4的token数量上限增加了

**Comment by Frank-Li-91** [comment]
同蹲更新,,,为啥issue关闭了呀
