### ISSUE TITLE
按配置设置为："model": "gpt-3.5-turbo"，但实际上调用的是GPT-2，这个怎么处理，2的智商有点低

### ISSUE THREAD

**Issue by zc3646766** [zhayujie/chatgpt-on-wechat#822]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
微信登陆机器人回复都没问题，但是GPT版本为2.0，请大佬帮忙研究下怎么调用3.5-turbo版本。
另外，能否给GPT一个时间同步功能，需要GPT记录一些东西时没有时间标签，不方便整理。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
他自己受训练数据限制，不知道自己的版本，填入 gpt-3.5-turbo 的话使用的就是官方的3.5版本

**Comment by zc3646766** [comment]
我问他是GPT3么？他回答是GPT2
