### ISSUE TITLE
默认安装1.1.3版本看openai api官方文档用的DALL-E2, 为什么画图那么丑；微软也用的DALL-E2就很漂亮。请教如何优化？

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#823]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 1.1.3
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足 满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
默认安装1.1.3版本看openai api官方文档用的DALL-E2, 为什么画图那么丑；微软也用的DALL-E2就很漂亮
> 简要说明、截图、复现步骤等，也可以是需求或想法
下面是默认安装在微信里触发画的图，中国双胞胎
![image](https://user-images.githubusercontent.com/4240638/231637027-36e40f53-3e4c-48a9-b20e-0db454578de9.png)
![435f2e1d1222a7b14b2f319958fcbf8](https://user-images.githubusercontent.com/4240638/231637055-36de75e4-9cf9-4454-858a-aaee3d7018ca.png)

下面是微软 https://www.bing.com/images/create?FORM=GENILP 的绘图结果
![image](https://user-images.githubusercontent.com/4240638/231637272-89f4e62c-7f2d-4fc3-9b13-46107edc0e37.png)
![image](https://user-images.githubusercontent.com/4240638/231637320-03d7d2fd-ec27-47b9-a56a-b5839237622b.png)

对比下来，我们openai api默认接口画的图人脸变形严重，画面清晰度也不够高。

请教该怎么调整优化这个问题，谢谢！

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Centos 8.6
 - Python版本  ( 执行 `python3 -V` )： 3.9                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhangzhanhui** [comment]
@zhayujie 有办法能选择DALL-E2吗？

**Comment by alawnchen** [comment]
都是吓人的
