### ISSUE TITLE
天气查询需要密钥？

### ISSUE THREAD

**Issue by jiuchu** [zhayujie/chatgpt-on-wechat#825]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

[bot] 对不起，由于OpenMeteo API的API密钥无效，我无法提供2023年4月13日武汉的天气信息。需要获得有效的API密钥才能访问天气数据。这个不是不需要密钥吗？

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by goldfishh** [comment]
这个问题晚会我去处理一下，你收到需要API密钥的提示，是因为chatgpt首次访问meteo失败之后会捏造的信息
