### ISSUE TITLE
现在chatgpt注册不能用接码平台了，你们有什么其他的办法吗

### ISSUE THREAD

**Issue by HuangKangjun** [zhayujie/chatgpt-on-wechat#826]

**Comment by dqzboy** [comment]
能吧 昨天我还注册了，前提得保证节点稳定才行

**Comment by HuangKangjun** [comment]
从今天开始的，昨天我也注册了

**Comment by dqzboy** [comment]
那以后 5刀也搞不到了呀  只能从号贩子那买了

**Comment by HuangKangjun** [comment]
号贩子卖的就是5刀，以后还得涨了，不知道openai以后会不会放开这些虚拟手机号

**Comment by jokerlinnn** [comment]
> 号贩子卖的就是5刀，以后还得涨了，不知道openai以后会不会放开这些虚拟手机号

新注册的5刀都没了吗？

**Comment by jk256** [comment]
限制注册是好事，限制新账号送额度也是好事，我表示支持
