### ISSUE TITLE
大佬，summary插件怎么搞，实在google插件自己都搞了，没看懂这个summary要怎么搞

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#832]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

大佬，summary插件怎么搞，实在google插件自己都搞了，没看懂这么summary要怎么搞

**Comment by lanvent** [comment]
`summary`是一个预览版本的插件哈，它目前支持总结最新的八九十条消息，功能不够完善。更新到最新版本(1.2.3)后，你可以参考#770的安装方法来体验`summary`插件，未来 @goldfishh 也会把功能集成到`tool`里，控制指令跟回复效果都会更好一些

**Comment by Maddaxman** [comment]
知道了 原来走了一个googleapis.com的域名，代理规则没有，我超
