### ISSUE TITLE
5分钟不聊后，第1次聊timeout，需要retry才能恢复

### ISSUE THREAD

**Issue by DIDAO-id** [zhayujie/chatgpt-on-wechat#833]
### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
在新加坡的部署服务器连接api.openai.com速度很快。
但微信和ChatGPT聊天，如果有5分钟左右不聊，再开始的时候，每次都连接api.openai.com 超时，retry之后又能连接。

100%必现bug

### 终端日志 (如有报错)

[WARNING][2023-04-13 22:31:47][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-13 22:31:52][chat_gpt_bot.py:139] - [CHATGPT] 第1次重试
[DEBUG][2023-04-13 22:31:53][chat_gpt_bot.py:62] - [CHATGPT] new_query=[{'role': 'system', 'content': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}, {'role': 'user', 'content': 'hi'}], session_id=@fb1994e5dbb16f67207c0da5c6530b03, reply_cont=Hello! How can I assist you today?, completion_tokens=9
[DEBUG][2023-04-13 22:31:53][session_manager.py:78] - raw total_tokens=78, savesession tokens=77
[DEBUG][2023-04-13 22:31:53][chat_channel.py:134] - [WX] ready to decorate reply: Reply(type=TEXT, content=Hello! How can I assist you today?)

每天有大量timeout
[WARNING][2023-04-14 09:45:29][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:12:09][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:16:02][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:16:34][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:17:06][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:19:08][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:29:22][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:55:10][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 10:55:41][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 11:04:43][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)
[WARNING][2023-04-14 11:05:26][chat_gpt_bot.py:125] - [CHATGPT] Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=30)

但网络层面非常快和稳定。
ping api.openai.com
PING api.openai.com (104.18.6.192) 56(84) bytes of data.
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=1 ttl=55 time=1.95 ms
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=2 ttl=55 time=1.84 ms
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=3 ttl=55 time=2.16 ms

每次都是timeout，retry一次又恢复正常，100%出现

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Ubuntu 20.04
 - Python版本  ( 执行 `python3 -V` )：  Python 3.8.10    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

**Comment by lanvent** [comment]
网络快没有作用，瓶颈在OPENAI

**Comment by shengzhou1216** [comment]
> 网络快没有作用，瓶颈在OpenAI( 付费api key会好用一点

付费key也没用。调用频次也远未达到OpenAI的限制。
