### ISSUE TITLE
railway部署私有的repositories跑不起来

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#834]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

大佬，我在railway部署后生成的私有repositories项目，然后改里面的代码，加上其他工具和工具的key，然后选私有项目部署到railway，发现跑不起来，是什么原因呢，在本地能跑起来

**Comment by lanvent** [comment]
需要删除主目录的Dockerfile
