### ISSUE TITLE
接入企业微信客服，打通微信生态，解决微信公众号不主动回复问题

### ISSUE THREAD

**Issue by Martin-dq** [zhayujie/chatgpt-on-wechat#837]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
参考现在接入企业微信机器人的方案，将微信客服参数增加进配置文件，因为微信客服参数和企业微信机器人参数基本一致，
接入后后台启动项目回复 Unknown Wecom EventType: kf_account_auth_change，其他项目作者已有成功案例，但是并未写明接入细节，参考项目https://github.com/razertory/gpt-wework，微信客服的API接口规则如下，
// 验证企业微信回调的token
var token = "token"
// 验证企业微信回调的key
var encodingAesKey = "encodingAesKey"
// 企业微信企业id 这个参数在企业微信后台的企业信息页
var corpid = "corpid"
// 企业微信secret 这个参数需要通过企业微信app发送
var corpsecret = "corpsecret"
// 上下文对话能力，默认是 3, 可以根据需要修改对话长度
var weworkConversationSize = 3

请求方式: POST(HTTPS)
请求地址: https://qyapi.weixin.qq.com/cgi-bin/kf/account/add?access_token=ACCESS_TOKEN
{
    "name": "新建的客服帐号",
    "media_id": "294DpAog3YA5b9rTK4PjjfRfYLO0L5qpDHAJIzhhQ2jAEWjb9i661Q4lk8oFnPtmj"
}
![image](https://user-images.githubusercontent.com/56908545/231916732-6ecb40bd-fd7d-4a45-845f-2d7fccd70684.png)
获取会话状态
请求方式: POST(HTTPS)

请求地址: https://qyapi.weixin.qq.com/cgi-bin/kf/service_state/get?access_token=ACCESS_TOKEN

请求实例:

{
	"open_kfid": "wkxxxxxxxxxxxxxxxxxx",
	"external_userid": "wmxxxxxxxxxxxxxxxxxx"
}
通过扫码直接接入机器人账号
![acb55d0e-b539-4d75-84a1-7aabca5e20e2](https://user-images.githubusercontent.com/56908545/231917268-4746c542-02c9-435a-a800-4f72af3a01f3.jpg)
![image](https://user-images.githubusercontent.com/56908545/231917349-83ca1571-1ca0-4da0-843a-05a39efc690d.png)

后期思路，新建一个企业微信账号，在配置文件中指定CHAGPT机器人接管这个账号的回复，基本可以做到扫码回复，群@回复等，避免微信炸群，封号等问题

https://developer.work.weixin.qq.com/document/path/94662

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by LeafBanks** [comment]
加油！

**Comment by forczc** [comment]
支持

**Comment by adminlove520** [comment]
这个我之前试过一次 利用企业微信的微信客服   但是会导致消息最终全转发到自己服务器 而不能用原生客服模块 后边微信给封了 就没试过了   企业微信（微信客服）+公众号这个思路

**Comment by Martin-dq** [comment]
> 这个我之前试过一次 利用企业微信的微信客服 但是会导致消息最终全转发到自己服务器 而不能用原生客服模块 后边微信给封了 就没试过了 企业微信（微信客服）+公众号这个思路

公众号也是调用原生客服模块对接的，chatgpt-on-chat这个项目是将消息接入到个人微信，chatgpt接管个人微信，我在想，能否参考在企业微信建立一个账号作为指定客户，然后chagpt接管他自动回答，但是还在看企业微信的API代码，之前没做过这个

**Comment by Martin-dq** [comment]
有大神可以参考更新一下么
消息转发到指定客服

如果您有多个客服人员同时登录了客服并且开启了自动接入在进行接待，每一个客户的消息转发给客服时，多客服系统会将客户分配给其中一个客服人员。如果您希望将某个客户的消息转给指定的客服来接待，可以在返回transfer_customer_service消息时附上TransInfo信息指定一个客服帐号。 需要注意，如果指定的客服没有接入能力(不在线、没有开启自动接入或者自动接入已满)，该用户会被直接接入到指定客服，不再通知其它客服，不会被其他客服接待。建议在指定客服时，先查询客服的接入能力（获取在线客服接待信息接口），指定到有能力接入的客服，保证客户能够及时得到服务。

示例代码

 <xml> 
  <ToUserName><![CDATA[touser]]></ToUserName>  
  <FromUserName><![CDATA[fromuser]]></FromUserName>  
  <CreateTime>1399197672</CreateTime>  
  <MsgType><![CDATA[transfer_customer_service]]></MsgType>  
  <TransInfo> 
    <KfAccount><![CDATA[test1@test]]></KfAccount> 
  </TransInfo> 
</xml>

**Comment by lichengzhe** [comment]
赞，这个模版出来，企业微信应用和客服就都可以接入了

**Comment by LeafBanks** [comment]
大神，什么时候打通？

**Comment by zousoo** [comment]
蹲一个

**Comment by lanvent** [comment]
微信公众号认证后可以主动回复问题。

已准备支持企业微信应用号，正在合并中 #936

**Comment by lichengzhe** [comment]
> 微信公众号认证后可以主动回复问题。
> 
> 
> 
> 已准备支持企业微信应用号，正在合并中 #936 

貌似客服接口和应用接口还有些区别 还没研究明白

**Comment by kill136** [comment]
大神 搞定了吗？

**Comment by TangSY** [comment]
企业微信客服可以接入了吗
