### ISSUE TITLE
Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gkuanine** [zhayujie/chatgpt-on-wechat#838]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：window server 2012 R2
 - Python版本  ( 执行 `python3 -V` )：Python 3.9.0
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.2.3

Administrator@WIN-HGNO5F5OIJ7 MINGW64 ~/Desktop/chatgpt-on-wechat (master)
$ python app.py
[ERROR][2023-04-14 10:28:43][app.py:47] - App startup failed!
[ERROR][2023-04-14 10:28:43][app.py:48] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\app.py", line 24, in run
    load_config()
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\config.py", line 164, in load_config
    config = Config(json.loads(config_str))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by forczc** [comment]
看起来是文件编码的问题，把相关文件删掉重新从仓库拉下来。看你是用windows，尽量用sublime之类的编辑器改。不知道哪个文件就整个项目重新拉
---------
以上是推测，可以试试
