### ISSUE TITLE
无法使用godcmd

### ISSUE THREAD

**Issue by LINKlang** [zhayujie/chatgpt-on-wechat#840]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![image](https://user-images.githubusercontent.com/116951234/231950113-5977077e-302c-4f9b-ac1d-a10dbdcc7249.png)

无法使用godcmd
一直提示找不到插件

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( Python 3.8.10` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by LINKlang** [comment]
补充：
help后插件也只有这些
![image](https://user-images.githubusercontent.com/116951234/231951058-9b63cb5a-6f7e-4695-a650-a54bda787c56.png)

**Comment by lanvent** [comment]
参考[使用说明](https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/godcmd)

**Comment by forczc** [comment]
啥auto，是auth

**Comment by LINKlang** [comment]
是打错了啊……
好吧
