### ISSUE TITLE
关于tool插件不能启用的问题

### ISSUE THREAD

**Issue by zkaiera** [zhayujie/chatgpt-on-wechat#842]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
配置以后其他功能全部正常执行，日志中tool和Banwords无法正常启用，查看配置文件显示false（前面已经修改为ture），在对话中通过#enablep命令启用，回复[ERROR]插件开启失败。

### 终端日志 (如有报错)

```
[INFO][2023-04-14 09:20:09][config.py:135] - [Config] User datas loaded.
[INFO][2023-04-14 09:20:09][plugin_manager.py:47] - Loading plugins config...
[INFO][2023-04-14 09:20:09][plugin_manager.py:63] - Scaning plugins ...
[INFO][2023-04-14 09:20:09][plugin_manager.py:39] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-04-14 09:20:09][plugin_manager.py:39] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-04-14 09:20:09][plugin_manager.py:39] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-04-14 09:20:09][plugin_manager.py:39] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-04-14 09:20:09][plugin_manager.py:39] - Plugin Role_v1.0 registered, path=./plugins/role
chatgpt-tool-hub version: 0.3.9
chatgpt-tool-hub 0.3.8后，部分工具名将变更：requests -> url-get
[INFO][2023-04-14 09:20:10][plugin_manager.py:39] - Plugin tool_v0.3 registered, path=./plugins/tool
[INFO][2023-04-14 09:20:10][plugin_manager.py:39] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-04-14 09:20:10][plugin_manager.py:39] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-04-14 09:20:10][godcmd.py:185] - [Godcmd] inited
[WARNING][2023-04-14 09:20:10][banwords.py:44] - [Banwords] init failed, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[WARNING][2023-04-14 09:20:10][plugin_manager.py:120] - Failed to init BANWORDS, diabled. [Errno 2] No such file or directory: '/root/chatgpt-on-wechat/plugins/banwords/banwords.txt'
[WARNING][2023-04-14 09:20:10][plugin_manager.py:120] - Failed to init TOOL, diabled. Expecting ',' delimiter: line 9 column 3 (char 175)
[INFO][2023-04-14 09:20:10][role.py:60] - [Role] inited
[INFO][2023-04-14 09:20:10][dungeon.py:43] - [Dungeon] inited

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Ubuntu20.04
 - Python版本  ( 执行 `python3 -V` )：     3.8.10                 
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：20.0.2

**Comment by zhayujie** [comment]
检查下 plugins/tool/config.json 的格式是否正确， 第9行

**Comment by aidyfeng** [comment]
我也是tool插件自从前天拉取过代码,重启后就无法使用了
后台输出:
`
[INFO][2023-04-14 14:15:12][config.py:135] - [Config] User datas loaded.
/home/zilanteng77/.local/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg 
or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
█^M[INFO][2023-04-14 14:15:12][plugin_manager.py:47] - Loading plugins config...
[INFO][2023-04-14 14:15:12][plugin_manager.py:63] - Scaning plugins ...
[INFO][2023-04-14 14:15:12][plugin_manager.py:39] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
chatgpt-tool-hub version: 0.3.9
ESC[31;1mESC[1;3mchatgpt-tool-hub 0.3.8后，部分工具名将变更：requests -> url-getESC[0m
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin tool_v0.3 registered, path=./plugins/tool
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-04-14 14:15:13][plugin_manager.py:39] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[ERROR][2023-04-14 14:15:13][plugin_manager.py:150] - Plugin sdwebui not found, but found in plugins.json
[INFO][2023-04-14 14:15:13][godcmd.py:170] - [Godcmd] 因未设置口令，本次的临时口令为3524。
[INFO][2023-04-14 14:15:13][godcmd.py:185] - [Godcmd] inited
[INFO][2023-04-14 14:15:13][role.py:60] - [Role] inited
[INFO][2023-04-14 14:15:13][dungeon.py:43] - [Dungeon] inited
[INFO][2023-04-14 14:15:13][hello.py:16] - [Hello] inited
[INFO][2023-04-14 14:15:13][finish.py:16] - [Finish] inited
Getting uuid of QR code.
Downloading QR code.


[INFO][2023-04-14 14:16:27][wechat_channel.py:167] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
未知插件命令
查看插件命令列表请输入#help 插件名
), receiver=@bd843f0ecb6a3c3dba4f315ce8363974
`
配置文件

![image](https://user-images.githubusercontent.com/13725371/232071190-d4f2bcf3-be2f-4c28-a842-fd4565aa34b8.png)
