### ISSUE TITLE
方案二，clash在服务器上如何切换节点呀

### ISSUE THREAD

**Issue by auto-fly** [zhayujie/chatgpt-on-wechat#843]
服务器版clash如何切点节点呀

**Comment by zhayujie** [comment]
配置了auto就可以自动切，类似这样

proxy-groups:
  - name: Auto

**Comment by auto-fly** [comment]
谢谢！


| |
leepengchao
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年4月14日 19:49 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zhayujie/chatgpt-on-wechat] 方案二，clash在服务器上如何切换节点呀 (Issue #843) |

配置了auto就可以自动切，类似这样

proxy-groups:

name: Auto
