### ISSUE TITLE
tool的config问题和一些建议

### ISSUE THREAD

**Issue by LINKlang** [zhayujie/chatgpt-on-wechat#845]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

请问一下tool的config要加功能是这样吗，好像这样就用不了了
![image](https://user-images.githubusercontent.com/116951234/232070018-fbb3ee72-40c1-4cfb-bd70-126938bc5608.png)

还有能不能加个黑名单功能，在群中只有一些人能用

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( 3.8.10 )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by LINKlang** [comment]
补充：
现在就算把tool的config文件删了tool也用不了了
![image](https://user-images.githubusercontent.com/116951234/232071632-23f82c56-6f6b-44f2-bf52-f203a8471f5a.png)

我tool是废了吗

**Comment by goldfishh** [comment]
你好，当你要添加一个tool，把新tool 名填入 tools list 里，同时如果该tool有额外配置参数，填入到kwargs里，
可参考 https://github.com/goldfishh/chatgpt-tool-hub/blob/master/docs/apply_optional_tool.md

如果需要插件ban掉某个人不能使用某个tool这种粒度，请查阅godcmd插件是否有实现，如未实现欢迎pr

**Comment by LINKlang** [comment]
> 你好，当你要添加一个工具，把新tool 名填入 tools list 里，同时如果该tool有额外配置参数，填入到kwargs里， 可参考 https://github.com/goldfishh/chatgpt-tool-hub/blob/master/docs/apply_optional_tool.md
> 
> 如果需要插件ban掉某个人不能使用某个工具这种粒度，请查阅godcmd插件是否有实现，如未实现欢迎PR



请问是这样吗
![image](https://user-images.githubusercontent.com/116951234/232179646-980a0923-ed30-4599-b7fd-31d8979d479f.png)

**Comment by zhayujie** [comment]
@LINKlang  bingo

**Comment by LINKlang** [comment]
> 

但是改完后在help里还是没有tool了
![IMG_1024](https://user-images.githubusercontent.com/116951234/232180050-d1a09040-9c43-408c-ac3d-3fb728261a65.jpg)

**Comment by LINKlang** [comment]
> @LINKlang bingo

也重启过了

**Comment by LINKlang** [comment]
@zhayujie 
怎么办啊，没用啊

**Comment by goldfishh** [comment]
> @zhayujie
> 怎么办啊，没用啊

你好 requirement-option.txt里面的依赖安装了吗？
能否提供日志方便判断问题

**Comment by LINKlang** [comment]
> > @zhayujie
> > 怎么办啊，没用啊
> 
> 你好 requirement-option.txt里面的依赖安装了吗？ 能否提供日志方便判断问题

谢谢，我刚刚用重装的方式自己搞定了
