### ISSUE TITLE
执行pip3 install -r requirements-optional.txt 报错tiktoken>=0.3.2 

### ISSUE THREAD

**Issue by ywh888** [zhayujie/chatgpt-on-wechat#848]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：3.9
3. `git pull` 拉取最新代码

5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足

### 问题描述

Collecting tiktoken>=0.3.2 (from -r requirements-optional.txt (line 1))
  Could not find a version that satisfies the requirement tiktoken>=0.3.2 (from -r requirements-optional.txt (line 1)) (from versions: )
No matching distribution found for tiktoken>=0.3.2 (from -r requirements-optional.txt (line 1))

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by chenxilol** [comment]
解决了吗？我也有类似问题

**Comment by SwarcSal** [comment]
同样的问题
