### ISSUE TITLE
插件显示无插件tool

### ISSUE THREAD

**Issue by ywh888** [zhayujie/chatgpt-on-wechat#849]
![image](https://user-images.githubusercontent.com/35958060/232184029-f9f6734e-0bcb-43ea-b869-abec7ba00012.png)

**Comment by ywh888** [comment]
![image](https://user-images.githubusercontent.com/35958060/232184153-cab21f80-8559-4e7b-b00e-320c46d7c0e3.png)

**Comment by ywh888** [comment]
![image](https://user-images.githubusercontent.com/35958060/232197628-cbac6a54-c6a4-45e3-aa0a-d91db342c4d2.png)

**Comment by MicroOpeMaster** [comment]
你输入有问题，应该是$tool

**Comment by ywh888** [comment]
就是这样输入的
试了好几个

**Comment by ywh888** [comment]
![image](https://user-images.githubusercontent.com/35958060/232230349-0547b76d-8a1b-4aae-8edb-d63f4fc7c5ec.png)

**Comment by weijianfan** [comment]
我也遇到这个问题，不知何故，怎么也出不来tool插件

**Comment by MicroOpeMaster** [comment]
> ![image](https://user-images.githubusercontent.com/35958060/232230349-0547b76d-8a1b-4aae-8edb-d63f4fc7c5ec.png)
你这应该是插件没打开，在plugins/config.json把tool启用一下

**Comment by weijianfan** [comment]
怎么启用？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MicroOpeMaster ***@***.***&gt;
发送时间: 2023年4月15日 22:48
收件人: zhayujie/chatgpt-on-wechat ***@***.***&gt;
抄送: weijianfan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhayujie/chatgpt-on-wechat] 插件显示无插件tool (Issue #849)





  

 你这应该是插件没打开，在plugins/config.json把tool启用一下

**Comment by MicroOpeMaster** [comment]
> 怎么启用？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MicroOpeMaster ***@***.***&gt; 发送时间: 2023年4月15日 22:48 收件人: zhayujie/chatgpt-on-wechat ***@***.***&gt; 抄送: weijianfan ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [zhayujie/chatgpt-on-wechat] 插件显示无插件tool (Issue #849) 你这应该是插件没打开，在plugins/config.json把tool启用一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我说错了，是在chatgpt-on-wechat/plugins/plugins.json里把tool部分的enable改为"true"

**Comment by weijianfan** [comment]
谢谢，果然可以了。

**Comment by ywh888** [comment]
![image](https://user-images.githubusercontent.com/35958060/232282760-bc79332c-9bb5-4824-b5a1-444a747b0aca.png)
还是这样

**Comment by ywh888** [comment]
![image](https://user-images.githubusercontent.com/35958060/232283979-329a8a58-b864-4419-84a3-f7803d6b19de.png)
为啥我改了好几次也保持了他还这样
又跳回来了

**Comment by Maddaxman** [comment]
@ywh888 +1 我也一样

**Comment by shenxianbu4** [comment]
同问，又自己改为false，tool依然无法启用，我把google_search和bing_search都放在了plugins下，tool下的config.json也改了

**Comment by lanvent** [comment]
使用最新代码吧，临时修复了这个问题
