### ISSUE TITLE
【增强】2023年2月7日  当前程序使用的是GPT-2，能切换成GPT-3么

### ISSUE THREAD

**Issue by BaoHeTaiHe** [zhayujie/chatgpt-on-wechat#85]
大佬 现在程序使用的是GPT-2，能切换成GPT-3么

**Comment by zhayujie** [comment]
> 大佬 现在程序使用的是GPT-2，能切换成GPT-3么

现在用的是gpt3

<img width="869" alt="image" src="https://user-images.githubusercontent.com/26161723/217248435-59cbbcf9-f305-40b0-bc37-4fd7408fbe38.png">

**Comment by BaoHeTaiHe** [comment]
> > 大佬现在程序使用的是GPT-2，能切换成GPT-3呢
> 
> 现在使用的是gpt3
> 
> <img alt="图像" width="869" src="https://user-images.githubusercontent.com/26161723/217248435-59cbbcf9-f305-40b0-bc37-4fd7408fbe38.png">

好嘞 ，我想自己研究研究，请问这个配置在哪个文件

**Comment by zhayujie** [comment]
在代码里 bot/openai/open_ai_bot.py

**Comment by BaoHeTaiHe** [comment]
> 在代码里 bot/openai/open_ai_bot.py

好嘞ヽ(￣▽￣)و
