### ISSUE TITLE
二维码内存在问号是什么原因

### ISSUE THREAD

**Issue by Greywizard1** [zhayujie/chatgpt-on-wechat#851]
linux上部署，Python 3.8.3
启动后生成的二维码存在问号,这个什么原因

![image](https://user-images.githubusercontent.com/130820286/232187316-f09a5791-5c6f-4ef1-98eb-4d6483691f83.png)

**Comment by lanvent** [comment]
通常是终端字体设置问题，二维码上方有4个网址，可以扫那个

**Comment by Greywizard1** [comment]
> 

感谢~

> 通常是终端字体设置问题，二维码上方有4个网址，可以扫那个
