### ISSUE TITLE
[ERROR]tool插件开启失败。

### ISSUE THREAD

**Issue by weijianfan** [zhayujie/chatgpt-on-wechat#854]
### 前置确认

网络能够访问openai接口
python 已安装：版本在 3.7 ~ 3.10 之间
git pull 拉取最新代码
执行pip3 install -r requirements.txt，检查依赖是否满足
拓展功能请执行pip3 install -r requirements-optional.txt，检查依赖是否满足
在已有 issue 中未搜索到类似问题
FAQS 中无类似问题

### 问题描述

配置以后其他功能全部正常执行，日志中tool和Banwords无法正常启用，查看配置文件显示false（前面已经修改为ture），在对话中通过#enablep命令启用，回复[ERROR]插件开启失败。

此时查看plugins.json，会发现其中tool插件的设置会恢复到false，尽管之前手工设为true

### 终端日志 (如有报错)

[WARNING][2023-04-16 01:44:34][load_app.py:28] - [deprecated]: load_app will be replaced by chatgpt_tool_hub.apps.AppFactory.create_app
[WARNING][2023-04-16 01:44:34][plugin_manager.py:120] - Failed to init TOOL, diabled. str expected, not int
[INFO][2023-04-16 01:44:34][wechat_channel.py:167] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件开启失败), receiver=@b734e7dd08de2e225cb860957c7e7f1a

### 环境

- 操作系统类型 (Mac/Windows/Linux)：Ubuntu 22.04.1 LTS 
- Python版本 ( 执行 python3 -V )： 3.10.6
- pip版本 ( 依赖问题此项必填，执行 pip3 -V)：22.0.2

**Comment by goldfishh** [comment]
toolhub 0.3.10

**Comment by weijianfan** [comment]
> toolhub 0.3.10

谢谢答复，但将toolhub升级到0.3.10后，问题仍然存在，没有变化

➜  plugins git:(master) ✗ pip3 list | grep chat
chatgpt-tool-hub         0.3.10
itchat-uos               1.5.0.dev0
wechaty                  0.10.7
wechaty-grpc             0.20.19
wechaty-puppet           0.4.23
wechaty-puppet-service   0.8.10

**Comment by goldfishh** [comment]
config.json 的timeout 值 请暂时配置成str

**Comment by weijianfan** [comment]
> config.json 的timeout 值 请暂时配置成str

仍然无济于事，我将tool目录下config.json的所有值都改为str类型了（加双引号），也不行。

➜  tool git:(master) ✗ cat config.json
{
  "tools": ["wikipedia"], 
  "kwargs": {
      "request_timeout": "60",  
      "no_default": "false",  
      "top_k_results": "1",
      "model_name": "gpt-3.5-turbo",
      "OPTIONAL_API_NAME": "OPTIONAL_API_KEY" 
  }
}

**Comment by shenxianbu4** [comment]
我也是这个问题，同问

**Comment by lanvent** [comment]
pull 最新的代码吧，这个问题已经fix了

**Comment by 1iang** [comment]
> pull 最新的代码吧，这个问题已经fix了，原因可以参考 #858

请问下railway部署，报“[ERROR][2023-04-17 07:42:35][plugin_manager.py:110] - Failed to import plugin tool: No module named 'webdriver_manager'”是什么原因，试了toolhub 0.3.10和0.3.9都不行，之前是可以用的

**Comment by lanvent** [comment]
```pip3 install --upgrade requirement-optional.txt``` 试试，如果还是不行就先手动安装这些依赖吧，等待chatgpt-tool-hub的更新~

**Comment by JS00000** [comment]
```
[ERROR][2023-04-17 21:38:35][victorinox.py:36] - 1 validation error for RequestsWrapper
__root__
  __init__() got an unexpected keyword argument 'options' (type=type_error)
[ERROR][2023-04-17 21:38:35][plugin_manager.py:151] - Failed to init TOOL, diabled. tool初始化失败
```
手动安装所有需要的依赖之后目前是这个报错，目前的chatgpt_tool_hub版本是0.3.14。

**Comment by weijianfan** [comment]
昨天的新版本已经完美解决了问题。
