### ISSUE TITLE
User datas file not found,请问这个用户数据是干什么用的，该怎么生成

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#855]
### 前置确认

1. 网络能够访问openai接口 是
2. python 已安装：版本在 3.7 ~ 3.10 之间 是
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足 满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足 是
6. 在已有 issue 中未搜索到类似问题 是
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题 没有

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

启动日志提示：

[config.py:137] - [Config] User datas file not found, ignore.

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Centos8.6
 - Python版本  ( 执行 `python3 -V` )：  3.9                    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.1 from /home/jvs086/.local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by 6vision** [comment]
+1同问，启动时候经常提示这个

**Comment by lanvent** [comment]
这个是用户设置私有apikey("#set_openai_api_key")时存储的数据，可以不用管

**Comment by viktorsjr** [comment]
> 这个是用户设置私有apikey("#set_openai_api_key")时存储的数据，可以不用管

请问下#set_openai_api_key设置用户私有apikey，生效范围是？在一个群里a用户设置了，其他用户提问的时候是走的默认的key还是a设置的key?

**Comment by lanvent** [comment]
在群里设置目前的生效范围是整个群。 如果想限制使用范围在单个会话的话，需要修改一行代码，我在想哪一种更好一些

**Comment by lanvent** [comment]
不会，目前`itchat`下只有summary插件是采用名字来标识对象的
