### ISSUE TITLE
tool插件无法开启，在plugins.json里已经设置为true，但是执行程序后，又自己还原为false

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#858]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

tool插件无法开启，在plugins.json里已经设置为true，但是执行程序后，又自己还原为false

前置操作：新装了summary插件，并已经安装了summary里的requirement，聊天里查summary插件是加载出来了，但tool插件没了

**Comment by shenxianbu4** [comment]
git clone https://github.com/goldfishh/chatgpt-tool-hub.git，这里是在chatgpt-on-wechat里边执行的吗？

**Comment by Maddaxman** [comment]
> git clone [https://github.com/goldfishh/chatgpt-tool-hub.git，这里是在chatgpt-on-wechat里边执行的吗？](https://github.com/goldfishh/chatgpt-tool-hub.git%EF%BC%8C%E8%BF%99%E9%87%8C%E6%98%AF%E5%9C%A8chatgpt-on-wechat%E9%87%8C%E8%BE%B9%E6%89%A7%E8%A1%8C%E7%9A%84%E5%90%97%EF%BC%9F)

是的

**Comment by shenxianbu4** [comment]
[INFO]
通用指令：
#help : 回复此帮助
#help 插件名: 回复指定插件的详细帮助
#set_openai_api_key api_key: 设置你的OpenAI私有api_key
#reset_openai_api_key : 重置为默认的api_key
#reset : 重置会话
目前可用插件有：
角色扮演:让机器人扮演不同的角色。
文字冒险:可以和机器人一起玩文字冒险游戏。

config.json文件中是这样没错吧？
{
  "tools": [],
  "kwargs": {
      "openai_api_key": "sk-*****************************************",
      "proxy": "",
      "debug": false,
      "request_timeout": 60,
      "no_default": false,
      "model_name": "gpt-3.5-turbo"
  }
}

**Comment by shenxianbu4** [comment]
我git到chatgpt-on-wechat后，我应该怎么启用他？

**Comment by Maddaxman** [comment]
> [INFO] 通用指令： #help : 回复此帮助 #help 插件名: 回复指定插件的详细帮助 #set_openai_api_key api_key: 设置你的OpenAI私有api_key #reset_openai_api_key : 重置为默认的api_key #reset : 重置会话 目前可用插件有： 角色扮演:让机器人扮演不同的角色。 文字冒险:可以和机器人一起玩文字冒险游戏。
> 
> config.json文件中是这样没错吧？ { "tools": [], "kwargs": { "openai_api_key": "sk-*****************************************", "proxy": "", "debug": false, "request_timeout": 60, "no_default": false, "model_name": "gpt-3.5-turbo" } }

我的是
{
  "tools": ["python", "url-get", "terminal", "meteo-weather","google-search","morning-news","bing-search","wolfram-alpha"],
  "kwargs": 
  {
      "top_k_results": 2,
      "no_default": false,
      "model_name": "gpt-3.5-turbo",
      "google_api_key": "AIzaSyBWVa_dQDG2S**************",
      "google_cse_id": "37bdde**************",
      "zaobao_api_key": "MvI9a**************",
      "bing_subscription_key": "a459934fafa24e5**************",
      "wolfram_alpha_appid": "6RX4J9-**************",
  }
}

**Comment by Maddaxman** [comment]
> 我git到chatgpt-on-wechat后，我应该怎么启用他？

wechat项目自带这个tool，要修改plugins->tool文件夹里的config.json，把你想用的插件，从tool这个项目复制到wechat项目的plugins文件夹里   https://github.com/goldfishh/chatgpt-on-wechat/blob/master/plugins/tool/README.md

**Comment by shenxianbu4** [comment]
> > 我git到chatgpt-on-wechat后，我应该怎么启用他？
> 
> wechat项目自带这个tool，要修改plugins->tool文件夹里的config.json，把你想用的插件，从tool这个项目复制到wechat项目的plugins文件夹里 https://github.com/goldfishh/chatgpt-on-wechat/blob/master/plugins/tool/README.md

大哥你好，设置完plugins->tool文件夹里的config.json后，我在wechat/plugins/下直接git clone https://github.com/goldfishh/chatgpt-tool-hub.git  在plugins下生成了一个chatgpt-tool-hub，这个文件夹下的config.json和plugins/tool/config.json设置一样，可是还运行不了，请大哥帮忙解答一下我的疑惑

**Comment by shenxianbu4** [comment]
> > 我git到chatgpt-on-wechat后，我应该怎么启用他？
> 
> wechat项目自带这个tool，要修改plugins->tool文件夹里的config.json，把你想用的插件，从tool这个项目复制到wechat项目的plugins文件夹里 https://github.com/goldfishh/chatgpt-on-wechat/blob/master/plugins/tool/README.md

我将chatgpt-tool-hub下的google-search文件夹复制到chatgpt-on-wechat/plugins/下就可以了？

**Comment by shenxianbu4** [comment]
> > 我git到chatgpt-on-wechat后，我应该怎么启用他？
> 
> wechat项目自带这个tool，要修改plugins->tool文件夹里的config.json，把你想用的插件，从tool这个项目复制到wechat项目的plugins文件夹里 https://github.com/goldfishh/chatgpt-on-wechat/blob/master/plugins/tool/README.md

这个是我的/pulgins/tool/config.json的设置
{
  "tools": ["python", "url-get", "terminal", "meteo-weather", "wikipedia", "bing-search", "google-search"],
  "kwargs": {
      "top_k_results": 2,
      "bing_subscription_key": "2e14564h746c41559d6de74746f0de78",
      "google_api_key": "AIz3SyCHUQ5Oacs8873btiXlor7Y0k-PvN25LeQ",
      "google_cse_id": "80bdb7245c57b4664",
      "no_default": false,
      "model_name": "gpt-3.5-turbo"
  }
}

**Comment by Maddaxman** [comment]
> > > 我git到chatgpt-on-wechat后，我应该怎么启用他？
> > 
> > 
> > wechat项目自带这个tool，要修改plugins->tool文件夹里的config.json，把你想用的插件，从tool这个项目复制到wechat项目的plugins文件夹里 https://github.com/goldfishh/chatgpt-on-wechat/blob/master/plugins/tool/README.md
> 
> 这个是我的/pulgins/tool/config.json的设置 { "tools": ["python", "url-get", "terminal", "meteo-weather", "wikipedia", "bing-search", "google-search"], "kwargs": { "top_k_results": 2, "bing_subscription_key": "2e14564h746c41559d6de74746f0de78", "google_api_key": "AIz3SyCHUQ5Oacs8873btiXlor7Y0k-PvN25LeQ", "google_cse_id": "80bdb7245c57b4664", "no_default": false, "model_name": "gpt-3.5-turbo" } }

不用clone，wechat项目的 的plugins文件夹就是tool项目

**Comment by lanvent** [comment]
原因是`summary`依赖的`chatgpt-tool-hub`版本(0.3.10)有一个参数类型的不兼容问题， 可拉取最新代码，目前临时fix了这个问题。
如果要重新开启插件，需要使用"#enablep tool"命令或修改`plugins/plugins.json`中对应的项

**Comment by hugo911** [comment]
[需要管理员权限才能执行该命令]如何设置管理员身份

**Comment by LINKlang** [comment]
> [需要管理员权限才能执行该命令]如何设置管理员身份

用#auth xxxxx
xxxxx是你自己设置的
