### ISSUE TITLE
规则定制化： 支持私聊中按指定规则触发自动回复，支持对群组设置自动回复白名单——这个功能在哪里设置

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#861]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

1.2.3代码的readme里有下面的描述，但是没看到相关选项和插件，请问在哪里设置
规则定制化： 支持私聊中按指定规则触发自动回复，支持对群组设置自动回复白名单

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
`single_chat_prefix`跟`group_name_white_list`

**Comment by zhangzhanhui** [comment]
> 

这两个我记得是在主程序的config.json里面设置，主要是私聊和群聊权限设置。但是好像没有和回复有关的规则设置。

**Comment by lanvent** [comment]
这个指的就是触发规则了，你想说的是某些关键词触发指定回复是吗？
