### ISSUE TITLE
内地服务器 设置了clash代理，No handler responded message <werobot.messages.messages.TextMessage object at 0x7f597ba42e80>

### ISSUE THREAD

**Issue by WandingPace** [zhayujie/chatgpt-on-wechat#862]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

按流程接入微信公众号，也配置了clash的proxy，测试还是不行

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```
[W 230417 01:27:25 robot:613] No handler responded message <werobot.messages.messages.TextMessage object at 0x7f597ba42e80>
81.69.101.237 - - [17/Apr/2023 01:27:25] "POST /?signature=17940841a99c9c636d200fc9011294299d086ac7&timestamp=1681666035&nonce=153870919&openid=o0i-M5oFHLaPtuIRMZqCkB-e6ee8 HTTP/1.1" 200 0
[INFO][2023-04-17 01:27:25][wechat_mp_channel.py:29] - [WX_Public] receive public msg: bot 吃饭了吗, userId: o0i-M5oFHLaPtuIRMZqCkB-e6ee8
[INFO][2023-04-17 01:27:25][wechat_mp_channel.py:57] - count=1, res={'status': 'waiting', 'req_times': 3}
[INFO][2023-04-17 01:27:26][wechat_mp_channel.py:57] - count=2, res={'status': 'waiting', 'req_times': 3}
[INFO][2023-04-17 01:27:27][wechat_mp_channel.py:57] - count=3, res={'status': 'waiting', 'req_times': 3}
[INFO][2023-04-17 01:27:28][wechat_mp_channel.py:57] - count=4, res={'status': 'waiting', 'req_times': 3}
[INFO][2023-04-17 01:27:28][wechat_mp_channel.py:64] - 微信超时3次
81.69.101.237 - - [17/Apr/2023 01:27:28] "POST /?signature=17940841a99c9c636d200fc9011294299d086ac7&timestamp=1681666035&nonce=153870919&openid=o0i-M5oFHLaPtuIRMZqCkB-e6ee8 HTTP/1.1" 200 335

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：centOS
 - Python版本  ( 执行 `python3 -V` )： 
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
请在bot-on-anything repo提问
