### ISSUE TITLE
推荐一些低价服务器吧

### ISSUE THREAD

**Issue by Naaril** [zhayujie/chatgpt-on-wechat#863]
RackNerd是一家位于美国，成立于2019年的主机商。RackNerd的主要产品有VPS和独立服务器租用等，其数据中心分布于全球14个地区，共计17个，包括美国洛杉矶、达拉斯、圣何塞、芝加哥、西雅图、纽约、荷兰阿姆斯特丹、英国伦敦等。该系列主机拥有国内三网直连线路，接入CN2，国内访问速度理想。

目前有新年促销和复活节促销，VPS价格最低的只需要10.18刀/年

打开下面链接可直接购买，国内支持支付宝、银联卡，具体配置点进去看吧，页面支持中文

下面是按价格从低到高排序的，我自己搭建是用的10.78刀的，系统可以选择Ubuntu，各位有性价比更好的也说一下吧。

10.18刀/年  CPU1核 内存512M SSD10G 流量1.5T/月
https://my.racknerd.com/aff.php?aff=7692&pid=734

10.28刀/年  CPU1核 内存768M SSD10G 流量1T/月
https://my.racknerd.com/aff.php?aff=7692&pid=695

10.78刀/年  CPU1核 内存840M SSD10G 流量1T/月
https://my.racknerd.com/aff.php?aff=7692&pid=766

11.88刀/年  CPU1核 内存768M SSD10G 流量2T/月
https://my.racknerd.com/aff.php?aff=7692&pid=679

12.98刀/年  CPU1核 内存1G SSD25G 流量4T/月
https://my.racknerd.com/aff.php?aff=7692&pid=735

14.88刀/年  CPU1核 内存1.2G SSD18G 流量2T/月
https://my.racknerd.com/aff.php?aff=7692&pid=670

14.98刀/年  CPU1核 内存1.2G SSD30G 流量3T/月
https://my.racknerd.com/aff.php?aff=7692&pid=767

14.98刀/年  CPU1核 内存1G SSD16G 流量3T/月
https://my.racknerd.com/aff.php?aff=7692&pid=680

16.88刀/年  CPU1核 内存1.5G SSD30G 流量3T/月
https://my.racknerd.com/aff.php?aff=7692&pid=696

21.98刀/年  CPU2核 内存2G SSD45G 流量5T/月
https://my.racknerd.com/aff.php?aff=7692&pid=768

20.98刀/年  CPU2核 内存2G SSD25G 流量4T/月
https://my.racknerd.com/aff.php?aff=7692&pid=681

24.88刀/年  CPU2核 内存2.5G SSD45G 流量6T/月
https://my.racknerd.com/aff.php?aff=7692&pid=736

25.88刀/年  CPU2核 内存2.5G SSD40G 流量3T/月
https://my.racknerd.com/aff.php?aff=7692&pid=671

25.95刀/年  CPU1核 内存1.5G SSD30G 流量3T/月
https://my.racknerd.com/aff.php?aff=7692&pid=319

28.55刀/年  CPU2核 内存2.5G SSD60G 流量7T/月
https://my.racknerd.com/aff.php?aff=7692&pid=697

29.5刀/年  CPU2核 内存2.5G SSD40G 流量5T/月
https://my.racknerd.com/aff.php?aff=7692&pid=211

29.99刀/年  CPU2核 内存3G SSD35G 流量5T/月
https://my.racknerd.com/aff.php?aff=7692&pid=473

30.19刀/年  CPU3核 内存3.5G SSD36G 流量5T/月
https://my.racknerd.com/aff.php?aff=7692&pid=125

**Comment by jokerlinnn** [comment]
这家的 重庆连过去很慢  好处是这家的ip没被openai拉黑   也就只能用来访问openai了
