### ISSUE TITLE
直接clone最新的项目仓库后运行，没有tool插件

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#869]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

直接clone最新的项目仓库后运行，没有tool插件，最新的代码已经包含（[fix: toolhub request_timeout should be str](https://github.com/zhayujie/chatgpt-on-wechat/commit/2f732e5493c6288f6a04405e858618fe87a25c90)）这个修改

**Comment by lanvent** [comment]
提issue时请贴出相关log

**Comment by Maddaxman** [comment]
> 提issue时请贴出相关log

@lanvent 

Please press confirm on your phone.
Loading the contact, this may take a little while.
[H[2JLogin successfully as 
[INFO][2023-04-17 15:08:29][wechat_channel.py:139] - Wechat login success, user_id: @3019199db5c1c1bd5713e1921227a, nickname: 
Start auto replying.
[INFO][2023-04-17 15:08:42][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-04-17 15:08:43][wechat_channel.py:206] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
通用指令：
#help : 回复此帮助
#help 插件名: 回复指定插件的详细帮助
#set_openai_api_key api_key: 设置你的OpenAI私有api_key
#reset_openai_api_key : 重置为默认的api_key
#reset : 重置会话

目前可用插件有：
角色扮演:让机器人扮演不同的角色。
文字冒险:可以和机器人一起玩文字冒险游戏。), receiver=@1e314837a5917f967542ae94c172e8c3
[INFO][2023-04-17 15:08:59][app.py:17] - signal 15 received, exiting...
[INFO][2023-04-17 15:08:59][config.py:134] - [Config] User datas saved.

**Comment by Maddaxman** [comment]
新下的包，没有改过里面的配置

**Comment by Maddaxman** [comment]
@lanvent 
发现 plugins.json里没有tool的代码，自行添加后，也没出来

**Comment by Maddaxman** [comment]
@lanvent 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/31379908/232415529-d10153a3-bd96-410e-a56a-690d4164a49d.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/31379908/232416207-fff4190a-d45e-4f04-897d-83feb627e6fb.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/31379908/232416615-bd739a70-3dd2-49b0-86b5-38a71750dbe9.png">

执行#reloadp tool
<img width="713" alt="image" src="https://user-images.githubusercontent.com/31379908/232416885-20c7e288-1ce0-4f6f-843f-5d56f2cb84dd.png">

**Comment by lanvent** [comment]
重启下程序吧， plugins目录下有tool文件夹吗，把程序启动时加载插件的log贴出来看看

**Comment by Maddaxman** [comment]
> 重启下程序吧， plugins目录下有tool文件夹吗，把程序启动时加载插件的log贴出来看看

@lanvent 
似乎运行tool需要的依赖库都没有安装

**Comment by lanvent** [comment]
缺失了什么依赖库

**Comment by Maddaxman** [comment]
> 缺失了什么依赖库

@lanvent 
selenium、webdriver_manager
装了这两个依赖库后tool可以启动了
