### ISSUE TITLE
画图报错

### ISSUE THREAD

**Issue by freeogo** [zhayujie/chatgpt-on-wechat#87]
[INFO][2023-02-07 23:09:22][open_ai_bot.py:71] - [OPEN_AI] image_query=一幅图，猫在树上
[INFO][2023-02-07 23:09:31][open_ai_bot.py:78] - [OPEN_AI] image_url=https://oaidalleapiprodscus.blob.core.windows.net/private/org-Gt5rx0gRxNOUTZbzhzA90jq0/user-xebIcPQOsJQOyG9AywE8UuLH/img-6BNfqk7PtI0ciJQ2eG1S00xP.png?st=2023-02-07T14%3A09%3A31Z&se=2023-02-07T16%3A09%3A31Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-02-06T21%3A30%3A16Z&ske=2023-02-07T21%3A30%3A16Z&sks=b&skv=2021-08-06&sig=05yQv469m95hmgFqGnzf%2BQxlZhtaQU7ehG9haFV%2BZ00%3D
[ERROR][2023-02-07 23:09:34][wechat_channel.py:139] - HTTPSConnectionPool(host='oaidalleapiprodscus.blob.core.windows.net', port=443): Max retries exceeded with url: /private/org-Gt5rx0gRxNOUTZbzhzA90jq0/user-xebIcPQOsJQOyG9AywE8UuLH/img-6BNfqk7PtI0ciJQ2eG1S00xP.png?st=2023-02-07T14%3A09%3A31Z&se=2023-02-07T16%3A09%3A31Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-02-06T21%3A30%3A16Z&ske=2023-02-07T21%3A30%3A16Z&sks=b&skv=2021-08-06&sig=05yQv469m95hmgFqGnzf%2BQxlZhtaQU7ehG9haFV%2BZ00%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
Traceback (most recent call last):

**Comment by zhayujie** [comment]
国内网络吗，没有开代理吧？ 图片接口不能频繁访问
