### ISSUE TITLE
帐号无法登录

### ISSUE THREAD

**Issue by little-weakduck** [zhayujie/chatgpt-on-wechat#872]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

新注册的帐号已经绑定微信支付无法使用

![image](https://user-images.githubusercontent.com/83490374/232508133-8c8f254a-7399-4aae-aaf4-a4ffcb542501.png)

**Comment by jiferent** [comment]
从中国地区的app store下载微信试一下。

**Comment by LINKlang** [comment]
同样错误，是WeChat的原因好像
换了个中国微信号解决
希望有人解决的话踢我
