### ISSUE TITLE
国内网络无法访问 api.openai.com， 暂时只能通过开代理解决

### ISSUE THREAD

**Issue by al6nlee** [zhayujie/chatgpt-on-wechat#873]
## 一个问题
当前我使用阿里云服务器，想访问chatgpt的api，奈何代理一直配不好，使用了clash，去机场要的json文件，然后转成了yaml文件，启动clash，迟迟不生效，三天了  难受

**Comment by yhfgyyf** [comment]
看这个https://w1.v2free.top/doc/#/linux/clash，如果还不会，我可以帮你设置

**Comment by yuanzhiyong1999** [comment]
> 看这个[https://w1.v2free.top/doc/#/linux/clash，如果还不会，我可以帮你设置](https://w1.v2free.top/doc/#/linux/clash%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%BF%98%E4%B8%8D%E4%BC%9A%EF%BC%8C%E6%88%91%E5%8F%AF%E4%BB%A5%E5%B8%AE%E4%BD%A0%E8%AE%BE%E7%BD%AE)

您好，这个链接失效了，有新的吗

**Comment by yhfgyyf** [comment]
> > 看这个[https://w1.v2free.top/doc/#/linux/clash，如果还不会，我可以帮你设置](https://w1.v2free.top/doc/#/linux/clash%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%BF%98%E4%B8%8D%E4%BC%9A%EF%BC%8C%E6%88%91%E5%8F%AF%E4%BB%A5%E5%B8%AE%E4%BD%A0%E8%AE%BE%E7%BD%AE)
> 
> 您好，这个链接失效了，有新的吗

https://w1.v2free.top/doc/#/linux/clash

**Comment by al6nlee** [comment]
多谢哈  我试试

**Comment by lanvent** [comment]
可以看下#446的方法

**Comment by al6nlee** [comment]
前段时间成功了一次  后来又试了一次   结果死活打不开系统代理的开关
