### ISSUE TITLE
隐私保护模块

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#876]
刚刚推大家推荐玩的时候，有些人顾忌到隐私泄露，不敢私聊机器人问题。因为后台都能看见。能否弄一个隐私保护模块，至少使得用户发送的信息在wx上显示是加密的，后台log也不能看见。治愈机器人私聊发送的信息要不要加密，还不知道能否实现。

**Comment by forczc** [comment]
你明文私聊发给微信机器人这一步，就没法加密了吧，不然人人都要发密文给微信，那不就太麻烦了
而一旦你明文给机器人，我的机器人小号自然能知道你说了啥，你后台怎么加密都没辙

**Comment by lanvent** [comment]
信息只能明文处理，如果需要隐藏聊天记录log，建议提高日志等级
