### ISSUE TITLE
某些微信号登录会报错，这是微信号的问题？

### ISSUE THREAD

**Issue by pgydwhhw** [zhayujie/chatgpt-on-wechat#877]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
![1681783316937](https://user-images.githubusercontent.com/41056537/232650816-d8027d64-e44d-47e6-9c16-e706d5454479.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by doublet44** [comment]
实名认证一下

**Comment by yuanzhiyong1999** [comment]
请问解决了吗

**Comment by pgydwhhw** [comment]
报错没解决，换个微信号就解决了

**Comment by lanvent** [comment]
可能的原因是没有实名认证或被微信限制
