### ISSUE TITLE
使用railway部署一段时间后就没反应了，后台日志也没显示登出，有人有相同问题么

### ISSUE THREAD

**Issue by congxuma** [zhayujie/chatgpt-on-wechat#879]
后台日志没报错，没登出，发送消息没反应 感觉像是挂了一样

**Comment by MGeorge01** [comment]
我也是，要重启一下项目才会好

**Comment by kianfeng** [comment]
我也遇到了同样的问题. 我的目前解决方案是先暴力的放到了云的vm里面, 然后保持后台运行. 感觉不是很好的solution :(

**Comment by congxuma** [comment]
> 我也遇到了同样的问题. 我的目前解决方案是先暴力的放到了云的vm里面, 然后保持后台运行. 感觉不是很好的solution :(

关键是不知道什么问题，是railway的问题么？

**Comment by chikang** [comment]
会不会是跟你设置了3600秒的无反应时间有关系？

**Comment by congxuma** [comment]
> 会不会是跟你设置了3600秒的无反应时间有关系？

应该不是，3600s这个应该是1小时没回复结束会话，我运行1天左右然后没反应的，我朋友部署在自己的服务器好久了也没这个问题感觉不是配置的问题

**Comment by lanvent** [comment]
可能跟网络连接等有关，开启debug看看有没有日志

**Comment by feather-root** [comment]
我也遇到了，我是登入2天后，自动LOG OUT!，没看到其他错误。  如果定期重启的话，不是要定期扫描登入，感觉不方便

**Comment by weijianfan** [comment]
最近才出现的，以前没有。

**Comment by weijianfan** [comment]
> 

我说的最近指的是从4月21日以来

**Comment by yunmemory** [comment]
我有同样的问题，大概每个3-4天就会自动log out

**Comment by congxuma** [comment]
看日志显示如下：
Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
LOG OUT!
感觉是itchat的问题么

**Comment by lanvent** [comment]
see https://github.com/zhayujie/chatgpt-on-wechat/issues/916#issuecomment-1535873131

**Comment by bydxzq** [comment]
> 看日志显示如下： Unexpectedsync check result: window.synccheck={retcode:"1102",selector:"0"} LOG OUT! 感觉是itchat的问题么

大佬你这个问题是怎么解决的？我断了就再连码都登不了啦

**Comment by weijianfan** [comment]
我后来没再用了🥴



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhanzb ***@***.***&gt;
发送时间: 2023年7月15日 14:04
收件人: zhayujie/chatgpt-on-wechat ***@***.***&gt;
抄送: weijianfan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhayujie/chatgpt-on-wechat] 使用railway部署一段时间后就没反应了，后台日志也没显示登出，有人有相同问题么 (Issue #879)





  
看日志显示如下： Unexpectedsync check result: window.synccheck={retcode:"1102",selector:"0"} LOG OUT! 感觉是itchat的问题么
  
大佬你这个问题是怎么解决的？我断了就再连码都登不了啦
