### ISSUE TITLE
不能触发news插件

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#881]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/31379908/232679030-bb177dd2-5355-41c9-9493-324b58ab9416.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/31379908/232679398-1eb10789-a1d6-4ffb-bbf0-70f2e060a5a5.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/31379908/232679260-a9e75fae-74df-4cef-bfc4-746c3d2615d1.png">

**Comment by lanvent** [comment]
等待@goldfishh 来更新一下~

**Comment by miracle0609** [comment]
我这块也是，用不了tool这个插件，说插件不存在或未启用，requirements.txt和requirements-optional.txt都执行并且安装成功了，但还是不行。
![1681801050466](https://user-images.githubusercontent.com/51525450/232696707-cf2f0cd7-e07a-4008-a11c-f787e31c3448.png)
