### ISSUE TITLE
gpt-3.5的上下文支持能力不佳，是不是可以通过将上下文信息重新放入prompt的方式去模拟有上下文对话的情况？

### ISSUE THREAD

**Issue by xrefft** [zhayujie/chatgpt-on-wechat#883]
非部署或运行问题。

**Comment by 18515381698** [comment]
貌似就是这么处理的呀，session里维护了一个messages列表的

**Comment by xrefft** [comment]
> 

不知道是模型问题还是运行效果，我感受不到上下文，docker运行。

**Comment by xrefft** [comment]
![image](https://user-images.githubusercontent.com/22056669/233101394-73154430-a91b-40b3-81fa-36208b92afdf.png)

**Comment by xrefft** [comment]
![20230419071105](https://user-images.githubusercontent.com/22056669/233101999-7d034d63-d972-4200-99c6-71c91fec1ef8.png)
****

**Comment by lanvent** [comment]
请使用Role插件
