### ISSUE TITLE
在roles.json中添加了角色但是列表里不出现也无法使用

### ISSUE THREAD

**Issue by MGeorge01** [zhayujie/chatgpt-on-wechat#884]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
 
部署在railway，正常运行使用都没有问题，但是在roles.json中按格式添加了角色之后用指令$角色类型 所有查看列表发现没有自行添加的角色，输入$角色 {角色名}指令提示error角色不存在。我是在运行状态下修改的github中的代码，修改完之后railway有自动更新，但是很明显没有生效

**Comment by lanvent** [comment]
如果railway需要修改配置，需要删除主目录的Dockerfile
