### ISSUE TITLE
Error communicating with OpenAI

### ISSUE THREAD

**Issue by yuanzhiyong1999** [zhayujie/chatgpt-on-wechat#885]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
调用接口时出现连接不上的报错问题，我已经在别的代码测试过，可以连接openai接口

### 终端日志 (如有报错)

![image](https://user-images.githubusercontent.com/94682439/232705279-db34e565-06b5-4c63-b15c-232ece37b242.png)
这个是报错问题
![image](https://user-images.githubusercontent.com/94682439/232705353-52a06544-3089-4011-b604-2d6c04c7d729.png)
我在这里测试过没问题

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zivchen666** [comment]
![image](https://user-images.githubusercontent.com/66064612/232734275-fe04cdc6-2a44-4c1d-b3ca-e8946ce3ed42.png)
我的也是，以前的微信版本没碰到这个问题

**Comment by lanvent** [comment]
自行检查是否设置了proxy

**Comment by zivchen666** [comment]
> 自行检查是否设置了proxy

是config.json里面的proxy吗，这个是要自己搭代理么，几个月前玩这个好像直接启动就可以了。求指点~
