### ISSUE TITLE
tool插件消失

### ISSUE THREAD

**Issue by LINKlang** [zhayujie/chatgpt-on-wechat#893]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

在今天我git pull后，我发现tool用不了了，godcmd的插件列表里也没有tool了
![image](https://user-images.githubusercontent.com/116951234/232958344-ba91dd7f-9d5d-4b5f-8868-ef409ad0c79f.png)

### 终端日志 (如有报错)

```
[WARNING][2023-04-19 03:16:46][wechat_message.py:82] - [WX]get other_user_id failed: 'NickName'
[INFO][2023-04-19 03:16:47][wechat_channel.py:219] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
插件列表：
Godcmd_v1.0 999 - 已启用
Keyword_v0.1 900 - 已启用
Banwords_v1.0 100 - 未启用
Role_v1.0 0 - 已启用
Dungeon_v1.0 0 - 已启用
BDunit_v0.1 0 - 未启用
Hello_v0.1 -1 - 已启用
Finish_v1.0 -999 - 已启用
), receiver=filehelper

```

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( 3.8.10 )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by LINKlang** [comment]
还是我更新的方法错了，是直接打git pull就行了吧

**Comment by LINKlang** [comment]
这是plugins.json里的内容
![image](https://user-images.githubusercontent.com/116951234/232958896-e1e58a56-0155-445d-8288-2c33dc92bd43.png)

**Comment by Maddaxman** [comment]
应该要重装reqeirment  装新版插件的依赖

**Comment by LINKlang** [comment]
> 应该要重装reqeirment 装新版插件的依赖

请问怎么搞呢，求指教

**Comment by LINKlang** [comment]
> 应该要重装reqeirment 装新版插件的依赖

是直接pip3 install -r requirements.txt吗

**Comment by LINKlang** [comment]
> 应该要重装reqeirment 装新版插件的依赖

直接pip后出现以下内容，是报错吗

> Traceback (most recent call last):

>   File "/usr/bin/pip3", line 11, in <module>
>     load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
>     from pip._internal.cli.autocompletion import autocomplete
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
>     from pip._internal.cli.main_parser import create_main_parser
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
>     from pip._internal.cli import cmdoptions
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
>     from pip._internal.exceptions import CommandError
>   File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
>     from pip._vendor.six import iteritems
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
>     vendored("cachecontrol")
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
>     __import__(modulename, globals(), locals(), level=0)
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
>     class X509StoreFlags(object):
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
>     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
>     from apport.fileutils import likely_packaged, get_recent_crashes
>   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
>     from apport.report import Report
>   File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
>     import apport.fileutils
>   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
>     import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
>   File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
>     import requests
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
>     class X509StoreFlags(object):
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
>     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/pip3", line 11, in <module>
>     load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
>     from pip._internal.cli.autocompletion import autocomplete
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
>     from pip._internal.cli.main_parser import create_main_parser
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
>     from pip._internal.cli import cmdoptions
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
>     from pip._internal.exceptions import CommandError
>   File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
>     from pip._vendor.six import iteritems
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
>     vendored("cachecontrol")
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
>     __import__(modulename, globals(), locals(), level=0)
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
>     class X509StoreFlags(object):
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
>     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
>

**Comment by lanvent** [comment]
pip install pyOpenSSL --upgrade

**Comment by LINKlang** [comment]
> pip install pyOpenSSL --upgrade

在尝试以上命令后提示以下报错

> Traceback (most recent call last):
>   File "/usr/bin/pip", line 11, in <module>
>     load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
>     from pip._internal.cli.autocompletion import autocomplete
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
>     from pip._internal.cli.main_parser import create_main_parser
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
>     from pip._internal.cli import cmdoptions
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
>     from pip._internal.exceptions import CommandError
>   File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
>     from pip._vendor.six import iteritems
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
>     vendored("cachecontrol")
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
>     __import__(modulename, globals(), locals(), level=0)
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
>     class X509StoreFlags(object):
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
>     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
>     from apport.fileutils import likely_packaged, get_recent_crashes
>   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
>     from apport.report import Report
>   File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
>     import apport.fileutils
>   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
>     import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
>   File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
>     import requests
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
>     class X509StoreFlags(object):
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
>     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 11, in <module>
>     load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
>     from pip._internal.cli.autocompletion import autocomplete
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
>     from pip._internal.cli.main_parser import create_main_parser
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
>     from pip._internal.cli import cmdoptions
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
>     from pip._internal.exceptions import CommandError
>   File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
>     from pip._vendor.six import iteritems
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
>     vendored("cachecontrol")
>   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
>     __import__(modulename, globals(), locals(), level=0)
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
>     class X509StoreFlags(object):
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
>     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
>

**Comment by LINKlang** [comment]
> pip install pyOpenSSL --upgrade

运行chatgpt-on-wechat时还出现了新报错

> [ERROR][2023-04-23 12:03:15][plugin_manager.py:91] - Failed to import plugin tool: cannot import name 'build_model_params' from 'chatgpt_tool_hub.models' (unknown location)
> Traceback (most recent call last):
>   File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 88, in scan_plugins
>     self.loaded[plugin_path] = importlib.import_module(import_path)
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/root/chatgpt-on-wechat/plugins/tool/__init__.py", line 1, in <module>
>     from .tool import *
>   File "/root/chatgpt-on-wechat/plugins/tool/tool.py", line 4, in <module>
>     from chatgpt_tool_hub.apps import AppFactory
>   File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/apps/__init__.py", line 1, in <module>
>     from chatgpt_tool_hub.apps.load_app import load_app
>   File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/apps/load_app.py", line 6, in <module>
>     from chatgpt_tool_hub.models import build_model_params
> ImportError: cannot import name 'build_model_params' from 'chatgpt_tool_hub.models' (unknown location)
> [ERROR][2023-04-23 12:03:15][plugin_manager.py:156] - Plugin tool not found, but found in plugins.json
>
