### ISSUE TITLE
无法开启插件

### ISSUE THREAD

**Issue by TLMEMO** [zhayujie/chatgpt-on-wechat#894]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

我今天第一次拉取了这个项目，但是我发现无法使用#enablep 来开启插件，我分别试了sdwebui、tool和banwords，都提示插件开启失败。并且我注意到的一点是，在运行app.py时，最初加载的插件并不包含tool。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```
![捕获](https://user-images.githubusercontent.com/120395916/232980515-84baf45c-4501-4491-8893-1698c4b2c0ec.PNG)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python3 -V` )：  python3.9.0
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by Maddaxman** [comment]
重装一下optional requirment

**Comment by TLMEMO** [comment]
> 重装一下optional requirment

我已经试过重装依赖并且保持最新版本了，但是并不起作用

**Comment by hugo911** [comment]
这个看起来像是你的tool配置文件里字符搞错了，可能是某个配置后面少打了“，”

**Comment by TLMEMO** [comment]
> 这个看起来像是你的tool配置文件里字符搞错了，可能是某个配置后面少打了“，”

感谢，的确是我配置文件漏写了一个","，但是现在还有的问题就是sdwebui插件还是不能启用。
