### ISSUE TITLE
能够自定义开启进群、拍拍消息的开启吗，有一点扰人

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#895]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

能够自定义开启进群、拍拍消息的开启吗，有一点扰人，另外，json里设置里群的触发关键词，把@bot去除了，但是群里@bot还是会触发，配置如下：
<img width="414" alt="image" src="https://user-images.githubusercontent.com/31379908/232985907-7997774c-8f2d-4106-bf65-1ef0e37783f0.png">

**Comment by lanvent** [comment]
可以关闭Hello插件
