### ISSUE TITLE
角色切换插件的一些建议

### ISSUE THREAD

**Issue by 18515381698** [zhayujie/chatgpt-on-wechat#896]
角色切换插件简直太棒了，我非常喜欢这个功能。
在使用过程中，我想，如果可以加入以下字段的选配，可能会对角色扮演有更好的帮助。
1. temperature
2. top_p
3. frequency_penalty
4. presence_penalty

上述字段可能会影响chatgpt的回复内容，对部分角色可能产生非常有趣的影响。希望作者大大在插件中提供支持~

**Comment by 6vision** [comment]
现在可以使用LinkAI的服务，每个群可以绑定一个应用，应用可以设置应用设定、温度、插件、知识库等，见#2146
