### ISSUE TITLE
扫码登入是出现出错误“App startup failed!”

### ISSUE THREAD

**Issue by xuyufenghz** [zhayujie/chatgpt-on-wechat#897]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

使用python3 app.py后进行扫码登入出现报错
![图片](https://user-images.githubusercontent.com/41050833/233079018-da97e4c4-07c6-443c-ba40-892af9dbf77f.png)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Ubuntu 22.04.1 LTS
 - Python版本  ( 执行 `python3 -V` )：  3.10.6
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

**Comment by evachxji** [comment]
我今天也突然出现了同样的问题，在railway上，之前一直是可以正常使用的

**Comment by lanvent** [comment]
可能被微信限制了

**Comment by evachxji** [comment]
老哥，我破案了。我昨天把微信号解绑了银行卡，并注销了微信支付。网页版登录是要求用户进行微信实名认证的，今天重新绑定了银行卡，完成钱包实名认证后，就可以正常登录了

**Comment by evachxji** [comment]
建议作者在readme里提醒一下其他人，因为不少人都是拿自己的微信小号去做机器人的。难免会有没做钱包实名认证，导致网页版无法登录的现象（而且控制台也没有给出足够明显的提示）
