### ISSUE TITLE
新账号无法登陆

### ISSUE THREAD

**Issue by LINKlang** [zhayujie/chatgpt-on-wechat#898]
新注册的账号无法使用，是只支持微信不支持WeChat吗
![image](https://user-images.githubusercontent.com/116951234/233081906-05890c91-1cae-423b-976d-f49c8c37773b.png)

**Comment by dqzboy** [comment]
WeChat没有网页版

**Comment by LINKlang** [comment]
> WeChat没有网页版

啊，不会吧，那itchat可以模拟成其他设备吗

**Comment by lanvent** [comment]
可尝试公众号等channel

**Comment by LittleMinWu** [comment]
我的一直扫描不起 显示network disconnected 有没有大佬帮忙解决一下 非常感谢！
