### ISSUE TITLE
docker 部署环境失败 docker-compose up -d

### ISSUE THREAD

**Issue by heyi-byte** [zhayujie/chatgpt-on-wechat#907]
![image](https://user-images.githubusercontent.com/52826441/233324776-d97bf3a3-c101-4402-9e95-7e8153c2acb0.png)

**Comment by lurenj** [comment]
我是使用nas 的docker 组件部署的，也是部署报错，我报的是另外一个错，如下图所示：
![image](https://user-images.githubusercontent.com/31582785/233395668-b8f26ba5-5e7e-4a3a-94c3-c9cf386ab277.png)
还有一个问题，就是我设置key 一直设置不成功，不管是通过参数配置还是在config.json中配置。都不行。

**Comment by lanvent** [comment]
@lurenj 检查json文件

**Comment by LiberatorHg** [comment]
> ![image](https://user-images.githubusercontent.com/52826441/233324776-d97bf3a3-c101-4402-9e95-7e8153c2acb0.png)

我和你一模一样的报错

**Comment by LiberatorHg** [comment]
有解决办法吗

**Comment by lanvent** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/pkgs/container/chatgpt-on-wechat
