### ISSUE TITLE
微信扫码后，为啥会提示在新设备登陆呢？

### ISSUE THREAD

**Issue by ziseyouyudefengzi** [zhayujie/chatgpt-on-wechat#91]
问题：用已登录的微信扫码登陆后，微信提示在异地登录、新设备登录，这个是什么原理呢？

**Comment by shuangzishuai** [comment]
我也遇到了同样的问题

**Comment by shuangzishuai** [comment]
扫二维码提示异地登录后微信就没有任何反应了，命令号中能看到Start auto replying

**Comment by zhayujie** [comment]
提示异地登录手机确认就好了

**Comment by zhayujie** [comment]
> 扫二维码提示异地登录后微信就没有任何反应了，命令号中能看到Start auto replying

这样就ok了，发消息触发试试

**Comment by letmeseeseeyourname** [comment]
> 
我也遇到同样的问题，如果要发消息的话，发给谁呢？没有出现对话框

**Comment by zhayujie** [comment]
> > 
> 
> 我也遇到同样的问题，如果要发消息的话，发给谁呢？没有出现对话框

随便找个好友

**Comment by ziseyouyudefengzi** [comment]
> 

我是怕会有微信安全问题，怕被盗号，因为我看怎么会提示在其他地方登录呢。
