### ISSUE TITLE
使用一段时间后控制台输出LOG OUT，微信连接断开。

### ISSUE THREAD

**Issue by evachxji** [zhayujie/chatgpt-on-wechat#916]
无论是在本地部署，还是在railway上，运行1~3天左右就会自动登出。这是微信那边的问题吗，被检测到，然后把我账号踢出了登录吗？
有没有朋友跟我遇到一样的状况？我用的是自己一个不常用的微信小号。大号不敢登，怕被封

**Comment by cshuo** [comment]
同.

**Comment by lanvent** [comment]
see #879 ， 可能是网络问题，建议还是定期重启下

**Comment by weijianfan** [comment]
我也发现如此，以前没这问题，这两天开始出现

**Comment by 602753090** [comment]
我也是

**Comment by Meng-de-Cao** [comment]
俺也一样，莫名退出了，也不知道是啥情况

**Comment by huasheng28** [comment]
同样的问题，这几天已经重新登录四五次了

**Comment by lanvent** [comment]
可能是网络问题，也有可能是微信服务器又加入了某些检测。因为一直在本地部署，我没遇到过此类情况，欢迎在环境变量中将"debug"设置为true，并把登出前一段时间的日志发送给我们，这对我们分析问题原因有很大的帮助。

**Comment by Meng-de-Cao** [comment]
在哪里设置日志级别呢？请告知




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 使用一段时间后控制台输出LOG OUT，微信连接断开。 (Issue #916)





 
可能是网络问题，也有可能是微信服务器又加入了某些检测。因为一直在本地部署，我没遇到过此类情况，欢迎在环境变量中将"debug"设置为true，并把登出前一段时间的日志发送给我们，这对我们分析问题原因有很大的帮助。

**Comment by lanvent** [comment]
railway中增加环境变量  debug=true， 或在根目录的`config.json`中添加 "debug": true

**Comment by Meng-de-Cao** [comment]
我把日志级别设置为了debug，在log out之前没有打印任何异常信息。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 使用一段时间后控制台输出LOG OUT，微信连接断开。 (Issue #916)





 
railway中增加环境变量  debug=true， 或在根目录的config.json中添加 "debug": true

**Comment by lanvent** [comment]
请问从Bot处理最后一条消息到LOGOUT经过了多长的时间

**Comment by Meng-de-Cao** [comment]
日志没有详细记录时间，我估计在两三个小时到十二个小时之间


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] 使用一段时间后控制台输出LOG OUT，微信连接断开。 (Issue #916)





 
请问从Bot处理最后一条消息到LOGOUT经过了多长的时间

**Comment by cshuo** [comment]
FYI. 供参考:
docker 环境变量开启了 debug = true, 三天没掉线了.  😂

**Comment by zhenda-hub** [comment]
同， debug开了。日志没有记录准确时间，内容如下（itchat内记录的log）：
[INFO][2023-05-03 07:47:38][chat_gpt_bot.py:49] - [CHATGPT] query=很好
[INFO][2023-05-03 07:47:39][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 谢谢！如有其他问题，请随时提出。), receiver=@e980c7cea5b422895d1edca7b6e813edfd592c5293b44b23a493fa0728417eae
Unexpected sync check result: window.synccheck={retcode:"1101",selector:"0"}
LOG OUT!

**Comment by huasheng28** [comment]
服务器本地部署（不使用railway时），出现一次error，但并不是每次掉都会出现

/usr/local/python3/lib/python3.8/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
/usr/local/python3/lib/python3.8/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
LOG OUT!

**Comment by evachxji** [comment]
以下是debug日志

[DEBUG][2023-04-28 07:38:21][chat_channel.py:264] - Worker return success, session_id = @@52cb54b22da38ed7114ea0810f99eab2a0646312671abc1add0b27a01ed01387
Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
LOG OUT!

**Comment by H-RY** [comment]
我也遇到了这个问题
Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
LOG OUT!
