### ISSUE TITLE
管理员认证失败

### ISSUE THREAD

**Issue by kongbaiwubai** [zhayujie/chatgpt-on-wechat#918]
能请问下为什么我的管理验证无法成功，无论是给他设置密码还是随机密码都会显示认证失败

**Comment by LINKlang** [comment]
请问能发下日志吗

**Comment by huaji1992** [comment]
[INFO][2023-04-28 03:48:06][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
认证失败), receiver=@281583a0d2f90e1f6db3dbec29274961

**Comment by huaji1992** [comment]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/30308645/235049771-534fdf2f-bb5c-4109-97ce-c0a787051be3.png">

**Comment by huaji1992** [comment]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/30308645/235049813-b028e132-bc99-44b9-865d-92be8ac5b735.png">

**Comment by chaomarks** [comment]
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/93130581/87958ee6-55d1-4b10-8b24-c0c17aceb3eb)
wod我的也是这个问题，都给它设置密码了，还自己创建了临时密码

**Comment by chaomarks** [comment]
> <img alt="image" width="618" src="https://user-images.githubusercontent.com/30308645/235049813-b028e132-bc99-44b9-865d-92be8ac5b735.png">

找到问题了，映射目录是这个：/app/plugins/godcmd/config.json，教程少了一个godcmd
