### ISSUE TITLE
运行提示 No module named 'itchat'

### ISSUE THREAD

**Issue by wupeizhong** [zhayujie/chatgpt-on-wechat#92]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等：

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by luck-zzb** [comment]
解决了吗 我也有这个问题

**Comment by wupeizhong** [comment]
> 解决了吗 我也有这个问题

没

**Comment by zhayujie** [comment]
执行以下命令看看

pip3 -V
pip3 show itchat-uos

**Comment by wupeizhong** [comment]
> 
![image](https://user-images.githubusercontent.com/85746360/217780585-82b9597d-0b18-4304-bca5-cac72ad3cf8e.png)
