### ISSUE TITLE
建议对前端用户做限制

### ISSUE THREAD

**Issue by axzaxza** [zhayujie/chatgpt-on-wechat#921]
比如对接了公众号，只要一个人知道这件事，就会一传十十传百，很快这个公众号被玩废了，建议做出限制，比如星标用户组可用。

**Comment by JS00000** [comment]
因为未认证公众号没有用户管理接口权限，因此需要有一些非微信官方途径去实现用户的分类。我建议是可以写一个plugin过滤一下用户，授权用户正常服务，非授权用户返回指定文本消息。用户可以通过输入邀请码来变成授权用户。邀请码可以完全由部署者生成，也可以考虑使用一些增长策略，比如高级授权用户可以生成一定数量，或者关注了x时间以上的用户每隔y时间可以生成z个，用来控制用户增长速度。如果有能力你可以帮助实现一下。
