### ISSUE TITLE
wechaty网关启动后本地curl不通导致机器人启动失败

### ISSUE THREAD

**Issue by lsCoding666** [zhayujie/chatgpt-on-wechat#923]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

简要说明、截图、复现步骤等，也可以是需求或想法
https://github.com/zhayujie/chatgpt-on-wechat/pull/244
中提到，设置了一个环境变量，讲端口指定在9001。但是我这里已经占用了这个端口了，所以我吧环境变量设置为9999.
重点来了，docker网关容器启动后，config.json channel切换到wxy，并且设置token为之前设置的uuid，修改channel/wechat/wechaty_channel.py。os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "127.0.0.1:9999"。以上修改如图所示
![image](https://user-images.githubusercontent.com/73888354/233677061-b5ed4fe0-edf2-48e7-b18d-46632f98c584.png)
![image](https://user-images.githubusercontent.com/73888354/233677184-d58aad2d-88a1-4bfb-915d-1ed5d9a19097.png)
![image](https://user-images.githubusercontent.com/73888354/233677287-9c2dd759-eb92-43ea-bd8a-caadb0601591.png)

启动后报错
![image](https://user-images.githubusercontent.com/73888354/233676775-0099a99e-029a-4f41-bc20-81802391b04d.png)
报错后发现，他这里提到的是网络 `not good`。于是curl 127.0.0.1:9999返回
![image](https://user-images.githubusercontent.com/73888354/233677578-30ff8d80-c4b2-4cdf-8ddb-fcc561dfa4a6.png)
而不是
![image](https://user-images.githubusercontent.com/73888354/233677627-1a66562e-a6bb-469d-9e48-c908ae450981.png)

说明docker确实跑在9999上了，但是没返回是怎么回事

对了 网关容器启动正常 没报错
![image](https://user-images.githubusercontent.com/73888354/233679013-ba64aca1-f346-4ff6-87e5-ce79ed3c0e75.png)

docker启动命令
```
docker run -ti   --name wechaty_puppet_service_token_gateway   --rm   -e WECHATY_LOG   -e WECHATY_PUPPET   -e WECHATY_PUPPET_PADLOCAL_TOKEN   -e WECHATY_PUPPET_SERVER_PORT   -e WECHATY_TOKEN   -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT"   wechaty/wechaty:1.11
```
使用1.11的原因是1.11开始才支持arm服务器
### 环境

 - 操作系统类型  (Mac/Windows/Linux)： ubuntu 20.04 arm64架构
 - Python版本  ( 执行 `python3 -V` )：  Python 3.8.10
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

**Comment by lsCoding666** [comment]
访问https://api.chatie.io/v0/hosties/puppet_padlocal_xxx ip显示0.0.0.0
服务器在国外 韩国甲骨文arm机

**Comment by lsCoding666** [comment]
初步判断是wechaty版本问题 在amd64的服务器上测试 使用0.65版本正常 现在正在装1.11版本测试

**Comment by lsCoding666** [comment]
确实 换了1.11版本后就会失败 是版本的问题。兼容性 不太好

**Comment by yhfgyyf** [comment]
肯定是wechaty版本问题，之前我试过好久，不是0.65版本就会失败
