### ISSUE TITLE
tool没找到的问题

### ISSUE THREAD

**Issue by AmaneSuzu** [zhayujie/chatgpt-on-wechat#924]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

昨天刚刚研究这个，使用的是railway部署，在使用中修改了/tool/config.json（删除了.template后缀）中的代码（不知是否有误），但是却依旧找不到tool，不知为何？或者是否需要一些其他操作呢？请指点一下。

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]

![图片](https://user-images.githubusercontent.com/92219348/233683569-a7d0ea4e-b151-434a-ab1a-b261331b5ada.png)
![图片](https://user-images.githubusercontent.com/92219348/233683660-80a58b7c-be9c-489b-914d-85b5d04fb409.png)

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by AmaneSuzu** [comment]
![图片](https://user-images.githubusercontent.com/92219348/233687711-a02e733a-d63c-4967-9ced-998659fa6682.png)

**Comment by goldfishh** [comment]
pull chatgpt on wechat  代码 并且更新tool-hub到0.4.1

**Comment by AmaneSuzu** [comment]
> pull chatgpt on wechat 代码 并且更新tool-hub到0.4.1

大佬能详细指点一下吗，我用的是railway一键部署（过些天可能考虑本地部署），要在哪里pull呢？并且tool-hub如何更新呢？

**Comment by lanvent** [comment]
好像是我的锅， 得重新发个镜像

**Comment by AmaneSuzu** [comment]
> 好像是我的锅， 得重新发个镜像

好的，感谢大佬指点。

**Comment by AmaneSuzu** [comment]
> 

大佬，我看到项目有更新了，请问是修复这个问题了吗？

**Comment by lanvent** [comment]
是的，等最新镜像自动打包好你试一下~

**Comment by AmaneSuzu** [comment]
> 是的，等最新镜像自动打包好你试一下~

好的，感谢大佬
