### ISSUE TITLE
建议作者在readme里提醒下，微信去钱包里做实名认证，才可登录网页版

### ISSUE THREAD

**Issue by evachxji** [zhayujie/chatgpt-on-wechat#925]
建议作者在readme里提醒一下其他人，因为不少人都是拿自己的微信小号去做机器人的。难免会有没做钱包实名认证，导致网页版无法登录的现象（而且控制台也没有给出足够明显的提示）

_Originally posted by @evachxji in https://github.com/zhayujie/chatgpt-on-wechat/issues/897#issuecomment-1518520866_

**Comment by zhayujie** [comment]
好的，这个readme里和faqs中都已经有了，可能不太明显
<img width="919" alt="image" src="https://user-images.githubusercontent.com/26161723/233777227-02975b37-9483-4472-8ad3-64a1a2d0aa64.png">

**Comment by evachxji** [comment]
好的，直接用的railway deploy，没往下看的这么仔细
