### ISSUE TITLE
我买的国外的服务器  但是不行 求大佬救救

### ISSUE THREAD

**Issue by lubenwei17998** [zhayujie/chatgpt-on-wechat#927]
Login successfully as 很遗憾不是吗
[INFO][2023-04-22 18:14:55][wechat_channel.py:144] - Wechat login success, user_id: @500d02354327679966bf212052910d5362e206db2606bbcc575f3da609aa978b, nickname: 很遗憾不是吗
Start auto replying.
[INFO][2023-04-22 18:15:03][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-04-22 18:15:04][chat_gpt_bot.py:56] - [CHATGPT] query=你好
[WARNING][2023-04-22 18:15:10][chat_gpt_bot.py:152] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022F7E638990>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[INFO][2023-04-22 18:15:10][wechat_channel.py:219] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@60dc49417e62d19d7c831dd5336ba83910564c8ff79a724fcc518d34b404fd40

**Comment by zhayujie** [comment]
是哪个地区的服务器， 不要配置proxy参数哈

**Comment by lubenwei17998** [comment]
> 是哪个地区的服务器， 不要配置proxy参数哈

首尔  呜呜呜V了人家50 人也消失了 还没部署上  大哥有空么
