### ISSUE TITLE
Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")

### ISSUE THREAD

**Issue by Lan0618** [zhayujie/chatgpt-on-wechat#93]
云服务器，wget能正常打开网页微信登录，Python3.8.1

**Comment by zhayujie** [comment]
是国内服务器吗？如果不是的话网络会不通

如果是国内的话看看这个 https://github.com/littlecodersh/ItChat/issues/386

**Comment by Lan0618** [comment]
> 是国内服务器吗？如果不是的话网络会不通
> 
> 如果是国内的话看这个[littlecodersh/ItChat#386](https://github.com/littlecodersh/ItChat/issues/386)

是国内的，修改requests.get(config.BASE_URL, verify=False)也无效🫣

**Comment by yuqinpeng1992** [comment]
我也是这个问题，有解决的大佬吗？

**Comment by yuqinpeng1992** [comment]
https://blog.csdn.net/qq78442761/article/details/126085578
按照这个博客重装openssl和python 问题解决

**Comment by yuqinpeng1992** [comment]
@Lan0618 @zhayujie

**Comment by shaxao** [comment]
我也是遇到这个问题，上述解决方案都试过还是不行
