### ISSUE TITLE
 docker 里群语音没不行  

### ISSUE THREAD

**Issue by 1183011789** [zhayujie/chatgpt-on-wechat#930]
SPEECH_RECOGNITION: "true"
      GROUP_SPEECH_RECOGNITION: "true"

docker 里群语音没不行  
![image](https://user-images.githubusercontent.com/30824602/233816811-89abef1a-eb89-45e3-bf99-b4396531be6c.png)

**Comment by lanvent** [comment]
群聊语音触发，需要匹配触发词前缀

**Comment by 1183011789** [comment]
发的语音怎么匹配前缀？

**Comment by 1183011789** [comment]
> 群聊语音触发，需要匹配触发词前缀

发的语音怎么匹配前缀？

**Comment by 1183011789** [comment]
> 群聊语音触发，需要匹配触发词前缀

我用的docker-compose.yaml

**Comment by lanvent** [comment]
私聊语音识别后不需要匹配前缀，群聊语音识别后需要匹配前缀才会处理，经过一些讨论，这个设置符合大多数的使用场景。也欢迎贡献代码，提供配置项。
