### ISSUE TITLE
经常出现聊天卡住的问题，，咋回事，是railway的还是openai的问题呢

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#931]
![图片](https://user-images.githubusercontent.com/29570378/233818335-79a96d0f-ea0c-44ab-b2c8-c0654eae40bf.png)

**Comment by lanvent** [comment]
都有可能，如果不想单个会话被阻塞可以把`concurrency_in_session`设置成大于1的项，但回答可能乱序
