### ISSUE TITLE
对接公众号，出现token无法验证通过的错误。

### ISSUE THREAD

**Issue by luomaofu** [zhayujie/chatgpt-on-wechat#934]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [x] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp_service(公众号, 服务号)

### 复现步骤 🕹

对接公众号，出现token无法验证通过的错误。

### 问题描述 😯

公众号的参数均已设置并正确的填入到config.json中。
但是，公众号token验证失败。
验证的时候，终端出现 404错误。
另外项目部署以iptables 转发 80端口请求到8080的方式。

### 终端日志 📒

```log
[INFO][2023-04-23 11:59:31][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-04-23 11:59:31][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-04-23 11:59:31][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-04-23 11:59:31][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-04-23 11:59:31][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-04-23 11:59:31][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
chatgpt-tool-hub version: 0.4.1
[INFO][2023-04-23 11:59:32][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-04-23 11:59:32][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-04-23 11:59:32][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-04-23 11:59:32][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-04-23 11:59:32][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-04-23 11:59:32][godcmd.py:181] - [Godcmd] 因未设置口令，本次的临时口令为3589。
[INFO][2023-04-23 11:59:32][godcmd.py:196] - [Godcmd] inited
[INFO][2023-04-23 11:59:32][keyword.py:40] - [keyword] {}
[INFO][2023-04-23 11:59:32][keyword.py:42] - [keyword] inited.
[INFO][2023-04-23 11:59:32][role.py:69] - [Role] inited
[INFO][2023-04-23 11:59:32][dungeon.py:56] - [Dungeon] inited
[INFO][2023-04-23 11:59:32][hello.py:23] - [Hello] inited
[INFO][2023-04-23 11:59:32][finish.py:23] - [Finish] inited
http://0.0.0.0:8080/
162.62.80.57:13738 - - [23/Apr/2023 11:59:49] "HTTP/1.1 GET /" - 404 Not Found


```

**Comment by lanvent** [comment]
你填写的网址格式是 http://xxx.com/wx吗

**Comment by luomaofu** [comment]
sorry。居然还有个 /wx的后缀。我大意了。问题解决了。

**Comment by huaji1992** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/30308645/235405142-80af2eb7-83ad-43ca-b36f-e101a5ac594e.png">
是指这里要有个wx？

**Comment by KunBoy5240** [comment]
> 您填写的网址格式是http://xxx.com/wx吗

我填写了‘/wx’的后缀，但是我使用的docker部署，网络模式为host，但是还是token验证失败，后台打印消息是403
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/97332061/292721c6-9264-4676-b88f-514127437a2c)

**Comment by Smileye-v** [comment]
大哥，这个问题你解决了吗

**Comment by Z-XINY** [comment]
wechatmp_service的话试试看公众号开启客服功能

**Comment by cbaoox** [comment]
帮我看下，后台没有报错，但是公众号里服务器配置一直提示超时，是端口的问题吗？
![WechatIMG184](https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/2d8b8472-0f63-4072-97c6-e028197cd871)
![WechatIMG183](https://github.com/zhayujie/chatgpt-on-wechat/assets/22851280/1f3a8597-7542-429c-bd15-154a3d2dc9e7)
