### ISSUE TITLE
关于在群聊中AI回复并  @用户  的一个小建议

### ISSUE THREAD

**Issue by Li-Eternally** [zhayujie/chatgpt-on-wechat#937]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

将AI在群聊中 @用户名 和问题的回答进行换行隔开

### 举例

![image](https://user-images.githubusercontent.com/128838111/233911304-5441bae0-cd09-41da-9e87-a62893adcdf3.png)

### 动机

像这样与AI回答的问题隔开，聊天效果会不会更好一些

**Comment by Moomook** [comment]
建议回复时把用户的原问题放在回答上面，问题和答案换行隔开，群聊时才容易知道回答的是哪个问题

**Comment by Li-Eternally** [comment]
> 建议回复时把用户的原问题放在回答上面，问题和答案换行隔开，群聊时才容易知道回答的是哪个问题

简短点的问题可以，但如果用户的问题很长恐怕就不行

**Comment by Zhaoyi-Yan** [comment]
@Li-Eternally 看上去应该是改：[reply_text = "@" + context["msg"].actual_user_nickname + " " + reply_text.strip()](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/chat_channel.py#L220) 改成 `reply_text = "@" + context["msg"].actual_user_nickname + " \n" + reply_text.strip()`就行了吧

**Comment by Li-Eternally** [comment]
> @Li-Eternally看上去应该是修改：[reply_text = "@" + context["msg"].actual_user_nickname + " " + reply_text.strip()](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/chat_channel.py#L220)修改`reply_text = "@" + context["msg"].actual_user_nickname + " \n" + reply_text.strip()`就进行了吧

感谢指导，确实有效果

**Comment by 6vision** [comment]
已优化
