### ISSUE TITLE
建议增加私聊黑白名单、私聊限制使用次数机制

### ISSUE THREAD

**Issue by zongshuai818** [zhayujie/chatgpt-on-wechat#938]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

现在已有群聊白名单机制，建议增加私聊的黑白名单机制

### 举例

私聊限制：{“微信名”: 每日限制总对话轮数, .....}
私聊黑名单：{"黑名单微信名": [微信号1,微信号2,.....]}

**Comment by JinHanLei** [comment]
支持

**Comment by Zhaoyi-Yan** [comment]
我看代码好像备注是说itchat是每次分配随机的id？所以私聊只能获取私聊的昵称貌似？微信号是没法获取的？毕竟即使你拉他黑名单了，换个昵称就完事儿了

**Comment by qcoltma** [comment]
> 我看代码好像备注是说itchat是每次分配随机的id？所以私聊只能获取私聊的昵称貌似？微信号是没法获取的？毕竟即使你拉他黑名单了，换个昵称就完事儿了

其实做到限制昵称也够了，一般人都不知道的。

**Comment by wangjueszu** [comment]
> > 我看代码好像备注是说itchat是每次分配随机的id？所以私聊只能获取私聊的昵称貌似？微信号是没法获取的？毕竟即使你拉他黑名单了，换个昵称就完事儿了
> 
> 其实做到限制昵称也够了，一般人都不知道的。

有解决么？我也尝试修改代码，添加昵称进去判断。但是找不到何时的位置，不清楚receiver是哪个时间获得了用户信息，然后又怎样储存去使用的。

**Comment by wangjueszu** [comment]
我解决了，开心

**Comment by 6vision** [comment]
已有相关PR，见#1538
