### ISSUE TITLE
微信中GPT回复的内容超过单条消息字数限制可否截断分成多条发送

### ISSUE THREAD

**Issue by vlux** [zhayujie/chatgpt-on-wechat#939]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

微信公众号和企业微信
谢谢！

**Comment by lanvent** [comment]
目前公众号超过字数是截断分条发送的，个人微信没有测试字数上限，你遇到了超过上限的情况吗？

**Comment by vlux** [comment]
> 目前公众号超过字数是截断分条发送的，个人微信没有测试字数上限，你遇到了超过上限的情况吗？

抱歉我这边可能开错issue，我是部署了作者的bot-on-anything在企业微信，正常回复没有问题，当回复内容过多时，后台log里显示收到了GPT的全文，但是企业微信里只收到了一条很长的信息有截断，没有收到后续的内容

**Comment by lanvent** [comment]
好的，目前本项目也已准备支持企业微信应用号，正在合并中 #936 。 字数上限的问题，在合并时我会测试。

**Comment by vlux** [comment]
> 好的，目前本项目也已准备支持企业微信应用号，正在合并中 #936 。 字数上限的问题，在合并时我会测试。

感谢大佬，现阶段测试的是让GPT写一段代码，后台log中是全的，企业微信内收到的是截断的，有搜到这个[回复](https://developers.weixin.qq.com/community/develop/doc/0008ea9ecc4db059479aac38d51400)

**Comment by lanvent** [comment]
已合入master
