### ISSUE TITLE
给机器人发送语音，如果机器人回复语音就好了，但现在是回复wav，不清楚能否实现

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#942]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

给朋友发一句语音，回复语音就好。如果朋友回复一个语音文件，还要下载，然后再用第三方音频播放器打开，，这也太不方便了。

不清楚能不能模拟“用户录入语音”的操作，但实际上是直接文字转语音~

### 举例

给朋友发一句语音，回复语音就好。如果朋友回复一个语音文件，还要下载，然后再用第三方音频播放器打开，，这也太不方便了。

不清楚能不能模拟“用户录入语音”的操作，但实际上是直接文字转语音~

**Comment by lanvent** [comment]
默认的网页版微信 itchat 不支持发送语音，公众号、企业微信应用号等支持发送语音
