### ISSUE TITLE
给订阅号发送图片，订阅号无回复

### ISSUE THREAD

**Issue by MastXu** [zhayujie/chatgpt-on-wechat#946]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

现象：给订阅号发送图片，订阅号无回复。

### 问题描述 😯

现象：给订阅号发送图片，订阅号无回复。
已完成：
1. 已按照 https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechatmp/README.md 中的推荐设置修改了配置项；
2. 给订阅号发送文字 “画个猫和狗的图”，可以接受到一张包含猫和狗的图片；
3. 文字交流正常；

### 终端日志 📒

```[INFO][2023-04-25 11:25:55][passive_reply.py:100] - [wechatmp] Request 1 from o4TI36tkSVPU53wlY92-IwGeCRkw 24086080543134233 162.62.81.123:5812
#reset
[INFO][2023-04-25 11:25:55][wechatmp_channel.py:83] - [wechatmp] text cached, receiver o4TI36tkSVPU53wlY92-IwGeCRkw
[INFO]
会话已重置
[INFO][2023-04-25 11:25:55][passive_reply.py:154] - [wechatmp] Request 1 do send to o4TI36tkSVPU53wlY92-IwGeCRkw 24086080543134233: #reset
[INFO]
会话已重置
[INFO][2023-04-25 11:31:48][passive_reply.py:100] - [wechatmp] Request 1 from o4TI36tkSVPU53wlY92-IwGeCRkw 24086082752744670 162.62.81.123:28294
tmp/SBr3nCyk_6MxnvjER7UvWcnOolbKLG2ROCbjQZuLz96Ggsl4kvR0kPyNKLfpVrGw.png
```

**Comment by lanvent** [comment]
公众号支持收发图片的能力，但默认的处理逻辑不包括对收到图片的处理。 目前 #770 中的插件支持处理图片。
