### ISSUE TITLE
在config.json中修改model:'gpt-4'提示报错

### ISSUE THREAD

**Issue by vlux** [zhayujie/chatgpt-on-wechat#947]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

将config.json中的'model'从'gpt-3.5-turbo'改成'gpt-4'，提示报错

### 问题描述 😯

如上

### 终端日志 📒

```log
http://0.0.0.0:80/
[INFO][2023-04-25 04:23:57][passive_reply.py:100] - [wechatmp] Request 1 from oIGM05wFcuOZZWUggv3p1dIJBKmI 24086125794982479 162.62.81.123:27352
Which gpt model are you using
[INFO][2023-04-25 04:23:57][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-04-25 04:23:57][chat_gpt_bot.py:48] - [CHATGPT] query=Which gpt model are you using
[WARNING][2023-04-25 04:23:57][chat_gpt_bot.py:141] - [CHATGPT] Exception: The model: `gpt-4` does not exist
[INFO][2023-04-25 04:23:57][wechatmp_channel.py:83] - [wechatmp] text cached, receiver oIGM05wFcuOZZWUggv3p1dIJBKmI
[ERROR]
我现在有点累了，等会再来吧
```

**Comment by lanvent** [comment]
请问你拥有gpt-4 api的使用权限吗

**Comment by vlux** [comment]
明白了，感谢两位！
