### ISSUE TITLE
服务号发送画图的请求不能回复图片，提示上传图片失败，必须要认证才能回复图片吗

### ISSUE THREAD

**Issue by xiaohan231** [zhayujie/chatgpt-on-wechat#948]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

发送：画一只猫

### 问题描述 😯

[ERROR][2023-04-25 06:50:48][wechatmp_channel.py:117] - [wechatmp] upload image failed: Error code: 48001, message: api unauthorized rid: 64477847-1e051de9-7b0f0ffb

### 终端日志 📒

[INFO][2023-04-25 06:50:38][passive_reply.py:100] - [wechatmp] Request 1 from oMqlh6bC5pAbdJZzPU8s1rptgYQk 24086257862090352 172.29.0.1:33062
画一只猫
[INFO][2023-04-25 06:50:38][open_ai_image.py:22] - [OPEN_AI] image_query=一只猫
[INFO][2023-04-25 06:50:43][passive_reply.py:100] - [wechatmp] Request 2 from oMqlh6bC5pAbdJZzPU8s1rptgYQk 24086257862090352 172.29.0.1:34656
画一只猫
[INFO][2023-04-25 06:50:44][open_ai_image.py:29] - [OPEN_AI] image_url=https://oaidalleapiprodscus.blob.core.windows.net/private/org-QFlh1GLBPklYieDsASbQi6lf/user-TyBk34DQXMBJCtAkw9sxubmx/img-J0JJ19VsgMyDmWnRev6emkrB.png?st=2023-04-25T05%3A50%3A44Z&se=2023-04-25T07%3A50%3A44Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-04-25T06%3A41%3A25Z&ske=2023-04-26T06%3A41%3A25Z&sks=b&skv=2021-08-06&sig=pzjzu4mMGoq/f3gG891aiNEIYKg8KJTOb7bBrB0RM94%3D
[ERROR][2023-04-25 06:50:48][wechatmp_channel.py:117] - [wechatmp] upload image failed: Error code: 48001, message: api unauthorized rid: 64477847-1e051de9-7b0f0ffb
[INFO][2023-04-25 06:50:48][passive_reply.py:100] - [wechatmp] Request 3 from oMqlh6bC5pAbdJZzPU8s1rptgYQk 24086257862090352 172.29.0.1:34672
画一只猫
[INFO][2023-04-25 06:50:48][open_ai_image.py:22] - [OPEN_AI] image_query=一只猫
[INFO][2023-04-25 06:50:54][open_ai_image.py:29] - [OPEN_AI] image_url=https://oaidalleapiprodscus.blob.core.windows.net/private/org-QFlh1GLBPklYieDsASbQi6lf/user-TyBk34DQXMBJCtAkw9sxubmx/img-KgvmGrWOG0J8UaUlCEN6LHCa.png?st=2023-04-25T05%3A50%3A54Z&se=2023-04-25T07%3A50%3A54Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-04-25T06%3A49%3A14Z&ske=2023-04-26T06%3A49%3A14Z&sks=b&skv=2021-08-06&sig=fdmWhRBzPDy0T3Kx5MvtssmmsvAHpse23v7bBMKQV0k%3D
[ERROR][2023-04-25 06:50:55][wechatmp_channel.py:117] - [wechatmp] upload image failed: Error code: 48001, message: api unauthorized rid: 6447784f-17838667-22e1f00d

**Comment by lanvent** [comment]
```
[ERROR][2023-04-25 06:50:55][wechatmp_channel.py:117] - [wechatmp] upload image failed: Error code: 48001, message: api unauthorized rid: 6447784f-17838667-22e1f00d
```
一般是配置填错了，具体是什么错误请配合搜索引擎

**Comment by xiaohan231** [comment]
好像是非认证服务号的原因，永久素材管理接口和临时素材管理接口权限两个都没有

**Comment by lanvent** [comment]
未认证支持前者

**Comment by xiaohan231** [comment]
企业服务号不行，没有认证两个权限都是没有的，我又重新注册了一个个人订阅号，这个没问题了

**Comment by lanvent** [comment]
原来企业服务号还有这个限制，感谢补充
