### ISSUE TITLE
希望弄一个railway调试代码教程

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#952]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在railway运行程序

### 问题描述 😯

本地调试会由于网络原因，不好弄。如果railway部署后，会自动fork代码，然后我调试，在fork的代码修改。但是运行的时候，仍旧是运行主repo的代码，现在没法调试了。我看了一下，好像是因为railway的时候，build的是该项目的docker导致的。
![图片](https://user-images.githubusercontent.com/29570378/234236724-271911d4-53b4-420f-8839-3c65a8839961.png)

因为没有啥docker的经验，所以我该怎么用railway进行调试呢？

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
你可以把Dockerfile删除，这样build的是你项目的代码。或者在Dockerfile里把from里的地址改成 ghcr.io/username/repo:master ，把镜像改成你的

**Comment by Zhaoyi-Yan** [comment]
不过好像一个问题是，因为我的名字是有大写字母，导致ghcr.io推送不上去貌似。ghcr.io默认是github的username吧

**Comment by lanvent** [comment]
可使用前一种方法。 后者你需要检查你项目主页右侧的packages内是否生成了镜像，有时候会出现生成了镜像但workflow之后的某一步报错了也有可能，具体可以点进git actions里查看

**Comment by Zhaoyi-Yan** [comment]
我刚刚试了一下，删除dockerfile文件是可以的。但是build一次需要三四分钟，调试有点费劲。如果可能的话，希望大佬可以加一个docker的制作流程，我今天弄了一天了，还没彻底解决。如果有一个railway的快速调试教程，可能会提高一部分想给这个项目做贡献的开发者的效率，谢谢。

**Comment by lanvent** [comment]
railway本来就是这么慢的，删除一些依赖可能会快点，我推荐你本地开发，railway仅适用于部署

**Comment by Zhaoyi-Yan** [comment]
主要是现在本地挂代理：requests.exceptions.SSLError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1682422693399&skey=%40crypt_b7f672f3_8dea04be57b8f83f187f10cd926f66fd&sid=e0nj%2B8siqab3VGwd&uin=1192860923&deviceid=e148468101986699&synckey=1_790452392%7C2_790452595%7C3_790452585%7C11_790452366%7C19_33004%7C23_1682422649%7C24_1682422655%7C27_2346%7C201_1682422655%7C206_103%7C1000_1682421481%7C1001_1682408461&_=1682422647905 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
就会出现这个问题。即使是“smart”模式，不是global模式。不知道咋解决

**Comment by lanvent** [comment]
根据搜索引擎的回复，你需要```pip install urllib3==1.25.11```

**Comment by Zhaoyi-Yan** [comment]
终于可以了。。原来是包的问题，一直以为是微信屏蔽的问题。感谢帮忙完美解决。

**Comment by alexhmyang** [comment]
> 

我现在 改了代码 删了 dockerfile 后 railway build报错呀 安装依赖就出问题了
