### ISSUE TITLE
给个人微信号发送消息，在服务器端能收到query，但没有reply

### ISSUE THREAD

**Issue by yintao-he** [zhayujie/chatgpt-on-wechat#953]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

按照readme配置，

### 问题描述 😯

给个人微信号发送消息，在服务器端能收到query，但没有reply。

[INFO][2023-04-25 17:25:20][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-04-25 17:25:20][chat_gpt_bot.py:48] - [CHATGPT] query=测试
[INFO][2023-04-25 17:25:39][chat_gpt_bot.py:48] - [CHATGPT] query=测试
[INFO][2023-04-25 17:25:49][chat_gpt_bot.py:48] - [CHATGPT] query=你好
[INFO][2023-04-25 17:27:01][chat_gpt_bot.py:48] - [CHATGPT] query=你怎么不说话呢

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by yintao-he** [comment]
已解决，在发送消息10分钟后显示：[WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络)，说明是网络问题

**Comment by lanvent** [comment]
一般可发送#help这类指令测试，是否能回复
