### ISSUE TITLE
morningnew初始化失败

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#958]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

<img width="592" alt="image" src="https://user-images.githubusercontent.com/31379908/234448202-afaa96b1-c1a3-4efa-8651-2c19c81f6cc5.png">

tool文件夹里json已经加入了key，尝试过把zao_bao_key改成morning_news_api_key 也是不行

**Comment by lanvent** [comment]
see https://github.com/zhayujie/chatgpt-on-wechat/pull/957
