### ISSUE TITLE
本地部署运行成功，但经常会出现"[ERROR]我连接不到你的网络“

### ISSUE THREAD

**Issue by ErvineWang** [zhayujie/chatgpt-on-wechat#961]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

在本地部署运行成功，但发送消息后经常会出现"[ERROR]我连接不到你的网络“，出现频率很高，本地机器上使用局部代理。

### 终端日志 📒

[WARNING][2023-04-26 10:20:30][chat_gpt_bot.py:137] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[INFO][2023-04-26 10:20:30][wechat_channel.py:196] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@a1390e1d141718f792bf71709b6d9df1

**Comment by lanvent** [comment]
代理问题吧

**Comment by MGeorge01** [comment]
开全局代理就能解决

**Comment by monk-after-90s** [comment]
看看后台是不是启动了多个程序实例
