### ISSUE TITLE
$tool bing-search 使用问题

### ISSUE THREAD

**Issue by taoguoliang** [zhayujie/chatgpt-on-wechat#963]
### 前置确认

- [x] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

``` java
$tool 使用bing告诉我今日北京天气
``` 
打印了一堆日志，使用了bing又使用meteo-weather最后回答的毫不相干。
![image](https://user-images.githubusercontent.com/28913539/234479889-d4386f5c-0b2b-43e7-9592-73795fa24a56.png)

### 终端日志 📒

[INFO][2023-04-26 13:37:05][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-04-26 13:37:06][victorinox.py:111] - 提问: 使用bing告诉我今日北京天气
[INFO][2023-04-26 13:37:15][base.py:226] - LLM-OS的内心独白: 推理：用户需要获取今日北京的天气信息，可以使用bing-search来搜索相关信息
思考：使用bing告诉我今日北京天气
反思：如果用户需要更详细的天气信息，可能需要使用meteo-weather工具
[INFO][2023-04-26 13:37:15][base.py:177] - 执行Tool: bing-search中...
[INFO][2023-04-26 13:37:15][base.py:115] - 输入: 今日北京天气
[INFO][2023-04-26 13:37:15][tool_engine.py:134] - 我将给工具发送如下信息: 
今日北京天气
[WARNING][2023-04-26 13:37:17][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[WARNING][2023-04-26 13:37:17][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[INFO][2023-04-26 13:37:17][tool_engine.py:163] - 工具 bing-search 返回内容: 北京天气预报，及时准确发布中央气象台天气信息，便捷查询北京今日天气，北京周末天气，北京一周天气预报，北京蓝天预报，北京天气预报，北京40日天气预报，还提供北京的生活指数、健康指数、交通指数、旅游指数，及时发布北京气象预警信号、各类气象资讯。
 北京市 北京天气 预报 省份： 城市： 日出 北京 日落 降水量 相对湿度 体感温度 ... 制作维护：国家气象中心预报系统开放实验室 地址：北京市中关村南大街46号 邮编：100081 京公网安备 11040102700100 ...
[INFO][2023-04-26 13:37:17][tool_engine.py:193] - 我从[bing-search]中获得了一些信息：
'北京天气预报，及时准确发布中央气象台天气信息，便捷查询北京今日天气，北京周末天气，北京一周天气预报，北京蓝天预报，北京天气预报，北京40日天气预报，还提供北京的生活指数、健康指数、交通指数、旅游指数，及时发布北京气象预警信号、各类气象资讯。\n 北京市 北京天气 预报 省份： 城市： 日出 北京 日落 降水量 相对湿度 体感温度 ... 制作维护：国家气象中心预报系统开放实验室 地址：北京市中关村南大街46号 邮编：100081 京公网安备 11040102700100 ...'
[INFO][2023-04-26 13:37:25][base.py:226] - LLM-OS的内心独白: 推理：用户可能需要更详细的天气信息，可以使用meteo-weather工具
思考：使用meteo-weather获取今日北京天气信息
反思：如果用户只需要简单的天气信息，可以使用bing-search工具
[INFO][2023-04-26 13:37:25][base.py:177] - 执行Tool: meteo-weather中...
[INFO][2023-04-26 13:37:25][base.py:115] - 输入: 今日北京天气按时
[INFO][2023-04-26 13:37:25][tool_engine.py:134] - 我将给工具发送如下信息: 
今日北京天气按时
[INFO][2023-04-26 13:37:29][base.py:77] - URL 构造: https://api.open-meteo.com/v1/forecast?latitude=39.9042&longitude=116.4074&hourly=temperature_2m&timezone=Asia/Shanghai&start_date=2023-04-26&end_date=2023-04-26
[INFO][2023-04-26 13:37:31][base.py:87] - API 响应: '{"latitude":39.875,"longitude":116.375,"generationtime_ms":0.10597705841064453,"utc_offset_seconds":28800,"timezone":"Asia/Shanghai","timezone_abbreviation":"CST","elevation":47.0,"hourly_units":{"time":"iso8601","temperature_2m":"°C"},"hourly":{"time":["2023-04-26T00:00","2023-04-26T01:00","2023-04-26T02:00","2023-04-26T03:00","2023-04-26T04:00","2023-04-26T05:00","2023-04-26T06:00","2023-04-26T07:00","2023-04-26T08:00","2023-04-26T09:00","2023-04-26T10:00","2023-04-26T11:00","2023-04-26T12:00","2023-04-26T13:00","2023-04-26T14:00","2023-04-26T15:00","2023-04-26T16:00","2023-04-26T17:00","2023-04-26T18:00","2023-04-26T19:00","2023-04-26T20:00","2023-04-26T21:00","2023-04-26T22:00","2023-04-26T23:00"],"temperature_2m":[11.8,11.7,10.3,9.7,8.6,7.8,7.5,8.5,10.8,13.2,15.7,17.3,17.8,18.5,19.4,19.5,19.3,19.2,18.9,18.2,16.9,16.1,15.8,15.5]}}'
[INFO][2023-04-26 13:37:43][tool_engine.py:163] - 工具 meteo-weather 返回内容: 根据API文档提供的信息，我们可以使用以下API URL来获取北京市今日的天气情况：
https://api.open-meteo.com/v1/forecast?latitude=39.9042&longitude=116.4074&hourly=temperature_2m&timezone=Asia/Shanghai&start_date=2023-04-26&end_date=2023-04-26
该API URL中包含了必要的参数，如经纬度、时区和日期等，以确保我们获取到的是北京市今日的天气情况。通过API的响应结果，我们可以看到北京市今日的每个小时的气温情况，其中包括了13:00时刻的气温数据。因此，根据API提供的数据，北京市13:00时刻的气温为18.5°C。
[INFO][2023-04-26 13:37:43][tool_engine.py:193] - 我从[meteo-weather]中获得了一些信息：
'根据API文档提供的信息，我们可以使用以下API URL来获取北京市今日的天气情况：\n\nhttps://api.open-meteo.com/v1/forecast?latitude=39.9042&longitude=116.4074&hourly=temperature_2m&timezone=Asia/Shanghai&start_date=2023-04-26&end_date=2023-04-26\n\n该API URL中包含了必要的参数，如经纬度、时区和日期等，以确保我们获取到的是北京市今日的天气情况。通过API的响应结果，我们可以看到北京市今日的每个小时的气温情况，其中包括了13:00时刻的气温数据。因此，根据API提供的数据，北京市13:00时刻的气温为18.5°C。'
[WARNING][2023-04-26 13:37:43][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-eL6FjMa9QsAd2IdlcHO8ImO0 on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
[INFO][2023-04-26 13:38:04][base.py:226] - LLM-OS的内心独白: 推理：用户可能需要获取特定网站的内容，需要进一步确认
思考：请问用户需要获取哪个网站的内容？
反思：如果用户只是需要一般的网站内容，可以使用url-get工具
[INFO][2023-04-26 13:38:04][base.py:115] - 输入: 请问用户需要获取哪个网站的内容？
[INFO][2023-04-26 13:38:05][wechat_channel.py:193] - [WX] sendMsg=Reply(type=TEXT, content=[bot] 请问用户需要获取哪个网站的内容？)

**Comment by lanvent** [comment]
反馈至https://github.com/goldfishh/chatgpt-tool-hub吧，这里可能看不到

**Comment by goldfishh** [comment]
你用bing-search并没有返回有用信息
meteo是专门查询天气的，你可以直接用它
现在chatgpt有幻觉，会默认它返回的中间内容用户已经搜到
所以chatgpt会默认你看到如下信息：
```text
[INFO][2023-04-26 13:37:43][tool_engine.py:193] - 我从[meteo-weather]中获得了一些信息：
'根据API文档提供的信息，我们可以使用以下API URL来获取北京市今日的天气情况：\n\nhttps://api.open-meteo.com/v1/forecast?latitude=39.9042&longitude=116.4074&hourly=temperature_2m&timezone=Asia/Shanghai&start_date=2023-04-26&end_date=2023-04-26\n\n该API URL中包含了必要的参数，如经纬度、时区和日期等，以确保我们获取到的是北京市今日的天气情况。通过API的响应结果，我们可以看到北京市今日的每个小时的气温情况，其中包括了13:00时刻的气温数据。因此，根据API提供的数据，北京市13:00时刻的气温为18.5°C。'
```
但是由于你之前指定了很奇怪的工具并且返回了无用的信息，所以chatgpt最后询问你
```text
[INFO][2023-04-26 13:38:04][base.py:226] - LLM-OS的内心独白: 推理：用户可能需要获取特定网站的内容，需要进一步确认
思考：请问用户需要获取哪个网站的内容？
反思：如果用户只是需要一般的网站内容，可以使用url-get工具
```
你在这里需要做的事情是怎么和模型更好的沟通。

**Comment by goldfishh** [comment]
你用bing-search并没有返回有用信息
meteo是专门查询天气的，你可以直接用它
现在chatgpt有幻觉，会默认它返回的中间内容用户已经搜到
所以chatgpt会默认你看到如下信息：
```text
[INFO][2023-04-26 13:37:43][tool_engine.py:193] - 我从[meteo-weather]中获得了一些信息：
'根据API文档提供的信息，我们可以使用以下API URL来获取北京市今日的天气情况：\n\nhttps://api.open-meteo.com/v1/forecast?latitude=39.9042&longitude=116.4074&hourly=temperature_2m&timezone=Asia/Shanghai&start_date=2023-04-26&end_date=2023-04-26\n\n该API URL中包含了必要的参数，如经纬度、时区和日期等，以确保我们获取到的是北京市今日的天气情况。通过API的响应结果，我们可以看到北京市今日的每个小时的气温情况，其中包括了13:00时刻的气温数据。因此，根据API提供的数据，北京市13:00时刻的气温为18.5°C。'
```
但是由于你之前指定了很奇怪的工具并且返回了无用的信息，所以chatgpt最后询问你
```text
[INFO][2023-04-26 13:38:04][base.py:226] - LLM-OS的内心独白: 推理：用户可能需要获取特定网站的内容，需要进一步确认
思考：请问用户需要获取哪个网站的内容？
反思：如果用户只是需要一般的网站内容，可以使用url-get工具
```
你在这里需要做的事情是怎么和模型更好的沟通。
