### ISSUE TITLE
Railway运行登陆成功,但是消息不回复

### ISSUE THREAD

**Issue by China-ZYW** [zhayujie/chatgpt-on-wechat#964]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

Railway运行登陆成功,但是消息不回复

### 问题描述 😯

Railway运行登陆成功,但是消息不回复

### 终端日志 📒

[Warning] You need to set OPEN_AI_API_KEY before running!
[INFO][2023-04-26 08:08:01][config.py:176] - [INIT] load config: {'open_ai_api_key': 'YOUR API KEY', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': ['bot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'group_chat_in_one_session': ['ChatGPT测试群'], 'image_create_prefix': ['画', '看', '找'], 'speech_recognition': False, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}
[INFO][2023-04-26 08:08:01][config.py:126] - [Config] User datas file not found, ignore.
█
[INFO][2023-04-26 08:08:03][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-04-26 08:08:03][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-04-26 08:08:03][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-04-26 08:08:03][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-04-26 08:08:03][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
chatgpt-tool-hub version: 0.4.1
[INFO][2023-04-26 08:08:04][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-04-26 08:08:04][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-04-26 08:08:04][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-04-26 08:08:04][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-04-26 08:08:04][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-04-26 08:08:04][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin GODCMD not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin KEYWORD not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin BANWORDS not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin TOOL not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin ROLE not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin DUNGEON not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin BDUNIT not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin HELLO not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][plugin_manager.py:101] - Plugin FINISH not found in pconfig, adding to pconfig...
[INFO][2023-04-26 08:08:04][godcmd.py:181] - [Godcmd] 因未设置口令，本次的临时口令为6283。
[INFO][2023-04-26 08:08:04][godcmd.py:196] - [Godcmd] inited
[INFO][2023-04-26 08:08:04][keyword.py:40] - [keyword] {}
[INFO][2023-04-26 08:08:04][keyword.py:42] - [keyword] inited.
[WARNING][2023-04-26 08:08:04][banwords.py:53] - [Banwords] init failed, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[ERROR][2023-04-26 08:08:04][plugin_manager.py:126] - Failed to init BANWORDS, diabled. [Errno 2] No such file or directory: '/app/plugins/banwords/banwords.txt'
[WARNING][2023-04-26 08:08:04][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[INFO][2023-04-26 08:08:04][load_tools.py:51] - [morning-news] init failed, error_info: ValueError('Did not find zaobao_api_key, please add an environment variable `ZAOBAO_API_KEY` which contains it, or pass  `zaobao_api_key` as a named parameter.')
[INFO][2023-04-26 08:08:04][load_tools.py:51] - [news-api] init failed, error_info: ValueError('Did not find news_api_key, please add an environment variable `NEWS_API_KEY` which contains it, or pass  `news_api_key` as a named parameter.')
[WARNING][2023-04-26 08:08:04][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[WARNING][2023-04-26 08:08:04][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[INFO][2023-04-26 08:08:04][victorinox.py:41] - use_tools=['url-get', 'news', 'meteo-weather', 'terminal', 'python'], params: {'debug': False, 'openai_api_key': 'YOUR API KEY', 'proxy': '', 'request_timeout': 120, 'model_name': 'gpt-3.5-turbo', 'no_default': False, 'top_k_results': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_host': '', 'wolfram_alpha_appid': '', 'zaobao_api_key': '', 'cuda_device': 'cpu'}
[INFO][2023-04-26 08:08:04][tool.py:32] - [tool] inited
[INFO][2023-04-26 08:08:04][role.py:69] - [Role] inited
[INFO][2023-04-26 08:08:04][dungeon.py:56] - [Dungeon] inited
[WARNING][2023-04-26 08:08:04][bdunit.py:47] - [BDunit] init failed, ignore
[ERROR][2023-04-26 08:08:04][plugin_manager.py:126] - Failed to init BDUNIT, diabled. config.json not found
[INFO][2023-04-26 08:08:04][hello.py:23] - [Hello] inited
[INFO][2023-04-26 08:08:04][finish.py:23] - [Finish] inited
Getting uuid of QR code.
Downloading QR code.
You can also scan QRCode in any website below:
https://api.pwmqr.com/qrcode/create/?url=https://login.weixin.qq.com/l/YYxga2lQsQ==
https://my.tv.sohu.com/user/a/wvideo/getQRCode.do?text=https://login.weixin.qq.com/l/YYxga2lQsQ==
https://api.qrserver.com/v1/create-qr-code/?size=400×400&data=https://login.weixin.qq.com/l/YYxga2lQsQ==
https://api.isoyu.com/qr/?m=1&e=L&p=20&url=https://login.weixin.qq.com/l/YYxga2lQsQ==
█▀▀▀▀▀▀▀█▀▀▀███▀▀▀█████▀▀▀▀▀▀▀█
█ █▀▀▀█ ██ ▄ █▄██▀▀ ▄██ █▀▀▀█ █
█ █   █ █ ▄██ ▀▄ █▀▀█▄█ █   █ █
█ ▀▀▀▀▀ █ █▀▄▀▄ █ ▄▀▄ █ ▀▀▀▀▀ █
█▀███▀█▀▀ ▄▄█▄█▄▄▄ █▄ ▀▀▀▀▀██▀█
█▄▀▀ █▀▀▀█▄▀▄█ █ ▄█▄█▄█▄▄▄▄▄▄ █
█▀ ▄█ ▄▀▄█▄█▀▀▀▄██ ▄▄ ▄█▄▄▄█ ▄█
██ ▀ ▄ ▀   ▄▀▀▄█  ▄ █▀█▄▄   ▄ █
█ ▀█▄█▀▀ ▀█ ▄▀█    ▄█▀ █████ ▄█
█▄▄▀▀██▀▀▀▀▀▀ █▀ ▄  ██▄ ▄ ▄▀▄ █
█▀▀▀▀▀▀▀ █ ██▄█     █▀▀▀▀ ▀█▄ █
█▀▀▀▀▀▀▀█ ▀  ▀█▀▀▄▄ ▀ █▀█ ▀▀█ █
█ █▀▀▀█ █▀ ▀▀▀▀    ▄  ▀▀▀ ▀█▄▀█
█ █   █ ██▄▀▄█▄▄▀▄  █  ███▀▀▀ █
█ ▀▀▀▀▀ █▀█▄ ▄▄█▀█ ▀█ ▀▄ █ █ ▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 南瓜一号
[INFO][2023-04-26 08:08:51][wechat_channel.py:133] - Wechat login success, user_id: @1a9b423b33425c3f32d86fdbe0791394e2d05e88815393025512d0e31c7217d0, nickname: 南瓜一号
Start auto replying.

**Comment by China-ZYW** [comment]
直接@的机器人


指南
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] Railway运行登陆成功,但是消息不回复 (Issue #964)





 
有没有加触发词

**Comment by lanvent** [comment]
群在白名单里？

**Comment by China-ZYW** [comment]
我是通过环境变量重载的,请求一下,不知道这样对不对





指南
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] Railway运行登陆成功,但是消息不回复 (Issue #964)





 
群在白名单里？

**Comment by Treessss** [comment]
同样的问题

**Comment by lanvent** [comment]
你可以增加环境变量debug=true ，私聊机器人如果显示收到了消息，就说明网络是正常的，接下来你只需要检查自己的触发设置和白名单

**Comment by zhaotailang123** [comment]
同遇到问题，私聊没问题，但是群聊没有任何反应

**Comment by China-ZYW** [comment]
我已经解决,是因为环境变量的格式问题






指南
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhayujie/chatgpt-on-wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhayujie/chatgpt-on-wechat] Railway运行登陆成功,但是消息不回复 (Issue #964)





 
同遇到问题，私聊没问题，但是群聊没有任何反应

**Comment by Treessss** [comment]
[INFO][2023-04-27 02:13:22][chat_gpt_bot.py:48] - [CHATGPT] query=这是什么
[DEBUG][2023-04-27 02:13:22][session_manager.py:70] - prompt tokens used=137
[DEBUG][2023-04-27 02:13:22][chat_gpt_bot.py:65] - [CHATGPT] session query=[{'role': 'system', 'content': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}, {'role': 'user', 'content': '你是谁'}, {'role': 'assistant', 'content': '我是ChatGPT，一个由OpenAI训练的大型语言模型，旨在回答并解决人们的各种问题，并可以使用多种语言进行交流。'}, {'role': 'user', 'content': '这是什么'}]
[DEBUG][2023-04-27 02:13:25][chat_gpt_bot.py:74] - [CHATGPT] new_query=[{'role': 'system', 'content': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}, {'role': 'user', 'content': '你是谁'}, {'role': 'assistant', 'content': '我是ChatGPT，一个由OpenAI训练的大型语言模型，旨在回答并解决人们的各种问题，并可以使用多种语言进行交流。'}, {'role': 'user', 'content': '这是什么'}], session_id=@1348a75e6c032d1426693b27e72be731, reply_cont=这是一个AI语言模型，可以进行自然语言处理(NLP)和自然语言生成(NLG)任务，通过学习大量的数据和算法，能够与人类进行对话，并提供有意义的回答和建议。, completion_tokens=65
[DEBUG][2023-04-27 02:13:25][session_manager.py:81] - raw total_tokens=202, savesession tokens=207
[DEBUG][2023-04-27 02:13:25][chat_channel.py:145] - [WX] ready to decorate reply: Reply(type=TEXT, content=这是一个AI语言模型，可以进行自然语言处理(NLP)和自然语言生成(NLG)任务，通过学习大量的数据和算法，能够与人类进行对话，并提供有意义的回答和建议。)
[DEBUG][2023-04-27 02:13:25][chat_channel.py:246] - [WX] ready to send reply: Reply(type=TEXT, content=bot这是一个AI语言模型，可以进行自然语言处理(NLP)和自然语言生成(NLG)任务，通过学习大量的数据和算法，能够与人类进行对话，并提供有意义的回答和建议。), context: Context(type=TEXT, content=这是什么, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WeChatMessage object at 0x7fbab9e71d20>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': '@1348a75e6c032d1426693b27e72be731', 'receiver': '@1348a75e6c032d1426693b27e72be731'})
[INFO][2023-04-27 02:13:25][wechat_channel.py:193] - [WX] sendMsg=Reply(type=TEXT, content=bot这是一个AI语言模型，可以进行自然语言处理(NLP)和自然语言生成(NLG)任务，通过学习大量的数据和算法，能够与人类进行对话，并提供有意义的回答和建议。), receiver=@1348a75e6c032d1426693b27e72be731
[DEBUG][2023-04-27 02:13:25][chat_channel.py:262] - Worker return success, session_id = @1348a75e6c032d1426693b27e72be731

开了debug  日志如上   还是接收不到信息
