### ISSUE TITLE
使用meteo weather过程中，触发bug

### ISSUE THREAD

**Issue by GgQqCc** [zhayujie/chatgpt-on-wechat#965]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

$tool  meteo 今日西安天气

### 问题描述 😯

无法正确返回天气信息。

### 终端日志 📒

Login successfully as bot
[INFO][2023-04-26 17:01:57][wechat_channel.py:133] - Wechat login success, user_id: @efcc886ee2fe4eb3c7b79cc73053641e2afd90b06eab6894df6dba3e9dc0de1e, nickname: bot
Start auto replying.
[INFO][2023-04-26 17:02:17][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-04-26 17:02:17][victorinox.py:111] - 提问: meteo 今日西安天气
[INFO][2023-04-26 17:02:28][base.py:226] - LLM-OS的内心独白: 推理：用户输入中包含了“meteo”这个词，可以猜测用户想要查询天气信息。同时，用户明确指出了查询的时间是今日，地点是西安。
思考：用户想要查询今日西安的天气信息
反思：我需要确认一下用户想要查询的是今天的天气，而不是其他时间的天气信息。

[INFO][2023-04-26 17:02:28][base.py:177] - 执行Tool: meteo-weather中...
[INFO][2023-04-26 17:02:28][base.py:115] - 输入: 今天西安的天气
[INFO][2023-04-26 17:02:28][tool_engine.py:134] - 我将给工具发送如下信息: 
今天西安的天气
[INFO][2023-04-26 17:02:35][base.py:77] - URL 构造: https://api.open-meteo.com/v1/forecast?latitude=34.27&longitude=108.95&hourly=temperature_2m,cloudcover,precipitation,snowfall,rain,weathercode,windspeed_10m,snow_depth,visibility&current_weather=true&temperature_unit=celsius&timeformat=iso8601&timezone=Asia/Shanghai&past_days=0
[INFO][2023-04-26 17:02:37][base.py:87] - API 响应: '{"latitude":34.25,"longitude":109.0,"generationtime_ms":0.9160041809082031,"utc_offset_seconds":28800,"timezone":"Asia/Shanghai","timezone_abbreviation":"CST","elevation":406.0,"current_weather":{"temperature":25.3,"windspeed":8.7,"winddirection":30.0,"weathercode":1,"is_day":1,"time":"2023-04-26T17:00"},"hourly_units":{"time":"iso8601","temperature_2m":"°C","cloudcover":"%","precipitation":"mm","snowfall":"cm","rain":"mm","weathercode":"wmo code","windspeed_10m":"km/h","snow_depth":"m","visibility":"m"},"hourly":{"time":["2023-04-26T00:00","2023-04-26T01:00","2023-04-26T02:00","2023-04-26T03:00","2023-04-26T04:00","2023-04-26T05:00","2023-04-26T06:00","2023-04-26T07:00","2023-04-26T08:00","2023-04-26T09:00","2023-04-26T10:00","2023-04-26T11:00","2023-04-26T12:00","2023-04-26T13:00","2023-04-26T14:00","2023-04-26T15:00","2023-04-26T16:00","2023-04-26T17:00","2023-04-26T18:00","2023-04-26T19:00","2023-04-26T20:00","2023-04-26T21:00","2023-04-26T22:00","2023-04-26T23:00","2023-04-27T00:00","2023-04-27T01:00","2023-04-27T02:00","2023-04-27T03:00","2023-04-27T04:00","2023-04-27T05:00","2023-04-27T06:00","2023-04-27T07:00","2023-04-27T08:00","2023-04-27T09:00","2023-04-27T10:00","2023-04-27T11:00","2023-04-27T12:00","2023-04-27T13:00","2023-04-27T14:00","2023-04-27T15:00","2023-04-27T16:00","2023-04-27T17:00","2023-04-27T18:00","2023-04-27T19:00","2023-04-27T20:00","2023-04-27T21:00","2023-04-27T22:00","2023-04-27T23:00","2023-04-28T00:00","2023-04-28T01:00","2023-04-28T02:00","2023-04-28T03:00","2023-04-28T04:00","2023-04-28T05:00","2023-04-28T06:00","2023-04-28T07:00","2023-04-28T08:00","2023-04-28T09:00","2023-04-28T10:00","2023-04-28T11:00","2023-04-28T12:00","2023-04-28T13:00","2023-04-28T14:00","2023-04-28T15:00","2023-04-28T16:00","2023-04-28T17:00","2023-04-28T18:00","2023-04-28T19:00","2023-04-28T20:00","2023-04-28T21:00","2023-04-28T22:00","2023-04-28T23:00","2023-04-29T00:00","2023-04-29T01:00","2023-04-29T02:00","2023-04-29T03:00","2023-04-29T04:00","2023-04-29T05:00","2023-04-29T06:00","2023-04-29T07:00","2023-04-29T08:00","2023-04-29T09:00","2023-04-29T10:00","2023-04-29T11:00","2023-04-29T12:00","2023-04-29T13:00","2023-04-29T14:00","2023-04-29T15:00","2023-04-29T16:00","2023-04-29T17:00","2023-04-29T18:00","2023-04-29T19:00","2023-04-29T20:00","2023-04-29T21:00","2023-04-29T22:00","2023-04-29T23:00","2023-04-30T00:00","2023-04-30T01:00","2023-04-30T02:00","2023-04-30T03:00","2023-04-30T04:00","2023-04-30T05:00","2023-04-30T06:00","2023-04-30T07:00","2023-04-30T08:00","2023-04-30T09:00","2023-04-30T10:00","2023-04-30T11:00","2023-04-30T12:00","2023-04-30T13:00","2023-04-30T14:00","2023-04-30T15:00","2023-04-30T16:00","2023-04-30T17:00","2023-04-30T18:00","2023-04-30T19:00","2023-04-30T20:00","2023-04-30T21:00","2023-04-30T22:00","2023-04-30T23:00","2023-05-01T00:00","2023-05-01T01:00","2023-05-01T02:00","2023-05-01T03:00","2023-05-01T04:00","2023-05-01T05:00","2023-05-01T06:00","2023-05-01T07:00","2023-05-01T08:00","2023-05-01T09:00","2023-05-01T10:00","2023-05-01T11:00","2023-05-01T12:00","2023-05-01T13:00","2023-05-01T14:00","2023-05-01T15:00","2023-05-01T16:00","2023-05-01T17:00","2023-05-01T18:00","2023-05-01T19:00","2023-05-01T20:00","2023-05-01T21:00","2023-05-01T22:00","2023-05-01T23:00","2023-05-02T00:00","2023-05-02T01:00","2023-05-02T02:00","2023-05-02T03:00","2023-05-02T04:00","2023-05-02T05:00","2023-05-02T06:00","2023-05-02T07:00","2023-05-02T08:00","2023-05-02T09:00","2023-05-02T10:00","2023-05-02T11:00","2023-05-02T12:00","2023-05-02T13:00","2023-05-02T14:00","2023-05-02T15:00","2023-05-02T16:00","2023-05-02T17:00","2023-05-02T18:00","2023-05-02T19:00","2023-05-02T20:00","2023-05-02T21:00","2023-05-02T22:00","2023-05-02T23:00"],"temperature_2m":[13.7,12.9,11.9,11.0,10.0,9.3,8.7,8.8,12.1,16.6,18.6,20.6,22.5,23.9,24.7,25.1,25.4,25.3,24.8,23.2,20.7,18.7,17.7,16.9,16.1,15.5,15.1,14.4,13.3,12.6,11.7,11.5,13.8,17.9,19.4,21.5,23.4,24.7,25.7,26.3,26.3,25.6,24.6,22.7,18.0,17.6,16.9,16.5,16.2,15.6,15.4,15.2,14.9,14.4,13.8,13.8,15.3,16.9,18.6,20.4,21.9,22.7,23.3,23.7,23.2,22.4,21.1,19.7,18.3,17.3,16.0,14.3,13.3,12.2,11.2,10.5,10.1,9.5,9.0,9.0,10.6,12.7,14.9,16.5,17.6,18.6,19.4,20.0,20.5,20.4,19.5,18.0,15.9,14.2,12.5,10.6,9.6,9.0,8.3,7.7,7.1,6.9,7.4,8.2,10.2,12.5,15.5,19.0,20.9,22.5,24.0,24.7,25.0,24.7,23.6,22.1,19.8,18.1,16.3,14.2,13.1,12.3,11.5,10.8,10.1,10.0,10.5,11.5,13.9,17.2,21.4,25.8,27.1,27.3,27.0,26.5,25.8,24.6,23.6,22.6,21.2,20.2,19.2,18.1,17.4,16.9,16.2,15.7,15.1,14.8,14.9,15.3,16.5,18.4,20.8,23.7,25.1,26.2,27.1,27.5,27.6,27.3,26.6,25.5,24.1,23.3,22.6,21.7],"cloudcover":[0,0,0,0,0,0,0,23,0,0,0,0,5,6,6,6,7,8,10,43,100,0,0,0,12,92,13,3,0,0,0,24,0,0,0,0,0,0,0,9,92,94,100,100,100,100,100,100,100,100,100,100,59,89,100,100,100,100,100,67,79,100,89,100,100,100,100,100,100,100,100,100,100,100,7,3,9,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,9,13,9,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,11,17,14,10,7,5,2,0,5,10,15,42,70,97,93,90,86,88,91,93,91,89,87,91,96,100,100,100,100,100,100,100,79,58,37,58,79,100,100,100,100,100,100,100,100,100,100],"precipitation":[0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.50,0.10,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00],"snowfall":[0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00],"rain":[0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.40,0.10,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00],"weathercode":[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,1,3,0,0,0,1,3,1,0,0,0,0,1,0,0,0,0,0,0,0,1,3,3,3,3,61,61,3,3,3,3,3,3,2,3,3,3,3,3,3,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3],"windspeed_10m":[7.9,7.0,5.1,4.3,3.8,4.4,4.4,4.0,3.2,5.5,8.4,8.4,8.5,8.9,10.8,10.9,10.6,8.7,6.9,4.6,4.7,6.4,7.5,6.7,6.4,6.9,6.2,4.2,3.7,3.4,3.6,3.4,1.3,4.5,4.6,3.4,5.1,6.8,7.5,5.8,7.0,8.0,7.2,10.2,14.5,3.7,3.5,5.5,8.0,7.1,7.1,5.6,5.4,4.5,4.3,4.0,3.8,5.2,9.0,11.5,12.1,10.7,11.0,12.6,13.0,12.4,22.8,18.0,9.0,10.3,7.9,7.6,7.9,8.1,7.1,6.3,6.5,5.2,4.1,3.6,4.1,6.7,10.2,11.0,10.1,8.0,4.8,1.6,2.2,5.4,5.9,4.9,3.8,3.6,3.8,4.7,4.9,4.7,4.7,5.1,5.6,5.9,5.9,5.1,3.8,1.8,2.6,5.4,6.5,7.3,8.1,9.4,11.5,12.5,11.2,8.4,5.1,3.6,2.9,3.7,3.9,4.0,3.9,3.9,3.7,3.2,2.5,2.4,3.3,4.5,6.2,6.8,3.1,5.4,11.1,9.7,5.6,3.0,4.3,5.6,6.9,7.4,7.7,7.2,6.4,5.7,4.9,4.6,4.2,3.7,3.2,2.4,1.8,2.3,4.6,7.5,9.4,11.4,13.2,13.1,12.5,10.9,9.5,8.4,7.9,8.0,8.6,8.2],"snow_depth":[0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00],"visibility":[24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,9400.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00,24140.00]}}'
**[ERROR][2023-04-26 17:02:38][victorinox.py:114] - [APP] catch a Exception: This model's maximum context length is 4097 tokens. However, your messages resulted in 7997 tokens. Please reduce the length of the messages.**

**Comment by lanvent** [comment]
反馈至https://github.com/goldfishh/chatgpt-tool-hub 吧，这里可能看不到

**Comment by goldfishh** [comment]
api输出内容太多了，这个用<del>gpt-4可以解决</del>
我去研究一下它们的文档
