### ISSUE TITLE
希望能支持Azure的DallE

### ISSUE THREAD

**Issue by hellangleZ** [zhayujie/chatgpt-on-wechat#966]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

能使用azure dalle来支持画图

### 举例

[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin SUMMARY triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][chat_channel.py:161] - [WX] ready to handle context: type=IMAGE_CREATE, content=横版 高清 二次元:cat
[INFO][2023-04-26 17:19:39][open_ai_image.py:22] - [OPEN_AI] image_query=横版 高清 二次元:cat
error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False
[ERROR][2023-04-26 17:19:41][open_ai_image.py:40] - Resource not found
Traceback (most recent call last):
  File "/aml/jupyter/chatgpt-on-wechat/bot/openai/open_ai_image.py", line 23, in create_img
    response = openai.Image.create(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_resources/image.py", line 36, in create
    response, _, api_key = requestor.request(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
[DEBUG][2023-04-26 17:19:41][chat_channel.py:145] - [WX] ready to decorate reply: Reply(type=ERROR, content=Resource not found)
[DEBUG][2023-04-26 17:19:41][chat_channel.py:246] - [WX] ready to send reply: Reply(type=ERROR, content=[ERROR]
Resource not found), context: Context(type=IMAGE_CREATE, content=横版 高清 二次元:cat, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7f2d0ffb7310>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': '@40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975', 'receiver': '@40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975'})
[INFO][2023-04-26 17:19:41][wechat_channel.py:196] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
Resource not found), receiver=@40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975
[DEBUG][2023-04-26 17:19:41][chat_channel.py:262] - Worker return success, session_id = @40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975

### 动机

可以提供更多的方案

**Comment by lanvent** [comment]
我昨天以为你是要提PR。。我们当前没有账号来测试，可以借用你的配置来测试下吗，仅用于测试目的。

**Comment by hellangleZ** [comment]
> 我昨天以为你是要提PR。。我们当前没有账号来测试，可以借用你的配置来测试下吗，仅用于测试目的。

可以，我怎么给你方便

**Comment by lanvent** [comment]
发送到我的邮箱就行，邮箱在我的个人主页

**Comment by hellangleZ** [comment]
> 发送到我的邮箱就行，邮箱在我的个人主页

已发送

**Comment by lanvent** [comment]
我看了，目前azure不支持调用dall-e api

**Comment by hellangleZ** [comment]
> 我看了，目前azure不支持调用dall-e api

感谢支持，我看了一下是url的问题，我发你一个我可以load出来的code，您看是否可以有机会集成，因为我把你的create_image的代码方法改了一下，老师报错，似乎我的http header有个字段和你的代码不兼容

代码如下：
import requests
import time
import os
api_base = 'https://a-wxf.openai.azure.com/'
api_key = ""
api_version = '2022-08-03-preview'
url = "{}dalle/text-to-image?api-version={}".format(api_base, api_version)
headers= { "api-key": api_key, "Content-Type": "application/json" }
body = {
    "caption": "画一匹狼",
    "resolution": "1024x1024"
}
submission = requests.post(url, headers=headers, json=body)
operation_location = submission.headers['Operation-Location']
retry_after = submission.headers['Retry-after']
status = ""
while (status != "Succeeded"):
    time.sleep(int(retry_after))
    response = requests.get(operation_location, headers=headers)
    
    status = response.json()['status']
image_url = response.json()['result']['contentUrl']

然后print出来这个image_url 是可以看到图片的

**Comment by lanvent** [comment]
为啥我没在azure上找到关于这个的说明呢，你是在哪里看到具体api文档的

**Comment by hellangleZ** [comment]
> 为啥我没在azure上找到关于这个的说明呢，你是在哪里看到具体api文档的

这个差不到，是我从azure的人那问的，api写的特别怪，目前我代入到chat_bot下面的open_ai_image里是不工作的，可能返回得对象有问题

**Comment by lanvent** [comment]
已支持

**Comment by hellangleZ** [comment]
> 已支持

好的，我实验一下

**Comment by hellangleZ** [comment]
> > 已支持
> 
> 好的，我实验一下 

@lanvent 已成功,  也看到兄弟你改的两端代码，多谢了

大大的赞

**Comment by OliverSunWH** [comment]
@hellangleZ 请教一下，已经设置了azure的api可以文字回复，现在想要应用Azure的DallE模型画图，是需要在config中修改什么吗，我直接尝试画图失败了，能否给我看下您的config设置？感谢

**Comment by hellangleZ** [comment]
> @hellangleZ 请教一下，已经设置了azure的api可以文字回复，现在想要应用Azure的DallE模型画图，是需要在config中修改什么吗，我直接尝试画图失败了，能否给我看下您的config设置？感谢

下新代码就可以了，楼主改了chatbot 和open_ai_image俩面的2个代码

**Comment by OliverSunWH** [comment]
> > @hellangleZ 请教一下，已经设置了azure的api可以文字回复，现在想要应用Azure的DallE模型画图，是需要在config中修改什么吗，我直接尝试画图失败了，能否给我看下您的config设置？感谢
> 
> 下新代码就可以了，楼主改了chatbot 和open_ai_image俩面的2个代码

已经更新了，但是还是如下报错
![image](https://user-images.githubusercontent.com/58762800/235040535-a4d1888a-e625-4667-b989-9402efe50d45.png)

我的config是这样配置的
![image](https://user-images.githubusercontent.com/58762800/235040800-d540766a-dd47-467e-bd67-987c0d15f985.png)

方便的话可以加个联系方式请教一下吗，wx：swh52647035

**Comment by hellangleZ** [comment]
> > > @hellangleZ 请教一下，已经设置了azure的api可以文字回复，现在想要应用Azure的DallE模型画图，是需要在config中修改什么吗，我直接尝试画图失败了，能否给我看下您的config设置？感谢
> > 
> > 
> > 下新代码就可以了，楼主改了chatbot 和open_ai_image俩面的2个代码
> 
> 已经更新了，但是还是如下报错 ![image](https://user-images.githubusercontent.com/58762800/235040535-a4d1888a-e625-4667-b989-9402efe50d45.png)
> 
> 我的config是这样配置的 ![image](https://user-images.githubusercontent.com/58762800/235040800-d540766a-dd47-467e-bd67-987c0d15f985.png)
> 

你modele name是错的
![image](https://user-images.githubusercontent.com/15274284/235041313-0091fd64-ced5-4437-b8b6-bfabe942bfb0.png)

**Comment by OliverSunWH** [comment]
> > > > @hellangleZ 请教一下，已经设置了azure的api可以文字回复，现在想要应用Azure的DallE模型画图，是需要在config中修改什么吗，我直接尝试画图失败了，能否给我看下您的config设置？感谢
> > > 
> > > 
> > > 下新代码就可以了，楼主改了chatbot 和open_ai_image俩面的2个代码
> > 
> > 
> > 已经更新了，但是还是如下报错 ![image](https://user-images.githubusercontent.com/58762800/235040535-a4d1888a-e625-4667-b989-9402efe50d45.png)
> > 我的config是这样配置的 ![image](https://user-images.githubusercontent.com/58762800/235040800-d540766a-dd47-467e-bd67-987c0d15f985.png)
> 
> 你modele name是错的 ![image](https://user-images.githubusercontent.com/15274284/235041313-0091fd64-ced5-4437-b8b6-bfabe942bfb0.png)

修改model name后，发送“画一只小猫"命令，仍然报错create image error: 'operation-location'，请问您是直接用类似命令画的吗？

**Comment by lanvent** [comment]
不好意思，拉一下最新代码吧，我没有改base

**Comment by OliverSunWH** [comment]
> 不好意思，拉一下最新代码吧，我没有改base

已成功，谢谢大佬

**Comment by cbaoox** [comment]
> > 不好意思，拉一下最新代码吧，我没有改base
> 
> 已成功，谢谢大佬

可以贴下怎么处理成功的吗，我遇到同样的问题

**Comment by cbaoox** [comment]
> > > > > @hellangleZ 请教一下，已经设置了azure的api可以文字回复，现在想要应用Azure的DallE模型画图，是需要在config中修改什么吗，我直接尝试画图失败了，能否给我看下您的config设置？感谢
> > > > 
> > > > 
> > > > 下新代码就可以了，楼主改了chatbot 和open_ai_image俩面的2个代码
> > > 
> > > 
> > > 已经更新了，但是还是如下报错 ![image](https://user-images.githubusercontent.com/58762800/235040535-a4d1888a-e625-4667-b989-9402efe50d45.png)
> > > 我的config是这样配置的 ![image](https://user-images.githubusercontent.com/58762800/235040800-d540766a-dd47-467e-bd67-987c0d15f985.png)
> > 
> > 
> > 你modele name是错的 ![image](https://user-images.githubusercontent.com/15274284/235041313-0091fd64-ced5-4437-b8b6-bfabe942bfb0.png)
> 
> 修改model name后，发送“画一只小猫"命令，仍然报错create image error: 'operation-location'，请问您是直接用类似命令画的吗？

同样的错误，如何解决的？可否给些提示呢
