### ISSUE TITLE
确认stable diffusion AI正确启动可以web访问，但是启动webui插件，发现报错找不到source

### ISSUE THREAD

**Issue by hellangleZ** [zhayujie/chatgpt-on-wechat#967]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

启动stable defussuin 然后正常加载插件，无法识别

![image](https://user-images.githubusercontent.com/15274284/234655114-41795a87-15fe-4254-9461-f4c404debbaf.png)

### 问题描述 😯

![1682530086744](https://user-images.githubusercontent.com/15274284/234655528-afd30f33-f316-489c-989f-c619718a8667.png)

### 终端日志 📒

```log
<此处粘贴终端日志>
```
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin SUMMARY triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][plugin_manager.py:163] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2023-04-26 17:19:39][chat_channel.py:161] - [WX] ready to handle context: type=IMAGE_CREATE, content=横版 高清 二次元:cat
[INFO][2023-04-26 17:19:39][open_ai_image.py:22] - [OPEN_AI] image_query=横版 高清 二次元:cat
error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False
[ERROR][2023-04-26 17:19:41][open_ai_image.py:40] - Resource not found
Traceback (most recent call last):
  File "/aml/jupyter/chatgpt-on-wechat/bot/openai/open_ai_image.py", line 23, in create_img
    response = openai.Image.create(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_resources/image.py", line 36, in create
    response, _, api_key = requestor.request(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
[DEBUG][2023-04-26 17:19:41][chat_channel.py:145] - [WX] ready to decorate reply: Reply(type=ERROR, content=Resource not found)
[DEBUG][2023-04-26 17:19:41][chat_channel.py:246] - [WX] ready to send reply: Reply(type=ERROR, content=[ERROR]
Resource not found), context: Context(type=IMAGE_CREATE, content=横版 高清 二次元:cat, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7f2d0ffb7310>, 'origin_ctype': <ContextType.TEXT: 1>, 'session_id': '@40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975', 'receiver': '@40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975'})
[INFO][2023-04-26 17:19:41][wechat_channel.py:196] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
Resource not found), receiver=@40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975
[DEBUG][2023-04-26 17:19:41][chat_channel.py:262] - Worker return success, session_id = @40889e2d513114cf425dd3882a688a3a47073f996fc84bd59d15cab7faa9e975

**Comment by lanvent** [comment]
你的LOG中sdwebui插件没有被触发，检查一下是否开启了插件

**Comment by hellangleZ** [comment]
![image](https://user-images.githubusercontent.com/15274284/234661927-6d342735-c602-42c7-b8a0-38efee1d417e.png)
真的是未启用，请问为什么没拉起来？

**Comment by lanvent** [comment]
启用下，看看log报什么错

**Comment by hellangleZ** [comment]
> 启用下，看看log报什么错

启动的log里看不出来哪错了啊

python app.py
[DEBUG][2023-04-26 18:03:36][config.py:193] - [INIT] set log level to DEBUG
[INFO][2023-04-26 18:03:36][config.py:195] - [INIT] load config: {'use_azure_chatgpt': True, 'open_ai_api_base': 'https://a-wxf.openai.azure.com/', 'open_ai_api_key': 'e95a5d7e4ef74f65b239743f244508fc', 'model': 'gpt-35-turbo', 'azure_deployment_id': 'gpt', 'image_create_prefix': ['画', '看', '找'], 'speech_recognition': True, 'group_speech_recognition': True, 'voice_reply_voice': False, 'always_reply_voice': False, 'voice_to_text': 'azure', 'text_to_voice': 'azure', 'azure_voice_api_key': '0a7d5143616c42cb8ba4f8d3e5f778da', 'azure_voice_region': 'eastus', 'single_chat_prefix': ['bot', 'b', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['RBQ', '机器人'], 'group_name_white_list': ['ALL_GROUP'], 'group_chat_in_one_session': ['ALL_GROUP'], 'plugin_trigger_prefix': '$', 'debug': True, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}
[INFO][2023-04-26 18:03:36][config.py:143] - [Config] User datas loaded.
[INFO][2023-04-26 18:03:36][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-04-26 18:03:36][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[INFO][2023-04-26 18:03:36][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
chatgpt-tool-hub version: 0.4.3
[INFO][2023-04-26 18:03:37][plugin_manager.py:41] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-04-26 18:03:37][plugin_manager.py:41] - Plugin summary_v0.3 registered, path=./plugins/plugin_summary
[INFO][2023-04-26 18:03:37][plugin_manager.py:41] - Plugin sdwebui_v2.0 registered, path=./plugins/plugin_sdwebui
[DEBUG][2023-04-26 18:03:37][plugin_manager.py:153] - plugins.json config={'plugins': SortedDict({'Godcmd': {'enabled': True, 'priority': 999}, 'Keyword': {'enabled': True, 'priority': 900}, 'Banwords': {'enabled': False, 'priority': 100}, 'tool': {'enabled': True, 'priority': 0}, 'sdwebui': {'enabled': False, 'priority': 0}, 'Role': {'enabled': True, 'priority': 0}, 'Dungeon': {'enabled': True, 'priority': 0}, 'BDunit': {'enabled': False, 'priority': 0}, 'summary': {'enabled': True, 'priority': -1}, 'Hello': {'enabled': True, 'priority': -1}, 'Finish': {'enabled': True, 'priority': -999}}, sort_func=<lambda>, reverse=True)}
[INFO][2023-04-26 18:03:37][godcmd.py:196] - [Godcmd] inited
[DEBUG][2023-04-26 18:03:37][keyword.py:34] - [keyword]加载配置文件/aml/jupyter/chatgpt-on-wechat/plugins/keyword/config.json
[INFO][2023-04-26 18:03:37][keyword.py:40] - [keyword] {}
[INFO][2023-04-26 18:03:37][keyword.py:42] - [keyword] inited.
[WARNING][2023-04-26 18:03:39][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[WARNING][2023-04-26 18:03:39][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[INFO][2023-04-26 18:03:39][victorinox.py:86] - use_tools=['python', 'url-get', 'terminal', 'meteo-weather'], params: {'debug': False, 'openai_api_key': 'e95a5d7e4ef74f65b239743f244508fc', 'open_ai_api_base': 'https://a-wxf.openai.azure.com/', 'proxy': '', 'request_timeout': 120, 'model_name': 'gpt-3.5-turbo', 'no_default': False, 'top_k_results': 2, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning_news_api_key': '', 'cuda_device': 'cpu'}
[INFO][2023-04-26 18:03:39][tool.py:32] - [tool] inited
[DEBUG][2023-04-26 18:03:39][role.py:62] - [Role] no role found for tag comments 
[INFO][2023-04-26 18:03:39][role.py:69] - [Role] inited
[INFO][2023-04-26 18:03:39][dungeon.py:56] - [Dungeon] inited
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (0, 'sessionid', 'TEXT', 0, None, 1)
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (1, 'msgid', 'INTEGER', 0, None, 2)
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (2, 'user', 'TEXT', 0, None, 0)
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (3, 'content', 'TEXT', 0, None, 0)
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (4, 'type', 'TEXT', 0, None, 0)
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (5, 'timestamp', 'INTEGER', 0, None, 0)
[DEBUG][2023-04-26 18:03:39][main.py:70] - [Summary] column: (6, 'is_triggered', 'INTEGER', 0, None, 0)
[INFO][2023-04-26 18:03:39][main.py:86] - [Summary] inited
[INFO][2023-04-26 18:03:39][hello.py:23] - [Hello] inited
[INFO][2023-04-26 18:03:39][finish.py:23] - [Finish] inited
Getting uuid of QR code.

**Comment by hellangleZ** [comment]
![image](https://user-images.githubusercontent.com/15274284/234664840-e74e6e2e-b5b9-4901-8dbd-d69d5c2b6282.png)
但是godcmd确实显示没启用

**Comment by lanvent** [comment]
你需要#enablep sdwebui

**Comment by hellangleZ** [comment]
> 你需要#enablep sdwebui

多谢，已经可以了，感谢支持
![1682550935474](https://user-images.githubusercontent.com/15274284/234722367-c0f6414c-d250-433a-bd8c-777395c00490.png)

**Comment by Eason0831** [comment]
这个需要API吗，为什么我的启用了，但用不了
[ERROR][2023-07-08 01:29:35][sdwebui.py:119] - [SD] exception: HTTPConnectionPool(host='127.0.0.1', port=7860): Max retries exceeded with url: /sdapi/v1/options (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001993CEBFCD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
