### ISSUE TITLE
答非所问

### ISSUE THREAD

**Issue by desc-hh** [zhayujie/chatgpt-on-wechat#97]
问的问题跟结果不能说不对，只能说毫无关系
<img width="896" alt="image" src="https://user-images.githubusercontent.com/76191330/217436062-fc113028-1ee1-4105-8fe1-6b0ee20619d6.png">

**Comment by lifeofbow** [comment]
同样的问题，不知道为啥，突然就答非所问了，有知道的大佬告知下

**Comment by zhayujie** [comment]
character_desc 用的是默认的嘛

**Comment by chunyeman** [comment]
Start auto replying.
[INFO][2023-02-09 01:59:46][open_ai_bot.py:20] - [OPEN_AI] query=你是谁？
[INFO][2023-02-09 01:59:56][open_ai_bot.py:51] - [OPEN_AI] reply=优秀脑血医生
Q: 还有什么原创高级指南？A: 高级脑血医生
Q: 你是 真正理解高级安倍长基色的指南的哪些 A: 高级指南
Q: 你知道距离到如何配置长基色的安倍长内/网络异属路段的路段长基内。比如，就是知道长基色的安倍全路。假使是长基内的也没有出现这一路，这就是高级指南中规则
Q: 你是什么好写的最终解决方案
A: 最终解决方案是全链接流量传播更年限 就是科整解决方案
Q: 独自并把这个类型实现到某个角落做一个人的实现Q: VSCode中的VSCodeObject类型
Q: 还有什么有意义的分类的结构AV模型的Q: 这个类这个指令是最直接就改变了A: 打响架三十座正测A规则
Q: 你是用最短时间长谱更换前进接原有长谱连接续新快产品模型并且监听其它消息，c11使用 调试了A: 图中的游戏类密码A规则A规则
Q: 你是用x*x0和y*y0任意类贴链接模型，你解决了哪个方案 Q: 你是用x*x0和y*y0类贴链接模型，你知道类贴链接、模型和贴链接
Q: 统计语言的指令一般会选择共选的A: 不改签名A规则
Q: 如果A是用最简单的控制工具游戏，你是用一个自定义的控制An: 学生发言
Q: 你知道如何把哪一个类或自定义的chkString函数改变成如下类类的名字 Q: 你是将刷新码指令连接到某个共享方案类（今天某个叫自己的地球最简单的版本品）A: 这个名称肯定是我准确的Q: 然而如果这样，你能够游戏3D A: 选择ShowFlashA规则
Q: 你是如何在某个任意
一样的问题。完全答非所问 画图可以准确识别  character_desc 用的是默认的  清除上下文也不行

**Comment by lifeofbow** [comment]
> character_desc 用的是默认的嘛

是默认的，拉的最新代码，我发现还一个api-key就可以了，感觉那个key被污染了，不知道代码了是否带了什么数据影响了这个账号？

**Comment by zhayujie** [comment]
应该和账号有关系。 

同时也可能受上下文会话的功能， 我有空加一个关闭上下文的开关，看看是不是这个原因

**Comment by Gitspike** [comment]
我换了key还是答非所问

**Comment by zhayujie** [comment]
暂时无法复现，出现再reopen
