### ISSUE TITLE
Railway部署后，看不到生成的任何本地内容，除了日志。

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [zhayujie/chatgpt-on-wechat#972]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

这就尴尬了，我看本地还能看到user_datas.pkl之类的，railway上只能看到日志了

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
没看明白

**Comment by Zhaoyi-Yan** [comment]
就是railway官网的界面，只能看到日志吧。比如，我代码里存一些数据，怎么找到相应的目录，下载到本地呢

**Comment by lanvent** [comment]
railway不支持
