### ISSUE TITLE
Exception: We could not parse the JSON body of your request.

### ISSUE THREAD

**Issue by BilkerRoger** [zhayujie/chatgpt-on-wechat#975]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

发送任何消息都是相同的回复

### 问题描述 😯

![cut](https://user-images.githubusercontent.com/49360109/234799733-51d66614-e616-408f-8c42-e5264c62f123.png)

### 终端日志 📒

```log
Login successfully as Cc
[INFO][2023-04-27 15:51:06][wechat_channel.py:133] - Wechat login success, user_id: @be965b238f70e2d90f573b33c11d6fa1b1a71e9661cf9b046fc61881a48b073a, nickname: Cc
Start auto replying.
[INFO][2023-04-27 15:51:15][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-04-27 15:51:15][chat_gpt_bot.py:48] - [CHATGPT] query=讲个笑话
[WARNING][2023-04-27 15:51:16][chat_gpt_bot.py:141] - [CHATGPT] Exception: We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to support@openai.com and include any relevant code you'd like help with.)
[INFO][2023-04-27 15:51:16][wechat_channel.py:196] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@250889394a55efa18f74f13821f663f39fe40dc3e4e1ab3354f8153882e0f34c
```

**Comment by lanvent** [comment]
```pip install -r requirements.txt``` 运行了吗

```
pip show openai
pip show requests
pip show urllib3
```
看看版本

**Comment by BilkerRoger** [comment]
requirements.txt和requirements-optional.txt都安装了，能正常启动然后微信扫码登录，之后发送任何消息就都是报错了
![version](https://user-images.githubusercontent.com/49360109/234811741-4efd5862-3070-4a4c-934b-fa346c9794e4.png)

**Comment by BilkerRoger** [comment]
我升级了上面三个库，现在启动之后扫完码会报错
![error](https://user-images.githubusercontent.com/49360109/234813464-d7ef31a6-3e08-46d9-92d1-c1b625dc0cee.png)
