### ISSUE TITLE
#set_openai_api_key 指令无效

### ISSUE THREAD

**Issue by taoguoliang** [zhayujie/chatgpt-on-wechat#979]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

#set_openai_api_key 指令无效，还是使用之前的key

**Comment by lanvent** [comment]
目前这个还只在公众号上支持，我等会会把其他channel都加进去。要注意的是：因为itchat上每次登录用户id都会变，所以重启后之前的配置就失效了，在想比较好的方法解决。

**Comment by lanvent** [comment]
fixed
