### ISSUE TITLE
大佬们，现在tool更新了llmos后，问问题后他自己的操作使得答案变得不太精准了

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#980]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

@goldfishh 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/31379908/234873224-596eea84-f6a6-4829-a740-718c5ce1a83a.png">

**Comment by goldfishh** [comment]
pull最新代码
在tool插件config.json的kwargs设置think_depth为1再试一试
