### ISSUE TITLE
summary插件，总是：无聊天记录可供总结

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#984]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

summary插件，总是：无聊天记录可供总结，railway已经挂着9小时了

![image](https://user-images.githubusercontent.com/31379908/235042380-89df090d-a748-4245-8d8e-d16c0bd5a6c3.png)

触发语和回复我撤回了

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by lanvent** [comment]
缺少log
