### ISSUE TITLE
summary插件报错

### ISSUE THREAD

**Issue by Maddaxman** [zhayujie/chatgpt-on-wechat#987]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

<img width="880" alt="image" src="https://user-images.githubusercontent.com/31379908/235051123-8fa3a150-55fa-4955-8158-0e75af6e828c.png">

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by goldfishh** [comment]
用url-get或browser工具输出会自动使用summary, 如果你要主动使用summary 你要确保传入一个本地文件路径和一个数字（总结前N行），这块我还没测试。
目前summary都是自动使用的

**Comment by lanvent** [comment]
打印summary插件的帮助，能够发现的事实是：使用自然语言发出命令，那中间不应该存在空格。不过，我刚刚顺手兼容了存在空格的情况，你可以更新下它

**Comment by Maddaxman** [comment]
> 打印summary插件的帮助，能够发现的事实是：使用自然语言发出命令，那中间不应该存在空格。不过，我刚刚顺手兼容了存在空格的情况，你可以更新下它

@lanvent git pull 项目还是更新summary插件

**Comment by Maddaxman** [comment]
懂了
