### ISSUE TITLE
竟然不支持docker吗？

### ISSUE THREAD

**Issue by kilvn** [zhayujie/chatgpt-on-wechat#99]

**Comment by dobzhao** [comment]
git clone之后，编辑好config.json，然后创建一个Dockerfile，内容如下：
```
FROM python:3.9.16
RUN pip3 install itchat-uos==1.5.0.dev0 && pip3 install --upgrade openai
WORKDIR /home
ADD . .
CMD python3 app.py
```

接下来
```bash
docker build -t chatgpt-on-wechat .
docker run -d --name chatgpt-on-wechat chatgpt-on-wechat
docker logs -f chatgpt-on-wechat
```

**Comment by dobzhao** [comment]
希望大家在提issue的时候更加尊重贡献者，增加特性和维护dockerhub会都需要时间和精力，不要说得理所应当。

**Comment by dobzhao** [comment]
学习了，写好yaml提PR会更有帮助
________________________________
发件人: 东子 ***@***.***>
发送时间: Wednesday, February 8, 2023 10:03:17 PM
收件人: zhayujie/chatgpt-on-wechat ***@***.***>
抄送: dobzhao ***@***.***>; Comment ***@***.***>
主题: Re: [zhayujie/chatgpt-on-wechat] 竟然不支持docker吗？ (Issue #99)


可以了解下 github actions 自动构建 dockerhub，就一个 workflow，主要是方便，一劳永逸配置好了不用再管，每次 push 或者发 release 他会自动构建发 dockerhub，我是这个意思。

―

**Comment by zhayujie** [comment]
暂时先关闭了， 后面恢复了再支持docker
