### ISSUE TITLE
多个apiKEY 随机调用

### ISSUE THREAD

**Issue by ooweigan** [zhayujie/chatgpt-on-wechat#991]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

我有多个apikey ，需要每个用户在群里唤醒gpt的时候随机分配一个apikey 并创建聊天机器人

**Comment by hk59775634** [comment]
github有多key的项目库。自己搭建一个私人api服务。可以放多key

**Comment by lanvent** [comment]
在计划中
