### ISSUE TITLE
扫码登录成功了，但是一直自动回复‘我现在有点累了，等会再来吧’

### ISSUE THREAD

**Issue by codezjun** [zhayujie/chatgpt-on-wechat#993]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码登录成功了，提示了Start auto replying。但是一直回复的是‘我现在有点累了，等会再来吧’

### 终端日志 📒

![企业微信截图_16826721558884](https://user-images.githubusercontent.com/30564611/235103416-c3712f19-6441-4357-b89f-1478fcbb9366.png)

**Comment by pulangxi** [comment]
我也是
我以前可以的

**Comment by flysky2000000** [comment]
那不写了，key错了吗？
他现在有的账号，是不给额度了，不是所有的账号，都有一点免费的了
所以不花钱，有的账号本身开了key也不好使，顺便说一下，plus和这个好像还没关系，我2号一个是plus但是生成的key都不好使
但是另外一个花钱了，生成的key就好使

**Comment by Rubiadragon** [comment]
我的api是新的，也是出现这样的情况
