### ISSUE TITLE
启动服务后二维码一直会变是怎么回事？

### ISSUE THREAD

**Issue by leyno** [zhayujie/chatgpt-on-wechat#994]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

![image](https://user-images.githubusercontent.com/13057786/235104086-e0c05b85-d5b5-4a86-9507-30e9845a7e5f.png)
启动服务后二维码一直变

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by Maddaxman** [comment]
你没有扫，不扫不登进去过期了就会刷新

**Comment by leyno** [comment]
但是这个二维码刷新的特别快
