### ISSUE TITLE
proxy no find, directly request to chatgpt instead

### ISSUE THREAD

**Issue by leyno** [zhayujie/chatgpt-on-wechat#995]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

![image](https://user-images.githubusercontent.com/13057786/235107807-e5cf4a40-1236-4000-81cd-6e1858140008.png)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
可以直接访问openai的话不用设置代理，如需设置代理，在项目根目录config文件配置proxy项目

**Comment by liaolongdong** [comment]
为什么我可以直接访问openai，也没有设置proxy，也一样报这个错误？
