### ISSUE TITLE
修改了config文件，还是无法识别插件

### ISSUE THREAD

**Issue by banping957** [zhayujie/chatgpt-on-wechat#997]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

这是一个能让chatgpt联网，搜索，数字运算的插件，将赋予强大且丰富的扩展能力。
使用说明：
$tool 命令: 根据给出的{命令}使用一些可用工具尽力为你得到结果。
$tool reset: 重置工具。

已加载工具列表: 
terminal, meteo-weather, python, url-get), receiver=@f70dbb70290120c7ecaeea25f2456fb4548a09d81e3d89881acadd556350638c

tool 里config文件
{
  "tools": [
    "python",
    "url-get",
    "terminal",
    "meteo-weather",
    "news",
    "wolfram-alpha",
    "summary",
    "arxiv",
    "wikipedia"
  ],
  "kwargs": {
    "top_k_results": 2,
    "no_default": true,
    "model_name": "gpt-3.5-turbo",
    "news_api_key": "e7ba21369752448bb97c80d2c1b9e59c",
    "wolfram_alpha_appid": "Y9AGPK-WH97YWEQ9H"
  }
}
~                  

### 问题描述 😯

我在plugins/tool里对config.json.template进行了修改，改成了上面的文件，但是我调出插件配置时，怎么没有识别这些插件

**Comment by Maddaxman** [comment]
要复制一份config.json.template副本，改成config.json，在里面修改

**Comment by banping957** [comment]
我加上去了，但是不知道因为什么现在#help不识别命令了

**Comment by banping957** [comment]
发生了什么，命令都识别不到
[INFO][2023-04-29 11:29:15][chat_gpt_bot.py:49] - [CHATGPT] query=#help tool
[INFO][2023-04-29 11:29:17][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[chris] Hello! How can I assist you today?), receiver=@2258b21b8f3f99f2902006bc2eb85cc025167d66f847612280c7d0140a87c1ac
[INFO][2023-04-29 11:32:53][chat_gpt_bot.py:49] - [CHATGPT] query=#plist
[INFO][2023-04-29 11:32:55][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[chris] 抱歉，我不理解您的请求，请提供更多细节或信息，让我更好地理解您的需求。), receiver=@2258b21b8f3f99f2902006bc2eb85cc025167d66f847612280c7d0140a87c1ac

**Comment by lanvent** [comment]
查看`plugins/plugins.json`看`Godcmd`插件有没有开启
