### ISSUE TITLE
ARM服务器上通过docker-compose部署报错

### ISSUE THREAD

**Issue by zhitaozeng** [zhayujie/chatgpt-on-wechat#998]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在arm机器上，执行部署流程，运行docker-compose后报错，报错信息如下：
`#5 53.03 Failed to build pysilk_mod
#5 53.03 ERROR: Could not build wheels for pysilk_mod, which is required to install pyproject.toml-based projects
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c apt-get update      && apt-get install -y --no-install-recommends         wget         curl      && rm -rf /var/lib/apt/lists/*     && export BUILD_GITHUB_TAG=${CHATGPT_ON_WECHAT_VER:-`curl -sL \"https://api.github.com/repos/zhayujie/chatgpt-on-wechat/releases/latest\" |         grep '\"tag_name\":' |         sed -E 's/.*\"([^\"]+)\".*/\\1/'`}     && wget -t 3 -T 30 -nv -O chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz             https://github.com/zhayujie/chatgpt-on-wechat/archive/refs/tags/${BUILD_GITHUB_TAG}.tar.gz     && tar -xzf chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz     && mv chatgpt-on-wechat-${BUILD_GITHUB_TAG} ${BUILD_PREFIX}     && rm chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz     && cd ${BUILD_PREFIX}     && cp config-template.json ${BUILD_PREFIX}/config.json     && /usr/local/bin/python -m pip install --no-cache --upgrade pip     && pip install --no-cache -r requirements.txt     && pip install --no-cache -r requirements-optional.txt" did not complete successfully: exit code: 1
`

### 问题描述 😯

错误信息：
#5 53.03 Failed to build pysilk_mod
#5 53.03 ERROR: Could not build wheels for pysilk_mod, which is required to install pyproject.toml-based projects
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c apt-get update      && apt-get install -y --no-install-recommends         wget         curl      && rm -rf /var/lib/apt/lists/*     && export BUILD_GITHUB_TAG=${CHATGPT_ON_WECHAT_VER:-`curl -sL \"https://api.github.com/repos/zhayujie/chatgpt-on-wechat/releases/latest\" |         grep '\"tag_name\":' |         sed -E 's/.*\"([^\"]+)\".*/\\1/'`}     && wget -t 3 -T 30 -nv -O chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz             https://github.com/zhayujie/chatgpt-on-wechat/archive/refs/tags/${BUILD_GITHUB_TAG}.tar.gz     && tar -xzf chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz     && mv chatgpt-on-wechat-${BUILD_GITHUB_TAG} ${BUILD_PREFIX}     && rm chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz     && cd ${BUILD_PREFIX}     && cp config-template.json ${BUILD_PREFIX}/config.json     && /usr/local/bin/python -m pip install --no-cache --upgrade pip     && pip install --no-cache -r requirements.txt     && pip install --no-cache -r requirements-optional.txt" did not complete successfully: exit code: 1

### 终端日志 📒

#5 53.03 Failed to build pysilk_mod
#5 53.03 ERROR: Could not build wheels for pysilk_mod, which is required to install pyproject.toml-based projects
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c apt-get update      && apt-get install -y --no-install-recommends         wget         curl      && rm -rf /var/lib/apt/lists/*     && export BUILD_GITHUB_TAG=${CHATGPT_ON_WECHAT_VER:-`curl -sL \"https://api.github.com/repos/zhayujie/chatgpt-on-wechat/releases/latest\" |         grep '\"tag_name\":' |         sed -E 's/.*\"([^\"]+)\".*/\\1/'`}     && wget -t 3 -T 30 -nv -O chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz             https://github.com/zhayujie/chatgpt-on-wechat/archive/refs/tags/${BUILD_GITHUB_TAG}.tar.gz     && tar -xzf chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz     && mv chatgpt-on-wechat-${BUILD_GITHUB_TAG} ${BUILD_PREFIX}     && rm chatgpt-on-wechat-${BUILD_GITHUB_TAG}.tar.gz     && cd ${BUILD_PREFIX}     && cp config-template.json ${BUILD_PREFIX}/config.json     && /usr/local/bin/python -m pip install --no-cache --upgrade pip     && pip install --no-cache -r requirements.txt     && pip install --no-cache -r requirements-optional.txt" did not complete successfully: exit code: 1

**Comment by superlyy** [comment]
遇到了类似的问题，目前是通过[源码](https://github.com/DCZYewen/Python-Silk-Module)安装解决

**Comment by lanvent** [comment]
注释掉相关依赖项再试
